### ISSUE TITLE
Letv - 无法获取标题

### ISSUE THREAD

**Issue by N46AN** [soimort/you-get#1000]
```
$ python3 you-get --debug http://www.le.com/ptv/vplay/24902320.html
Current Video Supports:
        --format 1000 <URL>
        --format 350 <URL>
        --format 720p <URL>
        --format 1300 <URL>
Site:       Le.com
you-get: version 0.4.350, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/24902320.html']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "src/you_get/common.py", line 1266, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "src/you_get/common.py", line 1179, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "src/you_get/common.py", line 1027, in download_main
    download(url, **kwargs)
  File "src/you_get/common.py", line 1259, in any_download
    m.download(url, **kwargs)
  File "src/you_get/extractors/le.py", line 137, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "src/you_get/extractors/le.py", line 96, in letv_download_by_vid
    print_info(site_info, title, ext, size)
  File "src/you_get/common.py", line 962, in print_info
    maybe_print("Title:     ", unescape_html(tr(title)))
  File "/usr/lib/python3.5/html/__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by baoyankun** [comment]
貌似是因为无法正确获取标题，研究一下

**Comment by baoyankun** [comment]
通过将目前 extractors/le.py 第 138 行修改为
```
letv_download_by_vid(vid, title='tmp-2016', output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
```
强行指定 title='tmp-2016'，暂时绕过了这个问题。
至于为何无法获取标题，边下载边继续研究

**Comment by ERioK** [comment]
这个视频实际是在sports.letv.com下的，代码里的获取标题方式不适用，需要修改

**Comment by baoyankun** [comment]
> 这个视频实际是在sports.letv.com下的，代码里的获取标题方式不适用，需要修改
果然将 le.py 137 行改为
```
        if match1(url, r'http://sports.letv.com/video/(\d+).html') is not None:
		    title = match1(html,r'name="keywords" content="(.*?)"')
        else:
            title = match1(html,r'name="irTitle" content="(.*?)"')
```
并在前面增加
```
            match1(url, r'http://sports.letv.com/video/(\d+).html') or \
```
之后，可以正确获取 http://sports.letv.com/video/(\d+).html 的标题了

**Comment by soimort** [comment]
@soimort-bot test this: http://www.le.com/ptv/vplay/24902320.html

**Comment by soimort** [comment]
本地机则是DNS解析不了。

```console
$ you-get -di http://www.le.com/ptv/vplay/24902320.html 
[DEBUG] get_content: http://www.le.com/ptv/vplay/24902320.html
you-get: version 0.4.364, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/24902320.html']
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/soimort/Projects/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractors/le.py", line 132, in letv_download
    html = get_content(url)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 308, in get_content
    response = request.urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

请求Pull Request。

**Comment by N46AN** [comment]
@soimort 您好，刚才试用发现还有类似问题，其他用户的报告 #1421 
请问是要我来发起 pull request 吗？
