### ISSUE TITLE
文件名里有单引号时合并失败

### ISSUE THREAD

**Issue by weijarz** [soimort/you-get#1009]
```
[animations]$ you-get -d 'http://www.tudou.com/albumplay/DL4UVIcjx3w/m4uV5hUvMlU.html'
site:                优酷 (Youku)
title:               03 THE BIG RED CHICKEN'S MAGIC SHOW
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          90.4 MiB (94763019 bytes)
    # download-with: you-get --format=mp4 [URL]

Downloading 03 THE BIG RED CHICKEN'S MAGIC SHOW.mp4 ...
 100% ( 90.4/ 90.4MB) ├████████████████████████████████████████████████████████████████████████████████████████┤[4/4]  157 MB/s
Merging video parts... you-get: version 0.4.350, a tiny downloader that scrapes the web.
you-get: ['http://www.tudou.com/albumplay/DL4UVIcjx3w/m4uV5hUvMlU.html']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.350', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1266, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1179, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1027, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1259, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractors/tudou.py", line 46, in tudou_download
    return youku_download_by_vid(vcode, title=title, output_dir=output_dir, merge=merge, info_only=info_only, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractor.py", line 70, in download_by_vid
    self.download(**kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractor.py", line 207, in download
    av=stream_id in self.dash_streams)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 759, in download_urls
    ffmpeg_concat_mp4_to_mp4(parts, output_filepath)
  File "/usr/lib/python3.5/site-packages/you_get/processor/ffmpeg.py", line 173, in ffmpeg_concat_mp4_to_mp4
    subprocess.check_call(params)
  File "/usr/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ffmpeg', '-loglevel', 'quiet', '-f', 'concat', '-y', '-i', "./03 THE BIG RED CHICKEN'S MAGIC SHOW.mp4.txt", '-c', 'copy', "./03 THE BIG RED CHICKEN'S MAGIC SHOW.mp4"]' returned non-zero exit status 1
```

所有文件名里带单引号的都会合并失败。
比如这个集里面 [动漫:爱探险的朵拉 第六季](http://www.tudou.com/albumcover/DL4UVIcjx3w.html) 大量文件名都有单引号。

**Comment by soimort** [comment]
Weird, I thought this was fixed in #496.

Thanks for the report.
