### ISSUE TITLE
斗鱼是失效了吗？没有任何返回

### ISSUE THREAD

**Issue by binai** [soimort/you-get#1010]
```
% you-get -i http://www.douyu.com/xiaocang                     
 ~
% you-get --debug http://www.douyu.com/xiaocang              
 ~
%     
```
斗鱼上没有任何返回值，是失效了吗？

**Comment by linhua55** [comment]
这不是正确的视频地址

**Comment by botusun** [comment]
#1011 斗鱼换了新的域名，之前为 douyutv.com 现在为 douyu.com

**Comment by kevinbakbak** [comment]
用douyutv.com这个域名

**Comment by binai** [comment]
并不能用到douyutv.com这个域名，会跳到douyu.com

**Comment by kevinbakbak** [comment]
@binai 主页我这也跳了...不过在个人中心就好了，以下是其他方法 @zhangn1985 下次更新进去呗？
https://github.com/soimort/you-get/issues/914#issuecomment-182903083

**Comment by soimort** [comment]
不管是 douyutv.com 还是 douyu.com，我这边都是DNS解析不能。

@soimort-bot test this: http://www.douyu.com/xiaocang

**Comment by soimort** [comment]
@soimort-bot test this: http://www.douyutv.com/xiaocang

**Comment by soimort** [comment]
看起来douyu最近抽风。

等他的域名稳定下来我再更新吧。

**Comment by kevinbakbak** [comment]
你们测试的时候确认他是否在开播吗？。。。。。@soimort-bot 和你错误信息一样。
但是我去这个地址去看了下，人下直播了啊=。=
以下我随意试了一个链接
you-get -di http://www.douyutv.com/12313
Site:       douyutv.com
Title:      叶音符：中单皇子，杀人只需一秒。
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

@soimort 你再试试？。。

**Comment by soimort** [comment]
> @soimort 你再试试？。。

DNS 解析不了，换了 Google DNS 也不行。

```console
$ you-get -di http://www.douyutv.com/12313
you-get: version 0.4.364, a tiny downloader that scrapes the web.
you-get: ['http://www.douyutv.com/12313']
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/soimort/Projects/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractors/douyutv.py", line 16, in douyutv_download
    content = get_html(json_request_url)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 271, in get_html
    content = get_response(url, faker).data
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 259, in get_response
    response = request.urlopen(url)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

@soimort-bot Test http://www.douyutv.com/12313 again.

**Comment by soimort** [comment]
因为根本没法访问，所以我也不知道他是否在开播啊 :disappointed:

**Comment by kevinbakbak** [comment]
@soimort 我这里douyu.tv早就不能用了。比如同一个直播间不同域名：
archgay ~ $ you-get -di http://www.douyutv.com/301712
Site:       douyutv.com
Title:      阿怡：大号上王者
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

archgay ~ $ you-get -di http://www.douyu.com/301712
you-get: version 0.4.350, a tiny downloader that scrapes the web.
you-get: ['http://www.douyu.com/301712']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.350', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1266, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1179, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1027, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1258, in any_download
    m, url = url_to_module(url)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1250, in url_to_module
    res = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

------
然后这是我找了一个已关播的，报错如下。。
you-get -di http://www.douyutv.com/221895
you-get: version 0.4.350, a tiny downloader that scrapes the web.
you-get: ['http://www.douyutv.com/221895']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.350', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1266, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1179, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1027, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1259, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractors/douyutv.py", line 24, in douyutv_download
    raise ValueError("The live stream is not online! (Errno:%s)" % server_status)
ValueError: The live stream is not online! (Errno:0)

-----
you-get: version 0.4.350
Linux archb 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux
只想说我目前是没遇到不能解析的，回复楼主的时候因为我就是在用vlc看直播（包括现在回复也在看啊），所以没有及时试试他的链接就给的回复，我估计你们测试时已关播了
然后，能不能支持识别douyu.tv。。 你那无法访问？国外么？国外看不了斗奶？=。=
嗯，手残把之前回复删了。。

**Comment by soimort** [comment]
> 然后，能不能支持识别douyu.tv。。 你那无法访问？国外么？国外看不了斗奶？=。=

只是我这边的DNS解析不了，不代表国外都看不了。
当然我访问不到就表示我自己没法修。

那么欢迎pull request。

**Comment by binai** [comment]
哈哈我的斗鱼问题解决了，现在可以正常看了。
估计斗鱼只是换了域名信息，原来的douyutv更换为了douyu其他的api之类的东西都没有更换。
我目前的做法是，把原来使用douyutv的关键字，包含链接都替换为了douyu。目前我可以正常打开斗鱼了，有需要有朋友可以试试。

**Comment by soimort** [comment]
Closed via #1011.
