### ISSUE TITLE
ffmpeg 3.0.1 无法合并视频

### ISSUE THREAD

**Issue by nuomi1** [soimort/you-get#1018]
今天升级了 ffmpeg 3.0.1 bottle 之后，调用就失败了。退回 3.0 正常。
不知道是参数有变还是 bottle 编译出错。

```
you-get -d http://www.bilibili.com/video/av4224821/
[DEBUG] get_content: http://www.bilibili.com/video/av4224821/
[DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=8e9fc618fbd41e28&cid=6826902
Site:       bilibili.com
Title:      双月之城 01
Type:       Flash video (video/x-flv)
Size:       213.43 MiB (223794336 Bytes)

Downloading 双月之城 01.flv ...
 0.0% (  0.0/213.4MB) ├─────────────────────────────────────────┤[1/2]
43.5% ( 92.8/213.4MB) ├██████████████████───────────────────────┤[1/2]   72 MB/s
 100% (213.4/213.4MB) ├█████████████████████████████████████████┤[2/2]   91 MB/s
Merging video parts... [proxychains] DLL init: proxychains-ng 4.11
you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av4224821/']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 151, in bilibili_download
    bilibili_download_by_cid(cid, title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 99, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 746, in download_urls
    ffmpeg_concat_flv_to_mp4(parts, output_filepath)
  File "/usr/local/lib/python3.5/site-packages/you_get/processor/ffmpeg.py", line 129, in ffmpeg_concat_flv_to_mp4
    subprocess.check_call(params)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ffmpeg', '-loglevel', 'quiet', '-f', 'concat', '-y', '-i', './双月之城 01.mp4.txt', '-c', 'copy', './双月之城 01.mp4']' returned non-zero exit status 1
```

**Comment by soimort** [comment]
既然这样，难道不应该是ffmpeg的问题么？
