### ISSUE TITLE
Soundcloud not working

### ISSUE THREAD

**Issue by sankalpsingha** [soimort/you-get#1038]
Please make sure these boxes are checked before submitting your issue – thank you!
- [y] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [y] Your `you-get` is up-to-date.
- [y] I have read https://github.com/soimort/you-get/wiki/FAQ and tried to do so.
- [y] The issue is not yet reported on https://github.com/soimort/you-get/issues or  https://github.com/soimort/you-get/wiki/Known-Bugs. If so, please add your comments under the existing issue.
- [y] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['https://soundcloud.com/lifeofdesiigner/desiigner-panda']
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1237, in connect
    server_hostname=server_hostname)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/soundcloud.py", line 21, in soundcloud_download
    metadata = get_html('https://api.soundcloud.com/resolve.json?url=' + url + '&client_id=02gUJC0hH2ct1EGOcYXQIzRFU91c72Ea')
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 271, in get_html
    content = get_response(url, faker).data
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 259, in get_response
    response = request.urlopen(url)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
```

**Comment by cnbeining** [comment]
Again the certificate problem...

2016年4月7日星期四，Mort the Bot <notifications@github.com> 写道：

**Comment by sankalpsingha** [comment]
Nope... Tried again.. Giving me the certificate problem like @cnbeining  mentioned.

**Comment by soimort** [comment]
Python installation via Homebrew is almost broken. I had troubles with its ssl module each time.

Try to rebuild openssl and python3 again, and if it still doesn't work, use the official installer from here https://www.python.org/downloads/mac-osx/. Otherwise I don't know what we could do.

**Comment by yan12125** [comment]
Here are some discussions regarding homebrewed Python and OpenSSL on Mac: https://github.com/rg3/youtube-dl/issues/5317.

**Comment by anuxs** [comment]
you-get -d 'https://youtu.be/rhnZ19sbxps' --no-check-certificate
依然报 [SSL: CERTIFICATE_VERIFY_FAILED]  错误。
用的全局代理，safari打开youtu没有问题。

**Comment by cnbeining** [comment]
Chances are the certificates curl and Pyhon using is not the same as the
built in one.

2016年10月8日星期六，alang <notifications@github.com> 写道：

**Comment by rosynirvana** [comment]
check #1710 for SSL Error on OS X
