### ISSUE TITLE
Issue with video download from facebook. 'NoneType' is not iterable

### ISSUE THREAD

**Issue by SantoshSrinivas79** [soimort/you-get#1048]
There seems to be a problem with the download of Facebook videos. Please see debug log below.

```sh
bash-3.2$ python3.5 you-get -i --debug https://www.facebook.com/photo.php?v=4837510389115
Site:       Facebook.com
you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['https://www.facebook.com/photo.php?v=4837510389115']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "src/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "src/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "src/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "src/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "src/you_get/extractors/facebook.py", line 23, in facebook_download
    print_info(site_info, title, type, size)
  File "src/you_get/common.py", line 965, in print_info
    maybe_print("Title:     ", unescape_html(tr(title)))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/html/__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by SantoshSrinivas79** [comment]
Thank you. Strange. I proxied into the US and it works.

**Comment by ellisonleao** [comment]
Having the same issue here.

```
❯ you-get -di https://www.facebook.com/imaitapeva/videos/660315830790906/
Site:       Facebook.com
you-get: version 0.4.424, a tiny downloader that scrapes the web.
you-get: ['https://www.facebook.com/imaitapeva/videos/660315830790906/']
Traceback (most recent call last):
  File "/Users/ellison/.virtualenvs/yg/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Users/ellison/.virtualenvs/yg/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/ellison/.virtualenvs/yg/lib/python3.5/site-packages/you_get/common.py", line 1277, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/ellison/.virtualenvs/yg/lib/python3.5/site-packages/you_get/common.py", line 1190, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/ellison/.virtualenvs/yg/lib/python3.5/site-packages/you_get/common.py", line 1033, in download_main
    download(url, **kwargs)
  File "/Users/ellison/.virtualenvs/yg/lib/python3.5/site-packages/you_get/common.py", line 1270, in any_download
    m.download(url, **kwargs)
  File "/Users/ellison/.virtualenvs/yg/lib/python3.5/site-packages/you_get/extractors/facebook.py", line 23, in facebook_download
    print_info(site_info, title, type, size)
  File "/Users/ellison/.virtualenvs/yg/lib/python3.5/site-packages/you_get/common.py", line 968, in print_info
    maybe_print("Title:     ", unescape_html(tr(title)))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/html/__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable
```
Python Version: 3.5.1
