### ISSUE TITLE
战旗TV 好像看Lyingman，似乎zhanqi.tv不能看

### ISSUE THREAD

**Issue by binai** [soimort/you-get#1049]
战旗TV好像不能看，用d也没有显示有什么有效的信息。
```
binai@BinaisAir ~> you-get -d http://www.zhanqi.tv/topic/lyingman             1
[DEBUG] get_content: http://www.zhanqi.tv/topic/lyingman
[DEBUG] get_content: http://www.zhanqi.tv/api/static/live.roomid/36596.json
Site:       zhanqi.tv
Title:      Lying Man 战旗TV高清直播_战旗TV游戏直播 - zhanqi.tv
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['http://www.zhanqi.tv/topic/lyingman']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/extractors/zhanqi.py", line 51, in zhanqi_download
    download_rtmp_url(real_url, title, 'flv', {}, output_dir, merge = merge)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/common.py", line 887, in download_rtmp_url
    assert has_rtmpdump_installed(), "RTMPDump not installed."
AssertionError: RTMPDump not installed.
```

原来是因为没有安装RTMPDump，上次用-d没有什么提示，这次有了，安装后就可以了。

**Comment by ERioK** [comment]
url格式问题，可以把topic去掉
you-get http://www.zhanqi.tv/lyingman

**Comment by cnbeining** [comment]
你确定不行么？

因为是直播流 肯定Size是没有的。

**Comment by cnbeining** [comment]
请问对于此issue是否有信息更新 或是否解决？

**Comment by soimort** [comment]
> 原来是因为没有安装RTMPDump

此 issue 可关。
