### ISSUE TITLE
[Failed]土豆

### ISSUE THREAD

**Issue by ppwwyyxx** [soimort/you-get#1054]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
╰─$you-get --debug "http://www.tudou.com/programs/view/FuECmFmtqZw"                                                                                  ⏎
you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['http://www.tudou.com/programs/view/FuECmFmtqZw']
Traceback (most recent call last):
  File "/home/wyx/.local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/wyx/.local/lib/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/wyx/.local/lib/python3.4/site-packages/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/wyx/.local/lib/python3.4/site-packages/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/wyx/.local/lib/python3.4/site-packages/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "/home/wyx/.local/lib/python3.4/site-packages/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "/home/wyx/.local/lib/python3.4/site-packages/you_get/extractors/tudou.py", line 52, in tudou_download
    tudou_download_by_iid(iid, title, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/wyx/.local/lib/python3.4/site-packages/you_get/extractors/tudou.py", line 18, in tudou_download_by_iid
    ext = r1(r'http://[\w.]*/(\w+)/[\w.]*', urls[0])
IndexError: list index out of range
```

**Comment by Rokicto** [comment]
you-get -di http://www.tudou.com/programs/view/FuECmFmtqZw
    Site:       Tudou.com
    Title:      Type:       Flash video (video/x-flv)
    Size:       113.8 MiB (119324567 Bytes)

Working well for me.

**Comment by ppwwyyxx** [comment]
Just tried again with the same version and it works as well. Don't know what's happening.

**Comment by soimort** [comment]
@soimort-bot Test this again http://www.tudou.com/programs/view/FuECmFmtqZw
