### ISSUE TITLE
windows cmd下url参数引号会导致错误

### ISSUE THREAD

**Issue by yueisme** [soimort/you-get#1056]
### 错误：windows cmd下url参数有单引号会发生错误

发生错误的：you-get -i --debug 'https://www.youtube.com/watch?v=jNQXAC9IVRw'
正常运行的：you-get -i --debug https://www.youtube.com/watch?v=jNQXAC9IVRw

### debug info

测试视频取自you-get wiki
```
C:\Users\a9198_000>you-get -i --debug 'https://www.youtube.com/watch?v=jNQXAC9IVRw'
you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ["'https://www.youtube.com/watch?v=jNQXAC9IVRw'"]
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1274, in main
  File "src\you_get\common.py", line 1187, in script_main
  File "src\you_get\common.py", line 1030, in download_main
  File "src\you_get\common.py", line 1266, in any_download
  File "src\you_get\common.py", line 1258, in url_to_module
  File "http\client.py", line 1174, in getresponse
  File "http\client.py", line 282, in begin
  File "http\client.py", line 251, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response
you-get returned -1
```

若去掉单引号则正常，CMD中会出现，powershell没有问题
```
C:\Users\a9198_000>you-get -i --debug https://www.youtube.com/watch?v=jNQXAC9IVR
w
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=jNQXAC9IVRw

[DEBUG] get_content: https://www.youtube.com/watch?v=jNQXAC9IVRw
[DEBUG] get_content: https://www.youtube.com/api/timedtext?key=yttt1&signature=1
8717BA959AF8DC5CCBBE378E72DF44C2F5D66AC.5C6B4F5FD465727B631DD601C854FCF637774AA9
&expire=1460561577&caps=&v=jNQXAC9IVRw&hl=en_US&sparams=caps%2Cv%2Cexpire&lang=e
n
[DEBUG] get_content: https://s.ytimg.com/yts/jsbin/player-en_US-vfll2CKBY/base.j
s
site:                YouTube
title:               Me at the zoo
streams:             # Available quality and codecs
.......(省略)
```

> [舔 :icecream:!]

**Comment by soimort** [comment]
Windows cmd的参数本来就不应该加引号……

这是使用方法不对。
