### ISSUE TITLE
acfun some video failed

### ISSUE THREAD

**Issue by zhangn1985** [soimort/you-get#1069]
you-get --debug http://www.acfun.tv/v/ac2674729
[DEBUG] get_content: http://api.aixifan.com/plays/3409199/realSource
you-get: version 0.4.529, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.tv/v/ac2674729']
Traceback (most recent call last):
  File "/home/zhangn1985/source/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/zhangn1985/source/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/zhangn1985/source/you-get/src/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/extractors/acfun.py", line 76, in acfun_download
    **kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/extractors/acfun.py", line 37, in acfun_download_by_vid
    urls = s['data']['files'][-1]['url']
KeyError: 'data'

**Comment by cnbeining** [comment]
Not all the videos are available via the mobile API.

2016年4月16日星期六，Mort the Bot <notifications@github.com> 写道：

**Comment by sslook** [comment]
** I come across the same error, too ! How to fix it?**
$ you-get --debug http://www.acfun.tv/v/ac2674729
[DEBUG] get_content: http://api.aixifan.com/plays/3409199/realSource
you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.tv/v/ac2674729']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/acfun.py", line 76, in acfun_download
    **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/acfun.py", line 37, in acfun_download_by_vid
    urls = s['data']['files'][-1]['url']
KeyError: 'data'

**Comment by cnbeining** [comment]
Bug confirmed.

**Comment by zhangn1985** [comment]
@soimort-bot Please test this link: http://www.acfun.tv/v/ac2676137

**Comment by cnbeining** [comment]
哎呀新API日了狗了。

**Comment by zhangn1985** [comment]
@soimort-bot Please test this link:  http://www.acfun.tv/v/ac2677480

**Comment by cnbeining** [comment]
只能和ct86正面硬肛了。

2016年4月18日星期一，Mort the Bot <notifications@github.com> 写道：

**Comment by drpo** [comment]
offline also failed on latest Android client (v4.1.7), no luck this time :see_no_evil:

**Comment by cnbeining** [comment]
They changed the whole api system.  No way to steal this time.

2016年4月18日星期一，Dr. PO <notifications@github.com> 写道：

**Comment by zhangn1985** [comment]
现在A站flash播放器和app全部不能播放视频了。

还是等A站自己更新好了我们再来吧。

**Comment by cnbeining** [comment]
他全用ct85了。

我们得把ct86搞出来....apk里面有些东西解不开。看样还是什么奇特的lua...

2016年4月18日星期一，zhangn1985 <notifications@github.com> 写道：

**Comment by ERioK** [comment]
ct86大概搞清楚了，大部分和原来代码里的ct12差不多，参考着写了下，可以先用着，等官方稳定了再说吧，或者看看ct85能不能解出来
https://github.com/ERioK/you-get/commit/a924bce22bf307d28f9d8bde836ff07dd96dc160
