### ISSUE TITLE
ffmpeg merge video parts error

### ISSUE THREAD

**Issue by Xuchenhao** [soimort/you-get#1070]
```
Soras-MacBook-Pro:~ Sora$ brew install ffmpeg
Warning: ffmpeg-3.0.1 already installed
Soras-MacBook-Pro:~ Sora$ you-get --debug http://www.bilibili.com/video/av4347588/ 
[DEBUG] get_content: http://www.bilibili.com/video/av4347588/
[DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=8e9fc618fbd41e28&cid=7036056
Site:       bilibili.com
Title:      【字幕】内田彩的家 (2016.04.08) Final LoveLive!感想等
Type:       Flash video (video/x-flv)
Size:       73.05 MiB (76593464 Bytes)

Downloading 【字幕】内田彩的家 (2016.04.08) Final LoveLive!感想等.flv ...
 100% ( 73.0/ 73.0MB) ├█████████████████████████████████████████┤[2/2]    1 GB/s
Merging video parts... you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av4347588/']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 151, in bilibili_download
    bilibili_download_by_cid(cid, title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 99, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 746, in download_urls
    ffmpeg_concat_flv_to_mp4(parts, output_filepath)
  File "/usr/local/lib/python3.5/site-packages/you_get/processor/ffmpeg.py", line 129, in ffmpeg_concat_flv_to_mp4
    subprocess.check_call(params)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ffmpeg', '-loglevel', 'quiet', '-f', 'concat', '-y', '-i', './【字幕】内田彩的家 (2016.04.08) Final LoveLive!感想等.mp4.txt', '-c', 'copy', './【字幕】内田彩的家 (2016.04.08) Final LoveLive!感想等.mp4']' returned non-zero exit status 1
```

**Comment by nuomi1** [comment]
@Xuchenhao 更新 you-get 至 https://github.com/soimort/you-get/commit/53cb97def5f2aa760de32f652e8db7be76be529a 即可解决，pip 还没推送更新。

**Comment by soimort** [comment]
As above.
