### ISSUE TITLE
(can you-get download 720p or hd video of tencent ?)you-get能不能下载腾讯视频的超清(720P)或者高清的视频

### ISSUE THREAD

**Issue by amylins** [soimort/you-get#1071]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by amylins** [comment]
can You-get download  720P or HD video  of Tencent ?? how to do it ??

**Comment by xyuanmu** [comment]
国内IP是支持720的，只是部分视频解析失败，如 #1066

**Comment by amylins** [comment]
@xyuanmu 你好，我有看到那个帖子，上面好像没说怎么下载720的视频，请问你知道怎么下吗

**Comment by amylins** [comment]
@xyuanmu 解析出来只有一个

**Comment by amylins** [comment]
@xyuanmu  解析出来只有一个码流
C:\Users\amylin>you-get -i http://v.qq.com/cover/w/wkfi7sdq44mto0i.html?vid=p0020toddhx

Site:       QQ.com
Title:      群星《总有幸福在等你》(《欢乐颂》片尾曲)
Type:       MPEG-4 video (video/mp4)
Size:       12.12 MiB (12710012 Bytes)

**Comment by xyuanmu** [comment]
哦，弄错了，刚才测试的是这个：https://github.com/zhangn1985/you-get
原版的只解析一个

**Comment by amylins** [comment]
@xyuanmu 这个可以支持720吗   我试试，先谢谢你哈

**Comment by amylins** [comment]
@xyuanmu 你好，直接把那个的you-get目录拷贝覆盖原版就好吗

**Comment by xyuanmu** [comment]
我不知道你用的是什么系统，我的是Windows，两份是分开放的，覆盖不知道会不会出问题。

**Comment by zhangn1985** [comment]
我那个版本在遇到v.qq.com/cover/h/* 开头的QQ视频，速度比较慢（50K），其余的速度还可以。

**Comment by xyuanmu** [comment]
cover/u/ 好像也挺慢的，前天下载奔跑吧兄弟下了一整天。

**Comment by amylins** [comment]
@xyuanmu 我的也是windows，原版you-get是用pip安装的，怎么安装这个版本呢？？  直接在文件夹里面执行会寻找原版的路径

**Comment by amylins** [comment]
@zhangn1985 你好，请问下你这个版本和原版能同时存在吗？？我原版是用pip安装的，能不覆盖原版安装你这个吗？

**Comment by zhangn1985** [comment]
@xyuanmu 难道只有cover/d/比较快？这个是能到500k的。那我需要研究一下了。
@amylins 很抱歉，我不了解pip。

**Comment by cnbeining** [comment]
为何不git clone下个standalone...

2016年4月18日星期一，zhangn1985 <notifications@github.com> 写道：

**Comment by amylins** [comment]
@zhangn1985 那怎么安装你这个呢？

**Comment by amylins** [comment]
@xyuanmu @zhangn1985 谢谢你们哈~~~

**Comment by amylins** [comment]
@zhangn1985 hi，我刚才发现你的版本在下载土豆的视频的时候出现了403 Forbidden，原版是正常的，试了几个都是这样，不知道你们会不会。-i  是正常的；

**Comment by amylins** [comment]
@zhangn1985 hi，我刚才发现你的版本在下载土豆的视频的时候出现了403 Forbidden，原版是正常的，试了几个都是这样，不知道你们会不会。-i 是正常的；
`C:\Users\amylin>you-get --format=current http://www.tudou.com/programs/view/6rRS
gDimPlI/
site:                土豆原创 (tudou)
title:               《一念向北》曝主题曲双MV_土豆_高清视频在线观看
streams:
    - format:        current
      container:     f4v
      video-profile: current
      size:          66.0 MiB (69175928 bytes)
    # download-with: you-get --format=current [URL]

Downloading 《一念向北》曝主题曲双MV_土豆_高清视频在线观看.f4v ...
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 89, in main
    m.download(u, para)
  File "C:\Python34\lib\site-packages\you_get\embedextractor.py", line 46, in do
wnload_by_url
    s.site.download_by_vid(vid, self.param, title=self.title, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractor.py", line 103, in downlo
ad_by_vid
    self.download(**kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractor.py", line 127, in downlo
ad
    download_urls(urls, self.title, self.streams[stream_id]['container'], self.s
treams[stream_id]['size'], output_dir=self.param.output_dir)
  File "C:\Python34\lib\site-packages\you_get\util\download.py", line 181, in do
wnload_urls
    url_save(url, filepath, bar, refer = refer, is_part = True)
  File "C:\Python34\lib\site-packages\you_get\util\download.py", line 10, in url
_save
    file_size = url_size(url)
  File "C:\Python34\lib\site-packages\you_get\util\html.py", line 128, in url_si
ze
    response = request.urlopen(url)
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by zhangn1985** [comment]
是的，我不知道怎么fix。

**Comment by q629988171** [comment]
我也遇到类似问题，在腾讯视频下载[一分钟教你学会倒车入库] 出错。Debug如下：

环境：Windows 7 x64、Python 3.5.1 32-bit

you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/cover/t/twt30q1v5sglfxo.html?vid=d01941f9oxs']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1274, in main
  File "src\you_get\common.py", line 1187, in script_main
  File "src\you_get\common.py", line 1030, in download_main
  File "src\you_get\common.py", line 1267, in any_download
  File "src\you_get\extractors\qq.py", line 33, in qq_download
  File "src\you_get\extractors\qq.py", line 14, in qq_download_by_vid
  File "src\you_get\common.py", line 353, in url_info
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 471, in open
  File "urllib\request.py", line 581, in http_response
  File "urllib\request.py", line 503, in error
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 686, in http_error_302
  File "urllib\request.py", line 471, in open
  File "urllib\request.py", line 581, in http_response
  File "urllib\request.py", line 509, in error
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 589, in http_error_default
urllib.error.HTTPError: HTTP Error 405: Method Not Allowed
you-get returned -1
