### ISSUE TITLE
有密码的优酷视频无法下载

### ISSUE THREAD

**Issue by shengting** [soimort/you-get#1072]
视频：http://v.youku.com/v_show/id_XMTUzOTc1MTAyOA==.html
密码：test 
人工验证密码正确，但you-get失败，下面是--debug信息。

看见之前有人问过这个问题：https://github.com/soimort/you-get/issues/1034
但他的好像是自己密码输出错误，为了验证这个问题，我特意自己上传了一个视频，设置密码试了一下。

```
python3 ./you-get --debug http://v.youku.com/v_show/id_XMTUzOTc1MTAyOA==.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTUzOTc1MTAyOA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTUzOTc1MTAyOA==&ct=12
Password: test
you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTUzOTc1MTAyOA==.html']
Traceback (most recent call last):
  File "./src/you_get/extractors/youku.py", line 166, in prepare
    assert 'stream' in data
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "./src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "./src/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "./src/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "./src/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "./src/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "./src/you_get/extractor.py", line 40, in download_by_url
    self.prepare(**kwargs)
  File "./src/you_get/extractors/youku.py", line 174, in prepare
    api_url12 += '&pwd={}'.format(self.password)
UnboundLocalError: local variable 'api_url12' referenced before assignment
```

无--dubug的执行情况如下：
```
python3 ./you-get http://v.youku.com/v_show/id_XMTUzOTc1MTAyOA==.html
Password: test
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
```

**Comment by jxon** [comment]
clearly, there's a typo in youku.py.
**api12_url** was mistyped as **api_url12** in line 174 and 180.
Fix these two typos should do the job.
Here is output after the fix:
```
you-get -di http://v.youku.com/v_show/id_XMTUzOTc1MTAyOA==.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTUzOTc1MTAyOA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTUzOTc1MTAyOA==&ct=12
Password: test
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTUzOTc1MTAyOA==&ct=10&pwd=test
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTUzOTc1MTAyOA==&ct=12&pwd=test
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/94610311886021205442b_00/st/flv/fileid/03000201005714F1116F810887A4CF647579D2-F8B5-3AFF-F5F8-A6970D52B0CE?ctype=12&ep=eyaSG0mOV88I7SXfij8bZynmcHVdXP4J9h%2BFg9JjALshT%2Bm77z%2FQxpvGRv5CHvEeAyZ1Zu31rNXgYzQWYYZL220Q3D%2FeT%2FqW%2B4br5dxVzZcAEhw0AM2kwVSaQjH1&yxon=1&K=1fef4e02dd5f1f32261ef699&token=4114&ev=1&oip=3701856303
site:                优酷 (Youku)
title:               test
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          0.2 MiB (223785 bytes)
    # download-with: you-get --format=flvhd [URL]
```
Can somebody create a pr for this? I am new to github, not sure how to do this yet.

**Comment by zhangn1985** [comment]
@jxon 你说得对
https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/youku.py#L180
https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/youku.py#L161

的确错了。

**Comment by zhangn1985** [comment]
https://github.com/soimort/you-get/commit/c054da9535a0b010b473d4427a0c414efe157651

@soimort

**Comment by shengting** [comment]
@jxon 👍 Thanks !
