### ISSUE TITLE
"NameError" when download youku playlist

### ISSUE THREAD

**Issue by bajingxiaozi** [soimort/you-get#1080]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[
Python version: Python 3.5.0
OS: Windows7 64-bit
Command: you-get-0.4.365-win32.exe -i http://list.youku.com/albumlist/show?id=26106350&ascending=1&page=1

Detail:
It's OK of showing all video urls in the page.

but I get a error below, I think this's abnormal.

_you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['http://list.youku.com/albumlist/show?id=26106350&ascending=1&page=1']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1274, in main
  File "src\you_get\common.py", line 1187, in script_main
  File "src\you_get\common.py", line 1030, in download_main
  File "src\you_get\common.py", line 1267, in any_download
  File "src\you_get\extractor.py", line 40, in download_by_url
  File "src\you_get\extractors\youku.py", line 151, in prepare
NameError: name 'exit' is not defined
you-get returned -1_

]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by bajingxiaozi** [comment]
Perhaps python 3.6 get something wrong with "NameError: name 'exit' is not defined"

***
    - title:         Lyingman第三季第二期上半场
       size:         1239.6 MiB (1299779974 bytes)
        url:         http://v.youku.com/v_show/id_XMTQzNjc5MTA4NA==.html

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by bajingxiaozi** [comment]
sorry python3.5

**Comment by CNMan** [comment]
我也遇到了这个问题，用的release里面的win full包

http://www.youku.com/show_page/id_z2db2b678de1e11de97c0.html

```
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.youku.com/show_page/id_z2db2b678de1e11de97c0.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1348, in main
  File "src\you_get\common.py", line 1261, in script_main
  File "src\you_get\common.py", line 1077, in download_main
  File "src\you_get\common.py", line 1341, in any_download
  File "src\you_get\extractor.py", line 41, in download_by_url
  File "src\you_get\extractors\youku.py", line 157, in prepare
NameError: name 'exit' is not defined
you-get returned -1
```

**Comment by CNMan** [comment]
```
you-get: version 0.4.555, a tiny downloader that scrapes the web.

>cd /d c:\Downloads\2008

>you-get -i http://www.youku.com/show_page/id_z2db2b678de1e11de97c0.html
site:                优酷 (Youku)
playlist:            None
videos:
    - title:         魔术四大天王(下) 081107
       size:         92.1 MiB (96575352 bytes)
        url:         http://v.youku.com/v_show/id_XMTY1ODA3MDAw.html

    - title:         不会创作谁敢出题 081111
       size:         90.4 MiB (94784629 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkzMjU2.html

    - title:         我是靠暧昧起家的 杨丞琳 081120
       size:         93.1 MiB (97642567 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkxOTc2.html

    - title:         史上最疯狂的月份 五月天 081105
       size:         91.1 MiB (95525922 bytes)
        url:         http://v.youku.com/v_show/id_XMTY1Nzk1NzYw.html

    - title:         最具爆发力的歌手 信 081028
       size:         93.5 MiB (98077432 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkzMjQ0.html

    - title:         娃娃依然实力不减 081219
       size:         92.9 MiB (97382912 bytes)
        url:         http://v.youku.com/v_show/id_XMTQwMzE1MTUy.html

    - title:         找回生命的美丽歌声 081223
       size:         93.3 MiB (97860712 bytes)
        url:         http://v.youku.com/v_show/id_XMTg2MjQ5OTAw.html

    - title:         耐人寻味 怀旧金曲重现 081210
       size:         93.4 MiB (97975483 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkzMjY4.html

    - title:         PUB不可或缺的点唱机 081230
       size:         90.4 MiB (94801127 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkxOTk2.html

    - title:         我要一份大支热狗RAP餐 081030
       size:         91.2 MiB (95647761 bytes)
        url:         http://v.youku.com/v_show/id_XMTQwMzE1MTQ0.html

    - title:         明星晚餐 刘若英 081027
       size:         93.6 MiB (98170800 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkzMjQw.html

    - title:         林心如的男人帮 081224
       size:         93.3 MiB (97814283 bytes)
        url:         http://v.youku.com/v_show/id_XMTY1ODExODky.html

    - title:         七匹狼之2狼来了 邰正宵 080121
       size:         93.3 MiB (97832143 bytes)
        url:         http://v.youku.com/v_show/id_XMTYyOTU4MjEy.html

    - title:         不简单的创作歌手 081225
       size:         94.5 MiB (99059043 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkxOTg4.html

    - title:         无所不在的深情 苏永康 081029
       size:         92.3 MiB (96772015 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkzMjQ4.html

    - title:         民歌黄金拍挡风光再现 081208
       size:         93.2 MiB (97713632 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkxOTg0.html

    - title:         图片之光 海角热潮 081124
       size:         92.0 MiB (96455276 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkxOTgw.html

    - title:         我也曾经是歌手 081113
       size:         90.1 MiB (94439539 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkzMjYw.html

    - title:         魔术四大天王(上) 081106
       size:         92.9 MiB (97429468 bytes)
        url:         http://v.youku.com/v_show/id_XMTY1ODA2OTk2.html

    - title:         今夜最浪漫的事 赵咏华 081229
       size:         91.7 MiB (96105881 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkxOTky.html

    - title:         最具爆发力的歌手 信 081028
       size:         93.5 MiB (98077432 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkzMjQ0.html&from-data=y1.6-85.3.1.2db2b678de1e11de97c0

    - title:         美女爱美不完美 081121
       size:         92.2 MiB (96648078 bytes)
        url:         http://v.youku.com/v_show/id_XMTQwMzE1MTQ4.html

    - title:         帅到深处无怨尤 潘玮柏 081125
       size:         95.5 MiB (100093197 bytes)
        url:         http://v.youku.com/v_show/id_XMTQwMzE1MjI0.html

    - title:         我要在台湾红起来 081212
       size:         91.9 MiB (96318166 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkzMjI4.html

    - title:         情歌王子征服情海 光良 李圣杰 081022
       size:         93.2 MiB (97676497 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkxOTY4.html

    - title:         B咖出头天 081128
       size:         89.3 MiB (93684627 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkzMjY0.html

    - title:         永远的欧香女郎 081222
       size:         93.0 MiB (97531788 bytes)
        url:         http://v.youku.com/v_show/id_XMTg2MjQ5ODk2.html

    - title:         永远的报告班长 081226
       size:         94.3 MiB (98836330 bytes)
        url:         http://v.youku.com/v_show/id_XMTg2MjQ5OTA0.html

    - title:         难忘的好声音 周华健 081020
       size:         90.6 MiB (95034631 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkzMjMy.html

    - title:         用歌声感动人心 081103
       size:         91.2 MiB (95653948 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkzMjUy.html

    - title:         全方位的音乐人黄韵玲黄国伦 081216
       size:         81.7 MiB (85631109 bytes)
        url:         http://v.youku.com/v_show/id_XMTQwMzE1MTU2.html

    - title:         台语好声音 Only you 张秀卿 翁立友 081218
       size:         93.7 MiB (98200931 bytes)
        url:         http://v.youku.com/v_show/id_XMTY1ODEyNTMy.html

    - title:         Pub英雄会 杨培安 081110
       size:         92.3 MiB (96820191 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkxOTcy.html

    - title:         用歌声征服人心!彭佳慧 周蕙 081021
       size:         93.3 MiB (97853553 bytes)
        url:         http://v.youku.com/v_show/id_XMTc1MzkzMjM2.html

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

>
```
