### ISSUE TITLE
乐视视频合并出错了

### ISSUE THREAD

**Issue by amylins** [soimort/you-get#1081]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]
`Merging video parts...
.\红辣椒贝斯手Flea致敬科比solo美国国歌[00].mp4
you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/25121125.html']
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1294, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1201, in script
ain
    download_main(download, download_playlist, args, playlist, output_dir=outp
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=capti
)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1040, in downlo
_main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1285, in any_do
load
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractors\le.py", line 140, in
tv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge,
nfo_only=info_only,**kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractors\le.py", line 101, in
tv_download_by_vid
    download_urls(urls, title, ext, size, output_dir=output_dir, merge=merge)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 775, in downloa
urls
    concat_mp4(parts, output_filepath)
  File "C:\Python34\lib\site-packages\you_get\processor\join_mp4.py", line 914
in concat_mp4
    merge_mp4s(mp4s, output)
  File "C:\Python34\lib\site-packages\you_get\processor\join_mp4.py", line 876
in merge_mp4s
    mp4s = list(map(read_mp4, ins))
  File "C:\Python34\lib\site-packages\you_get\processor\join_mp4.py", line 717
in read_mp4
    atoms = parse_atoms(stream)
  File "C:\Python34\lib\site-packages\you_get\processor\join_mp4.py", line 708
in parse_atoms
    atom = read_atom(stream)
  File "C:\Python34\lib\site-packages\you_get\processor\join_mp4.py", line 700
in read_atom
    raise NotImplementedError('%s: %d' % (type, left))
NotImplementedError: b'\x00\x00\xb0\r': 1195376648`

**Comment by amylins** [comment]
@soimort-bot hi，I can download it, but it's a mistake when i join it together.

**Comment by amylins** [comment]
100% ( 50.8/ 50.8MB) ├████████████████████████████
███████████┤[12/12]  761 kB/s
Merging video parts...
.\红辣椒贝斯手Flea致敬科比solo美国国歌[00].mp4
you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/25121125.html']
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1294, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1201, in script_m
ain
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1040, in download
_main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1285, in any_down
load
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractors\le.py", line 140, in le
tv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, i
nfo_only=info_only,**kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractors\le.py", line 101, in le
tv_download_by_vid
    download_urls(urls, title, ext, size, output_dir=output_dir, merge=merge)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 775, in download_
urls
    concat_mp4(parts, output_filepath)
  File "C:\Python34\lib\site-packages\you_get\processor\join_mp4.py", line 914,
in concat_mp4
    merge_mp4s(mp4s, output)
  File "C:\Python34\lib\site-packages\you_get\processor\join_mp4.py", line 876,
in merge_mp4s
    mp4s = list(map(read_mp4, ins))
  File "C:\Python34\lib\site-packages\you_get\processor\join_mp4.py", line 717,
in read_mp4
    atoms = parse_atoms(stream)
  File "C:\Python34\lib\site-packages\you_get\processor\join_mp4.py", line 708,
in parse_atoms
    atom = read_atom(stream)
  File "C:\Python34\lib\site-packages\you_get\processor\join_mp4.py", line 700,
in read_atom
    raise NotImplementedError('%s: %d' % (type, left))
NotImplementedError: b'\x00\x00\xb0\r': 1195376648

**Comment by soimort** [comment]
请安装 FFmpeg。

**Comment by amylins** [comment]
@soimort 你好，我安装了FFmpeg，在cmd也能看到FFmpeg的版本，但是还是报了相同的错误，这是为什么呢

**Comment by cnbeining** [comment]
@soimort  我在别的渠道也遇见了这个报错 Windows下 ffmpeg已经添加PATH 但是没调用。

需要复现一下恩。。

**Comment by amylins** [comment]
@soimort @cnbeining hi,安装了ffmpeg之后代码里面却检查不出来ffmpeg已经安装了，这个有关吗？我看到这里报了一个错误
  File "C:\Python34\lib\site-packages\you_get\processor\ffmpeg.py", line 28, in
<module>
    FFMPEG, FFMPEG_VERSION = get_usable_ffmpeg('ffmpeg') or get_usable_ffmpeg('a
vconv') or (None, None)
  File "C:\Python34\lib\site-packages\you_get\processor\ffmpeg.py", line 12, in
get_usable_ffmpeg
    p = subprocess.Popen(['ffmpeg', '-version'], stdout=subprocess.PIPE, stderr=
subprocess.PIPE)
  File "C:\Python34\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by cnbeining** [comment]
就是这个问题。我不知道为什么。
