### ISSUE TITLE
I tried to watch  video with my media player, but failed...

### ISSUE THREAD

**Issue by leyayun** [soimort/you-get#1082]
I run the command `you-get -p chromium "http://v.youku.com/v_show/id_XMTU0MzQzNDkzNg==.html?from=y1.3-idx-uhome-1519-20887.205805-205902.5-1#paction" --debug`, then got the following output.

```
site:                优酷 (Youku)
title:               荒野猎人
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          3316.9 MiB (3478023804 bytes)
    # download-with: you-get --format=hd3 [URL]

audio-languages:
    - lang:          英语
      download-url:  http://v.youku.com/v_show/id_XMTU0MzQzNDkzNg==

    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XMTU0MzQxNDg5Ng==

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
```

**Comment by soimort** [comment]
Youku is known to require the same set of cookies for accessiing videos, so the raw URLs extracted by `you-get` may not be working when passed to other tools (i.e. a player).

**Comment by cnbeining** [comment]
@soimort-bot Please kindly test this link for me: http://v.youku.com/v_show/id_XMTU0MzQzNDkzNg==.html

**Comment by cnbeining** [comment]
So you may want to check https://github.com/soimort/you-get/wiki/Region-Restrictions ?

**Comment by leyayun** [comment]
@soimort-bot 
This is the console log  with debug info.
```
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTU0MzQzNDkzNg==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTU0MzQzNDkzNg==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/9461464908695120d5157_00/st/flv/fileid/0300804700571910D1A17105CF07DDBB99DBB2-263F-2CEE-9993-314EB133A572?token=4129&ep=eyaSG02LUscA7SXWjT8bZ3jndXIIXP4J9h%2BNgdZlALshT%2Bm2mD6lxuyxSf5CE4pvciVyZJmDotmTGDIWYfJFqh4Q3T3dTPrp9%2Fng5a5SwOVyZxo1A8jQtlSaQjL4&ev=1&oip=1918880131&yxon=1&K=a7d3564267bee61b261ef8f4&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/9461464908695120d5157_00/st/flv/fileid/0300804701571910D1A17105CF07DDBB99DBB2-263F-2CEE-9993-314EB133A572?token=4129&ep=eyaSG02LUscA7SXWjT8bZ3jndXIIXP4J9h%2BNgdZlALohT%2Bm2mD6lxuyxSf5CE4pvciVyZJmDotmTGDIWYfJFqh4Q3T3dTPrp9%2Fng5a5SwOVyZxo1A8jQtlSaQjL4&ev=1&oip=1918880131&yxon=1&K=170b136b05ea7129282b5c89&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/9461464908695120d5157_00/st/flv/fileid/0300804702571910D1A17105CF07DDBB99DBB2-263F-2CEE-9993-314EB133A572?token=4129&ep=eyaSG02LUscA7SXWjT8bZ3jndXIIXP4J9h%2BNgdZlALkhT%2Bm2mD6lxuyxSf5CE4pvciVyZJmDotmTGDIWYfJFqh4Q3T3dTPrp9%2Fng5a5SwOVyZxo1A8jQtlSaQjL4&ev=1&oip=1918880131&yxon=1&K=2f6e3aafafa34b70282b5c89&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/9461464908695120d5157_00/st/flv/fileid/0300804703571910D1A17105CF07DDBB99DBB2-263F-2CEE-9993-314EB133A572?token=4129&ep=eyaSG02LUscA7SXWjT8bZ3jndXIIXP4J9h%2BNgdZlALghT%2Bm2mD6lxuyxSf5CE4pvciVyZJmDotmTGDIWYfJFqh4Q3T3dTPrp9%2Fng5a5SwOVyZxo1A8jQtlSaQjL4&ev=1&oip=1918880131&yxon=1&K=68a72782dfc7f676261ef8f4&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/9461464908695120d5157_00/st/flv/fileid/0300804704571910D1A17105CF07DDBB99DBB2-263F-2CEE-9993-314EB133A572?token=4129&ep=eyaSG02LUscA7SXWjT8bZ3jndXIIXP4J9h%2BNgdZlAL8hT%2Bm2mD6lxuyxSf5CE4pvciVyZJmDotmTGDIWYfJFqh4Q3T3dTPrp9%2Fng5a5SwOVyZxo1A8jQtlSaQjL4&ev=1&oip=1918880131&yxon=1&K=5797a4cafe3cc8262412955f&ctype=12
site:                优酷 (Youku)
title:               荒野猎人
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          3316.9 MiB (3478023804 bytes)
    # download-with: you-get --format=hd3 [URL]

audio-languages:
    - lang:          英语
      download-url:  http://v.youku.com/v_show/id_XMTU0MzQzNDkzNg==

    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XMTU0MzQxNDg5Ng==

you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTU0MzQzNDkzNg==.html?from=y1.3-idx-uhome-1519-20887.205805-205902.5-1#paction']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.365', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.365-py3.5.egg/you_get/__main__.py", line 92, in main
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.365-py3.5.egg/you_get/common.py", line 1274, in main
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.365-py3.5.egg/you_get/common.py", line 1187, in script_main
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.365-py3.5.egg/you_get/common.py", line 1030, in download_main
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.365-py3.5.egg/you_get/common.py", line 1267, in any_download
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.365-py3.5.egg/you_get/extractor.py", line 51, in download_by_url
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.365-py3.5.egg/you_get/extractor.py", line 207, in download
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.365-py3.5.egg/you_get/common.py", line 685, in download_urls
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.365-py3.5.egg/you_get/common.py", line 203, in launch_player
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
NotADirectoryError: [Errno 20] Not a directory
```

Python version: `2.7.10`
GeoIP location: `China`

**Comment by cnbeining** [comment]
Can you call ```chromium``` from your shell directly?

**Comment by soimort** [comment]
What is your 

```
$ type chromium
```

?

**Comment by soimort** [comment]
No response. Closing.
