### ISSUE TITLE
can't download tv.shou.com video file

### ISSUE THREAD

**Issue by wang20150419** [soimort/you-get#1087]
C:\you-get>you-get http://tv.sohu.com/20151113/n426423588.shtml
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by zhangn1985** [comment]
@soimort-bot please test link: http://tv.sohu.com/20150830/n420068384.shtml

**Comment by wang20150419** [comment]
you-get --debug http://tv.sohu.com/20151113/n426423588.shtml

you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://tv.sohu.com/20151113/n426423588.shtml']
Traceback (most recent call last):
  File "urllib\request.py", line 1240, in do_open
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 826, in connect
  File "socket.py", line 689, in create_connection
  File "socket.py", line 728, in getaddrinfo
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1237, in main
  File "src\you_get\common.py", line 1158, in script_main
  File "src\you_get\common.py", line 1006, in download_main
  File "src\you_get\common.py", line 1230, in any_download
  File "src\you_get\extractors\sohu.py", line 33, in sohu_download
  File "src\you_get\common.py", line 267, in get_decoded_html
  File "src\you_get\common.py", line 250, in get_response
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 465, in open
  File "urllib\request.py", line 483, in _open
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 1268, in http_open
  File "urllib\request.py", line 1242, in do_open
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed>
you-get returned -1

**Comment by cnbeining** [comment]
看起来像是域名换了之类的吧。

2016年4月29日星期五，wang20150419 <notifications@github.com> 写道：

**Comment by zhangn1985** [comment]
duplicate to https://github.com/soimort/you-get/issues/1098

it can be closed
