### ISSUE TITLE
搜狐下載不了

### ISSUE THREAD

**Issue by kwokts** [soimort/you-get#1103]
you-get -di http://tv.sohu.com/20120925/n353925789.shtml
you-get: version 0.4.390, a tiny downloader that scrapes the web.
you-get: ['http://tv.sohu.com/20120925/n353925789.shtml']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "src/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "src/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "src/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "src/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "src/you_get/extractors/sohu.py", line 35, in sohu_download
    hqvid = info['data'][qtyp]
TypeError: 'NoneType' object is not subscriptable

**Comment by zhangn1985** [comment]
please duplicate to https://github.com/soimort/you-get/issues/1098 and close
