### ISSUE TITLE
YouTube视频1080p可以在线观看但无法抓取下载链接

### ISSUE THREAD

**Issue by microka** [soimort/you-get#1109]
> you-get -y 127.0.0.1:1080 --debug http://www.youtube.com/watch?v=29mSe-5raVQ
> [DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=29mSe-5raVQ
> [DEBUG] get_content: https://www.youtube.com/watch?v=29mSe-5raVQ
> [DEBUG] get_content: https://manifest.googlevideo.com/api/manifest/dash/mm/31/ip/157.52.151.25/mn/sn-a8au-p5qs/fexp/9416126%2C9416891%2C9417828%2C9418751%2C9422596%2C9425946%2C9428398%2C9429381%2C9429744%2C9431012%2C9432579%2C9433096%2C9433424%2C9433629%2C9433773%2C9433946%2C9434344%2C9434598%2C9435606/hfr/1/sver/3/id/dbd9927bee6b6954/pl/24/mt/1462540367/sparams/as%2Cgcr%2Chfr%2Cid%2Cip%2Cipbits%2Citag%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cplayback_host%2Crequiressl%2Csource%2Cexpire/source/youtube/mv/u/ms/au/signature/0DBBAE0CE87D521EDC680CE13C5973E7E2B99B40.A0C803083B3B58F47F9416A37D9D6764039DBF82/upn/3KVrHwDAcwo/requiressl/yes/pcm2cms/yes/itag/0/gcr/cn/playback_host/r8---sn-a8au-p5qs.googlevideo.com/key/yt6/expire/1462562352/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/ipbits/0
> [DEBUG] get_content: https://s.ytimg.com/yts/jsbin/player-en_US-vflL5aRF-/base.js
> you-get: version 0.4.390, a tiny downloader that scrapes the web.
> you-get: ['http://www.youtube.com/watch?v=29mSe-5raVQ']
> Traceback (most recent call last):
>   File "urllib\request.py", line 1240, in do_open
>   File "http\client.py", line 1083, in request
>   File "http\client.py", line 1128, in _send_request
>   File "http\client.py", line 1079, in endheaders
>   File "http\client.py", line 911, in _send_output
>   File "http\client.py", line 854, in send
>   File "http\client.py", line 1229, in connect
>   File "http\client.py", line 826, in connect
>   File "socket.py", line 711, in create_connection
>   File "socket.py", line 702, in create_connection
> TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get__main__.py", line 92, in main
  File "src\you_get\common.py", line 1274, in main
  File "src\you_get\common.py", line 1189, in script_main
  File "src\you_get\common.py", line 1030, in download_main
  File "src\you_get\common.py", line 1267, in any_download
  File "src\you_get\extractor.py", line 49, in download_by_url
  File "src\you_get\extractors\youtube.py", line 386, in extract
  File "src\you_get\common.py", line 340, in urls_size
  File "src\you_get\common.py", line 340, in <listcomp>
  File "src\you_get\common.py", line 334, in url_size
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 465, in open
  File "urllib\request.py", line 483, in _open
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 1283, in https_open
  File "urllib\request.py", line 1242, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
you-get returned -1

**Comment by microka** [comment]
@soimort-bot 该视频可以在线观看1080p但只能抓取到720p的下载链接

**Comment by kwokts** [comment]
youtube 1080p 使用了 DASH影音分流，youtube-dl 可以下載。
youtube-dl -f 137+140 http://www.youtube.com/watch?v=29mSe-5raVQ

**Comment by microka** [comment]
@kwokts 嗯，我用 youtube-dl 下载回来了，但有个问题，youtube-dl 嗅探到的URL无法直接用IDM进行下载，请问有什么办法吗？

**Comment by soimort** [comment]
This is weird, because `you-get` obvious work for other 1080P videos:
https://www.youtube.com/watch?v=-JAiFo_fsNA

```
$ you-get -di https://www.youtube.com/watch\?v\=-JAiFo_fsNA 
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=-JAiFo_fsNA
[DEBUG] get_content: https://www.youtube.com/watch?v=-JAiFo_fsNA
[DEBUG] get_content: https://s.ytimg.com/yts/jsbin/player-da_DK-vflb3NRgP/base.js
site:                YouTube
title:               壞碑唇 _ 柏林塵埃 Official Music Video
streams:             # Available quality and codecs
    [ DASH ] ____________________________________
    - itag:          136
      container:     mp4
      quality:       1280x720
      size:          46.3 MiB (48564431 bytes)
    # download-with: you-get --itag=136 [URL]

    - itag:          247
      container:     webm
      quality:       1280x720
      size:          30.0 MiB (31464338 bytes)
    # download-with: you-get --itag=247 [URL]

    - itag:          135
      container:     mp4
      quality:       854x480
      size:          22.5 MiB (23600470 bytes)
    # download-with: you-get --itag=135 [URL]

    - itag:          244
      container:     webm
      quality:       854x480
      size:          17.5 MiB (18344238 bytes)
    # download-with: you-get --itag=244 [URL]

    - itag:          134
      container:     mp4
      quality:       640x360
      size:          13.2 MiB (13879256 bytes)
    # download-with: you-get --itag=134 [URL]

    - itag:          243
      container:     webm
      quality:       640x360
      size:          12.1 MiB (12704377 bytes)
    # download-with: you-get --itag=243 [URL]

    - itag:          133
      container:     mp4
      quality:       426x240
      size:          11.2 MiB (11720264 bytes)
    # download-with: you-get --itag=133 [URL]

    - itag:          242
      container:     webm
      quality:       426x240
      size:          8.8 MiB (9244333 bytes)
    # download-with: you-get --itag=242 [URL]

    - itag:          278
      container:     webm
      quality:       256x144
      size:          8.5 MiB (8908188 bytes)
    # download-with: you-get --itag=278 [URL]

    - itag:          160
      container:     mp4
      quality:       256x144
      size:          7.2 MiB (7506605 bytes)
    # download-with: you-get --itag=160 [URL]

    [ DEFAULT ] _________________________________
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          56.1 MiB (58829578 bytes)
    # download-with: you-get --itag=22 [URL]

    - itag:          43
      container:     webm
      quality:       medium
    # download-with: you-get --itag=43 [URL]

    - itag:          18
      container:     mp4
      quality:       medium
    # download-with: you-get --itag=18 [URL]

    - itag:          5
      container:     flv
      quality:       small
    # download-with: you-get --itag=5 [URL]

    - itag:          36
      container:     3gp
      quality:       small
    # download-with: you-get --itag=36 [URL]

    - itag:          17
      container:     3gp
      quality:       small
    # download-with: you-get --itag=17 [URL]
```

I'll see what is going on here.

**Comment by soimort** [comment]
My bad, the video in my last comment doesn't involve any 1080P format. But this one has:

```
$ you-get -di 'https://www.youtube.com/watch?v=DBnC0a6Sdz4'
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=DBnC0a6Sdz4
[DEBUG] get_content: https://www.youtube.com/watch?v=DBnC0a6Sdz4
[DEBUG] get_content: https://s.ytimg.com/yts/jsbin/player-da_DK-vflb3NRgP/base.js
site:                YouTube
title:               麥浚龍 X 謝安琪 - 羅生門 Lyrics Video
streams:             # Available quality and codecs
    [ DASH ] ____________________________________
    - itag:          137
      container:     mp4
      quality:       1920x1080
      size:          48.3 MiB (50644725 bytes)
    # download-with: you-get --itag=137 [URL]

    - itag:          248
      container:     webm
      quality:       1920x1080
      size:          45.8 MiB (48018809 bytes)
    # download-with: you-get --itag=248 [URL]

    - itag:          247
      container:     webm
      quality:       1280x720
      size:          28.6 MiB (30017289 bytes)
    # download-with: you-get --itag=247 [URL]

    - itag:          136
      container:     mp4
      quality:       1280x720
      size:          27.9 MiB (29265037 bytes)
    # download-with: you-get --itag=136 [URL]

    - itag:          244
      container:     webm
      quality:       854x480
      size:          15.7 MiB (16488752 bytes)
    # download-with: you-get --itag=244 [URL]

    - itag:          135
      container:     mp4
      quality:       854x480
      size:          14.3 MiB (14967526 bytes)
    # download-with: you-get --itag=135 [URL]

    - itag:          133
      container:     mp4
      quality:       426x240
      size:          11.6 MiB (12181021 bytes)
    # download-with: you-get --itag=133 [URL]

    - itag:          243
      container:     webm
      quality:       640x360
      size:          9.6 MiB (10061625 bytes)
    # download-with: you-get --itag=243 [URL]

    - itag:          134
      container:     mp4
      quality:       640x360
      size:          8.3 MiB (8666992 bytes)
    # download-with: you-get --itag=134 [URL]

    - itag:          160
      container:     mp4
      quality:       256x144
      size:          7.4 MiB (7756630 bytes)
    # download-with: you-get --itag=160 [URL]

    - itag:          242
      container:     webm
      quality:       426x240
      size:          6.1 MiB (6369414 bytes)
    # download-with: you-get --itag=242 [URL]

    - itag:          278
      container:     webm
      quality:       256x144
      size:          5.9 MiB (6177517 bytes)
    # download-with: you-get --itag=278 [URL]

    [ DEFAULT ] _________________________________
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          38.3 MiB (40202195 bytes)
    # download-with: you-get --itag=22 [URL]

    - itag:          43
      container:     webm
      quality:       medium
    # download-with: you-get --itag=43 [URL]

    - itag:          18
      container:     mp4
      quality:       medium
    # download-with: you-get --itag=18 [URL]

    - itag:          5
      container:     flv
      quality:       small
    # download-with: you-get --itag=5 [URL]

    - itag:          36
      container:     3gp
      quality:       small
    # download-with: you-get --itag=36 [URL]

    - itag:          17
      container:     3gp
      quality:       small
    # download-with: you-get --itag=17 [URL]
```
