### ISSUE TITLE
乐视无法合并视频

### ISSUE THREAD

**Issue by zhihuahuang** [soimort/you-get#1125]
you-get 能下载乐视的视频，但不能合并。下载格式为MP4。

日志如下：
```
you-get: version 0.4.390, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/25333904.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1274, in main
  File "src\you_get\common.py", line 1182, in script_main
  File "src\you_get\common.py", line 1030, in download_main
  File "src\you_get\common.py", line 1267, in any_download
  File "src\you_get\extractors\le.py", line 137, in letv_download
  File "src\you_get\extractors\le.py", line 98, in letv_download_by_vid
  File "src\you_get\common.py", line 765, in download_urls
  File "src\you_get\processor\join_mp4.py", line 914, in concat_mp4
  File "src\you_get\processor\join_mp4.py", line 876, in merge_mp4s
  File "src\you_get\processor\join_mp4.py", line 717, in read_mp4
  File "src\you_get\processor\join_mp4.py", line 708, in parse_atoms
  File "src\you_get\processor\join_mp4.py", line 700, in read_atom
NotImplementedError: b'\x00\x00\xb0\r': 1195376648
you-get returned -1
```

**Comment by pastebt** [comment]
maybe because this: http://libav.org/

> IMPORTANT

 NOTE: This release disables the 'concat' protocol by default as it has recently been identified as a vulnerability vector. 

>

**Comment by soimort** [comment]
装 ffmpeg 或 libav。
