### ISSUE TITLE
下载youtube视频出现问题

### ISSUE THREAD

**Issue by panw3i** [soimort/you-get#1138]
`[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=-wNyEUrxzFU
you-get: version 0.4.390, a tiny downloader that scrapes the web.
you-get: ['http://www.youtube.com/watch?v=-wNyEUrxzFU']
Traceback (most recent call last):
  File "C:\Python35\Lib\urllib\request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python35\Lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "C:\Python35\Lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python35\Lib\http\client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "C:\Python35\Lib\http\client.py", line 911, in _send_output
    self.send(msg)
  File "C:\Python35\Lib\http\client.py", line 854, in send
    self.connect()
  File "C:\Python35\Lib\http\client.py", line 1229, in connect
    super().connect()
  File "C:\Python35\Lib\http\client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Python35\Lib\socket.py", line 711, in create_connection
    raise err
  File "C:\Python35\Lib\socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\Lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python35\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\you-get\py35env\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\desktop\you-get\py35env\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\desktop\you-get\py35env\lib\site-packages\you_get\common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\desktop\you-get\py35env\lib\site-packages\you_get\common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\administrator\desktop\you-get\py35env\lib\site-packages\you_get\common.py", line 1030, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\desktop\you-get\py35env\lib\site-packages\you_get\common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\desktop\you-get\py35env\lib\site-packages\you_get\extractor.py", line 40, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\administrator\desktop\you-get\py35env\lib\site-packages\you_get\extractors\youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "c:\users\administrator\desktop\you-get\py35env\lib\site-packages\you_get\common.py", line 308, in get_content
    response = request.urlopen(req)
  File "C:\Python35\Lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python35\Lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "C:\Python35\Lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "C:\Python35\Lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "C:\Python35\Lib\urllib\request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Python35\Lib\urllib\request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应， 连接尝试失败。>`

**Comment by soimort** [comment]
GFW.

请走代理。
