### ISSUE TITLE
网易，酷我，QQ音乐都无法使用you-get下载

### ISSUE THREAD

**Issue by dxg74120** [soimort/you-get#1141]
应该是由于网易音乐地址中间加# 导致不能使用you-get对音乐进行下载了。
比如以下网易云音乐地址下载将不执行：http://music.163.com/#/song?id=411921852
xxxx@debian:~$ you-get http://music.163.com/#/song?id=411921852 --debug
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by dxg74120** [comment]
xxxx@debian:~$ you-get --debug  http://music.163.com/#/song?id=411921852
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=411921852&ids=[411921852]&csrf_token=
you-get: version 0.4.390, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/song?id=411921852']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/netease.py", line 120, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/netease.py", line 66, in netease_cloud_music_download
    netease_song_download(j["songs"][0], output_dir=output_dir, info_only=info_only)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/netease.py", line 107, in netease_song_download
    output_dir=output_dir, info_only=info_only)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/netease.py", line 110, in netease_download_common
    songtype, ext, size = url_info(url_best)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 357, in url_info
    response = request.urlopen(request.Request(url))
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1271, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1246, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by zhangn1985** [comment]
@soimort-bot please help test: http://music.163.com/#/song?id=411921852

**Comment by dxg74120** [comment]
好吧！估计又是网络问题，请关闭这个问题。
再次谢过

**Comment by nuomi1** [comment]
@dxg74120 在 OS X 试了，zsh with iTerm2，粘贴 URL 时自动对「# ? =」进行转义，去除「# =」转义依然可以识别，去除「?」转义则提示 `zsh: no matches found: http://music.163.com/#/song?id=411921852`。

**Comment by dAxIOnG8** [comment]
I CANT DOWNLOAD MUSIC FROM 163MUSIC TOO

**Comment by dAxIOnG8** [comment]
(D:\Program Files\anaconda) C:\Users\sqc>you-get -d http://music.163.com/#/my/m/music/playlist?id=25417131
[DEBUG] get_content: http://music.163.com/api/playlist/detail?id=25417131&csrf_token=
Downloading cover.jpg ...
 0.0% (  0.0/  0.7MB) ├─────────────────────────────────────────┤[1/1] you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/my/m/music/playlist?id=25417131']
Traceback (most recent call last):
  File "d:\program files\anaconda\lib\urllib\request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "d:\program files\anaconda\lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "d:\program files\anaconda\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "d:\program files\anaconda\lib\http\client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "d:\program files\anaconda\lib\http\client.py", line 911, in _send_output
    self.send(msg)
  File "d:\program files\anaconda\lib\http\client.py", line 854, in send
    self.connect()
  File "d:\program files\anaconda\lib\http\client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "d:\program files\anaconda\lib\socket.py", line 711, in create_connection
    raise err
  File "d:\program files\anaconda\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\program files\anaconda\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\anaconda\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files\anaconda\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 1129, in download_main
    download(url, **kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\extractors\netease.py", line 133, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\extractors\netease.py", line 56, in netease_cloud_music_download
    download_urls([cover_url], "cover", "jpg", 0, new_dir)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 780, in download_urls
    url_save(url, output_filepath, bar, refer = refer, faker = faker, headers = headers)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 472, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 390, in url_size
    response = request.urlopen(url)
  File "d:\program files\anaconda\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "d:\program files\anaconda\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "d:\program files\anaconda\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "d:\program files\anaconda\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\program files\anaconda\lib\urllib\request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "d:\program files\anaconda\lib\urllib\request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试 失败。>
