### ISSUE TITLE
NotImplementedError--www.le.com 

### ISSUE THREAD

**Issue by SharerMax** [soimort/you-get#1156]
**Debug Info**
-----------------------
Merging video parts...
temp\少年包青天13[00].mp4
you-get: version 0.4.390, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/1368629.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1274, in main
  File "src\you_get\common.py", line 1187, in script_main
  File "src\you_get\common.py", line 1030, in download_main
  File "src\you_get\common.py", line 1267, in any_download
  File "src\you_get\extractors\le.py", line 137, in letv_download
  File "src\you_get\extractors\le.py", line 98, in letv_download_by_vid
  File "src\you_get\common.py", line 765, in download_urls
  File "src\you_get\processor\join_mp4.py", line 914, in concat_mp4
  File "src\you_get\processor\join_mp4.py", line 876, in merge_mp4s
  File "src\you_get\processor\join_mp4.py", line 717, in read_mp4
  File "src\you_get\processor\join_mp4.py", line 708, in parse_atoms
  File "src\you_get\processor\join_mp4.py", line 700, in read_atom
NotImplementedError: b'\x00\x00\xb0\r': 1195376648
you-get returned -1
```
 Url: [http://www.le.com/ptv/vplay/1368629.html](http://www.le.com/ptv/vplay/1368629.html) 
 Version: you-get-0.4.390-win32-full.7z 
 Command: you-get -o temp -d http://www.le.com/ptv/vplay/1368629.html

**Comment by soimort** [comment]
Please install `ffmpeg`.
