### ISSUE TITLE
代理使用问题

### ISSUE THREAD

**Issue by kbitlive** [soimort/you-get#1157]
> you-get --debug -x 127.0.0.1:65500 'https://www.youtube.com/watch?v=jNQXAC9IVR
w'
you-get: version 0.4.390, a tiny downloader that scrapes the web.
you-get: ["'https://www.youtube.com/watch?v=jNQXAC9IVRw'"]
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1274, in main
  File "src\you_get\common.py", line 1187, in script_main
  File "src\you_get\common.py", line 1030, in download_main
  File "src\you_get\common.py", line 1266, in any_download
  File "src\you_get\common.py", line 1257, in url_to_module
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 826, in connect
  File "socket.py", line 693, in create_connection
  File "socket.py", line 732, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed
you-get returned -1

使用ss代理

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by soimort** [comment]
`-x` 暂时不支持 SOCKS 代理。参见 #1046。

可用 proxychains。
