### ISSUE TITLE
[xiami] downloading albums broken

### ISSUE THREAD

**Issue by L2501** [soimort/you-get#1165]
```
you-get --debug 'http://www.xiami.com/album/2100332592'
Site:       Xiami.com
Title:      Hello darkness, my dear friend
Type:       Unknown type (None)
Size:       7.11 MiB (7455288 Bytes)

Downloading 01.Hello darkness, my dear friend.mp3 ...
 100% (  7.1/  7.1MB) ├██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[1/1]  476 kB/s

you-get: version 0.4.424, a tiny downloader that scrapes the web.
you-get: ['http://www.xiami.com/album/2100332592']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.424', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1277, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1190, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1033, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1270, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractors/xiami.py", line 149, in xiami_download
    xiami_download_album(id, output_dir, merge, info_only)
  File "/usr/lib/python3.5/site-packages/you_get/extractors/xiami.py", line 120, in xiami_download_album
    song_title = i.getElementsByTagName("title")[0].firstChild.nodeValue
IndexError: list index out of range
```

downloading individual songs works but the titles are missing

**Comment by L2501** [comment]
```
result of the album xml here
http://www.xiami.com/song/playlist/id/2100332592/type/1 > http://paste2.org/HVmGbbNH
```

**Comment by zhangn1985** [comment]
not a logic error.
this is a coding mistake.
`getElementsByTagName("track")``  returns twice track count
<track>  ---> this is index 0 item
</track>  ---> this is index 1 item
when use it in for loop, and get index=1, </track>  will be used, then get en error.

**Comment by soimort** [comment]
Xiami is currently not available overseas, so we're not able to fix it. Anyone would like to give it a try?

**Comment by zhangn1985** [comment]
with a XML below:
```
<tag>
   aaa
</tar>
<tag>
   bbb
</tag>
```
``tag = getElementsByTagName('tag')`` returns: a tag list.
but `tag[0]` is first `<tag>`, `tag[1]` is first `</tag>`

when using `for t in tag:` , `</tag>` will be used, and get this error.

**Comment by cnbeining** [comment]
That's why I hate XML....

**Comment by mozbugbox** [comment]
`lxml` with `xpath` should be used to parse xml.
