### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by zdrjson** [soimort/you-get#1168]
➜  ~ pip3 install --upgrade you-get
Requirement already up-to-date: you-get in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get-0.4.424-py3.5.egg
➜  ~ you-get -i 'https://www.youtube.com/watch?v=jNQXAC9IVRw'
zsh: command not found: you-get

**Comment by jdfq** [comment]
我也是：
you-get：未找到命令

**Comment by soimort** [comment]
请检查你的PATH。

**Comment by zdrjson** [comment]
➜  ~ pip3 install you-get
Requirement already satisfied (use --upgrade to upgrade): you-get in ./Library/Python/3.5/lib/python/site-packages/you_get-0.4.424-py3.5.egg
如何fix?

**Comment by zdrjson** [comment]
➜  ~ sudo pip3 install you-get
The directory '/Users/json/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/json/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): you-get in ./Library/Python/3.5/lib/python/site-packages/you_get-0.4.424-py3.5.egg

**Comment by cnbeining** [comment]
还是你的PATH问题。


2016年5月26日星期四，zdrjson <notifications@github.com> 写道：

**Comment by zdrjson** [comment]
我知道有问题，那怎么改呀？

**Comment by soimort** [comment]
`pip show -f`

**Comment by zdrjson** [comment]
➜  ~ pip show - you-get
zsh: command not found: pip
➜  ~ pip3 show - you-get
zsh: /usr/local/bin/pip3: bad interpreter: /usr/local/opt/python3/bin/python3.5: no such file or directory

**Comment by soimort** [comment]
。。您还是别用pip了吧。

直接download下来解压了就能用的。

**Comment by zdrjson** [comment]
➜  Downloads you-get-develop
➜  you-get-develop sudo python3 setup.py install
Password:
➜  you-get-develop ..
➜  Downloads ..
➜  ~ you-get
zsh: command not found: you-get
还是不行呀

**Comment by soimort** [comment]
```
$ ./you-get
```

**Comment by zdrjson** [comment]
什么意思？大神，你能说明白点?在哪里敲这个这个命令？是这个敲什么命令吗？

**Comment by soimort** [comment]
![screenshot from 2016-05-27 12-08-27](https://cloud.githubusercontent.com/assets/342945/15605049/c7497a9c-2403-11e6-88d5-bc7b211d1773.png)

只能帮你到这里了。去补补命令行的基本常识吧。

**Comment by gonejack** [comment]
git clone https://github.com/soimort/you-get.git

cd you-get

python3 you-get 小视频地址

**Comment by zdrjson** [comment]
命令安装不上, 下面在桌面就不行。
➜  Desktop python3 you-get http://www.meipai.com/media/454570774
/Library/Frameworks/Python.framework/Versions/3.5/Resources/Python.app/Contents/MacOS/Python: can't open file 'you-get': [Errno 2] No such file or directory

**Comment by zdrjson** [comment]
按照作者方式安装的，不知道怎么就错了。

**Comment by soimort** [comment]
还是那句话，你需要去补一下命令行的基本常识。

`you-get` 不在你的**当前路径**中，当然运行不了。
你需要把 **`you-get` 所在的目录**加入到 `PATH`。

**Comment by linhua55** [comment]
当你在命令行中输入 `you-get` 的时候, shell会首先查询`PATH`环境变量中的路径，看看能不能在这些路径下找到`you-get`这个可执行文件, 如果没有, 则报错, 并提示找不到.
如果`you-get`可执行文件在当前路径下, 则可以使用 `./you-get` 这种相对路径的形式调用, 当然也可以使用绝对路径的形式调用.

**Comment by soimort** [comment]
pip 安装的路径问题解决方法如下

![screenshot from 2016-05-27 17-57-22](https://cloud.githubusercontent.com/assets/342945/15613660/c6924706-2434-11e6-9f9a-0f46e3e96d67.png)

第二条命令放到 `.bashrc` 里。记得把 `/home/soimort/.local/bin` 给改了。

**Comment by soimort** [comment]
刚看了一下，OS X 上 binary 所在的路径是  `/Library/Frameworks/Python.framework/Versions/3.5/bin`

所以你需要 ：

```
$ export PATH=/Library/Frameworks/Python.framework/Versions/3.5/bin:$PATH
```

**Comment by zdrjson** [comment]
通过home-brew安装后，mac终端试了一下，
➜  ~ you-get --debug 'https://www.youtube.com/watch?v=jNQXAC9IVRw'
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=jNQXAC9IVRw
you-get: version 0.4.424, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=jNQXAC9IVRw']
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1237, in connect
    server_hostname=server_hostname)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/you-get/0.4.424/libexec/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.424', 'console_scripts', 'you-get')()
  File "/Users/json/Library/Python/3.5/lib/python/site-packages/you_get-0.4.424-py3.5.egg/you_get/__main__.py", line 92, in main
  File "/Users/json/Library/Python/3.5/lib/python/site-packages/you_get-0.4.424-py3.5.egg/you_get/common.py", line 1291, in main
  File "/Users/json/Library/Python/3.5/lib/python/site-packages/you_get-0.4.424-py3.5.egg/you_get/common.py", line 1204, in script_main
  File "/Users/json/Library/Python/3.5/lib/python/site-packages/you_get-0.4.424-py3.5.egg/you_get/common.py", line 1041, in download_main
  File "/Users/json/Library/Python/3.5/lib/python/site-packages/you_get-0.4.424-py3.5.egg/you_get/common.py", line 1284, in any_download
  File "/Users/json/Library/Python/3.5/lib/python/site-packages/you_get-0.4.424-py3.5.egg/you_get/extractor.py", line 40, in download_by_url
  File "/Users/json/Library/Python/3.5/lib/python/site-packages/you_get-0.4.424-py3.5.egg/you_get/extractors/youtube.py", line 143, in prepare
  File "/Users/json/Library/Python/3.5/lib/python/site-packages/you_get-0.4.424-py3.5.egg/you_get/common.py", line 315, in get_content
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:645)>

国内youku，腾讯试一下可以。以后升级通过home-brew可以吗？

➜  Desktop you-get http://v.qq.com/prev/d/df4fnnni5a95pjs.html\?vid\=i0020w40343
Site:       QQ.com
Title:      昙花梦动作版片花：乔振宇变民国探长帅炸天
Type:       MPEG-4 video (video/mp4)
Size:       4.1 MiB (4303583 Bytes)

Downloading 昙花梦动作版片花：乔振宇变民国探长帅炸天.mp4 ...
 100% (  4.1/  4.1MB) ├██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[1/1]  211 kB/s
