### ISSUE TITLE
无法下载Letv蜡笔小新视频

### ISSUE THREAD

**Issue by xxmali** [soimort/you-get#1186]
你好，可以下载Letv海绵宝宝视频，但蜡笔小新的一直报错。麻烦看下错误信息。
root@my:/# you-get --debug http://www.le.com/ptv/vplay/2060517.html
[DEBUG] get_content: http://www.le.com/ptv/vplay/2060517.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=2060517&platid=1&splatid=101&format=1&tkey=1467208852&domain=www.letv.com
you-get: version 0.4.424, a tiny downloader that scrapes the web.you-get: ['http://www.le.com/ptv/vplay/2060517.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/**main**.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1277, in main
    script_main('you-get', any_download, any_download_playlist, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1190, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1033, in download_main
    download(url, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1270, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/le.py", line 137, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/le.py", line 90, in letv_download_by_vid
    ext , urls = video_info(vid,**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/le.py", line 61, in video_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'

**Comment by xxmali** [comment]
IP问题
