### ISSUE TITLE
腾讯视频专辑中的内容，仅能解析到列表中的第一个视频

### ISSUE THREAD

**Issue by samon1688** [soimort/you-get#1187]
使用you get 下载专辑列表中的视频，仅能得到列表中的第一个视频内容，列表中的其他视频无法解析下载。是不支持腾讯视频播放列表吗？
you-get: version 0.4.424, a tiny downloader that scrapes the web.

>you-get -i http://v.qq.com/cover/m/mp7nxcoq81t2pc5.html
Site:       QQ.com
Title:      医考：张老师讲传染病 性病
Type:       MPEG-4 video (video/mp4)
Size:       431.28 MiB (452230459 Bytes)

>you-get -i http://v.qq.com/cover/m/mp7nxcoq81t2pc5.html?vid=u0014qfd36b
Site:       QQ.com
Title:      医考：张老师讲传染病 性病
Type:       MPEG-4 video (video/mp4)
Size:       431.28 MiB (452230459 Bytes)

>you-get -i http://v.qq.com/cover/m/mp7nxcoq81t2pc5.html?vid=a0014llg3i9
Site:       QQ.com
Title:      医考：张老师讲传染病 性病
Type:       MPEG-4 video (video/mp4)
Size:       431.28 MiB (452230459 Bytes)

>you-get -dl http://v.qq.com/cover/m/mp7nxcoq81t2pc5.html?vid=a0014llg3i9
you-get: version 0.4.424, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/cover/m/mp7nxcoq81t2pc5.html?vid=a0014llg3i9']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1277, in main
  File "src\you_get\common.py", line 1190, in script_main
  File "src\you_get\common.py", line 1031, in download_main
  File "src\you_get\common.py", line 1274, in any_download_playlist
  File "src\you_get\common.py", line 895, in f
NotImplementedError: Playlist is not supported for qq
you-get returned -1

**Comment by nuomi1** [comment]
```
➜  ~ yg -i http://v.qq.com/cover/m/mp7nxcoq81t2pc5.html
Site:       QQ.com
Title:      医考：张老师讲传染病 性病
Type:       MPEG-4 video (video/mp4)
Size:       431.28 MiB (452230459 Bytes)

➜  ~ yg -i http://v.qq.com/cover/m/mp7nxcoq81t2pc5.html\?vid\=a0014llg3i9
Site:       QQ.com
Title:      孙老师讲中医内科
Type:       MPEG-4 video (video/mp4)
Size:       428.26 MiB (449061500 Bytes)
```

Please [upgrade the latest version from GitHub](https://github.com/soimort/you-get/pull/1183/commits/c372b09e5957b6cfe143d9ce58c56ce224b6128c).

**Comment by samon1688** [comment]
很奇怪，我的已经是最新版本了0.4.424，在我家里和工作单位里运行同样的命令都只能解析到第一个视频。

**Comment by nuomi1** [comment]
PyPI, version 0.4.424, [uploaded on 2016-05-23](https://pypi.python.org/pypi/you-get).
GitHub, version 0.4.424, [committed on 2016-05-29](https://github.com/soimort/you-get/commit/cb39f4b9f34066b7d4c053f7922420d38dd88e72).

**Comment by samon1688** [comment]
我这边还是不行，找另一个同事试了也是同样的问题，不知道是不是因为用的是windows预装包的原因。我的下载地址：https://github.com/soimort/you-get/releases/download/v0.4.424/you-get-0.4.424-win32-full.7z

**Comment by lki2019** [comment]
列表里那么多视频，你想一下子全部解析出来全部下载？好像不支持多线程下载吧
你挨个解析下载就好了，
