### ISSUE TITLE
miomio.tv cannot download video file anymore

### ISSUE THREAD

**Issue by jizg** [soimort/you-get#1195]
I can see the video on miomio.tv in browser with proxy enabled. But failed to download. Sample video link: http://www.miomio.tv/watch/cc274254/
debug output as follows

```
Traceback (most recent call last):
  File "/opt/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.424', 'console_scripts', 'you-get')()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1291, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1204, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, js
on_output=json_output, caption=caption)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1041, in download_main
    download(url, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1284, in any_download
    m.download(url, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/you_get/extractors/miomio.py", line 17, in miomio_do
wnload
    t = r1(r'type=(\w+)', flashvars)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/you_get/common.py", line 148, in r1
    m = re.search(pattern, text)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

**Comment by cnbeining** [comment]
@soimort-bot Can you kindly check this link for me? Thanks. http://www.miomio.tv/watch/cc274254/

**Comment by zhangn1985** [comment]
![screenshot at 2016-06-08 09 52 11](https://cloud.githubusercontent.com/assets/832666/15880345/ec042e4a-2d5e-11e6-8986-d92788f387b2.png)

难道我的打开方式有问题？

**Comment by jizg** [comment]
需要翻墙打开。

**Comment by cnbeining** [comment]
卡死了我的整个Chrome。哎呀啥玩意。。。

**Comment by yan12125** [comment]
This video, as well as some other previous reports, use a new 'h5' player. I have a WIP implementation at youtube-dl: yan12125/youtube-dl@9d6642bca4915b491cc9ebc8c15fed68c31926bc.

**Comment by cnbeining** [comment]
I am a little bit curious that where are they hot linking... Just saying.

2016年6月8日星期三，Yen Chi Hsuan <notifications@github.com> 写道：

**Comment by jizg** [comment]
I also found that this might be related to the player, as my chrome video download plugin also cannot download the video anymore.

**Comment by soimort** [comment]
@soimort-bot Please test this: http://www.miomio.tv/watch/cc274254/

**Comment by unknow123** [comment]
yeah! same problem with me :(
please fix it

**Comment by jizg** [comment]
@yan12125 's comment is correct. I can download now use his patch on youtube-dl.

**Comment by rosynirvana** [comment]
miomio.tv is dead
