### ISSUE TITLE
Some youtube video is triggering exceptions

### ISSUE THREAD

**Issue by kungfucop** [soimort/you-get#1199]
you-get --debug https://www.youtube.com/watch?v=bQYeSXpC244
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 1133, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 951, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 843, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 1126, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/extractor.py", line 44, in download_by_url
    self.extract(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/extractors/youtube.py", line 202, in extract
    sig = self.__class__.decipher(js, s)
  File "/usr/local/lib/python3.4/site-packages/you_get/extractors/youtube.py", line 53, in decipher
    f1def = re.sub(r'([$\w]+\.)([$\w]+\(\w+,\d+\))', r'\2', f1def)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/re.py", line 175, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by nuomi1** [comment]
```
➜  ~ pyg -i https://www.youtube.com/watch\?v\=bQYeSXpC244
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.11/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.11
[proxychains] DLL init: proxychains-ng 4.11
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  www.youtube.com:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  www.youtube.com:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  s.ytimg.com:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  r9---sn-a5m7ln7s.googlevideo.com:443  ...  OK
site:                YouTube
title:               Floyd Mayweather Defensive Genius (Defense Highlights) HD
streams:             # Available quality and codecs
    [ DASH ] ____________________________________
    - itag:          136
      container:     mp4
      quality:       1280x720
      size:          123.4 MiB (129403129 bytes)
    # download-with: you-get --itag=136 [URL]

    - itag:          247
      container:     webm
      quality:       1280x720
      size:          94.2 MiB (98748100 bytes)
    # download-with: you-get --itag=247 [URL]

    - itag:          135
      container:     mp4
      quality:       854x480
      size:          66.5 MiB (69756777 bytes)
    # download-with: you-get --itag=135 [URL]

    - itag:          244
      container:     webm
      quality:       854x480
      size:          51.0 MiB (53481501 bytes)
    # download-with: you-get --itag=244 [URL]

    - itag:          134
      container:     mp4
      quality:       640x360
      size:          39.8 MiB (41740054 bytes)
    # download-with: you-get --itag=134 [URL]

    - itag:          243
      container:     webm
      quality:       640x360
      size:          31.3 MiB (32862058 bytes)
    # download-with: you-get --itag=243 [URL]

    - itag:          133
      container:     mp4
      quality:       426x240
      size:          21.4 MiB (22473728 bytes)
    # download-with: you-get --itag=133 [URL]

    - itag:          242
      container:     webm
      quality:       426x240
      size:          20.6 MiB (21586881 bytes)
    # download-with: you-get --itag=242 [URL]

    - itag:          160
      container:     mp4
      quality:       256x144
      size:          13.6 MiB (14293955 bytes)
    # download-with: you-get --itag=160 [URL]

    - itag:          278
      container:     webm
      quality:       256x144
      size:          13.3 MiB (13995016 bytes)
    # download-with: you-get --itag=278 [URL]

    [ DEFAULT ] _________________________________
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          166.0 MiB (174061522 bytes)
    # download-with: you-get --itag=22 [URL]

    - itag:          43
      container:     webm
      quality:       medium
    # download-with: you-get --itag=43 [URL]

    - itag:          18
      container:     mp4
      quality:       medium
    # download-with: you-get --itag=18 [URL]

    - itag:          5
      container:     flv
      quality:       small
    # download-with: you-get --itag=5 [URL]

    - itag:          36
      container:     3gp
      quality:       small
    # download-with: you-get --itag=36 [URL]

    - itag:          17
      container:     3gp
      quality:       small
    # download-with: you-get --itag=17 [URL]
```

**Comment by soimort** [comment]
@soimort-bot test this link: https://www.youtube.com/watch?v=bQYeSXpC244

**Comment by soimort** [comment]
You'll need to use either quotes (as in @soimort-bot's comment) or character escaping (as in @nuomi1's comment) correctly.

**Comment by soimort** [comment]
Plus, I think your `you-get` might be quite out-of-date.
