### ISSUE TITLE
[PPTV] Became invalid

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#12]
```sh
➜  you-get git:(master) ✗ ./you-get -i http://v.pptv.com/show/KZvXVb0jk9E0sho.html
Traceback (most recent call last):
  File "./you-get", line 6, in <module>
    main()
  File "/home/soimort/Source/you-get/you_get/main.py", line 55, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/soimort/Source/you-get/you_get/common.py", line 643, in script_main
    download_main(download, download_playlist, args, playlist, output_dir, merge, info_only)
  File "/home/soimort/Source/you-get/you_get/common.py", line 563, in download_main
    download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/soimort/Source/you-get/you_get/main.py", line 48, in any_download
    m.download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/soimort/Source/you-get/you_get/downloader/pptv.py", line 36, in pptv_download
    pptv_download_by_id(id, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/soimort/Source/you-get/you_get/downloader/pptv.py", line 15, in pptv_download_by_id
    st = r1(r'<st>([^<>]+)</st>', xml).encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by soimort** [comment]
This issue is no longer relevant - See #447 for now.
