### ISSUE TITLE
problem in download in facebook

### ISSUE THREAD

**Issue by cleobatista** [soimort/you-get#1203]
I'm trying to download this video:
www.facebook.com/460410410646835/videos/1137613349593201/
Using python 3.5.1+
I've tried in another proxy (in another country and here in Brazil too), but unsucessfully :(

```
[cleo@cleo:~$ you-get --debug 'www.facebook.com/460410410646835/videos/1137613349593201/'
Site:       Facebook.com
you-get: version 0.4.424, a tiny downloader that scrapes the web.
you-get: ['www.facebook.com/460410410646835/videos/1137613349593201/']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/cleo/.local/lib/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/cleo/.local/lib/python3.4/site-packages/you_get/common.py", line 1277, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/cleo/.local/lib/python3.4/site-packages/you_get/common.py", line 1190, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/cleo/.local/lib/python3.4/site-packages/you_get/common.py", line 1033, in download_main
    download(url, **kwargs)
  File "/home/cleo/.local/lib/python3.4/site-packages/you_get/common.py", line 1270, in any_download
    m.download(url, **kwargs)
  File "/home/cleo/.local/lib/python3.4/site-packages/you_get/extractors/facebook.py", line 23, in facebook_download
    print_info(site_info, title, type, size)
  File "/home/cleo/.local/lib/python3.4/site-packages/you_get/common.py", line 968, in print_info
    maybe_print("Title:     ", unescape_html(tr(title)))
  File "/usr/lib/python3.4/html/__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable
]
```

**Comment by soimort** [comment]
@soimort-bot test this link: http://www.facebook.com/460410410646835/videos/1137613349593201/

**Comment by soimort** [comment]
Too many videos extracted from that Facebook page and I can't seem to verify which is the one wanted, so let's download them all.
