### ISSUE TITLE
b站好像又挂了

### ISSUE THREAD

**Issue by ingbyr** [soimort/you-get#1210]
G:\GUI-YouGet\app>you-get -d http://www.bilibili.com/video/av4995866/
[DEBUG] get_content: http://www.bilibili.com/video/av4995866/
[DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=8e9fc618fbd41e28&cid=8115270
Site:       bilibili.com
Title:      短裙全明星Nobody4 Plus
Type:       Unknown type ()
Size:       0.0 MiB (0 Bytes)

you-get: version 0.4.424, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av4995866/']
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1277, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1190, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1033, in download_main
    download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1270, in any_download
    m.download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\extractors\bilibili.py", line 155, in bilibili_download
    info_only=info_only)
  File "c:\python34\lib\site-packages\you_get\extractors\bilibili.py", line 99, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "c:\python34\lib\site-packages\you_get\common.py", line 679, in download_urls
    assert urls
AssertionError

**Comment by zhangn1985** [comment]
@ingbyr 很快就会挂了。

**Comment by ingbyr** [comment]
似乎可以了。。
