### ISSUE TITLE
搜狐vip专用视频无法下载

### ISSUE THREAD

**Issue by defia** [soimort/you-get#1223]
`you-get: version 0.4.455, a tiny downloader that scrapes the web.
you-get: ['http://tv.sohu.com/20160625/n456228856.shtml']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1291, in main
  File "src\you_get\common.py", line 1204, in script_main
  File "src\you_get\common.py", line 1041, in download_main
  File "src\you_get\common.py", line 1284, in any_download
  File "src\you_get\extractors\sohu.py", line 38, in sohu_download
KeyError: 'oriVid'
you-get returned -1`

我看了下源代码,然后看了下http://hot.vrs.sohu.com/vrs_flash.action?vid=3102515 这个返回里并没有oriVid,导致了该问题.

`{"play":1,"status":13,"id":3102515,"tvid":84236488,"pid":9133219,"url":"http://tv.sohu.com/20160625/n456228856.shtml","norVid":3102516,"highVid":3102515,"superVid":3102517,"coverImg":"http://photocdn.sohu.com/20160624/vrs_1466779187293_84236488.jpg","tvfee":1}
`

不过顺带说一句,该视频是有原画画质可以看的..

**Comment by soimort** [comment]
需要VIP会员的视频肯定是没法下载的。

**Comment by defia** [comment]
我是传了vip的cookie的...
只是现在使用的方法不能抓取到下载链接 我人工查看了浏览器请求最后还是找到方法下载了的

**Comment by soimort** [comment]
就算传了cookie，会员视频的解析套路也可能与常规视频有所不同。
不知道 http://hot.vrs.sohu.com/vrs_flash.action?vid=3102515 返回的结果里面有没有 clipsURL，如果没有这个就是不行的。

希望有帐号的人能来提PR。

**Comment by defia** [comment]
目前我这边看下来,他确实访问了这个url,但是加了额外的参数,返回内容也跟一般的不同..不过返回内容里确实有实际视频的url 

目前没有时间去仔细研究这些额外参数的由来,希望能给其他朋友带来一些提示吧

**Comment by lamlam123tld3** [comment]
sohu has an resolution called blue which cannot be obtained simply through http://hot.vrs.sohu.com/vrs_flash.action?vid=

**Comment by lamlam123tld3** [comment]
Through this api get vid & aid (blue>original>super>high>nor)
http://api.tv.sohu.com/v4/video/info/$vid.json?api_key=695fe827ffeb7d74260a813025970bd5

through this with VIP cookie (ppinf & pprdig) get mkey
https://api.store.sohu.com/film/pc/checkpermission?aid=$aid&vid=$vid

http://hot.vrs.sohu.com/vrs_flash.action?vid=$vid&mkey=$mkey

**Comment by qq286023414** [comment]
What the lamlam123tld3 said is OK.
I have got it.
Thanks

**Comment by Jeffrey-ZF** [comment]
What the lamlam123tld3 said is OK.
I have got it.
Thanks

**Comment by Jeffrey-ZF** [comment]
What the @lamlam123tld3  said is OK.
I have got it.
Thanks @lamlam123tld3
