### ISSUE TITLE
bilibili 剧番专辑无法解析下载

### ISSUE THREAD

**Issue by sosmygirl** [soimort/you-get#1226]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

`C:\Users\lxxx>you-get
 -d http://bangumi.bilibili.com/anime/v/90797
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/90797
you-get: version 0.4.455, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/v/90797']
Traceback (most recent call last):
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lee\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1291, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1204, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1041, in download_main
    download(url, **kwargs)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1284, in any_download
    m.download(url, **kwargs)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\bilibili.py", line 131, in bilibili_download
    assert flashvars
AssertionError`

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]
bilibili 剧番最近更新栏目中url为 **http://bangumi.bilibili.com**的无法解析下载

**Comment by soimort** [comment]
@soimort-bot test this now: http://bangumi.bilibili.com/anime/v/90797

**Comment by l2dy** [comment]
Not working again at 0.4.523 from pip. (Python 3.5.2)

```
$ you-get -di http://bangumi.bilibili.com/anime/v/90797
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/90797
[DEBUG] get_content: http://www.bilibili.com/video/av5073214/
[DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=f3bb208b3d081dc8&cid=8242543
Site:       bilibili.com
Title:      狐妖小红娘 28 月红篇如期到来！
Type:       Unknown type ()
Size:       0.0 MiB (0 Bytes)
```
