### ISSUE TITLE
[IQIYI]爱奇艺很多老视频不能下载.

### ISSUE THREAD

**Issue by Abirdcfly** [soimort/you-get#1228]
Please make sure these boxes are checked before submitting your issue – thank you!
- [Y] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [Y] Your `you-get` is up-to-date.
- [Y] I have read https://github.com/soimort/you-get/wiki/FAQ and tried to do so.
- [Y] The issue is not yet reported on https://github.com/soimort/you-get/issues or  https://github.com/soimort/you-get/wiki/Known-Bugs. If so, please add your comments under the existing issue.
- [Y] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:
(这是develop版.)

```
[DEBUG] get_content: http://cache.m.iqiyi.com/jp/tmts/285198/e489f7d654e24866a11bf5affd5f2186/?platForm=h5&rate=2&tvid=285198&vid=e489f7d654e24866a11bf5affd5f2186&cupid=qc_100001_100186&type=mp4&olimit=0&agenttype=13&src=d846d0c32d664d32b6b54ea48997a589&sc=1c34f9fa5e2226cb5712983c252a3462&t=1467012886424&__jsT=null
[DEBUG] get_content: http://cache.m.iqiyi.com/jp/tmts/285198/e489f7d654e24866a11bf5affd5f2186/?platForm=h5&rate=1&tvid=285198&vid=e489f7d654e24866a11bf5affd5f2186&cupid=qc_100001_100186&type=mp4&olimit=0&agenttype=13&src=d846d0c32d664d32b6b54ea48997a589&sc=fb09b5a18f15a8b0fc7b3d54ac2e172f&t=1467012886644&__jsT=null
you-get: version 0.4.455, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/dianshiju/20121002/7c440ce93024be7f.html']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/abirdcfly/桌面/工作/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/abirdcfly/桌面/工作/you-get/src/you_get/common.py", line 1291, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/abirdcfly/桌面/工作/you-get/src/you_get/common.py", line 1204, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/abirdcfly/桌面/工作/you-get/src/you_get/common.py", line 1041, in download_main
    download(url, **kwargs)
  File "/home/abirdcfly/桌面/工作/you-get/src/you_get/common.py", line 1284, in any_download
    m.download(url, **kwargs)
  File "/home/abirdcfly/桌面/工作/you-get/src/you_get/extractor.py", line 51, in download_by_url
    self.download(**kwargs)
  File "/home/abirdcfly/桌面/工作/you-get/src/you_get/extractor.py", line 185, in download
    stream_id = self.streams_sorted[0]['id'] if 'id' in self.streams_sorted[0] else self.streams_sorted[0]['itag']
IndexError: list index out of range

```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> 我在学习爬虫.爬了爱奇艺的排行榜,想用you-get把爬到的视频下载下来,发现很多视频,应该是爱奇艺版本的问题,并不能被you-get下载.虽然这些视频算"老"了,不过尚在排行榜的话,访问量应该还是可观的吧...
> 比如:
> `http://www.iqiyi.com/dianshiju/20121002/7c440ce93024be7f.html`  
> `http://yule.iqiyi.com/20121206/11c25ed634c82443.html`
> `http://www.iqiyi.com/edu/20130304/667dcba1d9da1448.html`  
> `http://www.iqiyi.com/dianying/20130701/04e9061b339569d8.html`
> `http://www.iqiyi.com/jilupian/20100428/n6754.html`
> [OR HAVE SOME :icecream:!]

**Comment by zhangn1985** [comment]
的确不能放了。

**Comment by rosynirvana** [comment]
前三个视频现在可以
```
~ you-get -di 'http://www.iqiyi.com/dianshiju/20121002/7c440ce93024be7f.html'

[DEBUG] get_response: http://www.iqiyi.com/dianshiju/20121002/7c440ce93024be7f.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/118519800/e489f7d654e24866a11bf5affd5f2186/?t=1500160311951&sc=cce824f806f3b0cad4c22bcff1a650a9&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               我是特种兵之利刃出鞘第1集
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: you-get --format=LD [URL]

➜  ~ you-get -di 'http://yule.iqiyi.com/20121206/11c25ed634c82443.html'
[DEBUG] get_response: http://yule.iqiyi.com/20121206/11c25ed634c82443.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/122684700/7289a0a89c1e24ce6da52b87aa248187/?t=1500160328378&sc=e11c6e3a60014553c4d856862e597c16&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               我们约会吧_20121206期
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: you-get --format=LD [URL]

➜  ~ you-get -di 'http://www.iqiyi.com/edu/20130304/667dcba1d9da1448.html'
[DEBUG] get_response: http://www.iqiyi.com/edu/20130304/667dcba1d9da1448.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/130858500/9e8d3aa37ca04c2cb12f3191b51f5ad0/?t=1500160341320&sc=e5a58882109865a11603a1812afd6c57&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               幼儿经典童话故事大全第1集
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: you-get --format=LD [URL]
```

第四个网页版上也不能播，客户端里搜不到

第五个属于 #1861
