### ISSUE TITLE
这个 B 站的专辑下载不了，不知道是不是个案，很多其他视频都是可以下载的

### ISSUE THREAD

**Issue by cisolarix** [soimort/you-get#1247]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
➜  Downloads you-get --debug http://www.bilibili.com/video/av2593414/
[DEBUG] get_content: http://www.bilibili.com/video/av2593414/
you-get: version 0.4.455, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av2593414/']
Traceback (most recent call last):
  File "/Users/dengyanming/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/Users/dengyanming/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/dengyanming/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/common.py", line 1328, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/dengyanming/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/common.py", line 1241, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/dengyanming/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/Users/dengyanming/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/common.py", line 1321, in any_download
    m.download(url, **kwargs)
  File "/Users/dengyanming/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/extractors/bilibili.py", line 136, in bilibili_download
    assert flashvars
AssertionError
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [舔 :icecream:!]

**Comment by cisolarix** [comment]
原来是需要登录才能播放。
这种情况该如何处理呢？

**Comment by cnbeining** [comment]
https://github.com/soimort/you-get/wiki/Bilibili

**Comment by cisolarix** [comment]
@cnbeining 好的，多谢，我试下看看
