### ISSUE TITLE
unable to download vkontakte videos with firefox cookies

### ISSUE THREAD

**Issue by mapleaimer** [soimort/you-get#1248]
## you-get is the latest version, and i used to download videos from www.aqiyi.com or youku...
but recently when i tried to download videos from vkontakte, some errors just occured~
debug information as below, anyone help?

C:\Users\maple>you-get -c C:\\Users\\maple\\AppData\\Roaming\\Mozilla\\Firefox\\
Profiles\\"lz5el7ec.default"\\cookies.sqlite --debug http://vk.com/id262353410#/
videos-46371384?section=all&z=video-46371384_170674389%2Fclub46371384%2Calbum-46
371384%2Fpl_-46371384
[DEBUG] get_content: http://vk.com/id262353410#/videos-46371384?section=all
you-get: version 0.4.455, a tiny downloader that scrapes the web.
you-get: ['http://vk.com/id262353410#/videos-46371384?section=all']
Traceback (most recent call last):
  File "d:\python\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\python\lib\site-packages\you_get\common.py", line 1291, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\python\lib\site-packages\you_get\common.py", line 1204, in script_mai
n
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "d:\python\lib\site-packages\you_get\common.py", line 1041, in download_m
ain
    download(url, **kwargs)
  File "d:\python\lib\site-packages\you_get\common.py", line 1284, in any_downlo
ad
    m.download(url, **kwargs)
  File "d:\python\lib\site-packages\you_get\extractors\vk.py", line 8, in vk_dow
nload
    video_page = get_content(url)
  File "d:\python\lib\site-packages\you_get\common.py", line 315, in get_content

    response = request.urlopen(req)
  File "d:\python\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\python\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "d:\python\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\python\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "d:\python\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\python\lib\urllib\request.py", line 676, in http_error_302
    self.inf_msg + msg, headers, fp)
urllib.error.HTTPError: HTTP Error 302: The HTTP server returned a redirect erro
r that would lead to an infinite loop.
The last 30x error message was:
Found
'z' is not recognized as an internal or external command,
operable program or batch file.

**Comment by MShel** [comment]
there is a bug there, but in your query you are missing quotes, so you get picks everything before the first  & which is an address of album -> as a result it fails.  should be:

> you-get -c C:\Users\maple\AppData\Roaming\Mozilla\Firefox\
Profiles\"lz5el7ec.default"\cookies.sqlite --debug "http://vk.com/id262353410#/
videos-46371384?section=all&z=video-46371384_170674389%2Fclub46371384%2Calbum-46
371384%2Fpl_-46371384"

**Comment by cnbeining** [comment]
True. This is a *nix bug...

**Comment by soimort** [comment]
Fixed by #1264.
