### ISSUE TITLE
B站无法下载独家视频

### ISSUE THREAD

**Issue by EVJOHN** [soimort/you-get#1250]
[DEBUG] get_content: http://bilibili.com/video/av5158525/
[DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=f3bb208b3d081dc8&cid=8414875
Site:       bilibili.com
Title:      【4月】机动战士敢达独角兽RE:0096 13【独家正版�
Type:       Flash video (video/x-flv)
Size:       231.89 MiB (243149434 Bytes)

Downloading 【4月】机动战士敢达独角兽RE:0096 13【独家正版】.flv ...
 0.0% (  0.0/231.9MB) ├──────────────────────────────────────────────────────────────────────────────┤[1/4] you-get: version 0.4.455, a tiny downloader that scrapes the web.
you-get: ['bilibili.com/video/av5158525/']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1291, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1204, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1041, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1284, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/bilibili.py", line 168, in bilibili_download
    info_only=info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/bilibili.py", line 105, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 736, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 486, in url_save
    with open(temp_filepath, open_mode) as output:
OSError: [Errno 22] Invalid argument: './【4月】机动战士敢达独角兽RE:0096 13【独家正版】[00].flv.download'

**Comment by soimort** [comment]
![screenshot from 2016-07-03 05-41-30](https://cloud.githubusercontent.com/assets/342945/16543656/ea6a7a04-40e0-11e6-8d6e-029091c592ac.png)

**Comment by soimort** [comment]
不是很清楚B站这类视频的运作机制…

**Comment by nuomi1** [comment]
登录状态可在线播放。

**Comment by soimort** [comment]
登录了，但是并不能


![screenshot from 2016-07-03 07-28-59](https://cloud.githubusercontent.com/assets/342945/16543904/06a1d096-40f0-11e6-8049-d3e5dd622ed8.png)

**Comment by zhangn1985** [comment]
点开这个链接： http://interface.bilibili.com/playurl?appkey=f3bb208b3d081dc8&cid=8414875

是能获得地址的。

**Comment by cnbeining** [comment]
逼站请确保你挂了cookie。

地区限制请使用unblockyouku。

以及这些事情在wiki里都有写真不知道你们开issue前看没看......

2016年7月3日星期日，zhangn1985 <notifications@github.com> 写道：

**Comment by soimort** [comment]
> 点开这个链接： http://interface.bilibili.com/playurl?appkey=f3bb208b3d081dc8&cid=8414875

```xml
<?xml version="1.0" encoding="UTF-8"?>
<video>
	<result>error</result>
	<message><![CDATA[视频不允许在您当前所在地区播放]]></message>
	<src>0</src>
</video>
```

这里应有地区限制的提示。
