### ISSUE TITLE
[sina] cannot resolve v.iask.com: Unknown host

### ISSUE THREAD

**Issue by Maslino** [soimort/you-get#1260]
use ask.ivideo.sina.com.cn instead.

**Comment by soimort** [comment]
Not sure if our Sina support is still working.  ![745ca059e1ceefbd033ecc5274eb4c7b-24](https://cloud.githubusercontent.com/assets/342945/16695097/1a8d298c-453e-11e6-81bf-aeeb4e71342a.png)

```
[♥] you-get  develop  you-get -di 'http://video.sina.com.cn/news/spj/topvideoes20160708/#250661216'
[DEBUG] get_content: http://video.sina.com.cn/news/spj/topvideoes20160708/#250661216
Site:       Sina.com
you-get: version 0.4.485, a tiny downloader that scrapes the web.
you-get: ['http://video.sina.com.cn/news/spj/topvideoes20160708/#250661216']
Traceback (most recent call last):
  File "/home/soimort/Projects/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1328, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1241, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1321, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractors/sina.py", line 81, in sina_download
    sina_download_by_vkey(vkey, title=title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/soimort/Projects/you-get/src/you_get/extractors/sina.py", line 57, in sina_download_by_vkey
    print_info(site_info, title, 'flv', size)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 995, in print_info
    maybe_print("Title:     ", unescape_html(tr(title)))
  File "/usr/lib/python3.5/html/__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by rosynirvana** [comment]
fixed with
https://github.com/soimort/you-get/commit/f8bf3e6cf3c96786523180d0568c72e0aa1d332e#diff-56150d15dfb3ed87abe1f37597c76c22
