### ISSUE TITLE
代理功能不工作？- proxy function doesn't work？

### ISSUE THREAD

**Issue by fremff** [soimort/you-get#1267]
开发者，你好。我遇到了一个问题，希望能得到解答，以下为问题描述：

_**环境：**_  Windows  XP SP3, Python 3.4.4, you-get 0.4.486.
_**描述：**_ 所用代理本身工作正常，链接为随机选取，页内视频可以通过浏览器正常播放；但在通过本软件（you-get）获取这一视频时，却只获得一条返回的错误信息（[error] oops, something went wrong.）。相关 Debug 信息如下：

_使用 http 代理选项：_

``` console
C:\Documents and Settings\don>you-get --debug -x 127.0.0.1:1032 -i "http://www.y
outube.com/watch?v=_qNo5S4AXnY"
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=_qNo5S4AXnY

you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://www.youtube.com/watch?v=_qNo5S4AXnY']
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1328, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1241, in script_m
ain
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1060, in download
_main
    download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1321, in any_down
load
    m.download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\extractor.py", line 40, in downloa
d_by_url
    self.prepare(**kwargs)
  File "c:\python34\lib\site-packages\you_get\extractors\youtube.py", line 143,
in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_i
nfo?video_id={}'.format(self.vid)))
  File "c:\python34\lib\site-packages\you_get\common.py", line 322, in get_conte
nt
    data = response.read()
  File "c:\python34\lib\http\client.py", line 546, in read
    s = self.fp.read()
  File "c:\python34\lib\socket.py", line 378, in readinto
    return self._sock.recv_into(b)
  File "c:\python34\lib\ssl.py", line 748, in recv_into
    return self.read(nbytes, buffer)
  File "c:\python34\lib\ssl.py", line 620, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

_不使用代理选项：_ 输出内容（从 [DEBUG] 位置开始的）同上

 _使用socks 代理选项：_

``` console
C:\Documents and Settings\don>you-get --debug -s 127.0.0.1:1031 -i "http://www.y
outube.com/watch?v=_qNo5S4AXnY"
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=_qNo5S4AXnY

you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://www.youtube.com/watch?v=_qNo5S4AXnY']
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\socks.py", line 747, in connect
    negotiate(self, dest_addr, dest_port)
  File "c:\python34\lib\site-packages\socks.py", line 419, in _negotiate_SOCKS5
    CONNECT, dest_addr)
  File "c:\python34\lib\site-packages\socks.py", line 486, in _SOCKS5_request
    resp = self._readall(reader, 3)
  File "c:\python34\lib\site-packages\socks.py", line 270, in _readall
    raise GeneralProxyError("Connection closed unexpectedly")
socks.GeneralProxyError: Connection closed unexpectedly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\urllib\request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\python34\lib\http\client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "c:\python34\lib\http\client.py", line 1182, in _send_request
    self.endheaders(body)
  File "c:\python34\lib\http\client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "c:\python34\lib\http\client.py", line 963, in _send_output
    self.send(msg)
  File "c:\python34\lib\http\client.py", line 898, in send
    self.connect()
  File "c:\python34\lib\http\client.py", line 1279, in connect
    super().connect()
  File "c:\python34\lib\http\client.py", line 871, in connect
    self.timeout, self.source_address)
  File "c:\python34\lib\socket.py", line 516, in create_connection
    raise err
  File "c:\python34\lib\socket.py", line 507, in create_connection
    sock.connect(sa)
  File "c:\python34\lib\site-packages\socks.py", line 751, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: Connection closed unexpectedly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1328, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1241, in script_m
ain
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1060, in download
_main
    download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1321, in any_down
load
    m.download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\extractor.py", line 40, in downloa
d_by_url
    self.prepare(**kwargs)
  File "c:\python34\lib\site-packages\you_get\extractors\youtube.py", line 143,
in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_i
nfo?video_id={}'.format(self.vid)))
  File "c:\python34\lib\site-packages\you_get\common.py", line 317, in get_conte
nt
    response = request.urlopen(req)
  File "c:\python34\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python34\lib\urllib\request.py", line 464, in open
    response = self._open(req, data)
  File "c:\python34\lib\urllib\request.py", line 482, in _open
    '_open', req)
  File "c:\python34\lib\urllib\request.py", line 442, in _call_chain
    result = func(*args)
  File "c:\python34\lib\urllib\request.py", line 1226, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\python34\lib\urllib\request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Socket error: Connection closed unexpected
ly>
```

**Comment by soimort** [comment]
如果你在墙内，请尝试用相同代理获取国内网站（Youku，etc.）视频。

另，如可能，请提供代理具体种类、服务端和客户端的log信息。

**Comment by fremff** [comment]
我所用代理软件为赛风。以下是一个国内站点样例（已启用代理，系统代理为(socks:127.0.0.1:1031;http:127.0.0.1:1032)）：
```
C:\Documents and Settings\don>you-get --debug -i http://www.bilibili.com/video/a
v5158525/
[DEBUG] get_content: http://www.bilibili.com/video/av5158525/
[DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=f3bb208b3d081d
c8&cid=8414875
Site:       bilibili.com
Title:      【4月】机动战士敢达独角兽RE:0096 13【独家正版】
Type:       Unknown type ()
Size:       0.0 MiB (0 Bytes)


C:\Documents and Settings\don>you-get --debug --no-proxy -i http://www.bilibili.
com/video/av5158525/
[DEBUG] get_content: http://www.bilibili.com/video/av5158525/
[DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=f3bb208b3d081d
c8&cid=8414875
Site:       bilibili.com
Title:      【4月】机动战士敢达独角兽RE:0096 13【独家正版】
Type:       Flash video (video/x-flv)
Size:       231.89 MiB (243149434 Bytes)


C:\Documents and Settings\don>you-get --debug -s 127.0.0.1:1031 -i http://www.bi
libili.com/video/av5158525/
[DEBUG] get_content: http://www.bilibili.com/video/av5158525/
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av5158525/']
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\socks.py", line 747, in connect
    negotiate(self, dest_addr, dest_port)
  File "c:\python34\lib\site-packages\socks.py", line 419, in _negotiate_SOCKS5
    CONNECT, dest_addr)
  File "c:\python34\lib\site-packages\socks.py", line 486, in _SOCKS5_request
    resp = self._readall(reader, 3)
  File "c:\python34\lib\site-packages\socks.py", line 270, in _readall
    raise GeneralProxyError("Connection closed unexpectedly")
socks.GeneralProxyError: Connection closed unexpectedly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\urllib\request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\python34\lib\http\client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "c:\python34\lib\http\client.py", line 1182, in _send_request
    self.endheaders(body)
  File "c:\python34\lib\http\client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "c:\python34\lib\http\client.py", line 963, in _send_output
    self.send(msg)
  File "c:\python34\lib\http\client.py", line 898, in send
    self.connect()
  File "c:\python34\lib\http\client.py", line 871, in connect
    self.timeout, self.source_address)
  File "c:\python34\lib\socket.py", line 516, in create_connection
    raise err
  File "c:\python34\lib\socket.py", line 507, in create_connection
    sock.connect(sa)
  File "c:\python34\lib\site-packages\socks.py", line 751, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: Connection closed unexpectedly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1328, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1241, in script_m
ain
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1060, in download
_main
    download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1321, in any_down
load
    m.download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\extractors\bilibili.py", line 121,
 in bilibili_download
    html = get_content(url)
  File "c:\python34\lib\site-packages\you_get\common.py", line 317, in get_conte
nt
    response = request.urlopen(req)
  File "c:\python34\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python34\lib\urllib\request.py", line 464, in open
    response = self._open(req, data)
  File "c:\python34\lib\urllib\request.py", line 482, in _open
    '_open', req)
  File "c:\python34\lib\urllib\request.py", line 442, in _call_chain
    result = func(*args)
  File "c:\python34\lib\urllib\request.py", line 1211, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\python34\lib\urllib\request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Socket error: Connection closed unexpected
ly>

```

**Comment by soimort** [comment]
如果Youku走代理正常而YouTube不正常，那么基本上是代理自身的问题。

请提供代理的日志信息。

**Comment by fremff** [comment]
抱歉，我无法取得并提供代理软件的有效 LOG 信息。不过我在该软件的官方网站上找到了这样一则内容：Outbound connections via the Psiphon network can only be made to a restricted set of server ports including: 53, 80, 443, 465, 587, 993, 995, 8000, 8001, 8080.
另外，我还尝试了 Shadowsocks，以免费账号来作测试，结果是一样的。

**Comment by soimort** [comment]
不清楚你的代理软件工作机理是什么。如果Facebook可以正常访问而YouTube不行的话，目测是代理没有正确转发HTTPS（443端口）。因为`you-get`对于下载YouTube视频使用了安全链接，对于Facebook则没有。

另外，你的Shadowsocks没有正确配置。

**Comment by soimort** [comment]
> 这里，请容许我提及另一款下载工具 -- youtube-dl，它可以正常自 Youtube 下载视频，但本工具却不可以。不过，youtube-dl 似乎也有无法下载的情况，原因不明。而以上问题好像只出现在 Youtube 上，在其它站点上是正常的。

请提供更详细的信息：youtube-dl是否使用了代理、使用何种代理？SOCKS或HTTP代理？使用youtube-dl下载的是http或https版本的YouTube视频？针对 youtube-dl “无法下载的情况”，能否提供出错信息？

**Comment by fremff** [comment]
> 请提供更详细的信息：youtube-dl是否使用了代理、使用何种代理？SOCKS或HTTP代理？使用youtube-dl下载的是http或https版本的YouTube视频？针对 youtube-dl “无法下载的情况”，能否提供出错信息？
使用了赛风作为代理方式，应用于测试的代理类型是 socks，http 和 https 都有试过。请参考此链接：[youtube-dl issue repeort](https://github.com/rg3/youtube-dl/issues/10055)

**Comment by soimort** [comment]
rg3/youtube-dl#10055

此issue无效。首先，http://www.youtube.com/watchv=_qNo5S4AXnY 这是个错误的地址。

**Comment by soimort** [comment]
针对 you-get 这边，我刚才看了一下 psiphon 的 FAQ 页面，这个软件应该是存在 log output 的，请务必提供此信息，否则我们无法判断问题所在。

**Comment by fremff** [comment]
这个就是日志了，只是一些常规信息：
![psiphon-log](https://cloud.githubusercontent.com/assets/4241731/16719189/522a82c2-475a-11e6-9fbe-cb3348196583.JPG)
另外，我还找到了这个，只是不确定是否是你所需要的--https://www.dropbox.com/s/k9diasw0p5rte36/psiphon?dl=0

**关于“http://www.youtube.com/watchv=_qNo5S4AXnY ”**
此链接确实是有问题的，谢谢提醒。不好意思，我不小心使用了错误的链接，正确的应是 https://www.youtube.com/watch?v=_qNo5S4AXnY 或 https://www.youtube.com/watch?v=_qNo5S4AXnY&index=4&list=PLoEX1vToAybgUXGEMTfsFZRHOGtTSnJCV 。 在youtube-dl中输入正确地址后，获得了正常返回结果：
```
F:\>youtube-dl.exe --get-title --verbose --proxy socks5://127.0.0.1:1031/ "https
://www.youtube.com/watch?v=_qNo5S4AXnY"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--get-title', '--verbose', '--proxy', 'socks5://127
.0.0.1:1031/', 'https://www.youtube.com/watch?v=_qNo5S4AXnY']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.07.11
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
[debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg 2.8.6, ffprobe 2.8.6
[debug] Proxy map: {'http': 'socks5://127.0.0.1:1031/', 'https': 'socks5://127.0
.0.1:1031/'}
048　Xperia Web CM Touch＆Try 2015 in 名古屋
```

而在you-get中使用链接”https://www.youtube.com/watch?v=_qNo5S4AXnY “ 加上参数``` -di -s 127.0.0.1:1031```，返回的结果还是```socks.GeneralProxyError: Connection closed unexpectedly```。

**Comment by soimort** [comment]
> 这个就是日志了，只是一些常规信息：

这个日志没有显示任何连接信息。请分别通过：
1. `you-get` + HTTP代理
2. `youtube-dl` + HTTP代理
3. `you-get` + SOCKS代理
4. `youtube-dl` + SOCKS代理

检查有无信息。

> 而在you-get中使用链接”https://www.youtube.com/watch?v=_qNo5S4AXnY “ 加上参数-di -s 127.0.0.1:1031

#1231 `you-get` 的 SOCKS 代理依赖 PySocks。请首先安装：https://pypi.python.org/pypi/PySocks

**Comment by fremff** [comment]
> 这个日志没有显示任何连接信息。请分别通过：
> 1. you-get + HTTP代理
> 2. youtube-dl + HTTP代理
> 3. you-get + SOCKS代理
> 4. youtube-dl + SOCKS代理
> 
> 检查有无信息。

这款软件的内部日志所提供信息很少，在成功连接后，只要未出现连接中断故障，是不会增加额外记录的。

> 
#1231 you-get 的 SOCKS 代理依赖 PySocks。请首先安装：https://pypi.python.org/pypi/PySocks

PySocks 已安装，版本```1.5.7```。

**经过测试，可以认为以上问题与所用代理（服务器或客户端软件）有关**；不过，youtube-dl 的使用却不受影响，可正常下载视频（包括 Youtube）,不清楚是否是与两款软件(youtube-dl和you-get)的运行机制或其它要素的不同有关。

以下是通过影梭(shadowsocks)来尝试获取信息并最终成功样例的 Debug 信息：
```
C:\Documents and Settings\don>you-get --debug -i -x 127.0.0.1:1080 "https://www.
youtube.com/watch?v=Zp8zm4FQhdk"
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=Zp8zm4FQhdk

[DEBUG] get_content: https://www.youtube.com/watch?v=Zp8zm4FQhdk
[DEBUG] get_content: https://s.ytimg.com/yts/jsbin/player-ja_JP-vflV1jdtu/base.j
s
site:                YouTube
title:               坂本真綾「LIVE TOUR 2015-2016“FOLLOW ME UP”FINAL at中野サ
ンプラザ」初回限定盤特典DVD映像ダイジェスト
streams:             # Available quality and codecs
    [ DASH ] ____________________________________
    - itag:          137
      container:     mp4
      quality:       1920x1080
      size:          68.9 MiB (72287163 bytes)
    # download-with: you-get --itag=137 [URL]

    - itag:          248
      container:     webm
      quality:       1920x1080
      size:          61.0 MiB (63913974 bytes)
    # download-with: you-get --itag=248 [URL]

    - itag:          136
      container:     mp4
      quality:       1280x720
      size:          37.9 MiB (39772017 bytes)
    # download-with: you-get --itag=136 [URL]

    - itag:          247
      container:     webm
      quality:       1280x720
      size:          33.6 MiB (35236634 bytes)
    # download-with: you-get --itag=247 [URL]

    - itag:          135
      container:     mp4
      quality:       854x480
      size:          21.5 MiB (22502521 bytes)
    # download-with: you-get --itag=135 [URL]

    - itag:          244
      container:     webm
      quality:       854x480
      size:          18.6 MiB (19504579 bytes)
    # download-with: you-get --itag=244 [URL]

    - itag:          134
      container:     mp4
      quality:       640x360
      size:          12.8 MiB (13385406 bytes)
    # download-with: you-get --itag=134 [URL]

    - itag:          243
      container:     webm
      quality:       640x360
      size:          12.6 MiB (13181591 bytes)
    # download-with: you-get --itag=243 [URL]

    - itag:          133
      container:     mp4
      quality:       426x240
      size:          11.7 MiB (12296465 bytes)
    # download-with: you-get --itag=133 [URL]

    - itag:          242
      container:     webm
      quality:       426x240
      size:          8.5 MiB (8945411 bytes)
    # download-with: you-get --itag=242 [URL]

    - itag:          160
      container:     mp4
      quality:       256x144
      size:          7.5 MiB (7860029 bytes)
    # download-with: you-get --itag=160 [URL]

    - itag:          278
      container:     webm
      quality:       256x144
      size:          6.7 MiB (7017218 bytes)
    # download-with: you-get --itag=278 [URL]

    [ DEFAULT ] _________________________________
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          37.9 MiB (39753364 bytes)
    # download-with: you-get --itag=22 [URL]

    - itag:          43
      container:     webm
      quality:       medium
    # download-with: you-get --itag=43 [URL]

    - itag:          18
      container:     mp4
      quality:       medium
    # download-with: you-get --itag=18 [URL]

    - itag:          36
      container:     3gp
      quality:       small
    # download-with: you-get --itag=36 [URL]

    - itag:          17
      container:     3gp
      quality:       small
    # download-with: you-get --itag=17 [URL]
```
最后，感谢你的耐心回复，谢谢！

**Comment by cnbeining** [comment]
Old issue without update.
