### ISSUE TITLE
[tudou] 土豆可以解析但下載不了

### ISSUE THREAD

**Issue by kwokts** [soimort/you-get#1274]
you-get -d http://www.tudou.com/programs/view/5vX22L_wLVk/
Site:       Tudou.com
Title:      YC
Type:       Flash video (video/x-flv)
Size:       21.91 MiB (22979361 Bytes)

Downloading YC.f4v ...
 0.0% (  0.0/ 21.9MB) ├─────────────────────────────────────────┤[1/1] you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://www.tudou.com/programs/view/5vX22L_wLVk/']
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 512, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 503, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/opt/you-get-20160711/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/opt/you-get-20160711/src/you_get/common.py", line 1328, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/opt/you-get-20160711/src/you_get/common.py", line 1241, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/opt/you-get-20160711/src/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/opt/you-get-20160711/src/you_get/common.py", line 1321, in any_download
    m.download(url, **kwargs)
  File "/opt/you-get-20160711/src/you_get/extractors/tudou.py", line 60, in tudou_download
    tudou_download_by_iid(iid, title, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/opt/you-get-20160711/src/you_get/extractors/tudou.py", line 23, in tudou_download_by_iid
    download_urls(urls, title, ext, size, output_dir=output_dir, merge = merge)
  File "/opt/you-get-20160711/src/you_get/common.py", line 726, in download_urls
    url_save(url, output_filepath, bar, refer = refer, faker = faker, headers = headers)
  File "/opt/you-get-20160711/src/you_get/common.py", line 429, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "/opt/you-get-20160711/src/you_get/common.py", line 347, in url_size
    response = request.urlopen(url)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by soimort** [comment]
请把错误信息贴全。
