### ISSUE TITLE
[iqiyi]愛奇藝不能下載

### ISSUE THREAD

**Issue by kwokts** [soimort/you-get#1275]
you-get -di http://www.iqiyi.com/v_19rrm9gg8k.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/506560600/f60be6c9263e3c8fd16cfa5ba1f4f8db/?t=1468217073382&sc=e25fd4c85574119bd0f409a0a5acf394&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrm9gg8k.html']
Traceback (most recent call last):
  File "/opt/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/opt/you-get-20160711/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/opt/you-get-20160711/src/you_get/common.py", line 1328, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/opt/you-get-20160711/src/you_get/common.py", line 1241, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/opt/you-get-20160711/src/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/opt/you-get-20160711/src/you_get/common.py", line 1321, in any_download
    m.download(url, **kwargs)
  File "/opt/you-get-20160711/src/you_get/extractor.py", line 40, in download_by_url
    self.prepare(**kwargs)
  File "/opt/you-get-20160711/src/you_get/extractors/iqiyi.py", line 138, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video

**Comment by cnbeining** [comment]
版权问题吧？

参见 https://github.com/soimort/you-get/wiki/Region-Restrictions ？

**Comment by zhangn1985** [comment]
是因为现在用的是电视API，有些视频是电视不能看的，所以要fallback到html5

**Comment by soimort** [comment]
这个视频确实有版权限制。

请首先检查能否在浏览器中正常播放。

**Comment by kwokts** [comment]
在瀏覽器中翻牆後會先播放廣告然後才正常播放。
而愛奇藝apk則不用翻牆也能正常播放。

**Comment by Irving23** [comment]
我也遇到了这个问题
➜  ~ you-get -id http://www.iqiyi.com/v_19rrmdszvo.html\#vfrm\=2-3-0-1
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/515981000/4d7af00026e9ecb1e90d4066a3f51cea/?t=1470027636861&sc=df84d86b9700653c5b9c209ef81b74ab&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrmdszvo.html#vfrm=2-3-0-1']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.486', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractor.py", line 40, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/iqiyi.py", line 139, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video
