### ISSUE TITLE
[Failed] VK: Nothing to download here

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#1311]
```
$ yg -di https://new.vk.com/video328585056_456239017
you-get: version 0.4.504, a tiny downloader that scrapes the web.
you-get: ['https://new.vk.com/video328585056_456239017']
Traceback (most recent call last):
  File "/home/soimort/Projects/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractors/vk.py", line 47, in vk_download
    raise NotImplementedError('Nothing to download here')
NotImplementedError: Nothing to download here
```

**Comment by lki2019** [comment]
貌似现在依然不支持
我看了下就是普通的HLS流，

**Comment by rosynirvana** [comment]
```
./you-get -i https://vk.com/video328585056_456239017
Site:       VK.com
Title:      YuriRena part 4
Type:       MPEG-4 video (video/mp4)
Size:       11.2 MiB (11744299 Bytes)
```
