### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 416: Requested Range Not Satisfiable

### ISSUE THREAD

**Issue by zero17333** [soimort/you-get#1324]
I ran you-get --debug http://8ch.net/2hu/index.html and it works for a few images but then prints

you-get: ['http://8ch.net/2hu/index.html']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.486', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1328, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1241, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1321, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractors/universal.py", line 79, in universal_download
    faker=True)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 726, in download_urls
    url_save(url, output_filepath, bar, refer = refer, faker = faker, headers = headers)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 496, in url_save
    response = request.urlopen(request.Request(url, headers = headers), None)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 416: Requested Range Not Satisfiable

I'm guessing 8chan is not supported or it is a urllib bug.

**Comment by redstoneleo** [comment]
搞不好就是这个网站不支持断点续传，就这样没办法了
