### ISSUE TITLE
a part of video in qq have some problem

### ISSUE THREAD

**Issue by cybmp3** [soimort/you-get#1327]
Please make sure these boxes are checked before submitting your issue – thank you!
- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`. 
  yes 
- [ ] Your `you-get` is up-to-date.
  2016-08-03
- [ ] I have read https://github.com/soimort/you-get/wiki/FAQ and tried to do so.
  yes.
- [ ] The issue is not yet reported on https://github.com/soimort/you-get/issues or  https://github.com/soimort/you-get/wiki/Known-Bugs. If so, please add your comments under the existing issue.
  yes.Haven't same problem
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.
  of course

Run the command with the `--debug` option, and paste the full output inside the fences:
[root@VM_4_249_centos you-get]# python3 you-get --debug http://v.qq.com/cover/w/wubwd4bfqn1imf2/c0014lfc69s.html
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/cover/w/wubwd4bfqn1imf2/c0014lfc69s.html']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/you-get/src/you_get/__main__.py", line 92, in main
    main(*_kwargs)
  File "/home/you-get/src/you_get/common.py", line 1332, in main
    script_main('you-get', any_download, any_download_playlist, *_kwargs)
  File "/home/you-get/src/you_get/common.py", line 1245, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/you-get/src/you_get/common.py", line 1061, in download_main
    download(url, *_kwargs)
  File "/home/you-get/src/you_get/common.py", line 1325, in any_download
    m.download(url, *_kwargs)
  File "/home/you-get/src/you_get/extractors/qq.py", line 57, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/home/you-get/src/you_get/extractors/qq.py", line 12, in qq_download_by_vid
    url = output_json['vl']['vi'][0]['ul']['ui'][0]['url']
KeyError: 'vl'
I think maybe this video has stored in iqiyi??? 

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!
- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
  那是当然啊
- [ ] 您的`you-get`为最新版.
  吼啊
- [ ] 我已经阅读并按 https://github.com/soimort/you-get/wiki/FAQ 中的指引进行了操作.
  钦点了
- [ ] 您的问题没有在https://github.com/soimort/you-get/issues , https://github.com/soimort/you-get/wiki/FAQ 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.
  那是肯定的啊
- [ ] 本问题确实关于`you-get`, 而不是其他项目.
  你问我兹兹不兹兹，我肯定是兹兹啊

请使用`--debug`运行，并将输出粘贴在下面:

```
[root@VM_4_249_centos you-get]#  python3 ../you-get/you-get -d http://v.qq.com/cover/w/wubwd4bfqn1imf2/c0014lfc69s.html?ptag=iqiyi
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/cover/w/wubwd4bfqn1imf2/c0014lfc69s.html?ptag=iqiyi']
Traceback (most recent call last):
  File "../you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/you-get/src/you_get/common.py", line 1332, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/you-get/src/you_get/common.py", line 1245, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/you-get/src/you_get/common.py", line 1061, in download_main
    download(url, **kwargs)
  File "/home/you-get/src/you_get/common.py", line 1325, in any_download
    m.download(url, **kwargs)
  File "/home/you-get/src/you_get/extractors/qq.py", line 57, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/home/you-get/src/you_get/extractors/qq.py", line 12, in qq_download_by_vid
    url = output_json['vl']['vi'][0]['ul']['ui'][0]['url']
KeyError: 'vl'

```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]
> PRPRPRPR

**Comment by EmmieMcDonald** [comment]
相同的问题
```
>you-get -d http://v.qq.com/x/page/g0320igh49m.html
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/x/page/g0320igh49m.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1331, in main
  File "src\you_get\common.py", line 1244, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1324, in any_download
  File "src\you_get\extractors\qq.py", line 61, in qq_download
  File "src\you_get\extractors\qq.py", line 13, in qq_download_by_vid
KeyError: 'vl'
you-get returned -1
```

**Comment by rosynirvana** [comment]
```
Site:       QQ.com
Title:      他们生活的世界_14
Type:       MPEG-4 video (video/mp4)
Size:       511.88 MiB (536747967 Bytes)
```
