### ISSUE TITLE
Cannot download netease albums when the names of the albums contain '/'

### ISSUE THREAD

**Issue by jzjsuper** [soimort/you-get#1341]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
$ you-get --debug http://music.163.com/#/album?id=2686209
[DEBUG] get_content: http://music.163.com/api/album/2686209?id=2686209&csrf_token=
you-get: version 0.4.523, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/album?id=2686209']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1332, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1245, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1061, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1325, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/netease.py", line 129, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/netease.py", line 33, in netease_cloud_music_download
    os.mkdir(new_dir)
FileNotFoundError: [Errno 2] No such file or directory: './Justin Timberlake - The 20/20 Experience- The Complete Experience'
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> :icecream:

**Comment by soimort** [comment]
Thanks for the report.

(The bug was there for 2 years but no seems to notice this issue.)
