### ISSUE TITLE
下载视频报相同的错误

### ISSUE THREAD

**Issue by EmmieMcDonald** [soimort/you-get#1343]
windows系统，使用的是 you-get-0.4.523-win32-full.7z
可以下载图片，但是下载视频就报相同的错误，求解

>you-get --debug 'http://www.tudou.com/albumplay/gBUcmd344II/c45_9KEXgSc.html'
you-get: version 0.4.523, a tiny downloader that scrapes the web.
you-get: ["'http://www.tudou.com/albumplay/gBUcmd344II/c45_9KEXgSc.html'"]
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1332, in main
  File "src\you_get\common.py", line 1245, in script_main
  File "src\you_get\common.py", line 1061, in download_main
  File "src\you_get\common.py", line 1324, in any_download
  File "src\you_get\common.py", line 1315, in url_to_module
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 826, in connect
  File "socket.py", line 689, in create_connection
  File "socket.py", line 728, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed
you-get returned -1

**Comment by soimort** [comment]
Windows 下不要使用单引号。
