### ISSUE TITLE
Douyu error on analysing

### ISSUE THREAD

**Issue by Lazy6Studio** [soimort/you-get#1348]
Please make sure these boxes are checked before submitting your issue – thank you!
- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read https://github.com/soimort/you-get/wiki/FAQ and tried to do so.
- [x] The issue is not yet reported on https://github.com/soimort/you-get/issues or  https://github.com/soimort/you-get/wiki/Known-Bugs. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get -u --debug http://www.douyu.com/3484
[DEBUG] get_content: http://www.douyu.com/3484
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=3484
Site:       douyu.com
Title:      今晚大战黄旭东 接班人
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Real URL:
['http://hdl3.douyucdn.cn/live/3484reW11KMQemyp.flv?wsAuth=61cd1b38d7a9691b01341d42dd1afc2f&token=web-0-3484-42bfaafc7ed31157b188294cc97f9c9d&logo=0&expire=0']

you-get: version 0.4.523, a tiny downloader that scrapes the web.
you-get: ['http://www.douyu.com/3484']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1332, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1245, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1061, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1325, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractors/douyutv.py", line 52, in douyutv_download
    download_url_ffmpeg(real_url, title, 'flv', None, output_dir, merge = merge)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 908, in download_url_ffmpeg
    if params.get("-y",False): #None or unset ->False
AttributeError: 'NoneType' object has no attribute 'get'


```

using --json it won't return json for me.

I also remember Douyu would return 3 url for each level of resolution, might this another bug?

**Comment by soimort** [comment]
Someone should fix this.

https://github.com/soimort/you-get/issues/1336#issuecomment-239614272

**Comment by power12317** [comment]
Another problem is the `-O / --output-filename` doesn't work

```
F:\douyutv>you-get -O 123.flv -o c:\ http://www.douyu.com/478997
Site:       douyu.com
Title:      Wake Up,Girls!演唱会倒计时
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://hdl3.douyucdn.cn/live/478997rzmKn1H6k2.flv?wsAuth=30b8c03b819ede565bf57d6c64326812&token=web-0-4
78997-95d297921214ce22ad70d2923aac480d&logo=0&expire=0 -c copy -bsf:a aac_adtstoasc Wake Up,Girls!演唱会倒计时.flv
ffmpeg version N-81192-g04da20e Copyright (c) 2000-2016 the FFmpeg developers
```

**Comment by rosynirvana** [comment]
outdated
