### ISSUE TITLE
error with youku

### ISSUE THREAD

**Issue by wcy95** [soimort/you-get#1351]
在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
wang@wang:~$ you-get --debug  http://v.youku.com/v_show/id_XMTY4OTg0MDgwNA==.html?tpa=dW5pb25faWQ9MTAzNzUzXzEwMDAwMV8wMV8wMQ
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTY4OTg0MDgwNA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTY4OTg0MDgwNA==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/847152986192012d7fdb7_00/st/flv/fileid/0300800A0057B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?oip=1909916266&ep=eiaTG0yPX8YG5CrdiD8bMyu0ICUIXP4J9h%2BNgdITALshT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSdRDD1&yxon=1&token=3704&ctype=12&K=717a8305efd9f36f261f2f8f&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/847152986192012d7fdb7_00/st/flv/fileid/0300800A0157B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?oip=1909916266&ep=eiaTG0yPX8YG5CrdiD8bMyu0ICUIXP4J9h%2BNgdITALohT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSdRDD1&yxon=1&token=3704&ctype=12&K=3b4b6d215d7f30e3261f2f8f&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/847152986192012d7fdb7_00/st/flv/fileid/0300800A0257B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?oip=1909916266&ep=eiaTG0yPX8YG5CrdiD8bMyu0ICUIXP4J9h%2BNgdITALkhT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSdRDD1&yxon=1&token=3704&ctype=12&K=b9b5156c801313f1261f2f8f&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/847152986192012d7fdb7_00/st/flv/fileid/0300800A0357B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?oip=1909916266&ep=eiaTG0yPX8YG5CrdiD8bMyu0ICUIXP4J9h%2BNgdITALghT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSdRDD1&yxon=1&token=3704&ctype=12&K=490ff971f9b503d3282ba8fc&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/847152986192012d7fdb7_00/st/flv/fileid/0300800A0457B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?oip=1909916266&ep=eiaTG0yPX8YG5CrdiD8bMyu0ICUIXP4J9h%2BNgdITAL8hT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSdRDD1&yxon=1&token=3704&ctype=12&K=a7cb472975aafcee282ba8fc&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/847152986192012d7fdb7_00/st/flv/fileid/0300800A0557B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?oip=1909916266&ep=eiaTG0yPX8YG5CrdiD8bMyu0ICUIXP4J9h%2BNgdITAL4hT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSdRDD1&yxon=1&token=3704&ctype=12&K=5db17ae0744593612412b622&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/847152986192012d7fdb7_00/st/flv/fileid/0300800A0657B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?oip=1909916266&ep=eiaTG0yPX8YG5CrdiD8bMyu0ICUIXP4J9h%2BNgdITAL0hT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSdRDD1&yxon=1&token=3704&ctype=12&K=0b032f76624b2051282ba8fc&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/847152986192012d7fdb7_00/st/flv/fileid/0300800A0757B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?oip=1909916266&ep=eiaTG0yPX8YG5CrdiD8bMyu0ICUIXP4J9h%2BNgdITALwhT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSdRDD1&yxon=1&token=3704&ctype=12&K=9746dc3747d689cb261f2f8f&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/847152986192012d7fdb7_00/st/flv/fileid/0300800A0857B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?oip=1909916266&ep=eiaTG0yPX8YG5CrdiD8bMyu0ICUIXP4J9h%2BNgdITALMhT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSdRDD1&yxon=1&token=3704&ctype=12&K=a9e1d036d20dabb32412b622&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/847152986192012d7fdb7_00/st/flv/fileid/0300800A0957B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?oip=1909916266&ep=eiaTG0yPX8YG5CrdiD8bMyu0ICUIXP4J9h%2BNgdITALIhT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSdRDD1&yxon=1&token=3704&ctype=12&K=8cc14bd4b79a8b242412b622&ev=1
site:                优酷 (Youku)
title:               44 以战止殇
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          472.1 MiB (495044202 bytes)
    # download-with: you-get --format=hd3 [URL]

Downloading 44 以战止殇.flv ...
22.6% (106.5/472.1MB) ├████████████████████████─────────────────────────────────────────────────────────────────────────────────────┤[ 3/10]    3 MB/syou-get: version 0.4.523, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTY4OTg0MDgwNA==.html?tpa=dW5pb25faWQ9MTAzNzUzXzEwMDAwMV8wMV8wMQ']
Traceback (most recent call last):
  File "/home/wang/.local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/wang/.local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/wang/.local/lib/python3.5/site-packages/you_get/common.py", line 1332, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/wang/.local/lib/python3.5/site-packages/you_get/common.py", line 1245, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/wang/.local/lib/python3.5/site-packages/you_get/common.py", line 1061, in download_main
    download(url, **kwargs)
  File "/home/wang/.local/lib/python3.5/site-packages/you_get/common.py", line 1325, in any_download
    m.download(url, **kwargs)
  File "/home/wang/.local/lib/python3.5/site-packages/you_get/extractor.py", line 51, in download_by_url
    self.download(**kwargs)
  File "/home/wang/.local/lib/python3.5/site-packages/you_get/extractor.py", line 207, in download
    av=stream_id in self.dash_streams)
  File "/home/wang/.local/lib/python3.5/site-packages/you_get/common.py", line 739, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers)
  File "/home/wang/.local/lib/python3.5/site-packages/you_get/common.py", line 474, in url_save
    response = request.urlopen(request.Request(url, headers = headers), None)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by wcy95** [comment]
Maybe it's the reason. Because it really works well now.But I can watch the video on the web.

**Comment by nuomi1** [comment]
看来是 CDN / ISP-Cache 的锅。

```
➜ ~ yg -d http://v.youku.com/v_show/id_XMTY4OTg0MDgwNA\=\=.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTY4OTg0MDgwNA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTY4OTg0MDgwNA==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0471537136638123f59a2_00/st/flv/fileid/0300800A0057B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?yxon=1&ev=1&ep=ciaTG0yOUc8D4yXcgD8bZHrnfSYNXP4J9h%2BNgdITALshT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSeRjT1&token=0544&K=a21c9aaeae789846261f2f99&oip=2026301284&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0471537136638123f59a2_00/st/flv/fileid/0300800A0157B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?yxon=1&ev=1&ep=ciaTG0yOUc8D4yXcgD8bZHrnfSYNXP4J9h%2BNgdITALohT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSeRjT1&token=0544&K=4d048f2f366f3ed32412b628&oip=2026301284&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0471537136638123f59a2_00/st/flv/fileid/0300800A0257B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?yxon=1&ev=1&ep=ciaTG0yOUc8D4yXcgD8bZHrnfSYNXP4J9h%2BNgdITALkhT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSeRjT1&token=0544&K=702ceddbaf8954e5261f2f99&oip=2026301284&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0471537136638123f59a2_00/st/flv/fileid/0300800A0357B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?yxon=1&ev=1&ep=ciaTG0yOUc8D4yXcgD8bZHrnfSYNXP4J9h%2BNgdITALghT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSeRjT1&token=0544&K=a1c748f07282184b282ba90a&oip=2026301284&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0471537136638123f59a2_00/st/flv/fileid/0300800A0457B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?yxon=1&ev=1&ep=ciaTG0yOUc8D4yXcgD8bZHrnfSYNXP4J9h%2BNgdITAL8hT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSeRjT1&token=0544&K=e0e2408cc9a448eb282ba90a&oip=2026301284&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0471537136638123f59a2_00/st/flv/fileid/0300800A0557B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?yxon=1&ev=1&ep=ciaTG0yOUc8D4yXcgD8bZHrnfSYNXP4J9h%2BNgdITAL4hT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSeRjT1&token=0544&K=ed5e59898303f0dd2412b628&oip=2026301284&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0471537136638123f59a2_00/st/flv/fileid/0300800A0657B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?yxon=1&ev=1&ep=ciaTG0yOUc8D4yXcgD8bZHrnfSYNXP4J9h%2BNgdITAL0hT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSeRjT1&token=0544&K=b253eb0ef6b41504261f2f99&oip=2026301284&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0471537136638123f59a2_00/st/flv/fileid/0300800A0757B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?yxon=1&ev=1&ep=ciaTG0yOUc8D4yXcgD8bZHrnfSYNXP4J9h%2BNgdITALwhT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSeRjT1&token=0544&K=d05635a03f6675bf261f2f99&oip=2026301284&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0471537136638123f59a2_00/st/flv/fileid/0300800A0857B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?yxon=1&ev=1&ep=ciaTG0yOUc8D4yXcgD8bZHrnfSYNXP4J9h%2BNgdITALMhT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSeRjT1&token=0544&K=d7176d7b7db5dee2282ba90a&oip=2026301284&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0471537136638123f59a2_00/st/flv/fileid/0300800A0957B59791B8DD1AC7F3E50DCC28FD-FCF4-EE52-1431-062258D65611?yxon=1&ev=1&ep=ciaTG0yOUc8D4yXcgD8bZHrnfSYNXP4J9h%2BNgdITALIhT5q6kDnYxu%2B4OotDZ4oeBCFzFeuF2KPlYjZgYYYw32wQqjutO%2Frh%2BvPi5a1VxpIFbm0wd8vWtVSeRjT1&token=0544&K=8fc860bbf1ea36a1261f2f99&oip=2026301284&ctype=12
site:                优酷 (Youku)
title:               44 以战止殇
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          472.1 MiB (495044202 bytes)
    # download-with: you-get --format=hd3 [URL]

Downloading 44 以战止殇.flv ...
 100% (472.1/472.1MB) ├███████████████████████████████████████┤[10/10]    1 MB/s
Merging video parts... Merged into 44 以战止殇.mp4
```
