### ISSUE TITLE
[Bilibili] 番剧解析出问题了

### ISSUE THREAD

**Issue by mengmo** [soimort/you-get#1362]
```
python -m you_get -di http://bangumi.bilibili.com/anime/v/91286
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/91286
[DEBUG] get_content: http://www.bilibili.com/m/html5?aid=None&page=1
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/v/91286']
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 95, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1060, in download_main
    download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractors\bilibili.py", line 68, in bilibili_download
    info = json.loads(get_content(api))
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 318, in get_content
    response = request.urlopen(req)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by mengmo** [comment]
```
you-get -di http://bangumi.bilibili.com/anime/v/91286
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/91286
[DEBUG] get_content: http://www.bilibili.com/m/html5?aid=None&page=1
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/v/91286']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1331, in main
  File "src\you_get\common.py", line 1244, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1324, in any_download
  File "src\you_get\extractors\bilibili.py", line 68, in bilibili_download
  File "src\you_get\common.py", line 318, in get_content
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 471, in open
  File "urllib\request.py", line 581, in http_response
  File "urllib\request.py", line 509, in error
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 589, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request
you-get returned -1
```
