### ISSUE TITLE
代理支持有问题，无法正常识别 系统变量 http_proxy

### ISSUE THREAD

**Issue by mengmo** [soimort/you-get#1366]
```
python -m you_get -di https://www.youtube.com/watch?v=OCU862nVpJ0
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=OCU862nVpJ0
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=OCU862nVpJ0']
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\urllib\request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "D:\PortableApps\Python\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "D:\PortableApps\Python\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "D:\PortableApps\Python\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "D:\PortableApps\Python\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "D:\PortableApps\Python\lib\http\client.py", line 877, in send
    self.connect()
  File "D:\PortableApps\Python\lib\http\client.py", line 1252, in connect
    super().connect()
  File "D:\PortableApps\Python\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "D:\PortableApps\Python\lib\socket.py", line 711, in create_connection
    raise err
  File "D:\PortableApps\Python\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 95, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1060, in download_main
    download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractor.py", line 40, in download_by_url
    self.prepare(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractors\youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 318, in get_content
    response = request.urlopen(req)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "D:\PortableApps\Python\lib\urllib\request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
```

**Comment by mengmo** [comment]
```
you-get -di https://www.youtube.com/watch?v=OCU862nVpJ0
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=OCU862nVpJ0
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=OCU862nVpJ0']
Traceback (most recent call last):
  File "urllib\request.py", line 1240, in do_open
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 1229, in connect
  File "http\client.py", line 826, in connect
  File "socket.py", line 707, in create_connection
  File "socket.py", line 698, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1331, in main
  File "src\you_get\common.py", line 1244, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1324, in any_download
  File "src\you_get\extractor.py", line 40, in download_by_url
  File "src\you_get\extractors\youtube.py", line 143, in prepare
  File "src\you_get\common.py", line 318, in get_content
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 465, in open
  File "urllib\request.py", line 483, in _open
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 1283, in https_open
  File "urllib\request.py", line 1242, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
you-get returned -1
```

**Comment by soimort** [comment]
请给出当前环境下 `http_proxy` 和 `https_proxy` 的 echo 结果。

**Comment by mengmo** [comment]
```
[2016-08-26 10:55:30] Socket connected to ss server:
[2016-08-26 10:55:30] connect to clients5.google.com:443
[2016-08-26 10:57:40] Socket connected to ss server: 
[2016-08-26 10:57:40] connect to safebrowsing.google.com:443
[2016-08-26 10:57:41] Socket connected to ss server: 
[2016-08-26 10:57:41] connect to safebrowsing-cache.google.com:443
```
@soimort 这个吗？ 顺便说一下，youtube-dl 正常。

**Comment by soimort** [comment]
> @soimort 这个吗？ 顺便说一下，youtube-dl 正常。

请贴 echo  命令的结果。

**Comment by mengmo** [comment]
```
echo %http_proxy%
http://127.0.0.1:1080

echo %https_proxy%
%https_proxy%
```

**Comment by soimort** [comment]
> 所以，youtube-dl算是“作弊”了？

是的：https://github.com/rg3/youtube-dl/issues/805

**Comment by mengmo** [comment]
@soimort 
那么是不是可以在`readme`的`proxy`这一块把`https_proxy`给加进去，或者也考虑跟`youtube-dl`一样处理
原来我还测试过`ffmpeg`，可以肯定，`ffmpeg`也是这么干的
https://github.com/rg3/youtube-dl/issues/805#issuecomment-17134110

**Comment by zhangn1985** [comment]
python的proxy_handler如果创建的时候，不传递参数，那么会自动抓取系统环境变量，注册表，等。。

**Comment by zhangn1985** [comment]
https://docs.python.org/3/library/urllib.request.html#urllib.request.ProxyHandler
