### ISSUE TITLE
下载腾讯视频报错

### ISSUE THREAD

**Issue by pthreadself** [soimort/you-get#1370]
执行命令：
you-get -i --debug http://v.qq.com/page/d/0/4/d0021eoy574.html
输出：
you-get: version 0.4.523, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/page/d/0/4/d0021eoy574.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/**main**.py", line 92, in main
    main(*_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1332, in main
    script_main('you-get', any_download, any_download_playlist, *_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1245, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1061, in download_main
    download(url, *_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1325, in any_download
    m.download(url, *_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/qq.py", line 60, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/qq.py", line 13, in qq_download_by_vid
    url = output_json['vl']['vi'][0]['ul']['ui'][0]['url']
KeyError: 'vl'

**Comment by xlfjn** [comment]
It should be the same issue as #1327.
I have another problematic video: http://v.qq.com/x/page/x0308swml8x.html

According to [Fiddler](https://www.telerik.com/fiddler), they started to use HTTPS to get the json.

**Comment by lsycxyj** [comment]
http://v.qq.com/x/cover/71so4gc7db7tmb0.html
这个地址同样无法下载

**Comment by rosynirvana** [comment]
http://v.qq.com/page/d/0/4/d0021eoy574.html is gone

for http://v.qq.com/x/cover/71so4gc7db7tmb0.html
```
Site:       QQ.com
Title:      160801解码财商_001
Type:       MPEG-4 video (video/mp4)
Size:       167.31 MiB (175437550 Bytes)
```
