### ISSUE TITLE
[iqiyi]爱奇艺某些视频下载失败

### ISSUE THREAD

**Issue by xf1** [soimort/you-get#1382]
在提交前，请确保您已经检查了以下内容!

- [✓] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [✓] 您的`you-get`为最新版.
- [✓] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [✓] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [✓] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/467329400/5e380c747254403bad70edf2819d1d30/?t=1472557749184&sc=f87359340651098f7c67443273b2d76f&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrkzo8wk.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1246, in script_main
    download_main(download, download_playlist, args, playlist, extractor_proxy=extractor_proxy, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 40, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/iqiyi.py", line 139, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [喵喵喵？]
> [舔 :icecream:!]

**Comment by soimort** [comment]
"Sorry, this video is not available in your region due to copyright limitations."

**Comment by cnbeining** [comment]
Just saying we can bypass the damned region restrictions with the even more damned ISP's cache servers. Works like a charm, and no one would even dare to block the cache server's IP range...
