### ISSUE TITLE
Cannot play live.bilibili.com video

### ISSUE THREAD

**Issue by ikzk** [soimort/you-get#1384]
Got 400 error:
```
> you-get --debug -p mpv "http://live.bilibili.com/138" 
[DEBUG] get_content: http://live.bilibili.com/138
[DEBUG] get_content: http://www.bilibili.com/m/html5?aid=None&page=1
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://live.bilibili.com/138']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.536', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 68, in bilibili_download
    info = json.loads(get_content(api))
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 318, in get_content
    response = request.urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```
This error is raised for every room on the site.

**Comment by cnbeining** [comment]
看样是没取到aid。。。我看看吧。

**Comment by cnbeining** [comment]
```
$ python3 you-get -di "http://live.bilibili.com/55041"
[DEBUG] get_content: http://live.bilibili.com/55041
[DEBUG] get_content: http://live.bilibili.com/api/playurl?cid=55041
Site:       bilibili.com
Title:      每天回家都看到汉子们在互撩 - 满汉全席音乐团队 - 哔哩哔哩直播
Type:       Flash video (video/x-flv)
Size:       0.0 MiB (0 Bytes)

```

Cannot reproduce. Please kindly upgrade your ```you-get``` to the latest version.

**Comment by ikzk** [comment]
Interesting, it seems that bilibili blocks my access to any video. With a proxy I can play videos without any problem.

**Comment by cnbeining** [comment]
![image](https://cloud.githubusercontent.com/assets/1560962/18111249/faa665de-6eeb-11e6-9fa0-08460730ee3a.png)

You can probably use ISP(e.g., China Unicom)'s cache server to access the APIs.

**Comment by ikzk** [comment]
咦，那是什么，怎么用？

**Comment by cnbeining** [comment]
In the code,

put http://120.52.73.83/ in the front of all the API urls.

![image](https://cloud.githubusercontent.com/assets/1560962/18111350/d841cd0c-6eec-11e6-9468-22029aec96ba.png)

**Comment by ikzk** [comment]
面白い，还可以这么玩。学到了，Thanks！

**Comment by heroesm** [comment]
其实这是 v0.4.536 中的一个问题，似乎是修改了抓取一般视频的api但没有考虑到直播，不过在 d66749801f6fbb0aee4e2030e93448e9d46e13f8 中被修复了。
