### ISSUE TITLE
乐视视频下载完成后不能正常合并

### ISSUE THREAD

**Issue by JayceCao** [soimort/you-get#1387]
我使用的是windows下的you-get-0.4.536-win32.exe，操作系统是win10，使用debug参数后的输出是：

[DEBUG] get_content: http://www.le.com/ptv/vplay/26128872.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=26128872&platid=1&splatid=101&format=1&tkey=2100283542&domain=www.letv.com
[DEBUG] get_content: http://play.g3proxy.lecloud.com/vod/v2/MjExLzE3LzQvbGV0di11dHMvMTQvdmVyXzAwXzIyLTEwNTcxMDIwODctYXZjLTI5MDAzNy1hYWMtMzIwMDAtMTQyNTQ0MC01ODkwNzg3OS1hZWMxYmI0NjZjMjYwOTBhMTg5ZTc5ZjFkNzA1ZDFlYy0xNDY5NTI0ODk0MzEyLm1wNA==?b=330&mmsid=60788883&tm=1472626507&key=5cc03d5969386bad5d3ae7f8a844e015&platid=1&splatid=101&playid=0&tss=ios&vtype=21&cvid=376532761701&payff=0&pip=935e9ad200b1da63867971be9f2e541d&ctv=pc&m3v=1&termid=1&format=1&hwtype=un&ostype=Linux&tag=letv&sign=letv&expect=3&tn=0.4112738999068053&pay=0&iscpn=f9051&rateid=350
[DEBUG] get_content: http://120.52.41.69/211/17/4/letv-uts/14/ver_00_22-1057102087-avc-290037-aac-32000-1425440-58907879-aec1bb466c26090a189e79f1d705d1ec-1469524894312.m3u8?crypt=39aa7f2e344&b=330&nlh=4096&nlt=60&bf=83&p2p=1&video_type=mp4&termid=1&tss=ios&platid=1&splatid=101&its=0&qos=4&fcheck=0&amltag=100&mltag=100&proxy=611247572,2016684358,467476944&uid=1929324590.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&ntm=1472644800&nkey=c89d45b60b3c8fcbdcd796bc12708885&nkey2=b909afbd524461615c36ec4a1f60ae44&geo=CN-1-6-2&mmsid=60788883&tm=1472626507&key=5cc03d5969386bad5d3ae7f8a844e015&playid=0&vtype=21&cvid=376532761701&payff=0&ctv=pc&m3v=1&hwtype=un&ostype=Linux&tag=letv&sign=letv&tn=0.4112738999068053&pay=0&iscpn=f9051&rateid=350&errc=0&gn=1158&vrtmcd=102&buss=100&cips=114.255.40.46
Site:       Le.com
Title:      黑暗之泉（瘟疫十周年演出北京站）
Type:       MPEG-4 video (video/mp4)
Size:       61.32 MiB (64302580 Bytes)

Downloading 黑暗之泉（瘟疫十周年演出北京站）.mp4 ...
100% ( 61.3/ 61.3MB) ├███████████████████████████████████████┤[86/86]   40 MB/s
Merging video parts...
.\黑暗之泉（瘟疫十周年演出北京站）[00].mp4
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/26128872.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1331, in main
  File "src\you_get\common.py", line 1239, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1324, in any_download
  File "src\you_get\extractors\le.py", line 137, in letv_download
  File "src\you_get\extractors\le.py", line 98, in letv_download_by_vid
  File "src\you_get\common.py", line 779, in download_urls
  File "src\you_get\processor\join_mp4.py", line 914, in concat_mp4
  File "src\you_get\processor\join_mp4.py", line 876, in merge_mp4s
  File "src\you_get\processor\join_mp4.py", line 717, in read_mp4
  File "src\you_get\processor\join_mp4.py", line 708, in parse_atoms
  File "src\you_get\processor\join_mp4.py", line 700, in read_atom
NotImplementedError: b'\x00\x00\xb0\r': 1195376648
you-get returned -1

**Comment by JayceCao** [comment]
@soimort-bot It can download correctly, but it can't merge all the pieces into a full video. So in the diectory, there are many video pieces.

**Comment by JayceCao** [comment]
@soimort-bot And when I use my Arch Linux, when I type 'you-get -i --debug http://www.le.com/ptv/vplay/26128872.html', it displays: 

[DEBUG] get_content: http://www.le.com/ptv/vplay/26128872.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=26128872&platid=1&splatid=101&format=1&tkey=2131126422&domain=www.letv.com
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/26128872.html']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractors/le.py", line 137, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractors/le.py", line 90, in letv_download_by_vid
    ext , urls = video_info(vid,**kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractors/le.py", line 61, in video_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'

**Comment by JayceCao** [comment]
I promise that I have installed FFmpeg and my you-get is up-to-date.

**Comment by soimort** [comment]
1. For the 1st failure, make sure you have `ffmpeg` in your **system path**. Or you may use the 7z version instead.
2. For the 2nd failure -- it seems unrelated to ffmpeg or video merging. Please open another issue if the general support for www.le.com is broken.
