### ISSUE TITLE
现在番剧解析又出问题了

### ISSUE THREAD

**Issue by isbasex** [soimort/you-get#1391]
```
➜  you-get git:(develop) ./you-get --debug -di  http://bangumi.bilibili.com/anime/v/91393
[DEBUG] get_content: http://bangumi.bilibili.com/anime/5064/
[DEBUG] get_content: None
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/5064/']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/Users/baiyun/tools/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/baiyun/tools/you-get/src/you_get/common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/baiyun/tools/you-get/src/you_get/common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/baiyun/tools/you-get/src/you_get/common.py", line 1077, in download_main
    download(url, **kwargs)
  File "/Users/baiyun/tools/you-get/src/you_get/common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "/Users/baiyun/tools/you-get/src/you_get/extractors/bilibili.py", line 128, in bilibili_download
    html = get_content(url)
  File "/Users/baiyun/tools/you-get/src/you_get/common.py", line 312, in get_content
    req = request.Request(url, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'None'
```

**Comment by isbaseby** [comment]
问题解决了，之前是通过pip3安装的，现在直接用 git clone git://github.com/soimort/you-get.git 是没有问题的

**Comment by l2dy** [comment]
Didn't work for me at `7e5abc9 version 0.4.555`.

```
./you-get -diu 'http://bangumi.bilibili.com/anime/v/90959'
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/90959
[DEBUG] get_content: http://www.bilibili.com/video/av6398089/
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/v/90959']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/Users/l2dy/Build/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/l2dy/Build/you-get/src/you_get/common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/l2dy/Build/you-get/src/you_get/common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/l2dy/Build/you-get/src/you_get/common.py", line 1077, in download_main
    download(url, **kwargs)
  File "/Users/l2dy/Build/you-get/src/you_get/common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "/Users/l2dy/Build/you-get/src/you_get/extractors/bilibili.py", line 135, in bilibili_download
    assert flashvars
AssertionError
```

**Comment by cnbeining** [comment]
不是海外？不是会员？

请使用Unblock-Youku之类的处理一下再试试。

**Comment by l2dy** [comment]
不是海外。这个还要会员？

**Comment by cnbeining** [comment]
哎呀 HTML5就没有flashvar了嘛。

bug确认，我找时间修修。
