### ISSUE TITLE
[CNTV] Became invalid

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#14]
``` sh
➜  you-get git:(master) ✗ ./you-get -i http://xiyou.cntv.cn/v-5e166490-faeb-11e0-b140-a4badb469111.html
Traceback (most recent call last):
  File "./you-get", line 6, in <module>
    main()
  File "/home/soimort/Source/you-get/you_get/main.py", line 55, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/soimort/Source/you-get/you_get/common.py", line 643, in script_main
    download_main(download, download_playlist, args, playlist, output_dir, merge, info_only)
  File "/home/soimort/Source/you-get/you_get/common.py", line 563, in download_main
    download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/soimort/Source/you-get/you_get/main.py", line 48, in any_download
    m.download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/soimort/Source/you-get/you_get/downloader/cntv.py", line 38, in cntv_download
    cntv_download_by_id(id, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/soimort/Source/you-get/you_get/downloader/cntv.py", line 23, in cntv_download_by_id
    _, _, temp = url_info(url)
  File "/home/soimort/Source/you-get/you_get/common.py", line 135, in url_info
    size = int(headers['content-length'])
TypeError: int() argument must be a string or a number, not 'NoneType'
```

``` sh
➜  you-get git:(master) ✗ ./you-get -i http://xiyou.cntv.cn/v-b79432d8-dc52-11e1-89a1-001e0bd5b3ca.html
Traceback (most recent call last):
  File "./you-get", line 6, in <module>
    main()
  File "/home/soimort/Source/you-get/you_get/main.py", line 55, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/soimort/Source/you-get/you_get/common.py", line 643, in script_main
    download_main(download, download_playlist, args, playlist, output_dir, merge, info_only)
  File "/home/soimort/Source/you-get/you_get/common.py", line 563, in download_main
    download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/soimort/Source/you-get/you_get/main.py", line 48, in any_download
    m.download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/soimort/Source/you-get/you_get/downloader/cntv.py", line 38, in cntv_download
    cntv_download_by_id(id, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/soimort/Source/you-get/you_get/downloader/cntv.py", line 13, in cntv_download_by_id
    title = title or info['title']
KeyError: 'title'
```

**Comment by rosynirvana** [comment]
```
you-get -di 'http://xiyou.cntv.cn/v-5e166490-faeb-11e0-b140-a4badb469111.html'
[DEBUG] get_response: http://vdn.apps.cntv.cn/api/getHttpVideoInfo.do?pid=5e166490-faeb-11e0-b140-a4badb469111
[DEBUG] url_info: http://v.iseeyoo.cn/video/2011/10/20/5e166490-faeb-11e0-b140-a4badb469111_001.mp4
Site:       CNTV.com
Title:      RIVER 美国版
Type:       MPEG-4 video (video/mp4)
Size:       30.0 MiB (31454827 Bytes)
```
