### ISSUE TITLE
bilibili 的视频不能下载

### ISSUE THREAD

**Issue by bonecto** [soimort/you-get#1406]
[root@pc-01 ~]# you-get -d http://bangumi.bilibili.com/anime/v/86847
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/86847
[DEBUG] get_content: http://www.bilibili.com/m/html5?aid=None&page=1
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/v/86847']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 68, in bilibili_download
    info = json.loads(get_content(api))
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 318, in get_content
    response = request.urlopen(req)
  File "/usr/local/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by bonecto** [comment]
我的网络没有问题，其它的是可以正常下载， 
http://www.bilibili.com/video/av6233336      正常
http://bangumi.bilibili.com/anime/v/86847   不正常

[root@pc-01 ~]# you-get -di http://www.bilibili.com/video/av6233336/
[DEBUG] get_content: http://www.bilibili.com/video/av6233336/
[DEBUG] get_content: http://www.bilibili.com/m/html5?aid=6233336&page=1
Site:       bilibili.com
Title:      Type:       MPEG-4 video (video/mp4)
Size:       7.84 MiB (8216325 Bytes)

[DEBUG] get_content: http://www.bilibili.com/m/html5?aid=6233336&page=2
Site:       bilibili.com
Title:      Type:       MPEG-4 video (video/mp4)
Size:       7.02 MiB (7359776 Bytes)

**Comment by nuomi1** [comment]
你的都不是最新版……

```
➜ ~ yg -d http://bangumi.bilibili.com/anime/v/86847
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/86847
[DEBUG] get_content: http://www.bilibili.com/video/av2701916/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=4224425&from=miniplay&player=1&sign=71e7a09114a0ce4562b7d29c7a7bb6a8
Site:       bilibili.com
Title:      【剧场版】哆啦A梦 大雄的宇宙英雄记【129.3&清藍&EMTP-Raws】
Type:       Flash video (video/x-flv)
Size:       824.27 MiB (864308891 Bytes)

Downloading 【剧场版】哆啦A梦 大雄的宇宙英雄记【129.3&清藍&EMTP-Raws】.flv ...
 0.0% (  0.2/824.3MB) ├─────────────────────────────────────────┤[1/1]  145 kB/s
```

**Comment by bonecto** [comment]
我通过 pip3 安装的 
you-get: version 0.4.536
python3: version 3.5.2

通过把仓库代码克隆本地然后运行正常了，多谢。。。
git clone https://github.com/soimort/you-get.git
./you-get -di http://bangumi.bilibili.com/anime/v/86847
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/86847
[DEBUG] get_content: http://www.bilibili.com/video/av2701916/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=4224425&from=miniplay&player=1&sign=71e7a09114a0ce4562b7d29c7a7bb6a8
Site:       bilibili.com
Title:      Type:       Flash video (video/x-flv)
Size:       824.27 MiB (864308891 Bytes)

**Comment by bonecto** [comment]
克隆仓库的最近代码，今天又出现不能下载了
测试地址：http://bangumi.bilibili.com/movie/11870

[bone@pc-01 you-get]$ ./you-get -di http://bangumi.bilibili.com/movie/11870
[DEBUG] get_content: http://bangumi.bilibili.com/movie/11870
[DEBUG] get_content: None
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/movie/11870']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/bone/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/bone/you-get/src/you_get/common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/bone/you-get/src/you_get/common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/bone/you-get/src/you_get/common.py", line 1077, in download_main
    download(url, **kwargs)
  File "/home/bone/you-get/src/you_get/common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "/home/bone/you-get/src/you_get/extractors/bilibili.py", line 125, in bilibili_download
    html = get_content(url)
  File "/home/bone/you-get/src/you_get/common.py", line 312, in get_content
    req = request.Request(url, headers=headers)
  File "/usr/local/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/local/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/local/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'None'

**Comment by woodword** [comment]
有时网络不稳定会造成You-get出错，优酷经常有这个毛病，要么直接出错，要么you-get长时间没反应，不得不ctrl+C。多试几次就好了
