### ISSUE TITLE
URL 参数带引号会导致无法下载

### ISSUE THREAD

**Issue by ad52825196** [soimort/you-get#1416]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ✓] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ✓] Your `you-get` is up-to-date.
- [ ✓] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ✓] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ✓] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
>you-get-0.4.555-win32 --debug "http://v.youku.com/v_show/id_XMTczNDk4MjQzMg==.html?spm=0.0.contentCard--updateFeed.A.xt6HFL"
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTczNDk4MjQzMg==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTczNDk4MjQzMg==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/847469763604912b45fb9_00/st/mp4/fileid/030008010057E49C7706DA0182ECB0286EE657-1B04-2C73-3938-DE9DB8491456?ctype=12&token=3749&yxon=1&K=3732d5d86b21d1812412c072&oip=1700961264&ep=eiaTHk%2BEUcgD4yPbgT8bNSjnIiUGXP4J9h%2BFidJjALshT527kE3WwJ22Oo5CF%2FEbB1F0EOn5raWSbEUTYfExqWwQ3T2vOvrj9%2FPr5dkmzeRybh0%2Fc8nSslSdRDT4&ev=1
site:                优酷 (Youku)
title:               【游民星空】真正的变形金刚
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          22.2 MiB (23226395 bytes)
    # download-with: you-get --format=mp4 [URL]

you-get: [Failed] Cannot extract video source.
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTczNDk4MjQzMg==.html?spm=0.0.contentCard--updateFeed.A.xt6HFL']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1348, in main
  File "src\you_get\common.py", line 1261, in script_main
  File "src\you_get\common.py", line 1077, in download_main
  File "src\you_get\common.py", line 1341, in any_download
  File "src\you_get\extractor.py", line 52, in download_by_url
  File "src\you_get\extractor.py", line 203, in download
  File "src\you_get\util\log.py", line 98, in wtf
NameError: name 'exit' is not defined
you-get returned -1
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ✓] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ✓] 您的`you-get`为最新版.
- [ ✓] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ✓] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ✓] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
>you-get-0.4.555-win32 --debug "http://v.youku.com/v_show/id_XMTczNDk4MjQzMg==.html?spm=0.0.contentCard--updateFeed.A.xt6HFL"
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTczNDk4MjQzMg==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTczNDk4MjQzMg==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/847469763604912b45fb9_00/st/mp4/fileid/030008010057E49C7706DA0182ECB0286EE657-1B04-2C73-3938-DE9DB8491456?ctype=12&token=3749&yxon=1&K=3732d5d86b21d1812412c072&oip=1700961264&ep=eiaTHk%2BEUcgD4yPbgT8bNSjnIiUGXP4J9h%2BFidJjALshT527kE3WwJ22Oo5CF%2FEbB1F0EOn5raWSbEUTYfExqWwQ3T2vOvrj9%2FPr5dkmzeRybh0%2Fc8nSslSdRDT4&ev=1
site:                优酷 (Youku)
title:               【游民星空】真正的变形金刚
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          22.2 MiB (23226395 bytes)
    # download-with: you-get --format=mp4 [URL]

you-get: [Failed] Cannot extract video source.
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTczNDk4MjQzMg==.html?spm=0.0.contentCard--updateFeed.A.xt6HFL']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1348, in main
  File "src\you_get\common.py", line 1261, in script_main
  File "src\you_get\common.py", line 1077, in download_main
  File "src\you_get\common.py", line 1341, in any_download
  File "src\you_get\extractor.py", line 52, in download_by_url
  File "src\you_get\extractor.py", line 203, in download
  File "src\you_get\util\log.py", line 98, in wtf
NameError: name 'exit' is not defined
you-get returned -1
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 使用不带引号的 URL 可以成功下载：>you-get-0.4.555-win32 --debug http://v.youku.com/v_show/id_XMTczNDk4MjQzMg==.html?spm=0.0.contentCard--updateFeed.A.xt6HFL
而且其他视频看起来使用带引号的 URL 也没有问题
> [舔 :icecream:!]

**Comment by ad52825196** [comment]
这个应该是网络问题，重试次数多了就可以成功
