### ISSUE TITLE
视频合并出错

### ISSUE THREAD

**Issue by ad52825196** [soimort/you-get#1417]
Please make sure these boxes are checked before submitting your issue – thank you!
- [ ✓] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ✓] Your `you-get` is up-to-date.
- [ ✓] I have read https://github.com/soimort/you-get/wiki/FAQ and tried to do so.
- [ ✓] The issue is not yet reported on https://github.com/soimort/you-get/issues or  https://github.com/soimort/you-get/wiki/Known-Bugs. If so, please add your comments under the existing issue.
- [ ✓] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
>you-get-0.4.555-win32 --debug "http://v.youku.com/v_show/id_XMTczNTc0MzI2MA==.html?spm=0.0.contentCard--updateFeed.A.baiwcR"
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTczNTc0MzI2MA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTczNTc0MzI2MA==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/747469858583712c4053a_00/st/flv/fileid/030080020057E5452A87C00182ECB08D2FFD15-6E4A-4F62-71C2-D2DBFB69ABEC?ep=dSaTHk%2BEXssI4Cvcjz8bNCjicXReXP4J9h%2BNgdJgALshT526nTvTtpW3Pf9CF%2FEbB1F0EOOFqaaRHkERYfY2rRkQ2ziuO%2Frn%2F4Ph5dlRsOJ2FB8%2FA7%2Bix1SdQDP4&ctype=12&K=606b3eede61dcc5e282bc10d&token=3339&ev=1&oip=1700961264&yxon=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/747469858583712c4053a_00/st/flv/fileid/030080020157E5452A87C00182ECB08D2FFD15-6E4A-4F62-71C2-D2DBFB69ABEC?ep=dSaTHk%2BEXssI4Cvcjz8bNCjicXReXP4J9h%2BNgdJgALohT526nTvTtpW3Pf9CF%2FEbB1F0EOOFqaaRHkERYfY2rRkQ2ziuO%2Frn%2F4Ph5dlRsOJ2FB8%2FA7%2Bix1SdQDP4&ctype=12&K=219f5694baeb5509282bc10d&token=3339&ev=1&oip=1700961264&yxon=1
site:                优酷 (Youku)
title:               【游民星空】《看门狗2》剧情预告
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          60.2 MiB (63122891 bytes)
    # download-with: you-get --format=hd3 [URL]

Downloading 【游民星空】《看门狗2》剧情预告.flv ...
50.9% ( 30.7/ 60.2MB) ├█████████████████████────────────────────┤[1/2]   49 M 100% ( 60.2/ 60.2MB) ├█████████████████████████████████████████┤[2/2]   39 MB/s
Merging video parts...
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTczNTc0MzI2MA==.html?spm=0.0.contentCard--updateFeed.A.baiwcR']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1348, in main
  File "src\you_get\common.py", line 1261, in script_main
  File "src\you_get\common.py", line 1077, in download_main
  File "src\you_get\common.py", line 1341, in any_download
  File "src\you_get\extractor.py", line 52, in download_by_url
  File "src\you_get\extractor.py", line 208, in download
  File "src\you_get\common.py", line 764, in download_urls
  File "src\you_get\processor\join_flv.py", line 306, in concat_flv
  File "src\you_get\processor\join_flv.py", line 247, in read_flv_header
AssertionError
you-get returned -1
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!
- [ ✓] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ✓] 您的`you-get`为最新版.
- [ ✓] 我已经阅读并按 https://github.com/soimort/you-get/wiki/FAQ 中的指引进行了操作.
- [ ✓] 您的问题没有在https://github.com/soimort/you-get/issues , https://github.com/soimort/you-get/wiki/FAQ 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.
- [ ✓] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
>you-get-0.4.555-win32 --debug "http://v.youku.com/v_show/id_XMTczNTc0MzI2MA==.html?spm=0.0.contentCard--updateFeed.A.baiwcR"
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTczNTc0MzI2MA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTczNTc0MzI2MA==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/747469858583712c4053a_00/st/flv/fileid/030080020057E5452A87C00182ECB08D2FFD15-6E4A-4F62-71C2-D2DBFB69ABEC?ep=dSaTHk%2BEXssI4Cvcjz8bNCjicXReXP4J9h%2BNgdJgALshT526nTvTtpW3Pf9CF%2FEbB1F0EOOFqaaRHkERYfY2rRkQ2ziuO%2Frn%2F4Ph5dlRsOJ2FB8%2FA7%2Bix1SdQDP4&ctype=12&K=606b3eede61dcc5e282bc10d&token=3339&ev=1&oip=1700961264&yxon=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/747469858583712c4053a_00/st/flv/fileid/030080020157E5452A87C00182ECB08D2FFD15-6E4A-4F62-71C2-D2DBFB69ABEC?ep=dSaTHk%2BEXssI4Cvcjz8bNCjicXReXP4J9h%2BNgdJgALohT526nTvTtpW3Pf9CF%2FEbB1F0EOOFqaaRHkERYfY2rRkQ2ziuO%2Frn%2F4Ph5dlRsOJ2FB8%2FA7%2Bix1SdQDP4&ctype=12&K=219f5694baeb5509282bc10d&token=3339&ev=1&oip=1700961264&yxon=1
site:                优酷 (Youku)
title:               【游民星空】《看门狗2》剧情预告
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          60.2 MiB (63122891 bytes)
    # download-with: you-get --format=hd3 [URL]

Downloading 【游民星空】《看门狗2》剧情预告.flv ...
50.9% ( 30.7/ 60.2MB) ├█████████████████████────────────────────┤[1/2]   49 M 100% ( 60.2/ 60.2MB) ├█████████████████████████████████████████┤[2/2]   39 MB/s
Merging video parts...
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTczNTc0MzI2MA==.html?spm=0.0.contentCard--updateFeed.A.baiwcR']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1348, in main
  File "src\you_get\common.py", line 1261, in script_main
  File "src\you_get\common.py", line 1077, in download_main
  File "src\you_get\common.py", line 1341, in any_download
  File "src\you_get\extractor.py", line 52, in download_by_url
  File "src\you_get\extractor.py", line 208, in download
  File "src\you_get\common.py", line 764, in download_urls
  File "src\you_get\processor\join_flv.py", line 306, in concat_flv
  File "src\you_get\processor\join_flv.py", line 247, in read_flv_header
AssertionError
you-get returned -1
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by gonejack** [comment]
没装那什么，ffmpeg，这坑我也踩过，脚本不提示的。

**Comment by ad52825196** [comment]
嗯的确是没手动装过 ffmpeg，不过测试了一下，只有1080p的合并会出错，用 --format=hd2 下载超清版本是可以正常合并的
