### ISSUE TITLE
爱奇艺，视频解析问题

### ISSUE THREAD

**Issue by mengmo** [soimort/you-get#1418]
```
python -m you_get -di http://www.iqiyi.com/v_19rr9h0t5g.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/542711800/498ea80a002b233de6e46745b68aaf60/?t=1474791035593&sc=c6cb80142fa624b2f307eff803df2367&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rr9h0t5g.html']
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 95, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1077, in download_main
    download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractors\iqiyi.py", line 140, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video
```

**Comment by mogu1121** [comment]
you-get -di http://www.iqiyi.com/v_19rr9h0yto.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/542765600/cc79923352055d57becf5f79b7817e52/?t=1474918092999&sc=d8cdf6cefc337aee98e3ee5dc4a0d4ff&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: vd: 1 is not handled
you-get: info is {'vid': '43f62760005998a7e1c4beae2df30506', 'vd': 1}
you-get: vd: 2 is not handled
you-get: info is {'vid': '04a698129c0c7b622eb15f448780c6ea', 'vd': 2}
site:                爱奇艺 (Iqiyi)
title:               航海王第757集
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________

**Comment by rosynirvana** [comment]
#1861
