### ISSUE TITLE
乐视体育无法下载

### ISSUE THREAD

**Issue by goroma** [soimort/you-get#1421]
乐视 http://www.le.com   --可以下载
乐视体育 http://www.lesports.com 播放页地址是http://sports.le.com  --无法下载
两个区别我看乐视体育解析的api返回内容是空的，导致无法下载。

[debug日志]
C:\Python34\python D:\Tools\you-get\you-get/you-get-master/you-get -di http://sports.le.com/video/topic/s/20034_26653001.html
[DEBUG] get_content: http://sports.le.com/video/topic/s/20034_26653001.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=None&platid=1&splatid=101&format=1&tkey=3430356118&domain=www.letv.com
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://sports.le.com/video/topic/s/20034_26653001.html']
Traceback (most recent call last):
  File "D:\Tools\you-get\you-get/you-get-master/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "D:\Tools\you-get\you-get\you-get-master/src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "D:\Tools\you-get\you-get\you-get-master/src\you_get\common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "D:\Tools\you-get\you-get\you-get-master/src\you_get\common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "D:\Tools\you-get\you-get\you-get-master/src\you_get\common.py", line 1060, in download_main
    download(url, **kwargs)
  File "D:\Tools\you-get\you-get\you-get-master/src\you_get\common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "D:\Tools\you-get\you-get\you-get-master/src\you_get\extractors\le.py", line 137, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "D:\Tools\you-get\you-get\you-get-master/src\you_get\extractors\le.py", line 90, in letv_download_by_vid
    ext , urls = video_info(vid,**kwargs)
  File "D:\Tools\you-get\you-get\you-get-master/src\you_get\extractors\le.py", line 61, in video_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'

**Comment by N46AN** [comment]
貌似还是 #1000 的问题。
修改 le.py 中 letv_download()
大概第 136 行
```
if match1(url, r'http://sports.le.com/video/(\d+).html') is not None:
            title = match1(html,r'name="keywords" content="(.*?)"')
        else:
            title = match1(html,r'name="irTitle" content="(.*?)"')
```
再在前面加上
```
match1(url, r'http://sports.le.com/video/(\d+).html') or \
```
即可下载

**Comment by goroma** [comment]
用新的py问题解决了，非常感谢。
