### ISSUE TITLE
douyu视频，-u参数会导致exception

### ISSUE THREAD

**Issue by ykelvis** [soimort/you-get#1423]
```
$ brew info you-get
you-get: stable 0.4.555 (bottled), HEAD
```

复现 `you-get --debug -u https://www.douyu.com/saxon`
看起来是douyutv.py调用download_url_ffmpeg那里把None传给了params的原因

完整日志

```
[DEBUG] get_content: http://www.douyu.com/saxon
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=171304
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['https://www.douyu.com/saxon']
Site:       douyu.com
Title:      ACEdota2升级赛RG-EhomeX
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Real URL:
['http://hdla.douyucdn.cn/live/171304r8CpKTjpmm.flv?wsAuth=383294032e5b6943b3aaa4ea517059f4&token=web-douyu-0-171304-ae14bf151073cf66daf84276117759f1&logo=0&expire=0&did=06CAD862F8844485BD6040CBC5F42260']

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.555', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.555/libexec/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.555/libexec/lib/python3.5/site-packages/you_get/common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.555/libexec/lib/python3.5/site-packages/you_get/common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.555/libexec/lib/python3.5/site-packages/you_get/common.py", line 1077, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.555/libexec/lib/python3.5/site-packages/you_get/common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.555/libexec/lib/python3.5/site-packages/you_get/extractors/douyutv.py", line 52, in douyutv_download
    download_url_ffmpeg(real_url, title, 'flv', None, output_dir = output_dir, merge = merge)
  File "/usr/local/Cellar/you-get/0.4.555/libexec/lib/python3.5/site-packages/you_get/common.py", line 909, in download_url_ffmpeg
    if params.get("-y",False): #None or unset ->False
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by cnbeining** [comment]
我的天哦 我在ffmpeg的wrapper那做了什么。。。

![image](https://cloud.githubusercontent.com/assets/1560962/18981291/db911df2-86aa-11e6-8c96-596ed11db9b8.png)

**Comment by WuYaoH** [comment]
有趣
