### ISSUE TITLE
bilibili 无法解析

### ISSUE THREAD

**Issue by mengmo** [soimort/you-get#1425]
```
python -m you_get -di http://www.bilibili.com/video/av6429835/
[DEBUG] get_content: http://www.bilibili.com/video/av6429835/
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av6429835/']
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 95, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1077, in download_main
    download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractors\bilibili.py", line 135, in bilibili_download
    assert flashvars
AssertionError
```

**Comment by SuperN0va** [comment]
you-get -di http://www.bilibili.com/video/av6429054/
[DEBUG] get_content: http://www.bilibili.com/video/av6429054/
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av6429054/']
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1077, in download_main
    download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\extractors\bilibili.py", line 135, in bilibili_download
    assert flashvars
AssertionError

**Comment by soimort** [comment]
![screenshot from 2016-10-05 14-09-48](https://cloud.githubusercontent.com/assets/342945/19112526/94e79cb4-8b05-11e6-8aa1-442568899e8a.png)

**Comment by mengmo** [comment]
```
python -m you_get -di http://bangumi.bilibili.com/anime/v/92403
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/92403
[DEBUG] get_content: http://www.bilibili.com/video/av6429835/
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/v/92403']
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 95, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1077, in download_main
    download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractors\bilibili.py", line 135, in bilibili_download
    assert flashvars
AssertionError
```
```
python -m you_get -di http://bangumi.bilibili.com/anime/v/92392
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/92392
[DEBUG] get_content: http://www.bilibili.com/video/av6429054/
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/v/92392']
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 95, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1077, in download_main
    download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractors\bilibili.py", line 135, in bilibili_download
    assert flashvars
AssertionError
```
@soimort 这是上边两个测试连接相对应的番剧播放页，可以正常播放，同样无法解析下载。
