### ISSUE TITLE
acfun无法解析

### ISSUE THREAD

**Issue by Vayn** [soimort/you-get#1429]
- [ ✔] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ✔] 您的`you-get`为最新版.
- [ ✔] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ✔] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ✔] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.tv/v/ac1105608']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.555', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.555_1/libexec/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.555_1/libexec/lib/python3.5/site-packages/you_get/common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.555_1/libexec/lib/python3.5/site-packages/you_get/common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.555_1/libexec/lib/python3.5/site-packages/you_get/common.py", line 1077, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.555_1/libexec/lib/python3.5/site-packages/you_get/common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.555_1/libexec/lib/python3.5/site-packages/you_get/extractors/acfun.py", line 77, in acfun_download
    title = unescape_html(title)
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/html/__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable
```

> [舔 :icecream:!]

**Comment by redstoneleo** [comment]
C:\Users\i>C:\Users\i\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.
exe -u --debug http://bangumi.bilibili.com/anime/v/91720
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/91720
[DEBUG] get_content: http://www.bilibili.com/video/av5784962/
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/v/91720']
Traceback (most recent call last):
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\Scripts\you-get-scr
ipt.py", line 11, in <module>
    load_entry_point('you-get==0.4.555', 'console_scripts', 'you-get')()
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\common.py", line 1077, in download_main
    download(url, **kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\extractors\bilibili.py", line 135, in bilibili_download
    assert flashvars
AssertionError

C:\Users\i>
