### ISSUE TITLE
Termux支持优化

### ISSUE THREAD

**Issue by bokuno** [soimort/you-get#1431]
你好，我在android 手机上用termux安装了python3，然后安装了you-get，尝试下载网易云音乐上的歌曲。结果报错了，报错输出：
=====START=====
$ you-get --debug http://music.163.com/m/song?id=4983862
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=4983862&ids=[4983862]&csrf_token=
Site:       163.com
Title:      13. My Will
Type:       MP3 (audio/mpeg)
Size:       12.279999999999999 MiB (12879024 Bytes)

Downloading 13. My Will.mp3 ...
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/m/song?id=4983862']
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/common.py", line 1077, in download_main
    download(url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/extractors/netease.py", line 131, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/extractors/netease.py", line 68, in netease_cloud_music_download
    netease_song_download(j["songs"][0], output_dir=output_dir, info_only=info_only)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/extractors/netease.py", line 118, in netease_song_download
    output_dir=output_dir, info_only=info_only)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/extractors/netease.py", line 124, in netease_download_common
    download_urls([url_best], title, ext, size, output_dir)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/common.py", line 727, in download_urls
    bar.update()
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/common.py", line 605, in update
    bar = self.bar.format(percent, round(self.received / 1048576, 1), bar, self.current_piece, self.total_pieces, self.speed)
ValueError: Sign not allowed in string format specifier

$ you-get -u http://music.163.com/m/song?id=4983862    Site:       163.com
Title:      13. My Will
Type:       MP3 (audio/mpeg)
Size:       12.279999999999999 MiB (12879024 Bytes)

Real URLs:
http://p2.music.126.net/r6EtASpJ5L749KLC6a0TmA==/5917571580893653.mp3
Saving 13. My Will.lrc ...Done.
$
=====END=====
可以看到用了-u参数得到了文件的地址，而且在电脑上没这个问题。
希望能确认这到底是什么问题。

**Comment by bokuno** [comment]
我发现了一个现象：
我的手机是1280*720的屏幕，
当我竖屏的时候，会出现上面那个问题，
而当我横屏使用时，就不会出现上面那个问题了。
所以应该是python和termux的问题吧。
关闭。
