### ISSUE TITLE
bilibili 解析问题

### ISSUE THREAD

**Issue by mengmo** [soimort/you-get#1436]
```
python -m you_get -di http://bangumi.bilibili.com/anime/v/91544
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/91544
[DEBUG] get_content: http://www.bilibili.com/video/av6571099/
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/v/91544']
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 95, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1077, in download_main
    download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractors\bilibili.py", line 135, in bilibili_download
    assert flashvars
AssertionError
```

**Comment by NoahChang94** [comment]
Same as #1391

**Comment by mengmo** [comment]
@NCACN #1391 跟这个不是一个版本的问题吧？而且我这边是在 #1425 这个的时间之后才出现问题的(每周都追番的，而且基本是每天都要用)

**Comment by nuomi1** [comment]
现在 bilibili 对某些新番强制从 `http://www.bilibili.com/video/av**/` 跳转到 `http://bangumi.bilibili.com/anime/v/**`，估计是这里出问题了。

**Comment by NCACN** [comment]
不好意思哈，已修复。
