### ISSUE TITLE
乐视这个地址无法下载

### ISSUE THREAD

**Issue by tulip33** [soimort/you-get#1444]
http://zongyi.le.com/izt/kjxjw/index.html#vid=26730966

>you-get --debug http://zongyi.le.com/izt/kjxjw/index.html#vid=26730966
[DEBUG] get_content: http://zongyi.le.com/izt/kjxjw/index.html#vid=26730966
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=26738450&platid=1&splatid=101&format=1&tkey=2192280726&domain=www.letv.com
Current Video Supports:
        --format 1080p <URL>
        --format 1300 <URL>
        --format 1000 <URL>
        --format 720p <URL>
        --format 350 <URL>
[DEBUG] get_content: http://play.g3proxy.lecloud.com/vod/v2/MjMzLzI1LzgxL2xldHYtdXRzLzE0L3Zlcl8wMF8yMi0xMDY3MjY1ODcyLWF2Yy0yOTk4OTE0LWFhYy0xMjgwMDEtNjEzNzg4MC0yNDA4NDIzMjgxLTkyNGI1ZThmYTE5YjMxMDM4YzIyYjEwZmNjOWI2NGNiLTE0NzU5NzEyMDczODIubXA0?b=3139&mmsid=61461302&tm=1475976778&key=fbebb2f1f5ccfb669b8a671169f131af&platid=1&splatid=101&playid=0&tss=ios&vtype=52&cvid=106763600263&payff=0&pip=b800b9125c5cbe6d6d0352d443e746e2&ctv=pc&m3v=1&termid=1&format=1&hwtype=un&ostype=Linux&tag=letv&sign=letv&expect=3&tn=0.8398697798589632&pay=0&iscpn=f9051&rateid=1080p
[DEBUG] get_content: http://218.61.209.61/233/25/81/letv-uts/14/ver_00_22-1067265872-avc-2998914-aac-128001-6137880-2408423281-924b5e8fa19b31038c22b10fcc9b64cb-1475971207382.m3u8?crypt=79aa7f2e3531&b=3139&nlh=4096&nlt=60&bf=90&p2p=1&video_type=mp4&termid=1&tss=ios&platid=1&splatid=101&its=0&qos=3&fcheck=0&amltag=100&mltag=100&proxy=2086645883,708280893,467476967&uid=1910999821.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&ntm=1475995200&nkey=0d4713a6826f2a7e7b131d09cbdf0978&nkey2=5a67565dcc78749c7bb3f8843991a7f5&geo=CN-6-71-2&mmsid=61461302&tm=1475976778&key=fbebb2f1f5ccfb669b8a671169f131af&playid=0&vtype=52&cvid=106763600263&payff=0&ctv=pc&m3v=1&hwtype=un&ostype=Linux&tag=letv&sign=letv&tn=0.8398697798589632&pay=0&iscpn=f9051&rateid=1080p&errc=0&gn=1173&vrtmcd=102&buss=100&cips=113.231.139.13
Site:       Le.com
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://zongyi.le.com/izt/kjxjw/index.html#vid=26730966']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1348, in main
  File "src\you_get\common.py", line 1261, in script_main
  File "src\you_get\common.py", line 1077, in download_main
  File "src\you_get\common.py", line 1341, in any_download
  File "src\you_get\extractors\le.py", line 137, in letv_download
  File "src\you_get\extractors\le.py", line 96, in letv_download_by_vid
  File "src\you_get\common.py", line 996, in print_info
  File "html\__init__.py", line 130, in unescape
TypeError: argument of type 'NoneType' is not iterable
you-get returned -1

>

**Comment by lki2019** [comment]
好像是下载不了，
