### ISSUE TITLE
乐视解析失败，无论在家里还是SSH到另一个地方，用不用proxy还是一样的错误

### ISSUE THREAD

**Issue by ShekBoy** [soimort/you-get#1455]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
>you-get -y 27.194.230.14:8888 --debug http://www.le.com/ptv/vplay/24093058.html
[DEBUG] get_content: http://www.le.com/ptv/vplay/24093058.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=24093058&platid=1&splatid=101&format=1&tkey=2540603542&domain=www.letv.com
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/24093058.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1348, in main
  File "src\you_get\common.py", line 1263, in script_main
  File "src\you_get\common.py", line 1077, in download_main
  File "src\you_get\common.py", line 1341, in any_download
  File "src\you_get\extractors\le.py", line 137, in letv_download
  File "src\you_get\extractors\le.py", line 90, in letv_download_by_vid
  File "src\you_get\extractors\le.py", line 61, in video_info
KeyError: 'playurl'
you-get returned -1
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> 

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
>you-get -y 27.194.230.14:8888 --debug http://www.le.com/ptv/vplay/24093058.html
[DEBUG] get_content: http://www.le.com/ptv/vplay/24093058.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=24093058&platid=1&splatid=101&format=1&tkey=2540603542&domain=www.letv.com
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/24093058.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1348, in main
  File "src\you_get\common.py", line 1263, in script_main
  File "src\you_get\common.py", line 1077, in download_main
  File "src\you_get\common.py", line 1341, in any_download
  File "src\you_get\extractors\le.py", line 137, in letv_download
  File "src\you_get\extractors\le.py", line 90, in letv_download_by_vid
  File "src\you_get\extractors\le.py", line 61, in video_info
KeyError: 'playurl'
you-get returned -1
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 无论有没有用proxy还是出现一样的错误

**Comment by ShekBoy** [comment]
我在自己家里还是用SSH到另一个地方运行you-get解析，无论有没有用proxy还是一样错误...

**Comment by ShekBoy** [comment]
发现问题了，之前proxy可以用-y参数，现在一定要-x不能只用-y
