### ISSUE TITLE
402 error

### ISSUE THREAD

**Issue by randinfo** [soimort/you-get#1459]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x ] Your `you-get` is up-to-date.
- [x ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
root@ns3048880:~# you-get --debug -i 'https://www.youtube.com/watch?v=jNQXAC9IVRw'
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=jNQXAC9IVRw
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=jNQXAC9IVRw']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1077, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 319, in get_content
    response = request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 402: Payment Required

```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> I'm using ovh servers maybe it needs to force ipv4 use

**Comment by randinfo** [comment]
root@ns3048880:~# you-get -di https://www.youtube.com/watch?v=jNQXAC9IVRw
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=jNQXAC9IVRw
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=jNQXAC9IVRw']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1077, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 319, in get_content
    response = request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 402: Payment Required

My ip is loacted in france
And python version :
root@ns3048880:~# python --version
Python 2.7.9

installed via root@ns3048880:~# apt-get install python3

**Comment by soimort** [comment]
Check if there's something wrong with your server (I assume you're using a VPS), for example, it reached its bandwidth limit.

**Comment by randinfo** [comment]
No i'm using a dedicated server. The problem was that that youtube block all the ipv6 ips from ovh. So i had just to disable ipv6 to force it to use ipv4. It will be cool if there is an option in your software to force juste the program to use ipv4 and not disable it all over the machine.

**Comment by soimort** [comment]
I don't think YouTube is blocking IPv6 intentionally. I saw people somewhere on the Internet complaining about hitting geoip restrictions with their IPv6 addresses, but not IPv4, so I guess it's just YouTube's problem.

I wasn't aware that IP layer can cause an accessibility issue like this (until now). If we have more reports regarding IPv4/v6 specific problems, I will definitely add this feature.

**Comment by cnbeining** [comment]
OVH is known to have bad IP reputation. Maybe try HE's tunnel.

2016年10月19日星期三，Mort Yao <notifications@github.com> 写道：
