### ISSUE TITLE
0.4.555版无法下载ACFUN的视频

### ISSUE THREAD

**Issue by sde31c** [soimort/you-get#1465]
>you-get --debug http://www.acfun.tv/v/ac3183433
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.tv/v/ac3183433']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1348, in main
  File "src\you_get\common.py", line 1261, in script_main
  File "src\you_get\common.py", line 1077, in download_main
  File "src\you_get\common.py", line 1341, in any_download
  File "src\you_get\extractors\acfun.py", line 77, in acfun_download
  File "html\__init__.py", line 130, in unescape
TypeError: argument of type 'NoneType' is not iterable
you-get returned -1

似乎所有acfun的视频都无法下载了。。。

**Comment by cnbeining** [comment]
请使用Github的最新版。

安装方法见Wiki。
