### ISSUE TITLE
Cannot download from iqiyi

### ISSUE THREAD

**Issue by scegg** [soimort/you-get#1482]
video file: http://www.iqiyi.com/v_19rrlzx5l4.html

Playable in Chrome.
You-get is unzipped from 7z, version is 0.4.555.

site:                爱奇艺 (Iqiyi)
title:               科技相对论 第二季&nbsp;&nbsp;王自如：科技是什么？
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by scegg** [comment]
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/524150500/3a99ece685734fcc98cc0fa6f68fb19d/?t=1477579074395&sc=c5e456c59b130762e25b3b6224d13045&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               科技相对论 第二季&nbsp;&nbsp;王自如：科技是什么？
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrlzx5l4.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1348, in main
  File "src\you_get\common.py", line 1261, in script_main
  File "src\you_get\common.py", line 1077, in download_main
  File "src\you_get\common.py", line 1341, in any_download
  File "src\you_get\extractor.py", line 52, in download_by_url
  File "src\you_get\extractors\iqiyi.py", line 204, in download
  File "src\you_get\common.py", line 918, in download_url_ffmpeg
AssertionError: FFmpeg not installed.
you-get returned -1

**Comment by scegg** [comment]
OK, I got the info now.
It seems that I need to get FFmpeg working before. Thanks.
