### ISSUE TITLE
I am not sure about this

### ISSUE THREAD

**Issue by iliuhe** [soimort/you-get#1484]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```

C:\Python35\Scripts>you-get --debug 'http://bangumi.bilibili.com/anime/v/65128'
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ["'http://bangumi.bilibili.com/anime/v/65128'"]
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python35\lib\site-packages\you_get\common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python35\lib\site-packages\you_get\common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\python35\lib\site-packages\you_get\common.py", line 1077, in download_main
    download(url, **kwargs)
  File "c:\python35\lib\site-packages\you_get\common.py", line 1340, in any_download
    m, url = url_to_module(url)
  File "c:\python35\lib\site-packages\you_get\common.py", line 1331, in url_to_module
    conn.request("HEAD", video_url, headers=fake_headers)
  File "c:\python35\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "c:\python35\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "c:\python35\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "c:\python35\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "c:\python35\lib\http\client.py", line 877, in send
    self.connect()
  File "c:\python35\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\python35\lib\socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "c:\python35\lib\socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> Am I the only guy who got this problem? I tried this:
    you-get 'https://www.youtube.com/watch?v=jNQXAC9IVRw'
which also failed. 
> :(

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by cnbeining** [comment]
>socket.gaierror: [Errno 11001] getaddrinfo failed

Please check your DNS.

**Comment by soimort** [comment]
Drop the single quotes `'` on Windows.
