### ISSUE TITLE
优酷视频下载到一半报错 HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by ad52825196** [soimort/you-get#1500]
视频地址：http://v.youku.com/v_show/id_XMTgwNjE0NjMzNg==.html

```
>you-get-0.4.575-win32.exe -d -o "/【风笑试玩】芬兰老炮儿的日常丨My Summer Car 试玩" --format=hd2 http://v.youku.com/v_show/id_XMTgwNjE0NjMzNg==.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTgwNjE0NjMzNg==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTgwNjE0NjMzNg==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/147839407966712eb6da5_00/st/flv/fileid/0300010700581D1DB50281023230A42191F904-392A-CA4E-E147-45FDAC69B92A?ep=cyaTEkqEUs4H7CXZjz8bMn7kICYKXP4J9h%2BFgNJlALshQOnLmEqjwp2yRv5CFPobcSJ3FOnwotGRY0AQYfNKqxkQrD%2BsTPqV%2F%2FTk5alWsuRxFR8%2FAMTVxVSeSjP4&oip=1700961264&ctype=12&token=0939&K=fcb35347ef355f92282bdd1f&yxon=1&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/147839407966712eb6da5_00/st/flv/fileid/0300010701581D1DB50281023230A42191F904-392A-CA4E-E147-45FDAC69B92A?ep=cyaTEkqEUs4H7CXZjz8bMn7kICYKXP4J9h%2BFgNJlALohQOnLmEqjwp2yRv5CFPobcSJ3FOnwotGRY0AQYfNKqxkQrD%2BsTPqV%2F%2FTk5alWsuRxFR8%2FAMTVxVSeSjP4&oip=1700961264&ctype=12&token=0939&K=da22056e7d5df4f0261f54cd&yxon=1&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/147839407966712eb6da5_00/st/flv/fileid/0300010702581D1DB50281023230A42191F904-392A-CA4E-E147-45FDAC69B92A?ep=cyaTEkqEUs4H7CXZjz8bMn7kICYKXP4J9h%2BFgNJlALkhQOnLmEqjwp2yRv5CFPobcSJ3FOnwotGRY0AQYfNKqxkQrD%2BsTPqV%2F%2FTk5alWsuRxFR8%2FAMTVxVSeSjP4&oip=1700961264&ctype=12&token=0939&K=06626be2c889b7542412cc7b&yxon=1&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/147839407966712eb6da5_00/st/flv/fileid/0300010703581D1DB50281023230A42191F904-392A-CA4E-E147-45FDAC69B92A?ep=cyaTEkqEUs4H7CXZjz8bMn7kICYKXP4J9h%2BFgNJlALghQOnLmEqjwp2yRv5CFPobcSJ3FOnwotGRY0AQYfNKqxkQrD%2BsTPqV%2F%2FTk5alWsuRxFR8%2FAMTVxVSeSjP4&oip=1700961264&ctype=12&token=0939&K=7a7f03a5559003f5282bdd1f&yxon=1&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/147839407966712eb6da5_00/st/flv/fileid/0300010704581D1DB50281023230A42191F904-392A-CA4E-E147-45FDAC69B92A?ep=cyaTEkqEUs4H7CXZjz8bMn7kICYKXP4J9h%2BFgNJlAL8hQOnLmEqjwp2yRv5CFPobcSJ3FOnwotGRY0AQYfNKqxkQrD%2BsTPqV%2F%2FTk5alWsuRxFR8%2FAMTVxVSeSjP4&oip=1700961264&ctype=12&token=0939&K=7a8269cd7ef44ac32412cc7b&yxon=1&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/147839407966712eb6da5_00/st/flv/fileid/0300010705581D1DB50281023230A42191F904-392A-CA4E-E147-45FDAC69B92A?ep=cyaTEkqEUs4H7CXZjz8bMn7kICYKXP4J9h%2BFgNJlAL4hQOnLmEqjwp2yRv5CFPobcSJ3FOnwotGRY0AQYfNKqxkQrD%2BsTPqV%2F%2FTk5alWsuRxFR8%2FAMTVxVSeSjP4&oip=1700961264&ctype=12&token=0939&K=2ebbe36c80bb0b18282bdd1f&yxon=1&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/147839407966712eb6da5_00/st/flv/fileid/0300010706581D1DB50281023230A42191F904-392A-CA4E-E147-45FDAC69B92A?ep=cyaTEkqEUs4H7CXZjz8bMn7kICYKXP4J9h%2BFgNJlAL0hQOnLmEqjwp2yRv5CFPobcSJ3FOnwotGRY0AQYfNKqxkQrD%2BsTPqV%2F%2FTk5alWsuRxFR8%2FAMTVxVSeSjP4&oip=1700961264&ctype=12&token=0939&K=8301fc268f98757b261f54cd&yxon=1&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/147839407966712eb6da5_00/st/flv/fileid/03000101005756ACD18896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109?ep=cyaTEkqEUs4H7CXZjz8bMn7kICYKXP4J9h%2BFgNJjALshT%2B256E2lxpW4R%2FlCFvkZcSB1GOyEqaKSY0FlYflE324Q3jurS%2FqR%2BPPn5dknseV1YhFDAMzXvVSeSjP4&oip=1700961264&ctype=12&token=0939&K=68dc2c6610cb889f2412cc7b&yxon=1&ev=1
site:                优酷 (Youku)
title:               【风笑试玩】芬兰老炮儿的日常丨My Summer Car 试玩
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          238.4 MiB (250013035 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 【风笑试玩】芬兰老炮儿的日常丨My Summer Car 试玩.flv ...
16.8% ( 40.1/238.4MB) ├███████──────────────────────────────────┤[1/8]   79 M38.7% ( 92.3/238.4MB) ├████████████████─────────────────────────┤[2/8]  170 M52.8% (125.8/238.4MB) ├██████████████████████───────────────────┤[3/8]  105 MB/syou-get: version 0.4.575, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTgwNjE0NjMzNg==.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1388, in main
  File "src\you_get\common.py", line 1296, in script_main
  File "src\you_get\common.py", line 1117, in download_main
  File "src\you_get\common.py", line 1381, in any_download
  File "src\you_get\extractor.py", line 52, in download_by_url
  File "src\you_get\extractor.py", line 208, in download
  File "src\you_get\common.py", line 780, in download_urls
  File "src\you_get\common.py", line 471, in url_save
  File "src\you_get\common.py", line 389, in url_size
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 471, in open
  File "urllib\request.py", line 581, in http_response
  File "urllib\request.py", line 503, in error
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 686, in http_error_302
  File "urllib\request.py", line 471, in open
  File "urllib\request.py", line 581, in http_response
  File "urllib\request.py", line 509, in error
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 589, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
you-get returned -1
```

**Comment by cnbeining** [comment]
这是CDN坏了吧。不是我们可以修的呀。。

**Comment by ad52825196** [comment]
@cnbeining 在以前的版本中有提过类似的问题 #29

**Comment by woodword** [comment]
我下载youku经常中途出错，需要重新下载几次，直到下载完整，估计是海外网络问题

**Comment by ad52825196** [comment]
网络问题，几天后重试下载成功
