### ISSUE TITLE
command "pip install --upgrade you-get" fails to upgrade the package, keep the package fail in some sites

### ISSUE THREAD

**Issue by Gary-Chow** [soimort/you-get#1515]
前两周能下载《爸爸去哪儿》第四季第4期的，但现在重复多次都一直提示下面的错误。是芒果台修改了网站？感谢

you-get --debug http://www.mgtv.com/b/298442/3676255.html

[DEBUG] get_content: http://v.api.mgtv.com/player/video?video_id=None
you-get: version 0.4.575, a tiny downloader that scrapes the web.
you-get: ['http://www.mgtv.com/b/298442/3676255.html']
Traceback (most recent call last):
  File "/home/gary/opt/anaconda3/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/gary/opt/anaconda3/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/gary/opt/anaconda3/lib/python3.5/site-packages/you_get/common.py", line 1388, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/gary/opt/anaconda3/lib/python3.5/site-packages/you_get/common.py", line 1301, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/gary/opt/anaconda3/lib/python3.5/site-packages/you_get/common.py", line 1117, in download_main
    download(url, **kwargs)
  File "/home/gary/opt/anaconda3/lib/python3.5/site-packages/you_get/common.py", line 1381, in any_download
    m.download(url, **kwargs)
  File "/home/gary/opt/anaconda3/lib/python3.5/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/home/gary/opt/anaconda3/lib/python3.5/site-packages/you_get/extractors/mgtv.py", line 60, in prepare
    self.title = content['data']['info']['title']
TypeError: 'NoneType' object is not subscriptable

**Comment by Gary-Chow** [comment]
Thank you very much for the immediate reply. 
I tried it under two network. I have downloaded video of 芒果TV under these two network two weeks ago. But now I cannot, while I now can still download from youtube.

**Comment by Gary-Chow** [comment]
Compare my debug info and yours. The problem is the "video ID". I got "None", and you got the right one. I check the video id function in mgtv.py as shown below, which is right. I am confused.

    def get_vid_from_url(url):
        """Extracts video ID from URL.
        """
        return match1(url, 'http://www.mgtv.com/v/\d/\d+/\w+/(\d+).html')

**Comment by liushuyu** [comment]
@Gary-Chow Maybe you are using the old version of `you-get`. Keep in mind that installing from `pip` won't give you the latest version of `you-get`

**Comment by Gary-Chow** [comment]
I have used "pip install --upgrade you-get" to upgrade. But the actually the files are not upgraded. I don't know why. So I keep failing. 
Just now, I uninstall and install the you-get, but the file is still the original one. problem is still there. 
At last, I download from github, and manually replace the updated files. And now, it words fine.
Thank you very much!
