### ISSUE TITLE
[激动网]不能解析下载/Cannot videos from joy.cn

### ISSUE THREAD

**Issue by InfiniteSamuel** [soimort/you-get#1519]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ x ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ x ] Your `you-get` is up-to-date.
- [ x ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ x ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ x ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get: version 0.4.575, a tiny downloader that scrapes the web.
you-get: ['http://www.joy.cn/entertainment/videoEntertainment?resourceId=60240134']
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1388, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1301, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1117, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1381, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/joy.py", line 27, in joy_download
    channel_id = r1(r'[^_]channelId\s*:\s*"([^\"]+)"', get_html(url))
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 280, in get_html
    content = get_response(url, faker).data
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 268, in get_response
    response = request.urlopen(url)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

**Comment by cnbeining** [comment]
不不不这纯属对方网站太垃圾吧。

![image](https://cloud.githubusercontent.com/assets/1560962/20418351/8c165724-ad1a-11e6-81c3-1920396f47ab.png)

**Comment by InfiniteSamuel** [comment]
['http://www.joy.cn/entertainment/videoEntertainment?resourceId=60240134']
这个网址下的视频其实也就是一个mp4文件['http://download.3g.joy.cn/video/240/60240134/1479282690155_hd.mp4']
但是如果直接```you-get --debug 'http://download.3g.joy.cn/video/240/60240134/1479282690155_hd.mp4'```，结果是：
```
you-get: version 0.4.575, a tiny downloader that scrapes the web.eo/240/60'
you-get: ['http://download.3g.joy.cn/video/240/60240134/1479282690155_hd.mp4']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1388, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1301, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1117, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1381, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/joy.py", line 31, in joy_download
    title, urls, hostpath = video_info(channel_id, program_id, volumn_id)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/joy.py", line 18, in video_info
    xml = get_html(url)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 280, in get_html
    content = get_response(url, faker).data
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 268, in get_response
    response = request.urlopen(url)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 333: Not Found

```
这个HTTP Error 333挺奇怪的……

**Comment by InfiniteSamuel** [comment]
哦对了，但是如果直接取这个mp4的IP地址替换掉URL，那还是成功的。
```
$you-get --debug 'http://122.227.201.114/video/240/60240134/1479282690155_hd.mp4'
Site:       227.201.114
Title:      1479282690155_hd
Type:       MPEG-4 video (video/mp4)
Size:       7.67 MiB (8044784 Bytes)

Downloading 1479282690155_hd.mp4 ...
 100% (  7.7/  7.7MB) ├████████████████████████████████████████████████┤[1/1]  104 MB/s


```
