### ISSUE TITLE
Video of Tencent and iQiyi cannot be downloaded

### ISSUE THREAD

**Issue by ewerab** [soimort/you-get#1530]
在提交前，请确保您已经检查了以下内容!

- [V ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [V ] 您的`you-get`为最新版.
- [V ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [V ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [V ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:
directory>You-get -i https://v.qq.com/x/cover/upbfcrtqzlggxqe/f0015w80fhv.html --debug
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

[在这里粘贴完整日志]
directory>You-get -i https://v.qq.com/x/cover/upbfcrtqzlggxqe/f0015w80fhv.html
directory>You-get -i http://www.iqiyi.com/v_19rrnexjw8.html

both of them display error messages as below:
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by ewerab** [comment]
I want to download the 1080p of the two video

**Comment by ewerab** [comment]
directory>You-get -i https://v.qq.com/x/cover/upbfcrtqzlggxqe/f0015w80fhv.html --debug
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by ewerab** [comment]
directory>You-get --debug https://v.qq.com/x/cover/upbfcrtqzlggxqe/f0015w80fhv.html
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/upbfcrtqzlggxqe/f0015w80fhv.html']
Traceback (most recent call last):
  File "directory\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "directory\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "directory\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1129, in download_main
    download(url, **kwargs)
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\qq.py", line 106, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\qq.py", line 55, in qq_download_by_vid
    print_info(site_info, parts_ti, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment

**Comment by ewerab** [comment]
Error msg for iQiyi:

directory>You-get --debug http://www.iqiyi.com/v_19rrnexjw8.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/303479700/dc232f0df07064221e105fe6ece000fb/?t=1480299277734&sc=a393528106cad6e2ef5476d8a34fedb7&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrnexjw8.html']
Traceback (most recent call last):
  File "directory\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "directory\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "directory\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1129, in download_main
    download(url, **kwargs)
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "directory\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\iqiyi.py", line 140, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video

**Comment by batjoker** [comment]
about the first Tencent video , you should use link like `https://v.qq.com/x/cover/upbfcrtqzlggxqe.html` or others .
and we can find 
`
>you-get  https://v.qq.com/x/cover/upbfcrtqzlggxqe.html
Site:       QQ.com
Title:      江湖论剑
Type:       MPEG-4 video (video/mp4)
Size:       11.25 MiB (11799758 Bytes)

Downloading 江湖论剑.mp4 ...
 0.0% (  0.0/ 11.3MB) ├──────────────────
 2.2% (  0.2/ 11.3MB) ├█─────────────────
 4.4% (  0.5/ 11.3MB) ├██────────────────
 6.7% (  0.8/ 11.3MB) ├███───────────────
 8.9% (  1.0/ 11.3MB) ├████──────────────
`
However, the software can only find the first part (5min) of whole video , and I can't find solution.

**Comment by soimort** [comment]
iQiyi support is known broken at the moment. PRs are welcome.

**Comment by rosynirvana** [comment]
```
$ ./you-get -i 'https://v.qq.com/x/cover/upbfcrtqzlggxqe/f0015w80fhv.html'
Site:       QQ.com
Title:      江湖论剑
Type:       MPEG-4 video (video/mp4)
Size:       1708.07 MiB (1791035987 Bytes)
```
