### ISSUE TITLE
vimeo download fails

### ISSUE THREAD

**Issue by apournaras** [soimort/you-get#1533]
I am unable to download videos from vimeo. Weird that it works on another computer with the same OS in the same network. I am not so familiar with SSL, so does anyone know if there is anything I can do?
```
DEBUG] get_content: https://vimeo.com/156310868
[DEBUG] get_content: http://player.vimeo.com/video/156310868
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['https://vimeo.com/156310868']
Traceback (most recent call last):
  File "urllib\request.py", line 1240, in do_open
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 1237, in connect
  File "ssl.py", line 376, in wrap_socket
  File "ssl.py", line 747, in __init__
  File "ssl.py", line 983, in do_handshake
  File "ssl.py", line 628, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1400, in main
  File "src\you_get\common.py", line 1313, in script_main
  File "src\you_get\common.py", line 1129, in download_main
  File "src\you_get\common.py", line 1393, in any_download
  File "src\you_get\extractors\vimeo.py", line 67, in vimeo_download
  File "src\you_get\extractors\vimeo.py", line 51, in vimeo_download_by_id
  File "src\you_get\common.py", line 409, in url_info
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 465, in open
  File "urllib\request.py", line 483, in _open
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 1283, in https_open
  File "urllib\request.py", line 1242, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)>
you-get returned -1
```

**Comment by soimort** [comment]
You need to make sure you have valid trusted CA (certificate authority) on your operating system -- Just google on how to install it.
