### ISSUE TITLE
您好，爱奇艺无法下载

### ISSUE THREAD

**Issue by kxy000** [soimort/you-get#1538]
you-get 版本为刚下载的最新版。
爱奇艺地址为 http://www.iqiyi.com/v_19rrifsq4x.html    浏览器中是可以观看的

应该是接口的问题；

--debug 运行后的日志是

>python3 you-get --debug http://www.iqiyi.com/v_19rrifsq4x.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/638269/76137a42ad594c149950efbb2ea1308a/?t=1480582992038&sc=84d0471377dace515be8e038b2de9d1a&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrifsq4x.html']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "E:\you-get-develop/src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "E:\you-get-develop/src\you_get\common.py", line 1405, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "E:\you-get-develop/src\you_get\common.py", line 1318, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "E:\you-get-develop/src\you_get\common.py", line 1134, in download_main
    download(url, **kwargs)
  File "E:\you-get-develop/src\you_get\common.py", line 1398, in any_download
    m.download(url, **kwargs)
  File "E:\you-get-develop/src\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "E:\you-get-develop/src\you_get\extractors\iqiyi.py", line 140, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video

**Comment by rosynirvana** [comment]
这视频没了，可以关了吧
