### ISSUE TITLE
土豆专辑无法解析

### ISSUE THREAD

**Issue by hlshooter** [soimort/you-get#1542]
ngshenpan\ http://www.tudou.com/plcover/SL7BDqBDhJ4/
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by hlshooter** [comment]
Thanks for answer.
only allow English?

**Comment by hlshooter** [comment]
Problem 1:
All download files from a tudou list play will use the same name.If I download a list,I will only recive one file.
Such as this:
you-get.exe -o T:\画师\zhanzhengshenpan\ http://www.tudou.com/listplay/SL7BDqBDhJ4/YpI-H34yieI.html
you-get.exe -o T:\画师\zhanzhengshenpan\ http://www.tudou.com/listplay/SL7BDqBDhJ4/xdqz16CUzOU.html
you-get.exe -o T:\画师\zhanzhengshenpan\ http://www.tudou.com/listplay/SL7BDqBDhJ4/_jMrB4lN9OU.html
you-get.exe -o T:\画师\zhanzhengshenpan\ http://www.tudou.com/listplay/SL7BDqBDhJ4/z_WNDXOlBfk.html
you-get.exe -o T:\画师\zhanzhengshenpan\ http://www.tudou.com/listplay/SL7BDqBDhJ4/z_WNDXOlBfk.html
you-get.exe -o T:\画师\zhanzhengshenpan\ http://www.tudou.com/listplay/SL7BDqBDhJ4/f3cZhpzpodw.html
you-get.exe -o T:\画师\zhanzhengshenpan\ http://www.tudou.com/listplay/SL7BDqBDhJ4/RJWLNwuo57M.html
you-get.exe -o T:\画师\zhanzhengshenpan\ http://www.tudou.com/listplay/SL7BDqBDhJ4/jleziSL2CTk.html
When I finish run this .bat file,I recive only one file.
Problem 2:
you-get don't support tudou listplay.
for exsample:
http://www.tudou.com/plcover/3mnAQx9OQpQ/
you-get result:
R:\3123\231132\you-get-0.4.555-win32-full\you-get>you-get.exe --debug -o T:\画师
\zhanzhengshenpan\ http://www.tudou.com/plcover/3mnAQx9OQpQ/
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.tudou.com/plcover/3mnAQx9OQpQ/']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1400, in main
  File "src\you_get\common.py", line 1313, in script_main
  File "src\you_get\common.py", line 1129, in download_main
  File "src\you_get\common.py", line 1393, in any_download
  File "src\you_get\extractors\tudou.py", line 47, in tudou_download
AttributeError: 'NoneType' object has no attribute 'replace'
you-get returned -1

R:\3123\231132\you-get-0.4.555-win32-full\you-get>pause
请按任意键继续. . .

Thank you very much!
