### ISSUE TITLE
腾讯视频下载失败

### ISSUE THREAD

**Issue by latel** [soimort/you-get#1555]
$ you-get --debug https://v.qq.com/x/cover/fgv49y1mh0z54bi/u0015sfd4wg.html
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/fgv49y1mh0z54bi/u0015sfd4wg.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.595', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/qq.py", line 106, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/qq.py", line 55, in qq_download_by_vid
    print_info(site_info, parts_ti, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment

**Comment by redstoneleo** [comment]
```
C:\Users\i>you-get -u --debug http://v.qq.com/page/d/6/d/d0013t1j56d.html?ptag=b
aidu_aladdin.tv
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/page/d/6/d/d0013t1j56d.html?ptag=baidu_aladdin.tv']
Traceback (most recent call last):
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\Scripts\you-get-scr
ipt.py", line 11, in <module>
    load_entry_point('you-get==0.4.595', 'console_scripts', 'you-get')()
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\common.py", line 1409, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\common.py", line 1322, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\common.py", line 1138, in download_main
    download(url, **kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\common.py", line 1402, in any_download
    m.download(url, **kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\extractors\qq.py", line 86, in qq_download
    if 'kuaibao.qq.com' in url or re.match(r'http://daxue.qq.com/content/content
/id/\d+', url):
TypeError: argument of type 'NoneType' is not iterable

C:\Users\i>

```

**Comment by Justsoos** [comment]
用 @soimort 在master branch 上新改出来的 fake header https://github.com/soimort/you-get/commit/f299d30161f2017318211099979845192a891025 试了下。
前后取到两个不同服务器的qq视频地址，但用mpv播放情况下都很卡，推测：是不是腾讯加了mpv header的黑名单？

之前：
http://lmbsy.qq.com/flv/51/220//q0022tqbeoa.p209.6.mp4?vkey=8EE630271343A0F3AC34D838A198FED1723879523490B7E3DF2BAAB19326EC9C164C6700F05E099BC2577FD47A338A29064B2510CE26FE511CED18330C5F0B5F788F078AFD971B36E5F5C58DB257860E6F81C0A9FDBC768B69288D54A038FAF9

之后：
http://vhoth.dnion.videocdn.qq.com/flv/51/220//q0022tqbeoa.p209.6.mp4?vkey=D5C5E0C5CA7B5B1DBDEA9A871EBABAE1A815B594ED31AB69D52D88CDFB35905D07EDADCE0BD9871B24CBC311DD985BCD9802F00DDAA476EEB9B50FD991C90E8E4D5B5D5E9FE8463FE4776A8CE624A7E8AABC2A14F09040C5B554D798ED0E9092

**Comment by plxus** [comment]
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/xba91rl764hqspo/x01859ooa23.html']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/qq.py", line 103, in qq_download
    content = get_html(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 278, in get_html
    content = get_response(url, faker).data
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 266, in get_response
    response = request.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
