### ISSUE TITLE
无法下载bilibili直播视频流

### ISSUE THREAD

**Issue by heroesm** [soimort/you-get#1560]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get --debug http://live.bilibili.com/193

[DEBUG] get_content: http://live.bilibili.com/193
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://live.bilibili.com/193']
Traceback (most recent call last):
  File "c:\app\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\app\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\app\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\app\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\app\python35-32\lib\site-packages\you_get\common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\app\python35-32\lib\site-packages\you_get\common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\app\python35-32\lib\site-packages\you_get\common.py", line 1129, in download_main
    download(url, **kwargs)
  File "c:\app\python35-32\lib\site-packages\you_get\common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "c:\app\python35-32\lib\site-packages\you_get\extractors\bilibili.py", line 139, in bilibili_download
    assert flashvars
AssertionError

```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> live.bilibili.com最近更改了flash播放器的载入方式（如果伪造navigator.plugins不含有flash插件的话flash播放器根本不会被载入），现在已无法从静态网页中直接获取flash播放器的flashvars属性。
建议通过网页顶部的 `var ROOMID = ` 获取cid。

**Comment by heroesm** [comment]
如果不是b站准备上线html5直播的话，这又是b站的一个无意义瞎折腾。

**Comment by cnbeining** [comment]
我认为上线HTML5的可能性大。

本来使用hls.js配合目前的播放器是个成熟的方案。Proven in ABP-Py.

唉。
