### ISSUE TITLE
请问在网易云音乐下载的时候 能不能支持自定义文件名？

### ISSUE THREAD

**Issue by LOVEChen** [soimort/you-get#1564]
比如 歌手 - 歌名.mp3 这样？

感谢～！

**Comment by LOVEChen** [comment]
sample link:
http://music.163.com/#/playlist?id=481181410
http://music.163.com/#/playlist?id=493708111
现在可以自动解析成 专辑/歌名，如果可以的话，不知道能不能添加规则解析成 专辑/歌手 - 歌名

另外回报一个bug

> you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/playlist?id=481181410']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.595', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/netease.py", line 133, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/netease.py", line 61, in netease_cloud_music_download
    netease_song_download(i, output_dir=new_dir, info_only=info_only, playlist_prefix=playlist_prefix)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/netease.py", line 120, in netease_song_download
    output_dir=output_dir, info_only=info_only)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/netease.py", line 123, in netease_download_common
    songtype, ext, size = url_info(url_best)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 413, in url_info
    response = request.urlopen(request.Request(url))
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
<

> 
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/playlist?id=493708111']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.595', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/netease.py", line 133, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/netease.py", line 61, in netease_cloud_music_download
    netease_song_download(i, output_dir=new_dir, info_only=info_only, playlist_prefix=playlist_prefix)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/netease.py", line 120, in netease_song_download
    output_dir=output_dir, info_only=info_only)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/netease.py", line 123, in netease_download_common
    songtype, ext, size = url_info(url_best)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 413, in url_info
    response = request.urlopen(request.Request(url))
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
<

以上两个列表下载到一定位置会报错退出

**Comment by rosynirvana** [comment]
自定义一个文件名简单，自定义多个文件名难也没人会去用
自定义patterns就更困难了

第二个问题由于api变动过期了
