### ISSUE TITLE
icourse couldn't be downloaded

### ISSUE THREAD

**Issue by MoraGG** [soimort/you-get#1566]
G:\PYthon\Scripts>you-get -d http://www.icourses.cn/coursestatic/course_4319.html
[DEBUG] get_content: http://www.icourses.cn/coursestatic/course_4319.html
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.icourses.cn/coursestatic/course_4319.html']
Traceback (most recent call last):
  File "G:\PYthon\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.4.595', 'console_scripts', 'you-get')()
  File "G:\PYthon\lib\site-packages\you_get-0.4.595-py3.5.egg\you_get\__main__.py", line 92, in main
  File "G:\PYthon\lib\site-packages\you_get-0.4.595-py3.5.egg\you_get\common.py", line 1400, in main
  File "G:\PYthon\lib\site-packages\you_get-0.4.595-py3.5.egg\you_get\common.py", line 1313, in script_main
  File "G:\PYthon\lib\site-packages\you_get-0.4.595-py3.5.egg\you_get\common.py", line 1129, in download_main
  File "G:\PYthon\lib\site-packages\you_get-0.4.595-py3.5.egg\you_get\common.py", line 1393, in any_download
  File "G:\PYthon\lib\site-packages\you_get-0.4.595-py3.5.egg\you_get\extractors\icourses.py", line 19, in icourses_download
  File "G:\PYthon\lib\site-packages\you_get-0.4.595-py3.5.egg\you_get\extractors\icourses.py", line 78, in icourses_cn_url_parser
AttributeError: 'NoneType' object has no attribute 'strip'

G:\PYthon\Scripts>

**Comment by rosynirvana** [comment]
```
./you-get -di http://www.icourses.cn/coursestatic/course_4319.html -l
[DEBUG] get_content: http://www.icourses.cn/coursestatic/course_4319.html
[DEBUG] post_content: http://www.icourses.cn/jpk/viewCharacterDetail2.action?courseId=4319&characId=31920&mod=2
 post_data: {}
[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=469489&courseId=4319
[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=469489&courseId=4319
[DEBUG] get_content: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=469489&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&other=&v=1502374400256
[DEBUG] get_content: http://media1.icourses.cn:8080/process4/campus//ssl/host.shtml
[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=139537
[DEBUG] url_info: http://media3.icourses.cn/process4/campus/processres/flv/2013/8/13/ff808081-4056bb03-0140-75af132c-0041.flv?h=XsLyTWBcnLm5ZPHmZtXl7A&start=0&lt=8-10%2F22%3A15%3A23&lv=150606-1&ls=play&p=151020&r=1502374584
Site:       icourses.cn
Title:      高分子化学   第一章绪论
Type:       Flash video (video/x-flv)
Size:       242.71 MiB (254504003 Bytes)

[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=185412&courseId=4319
[DEBUG] get_content: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=185412&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&other=&v=1502374460251
[DEBUG] get_content: http://media1.icourses.cn:8080/process5/campus//ssl/host.shtml
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=5193030
[DEBUG] url_info: http://media2.icourses.cn/process5/campus/processres/flv/2012/12/11/ff808081-3b84e1e3-013b-8702f370-002a.flv?h=QhUpinxPMuFX0NeqxKxSnQ&start=0&lt=8-10%2F22%3A15%3A33&lv=150606-1&ls=play&p=151020&r=1502404768
Site:       icourses.cn
Title:      高分子化学 第二章 第1节 第二章缩聚和逐步聚合（1）
Type:       Flash video (video/x-flv)
Size:       132.19 MiB (138615628 Bytes)

[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=185414&courseId=4319
[DEBUG] get_content: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=185414&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&other=&v=1502374367587
[DEBUG] get_content: http://media1.icourses.cn:8080/process5/campus//ssl/host.shtml
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=7157314
[DEBUG] url_info: http://media2.icourses.cn/process5/campus/processres/flv/2012/12/12/ff808081-3b84e31f-013b-8d18b6bd-00a1.flv?h=zl3UzmtxQ3iAeTNAZgi-pA&start=0&lt=8-10%2F22%3A15%3A35&lv=150606-1&ls=play&p=151020&r=1502404770
Site:       icourses.cn
Title:      高分子化学 第二章 第2节 第二章缩聚和逐步聚合（2）
Type:       Flash video (video/x-flv)
Size:       149.95 MiB (157232510 Bytes)
```
