### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by cxy930123** [soimort/you-get#1567]
you-get --itag=18 --debug https://www.youtube.com/watch\?v\=_13wD21RZh8\&t\=417s\&list\=PLo7VCIm-1sdMOElNk0FtD8THTd4FInNTP\&index\=40
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=_13wD21RZh8
[DEBUG] get_content: https://www.youtube.com/watch?v=_13wD21RZh8
[DEBUG] get_content: https://s.ytimg.com/yts/jsbin/player-en_US-vflxP8f0T/base.js
site:                YouTube
title:               [大家一起学入门韩语]第2课 이것은 뭐예요?  这是什么？
stream:
    - itag:          18
      container:     mp4
      quality:       medium
      size:          77.0 MiB (80728998 bytes)
    # download-with: you-get --itag=18 [URL]

Downloading [大家一起学入门韩语]第2课 이것은 뭐예요?  这是什么？.mp4 ...
 0.0% (  0.0/ 77.0MB) ├───────────────────────────────────────────┤[1/1] you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=_13wD21RZh8&t=417s&list=PLo7VCIm-1sdMOElNk0FtD8THTd4FInNTP&index=40']
Traceback (most recent call last):
  File "/home/paul/.anaconda3/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/paul/.anaconda3/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/paul/.anaconda3/lib/python3.5/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/paul/.anaconda3/lib/python3.5/site-packages/you_get/common.py", line 1308, in script_main
    download_main(download, download_playlist, args, playlist, stream_id=stream_id, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/paul/.anaconda3/lib/python3.5/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/home/paul/.anaconda3/lib/python3.5/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/home/paul/.anaconda3/lib/python3.5/site-packages/you_get/extractor.py", line 52, in download_by_url
    self.download(**kwargs)
  File "/home/paul/.anaconda3/lib/python3.5/site-packages/you_get/extractor.py", line 208, in download
    av=stream_id in self.dash_streams)
  File "/home/paul/.anaconda3/lib/python3.5/site-packages/you_get/common.py", line 780, in download_urls
    url_save(url, output_filepath, bar, refer = refer, faker = faker, headers = headers)
  File "/home/paul/.anaconda3/lib/python3.5/site-packages/you_get/common.py", line 531, in url_save
    with open(temp_filepath, open_mode) as output:
OSError: [Errno 22] Invalid argument: './[大家一起学入门韩语]第2课 이것은 뭐예요?  这是什么？.mp4.download'

**Comment by cxy930123** [comment]
It works with `-i`, but I got an error while starting download

**Comment by j16180339887** [comment]
不需要加 -i 參數也能正常下載這個影片，

我想你應該是遇到檔名 Unicode 的問題

建立檔案 sitecustomize.py 應該可以解決這個問題

請參考
[https://github.com/soimort/you-get/wiki/FAQ](https://github.com/soimort/you-get/wiki/FAQ)
Q: 在 Windows mintty 遇到 UnicodeDecodeError

**Comment by cxy930123** [comment]
已经解决了，是因为下载之名的文件名存在非法字符串。
