### ISSUE TITLE
qq mv部分视频会解析失败

### ISSUE THREAD

**Issue by SymphonyNo9** [soimort/you-get#1570]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get --debug https://y.qq.com/portal/mv/v/s0017amxyfd.html
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['https://y.qq.com/portal/mv/v/s0017amxyfd.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.595', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/qq.py", line 106, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/qq.py", line 55, in qq_download_by_vid
    print_info(site_info, parts_ti, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 不是每个mv都会报这个错，部分会
> [舔 :icecream:!]

**Comment by bt4wang** [comment]
Error occured when I tried to download qq video too. 

C:\Users\bt4wa>you-get --debug https://v.qq.com/x/page/g0336lvafg4.html
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/page/g0336lvafg4.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1400, in main
  File "src\you_get\common.py", line 1313, in script_main
  File "src\you_get\common.py", line 1129, in download_main
  File "src\you_get\common.py", line 1393, in any_download
  File "src\you_get\extractors\qq.py", line 106, in qq_download
  File "src\you_get\extractors\qq.py", line 59, in qq_download_by_vid
NameError: name 'output_json' is not defined
you-get returned -1

**Comment by lki2019** [comment]
C:\Users\Administrator>you-get -di https://y.qq.com/portal/mv/v/s0017amxyfd.html

[DEBUG] get_content: https://y.qq.com/portal/mv/v/s0017amxyfd.html
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333
&platform=11&defnpayver=1&vid=s0017amxyfd
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format
=11309&vid=s0017amxyfd&filename=s0017amxyfd.p1309.1.mp4&appver=3.2.19.333
[DEBUG] url_info: http://1.31.173.151/music.qqvideo.tc.qq.com/A8m7CkwOV0R6Ky3LqW
e2mQUpyADHTYtx3Y1UB3INJZhE/s0017amxyfd.p1309.1.mp4?vkey=03F3DA953DA5420BD5FC87F9
FE848E2A232EB730C2C5460076A5CC9A05751416999480CB302F1301F8926728E31DC2BB67C44328
1CEFC25DD34C31ABF420603806902BFE6ED0DEA80740512A19A3316348340249CC32A7917EB54CFC
289F5AED
Site:       QQ.com
Title:      继续青春
Type:       MPEG-4 video (video/mp4)
Size:       75.9 MiB (79588128 Bytes)


C:\Users\Administrator>


目前已经可以正常解析下载  可以关闭啦
