### ISSUE TITLE
Apply to support huomao live platform

### ISSUE THREAD

**Issue by 872517414** [soimort/you-get#1573]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get --debug http://www.huomao.com/6657
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.huomao.com/6657']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1400, in main
  File "src\you_get\common.py", line 1313, in script_main
  File "src\you_get\common.py", line 1129, in download_main
  File "src\you_get\common.py", line 1392, in any_download
  File "src\you_get\common.py", line 1379, in url_to_module
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'you_get.extractors.huomaotv'
you-get returned -1
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> Huomao live platform is Perfect World company's game live platform.
Perfect World is Dota2 and CS:GO of the Chinese mainland agents.
> :icecream:!

**Comment by cnbeining** [comment]
Closed for not moving forward.

Please reopen if the issue persists in the latest develop branch.
