### ISSUE TITLE
优酷土豆视频解析失败

### ISSUE THREAD

**Issue by epirus** [soimort/you-get#1579]
```python
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.tudou.com/albumplay/s866liBTy6I/k01XIoUzDTY.html\\?spm\\=a2h1r.8267915.m1273.5\\~5!2\\~5\\~5\\~5\\~A']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/tudou.py", line 45, in tudou_download
    html = get_decoded_html(url)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 286, in get_decoded_html
    response = get_response(url, faker)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 269, in get_response
    response = request.urlopen(url)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```python

**Comment by internalG** [comment]
I tried le.com and pptv.com, all failed. It seems their structures change too often?

**Comment by Sausky** [comment]
请教一个问题，像优酷土豆有地域限制的片，访问原始地址都指向了第一集，看了下网络请求也不是跳转的，请问对方是怎么做到了？感谢！

**Comment by Sausky** [comment]
上面的地址我自己写的程序可以解析，但是http://v.youku.com/v_show/id_XMjI2NTg3Njc2.html?tpa=dW5pb25faWQ9MTAyNzM0XzEwMDAwMl8wMV8wMQ&refer=bdhz-bf这类优酷独播，现在走的是rtmp，有人能解决吗？

**Comment by epirus** [comment]
不好意思。我自己的地址写错了
