### ISSUE TITLE
腾讯视频下载不了张小龙的公开课

### ISSUE THREAD

**Issue by biggbuddy** [soimort/you-get#1583]
尝试了一下, 下载一些娱乐节目是没有问题, 只是速度很慢, 但想下载最新张小龙的公开演讲的时候, 发现下载不了.

```
$ you-get https://v.qq.com/x/cover/w8vjdt3mghb00vi/l002287iux4.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
```

加`-d`后的输出如下:

```
$ you-get -d https://v.qq.com/x/cover/w8vjdt3mghb00vi/l002287iux4.html
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/w8vjdt3mghb00vi/l002287iux4.html']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/extractors/qq.py", line 106, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/extractors/qq.py", line 55, in qq_download_by_vid
    print_info(site_info, parts_ti, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment
```

**Comment by soimort** [comment]
Duplicate of #1555.
