### ISSUE TITLE
腾讯视频解析不了

### ISSUE THREAD

**Issue by caoyufei** [soimort/you-get#1588]
root@vagrant-centos65 vagrant]# you-get --debug 'https://v.qq.com/x/cover/klrm086xib2l9cu/w0022f7p9gv.html'
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/klrm086xib2l9cu/w0022f7p9gv.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/qq.py", line 106, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/qq.py", line 55, in qq_download_by_vid
    print_info(site_info, parts_ti, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment
[root@vagrant-centos65 vagrant]#

**Comment by soimort** [comment]
Diuplicate of #1555.
