### ISSUE TITLE
建议：-p参数直接接播放器绝对地址

### ISSUE THREAD

**Issue by Justsoos** [soimort/you-get#1594]
目前使用you-get，将码流交给播放器和其他软件，使用-p参数是这样的：
you-get -p PotPlayerMini64 http://www.panda.tv/351560
you-get -p vlc http://www.panda.tv/351560

但问题在于，vlc，PotPlayerMini64 这些播放器参数，只能位于系统默认寻址path，很多用户都被这个挡在门槛外了。

建议能直接传送绝对播放器地址，比如这样
you-get -p "E:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe" http://www.panda.tv/351560
you-get -p "E:\Program Files\VideoLAN\VLC\vlc.exe" http://www.panda.tv/351560

目前实测无效，看debug是参数不认：

you-get --debug -p 'E:\Program Files\VideoLAN\VLC\vlc.exe' https://www.douyu.com/luguanfei
[DEBUG] get_content: https://www.google.com/search?tbm=vid&q=Files%5CVideoLAN%5CVLC%5Cvlc.exe%27
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ["Files\\VideoLAN\\VLC\\vlc.exe'", 'https://www.douyu.com/luguanfei']
Traceback (most recent call last):
  File "src\you_get\common.py", line 1366, in url_to_module
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib\request.py", line 1240, in do_open
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 1229, in connect
  File "http\client.py", line 826, in connect
  File "socket.py", line 707, in create_connection
  File "socket.py", line 698, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1400, in main
  File "src\you_get\common.py", line 1313, in script_main
  File "src\you_get\common.py", line 1129, in download_main
  File "src\you_get\common.py", line 1392, in any_download
  File "src\you_get\common.py", line 1368, in url_to_module
  File "src\you_get\common.py", line 1349, in google_search
  File "src\you_get\common.py", line 321, in get_content
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 465, in open
  File "urllib\request.py", line 483, in _open
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 1283, in https_open
  File "urllib\request.py", line 1242, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
you-get returned -1

**Comment by Justsoos** [comment]
@soimort-bot  sorry, my mistake, the url I tried that was online at last night. I have updated the debug output in the first post, and you can try other alive streams as test instead of.

**Comment by soimort** [comment]
Instead of

```
-p 'E:\Program Files\VideoLAN\VLC\vlc.exe' 
```

Try

```
-p "E:\Program Files\VideoLAN\VLC\vlc.exe" 
```

You should not use single quotes on WIndows cmd.

**Comment by Justsoos** [comment]
@soimort  问题就在这，you-get -p不能识别 “C:\Tools\mpv-x86_64-20161225\mpv.exe” 这样的参数，单引号也不行。看debug最后一行，文件找不到，这应该是参数接收出错。

 python you-get --debug -p "C:\Tools\mpv-x86_64-20161225\mpv.exe" https://www.douyu.com/gd008
[DEBUG] get_content: http://www.douyu.com/gd008
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=96291
Site:       douyu.com
Title:      东北大鹌鹑 宇宙第一寒冰 8点开播！
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['https://www.douyu.com/gd008']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "C:\Tools\you-get\you-get-develop/src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Tools\you-get\you-get-develop/src\you_get\common.py", line 1409, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "C:\Tools\you-get\you-get-develop/src\you_get\common.py", line 1322, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "C:\Tools\you-get\you-get-develop/src\you_get\common.py", line 1138, in download_main
    download(url, **kwargs)
  File "C:\Tools\you-get\you-get-develop/src\you_get\common.py", line 1402, in any_download
    m.download(url, **kwargs)
  File "C:\Tools\you-get\you-get-develop/src\you_get\extractors\douyutv.py", line 52, in douyutv_download
    download_url_ffmpeg(real_url, title, 'flv', None, output_dir = output_dir, merge = merge)
  File "C:\Tools\you-get\you-get-develop/src\you_get\common.py", line 966, in download_url_ffmpeg
    launch_player(player, [url])
  File "C:\Tools\you-get\you-get-develop/src\you_get\common.py", line 213, in launch_player
    subprocess.call(shlex.split(player) + list(urls))
  File "E:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "E:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "E:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by Justsoos** [comment]
我测过多次了，带引号的参数 -p  都无法正常运行。否则也不会来发issue了。
我用的win 10 1607。 
对于python 来说，这的确有点奇怪。

**Comment by soimort** [comment]
Windows下路径反斜杠需要转义。换成C:/Tools/mpv-x86_64-20161225/mpv.exe试试。

**Comment by Justsoos** [comment]
@soimort 好恶心，的确是windwos这个问题，测试用反斜杠可行了。多谢你回复

**Comment by fireattack** [comment]
@soimort 理论上用argument传参数，反斜杠没必要双写才对。是不是代码哪里有问题？

**Comment by fireattack** [comment]
稍微研究了下，好像是common.py里的210行：
```python
    subprocess.call(shlex.split(player) + list(urls))
```

导致的。

我知道`shlex.split()`是用来分割command line的，不过不知道为什么他会有删除单个反斜杠的副作用（毕竟POSIX下应该不用反斜杠才对…）。

不过在windows下这个分割没有必要，所以有几种处理方式：

1. 单独写个条件语句处理windows情况，类似：
```python
if sys.platform == 'win32':
    args = cmd
else:
    args = shlex.split(cmd)
```

2. 给`.call`加上`shell=True`参数，这样无论是*nix下还是windows下都没必要分割args了，也就不再需要`shlex.split()`了。

我之所以觉得这个处理有必要是因为，在windows的cmd和powershell下，一般反斜杠是不双写的；就如我上面所示，-O参数就不用双写。只有-p参数双写用起来非常奇怪，也不一致。
