### ISSUE TITLE
直接下载 flv 资源报503

### ISSUE THREAD

**Issue by liudanking** [soimort/you-get#1603]
```
 you-get --debug 'https://p9-play-vp.autohome.com.cn/flvs/0A33363922E51BDE/2016-12-26/93212C867FE9E881-30.flv'                                                             1 ↵
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['https://p9-play-vp.autohome.com.cn/flvs/0A33363922E51BDE/2016-12-26/93212C867FE9E881-30.flv']
Traceback (most recent call last):
  File "/Users/liudanking/code/github/you-get/src/you_get/extractors/universal.py", line 10, in universal_download
    content_type = get_head(url, headers=fake_headers)['Content-Type']
  File "/Users/liudanking/code/github/you-get/src/you_get/common.py", line 405, in get_head
    res = request.urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
```
开始以为服务器做了限制，但是直接使用`wget`可以下载。

**Comment by rosynirvana** [comment]
明白发生什么了
```
    if video_host.endswith('.com.cn') or video_host.endswith('.ac.cn'):
        video_host = video_host[:-3]
    domain = r1(r'(\.[^.]+\.[^.]+)$', video_host) or video_host
    assert domain, 'unsupported url: ' + url

    k = r1(r'([^.]+)', domain)
    if k in SITES:
        return import_module('.'.join(['you_get', 'extractors', SITES[k]])), url
    else:
        import http.client
        if url.startswith('https://'):
            conn = http.client.HTTPSConnection(video_host)
        else:
            conn = http.client.HTTPConnection(video_host)
```
```p9-play-vp.autohome.com.cn```是```.com.cn```结尾的，```video_host```的```.cn```被去掉了
