### ISSUE TITLE
Bilibili番剧无法下载[Develop Branch]

### ISSUE THREAD

**Issue by 872517414** [soimort/you-get#1604]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get --debug http://bangumi.bilibili.com/anime/5851/play#100291
[DEBUG] get_content: http://bangumi.bilibili.com/anime/5851/play#100291
[DEBUG] post_content: http://bangumi.bilibili.com/web_api/get_source
 post_data: {'episode_id': '100291'}
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/5851/play#100291']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.595', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1323, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1139, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/bilibili.py", line 133, in bilibili_download
    cid = json.loads(cont)['result']['cid']
KeyError: 'result'
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> 使用的为Develop Branch f72b34f

**Comment by 872517414** [comment]
用的海外机器
