### ISSUE TITLE
acfun  无法获取网页视频信息

### ISSUE THREAD

**Issue by fanxiao92** [soimort/you-get#1606]
```
you-get -di http://www.acfun.cn/v/ac3300867
[DEBUG] get_content: http://api.aixifan.com/plays/4572753
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519d032263f8&video_id=CODg1Mzc2OA==&embsig=1_1483879989_62967c3fa7e1b442ce995d3b3c9c9f53
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=CODg1Mzc2OA==&ct=85&sign=MXwxNDgzODgwMTE0fDc5NzYxZmE2Yzk2OTYwMTIxZDQzZDIyNzViZDNhMDQ1
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac3300867']
Traceback (most recent call last):
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.595', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/extractors/acfun.py", line 88, in acfun_download
    **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/extractors/acfun.py", line 55, in acfun_download_by_vid
    youku_open_download_by_vid(client_id='908a519d032263f8', vid=sourceId, title=title, output_dir=output_dir,merge=merge, info_only=info_only, embsig = embsig, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/extractors/youku.py", line 375, in open_download_by_vid
    self.prepare(api_url = api85_url, api12_url = api86_url, ctype = 86, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/extractors/youku.py", line 173, in prepare
    headers={'Referer': 'http://static.youku.com/'}
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/common.py", line 321, in get_content
    response = request.urlopen(req)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
```

**Comment by fanxiao92** [comment]
yes, u are right. 回看到nodename nor servname provided 猜想是DNS 果断换了 google的dns 记好了.唉
