### ISSUE TITLE
mgtv下载出错

### ISSUE THREAD

**Issue by bingzhangdai** [soimort/you-get#1608]
视频可以播放，you-get已经是最新的，下载出错。
感觉像是接口返回的json格式变了，所以有个变量就没有赋值？！
```
$ you-get --debug http://www.mgtv.com/b/44819/3178820.html
[DEBUG] get_content: http://v.api.mgtv.com/player/video?video_id=3178820
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.mgtv.com/b/44819/3178820.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/mgtv.py", line 85, in prepare
    for i in zip(stream_fileid_list, segment_list_this):
UnboundLocalError: local variable 'stream_fileid_list' referenced before assignment
```

**Comment by rosynirvana** [comment]
```
./you-get -di http://www.mgtv.com/b/44819/3178820.html
[DEBUG] get_content: http://pcweb.api.mgtv.com/player/video?video_id=3178820
[DEBUG] get_content: http://disp.titan.mgtv.com/vod.do?pm=WUpNOYIFzNoUT4AANtic4VCq6FiH2OO7fZCCVHLgs9YQjwHM447~SWi7PRaICZ8qPM4JeQaukxAT_JJis4ChNnVOPTV9OvNVKxt5DBGuDZb9YHezFBz7pk0eT_TmSLJPVvbd42NcxXKCz~QiuZuGrD2o0ILpiXCdaDROYp1YXyQ96uT6bNyxMZFAgQ1e8fzHFjBcQQt8_rowVdnojfHvfF~uKI0tfKPV&fid=F65697325E5595C08110DBD1F787E27E&gsid=644feecf-4a77-4a31-99cf-80c3b6c8992c
[DEBUG] get_content: http://202.109.167.168/c1/2017/06/15_0/8782E7D43D2697D11C783152F88308C2_20170615_1_1_1529_mp4/E5E0B1DA49EED79500C9C8008E21AC7F.m3u8?arange=0&pm=Nf5TsJTMw~eEfm1tpT041SJdQRa~HXhcJyIbgz1dg5RrnhgQxjKiNNZkqv3A~zsUAsYdVR0STjm33fX0z~KS2C41H48_h0Si50b33OYi8_I6_1ZcfwfN_lpyfwV_XfEO2PteDuf88wJNByqPZykgGLFOdTfb3Fe0wdYNs5oSsmpsQguQc2dKJYeREAdaCpYB3TQ7iGTAF0nhn8NCLl5i6NS7msoPlZlvm7Oif~avgitSFevEMaoAjKFs7nypS1lxPMrikyo4D8J_BYmpH3NSSdNN0CtdiyhJUauJEYlHB~5~94cfHjCJtQ4Gku07PsHojdvx47EHXAP7wKnJexSRjmhDp9Cs9D8Gfqg0dI~LeJwWArIMtHkRH3Mzkns62C779mWBzvjKjIc6W_4j
[DEBUG] get_content: http://disp.titan.mgtv.com/vod.do?pm=LLE2b9CtbpkcccPab6Lvfpqz8dthYB4hNonotqcvKVpeEAe5KG08DuoCGEyUlCMWiCOnjXtsBlL0kyuoX2Swtl8G~W_J4AIgylCk_D2xJIG3_yWYgdjoAPTZ9ibHmu5LQmEcJD7XlQgDAilLeRhM8B~LJdpwBEtsbORAVcU4VA6PUmeYcJF4z00z4z~vlhU3H7rml0fzOVi~vpchKWXXJk0q6KI-&fid=9DEF125DAA55C52A0FE8CED128183607&gsid=3ee6f187-03e5-481b-8698-40a8f7a426cb
[DEBUG] get_content: http://202.109.167.166/c1/2017/06/15_0/EC3B62BBC926C73B92802452271CDCBB_20170615_1_1_859_mp4/92A6DE5BBDE72A54567C0BFBFA74EF2C.m3u8?arange=0&pm=38oj1aIB~wA5Ma0KGBkDKDKC_uuDMBexYDyIgzYsv0rjHVMuH8osj9tFUQikJjDLPOJCUt2Y3wVL_2GEZEXqKdlrlUGuSWO0cGR3hW53KyoasjTIV5xVW4J_0d67amOwgHDgt8dKzXSSVf1lBXa3VysvZuVYknpmvk16ySG9ig5n5ulFKcn0OdNwXZgPu~s2Cp10nEZ6Y5YqmCT8F598IKV5sMvgQi7eSlBTELcsd6gtp3jMJtO60O6dLKW6UHCd42G8Qks07~dURshuEAYrs7TGSzzDYhyLMXSNbCTYF9Sl3EHUfW0a05yttV~2C~h3cERqw695li0IhTm~q7J_mewUWCVKc9RYHLFsLuZ0WTV7QdtrBxTy_X88A6K45uI0_xPKDdxx7ZgAnpQu
[DEBUG] get_content: http://disp.titan.mgtv.com/vod.do?pm=DLyco4shGK7RWAQ7DDHEHoD0QCGlgRG68cLJ50j7M2oU9Qpnd4_4HLBqP7jdzq2ZpwqnEImC2HyDLPbHlHowaOi8P2k3vBLrWulyUcBJAZYvKOp7VJrpj9v6HXxQhtdQDBLuIzF0m_vlGzM0yS6Cfsczwy_d1JLKJKCNzV7tmj5EjbZn9lQ5hKxZ6VuOLx90cD5~9p_KrmZFWDclc8sDMqWG8K8-&fid=AB7EB363260AABDE05078ACCD6C7A1A2&gsid=0a523b82-f635-4ea0-a383-f317c2288e15
[DEBUG] get_content: http://202.109.167.175/c1/2017/06/15_0/DAAAC3854579A9CF986F604FD9C34B1E_20170615_1_1_478_mp4/9C0EC6C6907ACC29BDAB309310919920.m3u8?arange=0&pm=XdyuWN2p8U~_~KEGur1qYWsc1gGEjEP1GOuk3uAcTatcm97rDjXuuvfEdWcRzYxFvw0BbRibneYIvvSp16ZzRwVyF_3~UvsqhsirgQfcAIhHcurizFjGx0yaWMHtxsbGXe8JSSih6Lwc09bdpCxOLPJvL7DxRGVPSfZrJv3~aAKWJXEgiNKs8T8OH9cSjnJAM2eC6qNse3HKOuirhP53X5WnPtNjcNJPNIx4gu9iQfrMMUD28YWJKMP7Mws_Uj4vUyXmiMY8ijOn4frgydEKsJGkx0biwmWW3zoJY~E_dXkzco1jPe00FFvokWCA_fJEmlnjpXVrqUyHDssWUy7UDHlq9CiPn7_~xmqOpN~XYmVoNjqdNi9fPpFllp2ArVzJfZa7qEuZxArSz8ta
site:                芒果 (MGTV)
title:               《我是歌手》第二季第五期高清版：张宇《迷迭香》
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd
      container:     ts
      video-profile: 超清
      size:          51.9 MiB (54414156 bytes)
      m3u8_url:      http://202.109.167.168/c1/2017/06/15_0/8782E7D43D2697D11C783152F88308C2_20170615_1_1_1529_mp4/E5E0B1DA49EED79500C9C8008E21AC7F.m3u8?arange=0&pm=Nf5TsJTMw~eEfm1tpT041SJdQRa~HXhcJyIbgz1dg5RrnhgQxjKiNNZkqv3A~zsUAsYdVR0STjm33fX0z~KS2C41H48_h0Si50b33OYi8_I6_1ZcfwfN_lpyfwV_XfEO2PteDuf88wJNByqPZykgGLFOdTfb3Fe0wdYNs5oSsmpsQguQc2dKJYeREAdaCpYB3TQ7iGTAF0nhn8NCLl5i6NS7msoPlZlvm7Oif~avgitSFevEMaoAjKFs7nypS1lxPMrikyo4D8J_BYmpH3NSSdNN0CtdiyhJUauJEYlHB~5~94cfHjCJtQ4Gku07PsHojdvx47EHXAP7wKnJexSRjmhDp9Cs9D8Gfqg0dI~LeJwWArIMtHkRH3Mzkns62C779mWBzvjKjIc6W_4j
    # download-with: you-get --format=hd [URL]

    - format:        sd
      container:     ts
      video-profile: 高清
      size:          29.4 MiB (30873924 bytes)
      m3u8_url:      http://202.109.167.166/c1/2017/06/15_0/EC3B62BBC926C73B92802452271CDCBB_20170615_1_1_859_mp4/92A6DE5BBDE72A54567C0BFBFA74EF2C.m3u8?arange=0&pm=38oj1aIB~wA5Ma0KGBkDKDKC_uuDMBexYDyIgzYsv0rjHVMuH8osj9tFUQikJjDLPOJCUt2Y3wVL_2GEZEXqKdlrlUGuSWO0cGR3hW53KyoasjTIV5xVW4J_0d67amOwgHDgt8dKzXSSVf1lBXa3VysvZuVYknpmvk16ySG9ig5n5ulFKcn0OdNwXZgPu~s2Cp10nEZ6Y5YqmCT8F598IKV5sMvgQi7eSlBTELcsd6gtp3jMJtO60O6dLKW6UHCd42G8Qks07~dURshuEAYrs7TGSzzDYhyLMXSNbCTYF9Sl3EHUfW0a05yttV~2C~h3cERqw695li0IhTm~q7J_mewUWCVKc9RYHLFsLuZ0WTV7QdtrBxTy_X88A6K45uI0_xPKDdxx7ZgAnpQu
    # download-with: you-get --format=sd [URL]

    - format:        ld
      container:     ts
      video-profile: 标清
      size:          16.6 MiB (17432676 bytes)
      m3u8_url:      http://202.109.167.175/c1/2017/06/15_0/DAAAC3854579A9CF986F604FD9C34B1E_20170615_1_1_478_mp4/9C0EC6C6907ACC29BDAB309310919920.m3u8?arange=0&pm=XdyuWN2p8U~_~KEGur1qYWsc1gGEjEP1GOuk3uAcTatcm97rDjXuuvfEdWcRzYxFvw0BbRibneYIvvSp16ZzRwVyF_3~UvsqhsirgQfcAIhHcurizFjGx0yaWMHtxsbGXe8JSSih6Lwc09bdpCxOLPJvL7DxRGVPSfZrJv3~aAKWJXEgiNKs8T8OH9cSjnJAM2eC6qNse3HKOuirhP53X5WnPtNjcNJPNIx4gu9iQfrMMUD28YWJKMP7Mws_Uj4vUyXmiMY8ijOn4frgydEKsJGkx0biwmWW3zoJY~E_dXkzco1jPe00FFvokWCA_fJEmlnjpXVrqUyHDssWUy7UDHlq9CiPn7_~xmqOpN~XYmVoNjqdNi9fPpFllp2ArVzJfZa7qEuZxArSz8ta
    # download-with: you-get --format=ld [URL]
```
