### ISSUE TITLE
爱奇艺不能下载视频

### ISSUE THREAD

**Issue by jacksimjia** [soimort/you-get#1610]
```
you-get --debug -o ~/Desktop/download/ http://www.iqiyi.com/v_19rr9uchhg.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/588026600/7b89ac0b658b5ebf70c2843f37c622c4/?t=1483942013631&sc=9a4b6807b2e13bc6f757d7bfaa7a6610&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               无间道第6集
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rr9uchhg.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.595', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/extractor.py", line 52, in download_by_url
    self.download(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/extractors/iqiyi.py", line 204, in download
    merge=kwargs['merge'],)
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/common.py", line 970, in download_url_ffmpeg
    assert has_ffmpeg_installed(), "FFmpeg not installed."
AssertionError: FFmpeg not installed.
```

**Comment by mengmo** [comment]
@jacksimjia 
看你log的最后
```
  File "/usr/local/Cellar/you-get/0.4.595_1/libexec/lib/python3.6/site-packages/you_get/common.py", line 970, in download_url_ffmpeg
    assert has_ffmpeg_installed(), "FFmpeg not installed."
AssertionError: FFmpeg not installed.
```
你的 ffmpeg 没装好
