### ISSUE TITLE
pptv的视频下载不了

### ISSUE THREAD

**Issue by JrSider** [soimort/you-get#1611]
MacBook-Pro-2:~ liuside$ you-get http://v.pptv.com/show/X8uyMZnicb60QjvY.html?rcc_src=L1
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
MacBook-Pro-2:~ liuside$ you-get -V
you-get: version 0.4.595, a tiny downloader that scrapes the web.
MacBook-Pro-2:~ liuside$

**Comment by JrSider** [comment]
debug之后
MacBook-Pro-2:~ liuside$ you-get --debug http://v.pptv.com/show/X8uyMZnicb60QjvY.html?rcc_src=L1
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://v.pptv.com/show/X8uyMZnicb60QjvY.html?rcc_src=L1']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/extractors/pptv.py", line 144, in pptv_download
    assert re.match(r'http://v.pptv.com/show/(\w+)\.html$', url)
AssertionError

**Comment by redstoneleo** [comment]
其实这里已经修复了 https://github.com/soimort/you-get/pull/1577/commits/e358e33241827977149d71ab21ef902baf94f75d

**Comment by soimort** [comment]
Closed via #2025.
