### ISSUE TITLE
pandatv 熊猫直播流加了认证，大主播的房间extractors基本上都失效了

### ISSUE THREAD

**Issue by Justsoos** [soimort/you-get#1612]
pandatv 熊猫直播流加了认证，大主播的房间基本上都失效了。但某些24小时播出的房间，特别（未知原因）房间，还可以用，比如这个： `http://www.panda.tv/491124` 

下面是失败信息（**注意，这个房间可能测试时下播了**），注意，最后一行 HTTP Error 403: Forbidden：

you-get --debug http://www.panda.tv/888888
Site:       panda.tv
Title:      JY:下午lol晚上狼人杀！
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Traceback (most recent call last):
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 762, in download_urls
    total_size = urls_size(urls, faker=faker, headers=headers)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 401, in urls_size
    return sum([url_size(url, faker=faker, headers=headers) for url in urls])
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 401, in <listcomp>
    return sum([url_size(url, faker=faker, headers=headers) for url in urls])
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 395, in url_size
    response = request.urlopen(url)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
Downloading JY-下午lol晚上狼人杀！.flv ...
     %[========================================] 1/1you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.panda.tv/888888']
Traceback (most recent call last):
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.595', 'console_scripts', 'you-get')()
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\__main__.py", line 92, in main
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 1414, in main
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 1327, in script_main
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 1143, in download_main
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 1407, in any_download
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\extractors\panda.py", line 30, in panda_download
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 785, in download_urls
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 477, in url_save
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 395, in url_size
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by Justsoos** [comment]
对于这些房间， you-get -p PLAYER 也失效了，播放器返回错误都是 403 Forbidden。估计要像douyutv 的extractor 那样重写模板了。

**Comment by Justsoos** [comment]
@soimort  你的机器人还挺好玩的。哈哈。
you-get  -di 都没问题，但url 取出来是必须带token 和有效期的，-p 和下载都失效了。
这是最近熊猫 “逐渐” 改出来的新玩意儿，和斗鱼非常类似。（王公子除了抄袭真没啥内容）

**Comment by zhangn1985** [comment]
这个并不难～～

**Comment by Erk-** [comment]
I have made a fix that tries the backup servers if the main server returns 403.

**Comment by Justsoos** [comment]
@Erk- 我没看错吧，熊猫的程序员们在忽悠老板！ 根本没加上防盗链的token啊，哈哈哈，
只是服务器 由 pl8.live.panda.tv 变成了pl4.live.panda.tv，目前形如这样的URL 就能多次打开：
http://pl4.live.panda.tv/live_panda/d8bad1ee3e3556ae04c288e3203c4770.flv

**Comment by Erk-** [comment]
Sorry I do not understand Chinese. but I think the pl must be something about what server that they have the stream on. Because mobile streams usually use the pl21, but still have the 4 as a backup it usually works but not always.
