### ISSUE TITLE
爱奇艺出现这样的,无法下载

### ISSUE THREAD

**Issue by qwer123789** [soimort/you-get#1614]
E:\you-get>you-get -c cookies.sqlite --format=LD --debug "http://www.iqiyi.com/v_19rr9uc794.html"
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/588031700/4f33df8709d68f0d3919608ebe35fe6e/?t=1484115597659&sc=9c685aafcc91d8d437e45f7175b4bf1c&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rr9uc794.html']
Traceback (most recent call last):
  File "d:\program files (x86)\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files (x86)\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (x86)\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files (x86)\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 1256, in script_main
    download_main(download, download_playlist, args, playlist, stream_id=stream_id, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 1077, in download_main
    download(url, **kwargs)
  File "d:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "d:\program files (x86)\python35-32\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "d:\program files (x86)\python35-32\lib\site-packages\you_get\extractors\iqiyi.py", line 140, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video

E:\you-get>pause
请按任意键继续. . .

**Comment by rosynirvana** [comment]
```
you-get -di 'http://www.iqiyi.com/v_19rr9uc794.html'
[DEBUG] get_html: http://www.iqiyi.com/v_19rr9uc794.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rr9uc794.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/588031700/4f33df8709d68f0d3919608ebe35fe6e/?t=1493015419278&sc=249ac4e234fba1b676022d71d90c7e14&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               无间道第9集
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: you-get --format=LD [URL]
```
看来接口整合了，现在可以拿到了
