### ISSUE TITLE
[Soundcloud] HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by diegogslomp** [soimort/you-get#1616]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['https://soundcloud.com/john00fleming/john-00-fleming-global-trance-grooves-166-guest-jerome-isma-ae']
Traceback (most recent call last):
  File "/home/diego/Documents/projects/python/you-get/env/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/diego/Documents/projects/python/you-get/env/lib/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/diego/Documents/projects/python/you-get/env/lib/python3.4/site-packages/you_get/common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/diego/Documents/projects/python/you-get/env/lib/python3.4/site-packages/you_get/common.py", line 1323, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/diego/Documents/projects/python/you-get/env/lib/python3.4/site-packages/you_get/common.py", line 1139, in download_main
    download(url, **kwargs)
  File "/home/diego/Documents/projects/python/you-get/env/lib/python3.4/site-packages/you_get/common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "/home/diego/Documents/projects/python/you-get/env/lib/python3.4/site-packages/you_get/extractors/soundcloud.py", line 21, in soundcloud_download
    metadata = get_html('https://api.soundcloud.com/resolve.json?url=' + url + '&client_id=02gUJC0hH2ct1EGOcYXQIzRFU91c72Ea')
  File "/home/diego/Documents/projects/python/you-get/env/lib/python3.4/site-packages/you_get/common.py", line 282, in get_html
    content = get_response(url, faker).data
  File "/home/diego/Documents/projects/python/you-get/env/lib/python3.4/site-packages/you_get/common.py", line 270, in get_response
    response = request.urlopen(url)
  File "/home/diego/.pyenv/versions/3.4.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/home/diego/.pyenv/versions/3.4.4/lib/python3.4/urllib/request.py", line 470, in open
    response = meth(req, response)
  File "/home/diego/.pyenv/versions/3.4.4/lib/python3.4/urllib/request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/diego/.pyenv/versions/3.4.4/lib/python3.4/urllib/request.py", line 508, in error
    return self._call_chain(*args)
  File "/home/diego/.pyenv/versions/3.4.4/lib/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/home/diego/.pyenv/versions/3.4.4/lib/python3.4/urllib/request.py", line 588, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> :icecream:

**Comment by diegogslomp** [comment]
Maybe there is something wrong with the `client_id` like in a previous issue #679. Any ideas?

**Comment by rosynirvana** [comment]
```
./you-get -di https://soundcloud.com/john00fleming/john-00-fleming-global-trance-grooves-166-guest-jerome-isma-ae
[DEBUG] get_content: https://api.soundcloud.com/resolve.json?url=http://soundcloud.com/john00fleming/john-00-fleming-global-trance-grooves-166-guest-jerome-isma-ae&client_id=JlZIsxg2hY5WnBgtn3jfS0UYCl0K8DOg
[DEBUG] url_info: https://api.soundcloud.com/tracks/301927090/download?client_id=JlZIsxg2hY5WnBgtn3jfS0UYCl0K8DOg
Site:       SoundCloud.com
Title:      John 00 Fleming - Global Trance Grooves 166 (+ Guest Jerome Isma-Ae)
Type:       MP3 (audio/mpeg)
Size:       274.95 MiB (288307114 Bytes)
```

**Comment by Ivorforce** [comment]
I'm on you-get-0.4.803

```
❯ you-get -di https://soundcloud.com/john00fleming/john-00-fleming-global-trance-grooves-166-guest-jerome-isma-ae
[DEBUG] get_response: https://api.soundcloud.com/resolve.json?url=http://soundcloud.com/john00fleming/john-00-fleming-global-trance-grooves-166-guest-jerome-isma-ae&client_id=02gUJC0hH2ct1EGOcYXQIzRFU91c72Ea
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://soundcloud.com/john00fleming/john-00-fleming-global-trance-grooves-166-guest-jerome-isma-ae']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1181, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/soundcloud.py", line 21, in soundcloud_download
    metadata = get_html('https://api.soundcloud.com/resolve.json?url=' + url + '&client_id=02gUJC0hH2ct1EGOcYXQIzRFU91c72Ea')
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 306, in get_html
    content = get_response(url, faker).data
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 294, in get_response
    response = request.urlopen(url)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

```
