### ISSUE TITLE
you-get -p some error

### ISSUE THREAD

**Issue by coderwangyu** [soimort/you-get#1622]
you-get --debug -p Chrome 'https://www.bilibili.com/video/av1198584'
==>FileNotFoundError: [Errno 2] No such file or directory: 'Chrome'
you-get --debug -p /Applications/Google\ Chrome.app 'https://www.bilibili.com/video/av1198584'
**The command line with the blank space,run with error** 
==>FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Google'
???How should I deal with this problem???

you-get --debug -p "/Applications/Google\ Chrome.app" 'https://www.bilibili.com/video/av6776510/'
[DEBUG] get_content: http://www.bilibili.com/video/av6776510/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=11035698&from=miniplay&player=1&sign=89afbf37c2c3261687e5a6a57cac1306
Site:       bilibili.com
Title:      筱陌路在美国的LOL游戏养成 Part5
Type:       Flash video (video/x-flv)
Size:       739.76 MiB (775697323 Bytes)

you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['https://www.bilibili.com/video/av6776510/']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1323, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1139, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 177, in bilibili_download
    info_only=info_only)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 104, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 753, in download_urls
    launch_player(player, urls)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 214, in launch_player
    subprocess.call(shlex.split(player) + list(urls))
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
**## PermissionError: [Errno 13] Permission denied**

now i use firefox 
you-get --debug -p /Applications/Firefox.app 'https://www.bilibili.com/video/av1198584'
there has a other error 
**PermissionError: [Errno 13] Permission denied**

???How should I deal with this problem ???

so i have some question about  the command of parameter -p

**Comment by soimort** [comment]
`-p` should be used with the actual executable, while `Google Chrome.app` is just a bundle name.

**Comment by Erk-** [comment]
does `you-get --debug -p "open /Applications/Google\ Chrome.app"` work
