### ISSUE TITLE
無法下載優酷頻道會員視頻 http.cookiejar bug

### ISSUE THREAD

**Issue by scegg** [soimort/you-get#1627]
Allens-Mac-Pro:Downloads Allen$ you-get -c cookies.txt -d http://v.youku.com/v_show/id_XMTYyMzQ5MDYwMA==.html?from=zpdvip.001
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/cookiejar.py:2061: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/cookiejar.py", line 2034, in _really_load
    assert domain_specified == initial_dot
AssertionError

  _warn_unhandled_exception()
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTYyMzQ5MDYwMA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTYyMzQ5MDYwMA==&ct=12
site:                优酷 (Youku)
title:               腾飞五千年之悠悠两汉 01
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          137.8 MiB (144485555 bytes)
    # download-with: you-get --format=mp4 [URL]

you-get: [Failed] Cannot extract video source.

cookies.txt為Netscape格式。本機視頻瀏覽器中可正常播放。視頻為頻道會員視頻。

**Comment by scegg** [comment]
cookies.txt中包含幾十條記錄。
除了少數為".v.youku.com" "v.youku.com"，絕大多數為  ".youku.com" 。記錄不包含引號。

**Comment by scegg** [comment]
刷新幾次后，提示信息變為：

Allens-Mac-Pro:Downloads Allen$ you-get -c cookies.txt -d http://v.youku.com/v_show/id_XMTYyMzQ5MDYwMA==.html?from=zpdvip.001
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/cookiejar.py:2061: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/cookiejar.py", line 2034, in _really_load
    assert domain_specified == initial_dot
AssertionError

  _warn_unhandled_exception()
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTYyMzQ5MDYwMA==&ct=10
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTYyMzQ5MDYwMA==.html?from=zpdvip.001']
Traceback (most recent call last):
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.626', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1323, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1139, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/extractors/youku.py", line 173, in prepare
    headers={'Referer': 'http://static.youku.com/'}
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 322, in get_content
    response = request.urlopen(req)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

**Comment by cnbeining** [comment]
优酷抽风。

urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

这句话才是重点：优酷抽风了。

**Comment by scegg** [comment]
换了一台Windows，错误如下：

>you-get -d -c cookies.txt http://v.youku.com/v_show/id_XMTYyMzQ5MDYwMA==.html?spm=0.0.video_list.5~5!8~5!2~A.eX5i91&from=zpdvip.001
C:\Users\Allen\AppData\Local\Temp\_MEI39962\http\cookiejar.py:2058: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "http\cookiejar.py", line 2031, in _really_load
AssertionError

[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTYyMzQ5MDYwMA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTYyMzQ5MDYwMA==&ct=12
site:                优酷 (Youku)
title:               腾飞五千年之悠悠两汉 01
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          137.8 MiB (144485555 bytes)
    # download-with: you-get --format=mp4 [URL]

you-get: [Failed] Cannot extract video source.
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTYyMzQ5MDYwMA==.html?spm=0.0.video_list.5~5!8~5!2~A.eX5i91']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1410, in main
  File "src\you_get\common.py", line 1323, in script_main
  File "src\you_get\common.py", line 1139, in download_main
  File "src\you_get\common.py", line 1403, in any_download
  File "src\you_get\extractor.py", line 52, in download_by_url
  File "src\you_get\extractor.py", line 203, in download
  File "src\you_get\util\log.py", line 98, in wtf
NameError: name 'exit' is not defined
you-get returned -1
'from' is not recognized as an internal or external command,
operable program or batch file.

**Comment by v1-hermit** [comment]
就你错误这么多，左一个右一个

**Comment by scegg** [comment]
嗯 那就关闭这个问题吧 已经用youtube dl下好了
