### ISSUE TITLE
acfun 视频下载异常

### ISSUE THREAD

**Issue by bobonovski** [soimort/you-get#1629]
```
- [-] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [-] Your `you-get` is up-to-date.
- [-] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [-] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [-] The issue (or question) is really about `you-get`, not about some other code or project.
```
最近下载 acfun 的视频时老是会遇到下面的错误：
```
you-get --debug -u http://www.acfun.cn/v/ac2572739
[DEBUG] get_content: http://api.aixifan.com/plays/3240809
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519d032263f8&video_id=CMjY2MDMxMg==&embsig=1_1484806995_bb43b8b4fbe47bf3e8bcba9963f51247
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=CMjY2MDMxMg==&ct=85&sign=MXwxNDg0ODA2OTk1fGQ4NTRjOWEyNDJjYjg3MDFmNTNjYzQ0NTgzNGNiMWY5
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac2572739']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1323, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1139, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/acfun.py", line 88, in acfun_download
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/acfun.py", line 55, in acfun_download_by_vid
    youku_open_download_by_vid(client_id='908a519d032263f8', vid=sourceId, title=title, output_dir=output_dir,merge=merge, info_only=info_only, embsig = embsig, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/youku.py", line 375, in open_download_by_vid
    self.prepare(api_url = api85_url, api12_url = api86_url, ctype = 86, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/youku.py", line 173, in prepare
    headers={'Referer': 'http://static.youku.com/'}
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by soimort** [comment]
Closed via #2010.
