### ISSUE TITLE
Youku video downloads always terminate at same position

### ISSUE THREAD

**Issue by dklunarian** [soimort/you-get#1631]
you-get -d -o i:/tmp/ "http://v.youku.com/v_show/id_XMjQ3NTgwOTE4OA==.html"
...
6.8% ( 126.9/1855.1MB) ├███──────────────────────────────────┤[ 3/49]  955 kB/s
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjQ3NTgwOTE4OA==.html']
Traceback (most recent call last):
  File "urllib\request.py", line 1240, in do_open
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 826, in connect
  File "socket.py", line 707, in create_connection
  File "socket.py", line 698, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1410, in main
  File "src\you_get\common.py", line 1323, in script_main
  File "src\you_get\common.py", line 1139, in download_main
  File "src\you_get\common.py", line 1403, in any_download
  File "src\you_get\extractor.py", line 52, in download_by_url
  File "src\you_get\extractor.py", line 208, in download
  File "src\you_get\common.py", line 793, in download_urls
  File "src\you_get\common.py", line 473, in url_save
  File "src\you_get\common.py", line 391, in url_size
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 465, in open
  File "urllib\request.py", line 483, in _open
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 1268, in http_open
  File "urllib\request.py", line 1242, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试 失败。>
you-get returned -1

**Comment by dklunarian** [comment]
seems a windows related issue, did everything same on CentOS and it worked

**Comment by dklunarian** [comment]
btw, I didn't use any proxies on Windows
