### ISSUE TITLE
you-get download fail

### ISSUE THREAD

**Issue by LOVEChen** [soimort/you-get#1632]
### brew update -y
Already up-to-date.

### you-get --v
you-get: version 0.4.626, a tiny downloader that scrapes the web.

### you-get --debug http://music.163.com/#/album/34468010
[DEBUG] get_content: http://music.163.com/api/album/34468010?id=34468010&csrf_token=
Skipping ./Rihanna - ANTi/cover.jpg: file already exists

Site:       163.com
Title:      1. Consideration
Type:       MP3 (audio/mpeg)
Size:       6.15 MiB (6444973 Bytes)

Skipping ./Rihanna - ANTi/1. Consideration.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=401712010&lv=-1&csrf_token=
Saving 1. Consideration.lrc ...Done.
Site:       163.com
Title:      2. James Joint
Type:       MP3 (audio/mpeg)
Size:       2.75 MiB (2886051 Bytes)

Skipping ./Rihanna - ANTi/2. James Joint.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=401712011&lv=-1&csrf_token=
Saving 2. James Joint.lrc ...Done.
Site:       163.com
Title:      3. Kiss It Better
Type:       MP3 (audio/mpeg)
Size:       9.66 MiB (10126149 Bytes)

Skipping ./Rihanna - ANTi/3. Kiss It Better.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=401712012&lv=-1&csrf_token=
Saving 3. Kiss It Better.lrc ...Done.
Site:       163.com
Title:      4. Work
Type:       MP3 (audio/mpeg)
Size:       8.37 MiB (8775096 Bytes)

Skipping ./Rihanna - ANTi/4. Work.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=401712013&lv=-1&csrf_token=
Saving 4. Work.lrc ...Done.
Site:       163.com
Title:      5. Desperado
Type:       MP3 (audio/mpeg)
Size:       7.12 MiB (7461659 Bytes)

Skipping ./Rihanna - ANTi/5. Desperado.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=401712014&lv=-1&csrf_token=
Saving 5. Desperado.lrc ...Done.
Site:       163.com
Title:      6. Woo
Type:       MP3 (audio/mpeg)
Size:       8.99 MiB (9426067 Bytes)

Skipping ./Rihanna - ANTi/6. Woo.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=401712015&lv=-1&csrf_token=
Saving 6. Woo.lrc ...Done.
Site:       163.com
Title:      7. Needed Me
Type:       MP3 (audio/mpeg)
Size:       7.31 MiB (7666459 Bytes)

Skipping ./Rihanna - ANTi/7. Needed Me.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=401712016&lv=-1&csrf_token=
Saving 7. Needed Me.lrc ...Done.
Site:       163.com
Title:      8. Yeah, I Said It
Type:       MP3 (audio/mpeg)
Size:       5.08 MiB (5325888 Bytes)

Skipping ./Rihanna - ANTi/8. Yeah, I Said It.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=401712017&lv=-1&csrf_token=
Saving 8. Yeah, I Said It.lrc ...Done.
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/album/34468010']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.626', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1323, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1139, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/extractors/netease.py", line 133, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/extractors/netease.py", line 41, in netease_cloud_music_download
    netease_song_download(i, output_dir=new_dir, info_only=info_only)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/extractors/netease.py", line 120, in netease_song_download
    output_dir=output_dir, info_only=info_only)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/extractors/netease.py", line 123, in netease_download_common
    songtype, ext, size = url_info(url_best)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 414, in url_info
    response = request.urlopen(request.Request(url))
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by LOVEChen** [comment]
this album have 16 songs , you have only downloaded eight , the last 8 songs can't download because failed , please , check it again. thx

**Comment by LOVEChen** [comment]
1
Consideration
02:41	
Rihanna/SZA
 2
James Joint
01:12	
Rihanna
 3
Kiss It BetterMV
04:13	
Rihanna
 4
WorkMV
03:39	
Rihanna/Drake
 5
Desperado
03:06	
Rihanna
 6
Woo
03:55	
Rihanna
 7
Needed MeMV
03:11	
Rihanna
 8
Yeah, I Said It
02:13	
Rihanna
 9
Same Ol’ Mistakes
06:37	
Rihanna
 10
Never Ending
03:22	
Rihanna
 11
Love On The Brain
03:44	
Rihanna
 12
Higher
02:00	
Rihanna
 13
Close To You
03:57	
Rihanna
 14
Goodnight GothamMV
01:28	
Rihanna
 15
Pose
02:24	
Rihanna
 16
Sex With Me
Rihanna
