### ISSUE TITLE
Can anyone confirm if you-get supports TW Iqiyi（愛奇藝臺灣）?

### ISSUE THREAD

**Issue by NiGHTsC** [soimort/you-get#1634]
I'm getting this error while trying to download the video with you-get
no problem watching it via Firefox v50.1.0

```
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ["'http://tw.iqiyi.com/v_19rr9l4e18.html'"]
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1410, in main
  File "src\you_get\common.py", line 1323, in script_main
  File "src\you_get\common.py", line 1139, in download_main
  File "src\you_get\common.py", line 1402, in any_download
  File "src\you_get\common.py", line 1393, in url_to_module
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 826, in connect
  File "socket.py", line 689, in create_connection
  File "socket.py", line 728, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed
you-get returned -1
```

Thank you.

**Comment by cnbeining** [comment]
>socket.gaierror: [Errno 11004] getaddrinfo failed

Please kindly check your Internet connection.

**Comment by NiGHTsC** [comment]
Thanx, 
but please look at this, is it really downloading?
> frame=  409 fps=0.3 q=-1.0 size=    1867kB time=26:28:00.15 bitrate=   0.2kbits/
frame=  409 fps=0.3 q=-1.0 size=    1867kB time=26:28:00.15 bitrate=   0.2kbits/
frame=  409 fps=0.3 q=-1.0 size=    1867kB time=26:28:00.15 bitrate=   0.2kbits/
frame=  409 fps=0.3 q=-1.0 size=    1867kB time=26:28:00.15 bitrate=   0.2kbits/
frame=  409 fps=0.3 q=-1.0 size=    1867kB time=26:28:00.15 bitrate=   0.2kbits/
frame=  409 fps=0.3 q=-1.0 size=    1867kB time=26:28:00.15 bitrate=   0.2kbits/
s speed=  75x

**Comment by cnbeining** [comment]
Could be the CDN messing up.

2017年1月20日 下午5:26，"NiGHTsC" <notifications@github.com>写道：

**Comment by NiGHTsC** [comment]
My bad, just edited my last post.

However, I don't think the video would be watch-able after download, keep getting this kind of errors while downloading

````
[mp4 @ 002d9460] Non-monotonous DTS in output stream 0:0; previous: 16220765, current: 9954000; changing to 16220766. This may result in incorrect timestamps in the output file.
[mp4 @ 002d9460] Non-monotonous DTS in output stream 0:1; previous: 7948622, current: 4878336; changing to 7948623. This may result in incorrect timestamps in the output file.
[mp4 @ 002d9460] Non-monotonous DTS in output stream 0:1; previous: 7948623, current: 4880384; changing to 7948624. This may result in incorrect timestamps in the output file.
[mp4 @ 002d9460] Non-monotonous DTS in output stream 0:0; previous: 16220766, current: 9957600; changing to 16220767. This may result in incorrect timestamps in the output file.
[mp4 @ 002d9460] Non-monotonous DTS in output stream 0:0; previous: 16220767, current: 9961200; changing to 16220768. This may result in incorrect timestamps in the output file.
[mp4 @ 002d9460] Non-monotonous DTS in output stream 0:1; previous: 7948624, current: 4882432; changing to 7948625. This may result in incorrect timestamps in the output file.
[mp4 @ 002d9460] Non-monotonous DTS in output stream 0:1; previous: 7948625, current: 4884480; changing to 7948626. This may result in incorrect timestamps in the output file.
````

**Comment by cnbeining** [comment]
This should not affect so much: it's only timestamps.

2017年1月20日 下午5:46，"NiGHTsC" <notifications@github.com>写道：

**Comment by NiGHTsC** [comment]
nah, can't get it, always 3mins loop.

I tried it with livestreamer with the realurl as **@lzy0699** mentioned before(hsl://realurl), but still 3mins only...

**Comment by lzy0699** [comment]
try:
ffmpeg -i yourvideofile.mp4 -c:v copy -c:a copy out.mkv

**Comment by NiGHTsC** [comment]
I believe it's they problem with you-get/livestreamer, they just can't read the file from TW Iqiyi.

@lzy0699: you can still output Iqiyi video with livestreamer?

**Comment by redstoneleo** [comment]
@lzy0699 simplified version  of your command 
ffmpeg -i yourvideofile.ts -c copy out.mkv

**Comment by redstoneleo** [comment]
@NiGHTsC  try
ffmpeg -i m3u8Url.m3u8 -c copy out.mkv

**Comment by NiGHTsC** [comment]
shouldn't I use livestreamer to download the video first? cause I couldn't even download the full video, only first 3mins.

**Comment by Justsoos** [comment]
貌似you-get 对爱奇艺的 tw 子域名不支持吧，我这里运行出错。还没空看怎么回事

**Comment by Justsoos** [comment]
楼主你应该发一个 debug 命令结果，让 @soimort  的机器人 @soimort-bot 在米国用高级带宽给你测一下。

**Comment by cnbeining** [comment]
@soimort-bot Can you kindly try this link for us? http://tw.iqiyi.com/v_19rr9l4e18.html

**Comment by cnbeining** [comment]
好吧这个link有地区限制。

有别的什么example么？

**Comment by NiGHTsC** [comment]
是有版權地區限制，我是用VPN看的

這個沒有限制，應該可以試試
http://tw.iqiyi.com/v_19rrl4dv9g.html

**Comment by Justsoos** [comment]
@soimort-bot Can you kindly try this link for us? http://tw.iqiyi.com/v_19rrl4dv9g.html

**Comment by Justsoos** [comment]
haha， 机器人自相矛盾了。

**Comment by NiGHTsC** [comment]
真的是m3u8的問題？我不懂了，哈！

**Comment by lzy0699** [comment]
http://tw.iqiyi.com/v_19rrl4dv9g.html
我用realURL在livestreamer里面可以正常下载，我只测试下在200M，直接下下来TS文件可以直接播放，但是视频播放到最后会有点问题，文件信息如下：

> General
> ID                             : 1 (0x1)
> Complete name                  : X:\Downloads\2016臺北跨年演唱會20160115期.ts
> Format                         : MPEG-TS
> File size                      : 205 MiB
> Duration                       : 13mn 38s
> Overall bit rate mode          : Variable
> Overall bit rate               : 2 079 Kbps
> 
测试用我的ffmpeg无法重新封装此视频，估计可能ffmpeg最新版可以。用mmg封装为mkv以后一切正常，视频文件信息如下：

> General
> Unique ID                      : 217217234492355532361847735060217668738 (0xA36A8483B32D4CFB97209FD20B6F2482)
> Complete name                  : X:\Downloads\2016臺北跨年演唱會20160115期.mkv
> Format                         : Matroska
> Format version                 : Version 4 / Version 2
> File size                      : 198 MiB
> Duration                       : 13mn 48s
> Overall bit rate               : 2 004 Kbps
> Encoded date                   : UTC 2017-02-22 00:45:08
> Writing application            : mkvmerge v7.2.0 ('On Every Street') 32bit built on Sep 13 2014 15:42:11
> Writing library                : libebml v1.3.0 + libmatroska v1.4.1

PS:这个视频清晰度不高嘛。。。。。

**Comment by NiGHTsC** [comment]
@lzy0699 :請問下您livestreamer的下載指令是什麼？
我只能下載前三分鐘，和使用you-get同樣的問題

**Comment by lzy0699** [comment]
`livestreamer.exe "hls://realURL" best -o "x:\downloads\video.ts"`

反正下好以后记得用ffmpeg或者mmg之类的工具重新封装一下
@NiGHTsC

**Comment by lki2019** [comment]
http://tw.iqiyi.com/v_19rrl4dv9g.html you-get目前是支持的

http://tw.iqiyi.com/v_19rr9l4e18.html 版权问题 是不支持的
