### ISSUE TITLE
youtube download video gets ssl error

### ISSUE THREAD

**Issue by yxliang01** [soimort/you-get#1643]
The debug output is below. My system time and date are fine and I believe I am not hijacked 🤣 . Can use browser to access youtube.com without any issue (i.e. no warning). Comments in 廣東話, 普通话 and English are welcome. Thanks.

```
Traceback (most recent call last):
  File "c:\programdata\chocolatey\lib\python3\tools\lib\urllib\request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\http\client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\http\client.py", line 911, in _send_output
    self.send(msg)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\http\client.py", line 854, in send
    self.connect()
  File "c:\programdata\chocolatey\lib\python3\tools\lib\http\client.py", line 1237, in connect
    server_hostname=server_hostname)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\ssl.py", line 376, in wrap_socket
    _context=self)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\ssl.py", line 747, in __init__
    self.do_handshake()
  File "c:\programdata\chocolatey\lib\python3\tools\lib\ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "c:\programdata\chocolatey\lib\python3\tools\lib\ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\chocolatey\lib\python3\tools\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\chocolatey\lib\python3\tools\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\programdata\chocolatey\lib\python3\tools\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\site-packages\you_get\common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\site-packages\you_get\common.py", line 1323, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\site-packages\you_get\common.py", line 1139, in download_main
    download(url, **kwargs)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\site-packages\you_get\common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\site-packages\you_get\extractors\youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "c:\programdata\chocolatey\lib\python3\tools\lib\site-packages\you_get\common.py", line 322, in get_content
    response = request.urlopen(req)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\urllib\request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\urllib\request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
```

**Comment by rosynirvana** [comment]
chocolatey装的估计和homebrew一样会出现证书链的问题

#1038
先试试 --no-check-certificate

**Comment by yxliang01** [comment]
@rosynirvana 你是指chocolatey 安装的python(pip)吗?
话说,  you-get没有--no-check-certificate这个选项...
