### ISSUE TITLE
can't download bilibili 

### ISSUE THREAD

**Issue by thirdriver** [soimort/you-get#1645]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[DEBUG] get_content: http://www.bilibili.com/video/av7755392/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=12714955&from=miniplay&player=1&sign=ea2f38eac41d4431db5fd1f4782eeb54
Site:       bilibili.com
Title:      星露谷物语 Stardew Valley 第3期 祝尼魔一族 深辰解说_高清
Type:       Unknown type ()
Size:       0.0 MiB (0 Bytes)

you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av7755392/']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.626', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1323, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1139, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 177, in bilibili_download
    info_only=info_only)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 104, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 744, in download_urls
    assert urls
AssertionError
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[DEBUG] get_content: http://www.bilibili.com/video/av7755392/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=12714955&from=miniplay&player=1&sign=ea2f38eac41d4431db5fd1f4782eeb54
Site:       bilibili.com
Title:      星露谷物语 Stardew Valley 第3期 祝尼魔一族 深辰解说_高清
Type:       Unknown type ()
Size:       0.0 MiB (0 Bytes)

you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av7755392/']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.626', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1323, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1139, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 177, in bilibili_download
    info_only=info_only)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 104, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 744, in download_urls
    assert urls
AssertionError

```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by thirdriver** [comment]
```

[DEBUG] get_content: http://www.bilibili.com/video/av8136903/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=13380417&from=miniplay&player=1&sign=7eec38ffb3fcf4f6e809ff9bd1fb9bee
Site:       bilibili.com
Title:      【兄坑手书】东方家的惩罚游戏
Type:       Flash video (video/x-flv)
Size:       56.13 MiB (58854627 Bytes)

```

**Comment by thirdriver** [comment]
i can do work!

**Comment by biubiuboom** [comment]
貌似被B站封掉了= =

**Comment by cnbeining** [comment]
木有啊 您看看是不是请求没发出去或者被劫持了。。

**Comment by biubiuboom** [comment]
http://www.bilibili.com/video/av8289706/
这个链接就不行，看来是个别视频原因。
`C:\Users\Jie>you-get -di http://www.bilibili.com/video/av8289706/
[DEBUG] get_content: http://www.bilibili.com/video/av8289706/
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av8289706/']
Traceback (most recent call last):
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jie\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\bilibili.py", line 140, in bilibili_download
    assert flashvars
AssertionError`

**Comment by biubiuboom** [comment]
> C:\Users\Jie>you-get -di http://www.bilibili.com/video/av8289706/
[DEBUG] get_content: http://www.bilibili.com/video/av8289706/
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av8289706/']
Traceback (most recent call last):
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jie\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "c:\users\jie\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\bilibili.py", line 140, in bilibili_download
    assert flashvars
AssertionError

**Comment by cnbeining** [comment]
OK 是不是会员的世界呀 那您需要挂上cookie。。。

Refer to:

https://github.com/soimort/you-get/wiki/%E4%B8%AD%E6%96%87%E8%AF%B4%E6%98%8E#%E5%8A%A0%E8%BD%BDcookie

**Comment by biubiuboom** [comment]
您这回复速度，坐了火箭啊🚀，非常感谢！

**Comment by chn-yang** [comment]
不能下载B站视频+1,

log:

you-get --debug http://www.bilibili.com/video/av8463792/
[DEBUG] get_content: http://www.bilibili.com/video/av8463792/
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av8463792/']
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractors\bilibili.py", line 140, in bilibili_download
    assert flashvars
AssertionError
