### ISSUE TITLE
斗鱼源码多了反斜杠"\"，解析失败。youtube-dl 也同时中招

### ISSUE THREAD

**Issue by Justsoos** [soimort/you-get#1657]
“room_id” 由 js 导出的反斜杠没删掉，变成了 \“room_id\”，导致解析失败
目前只发现影响少数网页，比如  http://www.douyu.com/t/lpl

you-get -du http://www.douyu.com/t/lpl
[DEBUG] get_content: http://www.douyu.com/t/lpl
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=None
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['http://www.douyu.com/t/lpl']
Traceback (most recent call last):
  File "e:\users\obver\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\users\obver\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Users\obver\AppData\Local\Programs\Python\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>

  File "e:\users\obver\appdata\local\programs\python\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "e:\users\obver\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1416, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "e:\users\obver\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1329, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "e:\users\obver\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1145, in download_main
    download(url, **kwargs)
  File "e:\users\obver\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1409, in any_download
    m.download(url, **kwargs)
  File "e:\users\obver\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\douyutv.py", line 21, in douyutv_download
    data = json.loads(content)['data']
KeyError: 'data'

**Comment by Justsoos** [comment]
https://github.com/rg3/youtube-dl/pull/11931

**Comment by rosynirvana** [comment]
outdated
