### ISSUE TITLE
you-get: [Failed] vid参数错误(vid parameter error) when dealing with youku

### ISSUE THREAD

**Issue by neworld1974** [soimort/you-get#1658]
C:\>you-get -d http://v.youku.com/v_show/id_xmtu5mjez0tgyma==.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=xmtu5mjez0tgyma==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=xmtu5mjez0tgyma==&ct=12
you-get: [Failed] vid参数错误
（translation for the above Chinese characters: vid parameter error）

> [舔 :icecream:!]

**Comment by zhangn1985** [comment]
404

**Comment by neworld1974** [comment]
sorry. I made a mistake. the following is the problem:

C:\>you-get -d http://v.youku.com/v_show/id_XMjQ4NjgzMDIzNg==.html?from=y1.3-idx-beta-1519-23042.223465.10-1
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjQ4NjgzMDIzNg==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjQ4NjgzMDIzNg==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/148594579978112859ce5_00/st/flv/fileid/03008090005889E03F1A76011BA6A966DEC5CF-C033-818E-AA29-52136C2A9223?yxon=1&K=b77887f048bb6e3d2412e510%26sign%3Dc8d5e5395e4dcc73676034501b1a7008&ep=cyacH0CJU8kJ7CTXiT8bbynrJyIKXP4J9h%2BNgdtiALshQOC27D7SsZzBSflCF%2FhrAyR3Ge3336WUbzNiYYNDqmsQ10%2BgTPqRj%2FLq5ahRxZMGFRtHe8%2FVt1SeSjD4&ctype=12&token=0909&oip=2047154966&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/148594579978112859ce5_00/st/flv/fileid/03008090015889E03F1A76011BA6A966DEC5CF-C033-818E-AA29-52136C2A9223?yxon=1&K=5e001fb1424085fd282c167b%26sign%3D91173f375f6d73c120080b596cdd40ee&ep=cyacH0CJU8kJ7CTXiT8bbynrJyIKXP4J9h%2BNgdtiALohQOC27D7SsZzBSflCF%2FhrAyR3Ge3336WUbzNiYYNDqmsQ10%2BgTPqRj%2FLq5ahRxZMGFRtHe8%2FVt1SeSjD4&ctype=12&token=0909&oip=2047154966&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/148594579978112859ce5_00/st/flv/fileid/03008090025889E03F1A76011BA6A966DEC5CF-C033-818E-AA29-52136C2A9223?yxon=1&K=9d792da49cf870902412e510%26sign%3Da9cc89c488fe94332630b361dbd0b6d0&ep=cyacH0CJU8kJ7CTXiT8bbynrJyIKXP4J9h%2BNgdtiALkhQOC27D7SsZzBSflCF%2FhrAyR3Ge3336WUbzNiYYNDqmsQ10%2BgTPqRj%2FLq5ahRxZMGFRtHe8%2FVt1SeSjD4&ctype=12&token=0909&oip=2047154966&ev=1
site:                优酷 (Youku)
title:               丙申年封箱整场
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          4096.0 MiB (4294967295 bytes)
    # download-with: you-get --format=hd3 [URL]

Downloading 丙申年封箱整场.flv ...
 0.0% (   0.0/4096.0MB) ├───────────────────────────────────────┤[1/3] you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjQ4NjgzMDIzNg==.html?from=y1.3-idx-beta-1519-23042.223465.10-1']
Traceback (most recent call last):
  File "c:\users\王\appdata\local\programs\python\python35-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\王\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\王\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\王\appdata\local\programs\python\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\王\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\王\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1323, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\王\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1139, in download_main
    download(url, **kwargs)
  File "c:\users\王\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "c:\users\王\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractor.py", line 52, in download_by_url
    self.download(**kwargs)
  File "c:\users\王\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractor.py", line 208, in download
    av=stream_id in self.dash_streams)
  File "c:\users\王\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 793, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers)
  File "c:\users\王\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 532, in url_save
    with open(temp_filepath, open_mode) as output:
PermissionError: [Errno 13] Permission denied: '.\\丙申年封箱整场[00].flv.download'

**Comment by soimort** [comment]
1. 标题和debug信息不符。
2. 请检查下载文件夹写入权限。
