### ISSUE TITLE
dilidili 新域名支持。

### ISSUE THREAD

**Issue by kxxoling** [soimort/you-get#1663]
由于 dilidili.com 近期访问不畅，官方开启了 dilidili.wang 和 dilidili.mobi 两个新域名，希望能得到支持。

例如，``you-get http://www.dilidili.wang/watch3/54829/`` 什么结果也没有。

**Comment by ArchieMeng** [comment]
This is a debug output. The cookie might be broken.
[DEBUG] get_content: http://www.dilidili.com/watch3/48104/
[DEBUG] get_content: https://newplayer.jfrft.com/index.php?vid=XMTY4ODIzMzE1Mg==&v=youku&sign=e4dd9bf2248cf79ff409f7032f45ea8a
[DEBUG] get_content: http://player.005.tv/parse.php?xmlurl=null&type=youku&vid=XMTY4ODIzMzE1Mg==&hd=2&sign=e4dd9bf2248cf79ff409f7032f45ea8a&tmsign=645c0aa35e15930683ed5f76fcf75ad8&userlink=http%3A%2F%2Fwww.dilidili.com%2F
[DEBUG] get_content: http://player.005.tv/parse.php?xmlurl=null&type=youku&vid=XMTY4ODIzMzE1Mg==&hd=3&sign=e4dd9bf2248cf79ff409f7032f45ea8a&tmsign=645c0aa35e15930683ed5f76fcf75ad8&userlink=http%3A%2F%2Fwww.dilidili.com%2F
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.dilidili.com/watch3/48104/']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/archie/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/archie/you-get/src/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/archie/you-get/src/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/archie/you-get/src/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/home/archie/you-get/src/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/home/archie/you-get/src/you_get/extractors/dilidili.py", line 65, in dilidili_download
    ckplayer_download(parse_url, output_dir, merge, info_only, is_xml = True, title = title, headers = headers)
  File "/home/archie/you-get/src/you_get/extractors/ckplayer.py", line 94, in ckplayer_download
    info_only, title = title)
  File "/home/archie/you-get/src/you_get/extractors/ckplayer.py", line 58, in ckplayer_download_by_xml
    video_info = ckplayer_get_info_by_xml(ckinfo)
  File "/home/archie/you-get/src/you_get/extractors/ckplayer.py", line 23, in ckplayer_get_info_by_xml
    if '_text' in dictify(e)['ckplayer']['info'][0]['title'][0]:  #title
KeyError: 'info'
