### ISSUE TITLE
乐视视频无法下载

### ISSUE THREAD

**Issue by wjm2038** [soimort/you-get#1672]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get --debug http://www.le.com/ptv/vplay/1847703.html
[DEBUG] get_content: http://www.le.com/ptv/vplay/1847703.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=1847703&platid=1&splatid=101&format=1&tkey=957971627&domain=www.letv.com
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/1847703.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/le.py", line 137, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/le.py", line 90, in letv_download_by_vid
    ext , urls = video_info(vid,**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/le.py", line 61, in video_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get --debug http://www.le.com/ptv/vplay/1847703.html
[DEBUG] get_content: http://www.le.com/ptv/vplay/1847703.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=1847703&platid=1&splatid=101&format=1&tkey=957971627&domain=www.letv.com
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/1847703.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/le.py", line 137, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/le.py", line 90, in letv_download_by_vid
    ext , urls = video_info(vid,**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/le.py", line 61, in video_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by xuehao** [comment]
Bug还没解决吧，今天下载乐视视频，还是报错。表现是，可以下载各个分段，但是不能自动合成，所以应该是合成模块出了问题。

**Comment by quiet324** [comment]
碰到同样的问题，可以下载各个分段，但是不能自动合成。

**Comment by lki2019** [comment]
t470bg/bt709, progressive), 960x720, q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (HE-AACv2) (mp4a / 0x6134706D), 44100 Hz, stereo, fl
tp, 31 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=11150 fps=0.0 q=-1.0 size=   28928kB time=00:07:25.88 bitrate= 531.5kbits/
frame=16214 fps=16213 q=-1.0 size=   45568kB time=00:10:48.44 bitrate= 575.7kbit
frame=28223 fps=18814 q=-1.0 size=   73984kB time=00:18:48.80 bitrate= 536.9kbit
frame=34024 fps=19587 q=-1.0 Lsize=   86055kB time=00:22:40.96 bitrate= 518.0kbi
ts/s speed= 783x
video:79807kB audio:5317kB subtitle:0kB other streams:0kB global headers:0kB mux
ing overhead: 1.093438%
Merged into 海绵宝宝001.mp4



现在可以下载，也可以合并

可以关闭了
