### ISSUE TITLE
cannot download youtube live 无法下载YouTube直播

### ISSUE THREAD

**Issue by wjm2038** [soimort/you-get#1673]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get --debug https://www.youtube.com/watch?v=uNN6Pj06Cj8
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=uNN6Pj06Cj8
[DEBUG] get_content: https://www.youtube.com/watch?v=uNN6Pj06Cj8
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=uNN6Pj06Cj8']
Traceback (most recent call last):
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wjm\AppData\Local\Programs\Python\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\youtube.py", line 214, in prepare
    stream_itag = metadata['itag'][0]
KeyError: 'itag'
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get --debug https://www.youtube.com/watch?v=uNN6Pj06Cj8
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=uNN6Pj06Cj8
[DEBUG] get_content: https://www.youtube.com/watch?v=uNN6Pj06Cj8
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=uNN6Pj06Cj8']
Traceback (most recent call last):
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wjm\AppData\Local\Programs\Python\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\wjm\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\youtube.py", line 214, in prepare
    stream_itag = metadata['itag'][0]
KeyError: 'itag'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by wjm2038** [comment]
@soimort-bot could you please test this link for me? https://www.youtube.com/watch?v=uNN6Pj06Cj8

**Comment by wjm2038** [comment]
@soimort-bot could you please check you-get is up-to-date?

**Comment by cnbeining** [comment]
@wjm2038 Nah if @soimort-bot is here it is always using the most up-to-date commit...

**Comment by wjm2038** [comment]
@cnbeining but the least one is 0.4.652 and it still not workng
```
$ you-get -di https://www.youtube.com/watch?v=uNN6Pj06Cj8
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=uNN6Pj06Cj8
[DEBUG] get_content: https://www.youtube.com/watch?v=uNN6Pj06Cj8
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=uNN6Pj06Cj8']
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/you_get/extractors/youtube.py", line 214, in prepare
    stream_itag = metadata['itag'][0]
KeyError: 'itag'
```

**Comment by wjm2038** [comment]
@soimort-bot could you please test this link for me? https://www.youtube.com/watch?v=uNN6Pj06Cj8

**Comment by L34p** [comment]
@wjm2038 I fixed this issue but it is not merged yet. I'm not sure it can be merged but you can test my fixed version on https://github.com/L34p/you-get/tree/improve-youtube-livestream

You can use below commands to test my fixed version.
```shell
git clone https://github.com/L34p/you-get.git -b improve-youtube-livestream you-get-l34p
cd you-get-l34p
./you-get -di https://www.youtube.com/watch?v=uNN6Pj06Cj8
```

**Comment by wjm2038** [comment]
@L34p  i will. thank you very much!

**Comment by wjm2038** [comment]
@soimort-bot could you please test this link for me? https://www.youtube.com/watch?v=uNN6Pj06Cj8
