### ISSUE TITLE
bilibili2016和2017拜年祭视频无法下载

### ISSUE THREAD

**Issue by airectx** [soimort/you-get#1680]
在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:
2016的

```
C:\Users\airec>you-get -o E:/out -d https://www.bilibili.com/video/av3521416/
[DEBUG] get_content: http://www.bilibili.com/video/av3521416/
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://www.bilibili.com/video/av3521416/']
Traceback (most recent call last):
  File "c:\users\airec\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\airec\AppData\Local\Programs\Python\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\bilibili.py", line 140, in bilibili_download
    assert flashvars
AssertionError
```
2017的

```
C:\Users\airec>you-get -o E:/out -d https://www.bilibili.com/video/av7248433/
[DEBUG] get_content: http://www.bilibili.com/video/av7248433/
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://www.bilibili.com/video/av7248433/']
Traceback (most recent call last):
  File "c:\users\airec\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\airec\AppData\Local\Programs\Python\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\bilibili.py", line 140, in bilibili_download
    assert flashvars
AssertionError
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 2015的可以下载，发现这两个视频会跳转到拜年祭播放页面，但是用拜年祭播放页面依旧解析不出来
> [舔 :icecream:!]

**Comment by cnbeining** [comment]
您有可能需要挂cookie。

**Comment by zjuchenyuan** [comment]
我认为这个拜年祭页面是特殊页面，需要单独写代码考虑

**Comment by zjuchenyuan** [comment]
2017拜年祭的aid和cid在这里可以获得：http://api.bilibili.com/x/player/matsuri
bilibli has created a single api for matsuri, the url is "http://api.bilibili.com/x/player/matsuri"

**Comment by cnbeining** [comment]
我才不会为俩页面写个patch呢 哼！


ChenYuan <notifications@github.com>于2017年2月21日 周二下午11:46写道：

**Comment by zjuchenyuan** [comment]
@cnbeining 
我理解这种为两个单独页面修改代码并不合适，或许我们可以采用单独写个py（调用you-get的基本函数）的方式解决本issue？

I understand that modify the code for these two pages is not suitable, maybe we can write a small python file (calling basic function in you-get) to solve this issue.

**Comment by zjuchenyuan** [comment]
@airectx @cnbeining 
I finished this tiny script, you can look at this:
https://gist.github.com/zjuchenyuan/46700532b6c7721d3639219e4ac6a1f0

**Comment by airectx** [comment]
@zjuchenyuan 
感谢！视频可以解析出来了
```
D:\out>python bilibili_matsuri_download.py
Site:       bilibili.com
Title:      2017拜年祭_1鸡
Type:       Flash video (video/x-flv)
Size:       965.36 MiB (1012250145 Bytes)
```

> 不过2017的p3己实际是有4个版本的，不过那个视频的单品已发布可以解析下载了
