### ISSUE TITLE
使用socks代理，提示找不到pysocks，但是pysocks已经安装

### ISSUE THREAD

**Issue by lizhaode** [soimort/you-get#1684]
**复现环境**：

Mac 10.11.6 
HomeBrew安装Python3和You-Get --with-rtmpdump
Terminal中alias Python和pip命令到Brew安装的Python3目录下
PySocks已经通过pip进行安装

**复现步骤**：

1. Mac上使用原版的ShadowSocks翻墙
2. 随意找一个YouTube视频链接
3. Terminal中敲入命令 `you-get -s 127.0.0.1:1080 -i https://www.youtube.com/watch?v=0S4lpBFZGFQ --debug`

**实际结果**：

提示错误 `you-get: Error importing PySocks library, socks proxy ignored.In order to use use socks proxy, please install PySocks.`

截图如下
![](http://p1.bqimg.com/4851/161293a74dfd8864.png)

**Comment by lizhaode** [comment]
问题找到了，是因为HomeBrew安装的You-Get，自带Python3，所以找不到PySocks，这个问题请 @soimort 反馈给HomeBrew

**Comment by zhangn1985** [comment]
看来Brew也是一陀

**Comment by myfingerhurt** [comment]
Same Problem on Windows client, please fix it.

---------------------------------------------------------------
you-get: version 0.4.652, a tiny downloader that scrapes the web.

>
>pip install PySocks
Requirement already satisfied: PySocks in c:\users\finger\appdata\local\programs\python\python36-32\lib\site-packages

>you-get -d -s 127.0.0.1:1080 "https://www.youtube.com/watch?v=lXEfpTaaA5g"
you-get: Error importing PySocks library, socks proxy ignored.In order to use use socks proxy, please install PySocks.
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=lXEfpTaaA5g
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=lXEfpTaaA5g']
Traceback (most recent call last):
  File "urllib\request.py", line 1240, in do_open
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 1229, in connect
  File "http\client.py", line 826, in connect
  File "socket.py", line 707, in create_connection
  File "socket.py", line 698, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1400, in any_download
  File "src\you_get\extractor.py", line 41, in download_by_url
  File "src\you_get\extractors\youtube.py", line 143, in prepare
  File "src\you_get\common.py", line 323, in get_content
  File "src\you_get\common.py", line 300, in urlopen_with_retry
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 465, in open
  File "urllib\request.py", line 483, in _open
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 1283, in https_open
  File "urllib\request.py", line 1242, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
you-get returned -1

>

**Comment by zpfsqzyl** [comment]
同样存在这个问题，代理无法使用，提示Error importing PySocks library, socks proxy ignored.In order to use use socks proxy, please install PySocks.

**Comment by rosynirvana** [comment]
@zpfsqzyl
你的you-get是怎么装的？

**Comment by zpfsqzyl** [comment]
@rosynirvana 从chocolatey下载的、exe编译版本和7z的版本都是这样

**Comment by lizhaode** [comment]
@zpfsqzyl 装上pysocks就行了

**Comment by zpfsqzyl** [comment]
@lizhaode pysocks已安装

PS C:\Users\leafl> pip install pysocks
Requirement already satisfied: pysocks in c:\users\leafl\appdata\local\programs\python\python35-32\lib\site-packages\pysocks-1.6.7-py3.5.egg

python直接import socks也正常。

**Comment by zpfsqzyl** [comment]
相比之下，用win10的bash安装you-get之后就可以使用代理。

**Comment by yfhust** [comment]
ubuntu下没有这样的问题啊

**Comment by hugodotlau** [comment]
这问题没解决啊，怎么就close了？

**Comment by tedli** [comment]
/usr/local/Cellar/you-get/0.4.803/libexec/bin  ./pip3.6 --no-cache-dir install pysocks

**Comment by Co2333** [comment]
@tedli /usr/local/Cellar/you-get/版本号/libexec/bin/pip --no-cache-dir install pysocks

~ lakr$ /usr/local/Cellar/you-get/0.4.939/libexec/bin/pip --no-cache-dir install pysocks
