### ISSUE TITLE
youtube某些视频链接无法下载

### ISSUE THREAD

**Issue by ioilala** [soimort/you-get#1686]
https://www.youtube.com/watch?v=pTgGu2oUY8Q

> $ you-get --debug https://www.youtube.com/watch?v=pTgGu2oUY8Q
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=pTgGu2oUY8Q
[DEBUG] get_content: https://www.youtube.com/watch?v=pTgGu2oUY8Q
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-zh_HK-vflFr-ms_/base.js
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=pTgGu2oUY8Q']
Traceback (most recent call last):
  File "c:\users\xx\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\youtube.py", line 263, in prepare
    dashmpd = ytplayer_config['args']['dashmpd']
KeyError: 'dashmpd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\xx\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xx\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\xx\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\xx\appdata\local\programs\python\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
TypeError: 'NoneType' object is not iterable

**Comment by soimort** [comment]
Should be fixed by c1ed0d7e15d327327922235894623f7a551438b3.
