### ISSUE TITLE
可以增加全集下载支持吗

### ISSUE THREAD

**Issue by kt1024** [soimort/you-get#1691]
谢谢，单独下载OK，但是有几百集 另一个近千

>you-get.exe --debug http://list.youku.com/show/id_z2f9a63c4ca3411e5b522.html
[DEBUG] get_content: http://list.youku.com/show/id_z2f9a63c4ca3411e5b522.html
site:                优酷 (Youku)
playlist:            《贝瓦儿歌 第二季》更新至214集—大陆—动漫—优酷网，视频高清在线观看
videos:
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://list.youku.com/show/id_z2f9a63c4ca3411e5b522.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1400, in any_download
  File "src\you_get\extractor.py", line 41, in download_by_url
  File "src\you_get\extractors\youku.py", line 160, in prepare
NameError: name 'exit' is not defined
you-get returned -1

**Comment by xuyuanfang** [comment]
可以写个python脚本按地址顺序循环调用you-get把全集下下来23333

**Comment by ztytian** [comment]
我倒是用的是shell脚本。。。windows用bat批处理也行啊

**Comment by omaidb** [comment]
这是个好主意

**Comment by omaidb** [comment]
你们都好腻害，可惜我不知道怎么做

**Comment by rosynirvana** [comment]
dup #1596
