### ISSUE TITLE
http 301/302似乎会有一个bug

### ISSUE THREAD

**Issue by rosynirvana** [soimort/you-get#1693]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[DEBUG] get_content: http://www.bilibili.com/video/av7873772/
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av7873772/']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 140, in bilibili_download
    assert flashvars
AssertionError
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

这个url会被重定向到一个bangumi.bilibili的页面上去

curl -v 'http://www.bilibili.com/video/av7873772/'
< location: http://bangumi.bilibili.com/anime/5776/play#100138

最后 File "/usr/local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 140 的上下文在

 if re.match(r'https?://bangumi\.bilibili\.com/', url):
 ……
else:
    flashvars = r1_of([r'(cid=\d+)', r'(cid: \d+)', r'flashvars="([^"]+)"',
                       r'"https://[a-z]+\.bilibili\.com/secure,(cid=\d+)(?:&aid=\d+)?"'], html)
    assert flashvars

忽略了302后url的变化，assert的时候直接失败

**Comment by rosynirvana** [comment]
close via #1698
