### ISSUE TITLE
希望加入喜马拉雅的支持～

### ISSUE THREAD

**Issue by AlbertDu** [soimort/you-get#1721]
首先感谢作者的辛勤更新和you-get为我们生活带来的便利。

请问作者考虑加入 （喜马拉雅）的支持吗？

**Comment by rosynirvana** [comment]
给个域名和测试链接？

**Comment by AlbertDu** [comment]
这个是网站首页：http://www.ximalaya.com/explore/
专辑页面（这注意有些专辑可能多与一页，不知道这个会不会影响实现，提醒一下）：http://www.ximalaya.com/2232146/album/2673722

**Comment by rosynirvana** [comment]
那，多于一页的也帮忙找个链接？

**Comment by rosynirvana** [comment]
#1722

**Comment by AlbertDu** [comment]
感谢您的工作， 我想知道怎么才能得到这个最新的更新啊， pip 的upgrade 好像还不行。
再次谢谢您～

**Comment by rosynirvana** [comment]
@AlbertDu pip要等作者release新版本才行
这个还没merge，属于最早期状态的代码

**Comment by AlbertDu** [comment]
有点问题，是不是我的使用姿势不太对啊（OSX python 3.6）

`➜  you-get git:(develop) ./you-get -dl  'http://www.ximalaya.com/70268405/album/6506465'                        
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.ximalaya.com/70268405/album/6506465']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/Users/duzhy/Documents/my_addon/you-get-newest/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/duzhy/Documents/my_addon/you-get-newest/you-get/src/you_get/common.py", line 1421, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/duzhy/Documents/my_addon/you-get-newest/you-get/src/you_get/common.py", line 1334, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/duzhy/Documents/my_addon/you-get-newest/you-get/src/you_get/common.py", line 1148, in download_main
    download_playlist(url, **kwargs)
  File "/Users/duzhy/Documents/my_addon/you-get-newest/you-get/src/you_get/common.py", line 1418, in any_download_playlist
    m.download_playlist(url, **kwargs)
  File "/Users/duzhy/Documents/my_addon/you-get-newest/you-get/src/you_get/common.py", line 996, in f
    raise NotImplementedError('Playlist is not supported for ' + name)
NotImplementedError: Playlist is not supported for universal`

**Comment by rosynirvana** [comment]
common.py换了吗？

**Comment by AlbertDu** [comment]
我直接clone了你的仓库，

> git clone https://github.com/rosynirvana/you-get.git

**Comment by rosynirvana** [comment]
现在git在哪个branch?
如果不在support_ximalaya就
```
git checkout support_ximalaya
```

**Comment by AlbertDu** [comment]
ok，搞定了，刚才没注意clone了master的代码。

谢谢～

**Comment by soimort** [comment]
Fixed by #1722.
