### ISSUE TITLE
v.qq.com cant download 腾讯视频不能下载了

### ISSUE THREAD

**Issue by weigeloveu** [soimort/you-get#1723]
you-get -d https://v.qq.com/x/cover/j6cgzhtkuonf6te/d0022cirzjl.html
Site:       QQ.com
Title:      三生三世十里桃花_50
Type:       MPEG-4 video (video/mp4)
Size:       844.84000000000003 MiB (885881481 Bytes)

Downloading 三生三世十里桃花_50.mp4 ...
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/j6cgzhtkuonf6te/d0022cirzjl.html']
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/extractors/qq.py", line 111, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/extractors/qq.py", line 57, in qq_download_by_vid
    download_urls(part_urls, parts_ti, ext, total_size, output_dir=output_dir, merge=merge)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 783, in download_urls
    bar.update()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 655, in update
    bar = self.bar.format(percent, round(self.received / 1048576, 1), bar, self.current_piece, self.total_pieces, self.speed)
ValueError: Sign not allowed in string format specifier

**Comment by lamlam123tld3** [comment]
it just seems it cannot parse the vid correctly

**Comment by Cphilo** [comment]
这个应该是这个接口已经被封掉了，之前拿vkey的接口现在用不了了

**Comment by Zapiboss** [comment]
![image](https://cloud.githubusercontent.com/assets/4704947/24816745/392c9224-1bda-11e7-8338-59fa072fb7c3.png)
Hello, i've got the same issue for a recent vip video.

**Comment by Zapiboss** [comment]
Hello, it's me again.
A friend of mine helped me with this issue and you can fix it by just adding cookies.
you-get -c cookies.sqlite https://v.qq.com/x/cover/ttqxo9s3cblgofl/x002353t5ih.html
I used firefox cookies and inside, there is a vip account logged so maybe that's the solution.

**Comment by rosynirvana** [comment]
```
$ ./you-get -i 'https://v.qq.com/x/cover/j6cgzhtkuonf6te/d0022cirzjl.html'
Site:       QQ.com
Title:      三生三世十里桃花_50
Type:       MPEG-4 video (video/mp4)
Size:       763.68 MiB (800774863 Bytes)
```

and ```Size: 844.84000000000003 MiB (885881481 Bytes)``` suggested a python bug described in #2139
