### ISSUE TITLE
请问腾讯课堂的视频不能下载吗？

### ISSUE THREAD

**Issue by Cenbylin** [soimort/you-get#1724]
>you-get.exe --debug -i "https://ke.qq.com/webcourse/index.html#course_id=144677&term_id=100163870&taid=815665829262629&vid=z1413e8zlje"
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://ke.qq.com/webcourse/index.html#course_id=144677&term_id=100163870&taid=815665829262629&vid=z1413e8zlje']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1400, in any_download
  File "src\you_get\extractors\qq.py", line 111, in qq_download
  File "src\you_get\extractors\qq.py", line 10, in qq_download_by_vid
TypeError: Can't convert 'NoneType' object to str implicitly
you-get returned -1

和腾讯视频的原理很可能是一样的吧。希望加入支持。感谢

**Comment by lki2019** [comment]
https://ke.qq.com/

 公开课，切换UA MP4直链

**Comment by caryyu** [comment]
@soimort-bot  The sort of same issue occurring;  As the context said which means the new feature is in progress right ?
# Version Of you-get
```
you-get --version
you-get: version 0.4.915, a tiny downloader that scrapes the web.
```
# Command Line
```
you-get -i "https://ke.qq.com/webcourse/index.html#course_id=193209&term_id=100228911&taid=1109415822553785&vid=d1412aombil" --debug
```
# Verbose Message Below
```
[DEBUG] get_content: https://ke.qq.com/webcourse/index.html#course_id=193209&term_id=100228911&taid=1109415822553785&vid=d1412aombil
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=None
you-get: vid is wrong
```
