### ISSUE TITLE
Cannot download paid video from letv even got cookies.sqlite

### ISSUE THREAD

**Issue by lucifekit** [soimort/you-get#1725]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:
you-get -i --debug -c "cookies.sqlite" "http://www.le.com/ptv/vplay/27662516.html"
```
Not have code because it can run, just cannot merge and not full length.
```
The cookies i used is the one get from firefox directory, and is the one that i used to logged in to letv and watch full length video, but you-get can only download ~ 6 mins of the video like i watch when not logged in, not the full length (66 mins) i want.

**Comment by lucifekit** [comment]
```
Current Video Supports:
	--format 1000 <URL>
	--format 1080p <URL>
	--format 1300 <URL>
	--format 720p <URL>
	--format 350 <URL>
Site:       Le.com
Title:      总裁在上1初见初念
Type:       MPEG-4 video (video/mp4)
Size:       271.87 MiB (285073988 Bytes)

Downloading 总裁在上1初见初念.mp4 ...

 0.0% (  0.0/271.9MB) ├───────────────────────────────────────┤[ 1/42] 
 0.1% (  0.2/271.9MB) ├───────────────────────────────────────┤[ 1/42]  893 kB/s
 0.1% (  0.2/271.9MB) ├───────────────────────────────────────┤[ 2/42]  392 kB/s
 2.0% (  5.4/271.9MB) ├█──────────────────────────────────────┤[ 3/42]   29 MB/s
 2.6% (  7.1/271.9MB) ├█──────────────────────────────────────┤[ 4/42]   10 MB/s
 7.0% ( 19.0/271.9MB) ├███────────────────────────────────────┤[ 5/42]   65 MB/s
 9.8% ( 26.7/271.9MB) ├████───────────────────────────────────┤[ 6/42]   42 MB/s
14.3% ( 39.0/271.9MB) ├██████─────────────────────────────────┤[ 7/42]   67 MB/s
16.3% ( 44.3/271.9MB) ├███████────────────────────────────────┤[ 8/42]   28 MB/s
18.9% ( 51.5/271.9MB) ├████████───────────────────────────────┤[ 9/42]   37 MB/s
25.4% ( 69.0/271.9MB) ├██████████─────────────────────────────┤[10/42]   88 MB/s
30.4% ( 82.8/271.9MB) ├████████████───────────────────────────┤[11/42]   71 MB/s
32.1% ( 87.2/271.9MB) ├█████████████──────────────────────────┤[12/42]   25 MB/s
34.6% ( 94.1/271.9MB) ├██████████████─────────────────────────┤[13/42]   38 MB/s
38.1% (103.6/271.9MB) ├███████████████────────────────────────┤[14/42]   50 MB/s
39.4% (107.2/271.9MB) ├████████████████───────────────────────┤[15/42]   19 MB/s
40.8% (110.9/271.9MB) ├████████████████───────────────────────┤[16/42]   21 MB/s
42.3% (115.0/271.9MB) ├█████████████████──────────────────────┤[17/42]   22 MB/s
44.1% (120.0/271.9MB) ├██████████████████─────────────────────┤[18/42]   26 MB/s
47.3% (128.5/271.9MB) ├███████████████████────────────────────┤[19/42]   46 MB/s
50.5% (137.3/271.9MB) ├████████████████████───────────────────┤[20/42]   48 MB/s
52.9% (143.7/271.9MB) ├█████████████████████──────────────────┤[21/42]   34 MB/s
54.9% (149.4/271.9MB) ├██████████████████████─────────────────┤[22/42]   32 MB/s
58.1% (157.9/271.9MB) ├███████████████████████────────────────┤[23/42]   47 MB/s
60.1% (163.5/271.9MB) ├████████████████████████───────────────┤[24/42]   31 MB/s
63.4% (172.4/271.9MB) ├█████████████████████████──────────────┤[25/42]   46 MB/s
67.2% (182.6/271.9MB) ├███████████████████████████────────────┤[26/42]   55 MB/s
70.6% (191.9/271.9MB) ├████████████████████████████───────────┤[27/42]   48 MB/s
72.6% (197.3/271.9MB) ├█████████████████████████████──────────┤[28/42]   28 MB/s
74.0% (201.2/271.9MB) ├█████████████████████████████──────────┤[29/42]   21 MB/s
75.8% (206.1/271.9MB) ├██████████████████████████████─────────┤[30/42]   27 MB/s
78.1% (212.5/271.9MB) ├███████████████████████████████────────┤[31/42]   36 MB/s
80.2% (218.0/271.9MB) ├████████████████████████████████───────┤[32/42]   29 MB/s
82.7% (224.8/271.9MB) ├████████████████████████████████───────┤[33/42]   37 MB/s
84.4% (229.4/271.9MB) ├█████████████████████████████████──────┤[34/42]   25 MB/s
86.4% (235.0/271.9MB) ├██████████████████████████████████─────┤[35/42]   30 MB/s
88.7% (241.2/271.9MB) ├███████████████████████████████████────┤[36/42]   33 MB/s
91.2% (247.9/271.9MB) ├████████████████████████████████████───┤[37/42]   37 MB/s
92.8% (252.2/271.9MB) ├████████████████████████████████████───┤[38/42]   23 MB/s
94.5% (256.9/271.9MB) ├█████████████████████████████████████──┤[39/42]   25 MB/s
96.9% (263.4/271.9MB) ├██████████████████████████████████████─┤[40/42]   34 MB/s
98.2% (267.1/271.9MB) ├███████████████████████████████████████┤[41/42]   19 MB/s
 100% (271.9/271.9MB) ├███████████████████████████████████████┤[42/42]   26 MB/s
Merging video parts...
.\总裁在上1初见初念[00].mp4

```

**Comment by lucifekit** [comment]
```
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/27662516.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1400, in any_download
  File "src\you_get\extractors\le.py", line 137, in letv_download
  File "src\you_get\extractors\le.py", line 98, in letv_download_by_vid
  File "src\you_get\common.py", line 830, in download_urls
  File "src\you_get\processor\join_mp4.py", line 914, in concat_mp4
  File "src\you_get\processor\join_mp4.py", line 876, in merge_mp4s
  File "src\you_get\processor\join_mp4.py", line 717, in read_mp4
  File "src\you_get\processor\join_mp4.py", line 708, in parse_atoms
  File "src\you_get\processor\join_mp4.py", line 700, in read_atom
NotImplementedError: b'\x00\x00\xb0\r': 1195376648
you-get returned -1
```

**Comment by cnbeining** [comment]
请正确安装ffmpeg再试试？
