### ISSUE TITLE
non-ascii url issues

### ISSUE THREAD

**Issue by rosynirvana** [soimort/you-get#1728]
failed test case:
```
ou-get -di 'http://bonnie-23.tumblr.com/post/143530983701/艦これ３周年-金剛さんこれからもよろしくお願いします'
you-get: [error] oops, the current environment does not seem to support Unicode.
you-get: please set it to a UTF-8-aware locale first,
you-get: so as to save the video (with some Unicode characters) correctly.
you-get: you can do it like this:
you-get:     (Windows)    % chcp 65001
you-get:     (Linux)      $ LC_CTYPE=en_US.UTF-8
```
感觉首先应该在UnicodeError的时候打印Calling Stack
```diff
diff --git a/src/you_get/common.py b/src/you_get/common.py
index 2edbc42..680e8cd 100755
--- a/src/you_get/common.py
+++ b/src/you_get/common.py
@@ -1340,6 +1340,7 @@ def script_main(script_name, download, download_playlist, **kwargs):
         else:
             sys.exit(1)
     except UnicodeEncodeError:
+        raise
         log.e('[error] oops, the current environment does not seem to support Unicode.')
         log.e('please set it to a UTF-8-aware locale first,')
         log.e('so as to save the video (with some Unicode characters) correctly.')
```
搜了一下发现[这个commit](https://github.com/soimort/you-get/commit/3341bddfcaf0bb2d20ca078b6c56e0899952798f)是交给extractor处理的，应该遵照这个范例，还是放在common.py里？

如果在common.py里，似乎应该在url_to_module里，处理完google_search后

**Comment by rosynirvana** [comment]
这个patch会让一些url 404
```
/you-get -di 'https://bangumi.bilibili.com/anime/427/play#71958'
[DEBUG] get_content: http://bangumi.bilibili.com/anime/427/play#71958
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://bangumi.bilibili.com/anime/427/play#71958']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/Users/_/misc/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/_/misc/you-get/src/you_get/common.py", line 1428, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/_/misc/you-get/src/you_get/common.py", line 1341, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/_/misc/you-get/src/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/Users/_/misc/you-get/src/you_get/common.py", line 1421, in any_download
    m.download(url, **kwargs)
  File "/Users/_/misc/you-get/src/you_get/extractors/bilibili.py", line 120, in bilibili_download
    html = get_content(url)
  File "/Users/_/misc/you-get/src/you_get/common.py", line 337, in get_content
    response = urlopen_with_retry(req)
  File "/Users/_/misc/you-get/src/you_get/common.py", line 313, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by soimort** [comment]
Reverted. 

![lws77gt](https://cloud.githubusercontent.com/assets/342945/23592338/909804ac-01ff-11e7-9345-f30fcf58596d.gif)
