### ISSUE TITLE
斗鱼现在怎么直播呢

### ISSUE THREAD

**Issue by moboard** [soimort/you-get#1738]
斗鱼现在播放的话有提示：
 you-get -p vlc --debug https://www.douyu.com/193024
[DEBUG] get_content: http://www.douyu.com/193024
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=193024
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://www.douyu.com/193024']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1428, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1341, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1421, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/extractors/douyutv.py", line 21, in douyutv_download
    data = json.loads(content)['data']
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
----
然后主退出了，是什么问题呢？

**Comment by sweat89** [comment]
我直接用播放器打开。会提示vlc没权限。这个怎么破

**Comment by rosynirvana** [comment]
outdated
