### ISSUE TITLE
Netease music download with 404

### ISSUE THREAD

**Issue by KiritoStudio** [soimort/you-get#1739]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
C:\Users\233>you-get -d http://music.163.com/m/song?id=22805089
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=22805089&ids=[22805089]&csrf_token=
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/m/song?id=22805089']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1400, in any_download
  File "src\you_get\extractors\netease.py", line 133, in netease_download
  File "src\you_get\extractors\netease.py", line 70, in netease_cloud_music_download
  File "src\you_get\extractors\netease.py", line 120, in netease_song_download
  File "src\you_get\extractors\netease.py", line 123, in netease_download_common
  File "src\you_get\common.py", line 411, in url_info
  File "src\you_get\common.py", line 300, in urlopen_with_retry
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 471, in open
  File "urllib\request.py", line 581, in http_response
  File "urllib\request.py", line 509, in error
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 589, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
you-get returned -1
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
web端的接口改了
```
Request URL:http://music.163.com/weapi/song/enhance/player/url?csrf_token=
Request Method:POST
```
原来的extractor用的不是这个接口
```
get_content("http://music.163.com/api/song/detail/?id=%s&ids=[%s]&csrf_token=" % (rid, rid), headers={"Referer": "http://music.163.com/"})
```

**Comment by zhangn1985** [comment]
@rosynirvana 楼上对网易云音乐这么熟悉，不如提个patch改一下？

**Comment by rosynirvana** [comment]
不熟悉啊，刚去看的。

提交了一个patch让url_info返回404的都直接跳过，反向会被网易找麻烦。

**Comment by rosynirvana** [comment]
outdated
