### ISSUE TITLE
i can't download any video !

### ISSUE THREAD

**Issue by wangyaoxu** [soimort/you-get#1742]
I have installed you-get via homebrew,and the vision is up-to-date,and i can visit the video through URL,but can't download  through you-get. Please help me.

like this ![error](http://wx4.sinaimg.cn/mw690/710e403bly1fdedln47lyj20qa09itch.jpg)

**Comment by rosynirvana** [comment]
首先，请加上-d flag输出debug信息
其次，请阅读you-get --help输出中关于代理的说明

**Comment by myfingerhurt** [comment]
Same here, it's not proxy issues, I'm on the outside of GFW. This happened on a windows client.

-------------------------------------------------------------------------------
you-get: version 0.4.652, a tiny downloader that scrapes the web.

>you-get -d -i 'https://www.youtube.com/watch?v=jNQXAC9IVRw'
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ["'https://www.youtube.com/watch?v=jNQXAC9IVRw'"]
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1399, in any_download
  File "src\you_get\common.py", line 1390, in url_to_module
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 826, in connect
  File "socket.py", line 689, in create_connection
  File "socket.py", line 728, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed
you-get returned -1
---------------------------------------------------------------------------

**Comment by cnbeining** [comment]
It could be some DNS or GGC issue. Can anyone else confirm this?

**Comment by rosynirvana** [comment]
I've no access to a PC at this moment. Does the windows console(cmd.exe) support quoting with single quotation mark? 

From the log we can know that common.py did't recognize ytb url so it went to [line 1402](https://github.com/soimort/you-get/blob/develop/src/you_get/common.py#L1402)

**Comment by rosynirvana** [comment]
IMHO this issue should be closed for op didn't provide any debugging info.
