### ISSUE TITLE
sohu

### ISSUE THREAD

**Issue by fyshi2016** [soimort/you-get#1743]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
# you-get -d http://tv.sohu.com/20150724/n417464435.shtml
Site:       Sohu.com
Title:      3分钟告诉你我们的地球有多渺小
Type:       MPEG-4 video (video/mp4)
Size:       10.36 MiB (10859572 Bytes)

Downloading 3分钟告诉你我们的地球有多渺小.mp4 ...
 0.0% (  0.0/ 10.4MB) ├─────────────────────────────────────────┤[1/1] you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://tv.sohu.com/20150724/n417464435.shtml']
Traceback (most recent call last):
  File "/usr/lib64/python3.4/urllib/request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib64/python3.4/http/client.py", line 871, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python3.4/socket.py", line 516, in create_connection
    raise err
  File "/usr/lib64/python3.4/socket.py", line 507, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/extractors/sohu.py", line 75, in sohu_download
    download_urls(urls, title, 'mp4', size, output_dir, refer = url, merge = merge)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 778, in download_urls
    url_save(url, output_filepath, bar, refer = refer, faker = faker, headers = headers)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 470, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 388, in url_size
    response = urlopen_with_retry(url)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 300, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 464, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.4/urllib/request.py", line 482, in _open
    '_open', req)
  File "/usr/lib64/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 1211, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.4/urllib/request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```
$ ./you-get -d 'http://tv.sohu.com/20150724/n417464435.shtml'
[DEBUG] get_response: http://tv.sohu.com/20150724/n417464435.shtml
[DEBUG] get_response: http://hot.vrs.sohu.com/vrs_flash.action?vid=2482386
[DEBUG] get_response: http://hot.vrs.sohu.com/vrs_flash.action?vid=2482386
[DEBUG] get_response: http://121.46.19.90/?prot=9&prod=flash&pt=1&file=/tv/20150724/2482386-5f8aa474-0ea3-4a3d-937b-e2c4d28aae58.mp4&new=/135/133/WqvSX8Y9Eo1rsWszx4cW6N.mp4&key=qonFzeYto9-KPKWtjfW5zb6zm_dfngLV&vid=2482386&uid=1499606338336&t=0.3636925056957485&rb=1
Site:       Sohu.com
Title:      3分钟告诉你我们的地球有多渺小
Type:       MPEG-4 video (video/mp4)
Size:       10.36 MiB (10859572 Bytes)

Downloading 3分钟告诉你我们的地球有多渺小.mp4 ...
 100% ( 10.4/ 10.4MB) ├██████████████████████████████████████████████┤[1/1]    2 MB/s
```

outdated
