### ISSUE TITLE
芒果TV的一个视频无法下载

### ISSUE THREAD

**Issue by chaosink** [soimort/you-get#1760]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
➜  ~ you-get --debug 'http://www.mgtv.com/hz/bdpz/308921/3861140.html?cxid=19sgybcmgy'
[DEBUG] get_content: http://pcweb.api.mgtv.com/player/video?video_id=None
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.mgtv.com/hz/bdpz/308921/3861140.html?cxid=19sgybcmgy']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.652-py3.5.egg/you_get/__main__.py", line 92, in main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.652-py3.5.egg/you_get/common.py", line 1422, in main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.652-py3.5.egg/you_get/common.py", line 1335, in script_main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.652-py3.5.egg/you_get/common.py", line 1151, in download_main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.652-py3.5.egg/you_get/common.py", line 1415, in any_download
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.652-py3.5.egg/you_get/extractor.py", line 41, in download_by_url
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.652-py3.5.egg/you_get/extractors/mgtv.py", line 65, in prepare
TypeError: 'NoneType' object is not subscriptable
➜  ~ 
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 开发人员辛苦了，这么好的软件！目前还不会Python，不会改源码。:+1:
> [舔 :icecream:!]

**Comment by chaosink** [comment]
你有点厉害啊，Mort，你说是不是啊。

**Comment by lirikirikiri** [comment]
[DEBUG] get_content: http://www.bilibili.com/video/av2764705/index_7.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=4243565&from=miniplay&player=1&sign=2134c2e434f1253201eba7957dd0d735
Site:       bilibili.com
Title:      【BD1080P】最终流放-银翼之法姆+总集篇+Extra【EMD】(7)-7、弱格
Type:       Flash video (video/x-flv)
Size:       346.75 MiB (363590845 Bytes)

Downloading 【BD1080P】最终流放-银翼之法姆-总集篇-Extra【EMD】(7)-7、弱格.flv ...
 0.0% (  0.0/346.7MB) ├────────────────────────────────────── 0.1% (  0.2/346.7MB) ├──────────────────────
──────────────── 0.1% (  0.5/346.7MB) ├────────────────────────────────────── 0.2% (  0.8/346.7MB) ├──────
──────────────────────────────── 0.3% (  1.0/346.7MB) ├────────────────────────────────────── 0.
% (  1.2/346.7MB) ├────────────────────────────────────── 0.4% (  1.5/346.7MB) ├────────────────────────
────────────── 0.5% (  1.8/346.7MB) ├────────────────────────────────────── 0.6% (  2.0/346.7MB) ├────────
────────────────────────────── 0.6% (  2.2/346.7MB) ├────────────────────────────────────── 0.7% (
 2.5/346.7MB) ├────────────────────────────────────── 0.8% (  2.8/346.7MB) ├──────────────────────────
──────────── 0.9% (  3.0/346.7MB) ├────────────────────────────────────── 0.9% (  3.2/346.7MB) ├──────────
──────────────────────────── 1.0% (  3.5/346.7MB) ├█───────────────────────────────────── 1.1% (  3.
/346.7MB) ├█───────────────────────────────────── 1.2% (  4.0/346.7MB) ├█───────────────────────────
────────── 1.2% (  4.2/346.7MB) ├█───────────────────────────────────── 1.3% (  4.5/346.7MB) ├█───────────
────────────────────────── 1.4% (  4.8/346.7MB) ├█───────────────────────────────────── 1.4% (  5.0/34
.7MB) ├█────────────────────────────────────────┤[1/4]    7 MB/sTraceback (most recent call last):
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\linfi\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\bilibili.py", line 181, in bilibili_download
    info_only=info_only)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\bilibili.py", line 104, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 790, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 531, in url_save
    buffer = response.read(1024 * 256)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
