### ISSUE TITLE
Failed on Youku

### ISSUE THREAD

**Issue by wuxiao356** [soimort/you-get#1763]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjYxOTQ1Mzg2MA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjYxOTQ1Mzg2MA==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489341916610126d3abb_00/st/flv/fileid/0300800D0058C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?ctype=12&ev=1&K=8b9b4817004b2a0e282c3046%26sign%3Dacce2c2355f94402be7fac33f8248461&ep=ciacE0qJV8cB4yXeiD8bYXjhJSVdXP4J9h%2BNgdIWALshQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjD1&oip=404493581&token=0504&yxon=1
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjYxOTQ1Mzg2MA==.html']
Traceback (most recent call last):
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/extractor.py", line 50, in download_by_url
    self.extract(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/extractors/youku.py", line 319, in extract
    ksegs += [i['server'] for i in json.loads(get_content(u))]
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 323, in get_content
    response = urlopen_with_retry(req)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 300, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>

```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
timeout首先考虑网络问题，我这里重复不了
```
you-get -di 'http://v.youku.com/v_show/id_XMjYxOTQ1Mzg2MA==.html'
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjYxOTQ1Mzg2MA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjYxOTQ1Mzg2MA==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0058C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=206862f8d7da3fff2412f03c%26sign%3Ddb04d05007d6d3666679999f40d58afa&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWALshQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0158C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=e88a93536e79ba852412f03c%26sign%3D4369ac4a3d5fe2285d23d74d9f506dae&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWALohQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0258C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=203b9511fa32047a2412f03c%26sign%3D5ca2c6ce3e4f815958076eff00e1c506&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWALkhQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0358C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=61bc7c566feda442261f9064%26sign%3D391530bcd1d9125d0ae8b0890419daac&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWALghQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0458C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=0f1cccde7922e57d282c308c%26sign%3D6afce4d64eded76b4e9468ec42f1028f&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWAL8hQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0558C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=c170fd36a495e30f2412f03c%26sign%3D593f78dc33d00006ba0a54da471c1f6d&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWAL4hQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0658C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=4072d90a3ec3a84a282c308c%26sign%3Dd4f44ea560f9cd1307a277b573975f52&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWAL0hQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0758C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=abc3d3457ed0a356261f9064%26sign%3D09d632bcb4f6818ace8b5666abfeb6c2&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWALwhQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0858C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=8c320913d76bc6f22412f03c%26sign%3D6375f10cc0fb4d7192717edffc537c17&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWALMhQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0958C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=cbb13db1b4e861e52412f03c%26sign%3De09b73215ed35d2c4e627c3420ce3c6a&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWALIhQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0A58C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=b82316fa778223872412f03c%26sign%3Da6158f18fd12ae8ef09bafd8e6a24d37&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWAMohQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0B58C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=d613f07f9eb3df22282c308c%26sign%3Da90d975a352a56d24eb2750b428d0fd3&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWAMkhQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0489377926038128f0e40_00/st/flv/fileid/0300800D0C58C28D2F40E1011BA6A94B72D636-61FD-3D91-E694-AD07D66D39F6?token=0544&K=6251893db17211ca282c308c%26sign%3Dde1494918c95df7774edf41ca7476033&ev=1&ctype=12&oip=1933418779&yxon=1&ep=ciacE0qKUccC4yPcgD8bb3riIXMPXP4J9h%2BNgdIWAMghQJu9kUrTsZmwO%2F5CF%2FhrAyR3Ge%2BDrNKTbEMSYfZC3xwQ3DqhOPqV%2BPnn5dwnxJd0YB9CccShslSeRjT1
site:                优酷 (Youku)
title:               愿有人陪你颠沛流离 01
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          649.9 MiB (681478130 bytes)
    # download-with: you-get --format=hd3 [URL]

    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          339.4 MiB (355911143 bytes)
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          179.8 MiB (188529208 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          86.9 MiB (91092722 bytes)
    # download-with: you-get --format=flvhd [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XMjYxOTQ1Mzg2MA==
```

**Comment by wushilin** [comment]
遇到一样的问题，网络应该不是问题可能是优酷变化了

**Comment by wushilin** [comment]
似乎是优酷屏蔽了云计算服务商的IP段。

用电信的宽带可以解析...

**Comment by soimort** [comment]
@soimort-bot test: http://v.youku.com/v_show/id_XMjYxOTQ1Mzg2MA==.html
