### ISSUE TITLE
合并视频失败

### ISSUE THREAD

**Issue by tiantian1645** [soimort/you-get#1764]
请使用`--debug`运行，并将输出粘贴在下面:

```
you-get -s 127.0.0.1:1080 -d http://bangumi.bilibili.com/anime/5789/play#98660

[DEBUG] get_content: http://bangumi.bilibili.com/anime/5789/play#98660
[DEBUG] post_content: http://bangumi.bilibili.com/web_api/get_source 
 post_data: {'episode_id': '98660'}
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=15080346&from=miniplay&player=1&sign=4fd8989f0f331a511007ed557cd6e2a8

Site:       bilibili.com
Title:      热诚传说 第二季 [98660]
Type:       Flash video (video/x-flv)
Size:       306.79 MiB (321694465 Bytes)

Downloading 热诚传说 第二季 [98660].flv ...

 0.0% (  0.0/306.8MB) ├─────────────────────────────────────────┤[1/4] 
27.7% ( 85.1/306.8MB) ├████████████─────────────────────────────┤[1/4]  110 MB/s
57.4% (176.0/306.8MB) ├████████████████████████─────────────────┤[2/4]  131 MB/s
74.2% (227.8/306.8MB) ├███████████████████████████████──────────┤[3/4]   70 MB/s
 100% (306.8/306.8MB) ├█████████████████████████████████████████┤[4/4]  100 MB/s
Merging video parts... avconv version 11.8-6:11.8-1~deb8u1, Copyright (c) 2000-2016 the Libav developers
  built on Oct  1 2016 07:16:29 with gcc 4.9.2 (Debian 4.9.2-10)
[flv @ 0x2448560] max_analyze_duration 5000000 reached
Input #0, flv, from './热诚传说 第二季 [98660][00].flv':
  Metadata:
    creator         : Coded
    metadatacreator : Yet Another Metadata Injector for FLV - Version 1.9
    hasKeyframes    : true
    hasVideo        : true
    hasAudio        : true
    hasMetadata     : true
    canSeekToEnd    : false
    datasize        : 89190853
    videosize       : 86104702
    audiosize       : 2975223
    lasttimestamp   : 397
    lastkeyframetimestamp: 394
    lastkeyframelocation: 88774893
  Duration: 00:06:37.06, start: 0.087000, bitrate: N/A
    Stream #0.0: Video: h264 (High), yuv420p, 1280x720, 1732 kb/s, 23 fps, 1k tbn, 46 tbc
    Stream #0.1: Audio: aac, 48000 Hz, stereo, fltp, 55 kb/s
[adts @ 0x24b3a40] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Output #0, mpegts, to './热诚传说 第二季 [98660][00].flv.ts':
  Metadata:
    creator         : Coded
    metadatacreator : Yet Another Metadata Injector for FLV - Version 1.9
    hasKeyframes    : true
    hasVideo        : true
    hasAudio        : true
    hasMetadata     : true
    canSeekToEnd    : false
    datasize        : 89190853
    videosize       : 86104702
    audiosize       : 2975223
    lasttimestamp   : 397
    lastkeyframetimestamp: 394
    lastkeyframelocation: 88774893
    encoder         : Lavf56.1.0
    Stream #0.0: Video: libx264, yuv420p, 1280x720, q=2-31, 1732 kb/s, 90k tbn, 1k tbc
    Stream #0.1: Audio: aac, 48000 Hz, stereo, 55 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press ctrl-c to stop encoding
frame= 4111 fps=  0 q=-1.0 size=   47034kB time=178.61 bitrate=2157.2kbits/s    
frame= 8700 fps=8699 q=-1.0 size=   90641kB time=378.22 bitrate=1963.2kbits/s    
frame= 9131 fps=8470 q=-1.0 Lsize=   94716kB time=396.96 bitrate=1954.7kbits/s    
video:83947kB audio:2669kB other streams:0kB global headers:0kB muxing overhead: 9.351673%
avconv version 11.8-6:11.8-1~deb8u1, Copyright (c) 2000-2016 the Libav developers
  built on Oct  1 2016 07:16:29 with gcc 4.9.2 (Debian 4.9.2-10)
[flv @ 0x1527560] max_analyze_duration 5000000 reached
Input #0, flv, from './热诚传说 第二季 [98660][01].flv':
  Metadata:
    creator         : Coded
    metadatacreator : Yet Another Metadata Injector for FLV - Version 1.9
    hasKeyframes    : true
    hasVideo        : true
    hasAudio        : true
    hasMetadata     : true
    canSeekToEnd    : false
    datasize        : 95328396
    videosize       : 92044225
    audiosize       : 3167407
    lasttimestamp   : 418
    lastkeyframetimestamp: 415
    lastkeyframelocation: 94663179
  Duration: 00:06:57.89, start: 0.001000, bitrate: N/A
    Stream #0.0: Video: h264 (High), yuv420p, 1280x720, 1760 kb/s, 23 fps, 1k tbn, 46 tbc
    Stream #0.1: Audio: aac, 48000 Hz, stereo, fltp, 56 kb/s
[adts @ 0x153f660] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Output #0, mpegts, to './热诚传说 第二季 [98660][01].flv.ts':
  Metadata:
    creator         : Coded
    metadatacreator : Yet Another Metadata Injector for FLV - Version 1.9
    hasKeyframes    : true
    hasVideo        : true
    hasAudio        : true
    hasMetadata     : true
    canSeekToEnd    : false
    datasize        : 95328396
    videosize       : 92044225
    audiosize       : 3167407
    lasttimestamp   : 418
    lastkeyframetimestamp: 415
    lastkeyframelocation: 94663179
    encoder         : Lavf56.1.0
    Stream #0.0: Video: libx264, yuv420p, 1280x720, q=2-31, 1760 kb/s, 90k tbn, 1k tbc
    Stream #0.1: Audio: aac, 48000 Hz, stereo, 56 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press ctrl-c to stop encoding
frame= 4286 fps=  0 q=-1.0 size=   36744kB time=186.30 bitrate=1615.7kbits/s    
frame= 7829 fps=7828 q=-1.0 size=   79960kB time=340.43 bitrate=1924.1kbits/s    
frame= 9610 fps=7384 q=-1.0 Lsize=  101230kB time=417.87 bitrate=1984.5kbits/s    
video:89740kB audio:2845kB other streams:0kB global headers:0kB muxing overhead: 9.338098%
avconv version 11.8-6:11.8-1~deb8u1, Copyright (c) 2000-2016 the Libav developers
  built on Oct  1 2016 07:16:29 with gcc 4.9.2 (Debian 4.9.2-10)
[flv @ 0x17da560] max_analyze_duration 5000000 reached
Input #0, flv, from './热诚传说 第二季 [98660][02].flv':
  Metadata:
    creator         : Coded
    metadatacreator : Yet Another Metadata Injector for FLV - Version 1.9
    hasKeyframes    : true
    hasVideo        : true
    hasAudio        : true
    hasMetadata     : true
    canSeekToEnd    : false
    datasize        : 54298914
    videosize       : 52347356
    audiosize       : 1882866
    lasttimestamp   : 246
    lastkeyframetimestamp: 241
    lastkeyframelocation: 53370372
  Duration: 00:04:05.71, start: 0.000000, bitrate: N/A
    Stream #0.0: Video: h264 (High), yuv420p, 1280x720, 1702 kb/s, 23 fps, 1k tbn, 46 tbc
    Stream #0.1: Audio: aac, 48000 Hz, stereo, fltp, 57 kb/s
[adts @ 0x1890ae0] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Output #0, mpegts, to './热诚传说 第二季 [98660][02].flv.ts':
  Metadata:
    creator         : Coded
    metadatacreator : Yet Another Metadata Injector for FLV - Version 1.9
    hasKeyframes    : true
    hasVideo        : true
    hasAudio        : true
    hasMetadata     : true
    canSeekToEnd    : false
    datasize        : 54298914
    videosize       : 52347356
    audiosize       : 1882866
    lasttimestamp   : 246
    lastkeyframetimestamp: 241
    lastkeyframelocation: 53370372
    encoder         : Lavf56.1.0
    Stream #0.0: Video: libx264, yuv420p, 1280x720, q=2-31, 1702 kb/s, 90k tbn, 1k tbc
    Stream #0.1: Audio: aac, 48000 Hz, stereo, 57 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press ctrl-c to stop encoding
frame= 3767 fps=  0 q=-1.0 size=   35079kB time=163.73 bitrate=1755.1kbits/s    
frame= 5652 fps=  0 q=-1.0 Lsize=   57670kB time=245.70 bitrate=1922.8kbits/s    
video:51034kB audio:1692kB other streams:0kB global headers:0kB muxing overhead: 9.375077%
avconv version 11.8-6:11.8-1~deb8u1, Copyright (c) 2000-2016 the Libav developers
  built on Oct  1 2016 07:16:29 with gcc 4.9.2 (Debian 4.9.2-10)
[flv @ 0x778560] max_analyze_duration 5000000 reached
Input #0, flv, from './热诚传说 第二季 [98660][03].flv':
  Metadata:
    creator         : Coded
    metadatacreator : Yet Another Metadata Injector for FLV - Version 1.9
    hasKeyframes    : true
    hasVideo        : true
    hasAudio        : true
    hasMetadata     : true
    canSeekToEnd    : true
    datasize        : 82868400
    videosize       : 80138817
    audiosize       : 2627807
    lasttimestamp   : 364
    lastkeyframetimestamp: 364
    lastkeyframelocation: 82870252
  Duration: 00:06:04.17, start: 0.000000, bitrate: N/A
    Stream #0.0: Video: h264 (High), yuv420p, 1280x720, 1758 kb/s, 23 fps, 1k tbn, 46 tbc
    Stream #0.1: Audio: aac, 48000 Hz, stereo, fltp, 53 kb/s
[adts @ 0x84a700] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Output #0, mpegts, to './热诚传说 第二季 [98660][03].flv.ts':
  Metadata:
    creator         : Coded
    metadatacreator : Yet Another Metadata Injector for FLV - Version 1.9
    hasKeyframes    : true
    hasVideo        : true
    hasAudio        : true
    hasMetadata     : true
    canSeekToEnd    : true
    datasize        : 82868400
    videosize       : 80138817
    audiosize       : 2627807
    lasttimestamp   : 364
    lastkeyframetimestamp: 364
    lastkeyframelocation: 82870252
    encoder         : Lavf56.1.0
    Stream #0.0: Video: libx264, yuv420p, 1280x720, q=2-31, 1758 kb/s, 90k tbn, 1k tbc
    Stream #0.1: Audio: aac, 48000 Hz, stereo, 53 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press ctrl-c to stop encoding
frame= 2281 fps=  0 q=-1.0 size=   34894kB time=99.22 bitrate=2881.1kbits/s    
frame= 5432 fps=5423 q=-1.0 size=   68820kB time=236.21 bitrate=2386.8kbits/s    
frame= 8375 fps=6289 q=-1.0 Lsize=   87979kB time=364.17 bitrate=1979.1kbits/s    
video:78132kB audio:2350kB other streams:0kB global headers:0kB muxing overhead: 9.316319%
avconv version 11.8-6:11.8-1~deb8u1, Copyright (c) 2000-2016 the Libav developers
  built on Oct  1 2016 07:16:29 with gcc 4.9.2 (Debian 4.9.2-10)
concat:./热诚传说 第二季 [98660][00].flv.ts|./热诚传说 第二季 [98660][01].flv.ts|./热诚传说 第二季 [98660][02].flv.ts|./热诚传说 第二季 [98660][03].flv.ts|: Protocol not found
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/5787/play#100364', 'http://bangumi.bilibili.com/anime/5789/play#98660', 'http://bangumi.bilibili.com/anime/5786/play#100376', 'http://bangumi.bilibili.com/anime/5788/play#101770']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/bilibili.py", line 135, in bilibili_download
    bilibili_download_by_cid(str(cid), title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/bilibili.py", line 104, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 811, in download_urls
    ffmpeg_concat_flv_to_mp4(parts, output_filepath)
  File "/usr/local/lib/python3.4/dist-packages/you_get/processor/ffmpeg.py", line 159, in ffmpeg_concat_flv_to_mp4
    raise
RuntimeError: No active exception to reraise
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

bilibili以前下载视频均为flv  今天突然转换成mp4  出现这个错误

**Comment by rosynirvana** [comment]
libav

换成ffmpeg吧

**Comment by tiantian1645** [comment]
用服务器下的 变成mp4了  后来单机下载又变成flv了

**Comment by rosynirvana** [comment]
现在用的这个接口拿到的xml不确定，参考 #1735

**Comment by tiantian1645** [comment]
感觉代理有点问题 毕竟国内中转

**Comment by rosynirvana** [comment]
outdated
