### ISSUE TITLE
merge video failed from le.com

### ISSUE THREAD

**Issue by teoking** [soimort/you-get#1768]
```
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.letv.com/ptv/vplay/28090021.html', '-O', '20.mp4']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/le.py", line 137, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/le.py", line 98, in letv_download_by_vid
    download_urls(urls, title, ext, size, output_dir=output_dir, merge=merge)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 830, in download_urls
    concat_mp4(parts, output_filepath)
  File "/usr/local/lib/python3.4/dist-packages/you_get/processor/join_mp4.py", line 914, in concat_mp4
    merge_mp4s(mp4s, output)
  File "/usr/local/lib/python3.4/dist-packages/you_get/processor/join_mp4.py", line 876, in merge_mp4s
    mp4s = list(map(read_mp4, ins))
  File "/usr/local/lib/python3.4/dist-packages/you_get/processor/join_mp4.py", line 717, in read_mp4
    atoms = parse_atoms(stream)
  File "/usr/local/lib/python3.4/dist-packages/you_get/processor/join_mp4.py", line 708, in parse_atoms
    atom = read_atom(stream)
  File "/usr/local/lib/python3.4/dist-packages/you_get/processor/join_mp4.py", line 700, in read_atom
    raise NotImplementedError('%s: %d' % (type, left))
NotImplementedError: b'\x00\x00\xb0\r': 1195376648
```

**Comment by rosynirvana** [comment]
重复不了
```
you-get -d 'http://www.le.com/ptv/vplay/28090021.html'
[DEBUG] get_content: http://www.le.com/ptv/vplay/28090021.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=28090021&platid=1&splatid=101&format=1&tkey=2080323754&domain=www.letv.com
Current Video Supports:
	--format 1000 <URL>
	--format 1080p <URL>
	--format 350 <URL>
	--format 720p <URL>
	--format 1300 <URL>
[DEBUG] get_content: http://play.g3proxy.lecloud.com/vod/v2/MjE0LzkvOTYvbGV0di11dHMvMTQvdmVyXzAwXzIyLTEwODg4MjA2MzgtYXZjLTMwNDg5MTctYWFjLTEyODAwMC0yNzE4MjQwLTEwODM2MDUzNDgtMzU1MDZhMjEzMGZiZmEyZTEwNGYzZDMzYzQzODJiNWYtMTQ4ODgxMDQ0MzM1NC5tcDQ=?b=3188&mmsid=63372847&tm=1489488759&key=262f96b9a430e3608073c2c31c431bff&platid=1&splatid=101&playid=0&tss=ios&vtype=52&cvid=1878992464818&payff=0&pip=ecc5ec759a7b0948151d507752e38da0&ctv=pc&m3v=1&termid=1&format=1&hwtype=un&ostype=Linux&tag=letv&sign=letv&expect=3&tn=0.4084947204323015&pay=0&iscpn=f9051&rateid=1080p
[DEBUG] get_content: http://61.53.72.55/214/9/96/letv-uts/14/ver_00_22-1088820638-avc-3048917-aac-128000-2718240-1083605348-35506a2130fbfa2e104f3d33c4382b5f-1488810443354.m3u8?crypt=33aa7f2e1829&b=3188&nlh=4096&nlt=60&bf=46&p2p=1&video_type=mp4&termid=1&tss=ios&platid=1&splatid=101&its=0&qos=3&fcheck=0&amltag=100&mltag=100&proxy=3684355097,2072663077,467476947&uid=3060929766.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&ntm=1489507200&nkey=8c7026d75fe5866bf7a52627262a1e3d&nkey2=8235aa18b158e5f7f641bc9755a22494&geo=CN-16-214-2&mmsid=63372847&tm=1489488759&key=262f96b9a430e3608073c2c31c431bff&playid=0&vtype=52&cvid=1878992464818&payff=0&ctv=pc&m3v=1&hwtype=un&ostype=Linux&tag=letv&sign=letv&tn=0.4084947204323015&pay=0&iscpn=f9051&rateid=1080p&errc=0&gn=1307&vrtmcd=107&buss=100&cips=182.114.20.230
Site:       Le.com
Title:      鸡毛飞上天20
Type:       MPEG-4 video (video/mp4)
Size:       1079.81 MiB (1132261020 Bytes)

Downloading 鸡毛飞上天20.mp4 ...
 100% (1079.8/1079.8MB) ├███████████████████████████████████┤[159/159]   13 MB/s
Merging video parts... ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.2.4 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, concat, from './鸡毛飞上天20.mp4.txt':
  Duration: N/A, start: 0.000000, bitrate: 121 kb/s
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1072, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 121 kb/s
Output #0, mp4, to './鸡毛飞上天20.mp4':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p(tv, bt709, progressive), 1920x1072, q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 121 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  450 fps=0.0 q=-1.0 size=   17041kB time=00:00:18.22 bitrate=7658.1kbits/frame=  893 fps=891 q=-1.0 size=   31853kB time=00:00:36.15 bitrate=7217.2kbits/frame= 1278 fps=833 q=-1.0 size=   45084kB time=00:00:51.50 bitrate=7170.4kbits/frame= 1780 fps=867 q=-1.0 size=   60452kB time=00:01:11.69 bitrate=6907.8kbits/frame= 2348 fps=919 q=-1.0 size=   73754kB time=00:01:34.56 bitrate=6388.9kbits/frame= 3234 fps=1049 q=-1.0 size=   86067kB time=00:02:10.09 bitrate=5419.8kbitsframe= 4433 fps=1237 q=-1.0 size=   99748kB time=00:02:58.10 bitrate=4588.0kbitsframe= 5387 fps=1309 q=-1.0 size=  111624kB time=00:03:36.58 bitrate=4221.9kbitsframe= 6208 fps=1336 q=-1.0 size=  123929kB time=00:04:09.53 bitrate=4068.5kbitsframe= 7229 fps=1405 q=-1.0 size=  134972kB time=00:04:50.55 bitrate=3805.5kbitsframe= 8151 fps=1442 q=-1.0 size=  147464kB time=00:05:27.61 bitrate=3687.4kbitsframe= 9122 fps=1482 q=-1.0 size=  160256kB time=00:06:06.49 bitrate=3582.1kbitsframe= 9985 fps=1500 q=-1.0 size=  173074kB time=00:06:41.18 bitrate=3534.1kbitsframe=10663 fps=1490 q=-1.0 size=  186862kB time=00:07:08.45 bitrate=3572.7kbitsframe=11167 fps=1459 q=-1.0 size=  199519kB time=00:07:28.72 bitrate=3642.5kbitsframe=11652 fps=1427 q=-1.0 size=  215041kB time=00:07:48.17 bitrate=3762.7kbitsframe=12338 fps=1421 q=-1.0 size=  227345kB time=00:08:15.72 bitrate=3756.9kbitsframe=13176 fps=1433 q=-1.0 size=  240487kB time=00:08:49.44 bitrate=3721.0kbitsframe=13641 fps=1407 q=-1.0 size=  252937kB time=00:09:08.08 bitrate=3780.5kbitsframe=14436 fps=1414 q=-1.0 size=  269366kB time=00:09:39.97 bitrate=3804.8kbitsframe=15404 fps=1436 q=-1.0 size=  279570kB time=00:10:18.79 bitrate=3701.1kbitsframe=16454 fps=1466 q=-1.0 size=  291036kB time=00:11:01.07 bitrate=3606.5kbitsframe=17303 fps=1475 q=-1.0 size=  304182kB time=00:11:35.03 bitrate=3585.3kbitsframe=18271 fps=1494 q=-1.0 size=  315457kB time=00:12:14.03 bitrate=3520.6kbitsframe=19486 fps=1527 q=-1.0 size=  329747kB time=00:13:02.71 bitrate=3451.2kbitsframe=20364 fps=1534 q=-1.0 size=  341003kB time=00:13:38.03 bitrate=3414.9kbitsframe=21531 fps=1562 q=-1.0 size=  353300kB time=00:14:24.88 bitrate=3346.4kbitsframe=22589 fps=1581 q=-1.0 size=  364560kB time=00:15:07.36 bitrate=3291.4kbitsframe=23463 fps=1586 q=-1.0 size=  375845kB time=00:15:42.47 bitrate=3266.9kbitsframe=24810 fps=1620 q=-1.0 size=  388107kB time=00:16:36.56 bitrate=3190.3kbitsframe=26151 fps=1653 q=-1.0 size=  398337kB time=00:17:30.41 bitrate=3106.6kbitsframe=27333 fps=1674 q=-1.0 size=  409623kB time=00:18:17.89 bitrate=3056.4kbitsframe=28661 fps=1701 q=-1.0 size=  424047kB time=00:19:11.24 bitrate=3017.4kbitsframe=29819 fps=1717 q=-1.0 size=  436233kB time=00:19:57.68 bitrate=2983.8kbitsframe=30882 fps=1729 q=-1.0 size=  449506kB time=00:20:40.31 bitrate=2968.9kbitsframe=31639 fps=1721 q=-1.0 size=  461834kB time=00:21:10.73 bitrate=2977.3kbitsframe=32603 fps=1725 q=-1.0 size=  476210kB time=00:21:49.51 bitrate=2979.1kbitsframe=33511 fps=1727 q=-1.0 size=  489640kB time=00:22:26.01 bitrate=2980.0kbitsframe=34429 fps=1728 q=-1.0 size=  503068kB time=00:23:02.75 bitrate=2980.4kbitsframe=35372 fps=1731 q=-1.0 size=  516097kB time=00:23:40.71 bitrate=2975.9kbitsframe=36572 fps=1746 q=-1.0 size=  530465kB time=00:24:28.94 bitrate=2958.3kbitsframe=37480 fps=1748 q=-1.0 size=  542053kB time=00:25:05.44 bitrate=2949.6kbitsframe=38343 fps=1747 q=-1.0 size=  555347kB time=00:25:40.08 bitrate=2954.0kbitsframe=38949 fps=1735 q=-1.0 size=  568335kB time=00:26:04.32 bitrate=2976.2kbitsframe=39602 fps=1725 q=-1.0 size=  582695kB time=00:26:30.65 bitrate=3000.9kbitsframe=40154 fps=1711 q=-1.0 size=  596048kB time=00:26:52.76 bitrate=3027.6kbitsframe=40879 fps=1705 q=-1.0 size=  612356kB time=00:27:21.81 bitrate=3055.4kbitsframe=41682 fps=1703 q=-1.0 size=  625891kB time=00:27:54.06 bitrate=3062.8kbitsframe=42734 fps=1710 q=-1.0 size=  638987kB time=00:28:36.34 bitrate=3049.8kbitsframe=43588 fps=1710 q=-1.0 size=  650264kB time=00:29:10.74 bitrate=3042.7kbitsframe=44793 fps=1722 q=-1.0 size=  665372kB time=00:29:58.99 bitrate=3029.9kbitsframe=45591 fps=1718 q=-1.0 size=  675237kB time=00:30:31.04 bitrate=3021.0kbitsframe=46778 fps=1728 q=-1.0 size=  687520kB time=00:31:18.70 bitrate=2997.9kbitsframe=47779 fps=1732 q=-1.0 size=  702498kB time=00:31:58.96 bitrate=2998.9kbitsframe=48718 fps=1735 q=-1.0 size=  715487kB time=00:32:36.79 bitrate=2995.3kbitsframe=49799 fps=1741 q=-1.0 size=  728065kB time=00:33:20.08 bitrate=2982.0kbitsframe=50866 fps=1746 q=-1.0 size=  739789kB time=00:34:02.86 bitrate=2966.6kbitsframe=51909 fps=1752 q=-1.0 size=  754009kB time=00:34:44.81 bitrate=2962.8kbitsframe=52795 fps=1751 q=-1.0 size=  766998kB time=00:35:20.37 bitrate=2963.3kbitsframe=53955 fps=1760 q=-1.0 size=  780323kB time=00:36:06.98 bitrate=2949.9kbitsframe=55057 fps=1767 q=-1.0 size=  792582kB time=00:36:51.23 bitrate=2936.3kbitsframe=56156 fps=1774 q=-1.0 size=  803134kB time=00:37:35.49 bitrate=2917.0kbitsframe=57353 fps=1782 q=-1.0 size=  816978kB time=00:38:23.37 bitrate=2905.6kbitsframe=58042 fps=1776 q=-1.0 size=  830468kB time=00:38:51.09 bitrate=2918.5kbitsframe=58915 fps=1776 q=-1.0 size=  843487kB time=00:39:26.14 bitrate=2920.3kbitsframe=59892 fps=1778 q=-1.0 size=  858860kB time=00:40:05.47 bitrate=2924.9kbitsframe=60399 fps=1766 q=-1.0 size=  871474kB time=00:40:25.74 bitrate=2943.1kbitsframe=60929 fps=1756 q=-1.0 size=  886789kB time=00:40:47.14 bitrate=2968.6kbitsframe=61525 fps=1748 q=-1.0 size=  899123kB time=00:41:10.93 bitrate=2980.9kbitsframe=62364 fps=1746 q=-1.0 size=  914461kB time=00:41:44.63 bitrate=2991.0kbitsframe=63185 fps=1745 q=-1.0 size=  927892kB time=00:42:17.64 bitrate=2995.4kbitsframe=63849 fps=1739 q=-1.0 size=  938696kB time=00:42:44.31 bitrate=2998.8kbitsframe=64582 fps=1735 q=-1.0 size=  953360kB time=00:43:13.80 bitrate=3011.0kbitsframe=64997 fps=1722 q=-1.0 size=  965653kB time=00:43:30.48 bitrate=3030.3kbitsframe=65521 fps=1713 q=-1.0 size=  981760kB time=00:43:51.57 bitrate=3056.2kbitsframe=65918 fps=1701 q=-1.0 size=  994283kB time=00:44:07.43 bitrate=3076.6kbitsframe=66309 fps=1687 q=-1.0 size= 1009459kB time=00:44:23.07 bitrate=3105.2kbitsframe=66786 fps=1678 q=-1.0 size= 1025039kB time=00:44:42.29 bitrate=3130.6kbitsframe=67331 fps=1670 q=-1.0 size= 1041494kB time=00:45:04.17 bitrate=3155.1kbitsframe=67956 fps=1665 q=-1.0 Lsize= 1057129kB time=00:45:29.33 bitrate=3172.9kbits/s speed=66.9x
video:1012963kB audio:42475kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.160151%
Merged into 鸡毛飞上天20.mp4
```
没装ffmpeg?

**Comment by teoking** [comment]
安装ffmpeg后，问题解决。
