### ISSUE TITLE
Windows 下下载失败

### ISSUE THREAD

**Issue by lirikirikiri** [soimort/you-get#1769]
执行一次命令就下载5M，然后就会卡住，强行终止后重复执行命令会接着再下5M，如此往复。

**Comment by lirikirikiri** [comment]
[DEBUG] get_content: http://www.bilibili.com/video/av2764705/index_7.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=4243565&from=miniplay&player=1&sign=2134c2e434f1253201eba7957dd0d735
Site:       bilibili.com
Title:      【BD1080P】最终流放-银翼之法姆+总集篇+Extra【EMD】(7)-7、弱格
Type:       Flash video (video/x-flv)
Size:       346.75 MiB (363590845 Bytes)

Downloading 【BD1080P】最终流放-银翼之法姆-总集篇-Extra【EMD】(7)-7、弱格.flv ...
 0.0% (  0.0/346.7MB) ├────────────────────────────────────── 0.1% (  0.2/346.7MB) ├──────────────────────
──────────────── 0.1% (  0.5/346.7MB) ├────────────────────────────────────── 0.2% (  0.8/346.7MB) ├──────
──────────────────────────────── 0.3% (  1.0/346.7MB) ├────────────────────────────────────── 0.
% (  1.2/346.7MB) ├────────────────────────────────────── 0.4% (  1.5/346.7MB) ├────────────────────────
────────────── 0.5% (  1.8/346.7MB) ├────────────────────────────────────── 0.6% (  2.0/346.7MB) ├────────
────────────────────────────── 0.6% (  2.2/346.7MB) ├────────────────────────────────────── 0.7% (
 2.5/346.7MB) ├────────────────────────────────────── 0.8% (  2.8/346.7MB) ├──────────────────────────
──────────── 0.9% (  3.0/346.7MB) ├────────────────────────────────────── 0.9% (  3.2/346.7MB) ├──────────
──────────────────────────── 1.0% (  3.5/346.7MB) ├█───────────────────────────────────── 1.1% (  3.
/346.7MB) ├█───────────────────────────────────── 1.2% (  4.0/346.7MB) ├█───────────────────────────
────────── 1.2% (  4.2/346.7MB) ├█───────────────────────────────────── 1.3% (  4.5/346.7MB) ├█───────────
────────────────────────── 1.4% (  4.8/346.7MB) ├█───────────────────────────────────── 1.4% (  5.0/34
.7MB) ├█────────────────────────────────────────┤[1/4]    7 MB/sTraceback (most recent call last):
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\linfi\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\bilibili.py", line 181, in bilibili_download
    info_only=info_only)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\bilibili.py", line 104, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 790, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 531, in url_save
    buffer = response.read(1024 * 256)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "c:\users\linfi\appdata\local\programs\python\python36-32\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt

**Comment by rosynirvana** [comment]
这个log只能看出是键盘中断了

建议放着不管看看输出的log是什么

**Comment by lirikirikiri** [comment]
下了5M后就卡住了，偶尔会以900B的速度继续下一点，没有log输出。

**Comment by rosynirvana** [comment]
估计是在ws.acgvideo.com，没什么办法
