### ISSUE TITLE
优酷解析不了

### ISSUE THREAD

**Issue by fan26a** [soimort/you-get#1771]
[root@iZ23qn31p58Z ~]# you-get -di http://v.youku.com/v_show/id_XMTY0MTI2MjI1Ng==.html?spm=a2h0j.8191423.item_XMTY0MTI2MjI1Ng==.A
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTY0MTI2MjI1Ng==&ct=10
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTY0MTI2MjI1Ng==.html?spm=a2h0j.8191423.item_XMTY0MTI2MjI1Ng==.A']
Traceback (most recent call last):
  File "/usr/local/python3/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only,json_output=json_output, caption=caption)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/extractors/youku.py", line 176, in prepare
    headers={'Referer': 'http://static.youku.com/'}
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/common.py", line 323, in get_content
    response = urlopen_with_retry(req)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/common.py", line 300, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/python3/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python3/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/local/python3/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/python3/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/local/python3/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/python3/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

**Comment by lamlam123tld3** [comment]
change
http://play.youku.com/play/get.json?ct=12&vid=
to
http://play-ali.youku.com/play/get.json?ct=12&vid=

**Comment by zhangn1985** [comment]
json['data']['stream']['segs'][0]['path']+&hd=2&myp=0&ts=195&ymovie=1&ypp=2&ctype=10&ev=1&token=0524&oip={}&ep={}&yxon=1&special=true

**Comment by lzy0699** [comment]
```
            nowtime=int(float(time.time())*1000)
            #api_url = 'http://play.youku.com/play/get.json?vid=%s&ct=10' % self.vid
            api_url = 'http://play-ali.youku.com/play/get.json?vid=%s&ct=10&time=%s' % (self.vid,nowtime)
            #api12_url = 'http://play.youku.com/play/get.json?vid=%s&ct=12' % self.vid
            api12_url = 'http://play-ali.youku.com/play/get.json?vid=%s&ct=12&time=%s' % (self.vid,nowtime)
```
还有就是现在：
data['stream'][0].keys():['media_type', 'audio_lang', 'subtitle_lang', 'drm_type', 'transfer_mode', 'milliseconds_video', 'segs', 'height', 'stream_type', 'size', 'width', 'milliseconds_audio', 'logo']
没有'stream_fileid'键

**Comment by lzy0699** [comment]
等不及更新啦，自己折腾了下，测试可行，但没有全面测试，文件地址：
https://github.com/lzy0699/you-get/blob/develop/src/you_get/extractors/youku.py

修改的地址：
https://github.com/lzy0699/you-get/commit/e3b879fd88a1b1a98e7a191cee45d0c73c8b72a1

**Comment by lzy0699** [comment]
早上起来发现不改原来的也可以正常使用了，搞得我都怀疑是不是自己眼花脑乱了。。。。。

**Comment by ccxx2c2** [comment]
感谢楼上。我用原版的那个地址下载依旧会502.
大部分时间用楼上修改后的youku下载也没问题了。
有的时候会读取到302，不知道是为什么……

**Comment by viagram** [comment]
@lzy0699 python不懂，那个client_id是从哪里获取的？

**Comment by lzy0699** [comment]
不懂的话怎么和你说得清楚。。。。你是说'fileid'吧，那是从向优酷网站发送请求所返回的json文件里面提取的。

**Comment by zglzw** [comment]
@lzy0699 我使用了你提供的youku.py可以正常下载了，但是下载下来的都是flv，不是MP4，不知道为什么

**Comment by lzy0699** [comment]
flv、MP4只是封装格式而已，自己 用ffmpeg重新封装为MP4吧。

**Comment by rosynirvana** [comment]
This issue is outdated.

**Comment by denobisipsis** [comment]
youku getsize algorithm for ct 10 encrypted string

https://github.com/denobisipsis/adownloader/blob/master/youku_getSize.php

**Comment by rosynirvana** [comment]
```getSize``` = b64decode and decrypted with \0 padding DES EBC , which you will not need actually.

```setSize``` = encrypted with \0 padding DES EBC, key is trivial to find even in the FlasCC AS3 code, and then b64encode.

```changeSize``` = first 4 char in md5 with salt ```_kservice```

Now youku player does not use ```ct=10```
