### ISSUE TITLE
How to download all the pictures from a imgur album

### ISSUE THREAD

**Issue by WilliamZY** [soimort/you-get#1774]
I tried to use the latest release to download the images from imgur albums, but seems it is not working for me
I am sure it is not the issue of the GFW, I am currently outside Mainland of China

and these are the debug info:

you-get: version 0.4.652, a tiny downloader that scrapes the web.

>you-get --debug http://imgur.com/a/Fal7h
[DEBUG] get_content: http://imgur.com/a/Fal7h
site:                Imgur
title:               None
stream:
    - format:        original
      container:     png
      size:          1.3 MiB (1338434 bytes)
    # download-with: you-get --format=original [URL]

you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://imgur.com/a/Fal7h']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1400, in any_download
  File "src\you_get\extractor.py", line 52, in download_by_url
  File "src\you_get\extractor.py", line 208, in download
  File "src\you_get\common.py", line 761, in download_urls
  File "src\you_get\util\strings.py", line 25, in get_filename
  File "html\__init__.py", line 130, in unescape
TypeError: argument of type 'NoneType' is not iterable
you-get returned -1

——————————————————————————
Is there a existing way using the current stable release to achieve that?

**Comment by WilliamZY** [comment]
ok, I get it now
