### ISSUE TITLE
Some Youtube videos fail

### ISSUE THREAD

**Issue by zhengwx11** [soimort/you-get#1777]
Example  URL: www.youtube.com/watch?v=Vd1s_w9Lvvc
I'm using you-get  0.4.652.
Checking this URL with `-i` results in ` [error] something went wrong`

This is not about one particular video, but a set of videos on youtube.

Debug log:
```
$  you-get  --debug -i https://www.youtube.com/watch?v=Vd1s_w9Lvvc
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=Vd1s_w9Lvvc
[DEBUG] get_content: https://www.youtube.com/watch?v=Vd1s_w9Lvvc
[DEBUG] get_content: https://www.youtube.com/api/timedtext?sparams=asr_langs%2Ccaps%2Cv%2Cexpire&caps=asr&asr_langs=nl%2Cpt%2Cru%2Cen%2Cfr%2Cit%2Cko%2Cde%2Cja%2Ces&signature=CEF9FF807C683FEFD7C7576FC1B2C0372AEA1FDC.814519142948C4BF670090C9C8AE65E4FEBF3CE6&v=Vd1s_w9Lvvc&key=yttt1&expire=1489923301&hl=en_US&kind=asr&lang=ja
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-en_US-vflk2jRfn/base.js
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['www.youtube.com/watch?v=Vd1s_w9Lvvc']
Traceback (most recent call last):
  File "/home/saturn/.local/lib/python3.5/site-packages/you_get/extractors/youtube.py", line 263, in prepare
    dashmpd = ytplayer_config['args']['dashmpd']
KeyError: 'dashmpd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/saturn/.local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/saturn/.local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/saturn/.local/lib/python3.5/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/saturn/.local/lib/python3.5/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/saturn/.local/lib/python3.5/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/home/saturn/.local/lib/python3.5/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/home/saturn/.local/lib/python3.5/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/home/saturn/.local/lib/python3.5/site-packages/you_get/extractors/youtube.py", line 378, in prepare
    'src': [dash_url, dash_webm_a_url],
UnboundLocalError: local variable 'dash_webm_a_url' referenced before assignment
```

**Comment by zhengwx11** [comment]
@soimort-bot 
Well， my fault..
The result is updated.

**Comment by rosynirvana** [comment]
@soimort-bot 
please test: www.youtube.com/watch?v=Vd1s_w9Lvvc

For non-dash video the code run into dash try-except branch cause the problem. An early return can fix it.
```diff
diff --git a/src/you_get/extractors/youtube.py b/src/you_get/extractors/youtube.py
index d08c848..50587f5 100644
--- a/src/you_get/extractors/youtube.py
+++ b/src/you_get/extractors/youtube.py
@@ -259,6 +259,8 @@ class YouTube(VideoExtractor):

         # Prepare DASH streams
         try:
+            if ytplayer_config['args'].get('dashmpd') is None:
+                return
             dashmpd = ytplayer_config['args']['dashmpd']
             dash_xml = parseString(get_content(dashmpd))
             for aset in dash_xml.getElementsByTagName('AdaptationSet'):
```

**Comment by soimort** [comment]
@soimort-bot test https://www.youtube.com/watch?v=Vd1s_w9Lvvc
