### ISSUE TITLE
芒果TV失效了， 2017年3月20日23:55:27

### ISSUE THREAD

**Issue by Moobusy** [soimort/you-get#1782]
在提交前，请确保您已经检查了以下内容!

- [√] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [√] 您的`you-get`为最新版.
- [√] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [√] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [√] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
C:\Users\75467>you-get --debug "http://www.mgtv.com/b/310102/3870516.html"
[DEBUG] get_content: http://v.api.mgtv.com/player/video?video_id=3870516
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.mgtv.com/b/310102/3870516.html']
Traceback (most recent call last):
  File "c:\program files\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python3\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\program files\python3\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files\python3\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\program files\python3\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\program files\python3\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "c:\program files\python3\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "c:\program files\python3\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "c:\program files\python3\lib\site-packages\you_get\extractors\mgtv.py", line 65, in prepare
    content = loads(content)
  File "c:\program files\python3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

> 芒果TV api_endpoint = 'http://v.api.mgtv.com/player/video?video_id={video_id}' 这个地址没有返回正确数据，劳驾看一下
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
#1761

```
./you-get -i 'http://www.mgtv.com/b/310102/3870516.html'
site:                芒果 (MGTV)
title:               向往的生活20170319期：李冰冰何炅乡村尬舞活力十足 冰球大战黄磊现“超强大脑”
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd
      container:     ts
      video-profile: 超清
      size:          951.2 MiB (997446408 bytes)
    # download-with: you-get --format=hd [URL]

    - format:        sd
      container:     ts
      video-profile: 高清
      size:          537.3 MiB (563350272 bytes)
    # download-with: you-get --format=sd [URL]

    - format:        ld
      container:     ts
      video-profile: 标清
      size:          304.6 MiB (319408616 bytes)
    # download-with: you-get --format=ld [URL]
```

**Comment by Moobusy** [comment]
It's not running with this url "http://www.mgtv.com/b/309803/3867679.html"

**Comment by rosynirvana** [comment]
试看几分钟的视频，把arange去掉返回的json为空
```
url = domain + re.sub( r'(\&arange\=\d+)', '', url)  #Un-Hum
```

**Comment by Moobusy** [comment]
可以了，这样的话不能脱机，有点纠结

**Comment by cnbeining** [comment]
Closed due to issue solved by PR.

**Comment by maicss** [comment]
```
you-get --debug  http://www.mgtv.com/b/312289/3882167.html
[DEBUG] get_content: http://v.api.mgtv.com/player/video?video_id=3882167
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.mgtv.com/b/312289/3882167.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/mgtv.py", line 64, in prepare
    content = loads(content)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
