### ISSUE TITLE
video cant download from vine.co 

### ISSUE THREAD

**Issue by jiych** [soimort/you-get#1786]
$ you-get -ui 'https://vine.co/v/iFDvMVePn7n'
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
jack@avatar ~/tmp$ you-get -dui 'https://vine.co/v/iFDvMVePn7n'
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://vine.co/v/iFDvMVePn7n']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/extractors/vine.py", line 14, in vine_download
    stream = r1(r'"videoUrl":"([^"]+)"', html).replace('\\/', '/')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by rosynirvana** [comment]
1. from 'https://vine.co/v/iFDvMVePn7n' we can get iFDvMVePn7n;
2. str 'iFDvMVePn7n' maps to url 'https://archive.vine.co/posts/iFDvMVePn7n.json';
3. in the returned json there are "videoLowURL" "videoUrl" "videoDashUrl" and "videoDashUrl" should be the one with best quality.

**Comment by soimort** [comment]
Fixed by #1787.
