### ISSUE TITLE
能否支持下载百度网盘的视频

### ISSUE THREAD

**Issue by omaidb** [soimort/you-get#1790]
百度网盘里存了很多电影，在线可以播放，但是我习惯多倍速播放，想下载下来，但是网盘下载速度很慢，刚才试了下，但是不能，不知道能不能实现
you-get --debug https://pan.baidu.com/play/video#video/path=%2FBT%2FGame.of.Thrones.S01.2011.BluRay.720p.x264.DTS-CnSCG%2FGame.Of.Thrones.S01.E02.2011.BluRay.720p.x264.DTS-CnSCG.mkv&t=-1
[1] 70910
omaidbdeMacBook-Air:~ omaidb$ Generating cookies...
[DEBUG] get_content: http://pan.baidu.com/play/video#video/path=%2FBT%2FGame.of.Thrones.S01.2011.BluRay.720p.x264.DTS-CnSCG%2FGame.Of.Thrones.S01.E02.2011.BluRay.720p.x264.DTS-CnSCG.mkv
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://pan.baidu.com/play/video#video/path=%2FBT%2FGame.of.Thrones.S01.2011.BluRay.720p.x264.DTS-CnSCG%2FGame.Of.Thrones.S01.E02.2011.BluRay.720p.x264.DTS-CnSCG.mkv']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/extractors/baidu.py", line 108, in baidu_download
    real_url, title, ext, size = baidu_pan_download(url)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/extractors/baidu.py", line 183, in baidu_pan_download
    raise AssertionError("Share not found or canceled: %s" % url)
AssertionError: Share not found or canceled: http://pan.baidu.com/play/video#video/path=%2FBT%2FGame.of.Thrones.S01.2011.BluRay.720p.x264.DTS-CnSCG%2FGame.Of.Thrones.S01.E02.2011.BluRay.720p.x264.DTS-CnSCG.mkv

**Comment by rosynirvana** [comment]
1. url 里含有某些字符的时候需要加引号
```
you-get -di 'https://pan.baidu.com/play/video#video/path=%2FBT%2FGame.of.Thrones.S01.2011.BluRay.720p.x264.DTS-CnSCG%2FGame.Of.Thrones.S01.E02.2011.BluRay.720p.x264.DTS-CnSCG.mkv&t=-1'
```
2. 这个视频被取消分享了或者删了，浏览器里看不了，所以得到的log是这样的
```
AssertionError: Share not found or canceled: http://pan.baidu.com/play/video#video/path=%2FBT%2FGame.of.Thrones.S01.2011.BluRay.720p.x264.DTS-CnSCG%2FGame.Of.Thrones.S01.E02.2011.BluRay.720p.x264.DTS-CnSCG.mkv&t=-1
```

3. 下载速度慢是没办法的，今年百度盘的限速策略是一个ip 100KiBps

**Comment by cnbeining** [comment]
我们没有Baidu PCS的key 所以没什么好办法。

**Comment by rosynirvana** [comment]
现在支持百度盘
那个链接是你的账户私有的所以没法访问到，uri本身没有足够的信息

**Comment by GatoY** [comment]
如何加入自己的Cookie以便下载私有链接呢？
