### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by FLEM1NGTON** [soimort/you-get#1791]
![image](https://cloud.githubusercontent.com/assets/26676574/24325290/760b0220-11d0-11e7-9bf8-3ad6240a2107.png)
I want to get the latest develop branch,but i can't do it via PIP right?(I installed you-get via PIP)

**Comment by cnbeining** [comment]
您需要有git安装配置好 可以在命令行直接调用。

2017年3月25日 下午3:06，"FLEM1NGTON" <notifications@github.com>写道：

**Comment by rosynirvana** [comment]
From the main page
>In order to get the latest develop branch without messing up the PIP, you can try:
```
$ pip3 install --upgrade git+https://github.com/soimort/you-get@develop
```

**Comment by FLEM1NGTON** [comment]
thanks
![image](https://cloud.githubusercontent.com/assets/26676574/24328634/ed19eaca-1220-11e7-99a4-719c1f296370.png)
I did upgrade successfully ,but how can i get the latest feature?
I noticed that someone has already reported the issue and it's been solved,but i still can't download video from mgtv.com
成功更新了版本，但是我怎么获得那些已经解决了的新特性（貌似已经有人提出过芒果tv的问题）现在我还是不能从mgtv.com下载视频- -
求助...
http://www.mgtv.com/b/308921/3878651.html

```
> C:\Users\Mayer>you-get --debug http://www.mgtv.com/b/308921/3878651.html
[DEBUG] get_content: http://pcweb.api.mgtv.com/player/video?video_id=3878651
[DEBUG] get_content: http://disp.titan.mgtv.com/vod.do?pm=h5KD14lwG78jSmz_i~JlxViqk~Js5zWmOLaq~kIPZx9hOhXmXicuffbXT_e~405~wkIqQhCuTzhU991s9MiFzLy32s1kE8SsusTJhWCFLUfXOizkhqcI8mom~ZFgzwbm52IdXIoaBATgDhUiLOIk24AtJjDaXaXWWcPDhL1Quk9OYrvOEjZKH1aZtWwiTUE2EYey8PrscbfzF2SN9PuQqeB2k~0NIyOV&fid=B22A8B2453C302936AB16172B9204E04&gsid=f89cb6f3-8ec9-41f0-85c4-9d2eb54508c5
[DEBUG] get_content: http://202.109.167.163/c1/2017/03/25_0/C3FEFBC230B00082F7D98BF1B624A4B8_20170325_1_1_1581_mp4/E4BD7EE2F6F1B5DD41DC622EE2B1E901.m3u8?t=58d7b715&pno=1042000&sign=bb952973c881a064c974635d2ff868f3&win=300&srgid=253&urgid=1366&srgids=253&nid=1975&payload=usertoken%3Dhit%3D2%5Eruip%3D2936474319&rdur=21600&limitrate=0&fid=C3FEFBC230B00082F7D98BF1B624A4B8&ver=0x03&uuid=899e501bd582440bbc776880e214520c&arange=0
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.mgtv.com/b/308921/3878651.html']
Traceback (most recent call last):
  File "C:\Python34\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "C:\Python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1422, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1335, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1151, in download_main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1415, in any_download
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractors\mgtv.py", line 81, in prepare
    m3u8_url, m3u8_size, segment_list_this = self.get_mgtv_real_url(url)
  File "C:\Python34\lib\site-packages\you_get\extractors\mgtv.py", line 48, in get_mgtv_real_url
    content = get_content(content['info'])  #get the REAL M3U url, maybe to be changed later?
  File "C:\Python34\lib\site-packages\you_get\common.py", line 332, in get_content
    response = urlopen_with_retry(req)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 309, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

**Comment by rosynirvana** [comment]
flash版的api变了一点
```
ver:0.2.24016
pm:h5KD14lwG78jSmz_i~JlxViqk~Js5zWmOLaq~kIPZx9hOhXmXicuffbXT_e~405~wkIqQhCuTzhU991s9MiFzLy32s1kE8SsusTJhWCFLUfXOizkhqcI8mom~ZFgzwbm52IdXIoaBATgDhUiLOIk24AtJjDaXaXWWcPDhL1Quk9OYrvOEjZKH1aZtWwiTUE2EYey8PrscbfzF2SN9PuQqeB2k~0NIyOV
arange:0
fid:B22A8B2453C302936AB16172B9204E04
gsid:85218ba6-4a25-438a-bf95-41bc9bf1f054
chk:cc0c82af84d6b84b7579f1612c5c96ce
ld:1490509850040
```

多出来个chk和id
估计是加时间戳算md5

原来的api用的不知道是不是flash版这个接口

**Comment by zhangn1985** [comment]
这个视频的高清，和标清还是可以拿到的。

**Comment by rosynirvana** [comment]
```python
#fid is in the url
import time
import hashlib
import binascii

def calc_params(fid, t=None):
    if t is None:
        t = str(int(time.time() * 1000))

    step = str(int(int(t) / 600000))

    ver = '0.2.' + str(binascii.crc32((step + fid[0] + fid[7]).encode('utf8')) & 0xFFFFFFFF)[0:5]

    chk = hashlib.md5((step + '12345678' + fid + '000').encode('utf8')).hexdigest()

    print('{0} {1} {2}'.format(t, ver, chk))

calc_params('B22A8B2453C302936AB16172B9204E04', '1490509850040')
```

挖出来不难

**Comment by rosynirvana** [comment]
找了几个例子，arange好像是表示试看长度的？
免费则 arange == 0，不然arange是5分钟左右。#1782 的例子去掉arange返回结果是空的。
现在arange不该被去掉？
现在是：
```python
url = domain + re.sub( r'(\&arange\=\d+)', '', url)  #Un-Hum
```

---

In the few examples I've tested params ```arange``` seems to be the time of free segments, in seconds. It's 0 if the whole video is free. In #1782 one non-free video returned empty json with ```arange``` removed.
Perhaps we should not remove ```arange``` ?
Now the impl is
```python
url = domain + re.sub( r'(\&arange\=\d+)', '', url)  #Un-Hum
```

**Comment by tmhvnn** [comment]
How to download video from mgtv?
I can download *.TS from IDM only :(
