### ISSUE TITLE
Download stopped after a few files has been downloaded (ie. want to download 100 files but after 10 files, the download fails)

### ISSUE THREAD

**Issue by chenyiranru** [soimort/you-get#1799]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [X ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ √] 您的`you-get`为最新版.
- [√ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [√ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ √] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:
I:\Music\163>you-get -d http://music.163.com/#/playlist?id=636837036
```
[DEBUG] get_content: http://music.163.com/api/playlist/detail?id=636837036&csrf_token=
Skipping ./当文学遇见音乐\cover.jpg: file already exists

Site:       163.com
Title:      00_32. 当你老了
Type:       MP3 (audio/mpeg)
Size:       11.87 MiB (12441766 Bytes)

Skipping ./当文学遇见音乐\00_32. 当你老了.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=26090100&lv=-1&csrf_token=
Saving 00_32. 当你老了.lrc ...Done.
Site:       163.com
Title:      01_8. 现代病启示录
Type:       MP3 (audio/mpeg)
Size:       7.75 MiB (8130395 Bytes)

Skipping ./当文学遇见音乐\01_8. 现代病启示录.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=32364022&lv=-1&csrf_token=
Saving 01_8. 现代病启示录.lrc ...Done.
Site:       163.com
Title:      02_13. 追忆似水年华
Type:       MP3 (audio/mpeg)
Size:       11.08 MiB (11620711 Bytes)

Skipping ./当文学遇见音乐\02_13. 追忆似水年华.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=69325&lv=-1&csrf_token=
Saving 02_13. 追忆似水年华.lrc ...Done.
Site:       163.com
Title:      03_7. 流浪的红舞鞋
Type:       MP3 (audio/mpeg)
Size:       9.8 MiB (10271873 Bytes)

Skipping ./当文学遇见音乐\03_7. 流浪的红舞鞋.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=299515&lv=-1&csrf_token=
Saving 03_7. 流浪的红舞鞋.lrc ...Done.
Site:       163.com
Title:      04_8. 开到荼蘼
Type:       MP3 (audio/mpeg)
Size:       12.11 MiB (12698836 Bytes)

Skipping ./当文学遇见音乐\04_8. 开到荼蘼.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=299427&lv=-1&csrf_token=
Saving 04_8. 开到荼蘼.lrc ...Done.
Site:       163.com
Title:      05_1. 寒武纪
Type:       MP3 (audio/mpeg)
Size:       12.1 MiB (12685104 Bytes)

Skipping ./当文学遇见音乐\05_1. 寒武纪.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=299588&lv=-1&csrf_token=
Saving 05_1. 寒武纪.lrc ...Done.
Site:       163.com
Title:      06_5. 百年孤寂
Type:       MP3 (audio/mpeg)
Size:       12.14 MiB (12732523 Bytes)

Skipping ./当文学遇见音乐\06_5. 百年孤寂.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=299650&lv=-1&csrf_token=
Saving 06_5. 百年孤寂.lrc ...Done.
Site:       163.com
Title:      07_19. 守望麦田
Type:       MP3 (audio/mpeg)
Size:       12.24 MiB (12836762 Bytes)

Skipping ./当文学遇见音乐\07_19. 守望麦田.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=299454&lv=-1&csrf_token=
Saving 07_19. 守望麦田.lrc ...Done.
Site:       163.com
Title:      08_10. 笑忘书
Type:       MP3 (audio/mpeg)
Size:       10.22 MiB (10719651 Bytes)

Skipping ./当文学遇见音乐\08_10. 笑忘书.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=299601&lv=-1&csrf_token=
Saving 08_10. 笑忘书.lrc ...Done.
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/playlist?id=636837036']
Traceback (most recent call last):
  File "d:\program files\anaconda\lib\urllib\request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "d:\program files\anaconda\lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "d:\program files\anaconda\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "d:\program files\anaconda\lib\http\client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "d:\program files\anaconda\lib\http\client.py", line 911, in _send_output
    self.send(msg)
  File "d:\program files\anaconda\lib\http\client.py", line 854, in send
    self.connect()
  File "d:\program files\anaconda\lib\http\client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "d:\program files\anaconda\lib\socket.py", line 711, in create_connection
    raise err
  File "d:\program files\anaconda\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\program files\anaconda\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\ANACONDA\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files\anaconda\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\extractors\netease.py", line 133, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\extractors\netease.py", line 61, in netease_cloud_music_download
    netease_song_download(i, output_dir=new_dir, info_only=info_only, playlist_prefix=playlist_prefix)
  File "d:\program files\anaconda\lib\site-packages\you_get\extractors\netease.py", line 120, in netease_song_download
    output_dir=output_dir, info_only=info_only)
  File "d:\program files\anaconda\lib\site-packages\you_get\extractors\netease.py", line 123, in netease_download_common
    songtype, ext, size = url_info(url_best)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 411, in url_info
    response = urlopen_with_retry(request.Request(url))
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 300, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "d:\program files\anaconda\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "d:\program files\anaconda\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "d:\program files\anaconda\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "d:\program files\anaconda\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\program files\anaconda\lib\urllib\request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "d:\program files\anaconda\lib\urllib\request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
大神们好！ 我刚刚使用不久， 发现试图同时下载一个网站上的很多歌曲的时候， 会出现它下载一小部分然后报错的现象，上面的debug里写的 file already exist是因为我已经下载过了，但重新运行code的话，每次就卡在这个地方。 因为我在美国， 网易云音乐是不能听的， 所以不确定是否能在浏览器或者移动端听到。 不过因为这个现象并不是只在这一个歌单出现，我尝试了很多歌单，都会有这个现象，所以我认为不是他网站的资源问题。 谢谢了！！
> [舔 :icecream:!]

**Comment by chenyiranru** [comment]
Hi! Thank you for helping! I don't know if it's because of the network. I'm able to download until 笑忘书 too. But right after that the error pop up. Are you able to download all of the files in that song-list please?
