### ISSUE TITLE
--json option error

### ISSUE THREAD

**Issue by jianghua** [soimort/you-get#1807]
[root@iZ25p8gtt2gZ test]# ./you-get-develop/you-get --json -d http://www.bilibili.com/video/av9433035/
[DEBUG] get_content: http://www.bilibili.com/video/av9433035/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=15588946&from=miniplay&player=1&sign=a3c68187c4f5df6f542a47e201ac364e
[DEBUG] url_info: http://cn-sdjn-cu-v-05.acgvideo.com/vg5/7/39/15588946-1.flv?expires=1490858100&platform=pc&ssig=RSZwFM6cdysxwKsyxHewJw&oi=2067331022&nfa=zewukGbkdeYAV6tVxJRokA==&dynamic=1
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av9433035/']
Traceback (most recent call last):
  File "./you-get-develop/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/you-get-develop/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/you-get-develop/src/you_get/common.py", line 1422, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/you-get-develop/src/you_get/common.py", line 1335, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/you-get-develop/src/you_get/common.py", line 1151, in download_main
    download(url, **kwargs)
  File "/you-get-develop/src/you_get/common.py", line 1415, in any_download
    m.download(url, **kwargs)
  File "/you-get-develop/src/you_get/extractors/bilibili.py", line 181, in bilibili_download
    info_only=info_only)
  File "/you-get-develop/src/you_get/extractors/bilibili.py", line 104, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "/you-get-develop/src/you_get/common.py", line 758, in download_urls
    json_output_.download_urls(urls=urls, title=title, ext=ext, total_size=total_size, refer=refer)
  File "/you-get-develop/src/you_get/json_output.py", line 54, in download_urls
    output(ve)
  File "/you-get-develop/src/you_get/json_output.py", line 15, in output
    if ve.audiolang:
AttributeError: 'VideoExtractor' object has no attribute 'audiolang'

```
A temporary solution:
Edit src/you_get/json_output.py delete line 14-18
```

**Comment by jianghua** [comment]
add --json option and test

**Comment by rosynirvana** [comment]
also works for me (lastest release)
```
you-get -d --json 'http://www.bilibili.comvideo/av9433035/'
[DEBUG] get_content: http://www.bilibili.com/video/av9433035/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=15588946&from=miniplay&player=1&sign=a3c68187c4f5df6f542a47e201ac364e
{
    "site": "bilibili.com",
    "streams": {
        "__default__": {
            "container": "flv",
            "size": null,
            "src": [
                "http://cn-hnjz-cu-v-01.acgvideo.com/vg5/7/29/15588946-1.flv?expires=1490859000&platform=pc&ssig=P-sZilvEBbgOO0MTJIwdHw&oi=2100146498&nfa=JegTJDC+uC6hmp9MGMEVog==&dynamic=1"
            ],
            "video_profile": "__default__"
        }
    },
    "title": "FGO乱入到Fate系列动画中会是什么效果",
    "url": null
}
```

**Comment by soimort** [comment]
New release is on the way.
