### ISSUE TITLE
problem downloading from QQ music

### ISSUE THREAD

**Issue by chenyiranru** [soimort/you-get#1809]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
I:\Music\qq\zhangliangying>you-get -d https://y.qq.com/n/yqq/album/0032UyVG4NTKZg.html
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://y.qq.com/n/yqq/album/0032UyVG4NTKZg.html']
Traceback (most recent call last):
  File "d:\program files\anaconda\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\ANACONDA\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files\anaconda\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "d:\program files\anaconda\lib\site-packages\you_get\extractors\qq.py", line 111, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "d:\program files\anaconda\lib\site-packages\you_get\extractors\qq.py", line 10, in qq_download_by_vid
    info_api = 'http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=' + vid
TypeError: Can't convert 'NoneType' object to str implicitly
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
Is this because I'm in the US?
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
因为没人给 y.qq.com/n/yqq/album 写解析器，代码又没能正确提示。

**Comment by chenyiranru** [comment]
原来如此..所以如果想在qq音乐下载的话，不能去专辑，要去歌单就可以了吗？

**Comment by rosynirvana** [comment]
#128
应该是不行

y.qq.com没专用的解析代码，fall back到通用的上一般来说是不行的

**Comment by rosynirvana** [comment]
dup #128
