### ISSUE TITLE
  Download NetEase cloud music when the wrong

### ISSUE THREAD

**Issue by ranshao0121** [soimort/you-get#1811]
Hello, thank you very much for your software. I downloaded the NetEase cloud music when the wrong report. This music is the existence of copyright issues, can not download!

The following is a Chinese description:
你好,非常感谢你的软件.我在下载网易云音乐的时候报错.这个音乐是存在版权问题,不能下载.不知道能否能修复.之前是可以用的.多谢!

============================================

you-get: version 0.4.652, a tiny downloader that scrapes the web.

>you-get http://music.163.com/#/m/song?id=5280334&userid=260650194
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
'userid' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

>
==============================================

**Comment by ranshao0121** [comment]
Sorry, this is the content of debug

====================================================

you-get: version 0.4.652, a tiny downloader that scrapes the web.

>you-get --debug http://music.163.com/#/m/song?id=5280334&userid=260650194
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=5280334&ids=[52803
34]&csrf_token=
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/m/song?id=5280334']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1400, in any_download
  File "src\you_get\extractors\netease.py", line 133, in netease_download
  File "src\you_get\extractors\netease.py", line 70, in netease_cloud_music_down
load
  File "src\you_get\extractors\netease.py", line 120, in netease_song_download
  File "src\you_get\extractors\netease.py", line 123, in netease_download_common

  File "src\you_get\common.py", line 411, in url_info
  File "src\you_get\common.py", line 300, in urlopen_with_retry
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 471, in open
  File "urllib\request.py", line 581, in http_response
  File "urllib\request.py", line 509, in error
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 589, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
you-get returned -1
'userid' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

>
====================================================

**Comment by rosynirvana** [comment]
现在这个接口能拿到的，应该不会比网页上能播放的更多
另外命令行的&要转义，或者给整个url加引号

**Comment by ranshao0121** [comment]
首先多谢@rosynirvana 你的回答,不过我不太理解你的意思.引号是指双引号还是单引号.我都试过了.

**Comment by rosynirvana** [comment]
1. 从某些issue来看，cmd.exe大概只支持双引号。不用引号传递给you-get的url是不正确的。但是你可能不关心，因为这个url拿不到数据，无论是网页端还是you-get。

2. 网易云音乐有几个不同的接口，android app，iOS app，网页端…… 你用浏览器去开，用的是网页端的接口去访问。现在you-get用的应该是一个很早之前有人公布的接口，根据之前的issues，you-get这个接口拿到的应该只会比网页端接口拿到的少。

总结：网页上能播的，是否能用you-get下载？不一定，根据之前的issues有些不可以；网页上不能播的，是否能用you-get下载？未知，但是根据上一条推测，不能下的可能性更大。

**Comment by ranshao0121** [comment]
多谢你的解释

**Comment by rosynirvana** [comment]
outdated
