### ISSUE TITLE
土豆无法下载

### ISSUE THREAD

**Issue by lsycxyj** [soimort/you-get#1812]
直接打开能播，也不是收费视频，下载报错
python you-get --debug http://www.tudou.com/albumplay/hoPXCN2y4Po/E10gwfNvScE.html

```
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "J:\Youtube\YouGet/src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "J:\Youtube\YouGet/src\you_get\common.py", line 1422, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "J:\Youtube\YouGet/src\you_get\common.py", line 1335, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "J:\Youtube\YouGet/src\you_get\common.py", line 1151, in download_main
    download(url, **kwargs)
  File "J:\Youtube\YouGet/src\you_get\common.py", line 1415, in any_download
    m.download(url, **kwargs)
  File "J:\Youtube\YouGet/src\you_get\extractors\tudou.py", line 45, in tudou_download
    html = get_decoded_html(url)
  File "J:\Youtube\YouGet/src\you_get\common.py", line 290, in get_decoded_html
    response = get_response(url, faker)
  File "J:\Youtube\YouGet/src\you_get\common.py", line 269, in get_response
    response = request.urlopen(url)
  File "d:\Python\Python35-32\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "d:\Python\Python35-32\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "d:\Python\Python35-32\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "d:\Python\Python35-32\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\Python\Python35-32\lib\urllib\request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "d:\Python\Python35-32\lib\urllib\request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝， 无法连接。>
```

**Comment by rosynirvana** [comment]
```
you-get -di 'http://www.tudou.com/albumplay/hoPXCN2y4Po/E10gwfNvScE.html'
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XNDYyMTQ5OTYw&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XNDYyMTQ5OTYw&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0490886997080126bdab3_00/st/mp4/fileid/030008040050EDB70CD86C05DEE81BCF0A4C21-892F-C881-BD6F-1FC57B7CDFAE?yxon=1&ep=ciadGkGFUMcJ4iPXiD8bYX62JSUMXP4J9h%2BFidJmALshSJ3L6znRtOm4SIxCE41sByoHYpiHq6HjGUIVYfhKqx4QrEagOPqSivaV5awlt5UHFB5FBrumwVSeRjD1&K=bcf054a3a80bfe62282c3c02%26sign%3D20d61e2749f6d629010b29d032caff0a&oip=2100146498&token=0504&ev=1&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0490886997080126bdab3_00/st/mp4/fileid/030008040150EDB70CD86C05DEE81BCF0A4C21-892F-C881-BD6F-1FC57B7CDFAE?yxon=1&ep=ciadGkGFUMcJ4iPXiD8bYX62JSUMXP4J9h%2BFidJmALohSJ3L6znRtOm4SIxCE41sByoHYpiHq6HjGUIVYfhKqx4QrEagOPqSivaV5awlt5UHFB5FBrumwVSeRjD1&K=ef3da97ea82c452b2412f525%26sign%3D935084a0636bcb72c7a45b088c926a34&oip=2100146498&token=0504&ev=1&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0490886997080126bdab3_00/st/mp4/fileid/030008040250EDB70CD86C05DEE81BCF0A4C21-892F-C881-BD6F-1FC57B7CDFAE?yxon=1&ep=ciadGkGFUMcJ4iPXiD8bYX62JSUMXP4J9h%2BFidJmALkhSJ3L6znRtOm4SIxCE41sByoHYpiHq6HjGUIVYfhKqx4QrEagOPqSivaV5awlt5UHFB5FBrumwVSeRjD1&K=46e6600fbd00c9a4261f9894%26sign%3D7e861d2b5584d013922778716ba1747d&oip=2100146498&token=0504&ev=1&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/0490886997080126bdab3_00/st/mp4/fileid/030008040350EDB70CD86C05DEE81BCF0A4C21-892F-C881-BD6F-1FC57B7CDFAE?yxon=1&ep=ciadGkGFUMcJ4iPXiD8bYX62JSUMXP4J9h%2BFidJmALghSJ3L6znRtOm4SIxCE41sByoHYpiHq6HjGUIVYfhKqx4QrEagOPqSivaV5awlt5UHFB5FBrumwVSeRjD1&K=ef7253ec1e286e042412f525%26sign%3Db79d040976a9a18ed962e2881eac1bd5&oip=2100146498&token=0504&ev=1&ctype=12
site:                优酷 (Youku)
title:               第001话 飞向高空
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          95.9 MiB (100580037 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          50.0 MiB (52460020 bytes)
    # download-with: you-get --format=flvhd [URL]

audio-languages:
    - lang:          日语
      download-url:  http://v.youku.com/v_show/id_XNDYyMTQ5OTYw
```

works for me

**Comment by lsycxyj** [comment]
BTW, I'm using windows 10 64bit and Python 3.5.2-32

**Comment by lsycxyj** [comment]
I found something else changed my system's proxy setting. Closed.
