### ISSUE TITLE
bug when download video from youku.com. Please check it

### ISSUE THREAD

**Issue by daucongluu** [soimort/you-get#1813]
>you-get -i http://v.youku.com/v_show/id_XMTg3NzA5NzcwOA==.html?spm=a2h0j.819142
3.item_XMTg3NzA5NzcwOA==.A
site:                ä¼˜é…· (Youku)
title:               æžå“å®¶ä¸ 31
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          1021.9 MiB (1071559037 bytes)
    # download-with: you-get --format=hd3 [URL]

    - format:        hd2
      container:     flv
      video-profile: è¶…æ¸…
      size:          533.1 MiB (559027304 bytes)
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: é«˜æ¸…
      size:          282.2 MiB (295930596 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: æ ‡æ¸…
      size:          136.4 MiB (142983407 bytes)
    # download-with: you-get --format=flvhd [URL]

audio-languages:
    - lang:          å›½è¯­
      download-url:  http://v.youku.com/v_show/id_XMTg3NzA5NzcwOA==

>you-get --format=hd2 http://v.youku.com/v_show/id_XMTg3NzA5NzcwOA==.html?spm=a2
h0j.8191423.item_XMTg3NzA5NzcwOA==.A
site:                ä¼˜é…· (Youku)
title:               æžå“å®¶ä¸ 31
stream:
    - format:        hd2
      container:     flv
      video-profile: è¶…æ¸…
      size:          533.1 MiB (559027304 bytes)
    # download-with: you-get --format=hd2 [URL]

audio-languages:
    - lang:          å›½è¯­
      download-url:  http://v.youku.com/v_show/id_XMTg3NzA5NzcwOA==

you-get: [Failed] Cannot extract video source.
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

>you-get -d http://v.youku.com/v_show/id_XMTg3NzA5NzcwOA==.html?spm=a2h0j.819142
3.item_XMTg3NzA5NzcwOA==.A
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTg3NzA5NzcwOA==&c
t=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTg3NzA5NzcwOA==&c
t=12
site:                ä¼˜é…· (Youku)
title:               æžå“å®¶ä¸ 31
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          1021.9 MiB (1071559037 bytes)
    # download-with: you-get --format=hd3 [URL]

audio-languages:
    - lang:          å›½è¯­
      download-url:  http://v.youku.com/v_show/id_XMTg3NzA5NzcwOA==

you-get: [Failed] Cannot extract video source.
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTg3NzA5NzcwOA==.html?spm=a2h0j.8191423
.item_XMTg3NzA5NzcwOA==.A']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1400, in any_download
  File "src\you_get\extractor.py", line 52, in download_by_url
  File "src\you_get\extractor.py", line 203, in download
  File "src\you_get\util\log.py", line 98, in wtf
NameError: name 'exit' is not defined
you-get returned -1

**Comment by daucongluu** [comment]
you can teamview check it for me. thank you

**Comment by daucongluu** [comment]
you can check download this and post log for me thankyou.
