### ISSUE TITLE
乐视优酷获取"可用画质与格式"错误

### ISSUE THREAD

**Issue by iamty7** [soimort/you-get#1830]
乐视：
```
you-get -d -i 'http://www.le.com/ptv/vplay/27422674.html'
[DEBUG] get_content: http://www.le.com/ptv/vplay/27422674.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=27422674&platid=1&splatid=101&format=1&tkey=3939003562&domain=www.letv.com
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/27422674.html']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/extractors/le.py", line 137, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/extractors/le.py", line 90, in letv_download_by_vid
    ext , urls = video_info(vid,**kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/extractors/le.py", line 61, in video_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'

```

优酷：
```
you-get -d -i 'http://v.youku.com/v_show/id_XMjY3OTg5MzU2NA\=\=.html\?from\=y1.3-idx-beta-1519-23042.230771.1-1'
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjY3OTg5MzU2NA&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjY3OTg5MzU2NA&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049127702212112983c94_00/st/flv/fileid/030080260058DF95A3F9BA2BEEFCF9120297F7-EEB4-7808-0C4E-A4314F86023E?ctype=12&ev=1&K=7fdf374ae189b352261f9ab2%26sign%3Dba2d052f3a9578f89dc705eeb24681c9&ep=ciadG0uKUc4C5yLdiT8bbiThJ34LXP4J9h%2BNgdBkALshQJzJkDugxOu5PI5AZIxsBFFwGerzq9LubTYTYYU222wQ2EaoMfrgjfSW5dxXx5EEEBEwcs%2FUwVSeRjD4&oip=3723318150&token=0509&yxon=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049127702212112983c94_00/st/flv/fileid/030080260158DF95A3F9BA2BEEFCF9120297F7-EEB4-7808-0C4E-A4314F86023E?ctype=12&ev=1&K=b6700afc489711b22412f66a%26sign%3D924976882bf7e03fc21b05fe34409271&ep=ciadG0uKUc4C5yLdiT8bbiThJ34LXP4J9h%2BNgdBkALohQJzJkDugxOu5PI5AZIxsBFFwGerzq9LubTYTYYU222wQ2EaoMfrgjfSW5dxXx5EEEBEwcs%2FUwVSeRjD4&oip=3723318150&token=0509&yxon=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049127702212112983c94_00/st/flv/fileid/030080260258DF95A3F9BA2BEEFCF9120297F7-EEB4-7808-0C4E-A4314F86023E?ctype=12&ev=1&K=6b36b8e78abd1fb32412f66a%26sign%3D3c7e1fa0d455cd8394ab6d3aeb58ae40&ep=ciadG0uKUc4C5yLdiT8bbiThJ34LXP4J9h%2BNgdBkALkhQJzJkDugxOu5PI5AZIxsBFFwGerzq9LubTYTYYU222wQ2EaoMfrgjfSW5dxXx5EEEBEwcs%2FUwVSeRjD4&oip=3723318150&token=0509&yxon=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049127702212112983c94_00/st/flv/fileid/030080260358DF95A3F9BA2BEEFCF9120297F7-EEB4-7808-0C4E-A4314F86023E?ctype=12&ev=1&K=2df3874d61158a3d282c3ef9%26sign%3Dd644eac96dccae3a49f4e1e519375e49&ep=ciadG0uKUc4C5yLdiT8bbiThJ34LXP4J9h%2BNgdBkALghQJzJkDugxOu5PI5AZIxsBFFwGerzq9LubTYTYYU222wQ2EaoMfrgjfSW5dxXx5EEEBEwcs%2FUwVSeRjD4&oip=3723318150&token=0509&yxon=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049127702212112983c94_00/st/flv/fileid/030080260458DF95A3F9BA2BEEFCF9120297F7-EEB4-7808-0C4E-A4314F86023E?ctype=12&ev=1&K=51fc28cc5c9994bc2412f66a%26sign%3D22c7a9a38c81d029ef609bcd567939b3&ep=ciadG0uKUc4C5yLdiT8bbiThJ34LXP4J9h%2BNgdBkAL8hQJzJkDugxOu5PI5AZIxsBFFwGerzq9LubTYTYYU222wQ2EaoMfrgjfSW5dxXx5EEEBEwcs%2FUwVSeRjD4&oip=3723318150&token=0509&yxon=1
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjY3OTg5MzU2NA\\=\\=.html\\?from\\=y1.3-idx-beta-1519-23042.230771.1-1']
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/extractor.py", line 50, in download_by_url
    self.extract(**kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/extractors/youku.py", line 319, in extract
    ksegs += [i['server'] for i in json.loads(get_content(u))]
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 323, in get_content
    response = urlopen_with_retry(req)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 300, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

```

> 之前一直使用正常，某天以后出现这个问题。输完命令等待时间很久，也无法下载。不过直接在浏览器播放可以很快打开。
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
国内那几个大站需要多试几次，有时候api服务器会超时
