### ISSUE TITLE
couldn't download iqiyi vip video

### ISSUE THREAD

**Issue by liuxu623** [soimort/you-get#1833]
```
$ you-get -c cookies.txt --debug -i http://www.iqiyi.com/v_19rrb3rfno.html

[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/645431400/8525819c09a2265c08c623e60081bfea/?t=1491358967379&sc=1dcaa3f8d51fc65b91b6ea8004d72982&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrb3rfno.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/extractors/iqiyi.py", line 140, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video
```

**Comment by rosynirvana** [comment]
in favor of #2117
