### ISSUE TITLE
凤凰视频无法解析

### ISSUE THREAD

**Issue by sbwtw** [soimort/you-get#1834]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
➜  ~ you-get --debug -p mpv http://v.ifeng.com/video_6169467.shtml                                      ~
[DEBUG] get_html: http://v.ifeng.com/video_6169467.shtml
[DEBUG] get_response: http://v.ifeng.com/video_6169467.shtml
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://v.ifeng.com/video_6169467.shtml']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1426, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1339, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1155, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1419, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/extractors/ifeng.py", line 30, in ifeng_download
    assert id, "can't find video info"
AssertionError: can't find video info

```

**Comment by rosynirvana** [comment]
```
"vid": "01c7977b-aed6-4a98-bf20-6558bdb28734"
```

所以用vid=uuid这种写法匹配不到了
