### ISSUE TITLE
下载成功，但合并下载文件时报错

### ISSUE THREAD

**Issue by Boms** [soimort/you-get#1844]
url和错误信息如下，应该是合并文件太大造成的：
$ you-get --debug http://v.qq.com/x/page/s0391ddictq.html
Site:       QQ.com
Title:      《长谈》：罗振宇对话罗永浩
Type:       MPEG-4 video (video/mp4)
Size:       4371.84 MiB (4584202779 Bytes)

Downloading 《长谈》：罗振宇对话罗永浩.mp4 ...
 100% (4371.8/4371.8MB) ├█████████████████████████████████████┤[47/47]    5 MB/s
Merging video parts...
./《长谈》：罗振宇对话罗永浩[00].mp4
./《长谈》：罗振宇对话罗永浩[01].mp4
./《长谈》：罗振宇对话罗永浩[02].mp4
./《长谈》：罗振宇对话罗永浩[03].mp4
./《长谈》：罗振宇对话罗永浩[04].mp4
./《长谈》：罗振宇对话罗永浩[05].mp4
./《长谈》：罗振宇对话罗永浩[06].mp4
./《长谈》：罗振宇对话罗永浩[07].mp4
./《长谈》：罗振宇对话罗永浩[08].mp4
./《长谈》：罗振宇对话罗永浩[09].mp4
./《长谈》：罗振宇对话罗永浩[10].mp4
./《长谈》：罗振宇对话罗永浩[11].mp4
./《长谈》：罗振宇对话罗永浩[12].mp4
./《长谈》：罗振宇对话罗永浩[13].mp4
./《长谈》：罗振宇对话罗永浩[14].mp4
./《长谈》：罗振宇对话罗永浩[15].mp4
./《长谈》：罗振宇对话罗永浩[16].mp4
./《长谈》：罗振宇对话罗永浩[17].mp4
./《长谈》：罗振宇对话罗永浩[18].mp4
./《长谈》：罗振宇对话罗永浩[19].mp4
./《长谈》：罗振宇对话罗永浩[20].mp4
./《长谈》：罗振宇对话罗永浩[21].mp4
./《长谈》：罗振宇对话罗永浩[22].mp4
./《长谈》：罗振宇对话罗永浩[23].mp4
./《长谈》：罗振宇对话罗永浩[24].mp4
./《长谈》：罗振宇对话罗永浩[25].mp4
./《长谈》：罗振宇对话罗永浩[26].mp4
./《长谈》：罗振宇对话罗永浩[27].mp4
./《长谈》：罗振宇对话罗永浩[28].mp4
./《长谈》：罗振宇对话罗永浩[29].mp4
./《长谈》：罗振宇对话罗永浩[30].mp4
./《长谈》：罗振宇对话罗永浩[31].mp4
./《长谈》：罗振宇对话罗永浩[32].mp4
./《长谈》：罗振宇对话罗永浩[33].mp4
./《长谈》：罗振宇对话罗永浩[34].mp4
./《长谈》：罗振宇对话罗永浩[35].mp4
./《长谈》：罗振宇对话罗永浩[36].mp4
./《长谈》：罗振宇对话罗永浩[37].mp4
./《长谈》：罗振宇对话罗永浩[38].mp4
./《长谈》：罗振宇对话罗永浩[39].mp4
./《长谈》：罗振宇对话罗永浩[40].mp4
./《长谈》：罗振宇对话罗永浩[41].mp4
./《长谈》：罗振宇对话罗永浩[42].mp4
./《长谈》：罗振宇对话罗永浩[43].mp4
./《长谈》：罗振宇对话罗永浩[44].mp4
./《长谈》：罗振宇对话罗永浩[45].mp4
./《长谈》：罗振宇对话罗永浩[46].mp4
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/x/page/s0391ddictq.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/qq.py", line 111, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/qq.py", line 57, in qq_download_by_vid
    download_urls(part_urls, parts_ti, ext, total_size, output_dir=output_dir, merge=merge)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 830, in download_urls
    concat_mp4(parts, output_filepath)
  File "/usr/local/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 914, in concat_mp4
    merge_mp4s(mp4s, output)
  File "/usr/local/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 884, in merge_mp4s
    moov.write(output)
  File "/usr/local/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 78, in write
    atom.write(stream)
  File "/usr/local/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 78, in write
    atom.write(stream)
  File "/usr/local/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 78, in write
    atom.write(stream)
  [Previous line repeated 1 more times]
  File "/usr/local/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 515, in write
    write_uint(stream, chunk_offset)
  File "/usr/local/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 25, in write_uint
    stream.write(struct.pack('>I', n))
struct.error: 'I' format requires 0 <= number <= 4294967295

**Comment by rosynirvana** [comment]
装ffmpeg

**Comment by cnbeining** [comment]
Closed due to you really should use FFmpeg.
