### ISSUE TITLE
无法解析，提示socket.gaierror: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by limars874** [soimort/you-get#1848]
- [√ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [√ ] 您的`you-get`为最新版.
- [ √] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ √] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [√ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ["'http://tv.sohu.com/s2017/1663/s488315564/'"]
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1399, in any_download
  File "src\you_get\common.py", line 1390, in url_to_module
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 826, in connect
  File "socket.py", line 689, in create_connection
  File "socket.py", line 728, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed
you-get returned -1
```

> 系统为windows8.1，下载了最新版本的you-get，运行时发现无论用什么视频网址（本来只是想下个优酷视频），都会有这个错误，导致无法继续下一步动作。
谷歌了一下，据说是和dns或者系统代理有关，尝试了以下动作：
1.把dns配置改成默认，无效
2.我本身开着shadowsocks的pac代理，关掉-无效，开启全局代理-无效
3.使用--no-proxy参数，无效
4.然后我自己远程一个阿里云服务器，在上面安装了you-get，运行正常，我还把-u参数输出的url给弄出来在本机下载，速度飞快……但我想要的是本机进行下载合并。

这个到底是什么问题？

> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```
"'http://tv.sohu.com/s2017/1663/s488315564/'"
```

多了引号，所以没认出url是哪个站的，跳到google搜索上去了
```
File "src\you_get\common.py", line 1390, in url_to_module
File "http\client.py", line 1083, in request
```

请确定你用的console是不是支持单引号转义，某些版本的windows console(cmd.exe)并不支持
另外例子里的这个url不需要引号来转义

**Comment by limars874** [comment]
@rosynirvana 谢谢，原来就是一个单引号的问题，主要是官网教程有带单引号，所以以为这个是必须。现在没有任何问题了。
