### ISSUE TITLE
The Youku Video cannot be downloaded.

### ISSUE THREAD

**Issue by JiaxiangBU** [soimort/you-get#1849]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
$ you-get --debug http://v.youku.com/v_show/id_XMjcwNjk0NjA3Ng==.html?f=49499827&from=y1.3-idx-beta-1519-23042.223465.7-1
[1] 38806
JiaxiangdeMacBook-Air:~ JiaxiangLi$ [DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjcwNjk0NjA3Ng==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjcwNjk0NjA3Ng==&ct=12
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjcwNjk0NjA3Ng==.html?f=49499827']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/youku.py", line 231, in prepare
    'fileid': stream['stream_fileid'],
KeyError: 'stream_fileid'
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
$ you-get --debug http://v.youku.com/v_show/id_XMjcwNjk0NjA3Ng==.html?f=49499827&from=y1.3-idx-beta-1519-23042.223465.7-1
[1] 38806
JiaxiangdeMacBook-Air:~ JiaxiangLi$ [DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjcwNjk0NjA3Ng==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjcwNjk0NjA3Ng==&ct=12
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjcwNjk0NjA3Ng==.html?f=49499827']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/youku.py", line 231, in prepare
    'fileid': stream['stream_fileid'],
KeyError: 'stream_fileid'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```
{
    'logo': 'none',
    'drm_type': 'default',
    'media_type': 'standard',
    'subtitle_lang': 'default',
    'size': 44449669,
    'milliseconds_video': 844997,
    'width': 640,
    'milliseconds_audio': 844856,
    'height': 360,
    'stream_type': 'flvhd',
    'audio_lang': 'default',
    'segs': [{
        'path': 'http://k.youku.com/player/getFlvPath/sid/04921783982411030bcdc_00/st/flv/fileid/030002030058EFD44B985608BD8A982DDB01B0-A8D8-7737-D02A-58065BF3BB0F?k=0b1ed6b204087fd6282c45d1&hd=0&myp=0&ts=395&ymovie=1&sign=75e9fbd0e3a431fd1aea9ab2c8e4861b',
        'fileid': '030002030058EFD44B985608BD8A982DDB01B0-A8D8-7737-D02A-58065BF3BB0F',
        'total_milliseconds_audio': '395133',
        'size': '21000239',
        'total_milliseconds_video': '395199',
        'key': '0b1ed6b204087fd6282c45d1&sign=75e9fbd0e3a431fd1aea9ab2c8e4861b'
    }, {
        'path': 'http://k.youku.com/player/getFlvPath/sid/04921783982411030bcdc_01/st/flv/fileid/030002030158EFD44B985608BD8A982DDB01B0-A8D8-7737-D02A-58065BF3BB0F?k=92eb656548ff8108261f9f95&hd=0&myp=0&ts=386&ymovie=1&sign=3d08b6e6179adcf8ec01b6f394ec10ae',
        'fileid': '030002030158EFD44B985608BD8A982DDB01B0-A8D8-7737-D02A-58065BF3BB0F',
        'total_milliseconds_audio': '386263',
        'size': '20462892',
        'total_milliseconds_video': '386266',
        'key': '92eb656548ff8108261f9f95&sign=3d08b6e6179adcf8ec01b6f394ec10ae'
    }, {
        'path': 'http://k.youku.com/player/getFlvPath/sid/04921783982411030bcdc_02/st/flv/fileid/030002030258EFD44B985608BD8A982DDB01B0-A8D8-7737-D02A-58065BF3BB0F?k=9614538a2a5a0060282c45d1&hd=0&myp=0&ts=63&ymovie=1&sign=b22643d6c535ffedfb814963d14a466e',
        'fileid': '030002030258EFD44B985608BD8A982DDB01B0-A8D8-7737-D02A-58065BF3BB0F',
        'total_milliseconds_audio': '63460',
        'size': '2986538',
        'total_milliseconds_video': '63532',
        'key': '9614538a2a5a0060282c45d1&sign=b22643d6c535ffedfb814963d14a466e'
    }
```

这个stream_fileid应该是移动到seg里面去了，改名叫fileid?
youku.py的作者来改吧，现在的代码状态不太敢动。

**Comment by rosynirvana** [comment]
The following, words or code, are in public domain.

base url is ```"https://ups.youku.com/ups/get.json"```

5 params are mandatory: 
1. ```vid```
2. ```ccode=0401``` (040\d{1} for some youku partners)
3. ```client_ip=192.168.1.1``` (could be changed in the near future?)
4. ```tuid``` is from cookie cna (urlencoded). ```&tuid=``` is OK but maybe speed limit?
5. ```client_ts``` is epoch time. ```str(int(time.time()))``` in python

other possible params for youku: ```playlist_id password nochanne```

3 possible params for partners: ```client_id password r```

And then json containing everything will be returned and data -> stream -> segs -> cdn_url is all you need and no UA limitation at this moment.

**Comment by xuhaomin** [comment]
#1852 I fixed the bug
