### ISSUE TITLE
youku视频下载不了

### ISSUE THREAD

**Issue by MrLYU** [soimort/you-get#1853]
you-get --debug http://v.youku.com/v_show/id_XMjY5NzczODEyOA==.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjY5NzczODEyOA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjY5NzczODEyOA==&ct=12
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjY5NzczODEyOA==.html']
Traceback (most recent call last):
  File "d:\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\python\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\python\python36\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\python\python36\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\python\python36\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "d:\python\python36\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "d:\python\python36\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "d:\python\python36\lib\site-packages\you_get\extractors\youku.py", line 231, in prepare
    'fileid': stream['stream_fileid'],
KeyError: 'stream_fileid'

**Comment by magichackers** [comment]
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
'from' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
