### ISSUE TITLE
腾讯视频下载不了

### ISSUE THREAD

**Issue by augleo1989** [soimort/you-get#1855]
汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/004y4fy9dcn89cc.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/extractors/qq.py", line 111, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/lib/python3.4/site-packages/you_get/extractors/qq.py", line 55, in qq_download_by_vid
    print_info(site_info, parts_ti, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

>有些视频可以下载，有些视频下载返回上面错误，vip视频，下载只有头10分钟
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```'msg': 'format invalid'``` 看来接口变了

**Comment by augleo1989** [comment]
@rosynirvana 试了下按照源码方式模拟请求key，报错视频返回：QZOutputJson={"em":60,"exem":3,"ip":"111.201.36.171","msg":"check vid&filename failed","s":"f"};

**Comment by rosynirvana** [comment]
看了一眼腾讯最近的ckey 5.4，将近10000行相关的flascc代码，真素努力地不像话啊
比yy翻出来那个uauth还要厉害不少

**Comment by zhangn1985** [comment]
腾讯又不会check ckey

**Comment by lvqier** [comment]
@rosynirvana 腾讯的 ckey 相对来说比较容易，但是 guid 不好搞。。

**Comment by rosynirvana** [comment]
@lvqier 
ckey 5.4，不是腾讯祖传的TEA版

**Comment by lvqier** [comment]
@rosynirvana
嗯 chacha20-poly1305 版的已经搞定了

**Comment by rosynirvana** [comment]
那guid不好搞在哪里？

**Comment by rosynirvana** [comment]
现在flash版的接口用POST，ckey为必须，为空不可，否则返回客户端未授权

**Comment by zhangn1985** [comment]
ckey可为空。

**Comment by rosynirvana** [comment]
比如
```
curl 'https://vv.video.qq.com/getvinfo' --data 'refer=&encryptVer=5%2E4&defnpayver=1&ip=&sphls=1&speed=277&drm=8&guid=0EC484CB933D49F5AD028FDEA7A65907&linkver=2&platform=10902&otype=xml&fhdswitch=0&utype=0&sphttps=1&appver=3%2E2%2E38%2E411&ehost=https%3A%2F%2Fv%2Eqq%2Ecom%2Fx%2Fcover%2F9w1jwvn8nv56kea%2Ehtml&dtype=3&newplatform=10902&defsrc=1&pid=FF3B82651112F38B2BBDE5E8D28887A7&ran=0%2E4824169548228383&charge=0&fp2p=1&vid=x0020fpqfri&cKey=0cEw1ksgMgEYwcNGrK034xhHCplCdnvl797r6ND4PYriNkpKjRzH9bDbeSMC1ZhXhWrEX%5FPVuvSzJaK9mHgBcSLiovK5phC7Z4bLtZfIiL6rh3rcBahxhIAKjl9a3H%2DTYDto90mBaEFM230C5TR4oRqutLp%5FuOYs7GPTdalaSzGl87ahwMJrJPSHVEslCt56oyGWVUqCMJIvkkMWpSSgrpE%5FwReATvfC%5F%5FA%5F5CQxZbgcDYoIXHoZu5djIVtMFc%2D28JOMTZT1XJE9boDDvzMYa8dAL67wT%5F0u7Un%5FZi0MQFW7P9z3THdE%2DjkHBwcHBwcHLRkgaQ'
```
不论拿到的cdn有没有限速，是有数据的

如果让cKey为空
```
curl 'https://vv.video.qq.com/getvinfo' --data 'refer=&encryptVer=5%2E4&defnpayver=1&ip=&sphls=1&speed=277&drm=8&guid=0EC484CB933D49F5AD028FDEA7A65907&linkver=2&platform=10902&otype=xml&fhdswitch=0&utype=0&sphttps=1&appver=3%2E2%2E38%2E411&ehost=https%3A%2F%2Fv%2Eqq%2Ecom%2Fx%2Fcover%2F9w1jwvn8nv56kea%2Ehtml&dtype=3&newplatform=10902&defsrc=1&pid=FF3B82651112F38B2BBDE5E8D28887A7&ran=0%2E4824169548228383&charge=0&fp2p=1&vid=x0020fpqfri&cKey='
```
拿到的是```client not auth```

**Comment by zhangn1985** [comment]
https://vv.video.qq.com/getinfo

**Comment by rosynirvana** [comment]
```guid```的大致逻辑是
inline的js会生成一个hex string，完全基于prng，32bytes
```js
function createGUID(e) {
    e = e || 32;
    for (var r = "", a = 1; a <= e; a++) {
        var t = Math.floor(16 * Math.random()).toString(16);
        r += t
    }
    return r
}
```
注入到```window.PlayerParam```中，pid的生成方法相同

```guid```会成为swf在html中的```id```，flash会试图用[ExternalInterface.objectID](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/external/ExternalInterface.html#objectID)去读取，然后转换成大写，如果失败则会在flash内部生成一个guid，算法由下面的as3 code给出

```as3
public static
 function create(): String {
     var _loc1_: Date = new Date();
     var _loc3_: Number = _loc1_.getTime();
     var _loc2_: Number = Math.random() * 1.79769313486232e308;
     var _loc4_: String = Capabilities.serverString;
     counter = Number(counter) + 1;
     return calculate(_loc3_ + _loc4_ + _loc2_ + Number(counter)).toUpperCase();
 }
```
其中``` Capabilities.serverString```可以参考[文档](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/Capabilities.html#serverString)
```calculate```是计算sha1 hexdump的一个函数
所以说其实是没关系的，sha1摘要无法被求反拿到原始的输入，不能被验证，输入的数据只是保证guid不重复

**Comment by airdge** [comment]
不用cKey的接口都是get接口: getinfo  getkey
getv接口才要用到cKey: getvinfo getvkey

之前一段时间是取消了GUID认证的 
一个GUID从生成到客户端的认证失效是在一天内,之后限速
重新注册这个GUID又可以重新用,不会限制下载速度

**Comment by zhangn1985** [comment]
PLAYER_VERSION = '3.2.18.286'
好巧。。。

**Comment by Sornets** [comment]
guid, pid 看起来都是随机生成的[0~9|a-e]，就是ckey不知道是怎么来的，有大神知道吗？

**Comment by rosynirvana** [comment]
```platform=10901&isHLS=1``` 有1080p的m3u8

**Comment by rosynirvana** [comment]
cKey要先访问 ```'http://vv.video.qq.com/checktime?ran=' + str(random.random())```拿到一个xml，从xml中提取ip，epoch timestamp，和一个b64编码的随机值；

第一次生成的cKey不需要服务器的token，在as3里的方法名是```getTmpCKey```，从第二次的请求(第一次```getvinfo```，第二次就是```getvkey```)开始需要服务器的token。

本地先用```guid playerPlatform playerVersion```计算出一个hex string（hex string是根据下游的as3代码看出来的），然后```sendRequest```会把hex string转换会bytestring，发给```rlog.video.qq.com:8080```，不是http，是直接tcp发过去。

从服务器收到的tcp数据，前两字节是小端的数据长度，所有数据用一个长度为4的array xor解码，拿到的就是token，这个token会被储存。

32字节的guid，playerPlatform 10902，playerVersion '3.2.38.411'生成token，发出去的数据长度是70字节，前两字节是0x44 0x00，也就是长度0x0044 = 68 (68 + 2 = 70)；收到的数据是78字节。

拿到这个token后，生成cKey使用```getRegularCKey```，第一个参数是token，输出326字节；对于```getTmpCKey```，第一个参数是"2" + guid，输出长度是262字节。

很复杂，不知道谁有耐心去实现了，其实用m3u8就挺好。

**Comment by fstar** [comment]
http://vv.video.qq.com/getkey?vt=203&sdtfrom={sdtfrom}&vid={vid}&appVer={appver}&platform={platform}&otype=json&filename={filename}&format={format}&guid={guid}&charge=0&_rnd={_rnd}&_qv_rmt={_qv_rmt}&_qv_rmt2={_qv_rmt2} 
观测下来,主要通过这个接口获取vkey, 然后{**}是要填充的数据,
appVer通过chrome观测是3.0.66, 
sdtfrom是v1010
platform是10901, 
format是不同清晰度的版本, 
guid可以直接从浏览器里复制一个出来, 不过它是随机生成,但是随便填一个又会限速,不知道为什么,
_rnd是一个10位的时间戳, 
_qv_rmt和_qv_rmt2是通过一系列函数生成的值,会涉及到vid, _rnd, platform, sdtfrom

```js 
var c = i.hexToString(i.ha(e + t + n + i._Seed + s + a + r.charAt(0) + o)) // e是platfrom, t是vid, n是时间戳, s和a观察下来是空字符串, r观察下来就是个字符串'1', o是sdtfrom
,p = i.urlenc(i.tempcalc(c, i._Seed), r.charAt(0), n)
,u = i.u1(p, 0) // 这个值是_qv_rmt
,var h = i.u1(p, 1)  // 这个值是_qv_rmt2

i.ha = function(e) {
        function t(e, t) {
            return ((e >> 1) + (t >> 1) << 1) + (1 & e) + (1 & t)
        }
        for (var i = [], o = 0; o < 64; )
            i[o] = 0 | 4294967296 * Math.abs(Math.sin(++o));
        var r = function(o) {
            for (var r, n, s, a, d = [], c = window.unescape(encodeURI(o)), p = c.length, l = [r = 1732584193, n = -271733879, ~r, ~n], u = 0; u <= p; )
                d[u >> 2] |= (c.charCodeAt(u) || 128) << 8 * (u++ % 4);
            for (d[o = (p + 8 >> 6) * e + 14] = 8 * p,
            u = 0; u < o; u += e) {
                for (p = l,
                a = 0; a < 64; )
                    p = [s = p[3], t(r = p[1], (s = t(t(p[0], [r & (n = p[2]) | ~r & s, s & r | ~s & n, r ^ n ^ s, n ^ (r | ~s)][p = a >> 4]), t(i[a], d[[a, 5 * a + 1, 3 * a + 5, 7 * a][p] % e + u]))) << (p = [7, 12, 17, 22, 5, 9, 14, 20, 4, 11, e, 23, 6, 10, 15, 21][4 * p + a++ % 4]) | s >>> 32 - p), r, n];
                for (a = 4; a; )
                    l[--a] = t(l[a], p[a])
            }
            for (o = ""; a < 32; )
                o += (l[a >> 3] >> 4 * (1 ^ 7 & a++) & 15).toString(e);
            return o
        };
        return r
    }(16)

i.hexToString = function(e) {
        for (var t = "", i = "0x" == e.substr(0, 2) ? 2 : 0; i < e.length; i += 2)
            t += String.fromCharCode(parseInt(e.substr(i, 2), 16));
        return t
    }

i._Seed = "#$#@#*ad",

i._urlStr = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
    i.urlenc = function(e, t, o) {
        for (var r, n, s, a, d, c, p, l = "", u = 0; u < e.length; )
            r = e.charCodeAt(u++),
            n = e.charCodeAt(u++),
            s = e.charCodeAt(u++),
            15 == u && (l += "A",
            l += t,
            l += o),
            a = r >> 2,
            d = (3 & r) << 4 | n >> 4,
            c = (15 & n) << 2 | s >> 6,
            p = 63 & s,
            isNaN(n) ? c = p = 64 : isNaN(s) && (p = 64),
            l = l + i._urlStr.charAt(a) + i._urlStr.charAt(d) + i._urlStr.charAt(c) + i._urlStr.charAt(p);
        return l
    }
i.u1 = function(e, t) {
        for (var i = "", o = t; o < e.length; o += 2)
            i += e.charAt(o);
        return i
    }
```
然后需要注意的是js的位运算是32位的符号运算, 会有溢出情况, 我不知道在python里怎么优雅的得到本应该出现的溢出....

**Comment by rosynirvana** [comment]
@fstar 
如果不用ctype，直接&0xffffffff

**Comment by fstar** [comment]
直接&0xffffffff是没错...额...主要问题是...要变成负的....

**Comment by rosynirvana** [comment]
- 0x100000000
另外标准库里有ctype和struct

**Comment by Cphilo** [comment]
@fstar 问下这个guid会不会注册到了服务器上面，比如加上有效期然后随意生成一个就会有问题

**Comment by fstar** [comment]
@Cphilo 应该是的,  他会先判断storage里是否有guid, 如果没有就生成一个然后存进去, 然后我试过,直接把storage里的guid改掉, 改成自己随便生成的, 然后刷新页面以后这个新的guid也会生效, 应该是有个请求注册了storage里的guid, 但是我在chrome里没有抓到那个注册的请求T.T,

**Comment by fstar** [comment]
然后目测guid的有效期为3天....大概

**Comment by rosynirvana** [comment]
注册guid是TCP，不是http，chrome devtool抓不到
但是guid确实是随机生成的（32bytes）或某个无法被求反的sha1 hexdump

**Comment by Cphilo** [comment]
@rosynirvana 我理解腾讯视频页面如果禁止了flash的话是走的js的接口拿到视频地址的，这个注册guid怎么能够用tcp来操作呢

**Comment by airdge** [comment]
@Cphilo
之前的guid有效期是一天 这个应该不会变动
建议你去找下完整的js   guid只是一部分而已  
实现分段不限速 不是只靠guid和qv_rmt算法就能解决的
单段MP4倒是没那么多限制

**Comment by lvqier** [comment]
guid 是否有效和 kvcollect 接口有关，验证方法很简单：清除浏览器和flash存储中的 guid，用 adblocks 屏蔽这个接口调用，视频就不能正常播放。flash 播放器在播放视频的时候会有一系列的 kvcollect 接口的调用，这个接口看上去是统计用的。由此可以猜测腾讯通过数据统计实现了人机识别，而且识别策略可以随时调整，比不断升级加密算法容易多了。

**Comment by rosynirvana** [comment]
@Cphilo 
首先，腾讯有很多platform和不同的播放器，注册guid是10902的行为，其他平台不一定会去做
然后，js直接TCP的方法是很多的，比如H5 web sockets

**Comment by Cphilo** [comment]
@rosynirvana 确实@fstar 这个js破解的方式应该platform是10901的行为，这个应该没有去用tcp注册guid，但是我这边试了下这种办法发现并不能拿到正确的视频地址

**Comment by rosynirvana** [comment]
我给的什么方式？m3u8？

**Comment by Cphilo** [comment]
你说的注册guid是platform为10902的行为，这个是flash那边破解这样的，但是@fstar 提供的接口是js破解的方式platform是10901

**Comment by rosynirvana** [comment]
其实不用在guid上花心思，代码还是很明白的
静态页面里有一段js，里面有个```createGUID```，执行后把guid注入到```window.param```里
如果是js会直接用，如果是flash会用ExternalApi去读，读失败了会生成一个sha1 hexdump（比如bilibili上面用的腾讯播放器，没那段js）

代码在上面的一层回复里贴过，也可以在Devtool的console里eval ```window.param```，看和抓到的url里的guid是不是一样的。还有怀疑可以在静态页的js上加breakpoint验证。

**Comment by rosynirvana** [comment]
```
Site:       QQ.com
Title:      0422 SNH48 X队《逆流而上》剧场公演（高清全场）
Type:       MPEG-4 video (video/mp4)
Size:       1412.04 MiB (1480628432 Bytes)
```

**Comment by lki2019** [comment]
下这个地址的视频，速度 5 6百K吧 我一般抓m3u8 地址 那种快点

**Comment by radisliou** [comment]
@lki2019 请问怎么抓m3u8的地址？

**Comment by HJH12315** [comment]
@lki2019 腾讯视频的m3u8用什么抓取，谢谢？
