### ISSUE TITLE
优酷视频（youku）无法下载

### ISSUE THREAD

**Issue by zglzw** [soimort/you-get#1860]
>you-get -d http://v.youku.com/v_show/id_XMjcwNzkxNTAwOA==.html?from=s1.8-1-1.1&
spm=a2h0k.8191407.0.0
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjcwNzkxNTAwOA==&c
t=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjcwNzkxNTAwOA==&c
t=12
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjcwNzkxNTAwOA==.html?from=s1.8-1-1.1']

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1400, in any_download
  File "src\you_get\extractor.py", line 41, in download_by_url
  File "src\you_get\extractors\youku.py", line 231, in prepare
KeyError: 'stream_fileid'
you-get returned -1
'spm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

前几天还可以，最近突然就不行了

**Comment by zglzw** [comment]
我是使用预装包(仅供Windows)安装的you-get，有没有什么影响？

**Comment by zglzw** [comment]
我是打开you-get.bat，在其中中输入you-get http://v.youku.com/v_show/id_XMjcwNzkxNTAwOA==.html?from=s1.8-1-1.1  结果就无法下载，不知道为什么
