### ISSUE TITLE
iqiyi的其中一些视频无法解析。

### ISSUE THREAD

**Issue by ghjkl77** [soimort/you-get#1861]
在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
D:\TDDOWNLOAD\you-get>you-get -i http://www.iqiyi.com/dianshiju/20121106/a5f7e3e
10a47a397.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

D:\TDDOWNLOAD\you-get>you-get --debug http://www.iqiyi.com/dianshiju/20121106/a5
f7e3e10a47a397.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/120576300/2981ab8d436c404fba5
053359263f21b/?t=1492331940490&sc=aa809e337e86a1fb0a0a4e573ac9254f&src=76f90cbd9
2f94a2e925d83e8ccd22cb7
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/dianshiju/20121106/a5f7e3e10a47a397.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1410, in main
  File "src\you_get\common.py", line 1323, in script_main
  File "src\you_get\common.py", line 1139, in download_main
  File "src\you_get\common.py", line 1403, in any_download
  File "src\you_get\extractor.py", line 41, in download_by_url
  File "src\you_get\extractors\iqiyi.py", line 140, in prepare
AssertionError: can't play this video
you-get returned -1
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 这是一个专辑里面的前10集都出现这样错误，第11-13集解析正常。
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
是的，因为用的不是网页版的接口，所以行为和网页端并不一样。
不过接口已经公开了几次了，可以自己换src/you_get/extractors/iqiyi.py里的代码

**Comment by ghjkl77** [comment]
不知道接口，也不知怎么替换代码，还有其他方法吗？

**Comment by rosynirvana** [comment]
那大概要等有人愿意做这件事情了

**Comment by zglzw** [comment]
@rosynirvana 想问一下爱奇艺和优酷的vip视频如何解析？

**Comment by rosynirvana** [comment]
@zglzw 没vip账号，没测试过

**Comment by lki2019** [comment]
抱歉你访问的页面不存在
