### ISSUE TITLE
iqiyi video cannot be downloaded.

### ISSUE THREAD

**Issue by JiaxiangBU** [soimort/you-get#1865]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
$ you-get --debug http://www.iqiyi.com/v_19rrkagglg.html
[DEBUG] get_html: http://www.iqiyi.com/v_19rrkagglg.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rrkagglg.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/424945000/5c9828379aeeb2a921a1b048a72b34aa/?t=1492403663876&sc=811f70dd0c032f63463d4b8bded7bb3c&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               触手可及：陈冠希第2集
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrkagglg.html']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1158, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractor.py", line 52, in download_by_url
    self.download(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/iqiyi.py", line 204, in download
    merge=kwargs['merge'],)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 990, in download_url_ffmpeg
    assert has_ffmpeg_installed(), "FFmpeg not installed."
AssertionError: FFmpeg not installed.```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```container:     m3u8```
```FFmpeg not installed```

现在爱奇艺的m3u8是用ffmpeg下载的，所以必须安装ffmpeg才能正常使用

**Comment by JiaxiangBU** [comment]
我反复下载了FFmpeg，但是依然提示没有安装FFmpeg我觉得是不是我的文件路径设置错了。
```
$ /opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/multimedia/VLC/files/ffmpeg 
```

```
$ you-get 
```

**Comment by rosynirvana** [comment]
终端里直接```ffmpeg```能找到可执行文件吗？
