### ISSUE TITLE
每个月都会出现几次，you-get插件不可用，无法解析常用的优酷、腾讯网站

### ISSUE THREAD

**Issue by shuangziliuyun** [soimort/you-get#1866]
**操作及错误信息：**
「解析优酷视频失败」
you-get -i http://v.youku.com/v_show/id_XMjcxMTQ0MzAyMA\=\=.html\?f\=49541087\&spm\=a2hww.20023042.m_223465.5\~5\~5\~5\!2\~5\~5\~A\&from\=y1.3-idx-beta-1519-23042.223465.4-1
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

「解析腾讯视频失败」
you-get -i https://v.qq.com/x/cover/sqmkhre9cpq6t2y/s0023h9vfaw.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

「问题描述」
插件偶尔会出现，一整天无法解析优酷、腾讯等网站的任何URL的情况，但多数情况第二天就恢复了，请问造成这种问题的原因是什么？

**Comment by shuangziliuyun** [comment]
「解析腾讯视频失败 --debug」
you-get --debug  https://v.qq.com/x/cover/sqmkhre9cpq6t2y/s0023h9vfaw.html
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/sqmkhre9cpq6t2y/s0023h9vfaw.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/extractors/qq.py", line 111, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/extractors/qq.py", line 11, in qq_download_by_vid
    info = get_html(info_api)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 278, in get_html
    content = get_response(url, faker).data
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 266, in get_response
    response = request.urlopen(url)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

「解析优酷视频失败 --debug」
you-get --debug  http://v.youku.com/v_show/id_XMjcxMTQ0MzAyMA\=\=.html\?f\=49541087\&spm\=a2hww.20023042.m_223465.5\~5\~5\~5\!2\~5\~5\~A\&from\=y1.3-idx-beta-1519-23042.223465.4-1
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjcxMTQ0MzAyMA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjcxMTQ0MzAyMA==&ct=12
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjcxMTQ0MzAyMA==.html?f=49541087&spm=a2hww.20023042.m_223465.5~5~5~5!2~5~5~A&from=y1.3-idx-beta-1519-23042.223465.4-1']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.652/libexec/lib/python3.6/site-packages/you_get/extractors/youku.py", line 231, in prepare
    'fileid': stream['stream_fileid'],
KeyError: 'stream_fileid'
