### ISSUE TITLE
failed to download video from (v.douyu.com)

### ISSUE THREAD

**Issue by FLEM1NGTON** [soimort/you-get#1876]
```
you-get --debug https://v.douyu.com/show/GX3JzMa3Vx9vPQro
[DEBUG] get_content: http://v.douyu.com/show/GX3JzMa3Vx9vPQro
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=None
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['https://v.douyu.com/show/GX3JzMa3Vx9vPQro']
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\extractors\douyutv.py", line 21, in douyutv_download
    data = json.loads(content)['data']
KeyError: 'data'
```
url:https://v.douyu.com/show/GX3JzMa3Vx9vPQro

**Comment by rosynirvana** [comment]
好像直接 ```'https://vmobile.douyu.com/video/getInfo?vid= + url.split('/')[-1]'```拿到的json就是了

**Comment by rosynirvana** [comment]
in favor of #1598
