### ISSUE TITLE
Iqiyi Video cannot be downloaded.

### ISSUE THREAD

**Issue by JiaxiangBU** [soimort/you-get#1889]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
$ you-get --debug 'http://player.video.qiyi.com/baddd18205f8bf16f783d0f5c56eeea4/0/4477/v_19rrav1h70.swf-albumId=206033301-tvId=660276000-isPurchase=0-cnId=6'
[DEBUG] get_html: http://www.iqiyi.com/common/flashplayer/20170420/10471a7ff0f5.swf?vid=baddd18205f8bf16f783d0f5c56eeea4&pageURL=v_19rrav1h70.swf&albumId=206033301&tvId=660276000&isPurchase=0&cnId=6&share_sTime=0&share_eTime=4477&source=&purl=
[DEBUG] get_response: http://www.iqiyi.com/common/flashplayer/20170420/10471a7ff0f5.swf?vid=baddd18205f8bf16f783d0f5c56eeea4&pageURL=v_19rrav1h70.swf&albumId=206033301&tvId=660276000&isPurchase=0&cnId=6&share_sTime=0&share_eTime=4477&source=&purl=
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://player.video.qiyi.com/baddd18205f8bf16f783d0f5c56eeea4/0/4477/v_19rrav1h70.swf-albumId=206033301-tvId=660276000-isPurchase=0-cnId=6']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1158, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/iqiyi.py", line 137, in prepare
    self.title = match1(html, '<title>([^<]+)').split('-')[0]
AttributeError: 'NoneType' object has no attribute 'split'```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```http://player.video.qiyi.com/baddd18205f8bf16f783d0f5c56eeea4/0/4477/v_19rrav1h70.swf-albumId=206033301-tvId=660276000-isPurchase=0-cnId=6```

这不是iqiyi的页面地址，是播放器地址，当然抓不到title

**Comment by denobisipsis** [comment]
FYI

cmd5 with src 1702633101b340d8917a69cf8a4b8c7c solved.

PC uses Player_z.swf which in turn request the function ycalc and not xcalc.

Ycalc equals to a md5 with salt

str="/vms?key=fvip&src=1702633101b340d8917a69cf8a4b8c7c&tvId=214230107&vid=cce29b4a05363a5bdce1e824deeff474&vinfo=1&tm=1159&qyid=cf66272a29d2bd6bafca991c1af76911&puid=&authKey=0aaf6ce41642f43873ba9ee67c6aa7d1&um=0&pf=b6c13e26323c537d&thdk=&thdt=&rs=1&k_tag=1&qdx=n&qdv=3"

salt="u6fnp3eok0dpftcq9qbr4n9svk8tqh7u"

so vf=21d2ae1b3999acb91d75157ce98b435d

**Comment by yangl326-Dylan** [comment]
@denobisipsis  how to get vf?

**Comment by denobisipsis** [comment]
https://github.com/denobisipsis/adownloader/blob/master/iqiyi_ycalc.php
