### ISSUE TITLE
MGTV的不能下载这样的专辑吗？

### ISSUE THREAD

**Issue by GoGoogle** [soimort/you-get#1896]
汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [Y ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [Y ] 您的`you-get`为最新版.
- [Y ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [Y ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [Y ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get --debug http://www.mgtv.com/h/293426.html
[DEBUG] get_content: http://pcweb.api.mgtv.com/player/video?video_id=None
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.mgtv.com/h/293426.html']
Traceback (most recent call last):
  File "c:\users\gogoogle\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\gogoogle\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\gogoogle\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\gogoogle\appdata\local\programs\python\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\gogoogle\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\gogoogle\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\gogoogle\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "c:\users\gogoogle\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "c:\users\gogoogle\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\gogoogle\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\mgtv.py", line 68, in prepare
    self.title = content['data']['info']['title']
TypeError: 'NoneType' object is not subscriptable
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [MGTV的不能下载这样的专辑吗？类似专辑列表http://www.mgtv.com/h/293426.html ]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
下播放列表加-l
mgtv的没人写，还在函数里加了个pass不抛出异常，让我白debug半天

**Comment by GoGoogle** [comment]
you-get -l --debug http://www.mgtv.com/h/293426.html
啥也没有
mgtv的

**Comment by rosynirvana** [comment]
上面的回复已经说明了mgtv playlist没人写，也就是当前不支持
