### ISSUE TITLE
List of QQ Videos Don't Download

### ISSUE THREAD

**Issue by dkl3** [soimort/you-get#1908]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
$ you-get -I list --debug
[DEBUG] get_response: http://v.qq.com/page/a/0/g/a01714fzv0g.html
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/page/a/0/g/a01714fzv0g.html', 'http://v.qq.com/page/a/0/w/a0176r2690w.html', 'http://v.qq.com/page/a/3/u/a01845cyk3u.html', 'http://v.qq.com/page/a/8/j/a0174j10a8j.html', 'http://v.qq.com/page/a/8/n/a0184rbx38n.html', 'http://v.qq.com/page/a/8/n/a0197k6b48n.html', 'http://v.qq.com/page/a/g/z/a0158t3cygz.html', 'http://v.qq.com/page/a/o/r/a0169p0dwor.html', 'http://v.qq.com/page/a/o/u/a01662owjou.html', 'http://v.qq.com/page/a/s/t/a01494oyjst.html', 'http://v.qq.com/page/b/8/f/b0384ozwq8f.html', 'http://v.qq.com/page/b/d/n/b0177czxidn.html', 'http://v.qq.com/page/b/g/x/b0173hrimgx.html', 'http://v.qq.com/page/b/i/l/b0386skmbil.html', 'http://v.qq.com/page/b/m/3/b0356704vm3.html', 'http://v.qq.com/page/b/o/a/b0177axz5oa.html', 'http://v.qq.com/page/b/s/1/b0190pz6js1.html', 'http://v.qq.com/page/c/6/v/c033579lp6v.html', 'http://v.qq.com/page/c/g/0/c019640mfg0.html', 'http://v.qq.com/page/c/g/t/c0310xcm1gt.html', 'http://v.qq.com/page/c/v/s/c03066ti2vs.html', 'http://v.qq.com/page/d/2/5/d0184vdx325.html', 'http://v.qq.com/page/d/4/2/d0315r5oz42.html', 'http://v.qq.com/page/d/q/u/d0177quzgqu.html', 'http://v.qq.com/page/d/y/v/d0332uyd7yv.html', 'http://v.qq.com/page/e/1/x/e01586npo1x.html', 'http://v.qq.com/page/e/j/d/e0370lpwijd.html', 'http://v.qq.com/page/e/j/t/e0164a4h3jt.html', 'http://v.qq.com/page/e/k/9/e033692tfk9.html', 'http://v.qq.com/page/e/p/j/e0170y58hpj.html', 'http://v.qq.com/page/e/x/k/e0185421kxk.html', 'http://v.qq.com/page/f/1/d/f0174ko6k1d.html', 'http://v.qq.com/page/f/o/6/f01496d8eo6.html', 'http://v.qq.com/page/f/v/t/f0153dl8jvt.html', 'http://v.qq.com/page/g/e/5/g0177j27we5.html', 'http://v.qq.com/page/g/e/k/g0312l3jyek.html', 'http://v.qq.com/page/g/j/p/g01846xrwjp.html', 'http://v.qq.com/page/g/l/r/g03221ch0lr.html', 'http://v.qq.com/page/g/x/c/g0386k4ovxc.html', 'http://v.qq.com/page/g/y/5/g0160wozny5.html', 'http://v.qq.com/page/g/z/o/g035813mgzo.html', 'http://v.qq.com/page/g/z/s/g01940rihzs.html', 'http://v.qq.com/page/h/j/s/h016325qjjs.html', 'http://v.qq.com/page/h/q/k/h0170tyhjqk.html', 'http://v.qq.com/page/h/r/y/h01604kh1ry.html', 'http://v.qq.com/page/i/0/7/i0357e9ie07.html', 'http://v.qq.com/page/i/0/b/i01572spp0b.html', 'http://v.qq.com/page/i/8/v/i03824e698v.html', 'http://v.qq.com/page/i/k/q/i0340ekxrkq.html', 'http://v.qq.com/page/i/n/6/i0187iw65n6.html', 'http://v.qq.com/page/i/p/k/i0381c6elpk.html', 'http://v.qq.com/page/i/q/e/i0368oaicqe.html', 'http://v.qq.com/page/i/v/n/i0153e1uwvn.html', 'http://v.qq.com/page/i/x/c/i0332t55sxc.html', 'http://v.qq.com/page/j/0/7/j0173yg3x07.html', 'http://v.qq.com/page/j/1/2/j0382b3cl12.html', 'http://v.qq.com/page/j/7/c/j0194i9oc7c.html', 'http://v.qq.com/page/j/9/o/j0315gzco9o.html', 'http://v.qq.com/page/j/a/0/j03799n0ta0.html', 'http://v.qq.com/page/j/j/k/j0153hpsxjk.html', 'http://v.qq.com/page/j/o/l/j0164infuol.html', 'http://v.qq.com/page/k/5/8/k0354p7zb58.html', 'http://v.qq.com/page/k/b/l/k0152tix7bl.html', 'http://v.qq.com/page/k/h/6/k0376xesvh6.html', 'http://v.qq.com/page/k/h/q/k0158m5x8hq.html', 'http://v.qq.com/page/k/l/0/k0178p9udl0.html', 'http://v.qq.com/page/k/p/m/k0394j5dwpm.html', 'http://v.qq.com/page/k/q/m/k0178r3yrqm.html', 'http://v.qq.com/page/k/s/l/k0189xyyfsl.html', 'http://v.qq.com/page/k/x/s/k0150jfnsxs.html', 'http://v.qq.com/page/l/4/q/l03704ioy4q.html', 'http://v.qq.com/page/l/7/m/l01570p9w7m.html', 'http://v.qq.com/page/l/f/w/l0193htx1fw.html', 'http://v.qq.com/page/m/7/a/m01745abd7a.html', 'http://v.qq.com/page/m/a/o/m0160w3pbao.html', 'http://v.qq.com/page/m/b/q/m0176mmlfbq.html', 'http://v.qq.com/page/m/g/5/m0178n29hg5.html', 'http://v.qq.com/page/m/g/i/m0161oms9gi.html', 'http://v.qq.com/page/m/h/d/m0176wqnwhd.html', 'http://v.qq.com/page/m/i/g/m01890hf9ig.html', 'http://v.qq.com/page/m/s/3/m0369irv7s3.html', 'http://v.qq.com/page/m/y/3/m0169zyxby3.html', 'http://v.qq.com/page/n/4/l/n03139e5l4l.html', 'http://v.qq.com/page/n/i/2/n0382f2kri2.html', 'http://v.qq.com/page/n/t/y/n0337a6bpty.html', 'http://v.qq.com/page/o/0/i/o01495kj10i.html', 'http://v.qq.com/page/o/b/o/o0371mnx7bo.html', 'http://v.qq.com/page/o/l/b/o0319ecl8lb.html', 'http://v.qq.com/page/p/c/4/p03670xfec4.html', 'http://v.qq.com/page/p/n/9/p0175vnhkn9.html', 'http://v.qq.com/page/p/y/b/p0326ex58yb.html', 'http://v.qq.com/page/q/7/1/q0172vc3e71.html', 'http://v.qq.com/page/q/c/2/q016010k2c2.html', 'http://v.qq.com/page/q/w/a/q0167x0e7wa.html', 'http://v.qq.com/page/q/y/o/q0177flylyo.html', 'http://v.qq.com/page/r/1/p/r0181va171p.html', 'http://v.qq.com/page/r/2/c/r03611shu2c.html', 'http://v.qq.com/page/r/3/s/r0388ueb83s.html', 'http://v.qq.com/page/r/i/m/r01796xmvim.html', 'http://v.qq.com/page/r/m/e/r0173cpleme.html', 'http://v.qq.com/page/r/p/u/r03066nfqpu.html', 'http://v.qq.com/page/r/x/4/r0182oztmx4.html', 'http://v.qq.com/page/r/y/4/r0192dkm4y4.html', 'http://v.qq.com/page/s/4/e/s03693nli4e.html', 'http://v.qq.com/page/s/8/6/s0177flku86.html', 'http://v.qq.com/page/s/t/w/s0163fweltw.html', 'http://v.qq.com/page/s/z/n/s0151gxeqzn.html', 'http://v.qq.com/page/t/2/2/t0369drp122.html', 'http://v.qq.com/page/t/9/q/t0160jgei9q.html', 'http://v.qq.com/page/t/t/b/t0346dfsltb.html', 'http://v.qq.com/page/t/x/u/t0199b2l3xu.html', 'http://v.qq.com/page/u/1/7/u0181wwhc17.html', 'http://v.qq.com/page/u/j/b/u0378h541jb.html', 'http://v.qq.com/page/u/s/x/u0319oulzsx.html', 'http://v.qq.com/page/u/t/y/u0192708nty.html', 'http://v.qq.com/page/u/z/u/u015526tbzu.html', 'http://v.qq.com/page/v/3/m/v0344yqcc3m.html', 'http://v.qq.com/page/v/u/3/v0388o30uu3.html', 'http://v.qq.com/page/w/d/j/w0369cjtydj.html', 'http://v.qq.com/page/x/n/h/x0174gy6gnh.html', 'http://v.qq.com/page/y/0/u/y0178niuf0u.html', 'http://v.qq.com/page/y/9/i/y0166qvk79i.html', 'http://v.qq.com/page/y/e/q/y019110c2eq.html', 'http://v.qq.com/page/y/l/1/y0162gwpwl1.html', 'http://v.qq.com/page/y/o/m/y0171x97som.html', 'http://v.qq.com/page/y/s/z/y0160e3uxsz.html', 'http://v.qq.com/page/y/y/1/y0379e5t6y1.html', 'http://v.qq.com/page/z/6/g/z01604cok6g.html', 'http://v.qq.com/page/z/f/k/z01753tnwfk.html', 'http://v.qq.com/page/z/o/3/z01516hr5o3.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.715', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.715-py3.5.egg/you_get/__main__.py", line 92, in main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.715-py3.5.egg/you_get/common.py", line 1441, in main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.715-py3.5.egg/you_get/common.py", line 1352, in script_main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.715-py3.5.egg/you_get/common.py", line 1154, in download_main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.715-py3.5.egg/you_get/common.py", line 1434, in any_download
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.715-py3.5.egg/you_get/extractors/qq.py", line 140, in qq_download
TypeError: argument of type 'NoneType' is not iterable

---

It's just that v.qq.com videos won't download when in a text file. I'd appreciate  a fix, thanks.

**Comment by dkl3** [comment]
http://v.qq.com/vplus/b3e086f8333cd40349f7dca59105875c

Here's the channel page. Also, i'd like to download each video from the channel page like with Youku, which downloads all 50 video from a channel page each.

**Comment by rosynirvana** [comment]
问题在这里
```python
if 'v.qq.com/page' in url:
    # for URLs like this:
    # http://v.qq.com/page/k/9/7/k0194pwgw97.html
    content = get_html(url)
    url = match1(content,r'window\.location\.href="(.*?)"')
```

例如```http://v.qq.com/page/a/0/g/a01714fzv0g.html```
这个页面抓不到```window.location.href```，所以下面就因为```NoneType```报错了
解决方法应该是让server端302过去
```
$ curl -I 'http://v.qq.com/page/a/0/g/a01714fzv0g.html'
HTTP/1.1 302 Found
Server: Apache
Connection: close
Date: Wed, 26 Apr 2017 03:04:12 GMT
Cache-Control: max-age=60
Expires: Wed, 26 Apr 2017 03:05:12 GMT
Last-Modified: Wed, 26 Apr 2017 03:00:00 GMT
Content-Type: text/html; charset=iso-8859-1
Content-Length: 224
Location: https://v.qq.com/x/page/a01714fzv0g.html
Vary: Accept-Encoding
X-Cache-Lookup: Hit From Upstream
X-Daa-Tunnel: hop_count=1
X-NWS-LOG-UUID: 6abd3d9d-c39d-4fed-8ee0-9b3df551e7a8
Access-Control-Expose-Headers: X-Client-Ip
Access-Control-Expose-Headers: X-Server-Ip
Access-Control-Expose-Headers: X-Upstream-Ip
Keep-Alive: timeout=60
X-Client-Ip: 182.114.2.177
X-Server-Ip: 123.6.1.13
X-Upstream-Ip: 140.207.123.151:80
X-UA-Compatible: IE=Edge
X-Cache-Lookup: Hit From Upstream
```
