### ISSUE TITLE
ACFun 不支持

### ISSUE THREAD

**Issue by Jin-Whu** [soimort/you-get#1914]
[DEBUG] get_html: http://www.acfun.cn/v/ac3627993
[DEBUG] get_response: http://www.acfun.cn/v/ac3627993
[DEBUG] get_html: http://www.acfun.tv/video/getVideo.aspx?id=5072435
[DEBUG] get_response: http://www.acfun.tv/video/getVideo.aspx?id=5072435
[DEBUG] get_content: http://api.aixifan.com/plays/5072435
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519d032263f8&video_id=58f21c550cf2e0a5bb13b93d&embsig=1_1493385000_e0e1462e3e2b0cb1acb517916bd07279
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=58f21c550cf2e0a5bb13b93d&ct=85&sign=MXwxNDkzMzg1MDAxfDc4YzViOTIyYTQ3ZjJiY2FkMmJmODI3MmQ5NjdiYmZk
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac3627993']
Traceback (most recent call last):
  File "d:\program files\anaconda3\envs\python3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\anaconda3\envs\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Anaconda3\envs\python3\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files\anaconda3\envs\python3\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files\anaconda3\envs\python3\lib\site-packages\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files\anaconda3\envs\python3\lib\site-packages\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\program files\anaconda3\envs\python3\lib\site-packages\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "d:\program files\anaconda3\envs\python3\lib\site-packages\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "d:\program files\anaconda3\envs\python3\lib\site-packages\you_get\extractors\acfun.py", line 90, in acfun_download
    **kwargs)
  File "d:\program files\anaconda3\envs\python3\lib\site-packages\you_get\extractors\acfun.py", line 55, in acfun_download_by_vid
    youku_open_download_by_vid(client_id='908a519d032263f8', vid=sourceId, title=title, output_dir=output_dir,merge=merge, info_only=info_only, embsig = embsig, **kwargs)
  File "d:\program files\anaconda3\envs\python3\lib\site-packages\you_get\extractors\youku.py", line 375, in open_download_by_vid
    self.prepare(api_url = api85_url, api12_url = api86_url, ctype = 86, **kwargs)
  File "d:\program files\anaconda3\envs\python3\lib\site-packages\you_get\extractors\youku.py", line 172, in prepare
    headers={'Referer': 'http://static.youku.com/'}
  File "d:\program files\anaconda3\envs\python3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "d:\program files\anaconda3\envs\python3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\program files\anaconda3\envs\python3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

**Comment by soimort** [comment]
Closed via #2010.
