### ISSUE TITLE
iqiyi 不能解析

### ISSUE THREAD

**Issue by mengmo** [soimort/you-get#1916]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get -di http://www.iqiyi.com/v_19rrb063r8.html
D:\PortableApps\Python\lib\runpy.py:125: RuntimeWarning: 'you_get.__main__' found in sys.modules after import of package 'you_get', but prior to execution of 'you_get.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[DEBUG] get_html: http://www.iqiyi.com/v_19rrb063r8.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rrb063r8.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/668775400/ad340aee471e8ec200755f424ef10937/?t=1493534732663&sc=773c589d0696d01377273a5271e21d14&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrb063r8.html']
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 95, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractors\iqiyi.py", line 140, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

**Comment by rosynirvana** [comment]
多试几次
```
you-get -di http://www.iqiyi.com/v_19rrb063r8.html
[DEBUG] get_html: http://www.iqiyi.com/v_19rrb063r8.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rrb063r8.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/668775400/ad340aee471e8ec200755f424ef10937/?t=1493536533315&sc=1c857c87f8391b8fb0fafaa48db9dc83&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               奔跑吧_20170428期
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: you-get --format=LD [URL]
```

**Comment by mengmo** [comment]
嗯 确实

**Comment by mengmo** [comment]
情况好像是 Windows 10 Creator Update 后，命令提示符不需要再设置 http(s)_proxy，会直接调用 Windows 设置里的代理
