### ISSUE TITLE
网易云音乐下载歌单，cover和前两首歌都能下，但后面的下不了

### ISSUE THREAD

**Issue by dAxIOnG8** [soimort/you-get#1917]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
(py35) C:\Users\shu>you-get --debug http://music.163.com/#/my/m/music/playlist?id=469708961
[DEBUG] get_content: http://music.163.com/api/playlist/detail?id=469708961&csrf_token=
Skipping ./『静心纯音』钢琴的哼唱，让世界安静下来\cover.jpg: file already exists

[DEBUG] url_info: http://p2.music.126.net/M1YjXCVLQR0kQdFC1c4xHg==/3429376769197355.mp3
Site:       163.com
Title:      000_6. Do You
Type:       MP3 (audio/mpeg)
Size:       11.25 MiB (11799030 Bytes)

Skipping ./『静心纯音』钢琴的哼唱，让世界安静下来\000_6. Do You.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=22829926&lv=-1&csrf_token=
[DEBUG] url_info: http://p2.music.126.net/nOLhARsApFNWMsRUm9Fv6Q==/1989016534657900.mp3
Site:       163.com
Title:      001_15. A Shimmer of Leaves
Type:       MP3 (audio/mpeg)
Size:       5.83 MiB (6111886 Bytes)

Skipping ./『静心纯音』钢琴的哼唱，让世界安静下来\001_15. A Shimmer of Leaves.mp3: file already exists

[DEBUG] get_content: http://music.163.com/api/song/lyric/?id=1091355&lv=-1&csrf_token=
[DEBUG] url_info: http://p2.music.126.net/GDHu5fLGAMfJaTWpu-shBw==/1910951209137154.mp3
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/my/m/music/playlist?id=469708961']
Traceback (most recent call last):
  File "c:\anaconda3\envs\py35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\py35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\py35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\extractors\netease.py", line 133, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\extractors\netease.py", line 61, in netease_cloud_music_download
    netease_song_download(i, output_dir=new_dir, info_only=info_only, playlist_prefix=playlist_prefix)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\extractors\netease.py", line 120, in netease_song_download
    output_dir=output_dir, info_only=info_only)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\extractors\netease.py", line 123, in netease_download_common
    songtype, ext, size = url_info(url_best)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\common.py", line 425, in url_info
    response = urlopen_with_retry(request.Request(url))
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\common.py", line 310, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\anaconda3\envs\py35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "c:\anaconda3\envs\py35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "c:\anaconda3\envs\py35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\anaconda3\envs\py35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "c:\anaconda3\envs\py35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "c:\anaconda3\envs\py35\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by Himryang** [comment]
在下载网易云音乐的时候，同样遇到了这个问题，报错：`urllib.error.HTTPError: HTTP Error 404: Not Found`，事实上这个链接确实是有效的：[](http://music.163.com/#/song?id=150667)，可以直接访问到，结果如下：
```
λ you-get -di http://music.163.com/song?id=150667
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=150667&ids=[150667]&csrf_token=
[DEBUG] url_info: http://p2.music.126.net/iryd1VktLwJBbfihhSnEhQ==/1382086124991634.mp3
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/song?id=150667']
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Anaconda3\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "d:\anaconda3\lib\site-packages\you_get\extractors\netease.py", line 133, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "d:\anaconda3\lib\site-packages\you_get\extractors\netease.py", line 70, in netease_cloud_music_download
    netease_song_download(j["songs"][0], output_dir=output_dir, info_only=info_only)
  File "d:\anaconda3\lib\site-packages\you_get\extractors\netease.py", line 120, in netease_song_download
    output_dir=output_dir, info_only=info_only)
  File "d:\anaconda3\lib\site-packages\you_get\extractors\netease.py", line 123, in netease_download_common
    songtype, ext, size = url_info(url_best)
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 425, in url_info
    response = urlopen_with_retry(request.Request(url))
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 310, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "d:\anaconda3\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "d:\anaconda3\lib\urllib\request.py", line 470, in open
    response = meth(req, response)
  File "d:\anaconda3\lib\urllib\request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\anaconda3\lib\urllib\request.py", line 508, in error
    return self._call_chain(*args)
  File "d:\anaconda3\lib\urllib\request.py", line 442, in _call_chain
    result = func(*args)
  File "d:\anaconda3\lib\urllib\request.py", line 588, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
有办法在运行过程中 忽略歌单中无效的链接吗？

**Comment by rosynirvana** [comment]
我猜这个很早之前写的patch可以，试试看吧 #1709

**Comment by rosynirvana** [comment]
outdated
