### ISSUE TITLE
MGTV has a problem

### ISSUE THREAD

**Issue by tmhvnn** [soimort/you-get#1921]
you-get --debug --info --url --json http://www.mgtv.com/b/293994/3920088.html
[DEBUG] get_content: http://v.api.mgtv.com/player/video?video_id=3920088
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.mgtv.com/b/293994/3920088.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1400, in any_download
  File "src\you_get\extractor.py", line 41, in download_by_url
  File "src\you_get\extractors\mgtv.py", line 64, in prepare
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
you-get returned -1

**Comment by rosynirvana** [comment]
```
./you-get -di http://www.mgtv.com/b/293994/3920088.html
[DEBUG] get_content: http://pcweb.api.mgtv.com/player/video?video_id=3920088
[DEBUG] get_content: http://disp.titan.mgtv.com/vod.do?pm=_wM~gHL3Ev2TyoUQzKt2WQgiZZIyqQwt8l~7zNTuva7awLP9dpLJIdPprpMk_OzoJG~CxGa5KeOQbAVtgP0uMX_U8knh0jDrrbKq9pk8n0UkWHah0if5fvqOjdsIX_W0kh1wmewy6UJvlKRlm2AKFl_e5XMciOwqJjho3Bb0BcnK8MKXcTS1B_5CmFnyPLWXxUh5~abCsucEV6DCua~hNuwQbSw-&fid=9C75C149817A876E1FC8DDFF069F184F&gsid=14a44bd4-d4e2-4e1f-8e89-64aef3c90e5b
[DEBUG] get_content: http://202.109.167.167/c1/2017/06/06_0/EDA1B1AFE209857F82A0377C099BF2F3_20170606_1_1_910_mp4/87DB35B49C78C0950B1D0895C657BBC6.m3u8?arange=0&pm=YtKoxNxJlKD_nqWw~~TpUA_C0EMi4ow7EDldiCI3zoX9ddq~NdbjD2KHo2ELM30Tsvy__mOx4RPV~X0Ol4UUhcqK8r_jXmhcy7FmKfdW3lRO~kTgPDhEyFWbsUvFxU_D7vqCDEu3nVgY~VwoRQhiFOqciO6Qok6_GISqq0VZdXA2rZPFWzSw04YmWltub2_LiRRMcIVlTkcCFion1_KWV_dTcYct4OpPfCxGLGc7wXJciBxFO90NNuVacZaczzLvXK5fqL5onh6g0dcZSs8NthDfJbaWT~rGJeg2LOxEYN05mJE9PbBPtcRlk8BspnevsN_KziU7TEksidjmfuwtRZL77cK2_Xhr6dUPbFg3uX8hSJfczcAhTOOD5FpeqfY_mLJqtF0WaIXXMtNe
[DEBUG] get_content: http://disp.titan.mgtv.com/vod.do?pm=PcpPe_Fp~K7OnwZI8yVwOv4SX1k~dBNcyd93LMHjVYjowZrPxqC~PN3Tx1g40b6JhlbCcK3kSRMAXS_0cSTSa3Jq38ZZbDTeurV8SkDSxcjED1dcgoaLLr4TKy5QM5UxsO5KaS4DUMNQd7hvLACg7fftuSUDryooadh0_vpPPD7TlSHuEAemEQZOoL7FEmLQ4y6PboLkFAmk7nGSov0d5ZS5o~M-&fid=1B026C4FDF76D95B979760DAC7A6DDFB&gsid=7f7b8ca1-bf0d-4c07-a5a5-891f75a040c9
[DEBUG] get_content: http://202.109.167.166/c1/2017/06/06_0/6AD61CA9BC05DB4A0AFF8A59C8A23747_20170606_1_1_642_mp4/D759B11F51358B5AF46AC90BDA54B6A7.m3u8?arange=0&pm=X2DyUZZpR6Ty0SBNeYc~FLG9u~E1aNQwjope4qkvAEV~WdcsSOk~SkFRZcL3p63VvD~gyzRPOM7DhlB~R9D5CItWSoH~oHjYhtIcN6nuKN~AK7eWLfYGLFc0_dnWQsv_5C0sG5Kv7vnqfB6C73xSxG30ALXdffHBr~4ffKAToT6LHAVEZHXXZn1Bp7LRXwEucmwlY3vZzFHzXmCQr2JU~lQJyFBkwYn6fs9BWJxM27ZKgdgaA5hibzE8qR5VNfqYmWVW4D_AIOV1bNOO4WnWaK6SwBJHjO88PvdrumgFkLivU7NPsAhmFbh8Wj2knY4FojeSN0cx3sxJSSIK7qdoQlrIU2OPtZyxnXX4dFwEGv_rpW1VBz17wjPrLwwAvIoe9mENGTVOF_iJJjyM
[DEBUG] get_content: http://disp.titan.mgtv.com/vod.do?pm=2KKUEkLUullI83vii5zrbC5XE9TGfaQgQULlUDUl42n8R0Ikt1pZ~d14ejsHANwnDHHbXeRZMW6IObyJqnh1VmM8sqjOinyYKzEv4TCA9yi~9ArcSZGGu_Weo4Q~L1nWSBHiqgYSSLisaE9qDNYSxtUI5QJwKxvSdtdXXjbEERf8jWritSgnT35QoUrw~1cnqCiemMukU88awBB38jTLEkIcsh8-&fid=D2816607B908C9FE58FAC13500246F3A&gsid=55ff43b7-977e-48af-93e1-d5d5e2847c80
[DEBUG] get_content: http://202.109.167.172/c1/2017/06/06_0/A35516E1DA7BCBEFC5922BB60F208586_20170606_1_1_407_mp4/74F3608137BFBCCD3162BFA20A1B27F8.m3u8?arange=0&pm=NNN878L33dtya8Fr98peQDSIZKt_7zd~Pw42iXpMHRQsBi7bvT5xpF3soakbX74jQZySLvnDttP_rb727r_HajU5kf4btFKEMzFWfPo08RBChajNxX9C4H4dBccDa3y9ai2c0mHtea1o7Zjw95ztUN9Y4X2ZISpuuvimlDlL4XojHpAdqAywjn~yXXFh0fvt0OFmHooYaTyK9frXmfw6xvPR6Tz04LLtW3RrhYRIzPz34hUQYhqhY0ha~BBXL8CGxxtsvR23K457RHPEw79m5DVKO39T1Z9nDFM1Jj0B2CtkT8xwTVvi2WbrHTcznU8~gtpNulkItqcFIFyQVuoE1jy5abHxyHMA~9a__W2DlETKZLhup~teq7CkdIJCDq_Ct8ohrWartkAojWam
site:                芒果 (MGTV)
title:               择天记 第19集
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd
      container:     ts
      video-profile: 超清
      size:          320.7 MiB (336259432 bytes)
      m3u8_url:      http://202.109.167.167/c1/2017/06/06_0/EDA1B1AFE209857F82A0377C099BF2F3_20170606_1_1_910_mp4/87DB35B49C78C0950B1D0895C657BBC6.m3u8?arange=0&pm=YtKoxNxJlKD_nqWw~~TpUA_C0EMi4ow7EDldiCI3zoX9ddq~NdbjD2KHo2ELM30Tsvy__mOx4RPV~X0Ol4UUhcqK8r_jXmhcy7FmKfdW3lRO~kTgPDhEyFWbsUvFxU_D7vqCDEu3nVgY~VwoRQhiFOqciO6Qok6_GISqq0VZdXA2rZPFWzSw04YmWltub2_LiRRMcIVlTkcCFion1_KWV_dTcYct4OpPfCxGLGc7wXJciBxFO90NNuVacZaczzLvXK5fqL5onh6g0dcZSs8NthDfJbaWT~rGJeg2LOxEYN05mJE9PbBPtcRlk8BspnevsN_KziU7TEksidjmfuwtRZL77cK2_Xhr6dUPbFg3uX8hSJfczcAhTOOD5FpeqfY_mLJqtF0WaIXXMtNe
    # download-with: you-get --format=hd [URL]

    - format:        sd
      container:     ts
      video-profile: 高清
      size:          227.8 MiB (238823168 bytes)
      m3u8_url:      http://202.109.167.166/c1/2017/06/06_0/6AD61CA9BC05DB4A0AFF8A59C8A23747_20170606_1_1_642_mp4/D759B11F51358B5AF46AC90BDA54B6A7.m3u8?arange=0&pm=X2DyUZZpR6Ty0SBNeYc~FLG9u~E1aNQwjope4qkvAEV~WdcsSOk~SkFRZcL3p63VvD~gyzRPOM7DhlB~R9D5CItWSoH~oHjYhtIcN6nuKN~AK7eWLfYGLFc0_dnWQsv_5C0sG5Kv7vnqfB6C73xSxG30ALXdffHBr~4ffKAToT6LHAVEZHXXZn1Bp7LRXwEucmwlY3vZzFHzXmCQr2JU~lQJyFBkwYn6fs9BWJxM27ZKgdgaA5hibzE8qR5VNfqYmWVW4D_AIOV1bNOO4WnWaK6SwBJHjO88PvdrumgFkLivU7NPsAhmFbh8Wj2knY4FojeSN0cx3sxJSSIK7qdoQlrIU2OPtZyxnXX4dFwEGv_rpW1VBz17wjPrLwwAvIoe9mENGTVOF_iJJjyM
    # download-with: you-get --format=sd [URL]

    - format:        ld
      container:     ts
      video-profile: 标清
      size:          146.2 MiB (153329416 bytes)
      m3u8_url:      http://202.109.167.172/c1/2017/06/06_0/A35516E1DA7BCBEFC5922BB60F208586_20170606_1_1_407_mp4/74F3608137BFBCCD3162BFA20A1B27F8.m3u8?arange=0&pm=NNN878L33dtya8Fr98peQDSIZKt_7zd~Pw42iXpMHRQsBi7bvT5xpF3soakbX74jQZySLvnDttP_rb727r_HajU5kf4btFKEMzFWfPo08RBChajNxX9C4H4dBccDa3y9ai2c0mHtea1o7Zjw95ztUN9Y4X2ZISpuuvimlDlL4XojHpAdqAywjn~yXXFh0fvt0OFmHooYaTyK9frXmfw6xvPR6Tz04LLtW3RrhYRIzPz34hUQYhqhY0ha~BBXL8CGxxtsvR23K457RHPEw79m5DVKO39T1Z9nDFM1Jj0B2CtkT8xwTVvi2WbrHTcznU8~gtpNulkItqcFIFyQVuoE1jy5abHxyHMA~9a__W2DlETKZLhup~teq7CkdIJCDq_Ct8ohrWartkAojWam
    # download-with: you-get --format=ld [URL]
```
with https://github.com/soimort/you-get/commit/2344e7eaf441687d8cd817769f90b433d3bd11b7
