### ISSUE TITLE
乐视视频不能下载了

### ISSUE THREAD

**Issue by graminc** [soimort/you-get#1925]
>you-get --debug http://www.le.com/ptv/vplay/29198619.html
[DEBUG] get_content: http://www.le.com/ptv/vplay/29198619.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=29198619&platid=1&splatid=101&format=1&tkey=1284705453&domain
=www.letv.com
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/29198619.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1429, in main
  File "src\you_get\common.py", line 1342, in script_main
  File "src\you_get\common.py", line 1158, in download_main
  File "src\you_get\common.py", line 1422, in any_download
  File "src\you_get\extractors\le.py", line 137, in letv_download
  File "src\you_get\extractors\le.py", line 90, in letv_download_by_vid
  File "src\you_get\extractors\le.py", line 61, in video_info
KeyError: 'playurl'
you-get returned -1

**Comment by rosynirvana** [comment]
乐视都快死了怎么还改接口……

tkey是
```
magic = 185025305
return ror(t, magic % 17) ^ magic
```

endpoint是
```
url = 'http://player-pc.le.com/mms/out/video/playJson?id={}&platid=1&spl    atid=101&format=1&tkey={}&domain=www.le.com&region=cn&source=1000&accesyx=1'    .format(vid,calcTimeKey(int(time.time())))
```

拼url中间还有一步不能对答案的……

**Comment by graminc** [comment]
@rosynirvana  
目前只会使用，还看不懂你说的。感谢回复。

**Comment by skywang00** [comment]
@rosynirvana 
根据你提供的 le.py，手动修改了下最新版的you-get的同名文件，运行后报错
`PS C:\Users\xxx\Downloads\you-get-0.4.715> you-get -i -d http://www.le.com/ptv/vplay/29207824.html
[DEBUG] get_content: http://www.le.com/ptv/vplay/29207824.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=29207824&platid=1&splatid=101&format=1&tkey=1335039149&domain=www.letv.com
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/29207824.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "src\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "src\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "src\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "src\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "src\you_get\extractors\le.py", line 137, in letv_download
    else:
  File "src\you_get\extractors\le.py", line 90, in letv_download_by_vid
    m3u8 = get_content(info2["location"]+suffix,decoded=False)
  File "src\you_get\extractors\le.py", line 61, in video_info

KeyError: 'playurl'
you-get returned -1`

**Comment by rosynirvana** [comment]
@skywang00 

我的代码里写的是 ``` url = 'http://player-pc.le.com/mms/out/video/playJson?id=```
你给出的log里有 
```[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=29207824&platid=1&splatid=101&format=1&tkey=1335039149&domain=www.letv.com```

所以这个“手动修改”大概不正确，diff是这样的
```diff
diff --git a/src/you_get/extractors/le.py b/src/you_get/extractors/le.py
index 9de6c7a..bc034f3 100644
--- a/src/you_get/extractors/le.py
+++ b/src/you_get/extractors/le.py
@@ -26,7 +26,9 @@ def get_key(t):

 def calcTimeKey(t):
     ror = lambda val, r_bits, : ((val & (2**32-1)) >> r_bits%32) |  (val << (32-(r_bits%32)) & (2**32-1))
-    return ror(ror(t,773625421%13)^773625421,773625421%17)
+    magic = 185025305
+    return ror(t, magic % 17) ^ magic
+    #return ror(ror(t,773625421%13)^773625421,773625421%17)


 def decode(data):
@@ -52,9 +54,10 @@ def decode(data):


 def video_info(vid,**kwargs):
-    url = 'http://api.letv.com/mms/out/video/playJson?id={}&platid=1&splatid=101&format=1&tkey={}&domain=www.letv.com'.format(vid,calcTimeKey(int(time.time())))
+    url = 'http://player-pc.le.com/mms/out/video/playJson?id={}&platid=1&splatid=101&format=1&tkey={}&domain=www.le.com&region=cn&source=1000&accesyx=1'.format(vid,calcTimeKey(int(time.time())))
     r = get_content(url, decoded=False)
     info=json.loads(str(r,"utf-8"))
+    info = info['msgs']


     stream_id = None
@@ -73,15 +76,18 @@ def video_info(vid,**kwargs):
             stream_id =sorted(support_stream_id,key= lambda i: int(i[1:]))[-1]

     url =info["playurl"]["domain"][0]+info["playurl"]["dispatch"][stream_id][0]
+    uuid = hashlib.sha1(url.encode('utf8')).hexdigest() + '_0'
     ext = info["playurl"]["dispatch"][stream_id][1].split('.')[-1]
-    url+="&ctv=pc&m3v=1&termid=1&format=1&hwtype=un&ostype=Linux&tag=letv&sign=letv&expect=3&tn={}&pay=0&iscpn=f9051&rateid={}".format(random.random(),stream_id)
+    url = url.replace('tss=0', 'tss=ios')
+    url+="&m3v=1&termid=1&format=1&hwtype=un&ostype=MacOS10.12.4&p1=1&p2=10&p3=-&expect=3&tn={}&vid={}&uuid={}&sign=letv".format(random.random(), vid, uuid)

     r2=get_content(url,decoded=False)
     info2=json.loads(str(r2,"utf-8"))

     # hold on ! more things to do
     # to decode m3u8 (encoded)
-    m3u8 = get_content(info2["location"],decoded=False)
+    suffix = '&r=' + str(int(time.time() * 1000)) + '&appid=500'
+    m3u8 = get_content(info2["location"]+suffix,decoded=False)
     m3u8_list = decode(m3u8)
     urls = re.findall(r'^[^#][^\r]*',m3u8_list,re.MULTILINE)
     return ext,urls
```

**Comment by skywang00** [comment]
@rosynirvana 
还是有问题

> PS C:\Users\xxx\Downloads\you-get-0.4.715> you-get -i http://www.le.com/ptv/vplay/29230109.html
Current Video Supports:
        --format 350 <URL>
        --format 1000 <URL>
        --format 1300 <URL>
        --format 720p <URL>
        --format 1080p <URL>
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
PS C:\Users\xxx\Downloads\you-get-0.4.715> you-get -d http://www.le.com/ptv/vplay/29230109.html
[DEBUG] get_content: http://www.le.com/ptv/vplay/29230109.html
[DEBUG] get_content: http://player-pc.le.com/mms/out/video/playJson?id=29230109&platid=1&splatid=101&format=1&tkey=3428731367&domain=www.le.com&region=cn&source=1000&accesyx=1
Current Video Supports:
        --format 350 <URL>
        --format 1000 <URL>
        --format 1300 <URL>
        --format 720p <URL>
        --format 1080p <URL>
[DEBUG] get_content: http://play.g3proxy.lecloud.com/vod/v2/MjU0LzM5LzEwOS9sZXR2LXV0cy8xNC92ZXJfMDBfMjItMTA5OTU1MzUwNy1hdmMtMjk5NzA5NC1hYWMtMTI4MDAwLTMyNTc5MjAtMTI3ODM5MjcxMS03YWUwMDFiMjM1N2I3NmY1Y2VhMDNiYjEyYmYyNWMwMi0xNDkzODczNDYyMzc2Lm1wNA==?b=3139&mmsid=64590756&tm=1493892805&key=81b38f31953af9a50baa1db7efc25734&platid=1&splatid=101&playid=0&tss=ios&vtype=52&cvid=588473145478&payff=0&pip=9885f0e52832274164bc54cdb67b313c&m3v=1&termid=1&format=1&hwtype=un&ostype=MacOS10.12.4&p1=1&p2=10&p3=-&expect=3&tn=0.9403058125318483&vid=29230109&uuid=30a6b94092ab07e19d68b5a5a7c9331ab6d9f6ec_0&sign=letv
[DEBUG] get_content: http://202.119.25.36/254/39/109/letv-uts/14/ver_00_22-1099553507-avc-2997094-aac-128000-3257920-1278392711-7ae001b2357b76f5cea03bb12bf25c02-1493873462376.m3u8?crypt=24aa7f2e3531&b=3139&nlh=4096&nlt=60&bf=90&p2p=1&video_type=mp4&termid=1&tss=ios&platid=1&splatid=101&its=0&qos=3&fcheck=0&amltag=100&mltag=100&proxy=3086324756,2051539348,467476748&uid=3396487240.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&ntm=1493911200&nkey=bba1e330e268bd1bfc35d1d549a39540&nkey2=2fed690078cd9efb48e117645283111d&geo=CN-17-220-7&mmsid=64590756&tm=1493892805&key=81b38f31953af9a50baa1db7efc25734&playid=0&vtype=52&cvid=588473145478&payff=0&m3v=1&hwtype=un&ostype=MacOS10.12.4&p1=1&p2=10&p3=-&tn=0.9403058125318483&vid=29230109&uuid=30a6b94092ab07e19d68b5a5a7c9331ab6d9f6ec_0&sign=letv&errc=0&gn=136&vrtmcd=109&buss=100&cips=202.114.72.72&r=1493892807317&appid=500
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/29230109.html']
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 722, in create_connection
    raise err
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.715', 'console_scripts', 'you-get')()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.715-py3.6.egg\you_get\__main__.py", line 92, in main
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.715-py3.6.egg\you_get\common.py", line 1429, in main
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.715-py3.6.egg\you_get\common.py", line 1342, in script_main
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.715-py3.6.egg\you_get\common.py", line 1158, in download_main
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.715-py3.6.egg\you_get\common.py", line 1422, in any_download
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.715-py3.6.egg\you_get\extractors\le.py", line 143, in letv_download
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.715-py3.6.egg\you_get\extractors\le.py", line 96, in letv_download_by_vid
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.715-py3.6.egg\you_get\extractors\le.py", line 90, in video_info
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.715-py3.6.egg\you_get\common.py", line 333, in get_content
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.715-py3.6.egg\you_get\common.py", line 310, in urlopen_with_retry
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试 失败。>

**Comment by rosynirvana** [comment]
```urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试 失败。>```
出这种错误提示需要多试几遍

```
./you-get -i 'http://www.le.com/ptv/vplay/29230109.html'
Current Video Supports:
	--format 350 <URL>
	--format 720p <URL>
	--format 1000 <URL>
	--format 1080p <URL>
	--format 1300 <URL>
Site:       Le.com
Title:      思美人10
Type:       MPEG-4 video (video/mp4)
Size:       1272.26 MiB (1334063228 Bytes)
```

**Comment by skywang00** [comment]
@rosynirvana 
“format 1300 ”  是什么格式？
怎么我和你解析出的Current Video Supports都不一样

**Comment by rosynirvana** [comment]
乐视自己在json里标的
实际上是
```
Program 1
    Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 65 kb/s
```
fallback成了720p也有可能

**Comment by skywang00** [comment]
确实是网络问题，已经搞定了
可以直接下载我提供的附件，解压后得到le.py，替换you-get-0.4.715\src\you_get\extractors目录下le.py即可

该文件代码来自rosynirvana提供的 update api #1928
https://github.com/rosynirvana/you-get/blob/5cf63526c6c23ed08619ebe47085440ebdff6b9b/src/you_get/extractors/le.py

[le.py.zip](https://github.com/soimort/you-get/files/976275/le.py.zip)

**Comment by graminc** [comment]
@rosynirvana  @skywang00  我这里还是不行，希望其他人都能解决不能下载的问题。


>you-get --debug  http://www.le.com/ptv/vplay/28538674.html
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/28538674.html']
Traceback (most recent call last):
  File "d:\program files (x86)\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files (x86)\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Portable Software\you-get\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files (x86)\python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files (x86)\python\lib\site-packages\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files (x86)\python\lib\site-packages\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_out
put=json_output, caption=caption)
  File "d:\program files (x86)\python\lib\site-packages\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "d:\program files (x86)\python\lib\site-packages\you_get\common.py", line 1421, in any_download
    m, url = url_to_module(url)
  File "d:\program files (x86)\python\lib\site-packages\you_get\common.py", line 1408, in url_to_module
    return import_module('.'.join(['you_get', 'extractors', SITES[k]])), url
  File "d:\program files (x86)\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "d:\program files (x86)\python\lib\site-packages\you_get\extractors\__init__.py", line 3, in <module>
    from .acfun import *
  File "d:\program files (x86)\python\lib\site-packages\you_get\extractors\acfun.py", line 7, in <module>
    from .le import letvcloud_download_by_vu
  File "d:\program files (x86)\python\lib\site-packages\you_get\extractors\le.py", line 148
    Contact GitHub API Training Shop Blog About
                 ^
SyntaxError: invalid syntax

>

**Comment by rosynirvana** [comment]
@graminc 文件搞坏了，所以语法错误

**Comment by graminc** [comment]
@rosynirvana 
pip uninstall you-get  pip install you-get
卸载重装后，还是老样子。奇怪

**Comment by graminc** [comment]
@rosynirvana 
现在这个commit在develop branch里，升级到develop可用
如果要单独换文件
https://raw.githubusercontent.com/rosynirvana/you-get/develop/src/you_get/extractors/le.py

使用你最新的链接，下载替换后，乐视可以下载了。多谢！

**Comment by graminc** [comment]
@rosynirvana 
Windows 下 安装了 Python，使用pip 怎么把 you-get 升级到 develop版本呢？
谢谢

**Comment by rosynirvana** [comment]
需要git，然后根据项目主页上的
```
pip3 install --upgrade git+https://github.com/soimort/you-get@develop
```

**Comment by graminc** [comment]
Unix Linux 都不会用，也没安装这类系统。

**Comment by rosynirvana** [comment]
git是个软件，不是操作系统

**Comment by graminc** [comment]
@rosynirvana 
https://git-for-windows.github.io/ 
https://git-scm.com/downloads

for Windows 二者一样，对吧？

**Comment by rosynirvana** [comment]
大概不一样，但是你用来升pip应该没问题

**Comment by graminc** [comment]
@rosynirvana 
sha-256 对比发现是一样的，以后学习一下git
感谢这么多的回复
谢谢！
