### ISSUE TITLE
下载视屏的时候出现 you-get: [error] oops, something went wrong. 不能下载。但现在文件没什么问题

### ISSUE THREAD

**Issue by charlie6004** [soimort/you-get#1938]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=EUImlLqgi0A
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=EUImlLqgi0A']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1158, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 333, in get_content
    response = urlopen_with_retry(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 310, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [有点疑惑，希望帮忙看一下。谢谢]

**Comment by rosynirvana** [comment]
装证书
```
cd /Applications/Python\ 3.6/
./Install\ Certificates.command
```
#1687 #1710 #1805 #1832 #1845 #1885

**Comment by charlie6004** [comment]
可以下载了。非常感谢，没想到你能这么快回复。

**Comment by kang0024** [comment]
Hi,

I got similar error too!
``you-get --debug http://www.bilibili.com/video/av6250124/
[DEBUG] get_content: http://www.bilibili.com/video/av6250124/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=10153679&from=miniplay&player=1&sign=0b4e108a17133da5d999c3adebf0afb2
[DEBUG] url_info: http://ws.acgvideo.com/d/ce/10153679-1.flv?wsTime=1494052123&platform=pc&wsSecret2=42d7a6fd3beeac2ee4a05d61f6cdf77a&oi=1938065556&rate=1350
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av6250124/']
Traceback (most recent call last):
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kang0024\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\bilibili.py", line 187, in bilibili_download
    info_only=info_only)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\bilibili.py", line 101, in bilibili_download_by_cid
    _, type_, temp = url_info(url)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 425, in url_info
    response = urlopen_with_retry(request.Request(url))
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 310, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 504, in error
    result = self._call_chain(*args)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "c:\users\kang0024\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: `Forbidden`

I can open it with Chrome but cannot download. What is the problem here?

**Comment by kang0024** [comment]
B站也下载不了了。说是urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by rosynirvana** [comment]
@kang0024 
多试几次

**Comment by kang0024** [comment]
昨天试到今天了。。。
http://www.bilibili.com/video/av6250124

**Comment by rosynirvana** [comment]
@kang0024 
先用 ```you-get -u http://www.bilibili.com/video/av6250124```把url导出来吧

**Comment by kang0024** [comment]
导不出来，你看看

you-get -u --debug http://www.bilibili.com/video/av6250124
[DEBUG] get_content: http://www.bilibili.com/video/av6250124
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=10153679&from=miniplay&player=1&sign=0b4e108a17133da5d999c3adebf0afb2
[DEBUG] url_info: http://ws.acgvideo.com/d/ce/10153679-1.flv?wsTime=1494062798&platform=pc&wsSecret2=080a5a46b63501d80d6bca2dbcc6f8b5&oi=1938065556&rate=1280
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av6250124']
Traceback (most recent call last):
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\baidu\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\bilibili.py", line 187, in bilibili_download
    info_only=info_only)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\bilibili.py", line 101, in bilibili_download_by_cid
    _, type_, temp = url_info(url)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 425, in url_info
    response = urlopen_with_retry(request.Request(url))
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 310, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by rosynirvana** [comment]
等一会儿再试

其实就是```url_info```导致cdn短时间请求数太多了……

**Comment by kang0024** [comment]
恩那我一小时后再试。你那里能下载不？

**Comment by rosynirvana** [comment]
-di不行，-u导出url是可以的
晚些时候我会push一个patch

**Comment by kang0024** [comment]
哦好，先谢过哈。
我等你的patch出了再下载吧，毕竟昨天和今天都试过不行了。

**Comment by rosynirvana** [comment]
又试了一下好像不是```url_info```的请求次数太多
而是api返回的CDN url不对无论怎么访问都会403

需要写一个fall back来选择其他的CDN url
另外不能用```otype=json```，否则限速到10 - 20 KiB，不带referer反而还是50KiB
amusing

**Comment by kang0024** [comment]
前两天还能下载来着，现在无论哪个B站链接都下不了。

**Comment by zhangn1985** [comment]
403.

**Comment by rosynirvana** [comment]
因为有（若干）个CDN挂了呗
然后前端api那边也没处理

**Comment by kang0024** [comment]
嗯等你的patch！

**Comment by rosynirvana** [comment]
现在的情况是：
url: 
1.  http://www.bilibili.com/video/av6250124
成功，有时候会出现一个CDN错误

2. http://bangumi.bilibili.com/anime/1660/play#30134
成功

3. http://bangumi.bilibili.com/anime/5550/play#96035
成功

4. http://www.bilibili.com/video/av10308208/
经常出现所有CDN 403，有时候会成功

5. http://www.bilibili.com/video/av10289657/
所有CDN 403，没成功过
这个视频主Key拿到的三个地址会失败两个，只有最后那个非hd的mp4能成功

**Comment by kang0024** [comment]
我这边的情况：

1. 全部视频2天前还能下载，但是有时会断开下载，然后重新输入you-get xxxx之后还能继续下。
2. 那个视频现在完全是403，不过之前是能下的，下到第18段，然后昨天开始完全403了。你看下要不要也试着下载看看。
3. bangumi域名的下载自从用you-get以来就没成功过。。。囧
4. 随便点开B站首页任何视频都是403。

**Comment by rosynirvana** [comment]
#1698

av6250124整个下载好了

**Comment by kang0024** [comment]
啊
那我这边是什么问题呢？

**Comment by rosynirvana** [comment]
我说你要用#1698的patch啊

**Comment by rosynirvana** [comment]
好吧我知道了，bili估计在调整CDN，所以搞乱了
无限403的视频都是默认用```quality=2```的

**Comment by kang0024** [comment]
那就是只能等对吧？
