### ISSUE TITLE
BiliBIli no longer works.

### ISSUE THREAD

**Issue by liuzhen2008** [soimort/you-get#1949]
`you-get -i --debug http://www.bilibili.com/video/av9425646/
`
```
[DEBUG] get_content: http://www.bilibili.com/video/av9425646/
[DEBUG] get_html: http://www.bilibili.com/video/av9425646/index_1.html
[DEBUG] get_response: http://www.bilibili.com/video/av9425646/index_1.html
[DEBUG] get_html: http://www.bilibili.com/video/av9425646/index_2.html
[DEBUG] get_response: http://www.bilibili.com/video/av9425646/index_2.html
[DEBUG] get_html: http://www.bilibili.com/video/av9425646/index_3.html
[DEBUG] get_response: http://www.bilibili.com/video/av9425646/index_3.html
[DEBUG] get_html: http://www.bilibili.com/video/av9425646/index_4.html
[DEBUG] get_response: http://www.bilibili.com/video/av9425646/index_4.html
[DEBUG] get_html: http://www.bilibili.com/video/av9425646/index_5.html
[DEBUG] get_response: http://www.bilibili.com/video/av9425646/index_5.html
[DEBUG] get_html: http://www.bilibili.com/video/av9425646/index_6.html
[DEBUG] get_response: http://www.bilibili.com/video/av9425646/index_6.html
[DEBUG] get_html: http://www.bilibili.com/video/av9425646/index_7.html
[DEBUG] get_response: http://www.bilibili.com/video/av9425646/index_7.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=16671665&from=miniplay&player=1&sign=a2475d25d661bf9e26bc790a58248956
[DEBUG] url_info: http://ws.acgvideo.com/5/f3/16671665-1.flv?wsTime=1494133982&platform=pc&wsSecret2=16a71cc0649d8bb9463df76681b96596&oi=645487248&rate=1280
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av9425646/']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1158, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 187, in bilibili_download
    info_only=info_only)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 101, in bilibili_download_by_cid
    _, type_, temp = url_info(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 425, in url_info
    response = urlopen_with_retry(request.Request(url))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 310, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by cnbeining** [comment]
Report forwarded to upstream.

**Comment by liuzhen2008** [comment]
Interesting. Let me try develop branch
