### ISSUE TITLE
uninstall and upgrade failed  想要卸载you-get但失败，更新也失败

### ISSUE THREAD

**Issue by zhanghub** [soimort/you-get#1950]
**when uninsatalling, it shows like this:**
卸载时，提示

  C:\Users\Administrator>pip uninstall you-get
Exception:
Traceback (most recent call last):
  File "d:\其他\python\lib\site-packages\pip\basecommand.py", line 211, in main
    status = self.run(options, args)
  File "d:\其他\python\lib\site-packages\pip\commands\uninstall.py", line 76, in
 run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "d:\其他\python\lib\site-packages\pip\req\req_set.py", line 305, in unins
tall
    req.uninstall(auto_confirm=auto_confirm)
  File "d:\其他\python\lib\site-packages\pip\req\req_install.py", line 673, in u
ninstall
    for path in pip.wheel.uninstallation_paths(dist):
  File "d:\其他\python\lib\site-packages\pip\wheel.py", line 512, in unique
    for item in fn(*args, **kw):
  File "d:\其他\python\lib\site-packages\pip\wheel.py", line 531, in uninstallat
ion_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "d:\其他\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py",
 line 1619, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "d:\其他\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py",
 line 1616, in get_metadata
    return self._get(self._fn(self.egg_info, name)).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 12161: inva
lid continuation byte
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

**when upgrading, it shows like this:**
尝试更新时，提示：
   
C:\Users\Administrator>pip3 install --upgrade git+https://github.com/soimort/you
-get@develop
Collecting git+https://github.com/soimort/you-get@develop
  Cloning https://github.com/soimort/you-get (to develop) to c:\users\admini~1\a
ppdata\local\temp\pip-2d8y4v4o-build
  Error [WinError 2] 系统找不到指定的文件。 while executing command git clone -q
 https://github.com/soimort/you-get C:\Users\ADMINI~1\AppData\Local\Temp\pip-2d8
y4v4o-build
Cannot find command 'git'
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

**try several ways in the issues， but it does not work.**
 请问要要怎办？是个新手，求详细教程，试过其他与更新相关问题下的方法，但好像都没用。

**Comment by rosynirvana** [comment]
第一个，参考输出的提示
```
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command
```

第二个，需要装git

这两个操作之间没什么关系，卸载再装还是release，第二个是升级到develop branch

**Comment by skywang00** [comment]
应该是同时安装了python2和python3才会这样吧

我这里win10只安装了python 3.6，发现pip3=pip，两个命令都可以直接用，-V 后都是9.0.1  .....

**Comment by zhanghub** [comment]
@rosynirvana
第一个， 输入python -m pip install --upgrade pip后，
新版下载完毕后，显示如下：
Installing collected packages: pip
  Found existing installation: pip 7.1.2
Exception:
Traceback (most recent call last):
  File "D:\其他\python\lib\site-packages\pip\basecommand.py", line 211, in main
    status = self.run(options, args)
  File "D:\其他\python\lib\site-packages\pip\commands\install.py", line 311, in
run
    root=options.root_path,
  File "D:\其他\python\lib\site-packages\pip\req\req_set.py", line 640, in insta
ll
    requirement.uninstall(auto_confirm=True)
  File "D:\其他\python\lib\site-packages\pip\req\req_install.py", line 673, in u
ninstall
    for path in pip.wheel.uninstallation_paths(dist):
  File "D:\其他\python\lib\site-packages\pip\wheel.py", line 512, in unique
    for item in fn(*args, **kw):
  File "D:\其他\python\lib\site-packages\pip\wheel.py", line 531, in uninstallat
ion_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "D:\其他\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py",
 line 1619, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "D:\其他\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py",
 line 1616, in get_metadata
    return self._get(self._fn(self.egg_info, name)).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 22359: inva
lid continuation byte
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

第二个，我之前也看到别人说要安装git，但是没在以前的问题里搜到，可否详细告知？
跪谢！

**Comment by zhanghub** [comment]
@skywang00  请问要怎么检测自己的是否同时安装了python2和python3，我好像只安装了一次。

**Comment by rosynirvana** [comment]
https://github.com/soimort/you-get/wiki/FAQ
试试FAQ中最后一项的方法

装一个叫git的软件，详细说哪些问题？

**Comment by skywang00** [comment]
@zhanghub 

cmd 或者 powershell 下输入 python -V
V必须大写，会出输出安装的python版本，you-get要求python3 ，目前最新正式版为3.6.1
我觉得你直接卸载已经安装的python，重新去官网下载最新版，然后pip安装 you-get吧

**Comment by zhanghub** [comment]
@skywang00 好的，谢谢啦。

**Comment by zhanghub** [comment]
@rosynirvana 想问一下如何安装git，但在百度搜到了，所以就不麻烦了，谢谢啦。
