### ISSUE TITLE
爱奇艺不能下载

### ISSUE THREAD

**Issue by q6761471** [soimort/you-get#1951]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```Last login: Sun May  7 19:46:58 on ttys000
zhangdembp:~ liuwu$ you-get -i http://www.iqiyi.com/v_19rrifgu4t.html#vfrm=19-9-0-1
you-get: vd: 14 is not handled
you-get: info is {'vd': 14, 'vid': 'e461c62bc3b6016a8dc1c98bafb4e483', 'm3utx': 'http://cache.m.iqiyi.com/mus/text/96678500/e461c62bc3b6016a8dc1c98bafb4e483/afbe8fd3d73448c9//20161212/d4/c8/d3cc840ebf7321140b1daca77422bd23.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=96678500&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1494157787162&qd_sc=26de10d8629b41f89dda6833c9d443b5&qypid=96678500_04022000001000000000_14&qd_k=13a293e7cddc4c1c9e01185034179b21&qd_ip=113.218.171.253&other=', 'm3u': 'http://cache.m.iqiyi.com/mus/96678500/e461c62bc3b6016a8dc1c98bafb4e483/afbe8fd3d73448c9//20161212/d4/c8/d3cc840ebf7321140b1daca77422bd23.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=96678500&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1494157787162&qd_sc=26de10d8629b41f89dda6833c9d443b5&qypid=96678500_04022000001000000000_14&qd_k=13a293e7cddc4c1c9e01185034179b21&qd_ip=113.218.171.253&other='}
site:                爱奇艺 (Iqiyi)
title:               大笑江湖
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: you-get --format=LD [URL]

zhangdembp:~ liuwu$ you-get --format=TD http://www.iqiyi.com/v_19rrifgu4t.html#vfrm=19-9-0-1
you-get: vd: 14 is not handled
you-get: info is {'vd': 14, 'vid': 'e461c62bc3b6016a8dc1c98bafb4e483', 'm3utx': 'http://cache.m.iqiyi.com/mus/text/96678500/e461c62bc3b6016a8dc1c98bafb4e483/afbe8fd3d73448c9//20161212/d4/c8/d3cc840ebf7321140b1daca77422bd23.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=96678500&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1494157814363&qd_sc=2ac5565d63d9d064e58d9b14b9bb2fef&qypid=96678500_04022000001000000000_14&qd_k=a10b8441d373817879d72bcec3b02c7b&qd_ip=113.218.171.253&other=', 'm3u': 'http://cache.m.iqiyi.com/mus/96678500/e461c62bc3b6016a8dc1c98bafb4e483/afbe8fd3d73448c9//20161212/d4/c8/d3cc840ebf7321140b1daca77422bd23.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=96678500&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1494157814363&qd_sc=2ac5565d63d9d064e58d9b14b9bb2fef&qypid=96678500_04022000001000000000_14&qd_k=a10b8441d373817879d72bcec3b02c7b&qd_ip=113.218.171.253&other='}
site:                爱奇艺 (Iqiyi)
title:               大笑江湖
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by q6761471** [comment]
zhangdembp:~ liuwu$ you-get --debug http://www.iqiyi.com/v_19rrifgu4t.html#vfrm=19-9-0-1
[DEBUG] get_response: http://www.iqiyi.com/v_19rrifgu4t.html#vfrm=19-9-0-1
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/96678500/7e1906136495491eb30873d1c3217b8b/?t=1495355270314&sc=41085d26c2482d35b3eba4565c2a3a2b&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: vd: 14 is not handled
you-get: info is {'vd': 14, 'vid': 'e461c62bc3b6016a8dc1c98bafb4e483', 'm3utx': 'http://cache.m.iqiyi.com/mus/text/96678500/e461c62bc3b6016a8dc1c98bafb4e483/afbe8fd3d73448c9//20161212/d4/c8/d3cc840ebf7321140b1daca77422bd23.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=96678500&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1495355270447&qypid=96678500_04022000001000000000_14&qd_k=41085d26c2482d35b3eba4565c2a3a2b&qd_hip=71daaa89&qd_nsc=ad6cbd57afe30bdf3e1dfddead863e57&other=', 'm3u': 'http://cache.m.iqiyi.com/mus/96678500/e461c62bc3b6016a8dc1c98bafb4e483/afbe8fd3d73448c9//20161212/d4/c8/d3cc840ebf7321140b1daca77422bd23.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=96678500&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1495355270447&qypid=96678500_04022000001000000000_14&qd_k=41085d26c2482d35b3eba4565c2a3a2b&qd_hip=71daaa89&qd_nsc=ad6cbd57afe30bdf3e1dfddead863e57&other='}
site:                爱奇艺 (Iqiyi)
title:               大笑江湖
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrifgu4t.html#vfrm=19-9-0-1']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.715', 'console_scripts', 'you-get')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1443, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1354, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1156, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1436, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractor.py", line 52, in download_by_url
    self.download(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/iqiyi.py", line 204, in download
    merge=kwargs['merge'],)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 988, in download_url_ffmpeg
    assert has_ffmpeg_installed(), "FFmpeg not installed."
AssertionError: FFmpeg not installed.

**Comment by rosynirvana** [comment]
> FFmpeg not installed

**Comment by unamezzz** [comment]
C:\Users\xxx>you-get http://baidu.iqiyi.com/watch/01683816243148719998.html --de
bug
[DEBUG] get_response: http://baidu.iqiyi.com/watch/01683816243148719998.html
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://baidu.iqiyi.com/watch/01683816243148719998.html']
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_mai
n
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\you-get.exe\__main__.py", line 9, in <
module>
  File "c:\program files\python36\lib\site-packages\you_get\__main__.py", line 9
2, in main
    main(**kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 144
4, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 135
5, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 115
7, in download_main
    download(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 143
7, in any_download
    m.download(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractor.py", line
41, in download_by_url
    self.prepare(**kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractors\iqiyi.py"
, line 137, in prepare
    self.title = match1(html, '<title>([^<]+)').split('-')[0]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by rosynirvana** [comment]
for ```baidu.iqiyi```, it's like https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/ku6.py#L44

find the url in the iframe, then find iqiyi url in the html of that url
```
"site_play_url":"http:\/\/www.iqiyi.com\/w_19ru11f7it.html"
```

**Comment by unamezzz** [comment]
@rosynirvana 英语差看不懂..

**Comment by rosynirvana** [comment]
和ku6里面的实现一样，先从iframe里找url，然后再从那个url返回的html里找iqiyi的url

写给开发者的，如果你不打算动手patch就不用管

**Comment by unamezzz** [comment]
@rosynirvana 是自己肉眼在iqiyi那找到真正的视频源url然后写正则规则进py自动化，还是复制ku6的实现过来就行了？（ku6跟iqiyi不是一家应该不同吧）

**Comment by rosynirvana** [comment]
第一个iframe的正则是一样的
第二个不一样，不过是什么样式的第一个回复里面也标出来了

**Comment by unamezzz** [comment]
好的我研究研究

**Comment by lki2019** [comment]
<pre><code>
[mp4 @ 03fe74c0] pts has no value
    Last message repeated 1 times
[hls,applehttp @ 031188a0] Opening 'http://data.video.iqiyi.com/videos/v0/201511
16/66/16/5bd74bc57c217528781bc6bf9a1c27f2.ts?qdv=1&qypid=96678500_04022000001000
000000_4&start=5189999&end=9585469&hsize=46953&tag=1&v=&contentlength=2147712&qd
_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1502444339552&qd_ip=3a1240ec&qd_p=3a1240ec&
qd_k=0c1ac9905359a910b42d86e9b2efc93e&qd_sc=bf4bdc24ef9010acfa1f60a28835d5b4' fo
r reading
[mp4 @ 03fe74c0] pts has no value
frame=30208 fps=142 q=-1.0 size=  234240kB time=00:21:35.27 bitrate=1481.5kbits/
[hls,applehttp @ 031188a0] Opening 'http://data.video.iqiyi.com/videos/v0/201511
16/66/16/5bd74bc57c217528781bc6bf9a1c27f2.ts?qdv=1&qypid=96678500_04022000001000
000000_4&start=6038590&end=11151699&hsize=46953&tag=1&v=&contentlength=2010660&q
d_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1502444339552&qd_ip=3a1240ec&qd_p=3a1240ec
&qd_k=0c1ac9905359a910b42d86e9b2efc93e&qd_sc=bf4bdc24ef9010acfa1f60a28835d5b4' f
or reading
[mp4 @ 03fe74c0] pts has no value
frame=30381 fps=143 q=-1.0 size=  236032kB time=00:21:42.19 bitrate=1484.9kbits/</code></pre>


可以下载的，只是下载途中回有些带颜色的提示而已 比如[mp4 @ 03fe74c0] pts has no value

我感觉可能如果生成格式是flv 这个提示应该就没了

建议用最新的FFmpeg

**Comment by lki2019** [comment]
在这反馈一下吧，就不单独开主题了

<pre><code>Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get -di http://www.iqiyi.com/v_19rr8bnuac.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rr8bnuac.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/745870200
[DEBUG] get_content: http://www.iqiyi.com/v_19rr8bnuac.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/745870200/a2a578d8f97b54d04ba
e7058bf12fea7/?t=1502445345989&sc=e8387edc23d7516332e9b42515af8374&src=76f90cbd9
2f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               围炉音乐会2017_20170803期
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
      m3u8_url:      http://cache.m.iqiyi.com/mus/206675201/186714e395fda393e42e
54925fcf6abc/afbe8fd3d73448c9//20170802/e2/3d/b20fb48c4d40cab491312ca945841e2c.m
3u8?qd_originate=tmts_py&tvid=745870200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_31
2&prv=&previewType=&previewTime=&from=&qd_time=1502445388916&qd_p=3a1240ec&qd_as
c=3e399c5b290d882da516ab6fee12d300&qypid=745870200_04022000001000000000_14&qd_k=
e8387edc23d7516332e9b42515af8374&vf=289c777ef19cfaa2f30ce37d4eed9086&np_tag=ngin
x_part_tag
    # download-with: you-get --format=TD [URL]

    - format:        TD_H265
      container:     m3u8
      video-profile: 720p H265
      m3u8_url:      http://cache.m.iqiyi.com/mus/206675201/1442ee1d4c1d073cd014
631d1a8e1858/afbe8fd3d73448c9//20170802/be/15/58c9f035077dba57788ce726fa0a974b.m
3u8?qd_originate=tmts_py&tvid=745870200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_31
2&prv=&previewType=&previewTime=&from=&qd_time=1502445388916&qd_p=3a1240ec&qd_as
c=c4ce94cba5b861c3b439c1db1e619b92&qypid=745870200_04022000001000000000_17&qd_k=
e8387edc23d7516332e9b42515af8374&vf=92e7ea1d43ed57c0e6edbcbed0d067a6&np_tag=ngin
x_part_tag
    # download-with: you-get --format=TD_H265 [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
      m3u8_url:      http://cache.m.iqiyi.com/mus/206675201/a2a578d8f97b54d04bae
7058bf12fea7/afbe8fd3d73448c9//20170802/45/25/96a05391c911690e6d422cc6a9a63c4a.m
3u8?qd_originate=tmts_py&tvid=745870200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_31
2&prv=&previewType=&previewTime=&from=&qd_time=1502445388916&qd_p=3a1240ec&qd_as
c=c28a13de0e527c572ad9b69d1dab70d2&qypid=745870200_04022000001000000000_2&qd_k=e
8387edc23d7516332e9b42515af8374&vf=849e62289a05baa9414cac8a208ab502&np_tag=nginx
_part_tag
    # download-with: you-get --format=HD [URL]

    - format:        HD_H265
      container:     m3u8
      video-profile: 540p H265
      m3u8_url:      http://cache.m.iqiyi.com/mus/206675201/257008ea0438d2f0f2a0
d55b4d4dd4ca/afbe8fd3d73448c9//20170802/c6/d3/0f0486383bfa143b591f2df545ab823a.m
3u8?qd_originate=tmts_py&tvid=745870200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_31
2&prv=&previewType=&previewTime=&from=&qd_time=1502445388916&qd_p=3a1240ec&qd_as
c=9f3927276c37eac29ec8e5a8869192b7&qypid=745870200_04022000001000000000_21&qd_k=
e8387edc23d7516332e9b42515af8374&vf=4c0d200f770165a170ab98dff84070ed&np_tag=ngin
x_part_tag
    # download-with: you-get --format=HD_H265 [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
      m3u8_url:      http://cache.m.iqiyi.com/mus/206675201/b4f70eb15a1144ca5902
be7d2e479fa0/afbe8fd3d73448c9//20170802/db/16/b047911d836b71488b2089b3ccf103e3.m
3u8?qd_originate=tmts_py&tvid=745870200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_31
2&prv=&previewType=&previewTime=&from=&qd_time=1502445388916&qd_p=3a1240ec&qd_as
c=58b05e93594e1e49dcd27a083df56da5&qypid=745870200_04022000001000000000_1&qd_k=e
8387edc23d7516332e9b42515af8374&vf=35a950a0aa436d6308043342270c9e05&np_tag=nginx
_part_tag
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
      m3u8_url:      http://cache.m.iqiyi.com/mus/206675201/3d9449de74d595738f74
c4936a26c515/afbe8fd3d73448c9//20170802/ec/cf/708065f1957602f234ddaff9a715eda7.m
3u8?qd_originate=tmts_py&tvid=745870200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_31
2&prv=&previewType=&previewTime=&from=&qd_time=1502445388916&qd_p=3a1240ec&qd_as
c=b01d6d1c4c414384d3136c20ebf82284&qypid=745870200_04022000001000000000_96&qd_k=
e8387edc23d7516332e9b42515af8374&vf=57678ad02349abc8b65a983d173b89af&np_tag=ngin
x_part_tag
    # download-with: you-get --format=LD [URL]


C:\Users\Administrator>you-get -d http://www.iqiyi.com/v_19rr8bnuac.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rr8bnuac.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/745870200
[DEBUG] get_content: http://www.iqiyi.com/v_19rr8bnuac.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/745870200/a2a578d8f97b54d04ba
e7058bf12fea7/?t=1502445369235&sc=d77ebce6fb9d8290660c45de7ce5fc3b&src=76f90cbd9
2f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               围炉音乐会2017_20170803期
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      m3u8_url:      http://cache.m.iqiyi.com/mus/206675201/186714e395fda393e42e
54925fcf6abc/afbe8fd3d73448c9//20170802/e2/3d/b20fb48c4d40cab491312ca945841e2c.m
3u8?qd_originate=tmts_py&tvid=745870200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_31
2&prv=&previewType=&previewTime=&from=&qd_time=1502445412163&qd_p=3a1240ec&qd_as
c=eadc3561b9b89e4df59fdb0ed6796549&qypid=745870200_04022000001000000000_14&qd_k=
d77ebce6fb9d8290660c45de7ce5fc3b&vf=42b418c69d9cd3ae170e1b6e178fa9ca&np_tag=ngin
x_part_tag
    # download-with: you-get --format=TD [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -i http://cache.m.iqiyi.com/mus/206675201/186714e395fda393e42e54925fcf
6abc/afbe8fd3d73448c9//20170802/e2/3d/b20fb48c4d40cab491312ca945841e2c.m3u8?qd_o
riginate=tmts_py&tvid=745870200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&p
reviewType=&previewTime=&from=&qd_time=1502445412163&qd_p=3a1240ec&qd_asc=eadc35
61b9b89e4df59fdb0ed6796549&qypid=745870200_04022000001000000000_14&qd_k=d77ebce6
fb9d8290660c45de7ce5fc3b&vf=42b418c69d9cd3ae170e1b6e178fa9ca&np_tag=nginx_part_t
ag -c copy -bsf:a aac_adtstoasc 围炉音乐会2017_20170803期.mp4
ffmpeg version N-86755-g0780ad9 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --e
nable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --
enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv
--enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-li
bfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug -
-enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enabl
e-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-li
bsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolam
e --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx
 --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable
-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 67.100 / 55. 67.100
  libavcodec     57.100.104 / 57.100.104
  libavformat    57. 75.100 / 57. 75.100
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 95.100 /  6. 95.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
[hls,applehttp @ 03158920] Opening 'http://data.video.qiyi.com/videos/v0/2017080
2/e2/3d/e1730a86a13d789348badba7f1375e4e.dbts?qdv=1&qypid=745870200_040220000010
00000000_14&start=0&end=772680&contentlength=772680&sd=1400&durr=9000&qd_uid=&qd
_vip=0&qd_src=3_31_312&qd_tm=1502445413951&qd_ip=3a1240ec&qd_p=3a1240ec&qd_k=d77
ebce6fb9d8290660c45de7ce5fc3b&qd_sc=aac301d8822b154f517c9be4202ca9d4' for readin
g
Input #0, hls,applehttp, from 'http://cache.m.iqiyi.com/mus/206675201/186714e395
fda393e42e54925fcf6abc/afbe8fd3d73448c9//20170802/e2/3d/b20fb48c4d40cab491312ca9
45841e2c.m3u8?qd_originate=tmts_py&tvid=745870200&bossStatus=0&qd_vip=0&px=&qd_s
rc=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1502445412163&qd_p=3a12
40ec&qd_asc=eadc3561b9b89e4df59fdb0ed6796549&qypid=745870200_0402200000100000000
0_14&qd_k=d77ebce6fb9d8290660c45de7ce5fc3b&vf=42b418c69d9cd3ae170e1b6e178fa9ca&n
p_tag=nginx_part_tag':
  Duration: 01:09:23.00, start: 1.400000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709)
, 1280x720, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: eac3 ([135][0][0][0] / 0x0087), 48000 Hz, stereo, fltp,
96 kb/s
    Metadata:
      variant_bitrate : 0
[AVBSFContext @ 04407980] Codec 'eac3' (86057) is not supported by the bitstream
 filter 'aac_adtstoasc'. Supported codecs are: aac (86018)
Error initializing bitstream filter: aac_adtstoasc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times</code></pre>


不知道这是什么原因

**Comment by rosynirvana** [comment]
```
./you-get -di http://www.iqiyi.com/v_19rr8bnuac.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rr8bnuac.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/745870200
[DEBUG] get_content: http://www.iqiyi.com/v_19rr8bnuac.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/745870200/a2a578d8f97b54d04bae7058bf12fea7/?t=1502447095307&sc=43f70b518bc29e0b584d863fc419277f&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               围炉音乐会2017_20170803期
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
      m3u8_url:      http://cache.m.iqiyi.com/mus/206675201/186714e395fda393e42e54925fcf6abc/afbe8fd3d73448c9//20170802/e2/3d/b20fb48c4d40cab491312ca945841e2c.m3u8?qd_originate=tmts_py&tvid=745870200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1502447095526&qd_p=7d2db2af&qd_asc=2f87ee1cb017d11c50c8742061c7cef8&qypid=745870200_04022000001000000000_14&qd_k=43f70b518bc29e0b584d863fc419277f&vf=4208b6e545b8024967f906a537e3e4a1&np_tag=nginx_part_tag
    # download-with: you-get --format=TD [URL]


ffmpeg -i http://cache.m.iqiyi.com/mus/206675201/186714e395fda393e42e54925fcf6abc/afbe8fd3d73448c9//20170802/e2/3d/b20fb48c4d40cab491312ca945841e2c.m3u8\?qd_originate\=tmts_py\&tvid\=745870200\&bossStatus\=0\&qd_vip\=0\&px\=\&qd_src\=3_31_312\&prv\=\&previewType\=\&previewTime\=\&from\=\&qd_time\=1502447095526\&qd_p\=7d2db2af\&qd_asc\=2f87ee1cb017d11c50c8742061c7cef8\&qypid\=745870200_04022000001000000000_14\&qd_k\=43f70b518bc29e0b584d863fc419277f\&vf\=4208b6e545b8024967f906a537e3e4a1\&np_tag\=nginx_part_tag -c copy out.mp4
```
