### ISSUE TITLE
代理设置，下载youtube视频问题

### ISSUE THREAD

**Issue by fzhqzxguest** [soimort/you-get#1969]
发现代理设置后，用you-get --http-proxy 127.0.0.1:8080 ’https://www.youtube.com/watch?v=0RLBY_yzzcU‘下载youtube不行，而用you-get https://www.youtube.com/watch?v=0RLBY_yzzcU，就可以下，不知为何？

**Comment by fzhqzxguest** [comment]
C:\Python36>you-get --debug --http-proxy 127.0.0.1:8080 https://www.youtube.com/watch?v=0RLBY_yzzcU
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=0RLBY_yzzcU
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=0RLBY_yzzcU']
Traceback (most recent call last):
  File "c:\python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\python36\lib\http\client.py", line 964, in send
    self.connect()
  File "c:\python36\lib\http\client.py", line 1392, in connect
    super().connect()
  File "c:\python36\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\python36\lib\socket.py", line 722, in create_connection
    raise err
  File "c:\python36\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "c:\python36\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "c:\python36\lib\site-packages\you_get\extractors\youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "c:\python36\lib\site-packages\you_get\common.py", line 333, in get_content
    response = urlopen_with_retry(req)
  File "c:\python36\lib\site-packages\you_get\common.py", line 310, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\python36\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>

**Comment by rosynirvana** [comment]
研究研究你的代理具体是怎么部署的
