### ISSUE TITLE
bilibili video cannot be downloaded，because of "Forbidden"

### ISSUE THREAD

**Issue by JiaxiangBU** [soimort/you-get#1970]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get --debug http://www.bilibili.com/video/av10490784/
[DEBUG] get_content: http://www.bilibili.com/video/av10490784/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=17323965&from=miniplay&player=1&sign=f029df826657ebfea024ff784fb3818c
[DEBUG] url_info: http://ws.acgvideo.com/e/1f/17323965-1.flv?wsTime=1494610838&platform=pc&wsSecret2=b1f21d2442183e258607ec198c46eca3&oi=826533490&rate=1280
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av10490784/']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1158, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 187, in bilibili_download
    info_only=info_only)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 101, in bilibili_download_by_cid
    _, type_, temp = url_info(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 425, in url_info
    response = urlopen_with_retry(request.Request(url))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 310, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
升级到develop branch，或#1698

**Comment by kang0024** [comment]
小白借贴问怎么升级#1698？我这边B站任何视频都是403。

**Comment by rosynirvana** [comment]
如果不用git
用这个 https://raw.githubusercontent.com/rosynirvana/you-get/fix-bilibili-redirect/src/you_get/extractors/bilibili.py

替换you_get下的同名文件

**Comment by kang0024** [comment]
替换后出现错误

you-get --debug http://www.bilibili.com/video/av8875590/index_3.html
[DEBUG] url_locations: http://www.bilibili.com/video/av8875590/index_3.html
[DEBUG] get_content: http://www.bilibili.com/video/av8875590/index_3.html
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av8875590/index_3.html']
Traceback (most recent call last):
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\baidu\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\bilibili.py", line 231, in bilibili_download
    assert flashvars
AssertionError

**Comment by kang0024** [comment]
不过这个之前不能下的现在可以了

http://www.bilibili.com/video/av8592685/

**Comment by rosynirvana** [comment]
那个视频是登录可见的，需要挂cookies
```
./you-get -i -c '~/Downloads/c.txt' 'http://www.bilibili.com/video/av8875590/index_3.html'
sid 5z6qjp6l .bilibili.com
Site:       bilibili.com
Title:      【英剧-悬疑】Inside No.9 Season 1-2（01-06）(3)-3、2.3
Type:       Flash video (video/x-flv)
Size:       274.29 MiB (287617215 Bytes)
```

**Comment by kang0024** [comment]
不好意思，具体应该怎么做呢？真的是个小白，试了几行代码都不行。登录了火狐和chrome了，应该已经有cookie了对吧？

**Comment by rosynirvana** [comment]
登录后，打开任意视频，然后把firefox上把cookie导出（装插件 Export Cookies）
把导出的cookie文件放在某个路径，然后用```-c```告诉```you-get```cookie所在的位置
例如cookie文件放在PATH，就是
```you-get  -c PATH url```

**Comment by kang0024** [comment]
可以下载了，谢谢大神！
