### ISSUE TITLE
Unable to fetch Tudou videos | 土豆视频无法下载

### ISSUE THREAD

**Issue by chenyiping1995** [soimort/you-get#1986]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
```
$ you-get -V
you-get: version 0.4.715, a tiny downloader that scrapes the web.
```
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[DEBUG] get_decoded_html: http://video.tudou.com/v/XMjQ0NDIyMTk5Mg==.html
[DEBUG] get_response: http://video.tudou.com/v/XMjQ0NDIyMTk5Mg==.html
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://video.tudou.com/v/XMjQ0NDIyMTk5Mg==.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.715', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1158, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/extractors/tudou.py", line 47, in tudou_download
    title = r1(r'\Wkw\s*[:=]\s*[\'\"]([^\n]+?)\'\s*\n', html).replace("\\'", "\'")
AttributeError: 'NoneType' object has no attribute 'replace'
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> My Little Pony is great! (Yikes)

**Comment by rosynirvana** [comment]
和 #1935 一样
