### ISSUE TITLE
网易云音乐无法使用

### ISSUE THREAD

**Issue by HungryGuyLee** [soimort/you-get#1990]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by HungryGuyLee** [comment]
貌似前天还能使用

**Comment by martin-colorwolf** [comment]
还是不行啊

**Comment by happyhuaer** [comment]
是呀，不能用了呢，可惜呀

**Comment by NoAnyLove** [comment]
返回的JSON数据中，`'mp3Url': None`

**Comment by Fatalerr** [comment]
Hi, 
All the boxes above are checked. I use `you-got` in **WIN7 + CMDER**.  and below is the log:

```
R:\you-get
$ ping music.163.com
Pinging music.163.com [59.111.160.195] with 32 bytes of data:
Reply from 59.111.160.195: bytes=32 time=34ms TTL=55
Reply from 59.111.160.195: bytes=32 time=34ms TTL=55
Reply from 59.111.160.195: bytes=32 time=32ms TTL=55
Reply from 59.111.160.195: bytes=32 time=32ms TTL=55

Ping statistics for 59.111.160.195:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 32ms, Maximum = 34ms, Average = 33ms

R:\you-get
$ you-get -i "http://music.163.com/song?id=26200408"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

R:\you-get
$ you-get --debug -i "http://music.163.com/song?id=26200408"
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=26200408&ids=[26200408]&csrf_token=
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/song?id=26200408']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1429, in main
  File "src\you_get\common.py", line 1342, in script_main
  File "src\you_get\common.py", line 1158, in download_main
  File "src\you_get\common.py", line 1422, in any_download
  File "src\you_get\extractors\netease.py", line 133, in netease_download
  File "src\you_get\extractors\netease.py", line 70, in netease_cloud_music_download
  File "src\you_get\extractors\netease.py", line 110, in netease_song_download
AttributeError: 'NoneType' object has no attribute 'split'
you-get returned -1

```

**Comment by sutra** [comment]
> 返回的JSON数据中，'mp3Url': None

确实，抓包发现它有另一个请求：

```
curl 'http://music.163.com/weapi/song/enhance/player/url?csrf_token=d0f8973e609d81ddb107f20368bad3d6' -H 'Origin: http://music.163.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: */*' -H 'Referer: http://music.163.com/' -H 'Cookie: vjuids=362b437d8.15707ad39a0.0.47097c6b43a9f; vjlast=1473302576.1473302576.30; _ntes_nnid=faf86bd7306623535d8e8f4c9c781bdf,1473302576097; _ntes_nuid=faf86bd7306623535d8e8f4c9c781bdf; vinfo_n_f_l_n3=18928227a3e3c7e6.1.0.1473302576154.0.1473302719260; JSESSIONID-WYYY=6dEzOr6PpFGh21zikjWG96NiYMUhRAyact3%5C%5C9kUiTXEm%2BHqjiC%2F4X4dU%5ClooPARuEGapRyPEJe7I5d9srwfqPmCccY8SOoMkzokOyk7EWs84Fdu7rSf0EgnUc2jiiIRtKxKlKIWsF2uRjVbItpKu3%2BRnBbH%2FzIB%5CpulN%2FRvQRUxcczW%3A1496218324910; _iuqxldmzr_=32; MUSIC_U=833a6cdf683b30833f9a97acbfec206131357fd1443cfdfd02c8b72f0636c04636ebd13021adbd4518715b5b8ad00d5aaf9e62a8590fd08a; __remember_me=true; __csrf=d0f8973e609d81ddb107f20368bad3d6; __utma=94650624.1613387538.1490082868.1496214748.1496217978.4; __utmb=94650624.2.10.1496217978; __utmc=94650624; __utmz=94650624.1491869756.2.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)' -H 'Proxy-Connection: keep-alive' --data 'params=4PbxDJQuqzP9P519SJNjdDmx6vJCqmRgs4W3ixrYoqjNqBHtqI5j9Csgs%2F9tSs2zlAx9QdC%2FUqjJ0ZXBgDPVcWQAj6PdNkX1q8sswDlLOzDIBdTD%2B%2FoFWV0LJoZcZXSZVSqZfzYPchDvGMoocFAv1yX%2BIGn3kfQ8MW%2FoDpgzZQKxTzZOMz0wVR9fYmm5qVBB&encSecKey=1547b57594d10ec2ede05ec3a0e4ab51293815a33c446b01d7c82d758d265b867e474f7c92b3ddf8a05069005333a15b93ee11ce7ce334ebbcd6c317947d8b5f100ceddddca25b9fb3547ab5b2cbdc51fc3c6400e822e697280e5182f01ef7775f502ab57d53e59afc26b573639fb4f4ea1453cbb5828eaf7e5fac5a0efb062c' --compressed | jshon
```

```
{
 "data": [
  {
   "id": 31445554,
   "url": "http:\/\/m10.music.126.net\/20170531164222\/5fb8b2a98b0f5a282b8f04b6235abc7e\/ymusic\/3b42\/666c\/658d\/dd9fd710bf78b291bc63861a335588f6.mp3",
   "br": 128000,
   "size": 3042785,
   "md5": "dd9fd710bf78b291bc63861a335588f6",
   "code": 200,
   "expi": 1200,
   "type": "mp3",
   "gain": 3.6878000000000002,
   "fee": 0,
   "uf": null,
   "payed": 0,
   "flag": 0,
   "canExtend": false
  }
 ],
 "code": 200
}
```

**Comment by rosynirvana** [comment]
in favor of #2074
