### ISSUE TITLE
任何时候的you-get: [error] oops, something went wrong还有spm错误

### ISSUE THREAD

**Issue by cok3307788** [soimort/you-get#1993]
本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
C:\Users\pc>you-get -i --debug http://video.tudou.com/v/XMjc3MTI0NTAwMA==.html
[DEBUG] get_decoded_html: http://video.tudou.com/v/XMjc3MTI0NTAwMA==.html
[DEBUG] get_response: http://video.tudou.com/v/XMjc3MTI0NTAwMA==.html
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://video.tudou.com/v/XMjc3MTI0NTAwMA==.html']
Traceback (most recent call last):
  File "d:\program files\python\python36\lib\runpy.py", line 193, in _run_module
_as_main
    "__main__", mod_spec)
  File "d:\program files\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python\Python36\Scripts\you-get.exe\__main__.py", line
9, in <module>
  File "d:\program files\python\python36\lib\site-packages\you_get\__main__.py",
 line 92, in main
    main(**kwargs)
  File "d:\program files\python\python36\lib\site-packages\you_get\common.py", l
ine 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files\python\python36\lib\site-packages\you_get\common.py", l
ine 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "d:\program files\python\python36\lib\site-packages\you_get\common.py", l
ine 1158, in download_main
    download(url, **kwargs)
  File "d:\program files\python\python36\lib\site-packages\you_get\common.py", l
ine 1422, in any_download
    m.download(url, **kwargs)
  File "d:\program files\python\python36\lib\site-packages\you_get\extractors\tu
dou.py", line 47, in tudou_download
    title = r1(r'\Wkw\s*[:=]\s*[\'\"]([^\n]+?)\'\s*\n', html).replace("\\'", "\'
")
AttributeError: 'NoneType' object has no attribute 'replace'
```

如果您有其他附言：（我已经反复uninstall和install好几次了）
以下是任何URL都会出现的问题，只要开始运行实际功能
> you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
'spm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by rosynirvana** [comment]
还是这个
#1935
