### ISSUE TITLE
acfun视频解析失败

### ISSUE THREAD

**Issue by gasry1989** [soimort/you-get#1994]
C:\Users\Administrator\Downloads\you-get-develop>python you-get -u -t 3 --debug http://www.acfun.cn/v/ac2581016
[DEBUG] get_response: http://www.acfun.cn/v/ac2581016
[DEBUG] get_response: http://www.acfun.tv/video/getVideo.aspx?id=3254033
[DEBUG] get_content: http://api.aixifan.com/plays/3254033
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519d032263f8&video_id=CMjc5MTIwOA==&embsig=1_1495368829_bb305485d541d90add712e5fcaf0d4fe
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=CMjc5MTIwOA==&ct=85&sign=MXwxNDk1MzY4ODMwfDRkZTU4ZmRkYzU0YzY1OTI4OGE5OTcyNjZlMWE0MDM0
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac2581016']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\common.py", line 1157, in download_main    download(url, **kwargs)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\common.py", line 1437, in any_download    m.download(url, **kwargs)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\extractors\acfun.py", line 90, in acfun_download    **kwargs)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\extractors\acfun.py", line 55, in acfun_download_by_vid
    youku_open_download_by_vid(client_id='908a519d032263f8', vid=sourceId, title=title, output_dir=output_dir,merge=merge, info_only=info_only, embsig = embsig, **kwargs)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\extractors\youku.py", line 375, in open_download_by_vid
    self.prepare(api_url = api85_url, api12_url = api86_url, ctype = 86, **kwargs)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\extractors\youku.py", line 172, in prepare
    headers={'Referer': 'http://static.youku.com/'}
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

**Comment by soimort** [comment]
#1914
