### ISSUE TITLE
无法在vlc内播放

### ISSUE THREAD

**Issue by Ninzero** [soimort/you-get#1999]
`[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=fiUfHNmsQ5w
[DEBUG] get_content: https://www.youtube.com/watch?v=fiUfHNmsQ5w
[DEBUG] get_content: https://www.youtube.com/api/timedtext?sparams=asr_langs%2Ccaps%2Cv%2Cexpire&hl=zh_HK&signature=BF4DDA9482624DDC0DC6D08D3C71E7FC44431550.54BF3B552AD823D8C5CF1175FFB69C92C5942D01&asr_langs=en%2Cko%2Cja%2Cde%2Cru%2Cnl%2Cfr%2Cpt%2Ces%2Cit&v=fiUfHNmsQ5w&caps=asr&key=yttt1&expire=1495489110&kind=asr&lang=en
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-vfl4Xq3l4/zh_HK/base.js
site:                YouTube
title:               GWENT: THE WITCHER CARD GAME | PUBLIC BETA PREVIEW
stream:
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          460.3 MiB (482687685 bytes)
    # download-with: you-get --itag=22 [URL]

you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=fiUfHNmsQ5w']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractor.py", line 52, in download_by_url
    self.download(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractor.py", line 208, in download
    av=stream_id in self.dash_streams)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 771, in download_urls
    launch_player(player, urls)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 213, in launch_player
    subprocess.call(shlex.split(player) + list(urls))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'vlc'`

**Comment by Ninzero** [comment]
我安装了vlc 而且是最新版，但不知道为什么找不到vlc

**Comment by rosynirvana** [comment]
```-p```的含义是通过命令行传给下游，那么```-p vlc```就要保证必须有一个叫vlc的二进制文件在PATH里

这个不算```you-get```项目本身的问题，建议去查查如何从命令行启动vlc这类。各OS各种安装方法下肯定是不同的。

**Comment by Ninzero** [comment]
就是说我只要把用命令行启动vlc的命令输入到-p后面就行了是吗

**Comment by rosynirvana** [comment]
大体上是这个意思

但并非对于所有站点都适用

**Comment by Sense25** [comment]
windows下将vlc.exe所在路径加入到环境变量的path变量就可以了,不过播放放起来是一段一段的，youtube视频也要在vlc设置代理
