### ISSUE TITLE
miaopai.py crash

### ISSUE THREAD

**Issue by rosynirvana** [soimort/you-get#2000]
```
$you-get -di 'http://weibo.com/tv/v/13458f8dda3eb9310bd1c4e7c02ad747?fid=1034:13458f8dda3eb9310bd1c4e7c02ad747'
[DEBUG] get_content: http://video.weibo.com/show?fid=1034:13458f8dda3eb9310bd1c4e7c02ad747&type=mp4
[DEBUG] url_info: http://us.sinaimg.cn/000eqcvhjx06XxBPBWV1050d010000L10k01.m3u8?KID=unistore,video&Expires=1495469380&ssig=jPCDDcFwdy
Site:       miaopai
Title:      一美国高中生制作了几分钟的短片，点击量几百万，生动透彻地介绍了狭义相对论的精髓，并由此获得了硅谷科技大佬设立的“科学突破奖”25万美元！一起来感受下我的听译吧#分分钟涨姿势#《看待狭义相对论的几个酷炫角度》#酷炫科普小短片#【第35期】
Type:       Unknown type (None)
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://weibo.com/tv/v/13458f8dda3eb9310bd1c4e7c02ad747?fid=1034:13458f8dda3eb9310bd1c4e7c02ad747']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/miaopai.py", line 31, in miaopai_download
    miaopai_download_by_fid(fid, output_dir, merge, info_only)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/miaopai.py", line 23, in miaopai_download_by_fid
    print_info(site_info, title, type_, size)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1078, in print_info
    print("Size:      ", round(size / 1048576, 2), "MiB (" + str(size) + " Bytes)")
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

weibo videos could be m3u8 now.

**Comment by rosynirvana** [comment]
This is the 2000th issues or pr

**Comment by cnbeining** [comment]
So they are using M3U on mobile? Nice move I would say.

**Comment by rosynirvana** [comment]
mp4 for short videos and m3u8 for those long ones, I guess

**Comment by airdge** [comment]
如果获取到的是M3U8
http://us.sinaimg.cn/001IWeDnjx06XxBP8QWY0504010000310k01.m3u8?KID=unistore,video&Expires=1495585445&ssig=ewLUXIvN4r
获取M3U8内容,匹配下分段MP4信息
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:295
#EXTINF:294.500000,
002Gszi3jx06XxBOR6In05040103r0BS0k03.mp4?KID=unistore,video&Expires=1495585445&ssig=cFO8lu2wAc
#EXTINF:154.250000,
000B7PFbjx06XxBP0S7505040101B6TA0k02.mp4?KID=unistore,video&Expires=1495585445&ssig=h12VWcXpxv
#EXT-X-ENDLIST`
在前面拼接:http://us.sinaimg.cn/
`Array
(
    [0] => Array
        (
            [m] => http://us.sinaimg.cn/002Gszi3jx06XxBOR6In05040103r0BS0k03.mp4?KID=unistore,video&Expires=1495585445&ssig=cFO8lu2wAc
            [t] => 294.500000
        )

    [1] => Array
        (
            [m] => http://us.sinaimg.cn/000B7PFbjx06XxBP0S7505040101B6TA0k02.mp4?KID=unistore,video&Expires=1495585445&ssig=h12VWcXpxv
            [t] => 154.250000
        )

)`

**Comment by rosynirvana** [comment]
disappeared

```
$ ./you-get -di ''http://weibo.com/tv/v/13458f8dda3eb9310bd1c4e7c02ad747?fid=1034:13458f8dda3eb9310bd1c4e7c02ad747'
bogon:you-get Maxwellgoblin$ ./you-get -di 'http://weibo.com/tv/v/13458f8dda3eb9310bd1c4e7c02ad747?fid=1034:13458f8dda3eb9310bd1c4e7c02ad747'
[DEBUG] get_content: http://video.weibo.com/show?fid=1034:13458f8dda3eb9310bd1c4e7c02ad747&type=mp4
[DEBUG] url_info: http://us.sinaimg.cn/001ggo73jx06XxBJg6xi0504010537U50k04.mp4?KID=unistore,video&Expires=1499609261&ssig=XB4mNloawh
Site:       miaopai
Title:      一美国高中生制作了几分钟的短片，点击量几百万，生动透彻地介绍了狭义相对论的精髓，并由此获得了硅谷科技大佬设立的“科学突破奖”25万美元！一起来感受下我的听译吧#分分钟涨姿势#《看待狭义相对论的几个酷炫角度》#酷炫科普小短片#【第35期】
Type:       MPEG-4 video (video/mp4)
Size:       71.17 MiB (74627049 Bytes)
```
