### ISSUE TITLE
[bilibili] ws.acgvideo.com now checks UA and referer

### ISSUE THREAD

**Issue by rosynirvana** [soimort/you-get#2021]
```
you-get -di 'http://www.bilibili.com/video/av2783167/index_2.html'
[DEBUG] get_content: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_response: http://www.bilibili.com/video/av2783167/index_1.html
[DEBUG] get_response: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=4346931&from=miniplay&player=1&sign=35ee420d8598cca6d79c75c020338d12
[DEBUG] url_info: http://ws.acgvideo.com/c/eb/4346931-1.flv?wsTime=1495730628&platform=pc&wsSecret2=110f421a5e8aeb879216b072ee4fc85a&oi=_&rate=1280
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av2783167/index_2.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 187, in bilibili_download
    info_only=info_only)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 101, in bilibili_download_by_cid
    _, type_, temp = url_info(url, headers={'Referer': 'http://www.bilibili.com/'})
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 420, in url_info
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 307, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 503, in error
    result = self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

```curl``` is banned, so is ```Python```

origin: #2018

**Comment by soimort** [comment]
Closed via #1698.
