### ISSUE TITLE
PPTV 部分视频无法下载 

### ISSUE THREAD

**Issue by skywang00** [soimort/you-get#2024]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
PS C:\Users\XXX> you-get -d -i http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2']
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.750', 'console_scripts', 'you-get')()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\__mai
n__.py", line 92, in main
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
n.py", line 1444, in main
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
n.py", line 1355, in script_main
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
n.py", line 1157, in download_main
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
n.py", line 1437, in any_download
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\extra
ctors\pptv.py", line 146, in pptv_download
AssertionError
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
PS C:\Users\XXX> you-get -d -i http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2']
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.750', 'console_scripts', 'you-get')()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\__mai
n__.py", line 92, in main
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
n.py", line 1444, in main
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
n.py", line 1355, in script_main
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
n.py", line 1157, in download_main
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
n.py", line 1437, in any_download
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\extra
ctors\pptv.py", line 146, in pptv_download
AssertionError
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
手动把html后面那些没用的请求去掉就行了
```
you-get -di 'http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html'
[DEBUG] get_response: http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html
[DEBUG] get_response: http://web-play.pptv.com/webplay3-0-17285316.xml?type=web.fpp
Site:       PPTV.com
Title:      金玉良缘(第01集)
Type:       MPEG-4 video (video/mp4)
Size:       146.87 MiB (154003827 Bytes)
```

这种正则……
```assert re.match(r'http://v.pptv.com/show/(\w+)\.html$', url)```

**Comment by skywang00** [comment]
@rosynirvana 
后面那些没用的请求是pptv自己加的。。。从剧集列表 http://v.pptv.com/page/sKqGBGzSQoDjYck.html 直接点击都有这些 rcc_src 
解析的版本不对，就算没有PPTV的1080p，也得有720p吧，直接网页播放都有720p的

**Comment by rosynirvana** [comment]
我知道是网站自己加的，所以上面说了问题在于那个正则而非用户，一个pull request又不会很快被merge，你要让现在的you-get能下，把html后面的请求去掉就是了

你要更高分辨率那是另一个问题

**Comment by QShen3** [comment]
关于PPTV的其它清晰度之前提过一个issue，不知道现在还是否有效 #1831

**Comment by skywang00** [comment]
@QShen3 
改version 对这个PPTV 视频无效

@rosynirvana 
有计划加入对PPTV高分辨率视频解析的支持吗？

**Comment by rosynirvana** [comment]
现在的```pptv.py```应该重写了，等等吧

**Comment by QShen3** [comment]
我试了试，还是有效的，你可以把我那个pptv.py下载下来，运行
python pptv.py http://v.pptv.com/page/sKqGBGzSQoDjYck.html 4
4或者5都是1080P的，5比4的码率更高。具体有哪些分辨率可以看返回里面的available字段

**Comment by rosynirvana** [comment]
另外说一下，问题不在接口上，现在用的接口不是只有SD的
但是处理xml用的是```r1```，找第一个匹配到的(不熟悉的可以看```common.py```)
所以只动接口拿到的都是xml最前面那个最低分辨率的

**Comment by skywang00** [comment]
@QShen3 

应该就是rosynirvana说的那样，还和接口有关，就是common.py有关，运行you-get的时候是要通过common.py调用pptv.py的，所以我修改pptv.py的version没用，但你直接运行pptv.py是可以的

**Comment by rosynirvana** [comment]
写出来了

但是好像需要 #29 这个……

**Comment by shikkoku** [comment]
为什么我跳转到华数那边播放了，PPTV好像撤下来了。

**Comment by rosynirvana** [comment]
pptv的还有，顶楼链接可以进去

**Comment by shikkoku** [comment]
@rosynirvana 我这里访问[http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2](http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2)网页跳转503 ERROR。

**Comment by rosynirvana** [comment]
```
$ curl -IL 'http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2'
HTTP/1.1 200 OK
Date: Sat, 27 May 2017 02:41:56 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 52457
Connection: keep-alive
Vary: Accept-Encoding
Vary: Accept-Encoding
Vary: Accept-Encoding
Vary: Accept-Encoding
Cache-Control: max-age=3600, public
Age: 625
Via-2: http/1.1 nb-b-ats-190-63-2 ( [uScSsSfUpSeN:t cCSi p sS])
Via: http/1.1 wh-c-ats-161-70-1 (ApacheTrafficServer/4.2.3 [uScHs f p eN:t cCHi p s ])
X-C: HIT
```

```
$ curl 'http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2' | grep 'var webcfg'
 var webcfg = {"id":17285316,"id_encode":"xEKoJicibJcK4Rjicc","pid":9034928,"p_type":21,"cat_id":2,"subCataIds":[138],"duration":2729,"type":3,"title":"\u91d1\u7389\u826f\u7f18(\u7b2c01\u96c6)","p_title":"\u91d1\u7389\u826f\u7f18","share_content":"%E6%88%91%E6%AD%A3%E5%9C%A8%23PPTV+%E7%BD%91%E7%BB%9C%E7%94%B5%E8%A7%86%23%E8%A7%82%E7%9C%8B%E3%80%90%E9%87%91%E7%8E%89%E8%89%AF%E7%BC%98%28%E7%AC%AC01%E9%9B%86%29%E3%80%91%EF%BC%88%E5%88%86%E4%BA%AB%E8%87%AA%40PPTV%E8%81%9A%E5%8A%9B%EF%BC%89","videoRatio":1.79,"player":{"playerConfig":{"setting":{"wn":1}},"ctx":"duration=2729&sid=%7Bs%7D9034928&sl=1&salt=pv&segment=45eb1a6b_45eb1833_1495852291&kk=5131c28c5955d684b2759af70e67ea93-0629-5928f313","playList":[{"id":17285316,"pl":"pptv:\/\/0a2lmamZqaKkj9iioJbPpqeL1K2doKidpaOdn5zOraHdm97Pm7PV2eeyrQ==","mn":9999,"title":"\u91d1\u7389\u826f\u7f18(\u7b2c01\u96c6)","link":"http:\/\/v.pptv.com\/show\/xEKoJicibJcK4Rjicc.html","swf":"http:\/\/player.pptv.com\/v\/xEKoJicibJcK4Rjicc.swf"}],"playerType":"vod"},"plugin":{"force":3,"properties":{"videotype":2},"tips":{"interval":30000,"times":1,"display":10000},"blacklist":["hao123ku","v.360.cn","movie.hao123.com","tv.hao123.com","v.tao123.com","21c9b038e5b1b4868c40b7bd614ed33c","123.sogou.com"],"type":1,"forceVersion":"1.0.0.53","update":true},"comment":{"id":17285316,"config":{"defaultText":"","pageSize":20,"showHot":true,"tabs":["\u6700\u65b0\u8bc4\u8bba"],"type":"short-pages"},"playType":"vod"},"playType":"episode","recommend_type":2,"recommend_config":["huaxu",["actor","director","type","series"],"love"]};
```
没什么问题

**Comment by soimort** [comment]
Closed via #2025.
