### ISSUE TITLE
某些QQ视频无法下载

### ISSUE THREAD

**Issue by zywzyw1234567** [soimort/you-get#2031]
这个QQ视频链接是昨天才上线的，之前的似乎都可以下载

Debug结果如下

C:\WINDOWS\system32>you-get --debug https://v.qq.com/x/cover/e4th0v7bfha4rrf/g0506r4ca9a.html
[DEBUG] get_html: http://v.qq.com/x/cover/e4th0v7bfha4rrf/g0506r4ca9a.html
[DEBUG] get_response: http://v.qq.com/x/cover/e4th0v7bfha4rrf/g0506r4ca9a.html
[DEBUG] get_html: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=g0506r4ca9a
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=g0506r4ca9a
[DEBUG] get_html: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10209&vid=g0506r4ca9a&filename=g0506r4ca9a.p209.1.mp4
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10209&vid=g0506r4ca9a&filename=g0506r4ca9a.p209.1.mp4
[DEBUG] url_info: http://202.77.59.41/vkp.tc.qq.com/g0506r4ca9a.p209.1.mp4?vkey=24786CA77E2A33BCC261AC238B71FB091F1C53875792E2EADA6AE9C0E350FB502F1657898B052E74EF07944E0DDC5E489218B6AA6AF327C57A80407300C93BDF5A9E8F8396735707E042E6C16DD7DA7565EF8840DF3B653E5F862E6D8967CC28
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/e4th0v7bfha4rrf/g0506r4ca9a.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1429, in main
  File "src\you_get\common.py", line 1342, in script_main
  File "src\you_get\common.py", line 1158, in download_main
  File "src\you_get\common.py", line 1422, in any_download
  File "src\you_get\extractors\qq.py", line 158, in qq_download
  File "src\you_get\extractors\qq.py", line 57, in qq_download_by_vid
UnboundLocalError: local variable 'ext' referenced before assignment
you-get returned -1

感激不尽。

**Comment by zywzyw1234567** [comment]
@rosynirvana 
这个QQ视频载不了，不过其它的大部分都能载，不知道出什么问题了，烦请一看，谢谢。

**Comment by rosynirvana** [comment]
要不你先试试这个

https://github.com/soimort/you-get/pull/1685/files/dc1f78024b5ab4b086f24d6fdfa3240b8acce85b

**Comment by zywzyw1234567** [comment]
@rosynirvana 
试了一下，和原来一样。就某些QQ链接，比如这个，貌似是5月24号之后才出这个bug，之前的都好好的

debug如下：
[DEBUG] get_response: http://v.qq.com/x/cover/e4th0v7bfha4rrf/g0506r4ca9a.html
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=g0506r4ca9a
[DEBUG] get_response: http://vv.video.qq.com/getvkey?vid=g0506r4ca9a&appver=3.2.38.401&platform=11&otype=json&filename=g0506r4ca9a.p203.1.mp4&format=10203&cKey=lw2Ht9CKKx3TSbboTvzOND5RoEvE4cwU4RoquAATelWaW7QlenLSFO1rmn2QFUIt-lbUBVtDnaobmEwFc3umPd6oSO2vlLHAOduIRVaIw4C2mjEj1JOwJs-5xb1iVCY5hoHRoM8lGvq8Ct2ethdtvIPd0IgVkEfhNg1cyZTVqynGJLemVsSoDkQn8C_g_ZeRis7tb3yebDIQUjno&guid=4aaf4e8e76d045e788846d1f8730953a&charge=0&encryptVer=5.4&lnk=g0506r4ca9a
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/e4th0v7bfha4rrf/g0506r4ca9a.html']
Traceback (most recent call last):
  File "C:\Users\zywzy\AppData\Local\Programs\Python\Python36\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.750', 'console_scripts', 'you-get')()
  File "c:\users\zywzy\appdata\local\programs\python\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\zywzy\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\zywzy\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\zywzy\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "c:\users\zywzy\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "c:\users\zywzy\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\qq.py", line 241, in qq_download
    site.download_by_vid(vid=vid, output_dir=output_dir, merge=merge, info_only=info_only, **kwargs)
  File "c:\users\zywzy\appdata\local\programs\python\python36\lib\site-packages\you_get\extractor.py", line 61, in download_by_vid
    self.prepare(**kwargs)
  File "c:\users\zywzy\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\qq.py", line 184, in prepare
    urls = ['{prefix}/{vid}.p{format1000}.{idx}.mp4?vkey={vkey}'.format(prefix=url_prefix, vid=vid, format1000=f['id']%1000, idx=idx, vkey=self._getvkey(vid, f['id'], idx)) for idx in range(1, vi0['cl']['fc']+1)]
  File "c:\users\zywzy\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\qq.py", line 184, in <listcomp>
    urls = ['{prefix}/{vid}.p{format1000}.{idx}.mp4?vkey={vkey}'.format(prefix=url_prefix, vid=vid, format1000=f['id']%1000, idx=idx, vkey=self._getvkey(vid, f['id'], idx)) for idx in range(1, vi0['cl']['fc']+1)]
  File "c:\users\zywzy\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\qq.py", line 163, in _getvkey
    return key_json['key']
KeyError: 'key'

**Comment by rosynirvana** [comment]
看来这个也不能用了

等等吧，腾讯的代码量太大

**Comment by zywzyw1234567** [comment]
@rosynirvana 
好的，今天多谢了。那边我已经搞定了，我用choco曾经安装过you-get，晕、删了就好了。

**Comment by airdge** [comment]
这个原因是:该视频vid和lnk不匹配导致下载错误
http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=g0506r4ca9a
```
                            [fvkey] => B449649AA00B8EBA39432631EAE6E4A510E0A5E7B5B7627C2C3474B3BB436C6A935C3051E801D88F8DC5D106B89A6BD90DE0C9B5247A36C15D3F899653ACB793685935E3DE22C551C008CAFBA6D2F1FD436091F565807CD1
                            [head] => 0
                            [hevc] => 0
                            [iflag] => 1
                            [level] => 0
                            [lnk] => o0023ndi9kh
                            [logo] => 1
                            [mst] => 8
```
这个视频的vid为g0506r4ca9a,但其lnk为o0023ndi9kh(绝大部分vid=lnk)
文件名是以lnk为准,而不是vid
`http://115.231.152.15/vkp.tc.qq.com/o0023ndi9kh.p212.1.mp4?sdtfrom=v1010&guid=439ae2fa4d3b8f2b3f9ffe66ef6ff713&vkey=16DC5A13A3453875B8E769A3422275AB8DDBB2D81E3EFA67E67607A3469E5CB08F2E9B3010BD5372B5CBDFAA4E0EC5ACA37CEB345E2EF9933CC431F70A2B93372FC8D8814AEC144EF9E1EDB6C57FC02A26DA68F20E1FED32`

**Comment by rosynirvana** [comment]
这个视频用platform 11的getinfo getkey居然能跑到300k

**Comment by rosynirvana** [comment]
```
$ ./you-get -i 'https://v.qq.com/x/cover/e4th0v7bfha4rrf/g0506r4ca9a.html'
Site:       QQ.com
Title:      【科技相对论】互联网传奇企业——亚马逊的成功之道
Type:       MPEG-4 video (video/mp4)
Size:       183.12 MiB (192016269 Bytes)
```
