### ISSUE TITLE
优酷视频无法下载

### ISSUE THREAD

**Issue by zywzyw1234567** [soimort/you-get#2032]
youku视频从前三天起无法下载

Debug结果如下

C:\WINDOWS\system32>you-get --debug http://v.youku.com/v_show/id_XMjc4MzQwMjA0NA==.html?spm=a2hzp.8253869.0.0
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjc4MzQwMjA0NA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjc4MzQwMjA0NA==&ct=12
you-get: [Failed] 客户端无权播放,603
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjc4MzQwMjA0NA==.html?spm=a2hzp.8253869.0.0']
Traceback (most recent call last):
  File "src\you_get\extractors\youku.py", line 180, in prepare
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1429, in main
  File "src\you_get\common.py", line 1342, in script_main
  File "src\you_get\common.py", line 1158, in download_main
  File "src\you_get\common.py", line 1422, in any_download
  File "src\you_get\extractor.py", line 41, in download_by_url
  File "src\you_get\extractors\youku.py", line 200, in prepare
  File "src\you_get\util\log.py", line 98, in wtf
NameError: name 'exit' is not defined
you-get returned -1

**Comment by DogLi** [comment]
I got the same error.

**Comment by macping** [comment]
I got the same error too.

**Comment by Rex-Diego** [comment]
It seems youku do some real prohibition about the unofficial client retrieving videos. Even the Adsafe (the most stable way I've ever tried to filter ad) does not work anymore.

But on the other hand, as long as the video is open to the public, there shall always be a way to cheat the official verification.

**Comment by qq792368480** [comment]
I got the same error too.

**Comment by soimort** [comment]
Closed via #2015.
