### ISSUE TITLE
不能下载 youtube 视频，试了优酷的也这样，是我 python 环境的问题吗？

### ISSUE THREAD

**Issue by 9IPHP** [soimort/you-get#2036]
```
➜  Video you-get -id https://www.youtube.com/watch\?v\=Vd1s_w9Lvvc
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=Vd1s_w9Lvvc
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=Vd1s_w9Lvvc']
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1229, in connect
    super().connect()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Specs/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/Users/Specs/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/Specs/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/Specs/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/Specs/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/Users/Specs/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/Users/Specs/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/Users/Specs/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/extractors/youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "/Users/Specs/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/common.py", line 323, in get_content
    response = urlopen_with_retry(req)
  File "/Users/Specs/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-soimort-SLASH-you-get.git/src/you_get/common.py", line 300, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 65] No route to host>
```

**Comment by 9IPHP** [comment]
When I Run update:

```
➜  Video pip3 install --upgrade you-get
Requirement already up-to-date: you-get in /usr/local/lib/python3.5/site-packages
➜  Video you-get -V
you-get: version 0.4.652, a tiny downloader that scrapes the web.
```

**Comment by rosynirvana** [comment]
你好像是用antigen装的？

另外```No route to host```是网络问题

**Comment by 9IPHP** [comment]
@rosynirvana 额额，好像是。。用antigen安装的怎么升级。

**Comment by rosynirvana** [comment]
https://github.com/zsh-users/antigen/wiki/Commands

不过这解决不了你的问题
ytb看上去是网络的问题，develop HEAD的代码里面youku本来就不能用

**Comment by 9IPHP** [comment]
卸载掉了，用的 pip3 安装，但是还是报错。。

```
➜  ~ python3 -V
Python 3.6.1
➜  ~ you-get -V
you-get: version 0.4.750, a tiny downloader that scrapes the web.
➜  ~ you-get -di 'https://www.youtube.com/watch?v=Vd1s_w9Lvvc'
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=Vd1s_w9Lvvc
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=Vd1s_w9Lvvc']
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 330, in get_content
    response = urlopen_with_retry(req)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 307, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 65] No route to host>
```

**Comment by rosynirvana** [comment]
上面的回复已经说了两遍了，```No route to host```是网络问题，升级解决不了的
