### ISSUE TITLE
爱奇艺视频下载不了python3 you-get --debug --format=HD   http://www.iqiyi.com/v_19rr7dzkbo.html

### ISSUE THREAD

**Issue by 774619774** [soimort/you-get#2039]
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/usr/local/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/you-get/src/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/you-get/src/you_get/common.py", line 1350, in script_main
    download_main(download, download_playlist, args, playlist, stream_id=stream_id, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/you-get/src/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/usr/local/you-get/src/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/usr/local/you-get/src/you_get/extractor.py", line 53, in download_by_url
    self.download(**kwargs)
  File "/usr/local/you-get/src/you_get/extractors/iqiyi.py", line 204, in download
    merge=kwargs['merge'],)
  File "/usr/local/you-get/src/you_get/common.py", line 989, in download_url_ffmpeg
    assert has_ffmpeg_installed(), "FFmpeg not installed."
AssertionError: FFmpeg not installed.

**Comment by rosynirvana** [comment]
> AssertionError: FFmpeg not installed

**Comment by weituotian** [comment]
@soimort-bot 
```
$ you-get --debug http://www.iqiyi.com/w_19rsez1ynt.html
[DEBUG] get_html: http://www.iqiyi.com/w_19rsez1ynt.html
[DEBUG] get_response: http://www.iqiyi.com/w_19rsez1ynt.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/3083569109/1c6450d5cebf7fd7f9184ab40ad5fb8e/?t=1497364007867&sc=c77a4214963586306853f6d0b40629a5&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/w_19rsez1ynt.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1429, in main
  File "src\you_get\common.py", line 1342, in script_main
  File "src\you_get\common.py", line 1158, in download_main
  File "src\you_get\common.py", line 1422, in any_download
  File "src\you_get\extractor.py", line 52, in download_by_url
  File "src\you_get\extractors\iqiyi.py", line 204, in download
  File "src\you_get\common.py", line 990, in download_url_ffmpeg
AssertionError: FFmpeg not installed.
site:                ▒▒▒▒▒▒ (Iqiyi)
title:               C4D▒¹▒▒▒֮
stream:
    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

you-get returned -1

```

**Comment by rosynirvana** [comment]
> FFmpeg not installed

因为你没装ffmpeg
