### ISSUE TITLE
[letv] le.py seems failed to support extractor proxy 

### ISSUE THREAD

**Issue by rosynirvana** [soimort/you-get#2040]
origin: replies in #1961

reproduce:

without proxy
```
./you-get -i http://www.letv.com/ptv/vplay/29394106.html
Current Video Supports:
	--format 1300 <URL>
	--format 720p <URL>
	--format 1000 <URL>
	--format 1080p <URL>
	--format 350 <URL>
Site:       Le.com
Title:      欢乐颂2 01
Type:       MPEG-4 video (video/mp4)
Size:       1011.17 MiB (1060290296 Bytes)
```

with global proxy
```
./you-get -id -x 127.0.0.1:1087 http://www.letv.com/ptv/vplay/29394106.html
[DEBUG] url_locations: http://www.letv.com/ptv/vplay/29394106.html
[DEBUG] get_content: http://www.letv.com/ptv/vplay/29394106.html
[DEBUG] get_content: http://player-pc.le.com/mms/out/video/playJson?id=29394106&platid=1&splatid=101&format=1&tkey=3479071261&domain=www.le.com&region=cn&source=1000&accesyx=1
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.letv.com/ptv/vplay/29394106.html']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 1180, in download_main
    download(url, **kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/extractors/le.py", line 149, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/extractors/le.py", line 96, in letv_download_by_vid
    ext , urls = video_info(vid,**kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/extractors/le.py", line 64, in video_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'
```

with extractor proxy
```
./you-get -i -y 127.0.0.1:1087 http://www.letv.com/ptv/vplay/29394106.html
Current Video Supports:
	--format 720p <URL>
	--format 350 <URL>
	--format 1000 <URL>
	--format 1300 <URL>
	--format 1080p <URL>
Site:       Le.com
Title:      欢乐颂2 01
Type:       MPEG-4 video (video/mp4)
Size:       1011.17 MiB (1060290296 Bytes)
```

**Comment by rosynirvana** [comment]
I guess it's possible to rebuild the original link form m3u8 urls.
```diff
diff --git a/src/you_get/extractors/le.py b/src/you_get/extractors/le.py
index 2cd5f16..60d0601 100644
--- a/src/you_get/extractors/le.py
+++ b/src/you_get/extractors/le.py
@@ -74,7 +74,6 @@ def video_info(vid,**kwargs):
             stream_id = '720p'
         else:
             stream_id =sorted(support_stream_id,key= lambda i: int(i[1:]))[-1]
-
     url =info["playurl"]["domain"][0]+info["playurl"]["dispatch"][stream_id][0]
     uuid = hashlib.sha1(url.encode('utf8')).hexdigest() + '_0'
     ext = info["playurl"]["dispatch"][stream_id][1].split('.')[-1]
@@ -92,13 +91,21 @@ def video_info(vid,**kwargs):
     urls = re.findall(r'^[^#][^\r]*',m3u8_list,re.MULTILINE)
     return ext,urls
 
+def build_url(segs_list):
+    name_patt = r'ver_\d+_\d+_\d+_(\d+)_(\d+)_\d+_\d+_\d+\.ts'
+    hit = re.search(name_patt, segs_list[-1])
+    seg = int(hit.group(1)) + int(hit.group(2))
+
+    first_fn = re.search(name_patt, segs_list[0]).group(0).split('_')
+    first_fn[5] = str(seg)
+    fn = '_'.join(first_fn)
+    return re.sub(name_patt, fn, segs_list[0])
+
 def letv_download_by_vid(vid,title, output_dir='.', merge=True, info_only=False,**kwargs):
     ext , urls = video_info(vid,**kwargs)
-    size = 0
-    for i in urls:
-        _, _, tmp = url_info(i)
-        size += tmp
-
+    url = build_url(urls)
+    print(url)
+    _, _, size = url_info(url)
     print_info(site_info, title, ext, size)
     if not info_only:
         download_urls(urls, title, ext, size, output_dir=output_dir, merge=merge)
```

```name_patt = r'ver_\d+_\d+_\d+_(\d+)_(\d+)_\d+_\d+_\d+\.ts'```, F.I. ```ver_00_22_77_273_2_4193716_498468652_0.ts```,  ```77``` is seg_no，```4193716``` is size of this seg which can be verified with a HTTP HEAD request, ```498468652``` is the beginning position of the file.

```273``` is some kind of accumulator( real file slice? ) :
```
ver_00_22_77_273_2_4193716_498468652_0.ts
ver_00_22_78_275_1_2901780_502662368_0.ts
ver_00_22_79_276_2_2456784_505564148_0.ts
```

To rebuild the original url we should parse the accumulator and offset from the last url. The file beginning pos and offset are useless, for the rebuilt url has different ```content-length``` from the value calculated from the last m3u8 url.
