### ISSUE TITLE
无法下载腾讯视频,win10 1703 powershell

### ISSUE THREAD

**Issue by Sense25** [soimort/you-get#2044]
PS C:\Users\sense> you-get -d https://v.qq.com/x/cover/nuijxf6k13t6z9b/u0023ickfto.html
[DEBUG] get_response: http://v.qq.com/x/cover/nuijxf6k13t6z9b/u0023ickfto.html
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=u00
23ickfto
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10209&vid=u0023ickfto&filename=u0023ic
kfto.p209.1.mp4
[DEBUG] url_info: http://lmbsy.qq.com/flv/28/42/u0023ickfto.p209.1.mp4?vkey=0C06E1DE729916B2CA8ACC1BA4904ED4E4AD9C390589
03746694708C70CFAF428D90E7FD0438EB8C05755E70C9041AF942ED5B4A16E82C250A2A1F827A2ABC271CD91E2F091BDF1A9C172555D12E50A60FB1
D8554DD97A7AD0E334495BA685E1
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/nuijxf6k13t6z9b/u0023ickfto.html']
Traceback (most recent call last):
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sense\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in mai
n
    main(**kwargs)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1444, in mai
n
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1355, in scr
ipt_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only,
json_output=json_output, caption=caption)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1157, in dow
nload_main
    download(url, **kwargs)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1437, in any
_download
    m.download(url, **kwargs)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\qq.py", line 163,
in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\qq.py", line 57, i
n qq_download_by_vid
    print_info(site_info, parts_ti, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment

**Comment by lamlam123tld3** [comment]
the parse for grapping the tecent video's vid may failed
may you change the url from https://v.qq.com/x/cover/nuijxf6k13t6z9b/u0023ickfto.html
to https://v.qq.com/x/page/u0023ickfto.html
by simply removing the playlist id and changing cover to page

**Comment by rosynirvana** [comment]
parser got the correct vid (u0023ickfto)
```
http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=u0023ickfto
```

**Comment by Sense25** [comment]
Not work
PS C:\Users\sense> you-get https://v.qq.com/x/page/u0023ickfto.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
PS C:\Users\sense> you-get -d https://v.qq.com/x/page/u0023ickfto.html
[DEBUG] get_response: http://v.qq.com/x/page/u0023ickfto.html
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=u00
23ickfto
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10209&vid=u0023ickfto&filename=u0023ic
kfto.p209.1.mp4
[DEBUG] url_info: http://lmbsy.qq.com/flv/28/42/u0023ickfto.p209.1.mp4?vkey=0AC1745AEC0D0FEDFCA4D90B5A0DC30FBC89A9B09A22
0EF5F8428C4A802A229C907C43547CBBDEC95EB6D6EB68C3F2605F2F1A6A660E6FCE1F3258A59509E1B496F07EC475BE2F62CA3F377FCF4215D2BB81
CB2D6E610CF84FDEB89F1D0ED9D1
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/page/u0023ickfto.html']
Traceback (most recent call last):
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sense\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in mai
n
    main(**kwargs)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1444, in mai
n
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1355, in scr
ipt_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only,
json_output=json_output, caption=caption)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1157, in dow
nload_main
    download(url, **kwargs)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1437, in any
_download
    m.download(url, **kwargs)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\qq.py", line 163,
in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\qq.py", line 57, i
n qq_download_by_vid
    print_info(site_info, parts_ti, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment

**Comment by Sense25** [comment]
PS C:\Users\sense> you-get http://vv.video.qq.com/getinfo?otype=json'&'appver=3%2E2%2E19%2E333'&'platform=11'&'defnpayver=1'&'vid=u0
023ickfto
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
PS C:\Users\sense> you-get -d http://vv.video.qq.com/getinfo?otype=json'&'appver=3%2E2%2E19%2E333'&'platform=11'&'defnpayver=1'&'vid
=u0023ickfto
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=u0023ickfto
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=u0023ickfto
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10209&vid=u0023ickfto&filename=u0023ickfto.p209.1.
mp4
[DEBUG] url_info: http://lmbsy.qq.com/flv/28/42/u0023ickfto.p209.1.mp4?vkey=BA6986FDBFA30F6AF8C520DC0FF7FF23AABF5853CAA3833E875E0E3D
A9C05DBC05A029D6E987A5FED26BF511C011A0CA968D7C6B067A6776196A964BD121D018A446D2AB60E7CE3E721AEFA1895EBAA9B98901CFCAEB446460C618A4FEB4
303A
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=u0023ickfto']
Traceback (most recent call last):
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sense\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=
json_output, caption=caption)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\qq.py", line 163, in qq_downlo
ad
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "c:\users\sense\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\qq.py", line 57, in qq_downloa
d_by_vid
    print_info(site_info, parts_ti, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment

**Comment by rosynirvana** [comment]
```
$ ./you-get -i 'https://v.qq.com/x/cover/nuijxf6k13t6z9b/u0023ickfto.html'
Site:       QQ.com
Title:      择天记_01
Type:       MPEG-4 video (video/mp4)
Size:       1101.34 MiB (1154841188 Bytes)
```
