### ISSUE TITLE
A、B站问题

### ISSUE THREAD

**Issue by huanghe2015** [soimort/you-get#2061]
在提交前，请确保您已经检查了以下内容!
- [ √] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [√ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:
D:\ZWB\我的文档\我的视频\纪录片>you-get -d -o D:\ZWB\我的文档\我的视频\纪录片 ht
tp://www.acfun.cn/v/ac3421553
[DEBUG] get_html: http://www.acfun.cn/v/ac3421553
[DEBUG] get_response: http://www.acfun.cn/v/ac3421553
[DEBUG] get_html: http://www.acfun.tv/video/getVideo.aspx?id=4780080
[DEBUG] get_response: http://www.acfun.tv/video/getVideo.aspx?id=4780080
[DEBUG] get_content: http://api.aixifan.com/plays/4780080
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519
d032263f8&video_id=CMTA2OTM2NjQ=&embsig=1_1496649505_cafb835babbf471bc3f99d93b9b
69f53
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8
&vid=CMTA2OTM2NjQ=&ct=85&sign=MXwxNDk2NjQ5NTMwfGJlYzM4YzAzNmUwNjNmYmVjOTg5ODNjMT
MyY2RmNDRl
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac3421553']
Traceback (most recent call last):
  File "D:\Program Files\Python36\Scripts\you-get-script.py", line 11, in <modul
e>
    load_entry_point('you-get==0.4.715', 'console_scripts', 'you-get')()
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\__main__.py", line 92, in main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\common.py", line 1429, in main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\common.py", line 1342, in script_main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\common.py", line 1158, in download_main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\common.py", line 1422, in any_download
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\extractors\acfun.py", line 90, in acfun_download
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\extractors\acfun.py", line 55, in acfun_download_by_vid
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\extractors\youku.py", line 375, in open_download_by_vid
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\extractors\youku.py", line 172, in prepare
  File "D:\Program Files\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

D:\ZWB\我的文档\我的视频\纪录片>you-get -d -o D:\ZWB\我的文档\我的视频\纪录片 ht
tp://www.bilibili.com/video/av8005398?from=search&seid=17394223296558280970
[DEBUG] get_content: http://www.bilibili.com/video/av8005398?from=search
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=13252838&from=mi
niplay&player=1&sign=661b9f3bd9be983a6e80c5a30321f182
[DEBUG] url_info: http://cn-zjwz2-dx-v-03.acgvideo.com/vg4/3/57/13252838-1.flv?e
xpires=1496660100&platform=pc&ssig=JtIiQr6ST4wKeIdb3LnLMw&oi=3702654137&nfa=zn2O
TN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2064002514
[DEBUG] url_info: http://cn-zjwz2-dx-v-03.acgvideo.com/vg4/3/57/13252838-2.flv?e
xpires=1496660100&platform=pc&ssig=HFzJn7GUGtWck49fqcwlBg&oi=3702654137&nfa=zn2O
TN7O9p3rqnr0+3S2RQ==&dynamic=1
[DEBUG] url_info: http://cn-zjwz2-dx-v-03.acgvideo.com/vg4/3/57/13252838-3.flv?e
xpires=1496660100&platform=pc&ssig=nu0mSms2R8fPnuK4_bi-lg&oi=3702654137&nfa=zn2O
TN7O9p3rqnr0+3S2RQ==&dynamic=1
[DEBUG] url_info: http://cn-zjwz2-dx-v-03.acgvideo.com/vg4/3/57/13252838-4.flv?e
xpires=1496660100&platform=pc&ssig=S8AdAFVMCWXPEnSplpvEWQ&oi=3702654137&nfa=zn2O
TN7O9p3rqnr0+3S2RQ==&dynamic=1
[DEBUG] url_info: http://cn-zjwz2-dx-v-03.acgvideo.com/vg4/3/57/13252838-5.flv?e
xpires=1496660100&platform=pc&ssig=qxZohLanl1C0ChQ6lNO4MQ&oi=3702654137&nfa=zn2O
TN7O9p3rqnr0+3S2RQ==&dynamic=1
Site:       bilibili.com
Title:      【英剧-喜剧】扯蛋莎翁史 Cunk On Shakespeare 2016【电波字幕组】
Type:       Flash video (video/x-flv)
Size:       392.45 MiB (411513967 Bytes)

Downloading 【英剧-喜剧】扯蛋莎翁史 Cunk On Shakespeare 2016【电波字幕组】.flv .
..
 0.0% (  0.0/392.5MB) ├────────────────────────────
─────────────┤[1/5] you-get: version 0.4.715, a tiny downloader th
at scrapes the web.
you-get: ['http://www.bilibili.com/video/av8005398?from=search']
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "D:\Program Files\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Program Files\Python36\lib\http\client.py", line 1285, in _send_reque
st
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Program Files\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Program Files\Python36\lib\http\client.py", line 1026, in _send_outpu
t
    self.send(msg)
  File "D:\Program Files\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "D:\Program Files\Python36\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "D:\Program Files\Python36\lib\socket.py", line 722, in create_connection

    raise err
  File "D:\Program Files\Python36\lib\socket.py", line 713, in create_connection

    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\Scripts\you-get-script.py", line 11, in <modul
e>
    load_entry_point('you-get==0.4.715', 'console_scripts', 'you-get')()
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\__main__.py", line 92, in main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\common.py", line 1429, in main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\common.py", line 1342, in script_main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\common.py", line 1158, in download_main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\common.py", line 1422, in any_download
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\extractors\bilibili.py", line 187, in bilibili_download
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\extractors\bilibili.py", line 106, in bilibili_download_by_cid
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\common.py", line 812, in download_urls
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\common.py", line 531, in url_save
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.715-py3.6.egg\yo
u_get\common.py", line 310, in urlopen_with_retry
  File "D:\Program Files\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Program Files\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "D:\Program Files\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "D:\Program Files\Python36\lib\urllib\request.py", line 504, in _call_cha
in
    result = func(*args)
  File "D:\Program Files\Python36\lib\urllib\request.py", line 1346, in http_ope
n
    return self.do_open(http.client.HTTPConnection, req)
  File "D:\Program Files\Python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
'seid' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by rosynirvana** [comment]
首先你应该升级到0.4.750
然后去pull requests里找补丁 #2010 #1698

**Comment by huanghe2015** [comment]
已经升级到最新发布版，期待下一个版本！

**Comment by rosynirvana** [comment]
你贴的log是 ```0.4.715```
最新release是 ```0.4.750```
不过要是解决了就把issue关掉吧

**Comment by huanghe2015** [comment]
哦，最新版在上面，下面那个最新发布版太小了，没看见。

**Comment by huanghe2015** [comment]
D:\ZWB\我的文档\我的源代码\you-get-0.4.750>you-get -V
you-get: version 0.4.750, a tiny downloader that scrapes the web.

D:\ZWB\我的文档\我的源代码\you-get-0.4.750>you-get -d -o D:\ZWB\我的文档\我的视
频\纪录片 http://www.acfun.cn/v/ac3421553
[DEBUG] get_response: http://www.acfun.cn/v/ac3421553
[DEBUG] get_response: http://www.acfun.tv/video/getVideo.aspx?id=4780080
[DEBUG] get_content: http://api.aixifan.com/plays/4780080
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519
d032263f8&video_id=CMTA2OTM2NjQ=&embsig=1_1496722765_1af8938f4902191b35b19c94e24
1e78f
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8
&vid=CMTA2OTM2NjQ=&ct=85&sign=MXwxNDk2NzIyNzY4fDA3ZmViN2IwYWRiODYxNTQ3ZDc3YzZjYT
VkMmNkZjcx
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac3421553']
Traceback (most recent call last):
  File "D:\Program Files\Python36\Scripts\you-get-script.py", line 11, in <modul
e>
    load_entry_point('you-get==0.4.750', 'console_scripts', 'you-get')()
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\__main__.py", line 92, in main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\common.py", line 1444, in main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\common.py", line 1355, in script_main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\common.py", line 1157, in download_main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\common.py", line 1437, in any_download
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\extractors\acfun.py", line 90, in acfun_download
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\extractors\acfun.py", line 55, in acfun_download_by_vid
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\extractors\youku.py", line 375, in open_download_by_vid
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\extractors\youku.py", line 172, in prepare
  File "D:\Program Files\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

**Comment by huanghe2015** [comment]
D:\ZWB\我的文档\我的源代码\you-get-0.4.750>you-get -d -o D:\ZWB\我的文档\我的视
频\纪录片 http://www.bilibili.com/video/av8130715/?from=search&seid=173942232965
58280970
[DEBUG] get_content: http://www.bilibili.com/video/av8130715/?from=search
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=13369402&from=mi
niplay&player=1&sign=fa43d7474b2c665ce6046fad3e5df6ee
[DEBUG] url_info: http://cn-zjwz1-dx.acgvideo.com/vg6/5/54/13369402-1.flv?expire
s=1496734200&platform=pc&ssig=RA5vN6Yrm1jTqv7UwEXdIA&oi=3702654137&nfa=zn2OTN7O9
p3rqnr0+3S2RQ==&dynamic=1&hfa=2063930319
[DEBUG] url_info: http://cn-zjwz1-dx.acgvideo.com/vg6/5/54/13369402-2.flv?expire
s=1496734200&platform=pc&ssig=JchxbsU_qVqgFUsFmSNbRA&oi=3702654137&nfa=zn2OTN7O9
p3rqnr0+3S2RQ==&dynamic=1
[DEBUG] url_info: http://cn-zjwz1-dx.acgvideo.com/vg6/5/54/13369402-3.flv?expire
s=1496734200&platform=pc&ssig=BfwxJPPah6ynmZj5z8q7gA&oi=3702654137&nfa=zn2OTN7O9
p3rqnr0+3S2RQ==&dynamic=1
[DEBUG] url_info: http://cn-zjwz1-dx.acgvideo.com/vg6/5/54/13369402-4.flv?expire
s=1496734200&platform=pc&ssig=SJHAHIhoZizAoKfZFqOcVw&oi=3702654137&nfa=zn2OTN7O9
p3rqnr0+3S2RQ==&dynamic=1
[DEBUG] url_info: http://cn-zjwz1-dx.acgvideo.com/vg6/5/54/13369402-5.flv?expire
s=1496734200&platform=pc&ssig=ULXuBIrBHRw2hLWflOSAlQ&oi=3702654137&nfa=zn2OTN7O9
p3rqnr0+3S2RQ==&dynamic=1
Site:       bilibili.com
Title:      【英剧-喜剧】扯蛋圣诞史 Cunk On Christmas 2016【电波字幕组】
Type:       Flash video (video/x-flv)
Size:       402.68 MiB (422241400 Bytes)

Downloading 【英剧-喜剧】扯蛋圣诞史 Cunk On Christmas 2016【电波字幕组】.flv ...

 0.0% (  0.0/402.7MB) ├────────────────────────────
12.4% ( 50.0/402.7MB) ├█████───────────────────────
─────────────┤[1/5]  980 MB/syou-get: version 0.4.750, a tiny down
loader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av8130715/?from=search']
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "D:\Program Files\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Program Files\Python36\lib\http\client.py", line 1285, in _send_reque
st
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Program Files\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Program Files\Python36\lib\http\client.py", line 1026, in _send_outpu
t
    self.send(msg)
  File "D:\Program Files\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "D:\Program Files\Python36\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "D:\Program Files\Python36\lib\socket.py", line 722, in create_connection

    raise err
  File "D:\Program Files\Python36\lib\socket.py", line 713, in create_connection

    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\Scripts\you-get-script.py", line 11, in <modul
e>
    load_entry_point('you-get==0.4.750', 'console_scripts', 'you-get')()
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\__main__.py", line 92, in main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\common.py", line 1444, in main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\common.py", line 1355, in script_main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\common.py", line 1157, in download_main
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\common.py", line 1437, in any_download
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\extractors\bilibili.py", line 187, in bilibili_download
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\extractors\bilibili.py", line 106, in bilibili_download_by_cid
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\common.py", line 811, in download_urls
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\common.py", line 530, in url_save
  File "D:\Program Files\Python36\lib\site-packages\you_get-0.4.750-py3.6.egg\yo
u_get\common.py", line 307, in urlopen_with_retry
  File "D:\Program Files\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Program Files\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "D:\Program Files\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "D:\Program Files\Python36\lib\urllib\request.py", line 504, in _call_cha
in
    result = func(*args)
  File "D:\Program Files\Python36\lib\urllib\request.py", line 1346, in http_ope
n
    return self.do_open(http.client.HTTPConnection, req)
  File "D:\Program Files\Python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
'seid' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by exxfzc** [comment]
you-get是用brew安装的,要怎么升级到0.4.750?

**Comment by huanghe2015** [comment]
我是直接用Python命令py setup.py install 安装的。

**Comment by soimort** [comment]
Closed via #2010.
