### ISSUE TITLE
Can't download the live broadcast content from iQiYi?

### ISSUE THREAD

**Issue by tibetty** [soimort/you-get#2063]
When I tried to download an archived video clip from live broadcast channel using "you-get --debug 'http://www.iqiyi.com/l_19rrdheubv.html'", I received below error message:

[DEBUG] get_response: http://www.iqiyi.com/l_19rrdheubv.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/1055678823/362a7c41d35613a91f                                                                                        bad26cc60e746f/?t=1496679275534&sc=d8b105b540c58c40333c0f97d003ab9a&src=76f90cbd                                                                                        92f94a2e925d83e8ccd22cb7
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/l_19rrdheubv.html']
Traceback (most recent call last):
  File "/home/tourank/.local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/tourank/.local/lib/python3.5/site-packages/you_get/__main__.py", l                                                                                        ine 92, in main
    main(**kwargs)
  File "/home/tourank/.local/lib/python3.5/site-packages/you_get/common.py", lin                                                                                        e 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/tourank/.local/lib/python3.5/site-packages/you_get/common.py", lin                                                                                        e 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output                                                                                        _dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption                                                                                        )
  File "/home/tourank/.local/lib/python3.5/site-packages/you_get/common.py", lin                                                                                        e 1157, in download_main
    download(url, **kwargs)
  File "/home/tourank/.local/lib/python3.5/site-packages/you_get/common.py", lin                                                                                        e 1437, in any_download
    m.download(url, **kwargs)
  File "/home/tourank/.local/lib/python3.5/site-packages/you_get/extractor.py",                                                                                         line 41, in download_by_url
    self.prepare(**kwargs)
  File "/home/tourank/.local/lib/python3.5/site-packages/you_get/extractors/iqiy                                                                                        i.py", line 140, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video

Such content downloading has not been supported by now, or there's any other issue?

Thanks!

**Comment by tibetty** [comment]
I tried on a PC running Windows 10 later, and the download was successfully completed.  ’Given the default language of my Windows is Simplified Chinese whilst the language of the Ubuntu server where above error occurred is en_US.UTF-8, I am wondering if it's related to the encoding of content name.
 
More Info of the Windows PC:
Python version: 3.6.1
GeoIP location: US, United States
