### ISSUE TITLE
b站这种视频是否下载无解？

### ISSUE THREAD

**Issue by airectx** [soimort/you-get#2065]
在提交前，请确保您已经检查了以下内容!

- [x ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ x] 您的`you-get`为最新版.
- [x ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ x] 本问题确实关于`you-get`, 而不是其他项目.

> 这个视频是可以在浏览器看的，但是视频是不允许缓存的

请使用`--debug`运行，并将输出粘贴在下面:

```
C:\WINDOWS\system32>you-get -d http://www.bilibili.com/video/av10788045/
[DEBUG] get_content: http://www.bilibili.com/video/av10788045/
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av10788045/']
Traceback (most recent call last):
  File "c:\users\airec\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\airec\AppData\Local\Programs\Python\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\bilibili.py", line 146, in bilibili_download
    assert flashvars
AssertionError
```

> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
因为没登录看不到
要挂cookie

**Comment by airectx** [comment]
@rosynirvana 
带了cookie还是不行。。难道cookie不行？用的Firebug插件导出的cookie.txt
`C:\WINDOWS\system32>you-get -c D:\cookie.txt -d http://www.bilibili.com/video/av10788045/
[DEBUG] get_content: http://www.bilibili.com/video/av10788045/
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av10788045/']
Traceback (most recent call last):
  File "c:\users\airec\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\airec\AppData\Local\Programs\Python\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "c:\users\airec\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\bilibili.py", line 146, in bilibili_download
    assert flashvars
AssertionError`

**Comment by rosynirvana** [comment]
```
you-get -i -c ~/Downloads/cookies.txt 'http://www.bilibili.com/video/av10788045/'
Site:       bilibili.com
Title:      【纪录片-BBC】宇宙有多大 HOW BIG IS THE UNIVERSE-（2012）【地平线系列】
Type:       Flash video (video/x-flv)
Size:       680.53 MiB (713585933 Bytes)
```

现在cookie加载那段代码错误检查做的不行
正确加载了一个Netscape cookie file后是可以的

**Comment by airectx** [comment]
好吧，看来还是加载姿势问题，感谢解答

**Comment by airectx** [comment]
换成cookies.sqlite加载几次出来了。。 :joy:
```
C:\WINDOWS\system32>you-get -i -c D:\cookies.sqlite http://www.bilibili.com/video/av10788045/
Site:       bilibili.com
Title:      【纪录片-BBC】宇宙有多大 HOW BIG IS THE UNIVERSE-（2012）【地平线系列】
Type:       Flash video (video/x-flv)
Size:       680.53 MiB (713585933 Bytes)
```
