### ISSUE TITLE
-y proxy.uku.im:443 无法使用

### ISSUE THREAD

**Issue by Damhnait** [soimort/you-get#2072]
root@debian:/home/linin1/linin1# you-get -i http://v.youku.com/v_show/id_XMjgxMjgzNjkxNg==.html?spm=a2hww.20023042.m_223473.5~5~5~5~A
you-get: 抱歉，该视频仅限中国大陆地区播放，请您观看其他视频！

root@debian:/home/linin1/linin1# you-get -i -y proxy.uku.im:443 http://v.youku.com/v_show/id_XMjgxMjgzNjkxNg==.html?spm=a2hww.20023042.m_223473.5~5~5~5~A
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

root@debian-512mb-sfo2-01:/home/linin1/linin1# you-get -i -y proxy.uku.im:443 http://v.youku.com/v_show/id_XMjgxMjgzNjkxNg==.html?spm=a2hww.20023042.m_223473.5~5~5~5~A --debug
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjgxMjgzNjkxNg==.html?spm=a2hww.20023042.m_223473.5~5~5~5~A']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1357, in script_main
    download_main(download, download_playlist, args, playlist, extractor_proxy=extractor_proxy, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/youku.py", line 192, in prepare
    data = youku_ups(self.vid)['data']
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/youku.py", line 40, in youku_ups
    url += '&utid=' + fetch_cna()
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/youku.py", line 27, in fetch_cna
    req = urllib.request.urlopen(url)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
这是unblock youku的问题，不是you-get的问题

如果需要workaround可以看#2057 最后的回复

**Comment by ztytian** [comment]
改host或者用unblock youku dns
或者用别的代理

**Comment by demonluo** [comment]
:( i create a topic at unblock youku forum about the PAC issue around 80 days ago but no one seem to care, they only care to fix/update chrome extension & DNS...
https://bbs.uku.im/t/pac/568
