### ISSUE TITLE
bilibili issue

### ISSUE THREAD

**Issue by hyperVX** [soimort/you-get#2073]
Hi there.

Several days ago, you-get just worked fine for videos on bilibili.
But now it just doesn't work.
I have already upgraded you-get to the newest version and there's nothing wrong with the encoding.
For other site such as youku.com, you-get currently works fine.

Here's the debug info:

PS C:\Users\\*****\Videos> you-get.exe --debug http://www.bilibili.com/video/av11177726/
[DEBUG] get_content: http://www.bilibili.com/video/av11177726/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=18492670&from=miniplay&player=1&sign=0d8ba48aa2f538a181e07eac0870c312
[DEBUG] url_info: http://cn-jsks3-dx.acgvideo.com/vg3/b/2b/18492670-1.flv?expires=1497085500&platform=pc&ssig=cQ_9iEFC0o00OR25ZLp07w&oi=2105203517&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2064166748&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av11177726/']
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractors\bilibili.py", line 187, in bilibili_download
    info_only=info_only)
  File "c:\program files\python36\lib\site-packages\you_get\extractors\bilibili.py", line 101, in bilibili_download_by_cid
    _, type_, temp = url_info(url, headers={'Referer': 'http://www.bilibili.com/'})
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 420, in url_info
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 307, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\program files\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\program files\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\program files\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\program files\python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\program files\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\program files\python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by rosynirvana** [comment]
#1698

**Comment by hyperVX** [comment]
Ok I fixed it up by using https://raw.githubusercontent.com/rosynirvana/you-get/fix-bilibili-redirect/src/you_get/extractors/bilibili.py, thanks.
