### ISSUE TITLE
网易云音乐NeteaseMusic无法下载

### ISSUE THREAD

**Issue by leolqh** [soimort/you-get#2074]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=466795245&ids=[466795245]&csrf_token=
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['https://music.163.com/#/song?id=466795245']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/common.py", line 1180, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/extractors/netease.py", line 133, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/extractors/netease.py", line 70, in netease_cloud_music_download
    netease_song_download(j["songs"][0], output_dir=output_dir, info_only=info_only)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/you_get/extractors/netease.py", line 110, in netease_song_download
    songNet = 'p' + song['mp3Url'].split('/')[2][1:]
AttributeError: 'NoneType' object has no attribute 'split'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by yangaowei** [comment]
也遇到同样的问题？解决了吗

**Comment by rosynirvana** [comment]
换接口要AES的库
作者打算加依赖之前解决不了
或者哪天谁在py里手写了一个也行

**Comment by yangaowei** [comment]
@rosynirvana   有进展了吗？ 感谢

**Comment by rosynirvana** [comment]
呃，什么叫进展？
如果作者在```you-get```的依赖中加入一个AES库，那要不了半小时就能修复这问题
但现在作者很久没出现了

**Comment by yangaowei** [comment]
把代码粘出来看看，AES库先忽略

**Comment by rosynirvana** [comment]
https://gist.github.com/rosynirvana/9678ff353e098910313c77494425a75c

网易很不喜欢别人扒他们接口，所以不建议外传这个

**Comment by yangaowei** [comment]
多谢

**Comment by yangaowei** [comment]
@rosynirvana   自用，有些问题，不知是不是AES库版本问题，请求返回的数据为空

**Comment by rosynirvana** [comment]
是自带的测试都过不了吗？

**Comment by yangaowei** [comment]
@rosynirvana  是的  我用的python2.7

**Comment by rosynirvana** [comment]
这是py3的代码
你用py2要稍微改几个地方，一个是py2有长整型，生成的大数后面的```L```要去掉，另外就是unicode string要处理正确

**Comment by yangaowei** [comment]
@rosynirvana 感谢，python3环境下没有问题，python2.7的我再修改下。

**Comment by leolqh** [comment]
萌新表示，弄出来了给我一份……

**Comment by rosynirvana** [comment]
上面gist贴的有啊

**Comment by leolqh** [comment]
可是不能用啊……
ImportError: cannot import name 'netease_download'

**Comment by rosynirvana** [comment]
你理解错了，那是个单独的py script，和```you-get```没关系

**Comment by dinjia** [comment]
现在 http://music.163.com/api/song/detail/?ids=[歌曲id] 获取的dsfId都为0；
其实有个曲线救国的方式。
post  http://music.163.com/api/search/pc
参数      s: 歌曲id,
            limit: 1,
            type: 1,
            offset: 0,
这样获取的 dsfId并不为0；

**Comment by utpalma** [comment]
r的那个脚本运行报错。。。

**Comment by a137235** [comment]
@dinjia 获取的是空的好不

**Comment by dinjia** [comment]
@a137235 不会啊。我这边没问题。 只是用id搜有点小问题，最好用歌名+歌手名搜，在比较id。
![z](https://user-images.githubusercontent.com/16534175/27937130-79dd1e70-62e7-11e7-93ed-ad5034917ce8.png)

**Comment by lki2019** [comment]
网易云音乐，IDM直接可以嗅探出来的啊，
音频类的好像除非喜马拉雅收费的那种，一般的站IDM嗅探地址都能的吧？

**Comment by zhipfang** [comment]
现在you-get下载不了网易云音乐了？
`C:\Users>you-get -di http://music.163.com/#/song?id=185868
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=185868&ids=[185868]&csrf_token=
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/song?id=185868']
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, i
nfo_only=info_only, json_output=json_output, caption=caption)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\python36\lib\site-packages\you_get\extractors\netease.py", line 133, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "c:\python36\lib\site-packages\you_get\extractors\netease.py", line 69, in netease_cloud_musi
c_download
    j = loads(get_content("http://music.163.com/api/song/detail/?id=%s&ids=[%s]&csrf_token=" % (rid,
 rid), headers={"Referer": "http://music.163.com/"}))
  File "c:\python36\lib\site-packages\you_get\common.py", line 353, in get_content
    response = urlopen_with_retry(req)
  File "c:\python36\lib\site-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\python36\lib\urllib\request.py", line 806, in <lambda>
    meth(r, proxy, type))
  File "c:\python36\lib\urllib\request.py", line 834, in proxy_open
    return self.parent.open(req, timeout=req.timeout)
  File "c:\python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\python36\lib\urllib\request.py", line 549, in _open
    'unknown_open', req)
  File "c:\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\python36\lib\urllib\request.py", line 1388, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: 'http>`

**Comment by amtlib-dot-dll** [comment]
实测恢复了？
`you-get http://music.163.com/album/2943023`

**Comment by LOVEChen** [comment]
you-get https://music.163.com/#/song?id=26508186 --debug
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=26508186&ids=[26508186]&csrf_token=
you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://music.163.com/#/song?id=26508186'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.939', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/common.py", line 1363, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/common.py", line 1271, in script_main
    **extra
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/common.py", line 1073, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/common.py", line 1356, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/extractors/netease.py", line 133, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/extractors/netease.py", line 70, in netease_cloud_music_download
    netease_song_download(j["songs"][0], output_dir=output_dir, info_only=info_only)
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/extractors/netease.py", line 110, in netease_song_download
    songNet = 'p' + song['mp3Url'].split('/')[2][1:]
AttributeError: 'NoneType' object has no attribute 'split'
