### ISSUE TITLE
哔哩哔哩网站下载视频出现403问题，怎么解决，替换过issues中修改过的bilibili.py和common.py

### ISSUE THREAD

**Issue by zackzjc** [soimort/you-get#2079]
C:\Users\zack>you-get --debug https://www.bilibili.com/video/av11230200/
[DEBUG] get_content: http://www.bilibili.com/video/av11230200/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=18574803&from=miniplay&player=1&sign=fb422407732c1c26568a3213b3f93f02
[DEBUG] url_info: http://cn-jszj-dx-v-06.acgvideo.com/vg2/a/9e/18574803-1.flv?expires=1497343200&platform=pc&ssig=Yfy_HjjbX3lZCzsFMh7ZtA&oi=1927090318&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2064408073
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['https://www.bilibili.com/video/av11230200/']
Traceback (most recent call last):
  File "c:\users\zack\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\zack\AppData\Local\Programs\Python\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\zack\appdata\local\programs\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1433, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1344, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1146, in download_main
    download(url, **kwargs)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1426, in any_download
    m.download(url, **kwargs)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\bilibili.py", line 187, in bilibili_download
    info_only=info_only)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\bilibili.py", line 101, in bilibili_download_by_cid
    _, type_, temp = url_info(url, headers={'Referer': 'http://www.bilibili.com/'})
  File "c:\users\zack\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 419, in url_info
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "c:\users\zack\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 307, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "c:\users\zack\appdata\local\programs\python\python35\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by lrbmike** [comment]
发现解析出来的视频链接带上"http://www.bilibili.com"的referer就可以正常下载，貌似是B站限制外站播放?

**Comment by rosynirvana** [comment]
@lrbmike 403是bilibili的CDN限制UA和referer
但是```you-get```的develop branch，也就是现在的latest release，已经加了referer
老的```interface.bilibili.com```的接口可以用来解析不付费的东西，和403也无关

楼主生成他换过文件，和你的问题不同，不建议放一个issue下面讨论

**Comment by fredhdx** [comment]
同样的问题，最新develop branch的版本，下载发生403错误。
解析用的interface.bilibili.com
解析出的url显示的CDN防盗链

 > 拒绝访问
> 
> 本缓存服务器管理员：wssupport@chinanetcenter.com
> 
> Via:jg61:6 (Cdn Cache Server V2.0)
> Generated Fri, 16 Jun 2017 20:36:33 GMT by cache.51cdn.com (Cdn Cache Server V2.0)


`get_content: http://interface.bilibili.com/playurl?&cid=12057304&from=miniplay&player=1&sign=b2b2422e43041515997eb6caf6e0ecf6
[DEBUG] url_info: http://ws.acgvideo.com/8/d6/12057304-1.flv?wsTime=1497655873&platform=pc&wsSecret2=5311353c7a259ba2a308bde0c1fa0542&oi=2776404397&rate=1280
you-get: version 0.4.750, a tiny downloader that scrapes the web.
`

**Comment by cnbeining** [comment]
I am receiving error report on this problem even with legit users. Could be they are playing with the server.

Closed due to issue not moving forward. Please open if you need.
