### ISSUE TITLE
腾讯视频下载合并失败

### ISSUE THREAD

**Issue by longdeqidao** [soimort/you-get#2083]
汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
➜  ~  you-get --debug https://v.qq.com/x/page/v0501apykif.html                                                                                                                             [~]
[DEBUG] get_html: http://v.qq.com/x/page/v0501apykif.html
[DEBUG] get_response: http://v.qq.com/x/page/v0501apykif.html
[DEBUG] get_html: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=v0501apykif
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=v0501apykif
[DEBUG] get_html: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10709&vid=v0501apykif&filename=v0501apykif.p709.1.mp4
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10709&vid=v0501apykif&filename=v0501apykif.p709.1.mp4
[DEBUG] url_info: http://202.77.59.46/vhot2.qqvideo.tc.qq.com/v0501apykif.p709.1.mp4?vkey=94B123F81604E5BE946C89679E8651140D1D8B8E0AE7AD0DB11734FF077C255893F706FB6D69E7A6990587EAD223910B6AEA181E77BF3893B8F2C523BDA8852A56DDE18DEE7AB1BE6B70A7AE2D7BA14FAB5FD261B8B85FA44AA587F631516006
[DEBUG] get_html: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10709&vid=v0501apykif&filename=v0501apykif.p709.2.mp4
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10709&vid=v0501apykif&filename=v0501apykif.p709.2.mp4
[DEBUG] url_info: http://202.77.59.46/vhot2.qqvideo.tc.qq.com/v0501apykif.p709.2.mp4?vkey=CEEB084940ACF3D01F8E54E6ECB2D702E64D5D5F7C5BBF713210D0F628DA56B442C352FEA4457913BD0E534905D9A7E2CE94D2660C2E9911133480FF86DC0AF0260536E9C6456B0016AEA81684BB5639DECFEF675C24D0D23AF5F08365850917
[DEBUG] get_html: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10709&vid=v0501apykif&filename=v0501apykif.p709.3.mp4
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10709&vid=v0501apykif&filename=v0501apykif.p709.3.mp4
[DEBUG] url_info: http://202.77.59.46/vhot2.qqvideo.tc.qq.com/v0501apykif.p709.3.mp4?vkey=A8B079BF871E8684AA1407C78CAB9D0DABB7058D289B4E88A5DE4F736CBEBD2CAA14B0F0B45D3D36047DC97D3EF9876EC186826E71AD4836CE8DD80CF5744CC774030C286112F99646D18FDD4FEBF4EF6E15D9D96BBA34500BC122805574D3B5
Site:       QQ.com
Title:      木心美术馆对话陈丹青
Type:       MPEG-4 video (video/mp4)
Size:       186.35 MiB (195403072 Bytes)

Downloading 木心美术馆对话陈丹青.mp4 ...
 100% (233.5/186.4MB) ├████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[1/3]  441 kB/s
^CTraceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.715', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1158, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/extractors/qq.py", line 158, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/extractors/qq.py", line 59, in qq_download_by_vid
    download_urls(part_urls, parts_ti, ext, total_size, output_dir=output_dir, merge=merge)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 812, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 550, in url_save
    buffer = response.read(1024 * 256)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 很多个腾讯视频下载都会出现这样的状况，比如显示大小186.4MB，但会下载到超过186.4MB：100% (233.5/186.4MB) ，持续到下载几个G也不会停下来。

**Comment by rosynirvana** [comment]
虽说大概解决不了什么问题，现在最新版是0.4.750，你现在用的是0.4.715

**Comment by longdeqidao** [comment]
是的，我更新到0.4.750，结果是一样的。`另外腾讯的extractor实现是错误的，别对它报什么希望了` 是实现错误，还是实现不了？为什么不抱希望。 @rosynirvana

**Comment by rosynirvana** [comment]
实现错误

例如这个视频其实有4段，你贴出来的log拿到的是3段
再比如这个视频我用0.4.750可以正常下载

前端的东西，可以说没有实现不了的，只是（长期以来都）没人愿意去做

**Comment by longdeqidao** [comment]
吊！but the current situation sucks... should I close the issue? hmmm

**Comment by rosynirvana** [comment]
outdated
