### ISSUE TITLE
youtube下载失败

### ISSUE THREAD

**Issue by latel** [soimort/you-get#2085]
you https://www.youtube.com/watch?v=GVCzdpagXOQ
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
KEVINNWANG-MB0:Downloads kevin$ you https://www.youtube.com/watch?v=GVCzdpagXOQ --debug
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=GVCzdpagXOQ
[DEBUG] get_content: https://www.youtube.com/watch?v=GVCzdpagXOQ
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-vflQZSd3x/en_US/base.js
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=GVCzdpagXOQ']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractor.py", line 50, in download_by_url
    self.extract(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/youtube.py", line 410, in extract
    self.streams[stream_id]['size'] = urls_size(self.streams[stream_id]['src'])
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 401, in urls_size
    return sum([url_size(url, faker=faker, headers=headers) for url in urls])
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 401, in <listcomp>
    return sum([url_size(url, faker=faker, headers=headers) for url in urls])
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 395, in url_size
    response = urlopen_with_retry(url)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 307, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by latel** [comment]
没人看下嘛

**Comment by rosynirvana** [comment]
这个确实不是```you-get```的问题
另外发两遍没什么好处的
