### ISSUE TITLE
youtube 无法下载

### ISSUE THREAD

**Issue by WangGL1985** [soimort/you-get#2086]
我挂了 VPN chrome 播放没有问题

you-get -di https://www.youtube.com/watch\?v\=GVCzdpagXOQ
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=GVCzdpagXOQ
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=GVCzdpagXOQ']
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 330, in get_content
    response = urlopen_with_retry(req)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 307, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 65] No route to host>

**Comment by rosynirvana** [comment]
```No route to host``` 终究还是你的网络问题
建议研究研究你的console有没有走VPN，或者路由表是怎么设置的

```
$ you-get -di https://www.youtube.com/watch\?v\=GVCzdpagXOQ
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=GVCzdpagXOQ
[DEBUG] get_content: https://www.youtube.com/watch?v=GVCzdpagXOQ
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-vflQZSd3x/ja_JP/base.js
site:                YouTube
title:               Rebecca Black & Dave Days - Saturday
streams:             # Available quality and codecs
    [ DASH ] ____________________________________
    - itag:          137
      container:     mp4
      quality:       1920x1080
      size:          87.2 MiB (91442052 bytes)
    # download-with: you-get --itag=137 [URL]

    - itag:          248
      container:     webm
      quality:       1920x1080
      size:          64.5 MiB (67680242 bytes)
    # download-with: you-get --itag=248 [URL]

    - itag:          136
      container:     mp4
      quality:       1280x720
      size:          44.1 MiB (46230255 bytes)
    # download-with: you-get --itag=136 [URL]

    - itag:          247
      container:     webm
      quality:       1280x720
      size:          37.7 MiB (39567979 bytes)
    # download-with: you-get --itag=247 [URL]

    - itag:          135
      container:     mp4
      quality:       854x480
      size:          25.8 MiB (27042592 bytes)
    # download-with: you-get --itag=135 [URL]

    - itag:          244
      container:     webm
      quality:       854x480
      size:          22.2 MiB (23278955 bytes)
    # download-with: you-get --itag=244 [URL]

    - itag:          134
      container:     mp4
      quality:       640x360
      size:          15.3 MiB (16087338 bytes)
    # download-with: you-get --itag=134 [URL]

    - itag:          243
      container:     webm
      quality:       640x360
      size:          15.0 MiB (15715872 bytes)
    # download-with: you-get --itag=243 [URL]

    - itag:          133
      container:     mp4
      quality:       426x240
      size:          11.0 MiB (11521726 bytes)
    # download-with: you-get --itag=133 [URL]

    - itag:          242
      container:     webm
      quality:       426x240
      size:          10.2 MiB (10730592 bytes)
    # download-with: you-get --itag=242 [URL]

    - itag:          160
      container:     mp4
      quality:       256x144
      size:          7.0 MiB (7337239 bytes)
    # download-with: you-get --itag=160 [URL]

    - itag:          278
      container:     webm
      quality:       256x144
      size:          7.0 MiB (7324992 bytes)
    # download-with: you-get --itag=278 [URL]

    [ DEFAULT ] _________________________________
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          44.0 MiB (46176399 bytes)
    # download-with: you-get --itag=22 [URL]

    - itag:          43
      container:     webm
      quality:       medium
    # download-with: you-get --itag=43 [URL]

    - itag:          18
      container:     mp4
      quality:       medium
    # download-with: you-get --itag=18 [URL]

    - itag:          36
      container:     3gp
      quality:       small
    # download-with: you-get --itag=36 [URL]

    - itag:          17
      container:     3gp
      quality:       small
    # download-with: you-get --itag=17 [URL]
```

**Comment by WangGL1985** [comment]
@rosynirvana 
谢谢，我查查具体怎么操作吧。

**Comment by lirener** [comment]
![default](https://user-images.githubusercontent.com/19354130/27205245-319cde4c-5262-11e7-9338-71cafc94e068.jpg)
不挂VPN你至少也要hosts改一下 现在好多可以看youtube的hosts了 比如(Go Hosts、google-hosts、racaljk-hosts)甚至还有外链的 悠悠 Hosts都可以

**Comment by cnbeining** [comment]
Closed due to issue not moving forward.
