### ISSUE TITLE
youtube下载失败

### ISSUE THREAD

**Issue by yangaowei** [soimort/you-get#2094]
python3 you-get -di https://www.youtube.com/watch?v=GVCzdpagXOQ
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=GVCzdpagXOQ
[DEBUG] get_content: https://www.youtube.com/watch?v=GVCzdpagXOQ
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-vfle90bgw/en_US/base.js
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=GVCzdpagXOQ']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/root/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/root/you-get/src/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/root/you-get/src/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/root/you-get/src/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/root/you-get/src/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/root/you-get/src/you_get/extractor.py", line 50, in download_by_url
    self.extract(**kwargs)
  File "/root/you-get/src/you_get/extractors/youtube.py", line 410, in extract
    self.streams[stream_id]['size'] = urls_size(self.streams[stream_id]['src'])
  File "/root/you-get/src/you_get/common.py", line 401, in urls_size
    return sum([url_size(url, faker=faker, headers=headers) for url in urls])
  File "/root/you-get/src/you_get/common.py", line 401, in <listcomp>
    return sum([url_size(url, faker=faker, headers=headers) for url in urls])
  File "/root/you-get/src/you_get/common.py", line 395, in url_size
    response = urlopen_with_retry(url)
  File "/root/you-get/src/you_get/common.py", line 307, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by yan12125** [comment]
youtube-dl也遇到類似問題： https://github.com/rg3/youtube-dl/issues/13388 ，貌似是shadowsocks不能用了？

**Comment by rosynirvana** [comment]
```
$ you-get -d 'https://www.youtube.com/watch?v=elql9b_31IY'
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=elql9b_31IY
[DEBUG] get_content: https://www.youtube.com/watch?v=elql9b_31IY
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-vfle90bgw/ja_JP/base.js
site:                YouTube
title:               Duca - ISI
stream:
    - itag:          43
      container:     webm
      quality:       medium
      size:          7.3 MiB (7633999 bytes)
    # download-with: you-get --itag=43 [URL]

Downloading Duca - ISI.webm ...
 100% (  7.3/  7.3MB) ├█████████████████████████████████████████┤[1/1]  764 kB/s
```

proxy service provided by ```shadowsocks.com.hk```
ss client ```ShadowsocksX-NG 1.3.2(1)```

So I believe there's little to do with shadowsocks.

**Comment by yan12125** [comment]
Thanks. Almost all users at the aforementioned youtube-dl issue use shadowsocks with a server blocked by YouTube if connecting via IPv6. (It's not unusual that YouTube blocks IPv6 connections - there are already quite a few reports) As a result, I guess shadowsocks with IPv4 is broken for some users. Anyway that's just a guess. I'm not a victim of GFW and I don't use shadowsocks.

**Comment by yan12125** [comment]
Related: https://github.com/shadowsocks/shadowsocks/issues/867

**Comment by soimort** [comment]
As above -- Not really our problem, seems like some specific IP ranges are blocked by YouTube.
