### ISSUE TITLE
bilibili 视频下载失败

### ISSUE THREAD

**Issue by stella-shen** [soimort/you-get#2096]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get http://www.bilibili.com/video/av11399105/ -d
[DEBUG] get_content: http://www.bilibili.com/video/av11399105/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=18847311&from=miniplay&player=1&sign=92148e2aa190ff248b1c4cbe14b409f9
[DEBUG] url_info: http://cn-sdjn-cu-v-07.acgvideo.com/vg4/c/42/18847311-1.flv?expires=1497866400&platform=pc&ssig=IjHZj3l473FFHvK29nN5Qg&oi=1032300879&nfa=zewukGbkdeYAV6tVxJRokA==&dynamic=1&hfa=2071222846
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av11399105/']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.750', 'console_scripts', 'you-get')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 187, in bilibili_download
    info_only=info_only)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 101, in bilibili_download_by_cid
    _, type_, temp = url_info(url, headers={'Referer': 'http://www.bilibili.com/'})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 420, in url_info
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 307, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [尝试按照wiki下bilibili的添加cookie的方法添加了依旧是403Error]
> [舔 :icecream:!]

**Comment by luodaoyi** [comment]
b站防爬虫了  爬了都是403

**Comment by rosynirvana** [comment]
https://github.com/rosynirvana/you-get/tree/master

**Comment by sastation** [comment]
thx @rosynirvana , after upgrade to 0.4.750, it is work!

**Comment by awesome-tao** [comment]
下载的时候把header设置一下就行了
Hos:tx.acgvideo.com
Origin:http://www.bilibili.com
Referer:http://www.bilibili.com/video/av12345678/

**Comment by stella-shen** [comment]
@awesome-tao 是需要改一下extractors/bilibili.py 里的代码么？

**Comment by awesome-tao** [comment]
@stella-shen 不是吧，extractors/bilibili.py文件只是获取到了下载的url，你应该找下载视频的代码，在那里面改

**Comment by rosynirvana** [comment]
还有ua，这个问题也快一个月了 #2021

**Comment by stella-shen** [comment]
@rosynirvana @awesome-tao 更新到rosynirvana提供的地址问题解决了！！万分感谢！！！

**Comment by sakuramisaki** [comment]
@rosynirvana Thank you very much!  ٩(◕ω◕｡)۶

**Comment by rosynirvana** [comment]
bilibili的api访问返回的东西不确定
而youku或是pptv都是访问一次获取所有清晰度的流

也可以说bilibili的非付费内容并没有确切的清晰度概念，flv和mp4hd经常是差不多的东西

如果只是想要一个mp4容器的，个人比较建议用ffmpeg把拿到的文件重新封装成mp4

**Comment by MkAnaio** [comment]
maybe it is banned again. 
==================
Environment:
./you-get -h
you-get: version 0.4.750,
python -V
Python 3.6.1
===========================
The debug info. is as follows:
./you-get -id http://www.bilibili.com/video/av11399105
[DEBUG] get_content: http://www.bilibili.com/video/av11399105
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=18847311&from=miniplay&player=1&sign=92148e2aa190ff248b1c4cbe14b409f9
[DEBUG] url_info: http://ws.acgvideo.com/6/89/18847311-1.flv?wsTime=1498673308&platform=pc&wsSecret2=a6c63c7c94f252adc644c2efb83a561a&oi=1137817379&rate=1280
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av11399105']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/tmp/you-get/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/tmp/you-get/you-get/src/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/tmp/you-get/you-get/src/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/tmp/you-get/you-get/src/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/tmp/you-get/you-get/src/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/tmp/you-get/you-get/src/you_get/extractors/bilibili.py", line 187, in bilibili_download
    info_only=info_only)
  File "/tmp/you-get/you-get/src/you_get/extractors/bilibili.py", line 101, in bilibili_download_by_cid
    _, type_, temp = url_info(url, headers={'Referer': 'http://www.bilibili.com/'})
  File "/tmp/you-get/you-get/src/you_get/common.py", line 420, in url_info
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "/tmp/you-get/you-get/src/you_get/common.py", line 307, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/python3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/python3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/python3.6/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/local/python3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/python3.6/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/python3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/python3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/python3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/python3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/python3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by MkAnaio** [comment]
Thank you. It is resolved!

**Comment by cnbeining** [comment]
Closed due to issue solved.
