### ISSUE TITLE
proxychains you-get -di 没法下载youtube视频

### ISSUE THREAD

**Issue by outsinre** [soimort/you-get#2097]
proxychians is configured with a socks5 proxy.

```
~ $ proxychains you-get --debug -i "https://www.youtube.com/watch?v=aw6RsUhw1Q8"
```

Debug info:

```
(pyvenv3) bobme@zhtux ~ $ proxychains you-get --debug -i "https://www.youtube.com/watch?v=aw6RsUhw1Q8"
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib64/libproxychains.so.4.11
[proxychains] DLL init: proxychains-ng 4.11
[proxychains] DLL init: proxychains-ng 4.11
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=aw6RsUhw1Q8
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  61.91.161.217:443  ...  OK
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=aw6RsUhw1Q8']
Traceback (most recent call last):
  File "/usr/lib64/python3.4/urllib/request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib64/python3.4/http/client.py", line 1287, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.4/ssl.py", line 362, in wrap_socket
    _context=self)
  File "/usr/lib64/python3.4/ssl.py", line 580, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.4/ssl.py", line 807, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/outsinre/opt/pyvenv3/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/extractors/youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/common.py", line 330, in get_content
    response = urlopen_with_retry(req)
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/common.py", line 307, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 464, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.4/urllib/request.py", line 482, in _open
    '_open', req)
  File "/usr/lib64/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 1226, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.4/urllib/request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
```

**Comment by soimort** [comment]
Seems like a proxy-specific problem. Please confirm with

```
  $ proxychains curl -I 'https://www.youtube.com/get_video_info?video_id=aw6RsUhw1Q8'
```

**Comment by outsinre** [comment]
Done. It seems to be my custom hosts setting. proxychains fails to proxy dns while settting custom hosts file.

After removing custom hosts file, it works like a charm.
