### ISSUE TITLE
Cannot download music from music.163

### ISSUE THREAD

**Issue by xbbshampoo** [soimort/you-get#2112]
Hi guys, there is an issue with music.163

```
➜  ~ you-get --debug https://music.163.com/album/35657280
[DEBUG] get_content: http://music.163.com/api/album/35657280?id=35657280&csrf_token=
Skipping ./A-Lin - 一直走/cover.jpg: file already exists

[DEBUG] url_info: http://p2.music.126.net/hmZoNQaqzZALvVp0rE7faA==/0.mp3
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['https://music.163.com/album/35657280']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.715', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1158, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/extractors/netease.py", line 133, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/extractors/netease.py", line 41, in netease_cloud_music_download
    netease_song_download(i, output_dir=new_dir, info_only=info_only)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/extractors/netease.py", line 120, in netease_song_download
    output_dir=output_dir, info_only=info_only)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/extractors/netease.py", line 123, in netease_download_common
    songtype, ext, size = url_info(url_best)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 425, in url_info
    response = urlopen_with_retry(request.Request(url))
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 310, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by rosynirvana** [comment]
dup #2074
