### ISSUE TITLE
letv can not work 

### ISSUE THREAD

**Issue by batjoker** [soimort/you-get#2119]
汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
E:\software\video\download\you-get-master>python you-get -d http://www.le.com/pt
v/vplay/30217759.html
[DEBUG] url_locations: http://www.le.com/ptv/vplay/30217759.html
[DEBUG] get_content: http://www.le.com/ptv/vplay/30217759.html
[DEBUG] get_content: http://player-pc.le.com/mms/out/video/playJson.json?id=3021
7759&devid=b2627e53fcfe1053c695acbcaedc8315&tkey=1046354836&dvtype=1000&domain=w
ww.le.com&region=cn&accesyx=1&platid=3&splatid=304&source=1001
you-get: version 0.4.750-testing, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/30217759.html']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "E:\software\video\download\you-get-master/src\you_get\__main__.py", line
 92, in main
    main(**kwargs)
  File "E:\software\video\download\you-get-master/src\you_get\common.py", line 1
421, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "E:\software\video\download\you-get-master/src\you_get\common.py", line 1
305, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "E:\software\video\download\you-get-master/src\you_get\common.py", line 1
089, in download_main
    download(url, **kwargs)
  File "E:\software\video\download\you-get-master/src\you_get\common.py", line 1
409, in any_download
    m.download(url, **kwargs)
  File "E:\software\video\download\you-get-master/src\you_get\extractors\le.py",
 line 163, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, i
nfo_only=info_only,**kwargs)
  File "E:\software\video\download\you-get-master/src\you_get\extractors\le.py",
 line 110, in letv_download_by_vid
    ext, urls, is_mp4 = video_info(vid, **kwargs)
  File "E:\software\video\download\you-get-master/src\you_get\extractors\le.py",
 line 66, in video_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 使用的是#rosynirvana 最新修改后的版本 看到更新了letv的api到html5 但是报错

**Comment by rosynirvana** [comment]
你用的不是大陆IP吧

```
$ ./you-get -di 'http://www.le.com/ptv/vplay/30217759.html'
[DEBUG] url_locations: http://www.le.com/ptv/vplay/30217759.html
[DEBUG] get_content: http://www.le.com/ptv/vplay/30217759.html
[DEBUG] get_content: http://player-pc.le.com/mms/out/video/playJson.json?dvtype=1000&platid=3&region=cn&splatid=304&accesyx=1&domain=www.le.com&source=1001&id=30217759&devid=b5b6b790536784fed434a0deb7b7e88d&tkey=1113463728
Current Video Supports:
	--format  1300 <URL>
	--format  1000 <URL>
	--format   350 <URL>
[DEBUG] get_content: http://play.g3proxy.lecloud.com/vod/v2/MjYwLzQzLzU0L2xldHYtdXRzLzE0L3Zlcl8wMF8yMi0xMTA4MDg2NzQxLWF2Yy00MTk1ODktYWFjLTQ4MDAwLTMwMzQzMjAtMTgyMDUyMDUzLWJlZmRlYThhMzMzZGVjODE1MjNmMzA0MzZjMjFiNWZhLTE0OTg4MzE3Nzk2MzMubXA0?b=479&mmsid=65607910&tm=1498982729&key=83d9c845c7d4a5f1b68e97d13c48745a&platid=3&splatid=304&playid=0&tss=no&vtype=13&cvid=408495672742&payff=0&pip=7049846838d2608d2f569ee3888abfc8&m3v=1&termid=1&format=1&hwtype=un&ostype=MacOS10.12.4&p1=1&p2=10&p3=-&expect=3&tn=0.7337878965928155&vid=30217759&uuid=BA6B0631E24C202B97DC201B47D9BE7E5BB859EC_0&sign=letv
Site:       Le.com
Title:      《好好吃饭吧》20170702：Twins神同步默契满分 阿娇抡双刀吓傻阿Sa
Type:       MPEG-4 video (video/mp4)
Size:       173.62 MiB (182052053 Bytes)
```

```
$ export http_proxy=127.0.0.1:1087
$ ./you-get -di 'http://www.le.com/ptv/vplay/30217759.html'
[DEBUG] url_locations: http://www.le.com/ptv/vplay/30217759.html
[DEBUG] get_content: http://www.le.com/ptv/vplay/30217759.html
[DEBUG] get_content: http://player-pc.le.com/mms/out/video/playJson.json?region=cn&devid=a5b923ab5574f782917d3e15b249602f&dvtype=1000&id=30217759&tkey=2556304304&domain=www.le.com&source=1001&platid=3&accesyx=1&splatid=304
you-get: version 0.4.750-testing, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/30217759.html']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 1421, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 1305, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 1089, in download_main
    download(url, **kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 1409, in any_download
    m.download(url, **kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/extractors/le.py", line 163, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/extractors/le.py", line 110, in letv_download_by_vid
    ext, urls, is_mp4 = video_info(vid, **kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/extractors/le.py", line 66, in video_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'
```
