### ISSUE TITLE
cant download youku 

### ISSUE THREAD

**Issue by xiaoheiai4719** [soimort/you-get#2122]
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.715', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1158, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.715/libexec/lib/python3.6/site-packages/you_get/extractors/tudou.py", line 47, in tudou_download
    title = r1(r'\Wkw\s*[:=]\s*[\'\"]([^\n]+?)\'\s*\n', html).replace("\\'", "\'")
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by soimort** [comment]
Closed via #2015.
