### ISSUE TITLE
you-get突然不能下载视频了

### ISSUE THREAD

**Issue by keith-zheng** [soimort/you-get#2124]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
[DEBUG] get_response: http://www.acfun.cn/v/ac3826355
[DEBUG] get_response: http://www.acfun.tv/video/getVideo.aspx?id=5374904
[DEBUG] get_content: http://api.aixifan.com/plays/5374904
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519d032263f8&video_id=5959305c0cf2506591385d23&embsig=1_1499103348_9341dd591583a43253eb5528eee522f6
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=5959305c0cf2506591385d23&ct=85&sign=MXwxNDk5MTAzNDIxfDBmY2RlY2E5ZmNiNWNmNjBmOWRjNDE3ZWUwNjdiYTY5
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac3826355']
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\acfun.py", line 90, in acfun_download
    **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\acfun.py", line 55, in acfun_download_by_vid
    youku_open_download_by_vid(client_id='908a519d032263f8', vid=sourceId, title=title, output_dir=output_dir,merge=merge, info_only=info_only, embsig = embsig, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\youku.py", line 375, in open_download_by_vid
    self.prepare(api_url = api85_url, api12_url = api86_url, ctype = 86, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\youku.py", line 172, in prepare
    headers={'Referer': 'http://static.youku.com/'}
  File "c:\users\admin\appdata\local\programs\python\python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\admin\appdata\local\programs\python\python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)


If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
[DEBUG] get_response: http://www.acfun.cn/v/ac3826355
[DEBUG] get_response: http://www.acfun.tv/video/getVideo.aspx?id=5374904
[DEBUG] get_content: http://api.aixifan.com/plays/5374904
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519d032263f8&video_id=5959305c0cf2506591385d23&embsig=1_1499103348_9341dd591583a43253eb5528eee522f6
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=5959305c0cf2506591385d23&ct=85&sign=MXwxNDk5MTAzNDIxfDBmY2RlY2E5ZmNiNWNmNjBmOWRjNDE3ZWUwNjdiYTY5
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac3826355']
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\acfun.py", line 90, in acfun_download
    **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\acfun.py", line 55, in acfun_download_by_vid
    youku_open_download_by_vid(client_id='908a519d032263f8', vid=sourceId, title=title, output_dir=output_dir,merge=merge, info_only=info_only, embsig = embsig, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\youku.py", line 375, in open_download_by_vid
    self.prepare(api_url = api85_url, api12_url = api86_url, ctype = 86, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\youku.py", line 172, in prepare
    headers={'Referer': 'http://static.youku.com/'}
  File "c:\users\admin\appdata\local\programs\python\python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\admin\appdata\local\programs\python\python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by lamlam123tld3** [comment]
ua referrer again....

**Comment by rosynirvana** [comment]
referer？

acfun.py is broken for months because of api not updated

**Comment by lamlam123tld3** [comment]
ServiceUrl switch from

> http://aplay-vod.cn-beijing.aliyuncs.com/acfun/web

to

> http://player.acfun.cn/flash_data

Other things remain unchanged

the only different of the return from the second api is the ran parameter of the urls is now required

**Comment by soimort** [comment]
Closed via #2010.

**Comment by lamlam123tld3** [comment]
reopen again
a cookie "ac__avi" returned from the service_url "http://player.acfun.cn/flash_data" is required when requesting for the mp4 segments

**Comment by rosynirvana** [comment]
```
$ you-get -d 'http://www.acfun.cn/v/ac3852297'
[DEBUG] get_content: http://www.acfun.cn/v/ac3852297
[DEBUG] get_content: http://www.acfun.tv/video/getVideo.aspx?id=5419058
[DEBUG] get_content: http://aplay-vod.cn-beijing.aliyuncs.com/acfun/web?vid=5966def20cf2009f5ee8d71e&ct=85&ev=3&sign=1_1500097812_df1e8abdb2998b6aadd5a73afb224183
[DEBUG] url_info: http://player.acfun.cn/route_mp4?uid=0&timestamp=1500097812&fid=020040020400005966E14000010001370000000000-0000-0000-018C-82A800000000.mp4&ns=video.acfun.cn&ran=0&vid=5966def20cf2009f5ee8d71e&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct5969ad140cf22b644f448420
[DEBUG] url_info: http://player.acfun.cn/route_mp4?uid=0&timestamp=1500097812&fid=020140020400005966E14000010001370000000000-0000-0000-018C-82A800000000.mp4&ns=video.acfun.cn&ran=0&vid=5966def20cf2009f5ee8d71e&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct5969ad140cf22b644f448420
Site:       AcFun.tv
Title:      【MMD】靓丽清新和风短裙装3人「恋愛デコレート」 - 卿卿酱
Type:       MPEG-4 video (video/mp4)
Size:       116.4 MiB (122057421 Bytes)

Downloading 【MMD】靓丽清新和风短裙装3人「恋愛デコレート」 - 卿卿酱.mp4 ...
 100% (116.4/116.4MB) ├██████████████████████████████████████████████┤[2/2]  730 kB/s
```

still works for me
