### ISSUE TITLE
下载部分屑站视频时发生ValueError: Sign not allowed in string format specifier错误

### ISSUE THREAD

**Issue by Z4HD** [soimort/you-get#2139]
>- [x] You can actually watch the video in yourbrowser or mobile application, but not download them with `you-get`.
>- [x] Your `you-get` is up-to-date.
>- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
>- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
>- [x] The issue (or question) is really about `you-get`, not about some other code or project.

调试信息：

``` shell
Welcome to Termux!

$ you-get --debug -O 'cqx' 'http://www.bilibili.com/video/av10448626'
[DEBUG] url_locations: http://www.bilibili.com/video/av10448626
[DEBUG] get_content: http://www.bilibili.com/video/av10448626/
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=17254639&player=1&quality=3&ts=1499695246&sign=3b9589441978172fbbb89537b7bec95a
[DEBUG] get_content: http://comment.bilibili.com/17254639.xml
site:                Bilibili
title:               是的！我已经过气了
stream:
    - format:        flv
      container:     flv
      size:          88.799999999999997 MiB (93162574 bytes)
    # download-with: you-get --format=flv [URL]

Downloading cqx.flv ...
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av10448626']
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 1180, in download_main
    download(url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/extractor.py", line 58, in download_by_url
    self.download(**kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/extractor.py", line 220, in download
    av=stream_id in self.dash_streams)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 821, in download_urls
    bar.update()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 696, in update
    bar = self.bar.format(percent, round(self.received / 1048576, 1), bar, self.current_piece, self.total_pieces, self.speed)
ValueError: Sign not allowed in string format specifier
$
```

即使利用`-O`指定简单的文件名仍不能有效避免所有情况下的错误。目测是下载进度条（bar）导致的错误？

**Comment by rosynirvana** [comment]
这问题十有八九在libc里面……
估计是负责编译release的人搞错了libc的浮点数默认精度

https://stackoverflow.com/questions/2234303/emulate-floating-point-string-conversion-behaviour-of-linux-on-windows

```
$ you-get --debug -O 'cqx' 'http://www.bilibili.com/video/av10448626'
[DEBUG] url_locations: http://www.bilibili.com/video/av10448626
[DEBUG] get_content: http://www.bilibili.com/video/av10448626/
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=17254639&player=1&quality=3&ts=1499696871&sign=3f94947b537692996c3a321d1da09635
[DEBUG] get_content: http://comment.bilibili.com/17254639.xml
site:                Bilibili
title:               是的！我已经过气了
stream:
    - format:        flv
      container:     flv
      size:          88.8 MiB (93162574 bytes)
    # download-with: you-get --format=flv [URL]

Downloading cqx.flv ...
 100% ( 88.8/ 88.8MB) ├██████████████████████████████████████████████┤[1/1]    2 MB/s

Downloading 是的！我已经过气了.cmt.xml ...
```

我个人建议您不要在安卓平台上来下载，因为py并不官方支持android

**Comment by Z4HD** [comment]
@rosynirvana 要真是libc的问题，怕是要很长一段时间后才能解决罢，，，

如果在其他平台上没有问题，那么建议在[Known Bugs](https://github.com/soimort/you-get/wiki/Known-Bugs)里添加“不建议在Android平台/Termux中使用”的相关内容。
