### ISSUE TITLE
Youku HTTP 498 when downloading VIP videos with loaded cookies

### ISSUE THREAD

**Issue by pxia** [soimort/you-get#2140]
This happens when downloading fairly long VIP videos. The first few segments can be downloaded fine, but the server will start responding HTTP 498 (starting with the 57th segment in this case). It can be reproduced reliably. 

HTTP 498 means token expired. It might be the case that Youku server has added some logic to require a refreshed token for the later part of a video. This probably involves changing the request header to the video server.

I think currently we only change the request headers for extracting the video, but not for downloading. This was not an issue in the past, but I've observed that video servers have start to behave differently based on different headers. For example, they will throttle speed based on the User Agent. In my experiment, some segments of the videos are heavily throttled when downloading with a default/empty UA (we are talking 5KB/s), while when I changed to the UA of the Youku iOS app, the speed will become 30MB/s.

```
$ you-get -d -c ../cookies.txt http://v.youku.com/v_show/id_XMjg4NDEzNTI4OA\=\=.html\?spm\=a2hzp.8253869.0.0
you-get: Found cna in imported cookies. Use it
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjg4NDEzNTI4OA==&ccode=0401&client_ip=192.168.1.1&utid=L3q6EEVDqxUCAWiEAEb1h%2B6f&client_ts=1499799437
site:                优酷 (Youku)
title:               德云社郭麒麟相声专场杭州站整场
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          2557.3 MiB (2681488349 bytes)
    # download-with: you-get --format=hd3 [URL]

Downloading 德云社郭麒麟相声专场杭州站整场.flv ...
22.4% ( 573.7/2557.3MB) ├██████████───────────────────────────────────┤[22/91]  633 MB/syou-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjg4NDEzNTI4OA==.html?spm=a2hzp.8253869.0.0']
Traceback (most recent call last):
  File "/Users/pxia/homebrew/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Users/pxia/homebrew/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/pxia/homebrew/lib/python3.6/site-packages/you_get/common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/pxia/homebrew/lib/python3.6/site-packages/you_get/common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/pxia/homebrew/lib/python3.6/site-packages/you_get/common.py", line 1180, in download_main
    download(url, **kwargs)
  File "/Users/pxia/homebrew/lib/python3.6/site-packages/you_get/common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "/Users/pxia/homebrew/lib/python3.6/site-packages/you_get/extractor.py", line 58, in download_by_url
    self.download(**kwargs)
  File "/Users/pxia/homebrew/lib/python3.6/site-packages/you_get/extractor.py", line 220, in download
    av=stream_id in self.dash_streams)
  File "/Users/pxia/homebrew/lib/python3.6/site-packages/you_get/common.py", line 834, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "/Users/pxia/homebrew/lib/python3.6/site-packages/you_get/common.py", line 509, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "/Users/pxia/homebrew/lib/python3.6/site-packages/you_get/common.py", line 418, in url_size
    response = urlopen_with_retry(url)
  File "/Users/pxia/homebrew/lib/python3.6/site-packages/you_get/common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/Users/pxia/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/pxia/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Users/pxia/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/pxia/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Users/pxia/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Users/pxia/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 498:
```

**Comment by pxia** [comment]
After playing with it a bit more, I found the HTTP 498 response code might be misleading. Instead of a expired token, this is more a server side rate-limiting constraint or DDOS protection. 

The root cause is that when we resume a previous download, we will still query the file size information of the already-downloaded segments. This spawns a lot of network requests instantaneously. This is especially bad for long videos. For a 90-segment video with 60 segments downloaded, we need to query the video server 60 times before actually resuming the download. It is almost guaranteed the program will fail in this case.

There are two ways I can think of to fix this and they are not mutually exclusive:
1. Stop querying information about already downloaded segments
2. Make urlopen_with_retry() more robust and fault tolerant. Currently, it only recovers from socket.timeout, and it is certainly not the only transient error the program can encounter. I've also seen connection reset by peer errors, which can certainly be recovered as well. As for bad http code, although they mean the connection to server is successful, this 498 can certainly be recovered by adding a small delay before retrying.
