### ISSUE TITLE
error parsing weixin.qq.com pages

### ISSUE THREAD

**Issue by Paulswith** [soimort/you-get#2141]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
➜  ~ you-get --version
you-get: version 0.4.775, a tiny downloader that scrapes the web.
➜  ~ you-get -t 30 -u 'http://mp.weixin.qq.com/s?__biz=MzAwMTc0OTYwMA==&amp;mid=2648420948&amp;idx=1&amp;sn=7d0464125b8aafff3cdda7cbcc4b70fa&amp;scene=19#wechat_redirect' --debug
[DEBUG] get_response: http://mp.weixin.qq.com/s?__biz=MzAwMTc0OTYwMA==&amp;mid=2648420948&amp;idx=1&amp;sn=7d0464125b8aafff3cdda7cbcc4b70fa&amp;scene=19#wechat_redirect
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=o0521obbv5l
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10701&vid=o0521obbv5l&filename=o0521obbv5l.p701.1.mp4
[DEBUG] url_info: http://183.60.23.23/vhot2.qqvideo.tc.qq.com/A_CkVNxrVxPqF0NT_RvjXb9qefecBuTqb-NwfVRID9V0/o0521obbv5l.p701.1.mp4?vkey=8DED014B190703E28D533002CA3284862D540C6165D0319E4B01E904C67C04C91454BAE5F01B39BCCD0F9FA7641399D6F764C244EBE7CE98F8A43F0D24B15DC650291C4744C5478C29D6E4B46ED26F4EF57B8F696EFC32C789CF62DA0187130F
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10701&vid=o0521obbv5l&filename=o0521obbv5l.p701.2.mp4
[DEBUG] url_info: http://183.60.23.23/vhot2.qqvideo.tc.qq.com/A_CkVNxrVxPqF0NT_RvjXb9qefecBuTqb-NwfVRID9V0/o0521obbv5l.p701.2.mp4?vkey=081FAB8FBA1608C46CDD2E6EC754D4FC59979B776CA328C51277BA698B27FAA2363D007381B4885534BE09B3D5560E8E3A48B6F25C88A92554090B5A6B85F750396C892AE5CE433133008A6CA897C62657D8621A589DECEA6359E3E95AF091BD
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10701&vid=o0521obbv5l&filename=o0521obbv5l.p701.3.mp4
[DEBUG] url_info: http://183.60.23.23/vhot2.qqvideo.tc.qq.com/A_CkVNxrVxPqF0NT_RvjXb9qefecBuTqb-NwfVRID9V0/o0521obbv5l.p701.3.mp4?vkey=C22A8EEB857ED393478125F664EFE66660E939F9140211624B196F27C7F6D49AA0FD6FC832F987AC13EE8302E83FBFDA996205B4666D448A90A17130EF63B1B615C206727585DF6B8434E103B4D7430DCA5A8791F7483A3F58EB8FAE57790F2A
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10701&vid=o0521obbv5l&filename=o0521obbv5l.p701.4.mp4
[DEBUG] url_info: http://183.60.23.23/vhot2.qqvideo.tc.qq.com/A_CkVNxrVxPqF0NT_RvjXb9qefecBuTqb-NwfVRID9V0/o0521obbv5l.p701.4.mp4?vkey=2C6C21A4EE147915995BC1619CD9C11351C7114EF5A85A7FF5DDD44EAD55C282B358D2CF408F75B3DFFEC0A6287E800DE16EC9F1C22B1A15F0FC4D21174539EA9980E67F494B6937F0C140679DF08865C2FF71F6ED7ACE151BD39CEEF9A9881B
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10701&vid=o0521obbv5l&filename=o0521obbv5l.p701.5.mp4
[DEBUG] url_info: http://183.60.23.23/vhot2.qqvideo.tc.qq.com/A_CkVNxrVxPqF0NT_RvjXb9qefecBuTqb-NwfVRID9V0/o0521obbv5l.p701.5.mp4?vkey=D65524470910C315A2D8E800BAB8A829CED8FD1996429A5E727C709B2A49541B3C5EC2D0E8A65168899CF570BF7716B01C6055AEB8CCA6D654A4407BB868AA7335E17EA8BAEF8DD260866305A2DD9D23E3B6CB356B97BDCD514F576B95A7EBC9
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10701&vid=o0521obbv5l&filename=o0521obbv5l.p701.6.mp4
[DEBUG] url_info: http://183.60.23.23/vhot2.qqvideo.tc.qq.com/A_CkVNxrVxPqF0NT_RvjXb9qefecBuTqb-NwfVRID9V0/o0521obbv5l.p701.6.mp4?vkey=B04CB19762B46C53F5F003ABB2DE41D64E337D55565633F96CCE275A586AAE79C77AD572F7E03A82180E41E191DDD0C00688C9A3F75EC6F03674D613B25085ACAA408AE9A3B58AAEE6EB9CEF1873C9C838753CA72071B605659900A1E2CB7B58
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10701&vid=o0521obbv5l&filename=o0521obbv5l.p701.7.mp4
Site:       QQ.com
Title:      02 Python-接口自动化测试实战-HTTP协议讲解
Type:       MPEG-4 video (video/mp4)
Size:       256.33 MiB (268781729 Bytes)

Real URLs:
http://183.60.23.23/vhot2.qqvideo.tc.qq.com/A_CkVNxrVxPqF0NT_RvjXb9qefecBuTqb-NwfVRID9V0/o0521obbv5l.p701.1.mp4?vkey=8DED014B190703E28D533002CA3284862D540C6165D0319E4B01E904C67C04C91454BAE5F01B39BCCD0F9FA7641399D6F764C244EBE7CE98F8A43F0D24B15DC650291C4744C5478C29D6E4B46ED26F4EF57B8F696EFC32C789CF62DA0187130F
http://183.60.23.23/vhot2.qqvideo.tc.qq.com/A_CkVNxrVxPqF0NT_RvjXb9qefecBuTqb-NwfVRID9V0/o0521obbv5l.p701.2.mp4?vkey=081FAB8FBA1608C46CDD2E6EC754D4FC59979B776CA328C51277BA698B27FAA2363D007381B4885534BE09B3D5560E8E3A48B6F25C88A92554090B5A6B85F750396C892AE5CE433133008A6CA897C62657D8621A589DECEA6359E3E95AF091BD
http://183.60.23.23/vhot2.qqvideo.tc.qq.com/A_CkVNxrVxPqF0NT_RvjXb9qefecBuTqb-NwfVRID9V0/o0521obbv5l.p701.3.mp4?vkey=C22A8EEB857ED393478125F664EFE66660E939F9140211624B196F27C7F6D49AA0FD6FC832F987AC13EE8302E83FBFDA996205B4666D448A90A17130EF63B1B615C206727585DF6B8434E103B4D7430DCA5A8791F7483A3F58EB8FAE57790F2A
http://183.60.23.23/vhot2.qqvideo.tc.qq.com/A_CkVNxrVxPqF0NT_RvjXb9qefecBuTqb-NwfVRID9V0/o0521obbv5l.p701.4.mp4?vkey=2C6C21A4EE147915995BC1619CD9C11351C7114EF5A85A7FF5DDD44EAD55C282B358D2CF408F75B3DFFEC0A6287E800DE16EC9F1C22B1A15F0FC4D21174539EA9980E67F494B6937F0C140679DF08865C2FF71F6ED7ACE151BD39CEEF9A9881B
http://183.60.23.23/vhot2.qqvideo.tc.qq.com/A_CkVNxrVxPqF0NT_RvjXb9qefecBuTqb-NwfVRID9V0/o0521obbv5l.p701.5.mp4?vkey=D65524470910C315A2D8E800BAB8A829CED8FD1996429A5E727C709B2A49541B3C5EC2D0E8A65168899CF570BF7716B01C6055AEB8CCA6D654A4407BB868AA7335E17EA8BAEF8DD260866305A2DD9D23E3B6CB356B97BDCD514F576B95A7EBC9
http://183.60.23.23/vhot2.qqvideo.tc.qq.com/A_CkVNxrVxPqF0NT_RvjXb9qefecBuTqb-NwfVRID9V0/o0521obbv5l.p701.6.mp4?vkey=B04CB19762B46C53F5F003ABB2DE41D64E337D55565633F96CCE275A586AAE79C77AD572F7E03A82180E41E191DDD0C00688C9A3F75EC6F03674D613B25085ACAA408AE9A3B58AAEE6EB9CEF1873C9C838753CA72071B605659900A1E2CB7B58
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=vid
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://mp.weixin.qq.com/s?__biz=MzAwMTc0OTYwMA==&amp;mid=2648420948&amp;idx=1&amp;sn=7d0464125b8aafff3cdda7cbcc4b70fa&amp;scene=19#wechat_redirect']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1180, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/qq.py", line 130, in qq_download
    qq_download_by_vid(vid, vid, output_dir, merge, info_only)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/qq.py", line 13, in qq_download_by_vid
    parts_vid = video_json['vl']['vi'][0]['vid']
KeyError: 'vl'
```
![image](https://user-images.githubusercontent.com/24262233/28110521-47d55950-6725-11e7-9cc3-a56a8a5730fa.png)

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
问题在这里
```
vids = matchall(content, [r'\bvid=(\w+)'])
```

**Comment by rosynirvana** [comment]
```js
(function(){
--
  | var iframe = document.getElementsByTagName('iframe');
  | for (var i=0,il=iframe.length;i<il;i++) {
  | var a = iframe[i];
  | var src_ = a.getAttribute('src')||a.getAttribute('data-src')||"";
  | if(!/http(s)*\:\/\/v\.qq\.com\/iframe\/(preview|player)\.html\?/.test(src_)){
  | continue;
  | }
  | var vid = getQuery("vid",src_);
  | if(!vid){
  | continue;
  | }
  | vid=vid.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"");
  | a.removeAttribute('src');
  | var obj = window.__getVideoWh(a),
  | mydiv = document.createElement('img');
  | mydiv.className = "img_loading";
  | mydiv.src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==";
  | mydiv.setAttribute("data-vid",vid);
  | mydiv.style.cssText = "width: " + obj.w + "px !important;height: " + obj.h + "px !important;";
  | a.style.display = "none";
  | insertAfter(mydiv,a);
  | a.style.cssText += ";width: " + obj.w + "px !important;height: " + obj.h + "px !important;";
  | a.setAttribute("width",obj.w);
  | a.setAttribute("height",obj.h);
  | a.setAttribute("data-vh",obj.vh);
  | a.setAttribute("data-vw",obj.vw);
  | a.setAttribute("data-src",location.protocol+"//v.qq.com/iframe/player.html?vid="+ vid + "&width="+obj.vw+"&height="+obj.vh+"&auto=0");
  | }
  | })();
```

```html
<iframe width="556" height="417" class="video_iframe" frameborder="0" allowfullscreen="" style="   z-index: 1; " data-vidtype="2" data-src="https://v.qq.com/iframe/preview.html?vid=o0521obbv5l&amp;width=500&amp;height=375&amp;auto=0">
```

**Comment by rosynirvana** [comment]
```
$ ./you-get -i 'https://mp.weixin.qq.com/s?__biz=MzAwMTc0OTYwMA==&amp;mid=2648420948&amp;idx=1&amp;sn=7d0464125b8aafff3cdda7cbcc4b70fa&amp;scene=19#wechat_redirect'
Site:       QQ.com
Title:      02 Python-接口自动化测试实战-HTTP协议讲解
Type:       MPEG-4 video (video/mp4)
Size:       256.33 MiB (268781729 Bytes)
```
