### ISSUE TITLE
Dilidili在线视频无法下载

### ISSUE THREAD

**Issue by OHLIA** [soimort/you-get#2143]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]
----------------------------------------------------------------------
----------------------------------------------------------------------
you-get --debug http://www.dilidili.wang/watch3/59385

[DEBUG] get_content: http://www.dilidili.wang/watch3/59385
[DEBUG] dilidili_download: https://api.47ks.com/webcloud/?v=http://v.youku.com/v_show/id_XMjg3NDQyNDcxNg==.html
[DEBUG] get_content: https://api.47ks.com/webcloud/?v=http://v.youku.com/v_show/id_XMjg3NDQyNDcxNg==.html
[DEBUG] get_content: https://newplayer.jfrft.com/parse.php?xmlurl=null&type=None&vid=None&hd=None&sign=None&tmsign=None&
userlink=None
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://www.dilidili.wang/watch3/59385']
Traceback (most recent call last):
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\NEWLIA\AppData\Local\Programs\Python\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1378, in scrip
t_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only,
json_output=json_output, caption=caption)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1180, in downl
oad_main
    download(url, **kwargs)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1460, in any_d
ownload
    m.download(url, **kwargs)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\dilidili.py", line 6
8, in dilidili_download
    stream_types = dilidili_parser_data_to_stream_types(typ, vid, hd2, sign, tmsign, ulk)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\dilidili.py", line 2
8, in dilidili_parser_data_to_stream_types
    info = re.search(r'(\{[^{]+\})(\{[^{]+\})(\{[^{]+\})(\{[^{]+\})(\{[^{]+\})', html).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by rosynirvana** [comment]
```
http://www.dilidili.wang/watch3/59361/
<iframe src="https://api.47ks.com/webcloud/?v=http://v.youku.com/v_show/id_XMjg3MjQ3MDk2OA==.html" frameborder="0" border="0" marginwidth="0" marginheight="0" scrolling="no" id="player_iframe" allowfullscreen="true"></iframe>
```

```
http://www.dilidili.wang/watch3/59308/
<iframe src="https://api.47ks.com/webcloud/?v=http://v.youku.com/v_show/id_XMjg2MjIwMzM3Mg==.html" frameborder="0" border="0" marginwidth="0" marginheight="0" scrolling="no" id="player_iframe" allowfullscreen="true"></iframe>
```

```
http://www.dilidili.wang/watch3/59344/
<iframe src="http://aikan-tv.com/?url=http://v.youku.com/v_show/id_XMjg2ODkyNzM0NA==.html" frameborder="0" border="0" marginwidth="0" marginheight="0" scrolling="no" id="player_iframe" allowfullscreen="true"></iframe>
```

```
http://www.dilidili.wang/watch3/59318/
<iframe src="https://api.47ks.com/webcloud/?v=http://v.youku.com/v_show/id_XMjg2NDEzNjY1Ng==.html" frameborder="0" border="0" marginwidth="0" marginheight="0" scrolling="no" id="player_iframe" allowfullscreen="true"></iframe>
```

```
http://www.dilidili.wang/watch3/59350/
<iframe src="https://api.47ks.com/webcloud/?v=http://v.youku.com/v_show/id_XMjg2OTU4MjI1Mg==.html" frameborder="0" border="0" marginwidth="0" marginheight="0" scrolling="no" id="player_iframe" allowfullscreen="true"></iframe>
```

```
http://www.dilidili.wang/watch3/59349/
<iframe src="https://api.47ks.com/webcloud/?v=http://v.youku.com/v_show/id_XMjg2NTI2OTgyMA==.html" frameborder="0" border="0" marginwidth="0" marginheight="0" scrolling="no" id="player_iframe" allowfullscreen="true"></iframe>
```

翻了一堆都是youku的……

**Comment by airdge** [comment]
那地址用you-get解析就好了,这种都是第三方解析,变动比较频繁

AES/ECB加密
```
var dfgsd='contentWindowHig';
var rgfgb='contentDocuments';
function (a){
	var b=CryptoJS.MD5(dfgsd);
	var c=CryptoJS.enc.Utf8.parse(b);
	var d=CryptoJS.enc.Utf8.parse(rgfgb);
	var e=CryptoJS.AES.encrypt(a,c,{iv:d,mode:CryptoJS.mode.CBC,padding:CryptoJS.pad.ZeroPadding});
	return e.toString()
}
```
解析倒是挺简单的  
```
curl "https://api.47ks.com/config/webmain.php" -H "Host: api.47ks.com" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0" -H "Accept: application/json, text/javascript, */*; q=0.01" -H "Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3" -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" -H "X-Requested-With: XMLHttpRequest" -H "Referer: https://api.47ks.com/webcloud/?v=http://v.youku.com/v_show/id_XMjY5MzM3Mjc2MA==.html" -H "DNT: 1" -H "Connection: keep-alive" --data "k=OZyXMXikznq6Fhs14sMzqSZfbGw652EhGqoz6%252FAYMx4tEGvf3iU2GW%252BwqeEtm1roSNb%252FPhxct4buTnj%252FVZj0gmGxDlq8Nx%252BcJmE5t77cfI6xfcqa%252BO07GpC6V%252FxY1trLL7ttNARg76J3B2%252BJdYWaOg%253D%253D&k2=RhdDVo4XLmD4iPPFbwL75Vetd3yV4N1DTFpDnFyu9laQpkY%252BHdniXUvkwLz87oSC&ep=89DED00FBE8D5C86BB8A319B5E843AD9E0C0D63E8CDDF84AC26B37CFBC71751505D0DAB05727FEF480C84B8E94FB71723EDB673425BFEB71CFD95B4F05FFAA7A7BE4A9B24460A0E8202CEFBC8D7E6153D080E9D53BC3D1874996E2B9D655EF025D3824A0CD617D206F55823FFA56421B&cip=121.41.129.156&cip_hex=7929819c&csign=D8B23A66F29411F51B2F224F13B003F49BDB329AD671B583&tm=4500322439&v=http%3A%2F%2Fv.youku.com%2Fv_show%2Fid_XMjY5MzM3Mjc2MA%3D%3D.html&pt=auto&nip=null&from=http%3A%2F%2Fwww.dilidili.wang%2Fwatch3%2F59308%2F&mode="


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   952    0   206  100   746    203    735  0:00:01  0:00:01 --:--:--   735
100   952    0   206  100   746    203    735  0:00:01  0:00:01 --:--:--   735
{"play":"m3u8","url":"https%3A%2F%2Fapi.47ks.com%2Fconfig%2Fgetinfo.m3u8%3Fpt%3Dyouku%26k%3D2adb2BdMo83GC1kc958dvac%252BkcH0J7HnzFHByq1KkUlt63WeqDjBjjHrDdZDYQ%26vid%3DXMjY5MzM3Mjc2MA%253D%253D","success":1}
```

**Comment by hustshego** [comment]
方便告诉一下怎么post参数k，k2怎么计算来的吗？

**Comment by airdge** [comment]
@hustshego 

curl播放页访问得到的数据
```
	 $.post("/config/webmain.php", {"k": encodeURIComponent(get("acc15oNLB82dTDvof5s7fVj05cyFW+V+KfZ8JiJpw20NEP
+FFFJjZ9iZ/DKzCIcieL5fnvMTjoJSPKRoYKHBboZh7L3X2t9T405mph9M0xQ")),"k2": encodeURIComponent(get(k2)),"ep"
: ep,"cip": "127.0.0.1","cip_hex": "7005ec37","csign": $("#get").val(),"tm": $("#tm").val(),"v": "http
://v.youku.com/v_show/id_XMjg2MjIwMzM3Mg==.html","pt": "auto","nip": nip,"from": "http://www.dilidili
.wang/watch3/59308/","mode": ""},
```
匹配
```
acc15oNLB82dTDvof5s7fVj05cyFW+V+KfZ8JiJpw20NEP
+FFFJjZ9iZ/DKzCIcieL5fnvMTjoJSPKRoYKHBboZh7L3X2t9T405mph9M0xQ
```
使用了AES/ECB加密
key为:md5(contentWindowHig)  
iv为:contentDocuments
```
var dfgsd='contentWindowHig';
var rgfgb='contentDocuments';
function get(a){
	var b=CryptoJS.MD5(dfgsd);
	var c=CryptoJS.enc.Utf8.parse(b);
	var d=CryptoJS.enc.Utf8.parse(rgfgb);
	var e=CryptoJS.AES.encrypt(a,c,{iv:d,mode:CryptoJS.mode.CBC,padding:CryptoJS.pad.ZeroPadding});
	return e.toString()
}
```
进行cbc加密得到k1值
`PXNSrW1wb1hHezuGyNi3ol79ah5+TOLTRAySG33YaEOXZhxQqHnyeG+wPThRuuTOc9NC/dpwIucatnbDVNaDLQhAxIr2BUxfczHRIrPuJ86q4RkzX+JEj6WxBRNRGTzWZCap0IkdZZB6KuDwEc2FtQ==`

k2值是getjson返回数据中的key
```
	$.get("https://kr.47ks.com/getjson/", {"k": encodeURIComponent(get("0535MI0R2KYt9R7uSP7feEIcsUsGuhs42sL
+K9gvyZ6QrlwQcNXn9G1uQqYx/yrFxR7FzUFdpwFPLyThRi7plDJ3wJRTpweFMqNHNskcPkhSIWSI5I9kOEWOuG0iXb/4nq/XbOghbnlVDS
/NwWlj9VECcrxTQk15mp+V3DFQI5x0SOANjZThQb7+Eds"))},
    function(kdata){
		if(kdata['code'] == 200){
			k2 = kdata['key'];
			ep = kdata['ep'];
		}
```
同样 匹配字符串使用cbc加密  
获取key与ep
```
Array
(
    [code] => 200
    [47k2] => 20170419_r2
    [time] => k2_1500506070
    [purl] => aHR0cDovL3YueW91a3UuY29tL3Zfc2hvdy9pZF9YTWpnNE9UUXhNRGt5T0E9PS5odG1s
    [key] => 3f47tEeF9wqlv3T%2B7DDPdep4VmgovuM8yk6w6rH1RqpSrfYYoIYLwYeS
    [ep] => FB8754D0000D6B409D463DA092B1B5961F9725EDECDD034147BB1B46223865E5B8F15484C40B18F6107853A96598D5AD20C4C4B44C4B909CC4D5C86F3D551C885B326305A76AC8E828BB2E9B6FF9F364A2062A7BDA6A4A86756F22EC1EF344AD6B3C801714CC9B5D253A24F033453160DC284D7A98299131
)
```

**Comment by hustshego** [comment]
666,非常感谢~
