### ISSUE TITLE
优酷会员下载报500

### ISSUE THREAD

**Issue by sweat89** [soimort/you-get#2144]
you-get (develop) ✗ you-get --debug http://v.youku.com/v_show/id_XMjg3MDYzOTcxNg\=\=.html\?spm\=a2h0j.8191423.item_XMjg3MDYzOTcxNg\=\=.A
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjg3MDYzOTcxNg==&ccode=0401&client_ip=192.168.1.1&utid=GSntERht%2BmQCAXFYYzzZ9d1z&client_ts=1499872025
you-get: flvhd is a preview
you-get: mp4 is a preview
you-get: hd3 is a preview
you-get: hd2 is a preview
site:                优酷 (Youku)
title:               大军师司马懿之军师联盟 39
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          588.7 MiB (617333649 bytes)
    # download-with: you-get --format=hd3 [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XMjg3MDYzOTcxNg==

Downloading 大军师司马懿之军师联盟 39.flv ...
 0.8% (  5.0/588.7MB) ├─────────────────────────────────────────┤[1/2]  288 kB/syou-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjg3MDYzOTcxNg==.html?spm=a2h0j.8191423.item_XMjg3MDYzOTcxNg==.A']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1180, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractor.py", line 58, in download_by_url
    self.download(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractor.py", line 220, in download
    av=stream_id in self.dash_streams)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 834, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 578, in url_save
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by rosynirvana** [comment]
hd3的CDN有时候会出问题
换hd2即可，或者等一段时间，有时候会恢复

**Comment by sweat89** [comment]
嗯嗯。确实有点不稳定。
不过下载的还是4分钟的视频，也就是非会员能看到的。
这个能有什么办法突破下么  ^_^

**Comment by rosynirvana** [comment]
非vip不能看1080p，试看片段也不行
有时候等一段时间会好

**Comment by sweat89** [comment]
试看片段是可以的。
你说的等一段时间会好，那是因为会员抢先看的时间只有1天吧。1天后，普通会员也能看了^_^

**Comment by rosynirvana** [comment]
我说的不行是ui层面上的不行，如果说api层面上是可以的

hd3的CDN有问题，和是否限会员没关系
我把之前打印m3u8_url那个找回来了，可以试试
不过试看的几分钟基本都是op

**Comment by lamlam123tld3** [comment]
基本上要保留 k.youku.com 的連接
如果CDN傳回的是404
就換個IP (用PROXY什麼的) 再請求

**Comment by rosynirvana** [comment]
但是yxon已经没了

**Comment by airdge** [comment]
将ip换成下面的看下
```
http://vali.cp31.ott.cibntv.net
http://vali.youku.com
```

**Comment by rosynirvana** [comment]
inactive for about one month
