### ISSUE TITLE
Termux上运行you-get下载优酷标清以上视频错误

### ISSUE THREAD

**Issue by jyuan15** [soimort/you-get#2149]
可以下载标清视频（flvhd），其他分辨率下载会出错。

$ you-get -Fmp4 http://v.youku.com/v_show/id_XMjg4MTU0MjY4OA==.html
site:                优酷 (Youku)
title:               大军师司马懿之军师联盟 40
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          184.19999999999999 MiB (193105279 bytes)
    # download-with: you-get --format=mp4 [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XMjg4MTU0MjY4OA==

Downloading 大军师司马懿之军师联盟 40.mp4 ...
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

$ you-get -Fmp4 --debug http://v.youku.com/v_show/id_XMjg4MTU0MjY4OA==.html
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjg4MTU0MjY4OA==&ccode=0401&client_ip=192.168.1.1&utid=JjrvEUhySngCAXWw/KG66ciR&client_ts=1500007462
site:                优酷 (Youku)
title:               大军师司马懿之军师联盟 40
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          184.19999999999999 MiB (193105279 bytes)
    # download-with: you-get --format=mp4 [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XMjg4MTU0MjY4OA==

Downloading 大军师司马懿之军师联盟 40.mp4 ...
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjg4MTU0MjY4OA==.html']
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 1467, in main
   script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 1373, in script_main
    download_main(download, download_playlist, args, playlist, stream_id=stream_id, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 1180, in download_main
    download(url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/extractor.py", line 58, in download_by_url
    self.download(**kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/extractor.py", line 220, in download
    av=stream_id in self.dash_streams)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 827, in download_urls
    bar.update()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/you_get/common.py", line 696, in update
    bar = self.bar.format(percent, round(self.received / 1048576, 1), bar, self.current_piece, self.total_pieces, self.speed)
ValueError: Sign not allowed in string format specifier
-------------------------------------------------------

**Comment by rosynirvana** [comment]
dup #2139

**Comment by amtlib-dot-dll** [comment]
Seems OK if do like this
```sh
pip install -U --no-binary :all: you-get
PYTHONDONTWRITEBYTECODE=1 you-get
```
And make your screen wider by rotate it.

**Comment by sixiong** [comment]
我遇到了相同的问题，但是在正常的命令行下没什么问题，在C++代码里面调用时会出现这种问题
```cpp
    string strCom = "cd /home/hadop/videoDownloader && source bin/activate && you-get http://v.youku.com/v_show/id_XMjk2ODQzMTA4OA==.html";
    int status = system(strCom.c_str());
```
