### ISSUE TITLE
bilibili突然全部无法下载

### ISSUE THREAD

**Issue by OHLIA** [soimort/you-get#2151]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]
------------------------------------------
------------------------------------------
PS H:\> you-get.exe --debug http://www.bilibili.com/video/av12170000/
[DEBUG] url_locations: http://www.bilibili.com/video/av12170000/
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av12170000/']
Traceback (most recent call last):
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\http\client.py", line 964, in send
    self.connect()
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\socket.py", line 722, in create_connection
    raise err
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\NEWLIA\AppData\Local\Programs\Python\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1180, in download_main
    download(url, **kwargs)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\extractor.py", line 45, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\bilibili.py", line 106, in prepare
    self.url = url_locations([self.url])[0]
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 500, in url_locations
    response = urlopen_with_retry(request.Request(url))
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\users\newlia\appdata\local\programs\python\python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>

**Comment by rosynirvana** [comment]
无法重复

```
$ you-get -d 'http://www.bilibili.com/video/av12170000/'
[DEBUG] url_locations: http://www.bilibili.com/video/av12170000/
[DEBUG] get_content: http://www.bilibili.com/video/av12170000/
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=20064285&player=1&quality=3&ts=1500033992&sign=9d1e003f2f29682ec80e7e72565e7f41
[DEBUG] get_content: http://comment.bilibili.com/20064285.xml
site:                Bilibili
title:               【Gero】4th Album「EGOIST 」【全曲试听】
stream:
    - format:        flv
      container:     flv
      size:          73.5 MiB (77019150 bytes)
    # download-with: you-get --format=flv [URL]

Downloading 【Gero】4th Album「EGOIST 」【全曲试听】.flv ...
42.5% ( 31.2/ 73.5MB) ├████████████████████──────────────────────────┤[1/2]  276 kB/s
```

先考虑你的网络情况是不是够好

**Comment by OHLIA** [comment]
可以正常上网，就是无法用you-get下视频，我也很纳闷，昨天还在用着

**Comment by rosynirvana** [comment]
这种不是很容易debug

例如```you-get --debug URL```是使用系统代理的，浏览器是不是也在用同样的代理

**Comment by OHLIA** [comment]
刚在IE代关了理服务器就可以下载了。。。
这是个假issue...

**Comment by rosynirvana** [comment]
你可以试试 ```--no-proxy```
