### ISSUE TITLE
weibo.com download fail

### ISSUE THREAD

**Issue by ioilala** [soimort/you-get#2156]
$ you-get --debug -O xx -f http://weibo.com/tv/v/FaYsuaUB2?fid=1034:e69971dd76a28c0c0093213bc4577916
[DEBUG] get_content: http://video.weibo.com/show?fid=1034:e69971dd76a28c0c0093213bc4577916&type=mp4
[DEBUG] url_info: http://us.sinaimg.cn/00219i0Jjx07cp3xc1eo010f01023san0k02.mp4?label=mp4_hd&template=template_6&Expires=1500279953&ssig=6a%2BzuiYPX1&KID=unistore,video
Site:       miaopai
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://weibo.com/tv/v/FaYsuaUB2?fid=1034:e69971dd76a28c0c0093213bc4577916']
Traceback (most recent call last):
  File "c:\users\hzwangsheng2\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\hzwangsheng2\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\hzwangsheng2\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\hzwangsheng2\appdata\local\programs\python\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\hzwangsheng2\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\hzwangsheng2\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\hzwangsheng2\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1180, in download_main
    download(url, **kwargs)
  File "c:\users\hzwangsheng2\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "c:\users\hzwangsheng2\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\miaopai.py", line 31, in miaopai_download
    miaopai_download_by_fid(fid, output_dir, merge, info_only)
  File "c:\users\hzwangsheng2\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\miaopai.py", line 23, in miaopai_download_by_fid
    print_info(site_info, title, type_, size)
  File "c:\users\hzwangsheng2\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1099, in print_info
    maybe_print("Title:     ", unescape_html(tr(title)))
  File "c:\users\hzwangsheng2\appdata\local\programs\python\python35-32\lib\html\__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable

**Comment by rosynirvana** [comment]
```
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>盛夏美人妆 💆
和我一起做出门前的大改造吧！
< 1 >
#大多呀Daddoa##这一刻的时光##扑通扑通少女心##彩虹唇#</title>
```

新浪真厉害

**Comment by rosynirvana** [comment]
```
./you-get -di http://weibo.com/tv/v/FaYsuaUB2\?fid\=1034:e69971dd76a28c0c0093213bc4577916
[DEBUG] get_content: http://video.weibo.com/show?fid=1034:e69971dd76a28c0c0093213bc4577916&type=mp4
[DEBUG] url_info: http://us.sinaimg.cn/00219i0Jjx07cp3xc1eo010f01023san0k02.mp4?label=mp4_hd&template=template_6&Expires=1500283117&ssig=RcORyzs5od&KID=unistore,video
Site:       miaopai
Title:      盛夏美人妆 💆_和我一起做出门前的大改造吧！_< 1 >_#大多呀Daddoa##这一刻的时光##扑通扑通少女心##彩虹唇#
Type:       MPEG-4 video (video/mp4)
Size:       28.97 MiB (30375931 Bytes)
```

fixed via https://github.com/soimort/you-get/commit/5bbb536de46db2ae004a390aa5352a1864459e6d
