### ISSUE TITLE
爱奇艺不能下载

### ISSUE THREAD

**Issue by luhy118** [soimort/you-get#2161]
``D:\workspace>you-get http://www.iqiyi.com/v_19rr7jaku4.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

D:\workspace>you-get http://www.iqiyi.com/v_19rr7jaku4.html --debug
[DEBUG] get_response: http://www.iqiyi.com/v_19rr7jaku4.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/727450000/8e15511bf2705d3d5b6cdc65c7e9bd59/?t=1500370199383&sc=4eefbf123bc2c3fa391671184d965dbf&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rr7jaku4.html']
Traceback (most recent call last):
  File "d:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1180, in download_main
    download(url, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\extractor.py", line 45, in download_by_url
    self.prepare(**kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\extractors\iqiyi.py", line 140, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video

**Comment by luhy118** [comment]
``D:\workspace>you-get http://www.iqiyi.com/v_19rr7jaku4.html --debug
[DEBUG] get_response: http://www.iqiyi.com/v_19rr7jaku4.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/727450000/8e15511bf2705d3d5b6cdc65c7e9bd59/?t=1500370199383&sc=4eefbf123bc2c3fa391671184d965dbf&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rr7jaku4.html']
Traceback (most recent call last):
  File "d:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1180, in download_main
    download(url, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\extractor.py", line 45, in download_by_url
    self.prepare(**kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\extractors\iqiyi.py", line 140, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video

**Comment by rosynirvana** [comment]
dup #1861
