### ISSUE TITLE
Bilibili stoped functioning/Bilbili似乎挂了

### ISSUE THREAD

**Issue by ztytian** [soimort/you-get#2165]
Here is the verbose output.

you-get http://bangumi.bilibili.com/anime/5989/play#103878 --debug
[DEBUG] url_locations: http://bangumi.bilibili.com/anime/5989/play#103878
[DEBUG] get_content: http://bangumi.bilibili.com/anime/5989/play#103878
[DEBUG] get_content: http://bangumi.bilibili.com/jsonp/seasoninfo/5989.ver?callback=seasonListCallback&jsonp=jsonp&_=1500434603801
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/5989/play#103878']
Traceback (most recent call last):
  File "/Users/Peter/Downloads/you-get-develop/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/Users/Peter/Downloads/you-get-develop/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/Peter/Downloads/you-get-develop/src/you_get/common.py", line 1468, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/Peter/Downloads/you-get-develop/src/you_get/common.py", line 1379, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/Peter/Downloads/you-get-develop/src/you_get/common.py", line 1181, in download_main
    download(url, **kwargs)
  File "/Users/Peter/Downloads/you-get-develop/src/you_get/common.py", line 1461, in any_download
    m.download(url, **kwargs)
  File "/Users/Peter/Downloads/you-get-develop/src/you_get/extractor.py", line 45, in download_by_url
    self.prepare(**kwargs)
  File "/Users/Peter/Downloads/you-get-develop/src/you_get/extractors/bilibili.py", line 127, in prepare
    self.bangumi_entry(**kwargs)
  File "/Users/Peter/Downloads/you-get-develop/src/you_get/extractors/bilibili.py", line 191, in bangumi_entry
    ep_ids = collect_bangumi_epids(bangumi_data)
  File "/Users/Peter/Downloads/you-get-develop/src/you_get/extractors/bilibili.py", line 248, in collect_bangumi_epids
    eps = sorted(eps, key=lambda item: int(item['index']))
  File "/Users/Peter/Downloads/you-get-develop/src/you_get/extractors/bilibili.py", line 248, in <lambda>
    eps = sorted(eps, key=lambda item: int(item['index']))
ValueError: invalid literal for int() with base 10: '6.5'

**Comment by rosynirvana** [comment]
it has been fixed in develop branch with commit https://github.com/soimort/you-get/commit/94121ea76d182e17150db1fca13eb2513c4ef04a

**Comment by ztytian** [comment]
Indeed
