### ISSUE TITLE
发现大量A站视频无法下载

### ISSUE THREAD

**Issue by luhy118** [soimort/you-get#2166]
``D:\workspace\clip-spider>you-get http://www.acfun.cn/v/ac3567688 --debug
[DEBUG] get_content: http://www.acfun.cn/v/ac3567688
[DEBUG] get_content: http://www.acfun.tv/video/getVideo.aspx?id=4993287
[DEBUG] get_content: http://aplay-vod.cn-beijing.aliyuncs.com/acfun/web?vid=58d358eb0cf22d42c83861aa&ct=85&ev=3&sign=1_1500518398_fe1d2178da25fd24d771f6c9fbf57923
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac3567688']
Traceback (most recent call last):
  File "d:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1180, in download_main
    download(url, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\extractors\acfun.py", line 122, in acfun_download
    **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\extractors\acfun.py", line 73, in acfun_download_by_vid
    yk_streams = youku_acfun_proxy(info['sourceId'], info['encode'])
  File "d:\program files\python36\lib\site-packages\you_get\extractors\acfun.py", line 23, in youku_acfun_proxy
    json_data = json.loads(get_content(url))['data']
KeyError: 'data'

http://www.acfun.cn/v/ac3528704
http://www.acfun.cn/v/ac3567688
http://www.acfun.cn/v/ac3725639
http://www.acfun.cn/v/ac3725639

**Comment by rosynirvana** [comment]
```
./you-get -i http://www.acfun.cn/v/ac3528704 http://www.acfun.cn/v/ac3567688 http://www.acfun.cn/v/ac3725639
Site:       AcFun.tv
Title:      【胖小妞穿搭】胖美眉怎么把牛仔穿得潮出街！ - 凹凸曼APP
Type:       MPEG-4 video (video/mp4)
Size:       30.33 MiB (31799700 Bytes)

Site:       AcFun.tv
Title:      【胖小妞穿搭】用一件风衣打造不一样的轻熟风 - 凹凸曼APP
Type:       MPEG-4 video (video/mp4)
Size:       42.94 MiB (45021803 Bytes)

Site:       AcFun.tv
Title:      赌一包辣条 今年夏天这三条裙子最显瘦！ - 美搭时尚
Type:       MPEG-4 video (video/mp4)
Size:       36.13 MiB (37882969 Bytes)

./you-get http://www.acfun.cn/v/ac3725639
Site:       AcFun.tv
Title:      赌一包辣条 今年夏天这三条裙子最显瘦！ - 美搭时尚
Type:       MPEG-4 video (video/mp4)
Size:       36.13 MiB (37882969 Bytes)

Downloading 赌一包辣条 今年夏天这三条裙子最显瘦！ - 美搭时尚.mp4 ...
 100% ( 36.1/ 36.1MB) ├█████████████████████████████████████████┤[1/1]  118 kB/s

Downloading 赌一包辣条 今年夏天这三条裙子最显瘦！ - 美搭时尚.cmt.json ...
```

fixed with https://github.com/soimort/you-get/commit/9b32634088a40576d18359480b401069cba03cde
