### ISSUE TITLE
youtube下载失败：KeyError: 'dashmpd'

### ISSUE THREAD

**Issue by Yufeikang** [soimort/you-get#2167]
➜  download you-get --debug https://www.youtube.com/watch\?v\=VaoAU6PvuTg 
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=VaoAU6PvuTg
[DEBUG] get_content: https://www.youtube.com/watch?v=VaoAU6PvuTg
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-vflMaap-E/en_US/base.js
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=VaoAU6PvuTg']
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/youtube.py", line 258, in prepare
    dashmpd = ytplayer_config['args']['dashmpd']
KeyError: 'dashmpd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1180, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractor.py", line 45, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/youtube.py", line 375, in prepare
    'src': [dash_url, dash_webm_a_url],
UnboundLocalError: local variable 'dash_webm_a_url' referenced before assignment

**Comment by soimort** [comment]
@soimort-bot Test: https://www.youtube.com/watch?v=VaoAU6PvuTg
