### ISSUE TITLE
56.com 视频下载出错

### ISSUE THREAD

**Issue by luhy118** [soimort/you-get#2169]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
D:\workspace\clip-spider>you-get http://www.56.com/u72/v_NzM5MzU0NjE.html --debug
[DEBUG] get_content: http://www.56.com/u72/v_NzM5MzU0NjE.html
[DEBUG] get_response: http://vxml.56.com/json/NzM5MzU0NjE/?src=site
Site:       56.com
Title:      美国《国家地理》摄影大赛中国赛区作品2 09 24 16 46_wmv
Type:       MPEG-4 video (video/mp4)
Size:       6.4 MiB (6706051 Bytes)

Downloading 美国《国家地理》摄影大赛中国赛区作品2 09 24 16 46_wmv.mp4 ...
15.6% (  1.0/  6.4MB) ├███████──────────────────────────────────┤[1/1]    3 MB/syou-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://www.56.com/u72/v_NzM5MzU0NjE.html']
Traceback (most recent call last):
  File "d:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1180, in download_main
    download(url, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\extractors\w56.py", line 38, in w56_download
    w56_download_by_id(id, output_dir = output_dir, merge = merge, info_only = info_only)
  File "d:\program files\python36\lib\site-packages\you_get\extractors\w56.py", line 27, in w56_download_by_id
    download_urls([url], title, ext, size, output_dir = output_dir, merge = merge)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 822, in download_urls
    url_save(url, output_filepath, bar, refer = refer, faker = faker, headers = headers, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 555, in url_save
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "d:\program files\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "d:\program files\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "d:\program files\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\program files\python36\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "d:\program files\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "d:\program files\python36\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\program files\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "d:\program files\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\program files\python36\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "d:\program files\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "d:\program files\python36\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\program files\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "d:\program files\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\program files\python36\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "d:\program files\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "d:\program files\python36\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\program files\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "d:\program files\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\program files\python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "d:\program files\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "d:\program files\python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 416: Requested Range Not Satisfiable
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
我这里浏览器无法加载这个视频，和you-get拿到地址测试结果一致
```
curl http://f1.r.56.com/f1.c92.56.com/flvdownload/14/27/134888424274hd.flv\?v\=1\&t\=-CXpaBy1UdDiAjWy81ZTLA\&r\=69479\&e\=1500629730\&tt\=189\&sz\=6706051\&vid\=73935461\&prod\=56 -L > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   154    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   154    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0
curl: (7) Failed to connect to fcs92.56.com port 80: Operation timed out
```

所以感觉单纯是56的CDN比较烂……

**Comment by luhy118** [comment]
总量是浏览器可以正常播放，理应下载应该也可以没总量

**Comment by rosynirvana** [comment]
```
./you-get -d -o /tmp http://www.56.com/u72/v_NzM5MzU0NjE.html
[DEBUG] get_content: http://www.56.com/u72/v_NzM5MzU0NjE.html
[DEBUG] get_response: http://vxml.56.com/json/NzM5MzU0NjE/?src=site
Site:       56.com
Title:      美国《国家地理》摄影大赛中国赛区作品2 09 24 16 46_wmv
Type:       MPEG-4 video (video/mp4)
Size:       6.4 MiB (6706051 Bytes)

Downloading 美国《国家地理》摄影大赛中国赛区作品2 09 24 16 46_wmv.mp4 ...
 100% (  6.4/  6.4MB) ├█████████████████████████████████████████┤[1/1]  263 kB/s
```

就是CDN的问题
