### ISSUE TITLE
[bilibili][BUG]下载番剧遇到有小数点的index会出错

### ISSUE THREAD

**Issue by zsyes** [soimort/you-get#2178]
[bilibili][BUG]下载番剧遇到有小数点的index会出错

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

错误日志:

```
$ you-get --debug https://www.bilibili.com/video/av9650775
[DEBUG] url_locations: http://www.bilibili.com/video/av9650775
[DEBUG] get_content: http://bangumi.bilibili.com/anime/5989/play#103870
[DEBUG] get_content: http://bangumi.bilibili.com/jsonp/seasoninfo/5989.ver?callback=seasonListCallback&jsonp=jsonp&_=1500680005241
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['https://www.bilibili.com/video/av9650775']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1180, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractor.py", line 45, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 127, in prepare
    self.bangumi_entry(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 191, in bangumi_entry
    ep_ids = collect_bangumi_epids(bangumi_data)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 248, in collect_bangumi_epids
    eps = sorted(eps, key=lambda item: int(item['index']))
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 248, in <lambda>
    eps = sorted(eps, key=lambda item: int(item['index']))
ValueError: invalid literal for int() with base 10: '6.5'
```

:icecream::icecream::icecream:

**Comment by rosynirvana** [comment]
#2165
