### ISSUE TITLE
下载大文件时常出现中断

### ISSUE THREAD

**Issue by syazyz** [soimort/you-get#2180]
汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [checked] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [checked] 您的`you-get`为最新版.
- [checked] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [checked] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [checked] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

H:\Downloads\Temporary>you-get "http://v.youku.com/v_show/id_XMjkwODc1MDg2NA==.html?spm=a2hzp.8253869.0.0" --debug
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjkwODc1MDg2NA==&ccode=0401&client_ip=192.168.1.1&utid=5TD6EU0jGm0CAXT8qRmLxIj2&client_ts=1500725991
site:                优酷 (Youku)
title:               20170720深夜hong9 教屌录 你们见过哭着的龙骑吗(鼎鼎解说)
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          1993.0 MiB (2089790821 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjkwODc1MDg2NA%3D%3D&type=hd2&ups_client_netip=116.252.169.25&ups_ts=1500725989&utid=5TD6EU0jGm0CAXT8qRmLxIj2&ccode=0401&psid=718ad927a9512edeca74c0877cf3ff36&ckey=&duration=12296&expire=18000&ups_key=67399361758413f6a7d393a985050b91
    # download-with: you-get --format=hd2 [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 20170720深夜hong9 教屌录 你们见过哭着的龙骑吗(鼎鼎解说).flv ...
 6.2% ( 124.2/1993.0MB) ├███──────────────────────────────────┤[ 4/63]   23 MB/syou-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjkwODc1MDg2NA==.html?spm=a2hzp.8253869.0.0']
Traceback (most recent call last):
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 722, in create_connection
    raise err
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.775', 'console_scripts', 'you-get')()
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\extractor.py", line 224, in download
    av=stream_id in self.dash_streams)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 835, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 509, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 418, in url_size
    response = urlopen_with_retry(url)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\zzzzz\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试 失败。>

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

已经将you-get更新为develop branch。小视频（一般少于300M）就没有问题，此问题仅出现在下载超过500M的优酷视频的情况中。

**Comment by rosynirvana** [comment]
youku自己CDN扛不住，这不算you-get的问题
