### ISSUE TITLE
Download Youku Channel

### ISSUE THREAD

**Issue by dkl3** [soimort/you-get#2182]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x ] Your `you-get` is up-to-date.
- [x ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

'''
~⟫ you-get http://i.youku.com/i/UMjczMjEwNzY4/videos --debug
[DEBUG] get_content: http://i.youku.com/i/UMjczMjEwNzY4/videos
site:                优酷 (Youku)
playlist:            酷派天空官方频道的自频道-优酷视频
videos:
[DEBUG] get_content: http://v.youku.com/wechatShare
site:                优酷 (Youku)
playlist:            分享到微信
videos:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.775-py3.5.egg/you_get/extractors/youku.py", line 156, in download_playlist_by_url
    self.__class__().download_by_url(video, index=index, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.775-py3.5.egg/you_get/extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.775-py3.5.egg/you_get/extractors/youku.py", line 190, in prepare
    exit(0)
  File "/usr/lib/python3.5/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0

```
Self-explanatory--I get this error when i try to download a Youku channel.

**Comment by rosynirvana** [comment]
youku playlist is not supported
you can try with a specified video page

**Comment by soimort** [comment]
There seems to be a PR #1697, but it's stale and needs some extra work to merge.
