### ISSUE TITLE
爱奇艺视频不能获取信息不能下载

### ISSUE THREAD

**Issue by Asuly** [soimort/you-get#2196]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[C:\Users\andy_>you-get --debug -i http://www.iqiyi.com/v_19rr7n235s.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rr7n235s.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/737982700
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rr7n235s.html']
Traceback (most recent call last):
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\socket.py", line 722, in create_connection
    raise err
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\andy_\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\iqiyi.py", line 140, in prepare
    mixin = get_content(info_u)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 353, in get_content
    response = urlopen_with_retry(req)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\users\andy_\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试 失败。>]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [ 不能获取信息，不能下载 ykdl也不可以。  明明前天还能用的 ]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```
you-get --debug -i http://www.iqiyi.com/v_19rr7n235s.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rr7n235s.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/737982700
[DEBUG] get_content: http://www.iqiyi.com/v_19rr7n235s.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/737982700/a85a58703e10535c44a6bf0f7a1b6daf/?t=1501037604393&sc=9f87e08971ce07f82d0835555be32f34&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               我们的少年时代DVD版第29集
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
      m3u8_url:      http://cache.m.iqiyi.com/mus/208495401/9f5714ff08897018779e3aa19bfacc6f/afbe8fd3d73448c9//20170725/41/7d/c4228a438aa5f7448fa2904ad8b4ff0e.m3u8?qd_originate=tmts_py&tvid=737982700&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1501037603951&qd_p=b67200a2&qd_asc=72ade831adda813c6377ffc50911a29b&qypid=737982700_04022000001000000000_4&qd_k=9f87e08971ce07f82d0835555be32f34&vf=19e03a83412cace51b8ebc6647e88364&np_tag=nginx_part_tag
```

出现这个基本上就是你网络问题了
```
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
```
