### ISSUE TITLE
Youtube download failed, using XX-Net as global PAC proxy.

### ISSUE THREAD

**Issue by deargear** [soimort/you-get#2197]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
PS C:\Users\Dream4span\Downloads\Video> you-get -di 'https://www.youtube.com/watch?v=450p7goxZ
qg'
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=450p7goxZqg
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=450p7goxZqg']
Traceback (most recent call last):
  File "c:\python\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\python\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\python\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\python\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\python\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\python\lib\http\client.py", line 964, in send
    self.connect()
  File "c:\python\lib\http\client.py", line 1392, in connect
    super().connect()
  File "c:\python\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\python\lib\socket.py", line 722, in create_connection
    raise err
  File "c:\python\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝
试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=me
rge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\python\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\python\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\python\lib\site-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\python\lib\site-packages\you_get\extractors\youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={
}'.format(self.vid)))
  File "c:\python\lib\site-packages\you_get\common.py", line 353, in get_content
    response = urlopen_with_retry(req)
  File "c:\python\lib\site-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\python\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\python\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\python\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\python\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\python\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连
接的主机没有反应，连接尝试失败。>
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> :octocat: As a matter of fact, I just began to use it since several days ago. I successfully downloaded 2 Youtube videos and its audio. Since the 3rd time I tried to use it, I got errors. I instantly upgraded it to the newest version 0.4.803 and retried. But it still doesn't work. I've read quite a lot issues about youtube download failure, but I'm not sure if my network should answer for it. Cuz I can still use IDM to download the Youtube video.

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
我才不粘第二次๑乛◡乛๑
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 刚刚用的时候，看着下载时那shuashua的进度条，真是觉得相见恨晚(๑￫ܫ￩)
> 然而才爽了2次就GG了，好不甘心啊 (╯‵□′)╯︵ ┴─┴ 
> 有同样用XX-Net配合Google AppID跳墙的小伙伴吗？
> 难道XX-Net也走到头了，又要换一架梯子了吗(..•˘_˘•..)
> 🈳 🈚️

**Comment by rosynirvana** [comment]
这不是you-get本身的问题

**Comment by deargear** [comment]
@rosynirvana 但是我可以很正常地看Youtube啊，还可以用IDM下载视频。IDM不是根据网页对视频内容的请求解析出下载地址的吗，既然IDM能解析能下载，那说明不是因为代理用的IP段被Youtube屏蔽这种原因，而除了这个原因，我不知道还有什么原因能导致IDM能下载而you-get不能。you-get的解析机制是什么呢？应该原理差不多吧 😕

**Comment by rosynirvana** [comment]
这是你代理如何部署的问题
对于xx-net这种可靠性堪忧的东西，恐怕只能自己debug了

**Comment by Justsoos** [comment]
你先确定，你的 command 环境命令行是否能全局翻墙。 
换个角度说，你的命令行少了代理设置。

**Comment by deargear** [comment]
@Justsoos 可以。我上面说了啊，之前在command里用you-get下载过2个视频，没问题。代理设置一直没改动，版本更新了就没法用了。

**Comment by Justsoos** [comment]
你发的反馈里明确没有代理开关设置，返回错误也是被墙的连接典型症状。
与you-get 无关
