### ISSUE TITLE
无法下载bilibili的番剧

### ISSUE THREAD

**Issue by shikkoku** [soimort/you-get#2202]
无法下载 https://www.bilibili.com/video/av12605814/

$ you-get -c ~/cookies.txt --no-caption -i "https://www.bilibili.com/video/av12605814/" -o /d/Videos/ --debug
[DEBUG] url_locations: http://www.bilibili.com/video/av12605814/
[DEBUG] get_content: http://bangumi.bilibili.com/anime/5978/play#113060
[DEBUG] get_content: http://bangumi.bilibili.com/jsonp/seasoninfo/5978.ver?callback=seasonListCallback&jsonp=jsonp&_=1501241753304
[DEBUG] post_content: http://bangumi.bilibili.com/web_api/get_source
 post_data: {'episode_id': '113060'}
[DEBUG] get_content: http://bangumi.bilibili.com/web_api/episode/113060.json
[DEBUG] get_content: http://bangumi.bilibili.com/player/web_api/playurl?cid=20737497&module=bangumi&player=1&quality=4&ts=1501241753&sign=0de8a026e86b17f6ebdec48e46df3952
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://www.bilibili.com/video/av12605814/']
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "c:\program files\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractors\bilibili.py", line 127, in prepare
    self.bangumi_entry(**kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractors\bilibili.py", line 211, in bangumi_entry
    self.download_by_vid(cid, bangumi=True, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractors\bilibili.py", line 102, in download_by_vid
    self.parse_bili_xml(api_xml)
  File "c:\program files\python36\lib\site-packages\you_get\extractors\bilibili.py", line 77, in parse_bili_xml
    stream_type, container = self.bilibili_stream_type(urls_list)
  File "c:\program files\python36\lib\site-packages\you_get\extractors\bilibili.py", line 42, in bilibili_stream_type
    url = urls[0]
IndexError: list index out of range

不过中午的时候还能正常下载。

**Comment by rosynirvana** [comment]
![2017-07-28 7 43 11](https://user-images.githubusercontent.com/1081266/28715921-0a14b1d8-73cd-11e7-915e-f029ffc1a556.png)

视频挂了

**Comment by shikkoku** [comment]
233333全部番剧都肥肠抱歉了。

**Comment by rosynirvana** [comment]
似乎好了
