### ISSUE TITLE
Failed to download music from SoundCloud (ver 0.4.775)

### ISSUE THREAD

**Issue by CyanideCentral** [soimort/you-get#2204]
Command:
you-get --debug https://soundcloud.com/fractalfantasy/dark-matter-jlin-zora-jones

Output with debug option:
[DEBUG] get_response: https://api.soundcloud.com/resolve.json?url=http://soundcloud.com/fractalfantasy/dark-matter-jlin-zora-jones&client_id=02gUJC0hH2ct1EGOcYXQIzRFU91c72Ea
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['https://soundcloud.com/fractalfantasy/dark-matter-jlin-zora-jones']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1467, in main
  File "src\you_get\common.py", line 1378, in script_main
  File "src\you_get\common.py", line 1180, in download_main
  File "src\you_get\common.py", line 1460, in any_download
  File "src\you_get\extractors\soundcloud.py", line 21, in soundcloud_download
  File "src\you_get\common.py", line 306, in get_html
  File "src\you_get\common.py", line 294, in get_response
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 471, in open
  File "urllib\request.py", line 581, in http_response
  File "urllib\request.py", line 509, in error
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 589, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized
you-get returned -1

Running environment: you-get 0.4.775, installed via chocolatey on Windows 10. Download from YouTube  by you-get still working well.

**Comment by rosynirvana** [comment]
It's fixed with commit https://github.com/soimort/you-get/commit/7eb7ead38020bb17683dc3e7c5e609b150771dad

```
./you-get -di https://soundcloud.com/fractalfantasy/dark-matter-jlin-zora-jones
[DEBUG] get_content: https://api.soundcloud.com/resolve.json?url=http://soundcloud.com/fractalfantasy/dark-matter-jlin-zora-jones&client_id=JlZIsxg2hY5WnBgtn3jfS0UYCl0K8DOg
[DEBUG] url_info: https://api.soundcloud.com/tracks/335083208/download?client_id=JlZIsxg2hY5WnBgtn3jfS0UYCl0K8DOg
[DEBUG] get_content: https://api.soundcloud.com/i1/tracks/335083208/streams?client_id=JlZIsxg2hY5WnBgtn3jfS0UYCl0K8DOg
[DEBUG] url_info: https://cf-media.sndcdn.com/lSzGgGZJG8pe.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vbFN6R2dHWkpHOHBlLjEyOC5tcDMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1MDEzMzAyNzd9fX1dfQ__&Signature=yZwo6n2dQvAL9Ne40Xhpi7-3EE4Ox960EqV4JdN4Qz0X0gGES7XBzHcJjalFVv8De2gCHTS39pqi6ROeGfoh2ByLnoL~ONWwflPzMOxwflFpnly7eiSZ4hXiIg5Rat4tBtpd0mIfYLbZhGuNJNL-PqOB9vExSOsFCEJzx1JSNNm8DgsG25Jg1fxJl976QS1P2bxC70sLyK1ub36QQ6O-hu~HcH9amJYWckpkh1UH3Gjnqb90XV6tiFRsWSLy-1UIL1iFr5zWcnt~BiJCZEW~0roM3Ur3d0xV3uiO39HpAVolRS1SrD2ZoffDwlXP5kY7ikdgyTYogHItlVAzKUBO3w__&Key-Pair-Id=APKAJAGZ7VMH2PFPW6UQ
Site:       SoundCloud.com
Title:      Dark Matter - Jlin & Zora Jones
Type:       MP3 (audio/mpeg)
Size:       3.39 MiB (3553488 Bytes)
```

You can install you-get with pip3 or wait for release in chocolatey

**Comment by denobisipsis** [comment]
clientid is taken from https://a-v2.sndcdn.com/assets/app-xxxxx-xxxxxxx.js which you can find in html
