### ISSUE TITLE
Sina Weibo Video using new domain causes you-get failed

### ISSUE THREAD

**Issue by R-L-T-Y** [soimort/you-get#2209]
- [✓ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ✓] Your `you-get` is up-to-date.
- [✓ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [✓ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [✓ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://weibo.com/tv/v/FeOntp54t']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/common.py", line 1181, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/extractors/miaopai.py", line 39, in miaopai_download
    raise Exception('Unknown pattern')
Exception: Unknown pattern]
```

New domain is like "http://weibo.com/tv/v/FeOntp54t"

**Comment by rosynirvana** [comment]
```
./you-get -di http://weibo.com/tv/v/FeOntp54t
[DEBUG] get_content: http://weibo.com/tv/v/FeOntp54t
[DEBUG] get_content: http://video.weibo.com/show?fid=1034:3ecf605f76c79c0ca9bca54b9cb4243d&type=mp4
[DEBUG] url_info: http://f.us.sinaimg.cn/001VsWUhlx07d3j9bFO0010f0100TwNh0k01.mp4?label=mp4_hd&template=template_6&Expires=1501427633&ssig=mc0CBX0wuj&KID=unistore,video
Site:       miaopai
Title:      Listening To Blade Runner
Type:       MPEG-4 video (video/mp4)
Size:       12.62 MiB (13234103 Bytes)
```

fixed with fca1ec8
