### ISSUE TITLE
已更新到最新版，仍然不能下载乐视视频

### ISSUE THREAD

**Issue by dvhhhh** [soimort/you-get#2210]
C:\Users\Administrator.PC-201612101328>you-get --debug http://www.le.com/ptv/vplay/1710308.html
[DEBUG] url_locations: http://www.le.com/ptv/vplay/1710308.html
[DEBUG] get_content: http://www.le.com/ptv/vplay/1710308.html
[DEBUG] get_content: http://player-pc.le.com/mms/out/video/playJson?id=1710308&platid=1&splatid=101&format=1&tkey=291388822&domain=www.le.com&region=cn&source=1000&accesyx=1
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/1710308.html']
Traceback (most recent call last):
  File "c:\users\administrator.pc-201612101328\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator.pc-201612101328\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator.PC-201612101328\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator.pc-201612101328\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator.pc-201612101328\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator.pc-201612101328\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\administrator.pc-201612101328\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\users\administrator.pc-201612101328\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator.pc-201612101328\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\le.py", line 149, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "c:\users\administrator.pc-201612101328\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\le.py", line 96, in letv_download_by_vid
    ext , urls = video_info(vid,**kwargs)
  File "c:\users\administrator.pc-201612101328\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\le.py", line 64, in video_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'
```

**Comment by jyuan15** [comment]
不是说乐视只有540P的画质了么，事实上也只能解析出540P，@soimort-bot 是如何解析出1080P的？

$ python you-get -i http://www.le.com/ptv/vplay/1710308.html
Current Video Supports:
        --format 350 <URL>
        --format 1000 <URL>
        --format 1300 <URL>
        --format 720p <URL>
        --format 1080p <URL>
Site:       Le.com
Title:      从普拉达到纳达
Type:       MPEG-4 video (video/mp4)
Size:       422.01999999999998 MiB (442522672 Bytes)

**Comment by rosynirvana** [comment]
十有八九是因为美国IP

**Comment by jyuan15** [comment]
> 十有八九是因为美国IP

也以为是这原因，但挂了美国IP后根本解析不出来（Youtube没问题）

**Comment by rosynirvana** [comment]
当然不是断言所有美国IP都行

准确来说，乐视的api server对于它所使用的IP库中的某个部分依然有1080p，这个“某个部分”现在已知的特征就是美国IP

**Comment by jyuan15** [comment]
> 准确来说，乐视的api server对于它所使用的IP库中的某个部分依然有1080p，这个“某个部分”现在已知的特征就是GeoIP库识别出美国IP

你说的是真的嘛![28](https://user-images.githubusercontent.com/12642186/28787401-a1f6a6c2-764e-11e7-885b-e41c7ea350db.gif)

**Comment by lki2019** [comment]
<pre><code>you-get -i http://www.le.com/ptv/vplay/1710308.html
Current Video Supports:
        --format 350 <URL>
        --format 1000 <URL>
        --format 1300 <URL>
        --format 720p <URL>
        --format 1080p <URL>
Site:       Le.com
Title:      从普拉达到纳达
Type:       MPEG-4 video (video/mp4)
Size:       422.02 MiB (442522672 Bytes)<pre><code>

并没有你说的情况啊
<pre><code>
80.8% (341.0/422.0MB) ├██████████████████
80.8% (341.2/422.0MB) ├██████████████████
80.9% (341.4/422.0MB) ├██████████████████
81.0% (341.7/422.0MB) ├██████████████████
81.0% (341.9/422.0MB) ├██████████████████
81.1% (342.2/422.0MB) ├██████████████████
81.1% (342.2/422.0MB) ├██████████████████
81.2% (342.5/422.0MB) ├██████████████████
81.2% (342.7/422.0MB) ├██████████████████
81.3% (342.9/422.0MB) ├██████████████████
81.3% (343.2/422.0MB) ├██████████████████
81.4% (343.4/422.0MB) ├██████████████████
81.4% (343.7/422.0MB) ├██████████████████
81.4% (343.7/422.0MB) ├██████████████████<pre><code>

**Comment by rosynirvana** [comment]
因为他所在地区不能访问那个视频呗
