### ISSUE TITLE
Cannot download the all parts. Only first 10 finished.

### ISSUE THREAD

**Issue by scegg** [soimort/you-get#2215]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

you-get http://v.youku.com/v_show/id_XMjkzODAyODc1Mg==.html --debug
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjkzODAyODc1Mg==&ccode=0401&client_ip=192.168.1.1&utid=XKkHEk8D4yACAXQZ8E4eLHUE&client_ts=1501608801
site:                优酷 (Youku)
title:               观复嘟嘟（第81期）：一只蚕引发一件大事
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          512.3 MiB (537189420 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjkzODAyODc1Mg%3D%3D&type=hd3&ups_client_netip=116.25.240.78&ups_ts=1501608796&utid=XKkHEk8D4yACAXQZ8E4eLHUE&ccode=0401&psid=11f17d2ed68539d2cb355eb266c24ab6&duration=2119&expire=18000&ups_key=736124bbc69db99a9605856aaa3f24d3
    # download-with: you-get --format=hd3 [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 观复嘟嘟（第81期）：一只蚕引发一件大事.flv ...
64.9% (332.4/512.3MB) ├█████████████████████████──────────────┤[10/16]  413 MB/syou-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjkzODAyODc1Mg==.html']
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1477, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1388, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1186, in download_main
    download(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1470, in any_download
    m.download(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractor.py", line 224, in download
    av=stream_id in self.dash_streams)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 838, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 512, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 418, in url_size
    response = urlopen_with_retry(url)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\program files\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\program files\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\program files\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\program files\python36\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "c:\program files\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\program files\python36\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\program files\python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\program files\python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\program files\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\program files\python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\program files\python36\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "c:\program files\python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "c:\program files\python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "c:\program files\python36\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by scegg** [comment]
I can download only first 10 parts of the file.

**Comment by scegg** [comment]
seems to be network problem. solved a day after.
