### ISSUE TITLE
sports.le.com不支持乐视体育吗

### ISSUE THREAD

**Issue by luhy118** [soimort/you-get#2217]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
D:\workspace\clip-spider>you-get http://m.sports.le.com/video/topic/s/8849_24348958.html --debug
[DEBUG] url_locations: http://m.sports.le.com/video/topic/s/8849_24348958.html
[DEBUG] get_content: http://www.lesports.com/video/topic/s/8849_24348958.html
[DEBUG] get_content: http://player-pc.le.com/mms/out/video/playJson?id=None&platid=1&splatid=101&format=1&tkey=2992554458&domain=www.le.com&region=cn&source=1000&accesyx=1
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://m.sports.le.com/video/topic/s/8849_24348958.html']
Traceback (most recent call last):
  File "d:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\extractors\le.py", line 149, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\extractors\le.py", line 96, in letv_download_by_vid
    ext , urls = video_info(vid,**kwargs)
  File "d:\program files\python36\lib\site-packages\you_get\extractors\le.py", line 64, in video_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
http://sports.le.com/video/24348958.html

**Comment by luhy118** [comment]
3Q
