### ISSUE TITLE
moov.hk 网站解析

### ISSUE THREAD

**Issue by NearTan** [soimort/you-get#2218]
在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
$ you-get "https://moov.hk/\#/concert/VAML00034978A" --debug
[DEBUG] get_head: https://moov.hk/%5c
[DEBUG] get_head: https://moov.hk/%5c
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://moov.hk/\\#/concert/VAML00034978A']
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/universal.py", line 10, in universal_download
    content_type = get_head(url, headers=fake_headers)['Content-Type']
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 434, in get_head
    res = urlopen_with_retry(req)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1181, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/universal.py", line 12, in universal_download
    content_type = get_head(url, headers=fake_headers, get_method='GET')['Content-Type']
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 434, in get_head
    res = urlopen_with_retry(req)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

网站应该用的是 RTMP 协议，但是 URL 用的是 `#` 锚点来定位资源，处理时自然忽略掉锚点就返回 404，这就很尴尬。

另外我打开 Developer Tools 得到以下抓包
![screen shot 2017-08-03 at 6 39 10 pm](https://user-images.githubusercontent.com/4445695/28918228-1162a708-787b-11e7-8d0c-f6463caa74ae.png)

用 charls 抓 Android apk 的包得到以下 CURL
```
curl -H 'cookie: MTGSESSIONID=xxx;MTGDeviceID=xxx' \
-H 'x-wap-profile: http://uaprof.sonymobile.com/G8142R4501.xml' \
-H 'MTGHLS: MTGSESSIONID=xxxx;MTGDeviceID=xxx' \
-H 'User-Agent: SonyG8142 Build/45.0.A.7.90 stagefright/1.2 (Linux;Android 7.1.1)' \
-H 'Host: mtgvideostream.moov.now.com' \
--compressed 'https://mtgvideostream.moov.now.com/httpstreamer/getmedia?pid=xxx&segment=2&token=xxxx&appId=mtg'
```

因为网站是收费观看（新注册可免费 14 天），所以如果不便增加支持此网站的话，能不能提供一下思路我来试试？因为本人实在没有接触过相关项目，先感谢了～

**Comment by rosynirvana** [comment]
```https://mtg.now.com/moov/api/content/checkout?deviceid={device_id}&devicetype=web&cat=playlist&refid=&reftype=&pid={profile_id}&preview=F&connect=web&streamtype=hls&quality=FD&application=moovnext&clientver=2.0.6```
必须cookie ```MTGSESSIONID```

拿到的json按协议用```rtmpdump```处理就行了

**Comment by NearTan** [comment]
@rosynirvana 
非常感谢
我拿到了这样的 json
```
{  
  "result":{  
    "resultCode":"0",
    "chiMessage":"",
    "engMessage":"",
    "checksum":"-1359720693",
    "dataObject":{  
      "membership":"2",
      "membershipType":"1",
      "pid":"VVML00000545",
      "token":"xxx",
      "contentKey":"",
      "playUrl":"rtmpte://pctvfstream.netvigator.com:80/mv/",
      "playUrlValidate":"xxx",
      "allowDownload":"T",
      "quality":"FD",
      "moovMembership":"3",
      "aspectRatio":"",
      "netpassId":"30000798964",
      "loginId":"mov30000798964@netvigator.com"
    },
    "messageUrl":""
  }
}
```
可是我在构造 `rtmpdump` 时不知道参数对应位置，貌似少了那些参数，我构造的命令大概是这样的
```
rtmpdump -r "{playUrl}" \
--playpath "{playUrlValidate}" -o "output.mp4" -v
```

**Comment by rosynirvana** [comment]
```rtmpdump -r "rtmp://pctvfstream.netvigator.com:80/mv/" -l 3 -y {playUrlValidate} -T {token}```

**Comment by NearTan** [comment]
@rosynirvana 成功了，非常感谢～

**Comment by NearTan** [comment]
不过遇到一个奇怪的问题，`quality` 这个参数我与网页上的一致，但是网页上视频的质量是 `HD1080p` 而我下载下来经过对比看起来是 `SD` 的画质，并且我在播放途中切换画质浏览器似乎也没重新申请 token，我用 Wireshark 抓了一下看 RTMP 的包也没找到突破口。

不过这个已经超出 repo 的范围了，要是花费你太多时间的话就可以无视掉吧

**Comment by rosynirvana** [comment]
console里的debug log都没藏
把文件名后面的```_s```改成```_f```就行了
