### ISSUE TITLE
 HTTP Error 403 When Downloading Large Videos (> 5GiB) on Youku

### ISSUE THREAD

**Issue by Iustinius** [soimort/you-get#2236]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ✓] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [✓ ] Your `you-get` is up-to-date.
- [✓ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [✓ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [✓ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get: ['v.youku.com/v_show/id_XMjk0NzA0MTk3Ng==.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1181, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 224, in download
    av=stream_id in self.dash_streams)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 835, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 556, in url_save
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 501, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 684, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by rosynirvana** [comment]
blame their CDN
```
you-get -d http://v.youku.com/v_show/id_XMjk0NzA0MTk3Ng\=\=.html
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk0NzA0MTk3Ng==&ccode=0401&client_ip=192.168.1.1&utid=LvkNEgSugQMCAbZyAmGu9L%2BB&client_ts=1502022446
site:                优酷 (Youku)
title:               2017.8月5日直播录像（无弹幕）
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          5005.7 MiB (5248844563 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk0NzA0MTk3Ng%3D%3D&type=hd3&ups_client_netip=182.114.2.97&ups_ts=1502022447&utid=LvkNEgSugQMCAbZyAmGu9L%2BB&ccode=0401&psid=110ecc43a314be54104f11f735fd48fb&duration=15177&expire=18000&ups_key=a9c567dd39d7111dcbe6d702d49c4a3e
    # download-with: you-get --format=hd3 [URL]

Downloading 2017.8月5日直播录像（无弹幕）.flv ...
 0.0% (   1.0/5005.7MB) ├───────────────────────────────────┤[  1/112]    2 MB/s
```

**Comment by lki2019** [comment]
并没有出错啊 试了

**Comment by Iustinius** [comment]
你下完了整个视频吗？我一般是下到40% - 50%左右会跳403 error.

**Comment by lki2019** [comment]
你的意思是你试验了好几次 都这个情况么？
我只试验了下了百分之10就关了，你题目里也没说明是下到百分之多少回跳403啊 
以为你说的一点也不能下呢

**Comment by lki2019** [comment]
你要试验了几次 都这样，我可以试验下

**Comment by Iustinius** [comment]
抱歉，是我没有说清楚。是的，我试验了至少有10次吧，都是这样的情况。

**Comment by lki2019** [comment]
的确有中途回403的情况，你继续下载，它回断点续传的啊，最起码我这里断了后，我在继续下载这个 它是接着的，从百分之多少继续接着下的。现在下到百分30了 我还在试验

**Comment by rosynirvana** [comment]
youku CDN的问题没办法
从多少年前开始就这样子

**Comment by lki2019** [comment]
我有个想法，
可以写个批处理，下载这种超大视频，如果下载中途断开，然后倒计时10秒，然后自动继续下载，直到完成，

**Comment by lki2019** [comment]
timeout /t 10
cls
set /a counts=counts+1
goto main
exit

**Comment by Iustinius** [comment]
@lki2019 试了一下，可以断点续传。
@rosynirvana 5GiB的确不是出问题的边界条件，是我的问题描述有歧义。
多谢二位的回答~

**Comment by lki2019** [comment]
<pre><code>
site:                优酷 (Youku)
title:               2017.8月5日直播录像（无弹幕）
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          5005.7 MiB (5248844563 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk0NzA0MTk3Ng%3
D%3D&type=hd3&ups_client_netip=58.18.64.236&ups_ts=1502030361&utid=GRgOEhS2GTECA
ToSQOx3SJQO&ccode=0401&psid=dcc6a921666195eef4936eb0eb1a7931&duration=15177&expi
re=18000&ups_key=619d6ab0d202da195b29e2508e42bd13
    # download-with: you-get --format=hd3 [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Skipping .\2017.8月5日直播录像（无弹幕）.mp4: file already exists


等待  9 秒，按一个键继续 ..

<pre><code>

试验完毕，这个批处理可以用，最后合并完成后，
经过合并的过程后，最终生成2017.8月5日直播录像（无弹幕）.mp4

然后回提示上方的信息，你关闭就行了
==========================================
1.把you-get路径放到环境变量里
2.建立一个批处理  
超大视频下载.bat


@echo off
set /a counts=1
:main
call you-get -d http://v.youku.com/v_show/id_XMjk0NzA0MTk3Ng==.html

timeout /t 10
cls
set /a counts=counts+1
goto main
exit
</code></pre>

**Comment by fydennis** [comment]
我也遇到了这个问题，不同的是下完一个片段的时候报403错误。片段的位置不固定，有的在第30段，有的在17段。同系列的视频其他的能顺利下完，但遇到403错误的文件反复多次断点续传还是在同一个片段报错

**Comment by fydennis** [comment]
you-get http://v.youku.com/v_show/id_XMTUzOTI1MzIzNg==.html?spm=a2hzp.8253869.0.0 --debug
把之前已经下载的区段删除又重新下了一次，中间偶尔中断一两次都能重续上，但在30/36区段的地方还是报403错误，卡住不能续传了

**Comment by lki2019** [comment]
@fydennis  看到我上面的回复了么？
你用那个批处理，自动下载就行，
我试了你这个地址，不存在续不上的问题，
批处理回自动断开后自动再次执行下载命令·

**Comment by fydennis** [comment]
@lki2019 之前是用bash装的，又在Windows下重装了一遍最新的develop版并用了你的批处理命令，还是同样的403错误，批处理只是一遍遍的重试然后每次都卡在同一个地方。

**Comment by fydennis** [comment]
@lki2019 试着又下了几个其他的视频，大部分都能重续上，体积更大的视频也没出问题。出问题的那个地址换hd2清晰度下也没问题，平均下载速度>3m/s。可能是youku对于某几个视频的某些清晰度的网络接口会抽风？

**Comment by lki2019** [comment]
@fydennis 出问题的那个地址 是哪个地址啊？
是你开头那个么？v.youku.com/v_show/id_XMjk0NzA0MTk3Ng==.html

我试了，没有你的那个情况啊
批处理就是自动循环执行下载命令的，省去你手动输入命令

**Comment by lki2019** [comment]
针对楼主所说的这个地址http://v.youku.com/v_show/id_XMTUzOTI1MzIzNg==.html?spm=a2hzp.8253869.0.0

you-get -d http://v.youku.com/v_show/id_XMTUzOTI1MzIzNg==.html?spm=a2hzp.8253869.0.0

下载途中遇到<pre><code>File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
b\request.py", line 532, in open
  response = meth(req, response)
File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
b\request.py", line 642, in http_response
  'http', request, response, code, msg, hdrs)
File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
b\request.py", line 570, in error
  return self._call_chain(*args)
File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
b\request.py", line 504, in _call_chain
  result = func(*args)
File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
b\request.py", line 650, in http_error_default
  raise HTTPError(req.full_url, code, msg, hdrs, fp)
llib.error.HTTPError: HTTP Error 403: Forbidden</code></pre>


<pre><code>ykdl http://v.youku.com/v_show/id_XMTUzOTI1MzIzNg==.
pm=a2hzp.82.0.0
ite:                优酷 (Youku)
itle:               文明5 奥地利超时空军团-part5
rtist:              None
treams:
   - format:        BD
     container:     flv
     video-profile: 1080p
     size:          1824.9 MiB (1913527817 bytes)
   # download-with: ykdl --format=BD [URL]
ownload: 文明5 奥地利超时空军团-part5_BD part 0
ownload: 文明5 奥地利超时空军团-part5_BD part 1
ownload: 文明5 奥地利超时空军团-part5_BD part 2
ownload: 文明5 奥地利超时空军团-part5_BD part 3
ownload: 文明5 奥地利超时空军团-part5_BD part 4
ownload: 文明5 奥地利超时空军团-part5_BD part 5
ownload: 文明5 奥地利超时空军团-part5_BD part 6
ownload: 文明5 奥地利超时空军团-part5_BD part 7
 15%<

--


rame=143282 fps=380 q=-1.0 size= 1825536kB time=01:19:36.09 bitrate=3131.2kbits
rame=143694 fps=380 q=-1.0 size= 1828608kB time=01:19:49.81 bitrate=3127.5kbits
rame=143795 fps=380 q=-1.0 size= 1830912kB time=01:19:53.18 bitrate=3129.2kbits
rame=144389 fps=381 q=-1.0 size= 1835264kB time=01:20:12.96 bitrate=3123.7kbits
rame=144598 fps=381 q=-1.0 size= 1839616kB time=01:20:19.93 bitrate=3126.6kbits
rame=144808 fps=381 q=-1.0 size= 1842944kB time=01:20:26.94 bitrate=3127.7kbits
rame=145229 fps=381 q=-1.0 size= 1850112kB time=01:20:40.96 bitrate=3130.8kbits
rame=145550 fps=382 q=-1.0 size= 1853952kB time=01:20:51.67 bitrate=3130.4kbits
rame=145822 fps=382 q=-1.0 size= 1858304kB time=01:21:00.72 bitrate=3131.9kbits
rame=146022 fps=382 q=-1.0 size= 1861888kB time=01:21:07.39 bitrate=3133.6kbits
rame=146282 fps=382 q=-1.0 size= 1867776kB time=01:21:16.07 bitrate=3137.9kbits
rame=146312 fps=382 q=-1.0 Lsize= 1868689kB time=01:21:17.47 bitrate=3138.6kbit
/s speed=12.7x
ideo:1786146kB audio:76198kB subtitle:0kB other streams:0kB global headers:0kB
uxing overhead: 0.340717%

:\Users\Administrator>/code></pre>

使用YKDL 下载同样的地址 未出现断开现象

针对大神说的 我下youku没遇到过断开，因为我除了测试之外都不用啊

大神可以测试下这个地址，是否中途会出现断开的现象，如果大神下早途中一切正常
那么说明
1。CDN机制问题 有些的确正常不会断开，有些的确会，比如我还有这个问题里有断开现象的人

如果大神也遇到了下载途中断开的现象，
那说明
1，CDN机制问题
2.you-get 关于优酷的解析脚本可能有些问题。

以上仅是我测试的过程和我的判断，可能不对，仅供参考

**Comment by rosynirvana** [comment]
因为游戏分区有些CDN失效时间不对，而ykdl同时下载所以能避免这问题……

**Comment by Iustinius** [comment]
下载 http://v.youku.com/v_show/id_XMjk2MzgzNjcwMA==.html?spm=a2h0k.8191407.0.0&from=s1.8-3-1.1 时，断点续传卡在了24.1%，重复多次也下不了更多了。尝试删除所有文件后重新下载，还是卡在同一个地方。debug信息如下：

`you-get: ['http://v.youku.com/v_show/id_XMjk2MzgzNjcwMA==.html?spm=a2h0k.8191407.0.0&from=s1.8-3-1.1']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1352, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1259, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1057, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1345, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/youku.py", line 263, in youku_download_by_url
    Youku().download_by_url(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractor.py", line 227, in download
    av=stream_id in self.dash_streams)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 782, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 526, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 430, in url_size
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 344, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

求大神指点~

**Comment by lki2019** [comment]
26.4% (1530.3/5793.7MB) ├██████████────────
26.4% (1530.6/5793.7MB) ├██████████────────
26.4% (1530.8/5793.7MB) ├██████████────────
26.4% (1531.1/5793.7MB) ├██████████────────
26.4% (1531.3/5793.7MB) ├██████████────────
26.4% (1531.6/5793.7MB) ├██████████────────
26.4% (1531.8/5793.7MB) ├██████████────────
26.4% (1532.1/5793.7MB) ├██████████────────
26.4% (1532.3/5793.7MB) ├██████████────────
26.5% (1532.6/5793.7MB) ├██████████────────
26.5% (1532.8/5793.7MB) ├██████████────────
26.5% (1533.1/5793.7MB) ├██████████────────
26.5% (1533.3/5793.7MB) ├██████████────────
26.5% (1533.6/5793.7MB) ├██████████────────
26.5% (1533.8/5793.7MB) ├██████████────────
26.5% (1534.1/5793.7MB) ├██████████────────
26.5% (1534.3/5793.7MB) ├██████████────────
────────┤[ 37/149]  241 kB/s


并没有你说的情况，只是速度在百分之24之前都是几M/秒
倒了百分26之后 速度就是龟速了 几百K了

但是并没有断···
不知道你是哪天更新的
建议你在更新一下 
然后在试下，用那个批处理自动让他下就好了
目前下载到百分27了 依然没有断

也可能地区 CDN差异？
反正我这里是正常的
到百分28断了一次，也正常，，

批处理自动继续执行下载命令 的···
自动执行第2次下载后，速度上来了 几M

**Comment by rosynirvana** [comment]
等一段时间再下

**Comment by fydennis** [comment]
http://v.youku.com/v_show/id_XMTUzOTI1MzIzNg==.html?spm=a2hzp.8253869.0.0
这个网址已经试过好多次了，每次都隔一两天再重试，每次都卡在30/35的时候报错。其他视频链接大部分都没这个问题。今天装ykdl试了一次，也是同样的第30块下不了（ERROR:downloader:donwload failed at part 30）
#话说ykdl的error信息有typo...

**Comment by lki2019** [comment]
frame=143899 fps=1014 q=-1.0 size= 1827072kB time=01:19:56.58 bitrate=3120.4kbit
frame=144558 fps=1015 q=-1.0 size= 1832704kB time=01:20:18.55 bitrate=3115.8kbit
frame=144703 fps=1013 q=-1.0 size= 1836288kB time=01:20:23.38 bitrate=3118.7kbit
frame=144973 fps=1011 q=-1.0 size= 1842176kB time=01:20:32.38 bitrate=3122.9kbit
frame=145107 fps=1008 q=-1.0 size= 1843712kB time=01:20:36.85 bitrate=3122.6kbit
frame=145587 fps=1008 q=-1.0 size= 1848832kB time=01:20:52.85 bitrate=3121.0kbit
frame=145914 fps=1006 q=-1.0 size= 1853696kB time=01:21:03.75 bitrate=3122.2kbit
frame=146086 fps=1004 q=-1.0 size= 1858304kB time=01:21:09.48 bitrate=3126.2kbit
frame=146312 fps=998 q=-1.0 Lsize= 1869165kB time=01:21:17.43 bitrate=3139.4kbit
s/s speed=33.3x
video:1787003kB audio:76198kB subtitle:0kB other streams:0kB global headers:0kB
muxing overhead: 0.320064%
Merged into 文明5 奥地利超时空军团-part5.mp4


全程无中断，并没有你说的情况，

如果你是下载很多很多视频，建议你某一天啥都别下  就先单下这个 在看看

反正我这是没问题·

**Comment by JayXon** [comment]
我试了一下ykdl，由于支持多线程，下载速度直接翻了十几倍，并且没有遇到任何超时或者403之类的错误，不过我还是想用you-get。。。
话说为什么you-get不支持多线程？我看不是已经有PR了么 #1682
