### ISSUE TITLE
twitter video is not being merged mp4s

### ISSUE THREAD

**Issue by tarungog** [soimort/you-get#2250]
Please make sure these boxes are checked before submitting your issue – thank you!

- [X] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [X] Your `you-get` is up-to-date.
- [X] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [X] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [X] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
>> you-get https://twitter.com/addison_angelo/status/890027834932166657 --debug
[DEBUG] get_response: http://twitter.com/addison_angelo/status/890027834932166657
[DEBUG] get_content: https://twitter.com/i/videos/890027834932166657?embed_source=facebook
[DEBUG] get_content: https://video.twimg.com/ext_tw_video/890027795685851136/pu/pl/wrtvIP3YWow-Y-Lw.m3u8
[DEBUG] get_content: https://video.twimg.com/ext_tw_video/890027795685851136/pu/pl/720x1280/A-fyinCX6p-i2OQk.m3u8
Site:       Twitter.com
Title:      addison_angelo [890027834932166657]
Type:       MPEG-4 video (video/mp4)
Size:       1.99 MiB (2091124 Bytes)

Downloading addison_angelo [890027834932166657].mp4 ...
 100% (  2.0/  2.0MB) ├████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[2/2]   10 MB/s
Merging video parts...
./addison_angelo [890027834932166657][00].mp4
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://twitter.com/addison_angelo/status/890027834932166657']
Traceback (most recent call last):
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/extractors/twitter.py", line 25, in twitter_download
    assert urls
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/common.py", line 1181, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/extractors/twitter.py", line 85, in twitter_download
    download_urls(urls, page_title, ext, size, output_dir, merge=merge)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/common.py", line 875, in download_urls
    concat_mp4(parts, output_filepath)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 914, in concat_mp4
    merge_mp4s(mp4s, output)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 876, in merge_mp4s
    mp4s = list(map(read_mp4, ins))
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 717, in read_mp4
    atoms = parse_atoms(stream)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 708, in parse_atoms
    atom = read_atom(stream)
  File "/usr/local/Cellar/you-get/0.4.803/libexec/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 700, in read_atom
    raise NotImplementedError('%s: %d' % (type, left))
NotImplementedError: b'\x00B\xf0!': 1195381000
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by tarungog** [comment]
@soimort-bot the dry run works but the real download does not; the mp4 merging on mac is failing

**Comment by soimort** [comment]
I guess you might need to install `ffmpeg` for that.
