### ISSUE TITLE
zol.com.cn support?

### ISSUE THREAD

**Issue by dkl3** [soimort/you-get#2256]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x ] Your `you-get` is up-to-date.
- [ x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get  http://zol.iqiyi.com.cn/video25224.html --debug
[DEBUG] get_response: http://zol.iqiyi.com.cn/video25224.html
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://zol.iqiyi.com.cn/video25224.html']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/__main__.py", line 92, in main
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/common.py", line 1352, in main
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/common.py", line 1259, in script_main
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/common.py", line 1057, in download_main
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/common.py", line 1345, in any_download
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/extractor.py", line 46, in download_by_url
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/extractors/iqiyi.py", line 139, in prepare
TypeError: Can't convert 'NoneType' object to str implicitly

In addition:

~$ you-get  http://v.zol.com.cn/video25224.html --debug
[DEBUG] get_response: http://zol.iqiyi.com.cn/video25224.html
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://v.zol.com.cn/video25224.html']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/__main__.py", line 92, in main
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/common.py", line 1352, in main
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/common.py", line 1259, in script_main
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/common.py", line 1057, in download_main
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/common.py", line 1345, in any_download
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/extractor.py", line 46, in download_by_url
  File "/usr/lib/python3.4/site-packages/you_get-0.4.803-py3.4.egg/you_get/extractors/iqiyi.py", line 139, in prepare
TypeError: Can't convert 'NoneType' object to str implicitly


```
Example urls:

* http://v.zol.com.cn/video25224.html
* http://zol.iqiyi.com.cn/video25224.html

Thank you :)

**Comment by lki2019** [comment]
![qq 20170812145618](https://user-images.githubusercontent.com/30022431/29238794-8796f2d6-7f6e-11e7-96cb-e25511f1108d.png)

差点把我蒙住了，

**Comment by rosynirvana** [comment]
```
./you-get -di http://v.zol.com.cn/video25224.html
[DEBUG] get_response: http://zol.iqiyi.com.cn/video25224.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/2120762209
[DEBUG] get_content: http://www.iqiyi.com/w_19rqvkzkst.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/2120762209/eff24e07061fc00d92e5fb01c1a31723/?t=1502524724809&sc=4bd9507ed3eab4f896017bd95645f04d&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               世界上玩马里奥龟壳最牛的人
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        HD
      container:     m3u8
      video-profile: 540p
      m3u8_url:      http://cache.m.iqiyi.com/mus/2120762209/b61a8a9b9264893784357e34118ae69f/afbe8fd3d73448c9//20140511/72/b7/f5/331cbb4dca2289694a749bee4c826eb9.m3u8?qd_originate=tmts_py&tvid=2120762209&bossStatus=0&qd_vip=0&px=&qd_src=null&prv=&previewType=&previewTime=&from=&qd_time=1502524724849&qd_p=7d2db2af&qd_asc=7213f164031835711aec2562122782c4&qypid=2120762209_04022000001000000000_2&qd_k=4bd9507ed3eab4f896017bd95645f04d&vf=7398590667d55881e227df1ae85a0ab3&np_tag=nginx_part_tag
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
      m3u8_url:      http://cache.m.iqiyi.com/mus/2120762209/0c765921e6f6a428d3a8c3dcde43704f/afbe8fd3d73448c9//20140511/72/b7/f5/518e5c706f2602d9ecd903465fc9609c.m3u8?qd_originate=tmts_py&tvid=2120762209&bossStatus=0&qd_vip=0&px=&qd_src=null&prv=&previewType=&previewTime=&from=&qd_time=1502524724849&qd_p=7d2db2af&qd_asc=f76f6691731f5d631256532c5dd57606&qypid=2120762209_04022000001000000000_1&qd_k=4bd9507ed3eab4f896017bd95645f04d&vf=2147816873e051249167b73f021b96b8&np_tag=nginx_part_tag
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
      m3u8_url:      http://cache.m.iqiyi.com/mus/2120762209/eff24e07061fc00d92e5fb01c1a31723/afbe8fd3d73448c9//20140511/72/b7/f5/18ebd206f16dbbb2a402e5491b1f94ed.m3u8?qd_originate=tmts_py&tvid=2120762209&bossStatus=0&qd_vip=0&px=&qd_src=null&prv=&previewType=&previewTime=&from=&qd_time=1502524724849&qd_p=7d2db2af&qd_asc=2d4fb4084c41679da035407ebed4a76b&qypid=2120762209_04022000001000000000_96&qd_k=4bd9507ed3eab4f896017bd95645f04d&vf=6683d24c5296210cbf11a8c6a7cb93a1&np_tag=nginx_part_tag
    # download-with: you-get --format=LD [URL]
```

**Comment by lki2019** [comment]
<pre><code>
C:\Users\Administrator>you-get -d http://nb.zol.com.cn/650/6509483.html
[DEBUG] get_head: http://nb.zol.com.cn/650/6509483.html
[DEBUG] get_content: http://nb.zol.com.cn/650/6509483.html
[DEBUG] get_response: http://nb.zol.com.cn/650/6509483.html
[DEBUG] url_info: http://i4.article.fd.zol-img.com.cn/t_s120x75/g5/M00/0A/02/ChM
kJ1mMNAGIC2x0AAEY5i700bsAAfjvgB-ja0AARj-854.jpg
Site:       zol.com.cn
Title:      ChMkJ1mMNAGIC2x0AAEY5i700bsAAfjvgB-ja0AARj-854
Type:       JPEG Image (image/jpeg)
Size:       0.0 MiB (2106 Bytes)

Downloading ChMkJ1mMNAGIC2x0AAEY5i700bsAAfjvgB-ja0AARj-854.jpg ...
 0.0% (  0.0/  0.0MB) ├────────────────────────────
 100% (  0.0/  0.0MB) ├████████████████████████████
█████████████┤[1/1]   10 kB/s


其实是56分钟的

C:\Users\Administrator>you-get -d http://nb.zol.com.cn/650/6509179.html
[DEBUG] get_head: http://nb.zol.com.cn/650/6509179.html
[DEBUG] get_content: http://nb.zol.com.cn/650/6509179.html
[DEBUG] get_response: http://nb.zol.com.cn/650/6509179.html<pre><code>

**Comment by rosynirvana** [comment]
不会自动转跳到zol.iqiyi的要另外写extractor了

**Comment by rosynirvana** [comment]
5825564

```
./you-get -i http://nb.zol.com.cn/650/6509483.html
site:                爱奇艺 (Iqiyi)
title:               拆机pa：如何变得更轻薄还带指纹识别？华硕U4100U拆机直播
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        HD
      container:     m3u8
      video-profile: 540p
      m3u8_url:      http://cache.m.iqiyi.com/mus/8799075709/22f201c46ec0435665025c2c7d2e42dd/afbe8fd3d73448c9//20170811/d5/31/f0f6429dc49837c680510367a8a82392.m3u8?qd_originate=tmts_py&tvid=8799075709&bossStatus=0&qd_vip=0&px=&qd_src=null&prv=&previewType=&previewTime=&from=&qd_time=1502542702322&qd_p=7d2db2af&qd_asc=15f622f9d65bdb5c434d0eea0156bf0e&qypid=8799075709_04022000001000000000_2&qd_k=a484a660788cf819d4d999bd115a773a&vf=1b67441493ff25fda58b09ddc6a88eb3&np_tag=nginx_part_tag
    # download-with: you-get --format=HD [URL]
```
