### ISSUE TITLE
Some of sohu videos get no host given error

### ISSUE THREAD

**Issue by einverne** [soimort/you-get#2268]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
./you-get -di "http://my.tv.sohu.com/us/272999107/91667020.shtml"
[DEBUG] get_response: http://my.tv.sohu.com/us/272999107/91667020.shtml
[DEBUG] get_response: http://my.tv.sohu.com/play/videonew.do?vid=91667020&referer=http://my.tv.sohu.com
[DEBUG] get_response: http:///?prot=9&prod=flash&pt=1&file=123.126.104.214/2017/8/12/7/4/15ebb6fdb5a_91667020.mp4&new=&key=1&vid=91667020&uid=1502697319219&t=0.5014305153362143&rb=1
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://my.tv.sohu.com/us/272999107/91667020.shtml']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/mi/wjw/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/mi/wjw/you-get/src/you_get/common.py", line 1355, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/mi/wjw/you-get/src/you_get/common.py", line 1262, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/mi/wjw/you-get/src/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/home/mi/wjw/you-get/src/you_get/common.py", line 1348, in any_download
    m.download(url, **kwargs)
  File "/home/mi/wjw/you-get/src/you_get/extractors/sohu.py", line 71, in sohu_download
    urls.append(real_url(host,vid,tvid,new,clipURL,ck))
  File "/home/mi/wjw/you-get/src/you_get/extractors/sohu.py", line 20, in real_url
    return json.loads(get_html(url))['url']
  File "/home/mi/wjw/you-get/src/you_get/common.py", line 320, in get_html
    content = get_response(url, faker).data
  File "/home/mi/wjw/you-get/src/you_get/common.py", line 308, in get_response
    response = request.urlopen(url)
  File "/home/mi/.pyenv/versions/3.6.1/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/mi/.pyenv/versions/3.6.1/lib/python3.6/urllib/request.py", line 524, in open
    req = meth(req)
  File "/home/mi/.pyenv/versions/3.6.1/lib/python3.6/urllib/request.py", line 1241, in do_request_
    raise URLError('no host given')
urllib.error.URLError: <urlopen error no host given>
```

Only several of sohu videos get this error.

**Comment by einverne** [comment]
Sohu response: http://my.tv.sohu.com/play/videonew.do?vid=7654879&referer=http://my.tv.sohu.com

return

```
{
    "status": 5,
    "play": 1,
    "code": 9,
    "mytvmsg": "该视频已被删除…"
}
```

But this video can still be played, strange.

**Comment by einverne** [comment]
Found sohu move video url to `clipsURL`, give me some time to fix it.

```
  "data": {
    "tvName": "无法无天！监拍男生遭女老师扇耳光 当场猛扇耳光回击",
    "keyword": "女老师 无法无天 男生 扇耳光",
    "tag": "女老师 无法无天 男生 扇耳光",
    "ch": "pgc",
    "cid": 212115,
    "myTvUid": 272999107,
    "fps": "",
    "ipLimit": "",
    "width": 0,
    "height": 0,
    "clipsURL": [
      "123.126.104.214/2017/8/12/7/4/15ebb6fdb5a_91667020.mp4?token=o3OgoJHUl6M93F799NhZTQ&srcip=123.126.104.214&t=1502698812"
    ],
    "version": 1,
    "clipsBytes": [
      "7654879"
    ],

```

**Comment by rosynirvana** [comment]
It's OK now
```
curl http://my.tv.sohu.com/play/videonew.do\?vid\=91667020\&referer\=http://my.tv.sohu.com | js-beautify
{
    "prot": 2,
    "ct": 39,
    "allot": "121.46.19.90",
    "reserveIp": "220.181.61.213",
    "vr": 0,
    "vt": 1,
    "tn": 5,
    "sp": 1024,
    "pid": 9133449,
    "status": 1,
    "play": 1,
    "pL": 10,
    "url": "http://my.tv.sohu.com/us/272999107/91667020.shtml",
    "uS": -1,
    "fms": 0,
    "isdl": 1,
    "holiday": "0",
    "catcode": 212115,
    "systype": 1,
    "cmscat": "10000001;10000001_212115",
    "id": "91667020_1",
    "p2pflag": 1300,
    "nt": 2,
    "tvid": 91667020,
    "wm_data": {
        "wm_username": "\u706B\u9F99\u679C\u4F20\u5A92",
        "wm_userphoto": "http://224.img.pp.sohu.com.cn/p224/2016/8/1/15/27/0_157255b46fcg201b8266673_1.jpg",
        "wm_video": 1,
        "wm_isact": 1,
        "wm_publisher": 1,
        "wm_playtype": 0,
        "wm_user": 20,
        "fc_user": 0,
        "fc_video": 0,
        "wm_filing": ""
    },
    "pay_data": {},
    "data": {
        "tvName": "\u65E0\u6CD5\u65E0\u5929\uFF01\u76D1\u62CD\u7537\u751F\u906D\u5973\u8001\u5E08\u6247\u8033\u5149 \u5F53\u573A\u731B\u6247\u8033\u5149\u56DE\u51FB",
        "keyword": "\u5973\u8001\u5E08 \u65E0\u6CD5\u65E0\u5929 \u7537\u751F \u6247\u8033\u5149",
        "tag": "\u5973\u8001\u5E08 \u65E0\u6CD5\u65E0\u5929 \u7537\u751F \u6247\u8033\u5149",
        "ch": "pgc",
        "cid": 212115,
        "myTvUid": 272999107,
        "fps": "",
        "ipLimit": "",
        "width": 0,
        "height": 0,
        "clipsURL": [""],
        "version": 1,
        "clipsBytes": ["7654879"],
        "num": 1,
        "coverImg": "http://001.img.pu.sohu.com.cn/group2/M10/8D/55/MTAuMTAuODguODE=/6_15ebbd13582g104SysCutcloud_91667020_7_3b.jpg",
        "totalDuration": 65,
        "totalBytes": 7654879,
        "clipsDuration": [65],
        "relativeId": "",
        "totalBlocks": 1,
        "ck": ["2dRkhz-1yCEo5vyJD3ydtPNErJLf7Hh1"],
        "hc": ["PHFP23NHXKMQCYPC33LOZ3T2GETTD5I4"],
        "su": ["/219/8/r8dggQJEJ4zB88rG0ePJ6C.mp4"],
        "sT": 0,
        "norVid": "91667020_2",
        "highVid": "91667020_1",
        "superVid": "91667020_21",
        "oriVid": "91667020_31",
        "eT": 0,
        "eP": null
    },
    "syst": 1502721153444,
    "dm": 0,
    "isSelf": 0
}
```

**Comment by einverne** [comment]
It's OK here now. I don't know why sohu change this json sometime. But it seems if allot is empty, we can get the video link in `clipsURL`.

**Comment by rosynirvana** [comment]
```diff
2c2
<     "prot": 3,
---
>     "prot": 2,
4c4,5
<     "allot": "",
---
>     "allot": "121.46.19.90",
>     "reserveIp": "220.181.61.213",
49c50
<         "clipsURL": ["123.126.104.214/2017/8/12/7/4/15ebb6fdb5a_91667020.mp4?token=o3OgoJHUl6M93F799NhZTQ&srcip=123.126.104.214&t=1502698812"],
---
>         "clipsURL": [""],
59c60
<         "ck": ["1"],
---
>         "ck": ["2dRkhz-1yCEo5vyJD3ydtPNErJLf7Hh1"],
61c62
<         "su": [""],
---
>         "su": ["/219/8/r8dggQJEJ4zB88rG0ePJ6C.mp4"],
70c71
<     "syst": 1502698812133,
---
>     "syst": 1502721153444,
```

something to do with ```prot```
