### ISSUE TITLE
Sohu could get url but download with HTTP error 403

### ISSUE THREAD

**Issue by fuzhuo** [soimort/you-get#2274]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
./you-get -d 'http://tv.sohu.com/20170810/n600098774.shtml'
[DEBUG] get_response: http://tv.sohu.com/20170810/n600098774.shtml
[DEBUG] get_response: http://hot.vrs.sohu.com/vrs_flash.action?vid=3953866
[DEBUG] get_response: http://hot.vrs.sohu.com/vrs_flash.action?vid=3953869
[DEBUG] get_response: http://220.181.61.229/?prot=9&prod=flash&pt=1&file=/tv/Sample1/BackUp_Sample1/svc/20170810/91612926_3953868_tv_S_191252_47011/91612926_3953868_tv_S_191252_47011_001.mp4&new=/148/182/LueCMkvvQHWwmwmdNFTNMD.mp4&key=DeAXdvDMqPDFkWzM7BWbuc3IRPnMrhW3&vid=3953869&uid=1502777043154&t=0.17922277700688594&rb=1
[DEBUG] get_response: http://220.181.61.229/?prot=9&prod=flash&pt=1&file=/tv/Sample1/BackUp_Sample1/svc/20170810/91612926_3953868_tv_S_191252_47011/91612926_3953868_tv_S_191252_47011_002.mp4&new=/83/64/T8QL1zpCJZLYk9D0oc0sVC.mp4&key=f685I4eyggMkEBNizUIPrLwY9ALi6SD6&vid=3953869&uid=1502777043255&t=0.6423247415078134&rb=1
[DEBUG] get_response: http://220.181.61.229/?prot=9&prod=flash&pt=1&file=/tv/Sample1/BackUp_Sample1/svc/20170810/91612926_3953868_tv_S_191252_47011/91612926_3953868_tv_S_191252_47011_003.mp4&new=/216/65/KKEXH8nqoFFUi6kbEJ9F1B.mp4&key=68snWpIXrwypM_7ccCJ-Bf4Dm9y802dp&vid=3953869&uid=1502777043322&t=0.3403211238912385&rb=1
[DEBUG] get_response: http://220.181.61.229/?prot=9&prod=flash&pt=1&file=/tv/Sample1/BackUp_Sample1/svc/20170810/91612926_3953868_tv_S_191252_47011/91612926_3953868_tv_S_191252_47011_004.mp4&new=/99/216/x6Xs0P3qQdi7807uOjdJLA.mp4&key=f_3_o9qDVouoDCXTTds2Xfyf3sVS57tK&vid=3953869&uid=1502777043405&t=0.8605906418663568&rb=1
[DEBUG] get_response: http://220.181.61.229/?prot=9&prod=flash&pt=1&file=/tv/Sample1/BackUp_Sample1/svc/20170810/91612926_3953868_tv_S_191252_47011/91612926_3953868_tv_S_191252_47011_005.mp4&new=/205/225/jV4j6xA3SRusTz5UHszCfC.mp4&key=kvPTqBoWCIL8qxme7OSuNEhBFPko34yG&vid=3953869&uid=1502777043469&t=0.27542012339880595&rb=1
[DEBUG] get_response: http://220.181.61.229/?prot=9&prod=flash&pt=1&file=/tv/Sample1/BackUp_Sample1/svc/20170810/91612926_3953868_tv_S_191252_47011/91612926_3953868_tv_S_191252_47011_006.mp4&new=/171/142/usvL52IBTy68InREM6MAtB.mp4&key=q8owe0q9Eyzo9J11Ifs_0gpFMapClU5g&vid=3953869&uid=1502777043547&t=0.5751901018043409&rb=1
[DEBUG] get_response: http://220.181.61.229/?prot=9&prod=flash&pt=1&file=/tv/Sample1/BackUp_Sample1/svc/20170810/91612926_3953868_tv_S_191252_47011/91612926_3953868_tv_S_191252_47011_007.mp4&new=/188/184/j2rirv6eRISYvAeB7vEuRC.mp4&key=o9UNhSNaGnLS3p3bVxO8NOCevgoDmvNT&vid=3953869&uid=1502777043625&t=0.8814157370425667&rb=1
[DEBUG] get_response: http://220.181.61.229/?prot=9&prod=flash&pt=1&file=/tv/Sample1/BackUp_Sample1/svc/20170810/91612926_3953868_tv_S_191252_47011/91612926_3953868_tv_S_191252_47011_008.mp4&new=/124/28/I84w8tm8aCkyRQ5Ug20O5V.mp4&key=M1A81PwV4HrApTFgJnixe35sV0gr8FA4&vid=3953869&uid=1502777043703&t=0.5805406335846984&rb=1
[DEBUG] get_response: http://220.181.61.229/?prot=9&prod=flash&pt=1&file=/tv/Sample1/BackUp_Sample1/svc/20170810/91612926_3953868_tv_S_191252_47011/91612926_3953868_tv_S_191252_47011_009.mp4&new=/52/199/Zqgp96vyp9YjxCXaODuH4I.mp4&key=p3bwsz2-76hYrJ-SgHZlzVbVMeJoWyL1&vid=3953869&uid=1502777043772&t=0.2542083906248933&rb=1
Site:       Sohu.com
Title:      我们的爱第1集
Type:       MPEG-4 video (video/mp4)
Size:       329.2 MiB (345188284 Bytes)

Downloading 我们的爱第1集.mp4 ...
 0.0% (  0.0/329.2MB) ├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤[1/9] [DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
you-get: version 0.4.907, a tiny downloader that scrapes the web.
you-get: ['http://tv.sohu.com/20170810/n600098774.shtml']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/Users/xxx/proj/website/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/xxx/proj/website/you-get/src/you_get/common.py", line 1355, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/xxx/proj/website/you-get/src/you_get/common.py", line 1262, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/xxx/proj/website/you-get/src/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/Users/xxx/proj/website/you-get/src/you_get/common.py", line 1348, in any_download
    m.download(url, **kwargs)
  File "/Users/xxx/proj/website/you-get/src/you_get/extractors/sohu.py", line 75, in sohu_download
    download_urls(urls, title, 'mp4', size, output_dir, refer = url, merge = merge)
  File "/Users/xxx/proj/website/you-get/src/you_get/common.py", line 785, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "/Users/xxx/proj/website/you-get/src/you_get/common.py", line 529, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "/Users/xxx/proj/website/you-get/src/you_get/common.py", line 437, in url_size
    size = response.headers['content-length']
AttributeError: 'NoneType' object has no attribute 'headers'
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> Test with latest develop branch.
> When play segment url by mpv, Got error
> mpv --no-ytdl 'http://61.155.130.203/sohu/v1/TmXCTmw7qEINuT0i8t4C08bGfmvWzK6sNJdseTev5m47fFoGRMNiNw.mp4?k=3qPROp&p=j9lvzSw3opPiqmkU0pXGoSPWXZxIWhoVqTPcWOA4WOdtfGoBoJ2svm1BqVPcNmsdytP&r=TmI20LscWOo70Sc2ZDASqt8IS39J3IFfmvOg2v7fLxUfV8mDVCO04NVRpCIWCgJC7damvW49JLzSkGoKOyOHXIlBy45B6XfDcNuT0i8t4C08bGfmvWzK6sNJdseTev5m47fw&q=OpC3hW7IWhodRDbOwmfCyY2sRY1HfhNt5GeOlGvsvmbcWJesfFNOWJ6SqD2sWhASqF2sY&cip=180.166.53.21'
> [ffmpeg] http: HTTP error 403 CoachingSessionExceededWithoutJS

**Comment by fuzhuo** [comment]
Sorry, seems issues with my network.
