### ISSUE TITLE
优酷：客户端无权播放,201。怎么解决呢？

### ISSUE THREAD

**Issue by turinchlid** [soimort/you-get#2279]
you-get: 客户端无权播放,201
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
'from' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by turinchlid** [comment]
@lki2019  pip3 install这个怎么操作啊？你更新一下就可以了pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip

**Comment by kfcceo** [comment]
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk3OTM1MzM2MA&ccode=0401&client_ip=192.168.1.1&utid=qQcsEvhrME0CAW8RwlZS2jrk&client_ts=1503992230
you-get: 客户端无权播放,201
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjk3OTM1MzM2MA\\=\\=.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1467, in main
  File "src\you_get\common.py", line 1378, in script_main
  File "src\you_get\common.py", line 1180, in download_main
  File "src\you_get\common.py", line 1460, in any_download
  File "src\you_get\extractor.py", line 45, in download_by_url
  File "src\you_get\extractors\youku.py", line 196, in prepare
  File "src\you_get\util\log.py", line 98, in wtf
NameError: name 'exit' is not defined
you-get returned -1
