### ISSUE TITLE
bilibili不能下载

### ISSUE THREAD

**Issue by wasmetqall** [soimort/you-get#2280]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:
第一遍是下面的样子
```
[DEBUG] url_locations: http://www.bilibili.com/video/av10042290/index_35.html
[DEBUG] get_content: http://www.bilibili.com/video/av10042290/index_35.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=16596200&player=1&quality=3&ts=1502938641&sign=e2101b258061d174c95438ff2b3db508
[DEBUG] get_content: http://comment.bilibili.com/16596200.xml
site:                Bilibili
title:               生物信息学：导论与方法(北京大学)(35)
stream:
    - format:        flv
      container:     flv
      size:          22.9 MiB (24022303 bytes)
    # download-with: you-get --format=flv [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 生物信息学：导论与方法(北京大学)(35).flv ...
 0.0% (  0.0/ 22.9MB) ├─────────────────────────────────── ──────┤[1/2] you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://www.bilibili.com/video/av10042290/index_35.html']
Traceback (most recent call last):
  File "c:\program files (x86)\python 3.5\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python 3.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python 3.5\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\extractor.py", line 224, in download
    av=stream_id in self.dash_streams)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 835, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 509, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 416, in url_size
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\program files (x86)\python 3.5\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "c:\program files (x86)\python 3.5\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "c:\program files (x86)\python 3.5\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "c:\program files (x86)\python 3.5\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "c:\program files (x86)\python 3.5\lib\urllib\request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\program files (x86)\python 3.5\lib\urllib\request.py", line 1243, in do_open
    r = h.getresponse()
  File "c:\program files (x86)\python 3.5\lib\http\client.py", line 1174, in getresponse
    response.begin()
  File "c:\program files (x86)\python 3.5\lib\http\client.py", line 304, in begin
    raise UnknownProtocol(version)
http.client.UnknownProtocol: HTTP/0.0
```
之后就都变成了这样
```
[DEBUG] url_locations: http://www.bilibili.com/video/av10042290/index_35.html
[DEBUG] get_content: http://www.bilibili.com/video/av10042290/index_35.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=16596200&player=1&quality=3&ts=1502939216&sign=a8aa379e578c4f23dba3dfa46e5b2532
[DEBUG] get_content: http://comment.bilibili.com/16596200.xml
site:                Bilibili
title:               生物信息学：导论与方法(北京大学)(35)
stream:
    - format:        flv
      container:     flv
      size:          22.9 MiB (24022303 bytes)
    # download-with: you-get --format=flv [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 生物信息学：导论与方法(北京大学)(35).flv ...
 0.0% (  0.0/ 22.9MB) ├─────────────────────────────────── ──────┤[1/2] you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://www.bilibili.com/video/av10042290/index_35.html']
Traceback (most recent call last):
  File "c:\program files (x86)\python 3.5\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python 3.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python 3.5\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\extractor.py", line 224, in download
    av=stream_id in self.dash_streams)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 835, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 509, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 416, in url_size
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "c:\program files (x86)\python 3.5\lib\site-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\program files (x86)\python 3.5\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "c:\program files (x86)\python 3.5\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "c:\program files (x86)\python 3.5\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "c:\program files (x86)\python 3.5\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "c:\program files (x86)\python 3.5\lib\urllib\request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\program files (x86)\python 3.5\lib\urllib\request.py", line 1243, in do_open
    r = h.getresponse()
  File "c:\program files (x86)\python 3.5\lib\http\client.py", line 1174, in getresponse
    response.begin()
  File "c:\program files (x86)\python 3.5\lib\http\client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "c:\program files (x86)\python 3.5\lib\http\client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\program files (x86)\python 3.5\lib\socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

>昨天晚上还可以的，今天上午一来发现不行了
> [舔 :icecream:!]

**Comment by wasmetqall** [comment]
我的也可以用`-i`查看信息但是不能下载啊

**Comment by rosynirvana** [comment]
```
./you-get -d -o /tmp http://www.bilibili.com/video/av10042290/index_35.html
[DEBUG] url_locations: http://www.bilibili.com/video/av10042290/index_35.html
[DEBUG] get_content: http://www.bilibili.com/video/av10042290/index_35.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=16596200&player=1&quality=3&ts=1502939935&sign=bef5b60f0e62993df31c06e5250eed91
[DEBUG] get_content: http://comment.bilibili.com/16596200.xml
site:                Bilibili
title:               生物信息学：导论与方法(北京大学)(35)
stream:
    - format:        flv
      container:     flv
      size:          22.9 MiB (24022303 bytes)
    # download-with: you-get --format=flv [URL]

Downloading 生物信息学：导论与方法(北京大学)(35).flv ...
 0.0% (  0.0/ 22.9MB) ├─────────────────────────────────────────┤[1/2] 
28.4% (  6.5/ 22.9MB) ├████████████─────────────────────────────┤[1/2]   38 kB/s
```

**Comment by wasmetqall** [comment]
不知道为啥又可以下了。。。之前是可以用浏览器打开但是不能用you-get下载，但是啥也没干过了一会又可以下了。。。麻烦啦~
