### ISSUE TITLE
无法录制nico生放视频

### ISSUE THREAD

**Issue by hoshinohikari** [soimort/you-get#2282]
我今天在使用you-get抓取nico上的直播生放视频时，出现了以下错误提示
```
you-get --debug http://live2.nicovideo.jp/watch/lv303558926
User:     zengjieliang1@gmail.com
Password: 
Logging in...
[DEBUG] get_response: http://live2.nicovideo.jp/watch/lv303558926
[DEBUG] get_response: http://flapi.nicovideo.jp/api/getflv?v=lv303558926
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://live2.nicovideo.jp/watch/lv303558926']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1181, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/extractors/nicovideo.py", line 39, in nicovideo_download
    real_url = parse.unquote(r1(r'url=([^&]+)&', api_html))
  File "/usr/lib/python3.6/urllib/parse.py", line 608, in unquote
    if '%' not in string:
TypeError: argument of type 'NoneType' is not iterable
```
貌似所有的nico生放都无法录制，但是nico上的普通视频就可以正常下载

**Comment by lki2019** [comment]
貌似好像就支持视频下载，并不支持直播解析吧

**Comment by lki2019** [comment]
我看了下，
http://live2.nicovideo.jp/watch/lv304989282?ref=top&zroute=index&kind=top_onair&row=1

直播页面是rtmp流，所以you-get目前是不支持此类协议的

rtmp://smilevideo.fc.llnwd.net/smilevideo/s_lv304989282uid=394&h=4504dfb9b3d89cec49bea4e58cf3961d

**Comment by rosynirvana** [comment]
好好读文档
装了rtmpdump就支持rtmp

**Comment by lki2019** [comment]
@rosynirvana 

启动选项：
    -V | --version打印版本并退出。
    -h | --help打印帮助并退出。

干运行选项：（无实际下载）
    -i | --info打印提取的信息。
    -u | --url使用URL打印提取的信息。
         --json以JSON格式打印提取的URL。

下载选项：
    -n | --no-merge不合并视频部分。
         --no-caption不要下载字幕。
                                        （字幕，歌词，danmaku，...）
    -f | - 强制重写存在的文件。
    -F | - 格式<STREAM_ID>将视频格式设置为STREAM_ID。
    -O | --output-filename <FILE>设置输出文件名。
    -o | --output-dir <PATH>设置输出目录。
    -p | - 玩家<PLAYER [OPTIONS]>将提取的URL流式提取到播放器。
    -c | --cookies <COOKIES_FILE>加载cookies.txt或cookies.sqlite。
    -x | --http-proxy <HOST：PORT>使用HTTP代理进行下载。
    -y | --extractor-proxy <HOST：PORT>仅使用HTTP代理进行提取。
         --no-proxy不使用代理。
    -s | --socks-proxy <HOST：PORT>使用SOCKS5代理进行下载。
    -t | --timeout <SECONDS>设置套接字超时。
    -d | --debug显示追溯和其他调试信息。
    -I | - 输入文件从文件中读取非播放列表URL。
    -P | - 密码<PASSWORD>将视频访问密码设置为PASSWORD。



Prerequisites

The following dependencies are required and must be installed separately, unless you are using a pre-built package or chocolatey on Windows:

Python 3
FFmpeg (strongly recommended) or Libav
(Optional) RTMPDump



我只看到了这一条··那具体的命令语法是什么样子的呢？
