### ISSUE TITLE
Bilibili download error

### ISSUE THREAD

**Issue by kobemtl** [soimort/you-get#2285]
Please make sure these boxes are checked before submitting your issue – thank you!

- [X ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [X ] Your `you-get` is up-to-date.
- [X ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ X] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ X] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[DEBUG] url_locations: http://www.bilibili.com/video/av10042290/index_35.html
[DEBUG] get_content: http://www.bilibili.com/video/av10042290/index_35.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=16596200&player=1&quality=3&ts=1502990202&sign=b7f73b7097feddf1f47a5325e190ca2d
[DEBUG] get_content: http://comment.bilibili.com/16596200.xml
site:                Bilibili
title:               生物信息学：导论与方法(北京大学)(35)
stream:
    - format:        flv
      container:     flv
      size:          22.9 MiB (24022303 bytes)
    # download-with: you-get --format=flv [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 生物信息学：导论与方法(北京大学)(35).flv ...
 0.0% (  0.0/ 22.9MB) ├───────────────────────────────────────────────────────────────────────────────────────────┤[1/2] you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av10042290/index_35.html']
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1360, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1267, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1065, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1353, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractor.py", line 227, in download
    av=stream_id in self.dash_streams)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 790, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 531, in url_save
    file_size = url_size(url, faker=faker, headers=tmp_headers)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 433, in url_size
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 344, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> Python 3.5.2
> GEO IP CANADA
> I could download video from youtube

**Comment by kobemtl** [comment]
-i works but not able to download the video.

**Comment by rosynirvana** [comment]
#2280
surprisingly, same URI reported within 24 hours.

**Comment by kobemtl** [comment]
Yes, I read that post. I tried and it failed. Some other links I tried got the same error. 

[DEBUG] url_locations: http://www.bilibili.com/video/av12201458/
[DEBUG] get_content: http://www.bilibili.com/video/av12201458/
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=20109817&player=1&quality=3&ts=1502995948&sign=a0a56c34ed19732125facc941c924e9f
[DEBUG] get_content: http://comment.bilibili.com/20109817.xml
site:                Bilibili
title:               【合集】《阿爺廚房》第二辑 08-17更新第23集【粤语中字】（更新中）
stream:
    - format:        flv
      container:     flv
      size:          6.8 MiB (7122408 bytes)
    # download-with: you-get --format=flv [URL]

Downloading 【合集】《阿爺廚房》第二辑 08-17更新第23集【粤语中字】（更新中）.flv ...
 0.0% (  0.0/  6.8MB) ├───────────────────────────────────────────────────────────────────────────────────────────┤[1/1] you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av12201458/']
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1360, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1267, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1065, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1353, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractor.py", line 227, in download
    av=stream_id in self.dash_streams)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 778, in download_urls
    url_save(url, output_filepath, bar, refer = refer, faker = faker, headers = headers, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 531, in url_save
    file_size = url_size(url, faker=faker, headers=tmp_headers)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 433, in url_size
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 344, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by rosynirvana** [comment]
what urls can you get with flag ```-u``` ?
can you access the hostname in the url?

**Comment by kobemtl** [comment]
you-get -u http://www.bilibili.com/video/av12201458/
site:                Bilibili
title:               【合集】《阿爺廚房》第二辑 08-17更新第23集【粤语中字】（更新中）
stream:
    - format:        flv
      container:     flv
      size:          6.8 MiB (7122408 bytes)
    # download-with: you-get --format=flv [URL]

Real URLs:
http://tx.acgvideo.com/0/1d/20109817-1.flv?txTime=1503005147&platform=pc&txSecret=f715b105b383ae6c7556da98965bd193&oi=1109688920&rate=403293&hfb=b99ffc3c5c68f00a33123bb25f882d5b

**Comment by kobemtl** [comment]
curl http://tx.acgvideo.com
curl: (6) Could not resolve host: tx.acgvideo.com

you are right!!!! damn it. 
how can I solve this problem? Thanks a lot.

**Comment by rosynirvana** [comment]
forwarding DNS query to some remote servers via proxies, changing hosts file to bypass DNS, complaining to your ISP, waiting until it recovers, etc.

**Comment by kobemtl** [comment]
it works fine now. Its first time happened. never thougth about that. thanks again!
