### ISSUE TITLE
you-get搭配shadowsock，YouTube 视频不能下载

### ISSUE THREAD

**Issue by Hongbosherlock** [soimort/you-get#2299]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

C:\Users\del>you-get -s  127.0.0.1:1080 https://www.youtube.com/watch?v=rc34LkKybEA&index=4&list=PLFeBoAy1jcbA6acsjFYz9ufFLqfbiTyWh
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
'index' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'list' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\del>you-get -s 127.0.0.1:1080 -di https://youtu.be/rc34LkKybEA?list=PLFeBoAy1jcbA6acsjFYz9ufFLqfbiTyWh
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=rc34LkKybEA?list=PLFeBoAy1jcbA6acsjFYz9ufFLqfbiTyWh
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://youtu.be/rc34LkKybEA?list=PLFeBoAy1jcbA6acsjFYz9ufFLqfbiTyWh']
Traceback (most recent call last):
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 911, in _send_output
    self.send(msg)
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 854, in send
    self.connect()
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 1237, in connect
    server_hostname=server_hostname)
  File "c:\program files (x86)\python35-32\lib\ssl.py", line 376, in wrap_socket
    _context=self)
  File "c:\program files (x86)\python35-32\lib\ssl.py", line 747, in __init__
    self.do_handshake()
  File "c:\program files (x86)\python35-32\lib\ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "c:\program files (x86)\python35-32\lib\ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\extractors\youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 353, in get_content
    response = urlopen_with_retry(req)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:645)>

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
上面是我用ss+you-get尝试下载Youtube上视频失败。刚开始提示我： Error importing PySocks library, socks proxy ignored.In order to use use socks proxy, please install PySocks.   安装了之后还是有问题。
我的版本已用pip3 install --upgrade you-get更新。另外，我按照其他issues（2244）的提示下载了新的更新，但会提示 failed to progress.
> [OR HAVE SOME :icecream:!]

**Comment by rosynirvana** [comment]
@soimort-bot test https://youtu.be/rc34LkKybEA?list=PLFeBoAy1jcbA6acsjFYz9ufFLqfbiTyWh again

**Comment by lki2019** [comment]
哇机器人好智能，

**Comment by jyuan15** [comment]
you-get|develop⚡🔅 ➡ python you-get -o /sdcard1/movies https://www.youtube.com/watch\?v\=rc34LkKybEA\&index\=4\&list\=PLFeBoAy1jcbA6acsjFYz9ufFLqfbiTyWh
site:                YouTube
title:               Let Her Go《任她離去》 - Boyce Avenue feat. Hannah Trigwell 中文字幕
stream:
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          33.9 MiB (35592209 bytes)
    # download-with: you-get --itag=22 [URL]

Downloading Let Her Go《任她離去》 - Boyce Avenue feat. Hannah Trigwell 中文字幕.mp4 ...
 100% ( 33.9/ 33.9MB) ├████████████████┤[1/1]    5 MB/s

**Comment by Hongbosherlock** [comment]
@jyuan15  How did it works for you?

**Comment by Hongbosherlock** [comment]
Here is another test.

`
C:\Users\del>you-get --debug "https://www.youtube.com/watch?v=hMLf9DhFH8Y"
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=hMLf9DhFH8Y
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=hMLf9DhFH8Y']
Traceback (most recent call last):
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 911, in _send_output
    self.send(msg)
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 854, in send
    self.connect()
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 1229, in connect
    super().connect()
  File "c:\program files (x86)\python35-32\lib\http\client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\program files (x86)\python35-32\lib\socket.py", line 711, in create_connection
    raise err
  File "c:\program files (x86)\python35-32\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\extractors\youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 353, in get_content
    response = urlopen_with_retry(req)
  File "c:\program files (x86)\python35-32\lib\site-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\program files (x86)\python35-32\lib\urllib\request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试 失败。>`

**Comment by fzhqzxguest** [comment]
先安装
pip install PySocks
再运行
you-get -s 127.0.0.1:1080 -di https://www.youtube.com/watch?v=MtKHKPCy0cI

试一下。

**Comment by lki2019** [comment]
C:\Users\Administrator>pip install PySocks
Collecting PySocks
  Downloading PySocks-1.6.7-py3-none-any.whl
Installing collected packages: PySocks
Successfully installed PySocks-1.6.7

C:\Users\Administrator>you-get -s 127.0.0.1:1080 -di https://www.youtube.com/wat
ch?v=MtKHKPCy0cI
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=MtKHKPCy0cI

[DEBUG] Error connecting to SOCKS5 proxy 127.0.0.1:1080 due to: [WinError 10061]
 由于目标计算机积极拒绝，无法连接。
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=MtKHKPCy0cI']
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\socks.py", line 794, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\htt
p\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\htt
p\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\htt
p\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\htt
p\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\htt
p\client.py", line 964, in send
    self.connect()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\htt
p\client.py", line 1392, in connect
    super().connect()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\htt
p\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\soc
ket.py", line 722, in create_connection
    raise err
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\soc
ket.py", line 713, in create_connection
    sock.connect(sa)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\socks.py", line 96, in wrapper
    return function(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\socks.py", line 806, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1080: [Wi
nError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1363, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1270, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1067, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1356, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_i
nfo?video_id={}'.format(self.vid)))
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 372, in get_content
    response = urlopen_with_retry(req)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 346, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 544, in _open
    '_open', req)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Error connecting to SOCKS5 proxy 127.0.0.1
:1080: [WinError 10061] 由于目标计算机积极拒绝，无法连接。>

C:\Users\Administrator>

**Comment by thisisjin** [comment]
你的sock5代理能联通么。   
我用的指令是
you-get -x 127.0.0.1:1080 -o F:\MOVIES --itag=XX 视频链接
可以下载啊。

我是ss跟proxifier都开着，然后proxifier开启了http proxy service

**Comment by ZUOXIN** [comment]
pip3.6 install --upgrade you-get
Collecting you-get
  Downloading you_get-0.4.803-py3-none-any.whl (176kB)
    100% |████████████████████████████████| 184kB 5.9MB/s 
Installing collected packages: you-get
Successfully installed you-get-0.4.803

AND 

you-get -s 127.0.0.1:local_port 'target_url' 

works fine with my shadowsocks.

**Comment by Hongbosherlock** [comment]
我的是电信宽带。proxifier怎么开？ 发自网易邮箱手机版 在2017年09月04日 20:51，Okita 写道： 你的sock5代理能联通么。 我用的指令是 you-get -x 127.0.0.1:1080 -o F:\MOVIES --itag=XX 视频链接 可以下载啊。 我是ss跟proxifier都开着，然后proxifier开启了http proxy service — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
