### ISSUE TITLE
下载斗鱼视频出错

### ISSUE THREAD

**Issue by thinksource** [soimort/you-get#2300]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
G:\>you-get --debug https://v.douyu.com/show/JwLjGvLKX42WmO90
[DEBUG] get_content: http://v.douyu.com/show/JwLjGvLKX42WmO90
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=None
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://v.douyu.com/show/JwLjGvLKX42WmO90']
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\extractors\douyutv.py", line 23, in douyutv_download
    raise ValueError("Server returned error:%s" % server_status)
ValueError: Server returned error:1001
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ x] 您的`you-get`为最新版.
- [ x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
G:\>you-get --debug https://v.douyu.com/show/JwLjGvLKX42WmO90
[DEBUG] get_content: http://v.douyu.com/show/JwLjGvLKX42WmO90
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=None
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://v.douyu.com/show/JwLjGvLKX42WmO90']
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\extractors\douyutv.py", line 23, in douyutv_download
    raise ValueError("Server returned error:%s" % server_status)
ValueError: Server returned error:1001
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 视频可以在浏览器播放，无法用you-get download，我的python是3.6用 anaconda安装包
> [舔 :icecream:!]

**Comment by thinksource** [comment]
I use 
···
pip install --upgrade you-get
···
installed the you-get.
I think you need to upgrade the version on pip system, it is different from the version on github.

**Comment by rosynirvana** [comment]
Only release versions are distributed via PyPI and douyu videos(v.douyu) are supported only in develop branch, not in any release.

**Comment by thinksource** [comment]
Still have some error on：

```
[DEBUG] get_content: https://v.douyu.com/show/JwLjGvLKX42WmO90
[DEBUG] get_content: http://vmobile.douyu.com/video/getInfo?vid=JwLjGvLKX42WmO90
Site:       Douyu Video
Title:      《见面》第三期：量化交易从0到1 上半场
Type:       M3U8 Playlist m3u8
M3U8 Url:   http://vodhls1.douyucdn.cn/live/normal_live-461410r0pgll2kEI--20170805135501/playlist.m3u8?k=850e0ab45193c29a26fdcc6cdcbc672a&t=599f8d49&u=0&ct=h5&vid=1154886&d=

[DEBUG] get_content: http://vodhls1.douyucdn.cn/live/normal_live-461410r0pgll2kEI--20170805135501/playlist.m3u8?k=850e0ab45193c29a26fdcc6cdcbc672a&t=599f8d49&u=0&ct=h5&vid=1154886&d=
Downloading 《见面》第三期：量化交易从0到1 上半场.ts ...
12.8% ( 150.8/1176.3MB) ├█████──────────────────────────────┤[ 83/700]    1 MB/syou-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://v.douyu.com/show/JwLjGvLKX42WmO90']
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "C:\Anaconda3\lib\site-packages\you_get-0.4.803-py3.6.egg\you_get\__main__.py", line 92, in main
  File "C:\Anaconda3\lib\site-packages\you_get-0.4.803-py3.6.egg\you_get\common.py", line 1361, in main
  File "C:\Anaconda3\lib\site-packages\you_get-0.4.803-py3.6.egg\you_get\common.py", line 1268, in script_main
  File "C:\Anaconda3\lib\site-packages\you_get-0.4.803-py3.6.egg\you_get\common.py", line 1066, in download_main
  File "C:\Anaconda3\lib\site-packages\you_get-0.4.803-py3.6.egg\you_get\common.py", line 1354, in any_download
  File "C:\Anaconda3\lib\site-packages\you_get-0.4.803-py3.6.egg\you_get\extractors\douyutv.py", line 40, in douyutv_download
  File "C:\Anaconda3\lib\site-packages\you_get-0.4.803-py3.6.egg\you_get\extractors\douyutv.py", line 36, in douyutv_video_download
  File "C:\Anaconda3\lib\site-packages\you_get-0.4.803-py3.6.egg\you_get\common.py", line 791, in download_urls
  File "C:\Anaconda3\lib\site-packages\you_get-0.4.803-py3.6.egg\you_get\common.py", line 599, in url_save
  File "C:\Anaconda3\lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "C:\Anaconda3\lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "C:\Anaconda3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

is there have some way to continue last download?
since sometime the net work not good enough

**Comment by rosynirvana** [comment]
run the same command again and it will resume

**Comment by jyuan15** [comment]
$ you-get -o /f/movie https://v.douyu.com/show/JwLjGvLKX42WmO90
Site:       Douyu Video
Title:      《见面》第三期：量化交易从0到1 上半场
Type:       M3U8 Playlist m3u8
M3U8 Url:   http://vodhls1.douyucdn.cn/live/normal_live-461410r0pgll2kEI--20170805135501/playlist.m3u8?k=2b08054420ab3d4112b5d1ff7a86a1e7&t=59a4ca17&u=0&ct=h5&vid=1154886&d=

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 《见面》第三期：量化交易从0到1 上半场.ts ...
 100% (1176.3/1176.3MB) ├███████┤[700/700]   11 MB/s
Merging video parts... Merged into 《见面》第三期：量化交易从0到1 上半场.mkv
