### ISSUE TITLE
爱课程地址解析出错

### ISSUE THREAD

**Issue by vtoo** [soimort/you-get#2301]
C:\Users\Administrator>you-get -di http://www.icourses.cn/coursestatic/course_2775.html
[DEBUG] get_content: http://www.icourses.cn/coursestatic/course_2775.html
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://www.icourses.cn/coursestatic/course_2775.html']
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1383, in script_
main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=
json_output, caption=caption)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1181, in downloa
d_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1465, in any_dow
nload
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\icourses.py", line 19,
 in icourses_download
    real_url = icourses_parser.icourses_cn_url_parser(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\icourses.py", line 78,
 in icourses_cn_url_parser
    title_a = match1(html, title_a_patt).strip()
AttributeError: 'NoneType' object has no attribute 'strip'

在下载以上地址的时候，地址解析出错，望解答 （有些获取不到地址）

**Comment by rosynirvana** [comment]
升级到develop branch
然后加上```-l```

**Comment by vtoo** [comment]
@rosynirvana 谢谢，搞定了
