### ISSUE TITLE
bilibili无法下载番剧

### ISSUE THREAD

**Issue by trotsky1997** [soimort/you-get#2304]
https://bangumi.bilibili.com/movie/12044

**Comment by rosynirvana** [comment]
```
./you-get -i https://bangumi.bilibili.com/movie/12044
site:                Bilibili
title:               01
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        flv
      container:     flv
      size:          87.4 MiB (91662481 bytes)
    # download-with: you-get --format=flv [URL]

    - format:        hdmp4
      container:     mp4
      size:          1042.4 MiB (1093004874 bytes)
    # download-with: you-get --format=hdmp4 [URL]

    - format:        mp4
      container:     mp4
      size:          367.0 MiB (384810953 bytes)
    # download-with: you-get --format=mp4 [URL]
```

**Comment by xxf1995** [comment]
cannot download as well..
```
mahuapp2017@instance-1:~/you-get$ ./you-get -i https://bangumi.bilibili.com/movie/12044
site:                Bilibili
title:               YN-010
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        mp4
      container:     mp4
      size:          0.1 MiB (124627 bytes)
    # download-with: you-get --format=mp4 [URL]```

**Comment by xxf1995** [comment]
on mac can't as well
```
➔ you-get -i https://bangumi.bilibili.com/movie/12044
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.```

**Comment by xxf1995** [comment]
I suspect this is probably because I am in US which is blocked for bangumi content...

**Comment by xxf1995** [comment]
even if with proxy still error
```
ubuntu@ip-172-31-15-123:~$  you-get -x 111.13.7.42:81 -i https://bangumi.bilibili.com/movie/12044 --debug
[DEBUG] url_locations: http://bangumi.bilibili.com/movie/12044
[DEBUG] get_content: http://bangumi.bilibili.com/movie/12044
[DEBUG] get_content: http://www.bilibili.com/widget/getPageList?aid=13662970
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=22620491&player=1&quality=4&ts=1504422630&sign=96dfa49495094349fa2e53adef80877a
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://bangumi.bilibili.com/movie/12044']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1181, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/bilibili.py", line 125, in prepare
    self.movie_entry(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/bilibili.py", line 139, in movie_entry
    self.download_by_vid(page_list[0]['cid'], False, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/bilibili.py", line 102, in download_by_vid
    self.parse_bili_xml(api_xml)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/bilibili.py", line 77, in parse_bili_xml
    stream_type, container = self.bilibili_stream_type(urls_list)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/bilibili.py", line 42, in bilibili_stream_type
    url = urls[0]
IndexError: list index out of range```

```<video>
<code>-5009</code>
<message>
<![CDATA[ video is hidden ]]>
</message>
</video>```

**Comment by xxf1995** [comment]
@rosynirvana

**Comment by xxf1995** [comment]
alright...seems to require login

**Comment by xxf1995** [comment]
still can't download with cookies loaded with or without cookies..even with VIP（大会员)

**Comment by xxf1995** [comment]
https://gist.github.com/xxf1995/49d976efae80546c7dce2c1e3d6b8ddd 
cookie file

**Comment by xxf1995** [comment]
I used this command:
```
you-get -c bili_cookie.txt -y proxy.uku.im:443 -i https://bangumi.bilibili.com/movie/12044 --debug
[DEBUG] url_locations: http://bangumi.bilibili.com/movie/12044
[DEBUG] get_content: http://bangumi.bilibili.com/movie/12044
[DEBUG] get_content: http://www.bilibili.com/widget/getPageList?aid=13662970
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=22620491&player=1&quality=4&ts=1504425282&sign=ad1251dbaf4887e7412e8d0d8d25f6eb
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://bangumi.bilibili.com/movie/12044']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1385, in script_main
    download_main(download, download_playlist, args, playlist, extractor_proxy=extractor_proxy, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1181, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 125, in prepare
    self.movie_entry(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 139, in movie_entry
    self.download_by_vid(page_list[0]['cid'], False, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 102, in download_by_vid
    self.parse_bili_xml(api_xml)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 77, in parse_bili_xml
    stream_type, container = self.bilibili_stream_type(urls_list)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 42, in bilibili_stream_type
    url = urls[0]
IndexError: list index out of range```
