### ISSUE TITLE
Can not download through a proxy

### ISSUE THREAD

**Issue by EFanZh** [soimort/you-get#2325]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
sh-4.4$ wget http://www.fsf.org/blogs/rms/20140407-geneva-tedx-talk-free-software-free-society
--2017-09-07 13:19:36--  http://www.fsf.org/blogs/rms/20140407-geneva-tedx-talk-free-software-free-society
Resolving ██████████████████... █████████
Connecting to ██████████████████|█████████|:80... connected.
Proxy request sent, awaiting response... 200 OK
Length: 36314 (35K) [text/html]
Saving to: ‘20140407-geneva-tedx-talk-free-software-free-society.1’

20140407-geneva-tedx-talk-free-software-free-socie 100%[==============================================================================================================>]  35.46K  --.-KB/s    in 0.09s   

2017-09-07 13:19:36 (413 KB/s) - ‘20140407-geneva-tedx-talk-free-software-free-society.1’ saved [36314/36314]

sh-4.4$ you-get -u http://www.fsf.org/blogs/rms/20140407-geneva-tedx-talk-free-software-free-society --debug
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://www.fsf.org/blogs/rms/20140407-geneva-tedx-talk-free-software-free-society']
Traceback (most recent call last):
  File "/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1181, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1464, in any_download
    m, url = url_to_module(url)
  File "/usr/lib/python3.6/site-packages/you_get/common.py", line 1455, in url_to_module
    conn.request("HEAD", video_url, headers=fake_headers)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

I have an `http_proxy` environment variable set to `████████████████████████████`. As you can see in the log above, I can use wget to download the web page, but I can not use you-get to get extract the video url.

I suspect that is because [here](https://github.com/soimort/you-get/blob/develop/src/you_get/common.py#L1347) is not using the proxy.

**Comment by lki2019** [comment]
http://audio-video.gnu.org/video/TEDxGE2014_Stallman05_LQ.webm

**Comment by fzhqzxguest** [comment]
问题先安装pip install PySocks再运行you-get -s 127.0.0.1:1080 -di https://www.youtube.com/watch?v=MtKHKPCy0cI
--

**Comment by rosynirvana** [comment]
和两位说的没关系
主楼描述的是不设置显式代理没办法上网的情况

至于```url_to_module```为什么会直接用```HTTPClient```就不知道了，等作者来改
