### ISSUE TITLE
SSR无法下载youtube视频（CCCAT节点）

### ISSUE THREAD

**Issue by HJH12315** [soimort/you-get#2332]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

C:\Users\lenovo>you-get -o E:\temp -s jp.node.cccat.io:46796 https://www.youtube.com/watch?v=isFCXQ1KdVM --debug
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=isFCXQ1KdVM
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=isFCXQ1KdVM']
Traceback (most recent call last):
  File "E:\Python\Python36-32\lib\site-packages\socks.py", line 813, in connect
    negotiate(self, dest_addr, dest_port)
  File "E:\Python\Python36-32\lib\site-packages\socks.py", line 477, in _negotiate_SOCKS5
    CONNECT, dest_addr)
  File "E:\Python\Python36-32\lib\site-packages\socks.py", line 503, in _SOCKS5_request
    chosen_auth = self._readall(reader, 2)
  File "E:\Python\Python36-32\lib\site-packages\socks.py", line 306, in _readall
    raise GeneralProxyError("Connection closed unexpectedly")
socks.GeneralProxyError: Connection closed unexpectedly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python\Python36-32\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "E:\Python\Python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "E:\Python\Python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "E:\Python\Python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "E:\Python\Python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "E:\Python\Python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "E:\Python\Python36-32\lib\http\client.py", line 1392, in connect
    super().connect()
  File "E:\Python\Python36-32\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "E:\Python\Python36-32\lib\socket.py", line 722, in create_connection
    raise err
  File "E:\Python\Python36-32\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
  File "E:\Python\Python36-32\lib\site-packages\socks.py", line 96, in wrapper
    return function(*args, **kwargs)
  File "E:\Python\Python36-32\lib\site-packages\socks.py", line 817, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: Connection closed unexpectedly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python\Python36-32\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "E:\Python\Python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "E:\Python\Python36-32\lib\site-packages\you_get\common.py", line 1352, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "E:\Python\Python36-32\lib\site-packages\you_get\common.py", line 1259, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "E:\Python\Python36-32\lib\site-packages\you_get\common.py", line 1057, in download_main
    download(url, **kwargs)
  File "E:\Python\Python36-32\lib\site-packages\you_get\common.py", line 1345, in any_download
    m.download(url, **kwargs)
  File "E:\Python\Python36-32\lib\site-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "E:\Python\Python36-32\lib\site-packages\you_get\extractors\youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "E:\Python\Python36-32\lib\site-packages\you_get\common.py", line 367, in get_content
    response = urlopen_with_retry(req)
  File "E:\Python\Python36-32\lib\site-packages\you_get\common.py", line 344, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "E:\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Python\Python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "E:\Python\Python36-32\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "E:\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "E:\Python\Python36-32\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "E:\Python\Python36-32\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Socket error: Connection closed unexpectedly>
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by HJH12315** [comment]
不加-s jp.node.cccat.io:46796 居然就可以下载，加了反而不能。奇怪了。。

**Comment by rosynirvana** [comment]
系统有默认的https代理呗

**Comment by soimort** [comment]
`jp.node.cccat.io:46796` 是远程服务器端口，不是你的本地端口。
