### ISSUE TITLE
acfun 输入从合集进入的视频页面地址无法解析【已解决】

### ISSUE THREAD

**Issue by MarcusVVV** [soimort/you-get#2333]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ yes] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [yes ] Your `you-get` is up-to-date.
- [ yes] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ yes] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ yes] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
   you-get -i 'http://www.acfun.cn/v/ac3956831\#album\=5000632,25689,4,6' --debug
[DEBUG] get_content: http://www.acfun.cn/v/ac3956831\#album\=5000632,25689,4,6
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac3956831\\#album\\=5000632,25689,4,6']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1181, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/acfun.py", line 109, in acfun_download
    html = get_content(url)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 353, in get_content
    response = urlopen_with_retry(req)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
你输入的地址不对
转义或引用只能做一个

```
./you-get -i http://www.acfun.cn/v/ac3956831\#album\=5000632,25689,4,6

Site:       AcFun.tv
Title:      【动画-720P】瑞克与莫蒂 Rick and Morty S03E04【电波字幕组】 - 电波字幕组
Type:       MPEG-4 video (video/mp4)
Size:       293.45 MiB (307702937 Bytes)
```

**Comment by rosynirvana** [comment]
@soimort-bot test 'http://www.acfun.cn/v/ac3956831#album=5000632,25689,4,6' again

**Comment by MarcusVVV** [comment]
啊，不知道为什么从chrome上copy到terminal以后链接多了两个转义符。。手动删掉就好了，谢谢！
