### ISSUE TITLE
下载时无法使用 --format 选择格式

### ISSUE THREAD

**Issue by tommyjiang** [soimort/you-get#2347]
在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get: version 0.4.900, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://v.youku.com/v_show/id_XMjkzMDExMTA0NA==.html?spm=a2hzp.8253869.0.0'], cookies=None, debug=True, extractor_proxy=None, force=False, format='flvhd', help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1270, in script_main
    **extra
TypeError: download_main() got multiple values for keyword argument 'stream_id'
```

上个版本可以，今天更新了发现不能用`--format`选项了。

**Comment by rosynirvana** [comment]
dropping 3510357 should be a cure
