### ISSUE TITLE
腾讯无法下载

### ISSUE THREAD

**Issue by luhy118** [soimort/you-get#2353]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[root@easub-hz4 clip-spider]# you-get --debug https://v.qq.com/x/page/f0548f9324q.html
[DEBUG] get_content: https://v.qq.com/x/page/f0548f9324q.html
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=f0548f9324q
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format=2&vid=f0548f9324q&filename=f0548f9324q.p2.1.mp4&appver=3.2.19.333
you-get: check vid&filename failed
you-get: version 0.4.909, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://v.qq.com/x/page/f0548f9324q.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.909', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1270, in script_main
    **extra
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1072, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/qq.py", line 144, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/qq.py", line 45, in qq_download_by_vid
    print_info(site_info, title, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
因为json里包含的format和fn是不正常的
```
{
    "id": 2,
    "name": "hd",
    "lmt": 0,
    "sb": 1,
    "cname": "高清;(480P)",
    "br": 60,
    "drm": 0,
    "video": 1,
    "fs": 14650372,
    "sl": 1
}
```

而且filename不知道为什么是这样子
```
"fn": "f0548f9324q.mp4"
```

正常的是这样
```
{
    "id": 10712,
    "name": "hd",
    "lmt": 0,
    "sb": 1,
    "cname": "高清;(480P)",
    "br": 60,
    "drm": 0,
    "video": 1,
    "fs": 16211347,
    "sl": 1
}

"fn": "f0539959tnf.p712.mp4"
```

没什么好的方法

链接是
"http://video.dispatch.tc.qq.com/f0548f9324q.mp4?vkey=6B655D9BDF2908D057AFE34266E917353B74ACBCBB2DCFBC7468A178ADB2D9A20ABA3A9285AB1569FDA6CEDC16AB9BA479F13A77BCAF9A0747D2CE561228008C11FE2E7AC005E335355520E899873C0325806D478D11AF7FCD0431843AEB17F0"

**Comment by onlylhf** [comment]
试了一些视频，发现似乎有720P及以上的才会分段，如果直接是480P及其以下的，就不会进行分段了。

**Comment by liangWenPeng** [comment]
https://v.qq.com/x/cover/0880kgnqvyj9crd/m0114w5puld.html 这个网址无法解析，已经更新到0.4.915

**Comment by lanpenzi** [comment]
mini:~ ggp$ you-get -o /Users/ggp/Downloads/you-get --debug https://v.qq.com/x/cover/bhy04pna3ewxzv4/j0016t2xt5x.html
[DEBUG] get_content: https://v.qq.com/x/cover/bhy04pna3ewxzv4/j0016t2xt5x.html
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=j0016t2xt5x
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://v.qq.com/x/cover/bhy04pna3ewxzv4/j0016t2xt5x.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='/Users/ggp/Downloads/you-get', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.915', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/common.py", line 1270, in script_main
    **extra
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/common.py", line 1072, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/extractors/qq.py", line 149, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/extractors/qq.py", line 17, in qq_download_by_vid
    log.wtf(video_json['msg'])
KeyError: 'msg'

**Comment by mengmo** [comment]
```
you-get -di http://v.qq.com/x/cover/qzmn289abuigokp/o055627cs8t.html
D:\PortableApps\Python\lib\runpy.py:125: RuntimeWarning: 'you_get.__main__' found in sys.modules after import of package 'you_get', but prior to execution of 'you_get.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[DEBUG] get_content: http://v.qq.com/x/cover/qzmn289abuigokp/o055627cs8t.html
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=o055627cs8t
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://v.qq.com/x/cover/qzmn289abuigokp/o055627cs8t.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 95, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1270, in script_main
    **extra
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1072, in download_main
    download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractors\qq.py", line 149, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractors\qq.py", line 17, in qq_download_by_vid
    log.wtf(video_json['msg'])
KeyError: 'msg'
```

**Comment by soimort** [comment]
@soimort-bot test this: https://v.qq.com/x/page/f0548f9324q.html

**Comment by mengmo** [comment]
Title 不正确
```
you-get -i http://v.qq.com/x/cover/qzmn289abuigokp/o055627cs8t.html
D:\PortableApps\Python\lib\runpy.py:125: RuntimeWarning: 'you_get.__main__' found in sys.modules after import of package 'you_get', but prior to execution of 'you_get.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Site:       QQ.com
Title:      日语版_13
Type:       MPEG-4 video (video/mp4)
Size:       494.27 MiB (518280859 Bytes)
```
