### ISSUE TITLE
can you support egghead.io for download course?

### ISSUE THREAD

**Issue by thinksource** [soimort/you-get#2361]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
F:\videos>you-get 'https://egghead.io/lessons/react-bootstrap-a-react-application-with-yarn-create-react-app' --debug
you-get: version 0.4.909, a tiny downloader that scrapes the web.
you-get: Namespace(URL=["'https://egghead.io/lessons/react-bootstrap-a-react-application-with-yarn-create-react-app'"], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1270, in script_main
    **extra
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1072, in download_main
    download(url, **kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1354, in any_download
    m, url = url_to_module(url)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1345, in url_to_module
    conn.request("HEAD", video_url, headers=fake_headers)
  File "c:\anaconda3\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\anaconda3\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\anaconda3\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\anaconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\anaconda3\lib\http\client.py", line 964, in send
    self.connect()
  File "c:\anaconda3\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\anaconda3\lib\socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "c:\anaconda3\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
F:\videos>you-get 'https://egghead.io/lessons/react-bootstrap-a-react-application-with-yarn-create-react-app' --debug
you-get: version 0.4.909, a tiny downloader that scrapes the web.
you-get: Namespace(URL=["'https://egghead.io/lessons/react-bootstrap-a-react-application-with-yarn-create-react-app'"], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1270, in script_main
    **extra
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1072, in download_main
    download(url, **kwargs)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1354, in any_download
    m, url = url_to_module(url)
  File "c:\anaconda3\lib\site-packages\you_get\common.py", line 1345, in url_to_module
    conn.request("HEAD", video_url, headers=fake_headers)
  File "c:\anaconda3\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\anaconda3\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\anaconda3\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\anaconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\anaconda3\lib\http\client.py", line 964, in send
    self.connect()
  File "c:\anaconda3\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\anaconda3\lib\socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "c:\anaconda3\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [能加个对egghead.io的支持吗? ]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
in the static page
```js
"media_urls": {
                    "wistia_url": "https://fast.wistia.com/medias/5v6p7b78z7",
                    "hls_url": "https://d2c5owlt6rorc3.cloudfront.net/react-bootstrap-a-react-application-with-yarn-create-react-app-0f7132ef95/react-bootstrap-a-react-application-with-yarn-create-react-app-0f7132ef95.m3u8",
                    "dash_url": "https://d2c5owlt6rorc3.cloudfront.net/react-bootstrap-a-react-application-with-yarn-create-react-app-0f7132ef95/react-bootstrap-a-react-application-with-yarn-create-react-app-0f7132ef95.mpd"
                }
```

**Comment by lki2019** [comment]
看到这个问题我才想起来我那个关于DASH的视频下载
虽然手机浏览器和火狐浏览器可以下载，但是应该是下载下来也无法播放的，

--------------

                    "hls_url": "https://d2c5owlt6rorc3.cloudfront.net/react-bootstrap-a-react-application-with-yarn-create-react-app-0f7132ef95/react-bootstrap-a-react-application-with-yarn-create-react-app-0f7132ef95.m3u8",


这个m3u8地址，打开里面是2个画质的m3u8

下载下来后无法播放，

最后还是挂在怎么播放的问题上了

**Comment by rosynirvana** [comment]
osx quicktime

估计一般的工具没实现EXT-X-MAP
