### ISSUE TITLE
Youtube Live Stream下载问题，求助！

### ISSUE THREAD

**Issue by superxuxin** [soimort/you-get#237]
./you-get https://www.youtube.com/watch?v=rdcvn4W-6xM

Traceback (most recent call last):
  File "./you-get", line 10, in <module>
    main()
  File "/Users/wintwelve/Study/Programming/Python/you-get/src/you_get/downloader/**main**.py", line 81, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/Users/wintwelve/Study/Programming/Python/you-get/src/you_get/common.py", line 819, in script_main
    download_main(download, download_playlist, args, playlist, output_dir, merge, info_only)
  File "/Users/wintwelve/Study/Programming/Python/you-get/src/you_get/common.py", line 729, in download_main
    download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/Users/wintwelve/Study/Programming/Python/you-get/src/you_get/downloader/**main**.py", line 74, in any_download
    m.download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/Users/wintwelve/Study/Programming/Python/you-get/src/you_get/downloader/youtube.py", line 113, in youtube_download
    youtube_download_by_id(id, title=None, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/Users/wintwelve/Study/Programming/Python/you-get/src/you_get/downloader/youtube.py", line 83, in youtube_download_by_id
    for stream in stream_list
  File "/Users/wintwelve/Study/Programming/Python/you-get/src/you_get/downloader/youtube.py", line 83, in <dictcomp>
    for stream in stream_list
KeyError: 'itag'

**Comment by soimort** [comment]
It seems the problem fixed itself.
@soimort-bot test this: https://www.youtube.com/watch?v=rdcvn4W-6xM
