### ISSUE TITLE
执行you-get命令时，发生了错误，以下为--debug的全部输出结果

### ISSUE THREAD

**Issue by wzjjwxy** [soimort/you-get#2376]
you-get --debug -i 'https://v.youku.com/v_show/id_XMzAzMDQwOTA4OA==.html?spm=a2hww.20023042.m_223465.5~5~5~5~5~5~A'
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzAzMDQwOTA4OA==&ccode=0401&client_ip=192.168.1.1&utid=MsZHEo5nC3wCAXt%2BFqaYehoo&client_ts=1505810485
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://v.youku.com/v_show/id_XMzAzMDQwOTA4OA==.html?spm=a2hww.20023042.m_223465.5~5~5~5~5~5~A'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Users/apple/Library/Python/3.6/lib/python/site-packages/you_get-0.4.915-py3.6.egg/you_get/__main__.py", line 92, in main
  File "/Users/apple/Library/Python/3.6/lib/python/site-packages/you_get-0.4.915-py3.6.egg/you_get/common.py", line 1362, in main
  File "/Users/apple/Library/Python/3.6/lib/python/site-packages/you_get-0.4.915-py3.6.egg/you_get/common.py", line 1270, in script_main
  File "/Users/apple/Library/Python/3.6/lib/python/site-packages/you_get-0.4.915-py3.6.egg/you_get/common.py", line 1072, in download_main
  File "/Users/apple/Library/Python/3.6/lib/python/site-packages/you_get-0.4.915-py3.6.egg/you_get/common.py", line 1355, in any_download
  File "/Users/apple/Library/Python/3.6/lib/python/site-packages/you_get-0.4.915-py3.6.egg/you_get/extractors/youku.py", line 295, in youku_download_by_url
  File "/Users/apple/Library/Python/3.6/lib/python/site-packages/you_get-0.4.915-py3.6.egg/you_get/extractor.py", line 46, in download_by_url
  File "/Users/apple/Library/Python/3.6/lib/python/site-packages/you_get-0.4.915-py3.6.egg/you_get/extractors/youku.py", line 155, in prepare
  File "/Users/apple/Library/Python/3.6/lib/python/site-packages/you_get-0.4.915-py3.6.egg/you_get/extractors/youku.py", line 83, in youku_ups
  File "/Users/apple/Library/Python/3.6/lib/python/site-packages/you_get-0.4.915-py3.6.egg/you_get/common.py", line 372, in get_content
  File "/Users/apple/Library/Python/3.6/lib/python/site-packages/you_get-0.4.915-py3.6.egg/you_get/common.py", line 346, in urlopen_with_retry
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>

**Comment by jxon** [comment]
命令行里的单引号换成双引号就不会出错了

**Comment by rosynirvana** [comment]
#2375

**Comment by wzjjwxy** [comment]
@rosynirvana 厉害了！谢谢，问题解决了。
执行这个，就解决了
cd /Applications/Python\ 3.6/
./Install\ Certificates.command

**Comment by wzjjwxy** [comment]
@jxon 换成双引号也不行！谢谢你的热心回复😊😊😊😊
