### ISSUE TITLE
B站无法下载

### ISSUE THREAD

**Issue by 9dtman** [soimort/you-get#2377]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[you-get --debug http://www.bilibili.com/video/av14607501/
[DEBUG] url_locations: http://www.bilibili.com/video/av14607501/
[DEBUG] get_content: http://www.bilibili.com/video/av14607501/
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=23817636&player=1&quality=3&ts=1505911674&sign=fab7ebc1933e732d7b03d80158f33173
[DEBUG] get_content: http://comment.bilibili.com/23817636.xml
site:                Bilibili
title:               音乐大师川井宪次宣布担任《永远的7日之都》游戏配乐
stream:
    - format:        flv
      container:     flv
      size:          15.0 MiB (15687948 bytes)
    # download-with: you-get --format=flv [URL]

Downloading 音乐大师川井宪次宣布担任《永远的7日之都》游戏配乐.flv ...
21.7% (  3.2/ 15.0MB) ├█████████────────────────────────────────┤[1/1]  997  B/s^CTraceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.915', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/common.py", line 1270, in script_main
    **extra
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/common.py", line 1072, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/extractor.py", line 227, in download
    av=stream_id in self.dash_streams)
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/common.py", line 785, in download_urls
    url_save(url, output_filepath, bar, refer = refer, faker = faker, headers = headers, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.915/libexec/lib/python3.6/site-packages/you_get/common.py", line 602, in url_save
    buffer = response.read(1024 * 256)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [每下载3M就停止不同，需要手动暂停或者下载，再继续也是再下载3M就停了。]
> [舔 :icecream:!]

**Comment by 7654** [comment]
同样，感觉又回到以前了，需要Ctrl+C重新开始

**Comment by lki2019** [comment]
https://cn-sdjn-cu-v-04.acgvideo.com/vg0/1/1c/23817636-1.flv?expires=1505983800&platform=pc&ssig=0IbYHgjxgvzkj4ny6JlWrA&oi=974274796&nfa=SqZenuNOtT7n61xgt/NuVg==&dynamic=1&hfa=2079342756&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=


1080p

**Comment by yuansu2016** [comment]
+1
我也遇到了同样的问题

**Comment by lidihuan** [comment]
+1，我也是

**Comment by zhpking** [comment]
+1 前天的时候下着下着就突然出现这个问题，一开始还以为是卡了就没注意，但是今天重新下载的时候就发现视频下载到4M之后速度就降成了几KB

**Comment by Simplici** [comment]
+1, 遇到同样的问题

**Comment by lidihuan** [comment]
https://github.com/soimort/you-get/commit/5019d9d23fac0995c33f7b2ca5818840ed3a2156 参照这个例子，在src/you_get/extractors/bilibili.py的107行添上socket.setdefaulttimeout(1)，就可以重新下载B站视频了（ps：感谢鸥姐~~~）

**Comment by gonejack** [comment]
dirty hack(笑)
