### ISSUE TITLE
Uyntv.com and kzntv.com  Support

### ISSUE THREAD

**Issue by dkl3** [soimort/you-get#2381]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ x] Your `you-get` is up-to-date.
- [x ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```

UYNTV:

~⟫ you-get "http://www.uyntv.com/xiyou/video/index.shtml?url=v-04eda3c1-acc7-4a08-90d4-813af1fbb86e.html" --debug
[DEBUG] get_head: http://www.uyntv.com/xiyou/video/index.shtml?url=v-04eda3c1-acc7-4a08-90d4-813af1fbb86e.html
[DEBUG] get_content: http://www.uyntv.com/xiyou/video/index.shtml?url=v-04eda3c1-acc7-4a08-90d4-813af1fbb86e.html
[DEBUG] get_response: http://www.uyntv.com/xiyou/video/index.shtml?url=v-04eda3c1-acc7-4a08-90d4-813af1fbb86e.html
~⟫

KZNTV:

you-get   http://kzntv.cctv.com/xiyou/video/index.shtml?url=v-2bb68831-886d-45a3-b7a8-e8f921ebf2b7.html --debug
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://kzntv.cctv.com/xiyou/video/index.shtml?url=v-2bb68831-886d-45a3-b7a8-e8f921ebf2b7.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1270, in script_main
    **extra
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1072, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/cntv.py", line 62, in cntv_download
    raise NotImplementedError(url)
NotImplementedError: http://kzntv.cctv.com/xiyou/video/index.shtml?url=v-2bb68831-886d-45a3-b7a8-e8f921ebf2b7.html

```
A friend told me about these two sites, and apparently they are Uyghur tv station websites with upload support. Here's the output when i try and run both.

**Comment by dkl3** [comment]
Both sites seem to relate to CCTV--or specifically Xiyou (http://xiyou.cctv.com). Here's an example video and attempt at scraping:

:~⟫ you-get http://xiyou.cctv.com/v-db047e7a-f8be-4132-a7bb-60528838507e.html --debug
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://xiyou.cctv.com/v-db047e7a-f8be-4132-a7bb-60528838507e.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1270, in script_main
    **extra
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1072, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/cntv.py", line 62, in cntv_download
    raise NotImplementedError(url)
NotImplementedError: http://xiyou.cctv.com/v-db047e7a-f8be-4132-a7bb-60528838507e.html

**Comment by lki2019** [comment]
http://www.uyntv.com/xiyou/video/index.shtml?url=v-04eda3c1-acc7-4a08-90d4-813af1fbb86e.html


http://110.19.182.24/vod.cntv.lxdns.com/flash/mp4video62/TMS/xiyou/video1/2017/09/21/10/04eda3c1-acc7-4a08-90d4-813af1fbb86e_041832_001.mp4?wshc_tag=0&wsts_tag=59c5154f&wsid_tag=3a1240ec&wsiphost=ipdbm

**Comment by lki2019** [comment]
http://kzntv.cctv.com/xiyou/video/index.shtml?url=v-2bb68831-886d-45a3-b7a8-e8f921ebf2b7.html


http://110.19.205.60/v.cctv.com/flash/mp4video58/TMS/xiyou/video1/2017/02/08/10/2bb68831-886d-45a3-b7a8-e8f921ebf2b7_041832_001.mp4?wsiphost=local
