### ISSUE TITLE
B站视频无法下载

### ISSUE THREAD

**Issue by Travical** [soimort/you-get#2393]
[DEBUG] url_locations: https://www.bilibili.com/video/av7299271/index_2.html#page=2
[DEBUG] get_content: http://www.bilibili.com/video/av7299271/index_2.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=11931682&player=1&quality=3&ts=1506244685&sign=84b3db7ad22dac94feb3c8b1060ce948
[DEBUG] get_content: http://comment.bilibili.com/11931682.xml
site:                Bilibili
title:               韩顺平老师-Java从入门到精通[全](2)
stream:
    - format:        flv
      container:     flv
      size:          142.0 MiB (148906474 bytes)
    # download-with: you-get --format=flv [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 韩顺平老师-Java从入门到精通(全)(2).flv ...
 0.0% (  0.0/142.0MB) ├─────────────────────────────────────────┤[1/9] you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/av7299271/index_2.html#page=2'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\program files (x86)\python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\program files (x86)\python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\program files (x86)\python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\program files (x86)\python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\program files (x86)\python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "c:\program files (x86)\python36-32\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\program files (x86)\python36-32\lib\socket.py", line 722, in create_connection
    raise err
  File "c:\program files (x86)\python36-32\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\you_get\common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\you_get\common.py", line 1270, in script_main
    **extra
  File "c:\program files (x86)\python36-32\lib\site-packages\you_get\common.py", line 1072, in download_main
    download(url, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\you_get\common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\you_get\extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\you_get\extractor.py", line 227, in download
    av=stream_id in self.dash_streams)
  File "c:\program files (x86)\python36-32\lib\site-packages\you_get\common.py", line 797, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\you_get\common.py", line 533, in url_save
    file_size = url_size(url, faker=faker, headers=tmp_headers)
  File "c:\program files (x86)\python36-32\lib\site-packages\you_get\common.py", line 435, in url_size
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "c:\program files (x86)\python36-32\lib\site-packages\you_get\common.py", line 346, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\program files (x86)\python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\program files (x86)\python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\program files (x86)\python36-32\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\program files (x86)\python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\program files (x86)\python36-32\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\program files (x86)\python36-32\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
> [舔 :icecream:!]

**Comment by BenjaminGao** [comment]
我测试可以下载

**Comment by Adek06** [comment]
我这里下载到3MB就停止了

**Comment by liwufan** [comment]
我也可以下载

**Comment by cji03** [comment]
same problem with @Adek06 , I tried quite a few videos and get the same problem: they all stuck at exactly 3MB, dont know why :(.  location: New York.

**Comment by xmoiduts** [comment]
Same problem with @Adek06 and @cji03 .Seems that bilibili has changed their speed limit strategy from 5MB to 3MB of unlimited downloading. And sending ctrl+c to console didn't work.

you-get 0.4.915, windows 10,python3.

**Comment by gonejack** [comment]
我这里是4MB，只能ctrl+c停掉再enter命令接着下，时间复杂度=视频体积 in MB * 4 / 网速;

**Comment by xmoiduts** [comment]
按照 https://github.com/soimort/you-get/commit/5019d9d23fac0995c33f7b2ca5818840ed3a2156 的方法加了一行代码，指定socket的超时为1s，可以有效为b站下载功能+1s。
看之前的讨论，好像还应该加上&ref这种参数来缓解限速，可是在bilibili。py中并没有看到。
