### ISSUE TITLE
Facebook videos download bug - IndexError: list index out of range

### ISSUE THREAD

**Issue by Mayorc1978** [soimort/you-get#2395]
I'm trying to get you-get to work with facebook, but it seems buggy, **I also cannot select video quality** (like I can with youtube), and have trouble to download live feeds (sometimes even when finished streaming, sometimes not).
Would also like to know how to use the vlc redirect feature in Windows 7 **-p vlc command doesn't seem to work.**
Also **how do I get to download a video if it's a friend private video** (which requires me to login to facebook with my credentials, I only see a password in the small guide, but (not tested) don't think can be enough for that.

Using latest windows compiled version, here is the error I get with facebook:

**IndexError bug (notice how the bug happens even when I ask for info only):**

```
H:\---SECURITY---\---Video Downloader - CMLINE>you-get.exe --debug --info https://www.facebook.com/CallofDutyit/videos/352705635179980/
[DEBUG] get_response: https://www.facebook.com/CallofDutyit/videos/352705635179980/
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.facebook.com/CallofDutyit/videos/352705635179980/'], cookies=None, debug=True, extractor_proxy=None, force=False, format=No
ne, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_fil
ename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1362, in main
  File "src\you_get\common.py", line 1270, in script_main
  File "src\you_get\common.py", line 1072, in download_main
  File "src\you_get\common.py", line 1355, in any_download
  File "src\you_get\extractors\facebook.py", line 26, in facebook_download
IndexError: list index out of range
you-get returned -1

```

**VLC bug on a downloading video:**

```
H:\---SECURITY---\---Video Downloader - CMLINE>you-get.exe --debug https://www.facebook.com/montemagno/videos/1500492970018515/ -p vlc
[DEBUG] get_response: https://www.facebook.com/montemagno/videos/1500492970018515/
[DEBUG] url_info: https://video-mxp1-1.xx.fbcdn.net/v/t43.1792-2/17638296_278794129240653_1032268077896564736_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=89ac
eca7816b6f64214a3e981dbfca42&oe=59C96E45
Site:       Facebook.com
Title:      Come fa Fiorello a intrattenere e tenere... - Marco Monty Montemagno
Type:       MPEG-4 video (video/mp4)
Size:       33.58 MiB (35207957 Bytes)

you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.facebook.com/montemagno/videos/1500492970018515/'], cookies=None, debug=True, extractor_proxy=None, force=False, format=Non
e, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_fil
ename=None, password=None, player='vlc', playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1362, in main
  File "src\you_get\common.py", line 1270, in script_main
  File "src\you_get\common.py", line 1072, in download_main
  File "src\you_get\common.py", line 1355, in any_download
  File "src\you_get\extractors\facebook.py", line 31, in facebook_download
  File "src\you_get\common.py", line 757, in download_urls
  File "src\you_get\common.py", line 252, in launch_player
  File "subprocess.py", line 560, in call
  File "subprocess.py", line 950, in __init__
  File "subprocess.py", line 1220, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
you-get returned -1

```

**Comment by soimort** [comment]
The first video needs a login (cookie).

For the second video: you need to make sure you can invoke `vlc` from your Windows command line.
