### ISSUE TITLE
B站视频下载报错

### ISSUE THREAD

**Issue by zhpking** [soimort/you-get#2404]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
sudo /usr/bin/python3 /opt/htdocs2/you-get-develop/you-get -d http://www.bilibili.com/video/av14684265/
[sudo] peng 的密码： 
[DEBUG] url_locations: http://www.bilibili.com/video/av14684265/
[DEBUG] get_content: http://www.bilibili.com/video/av14684265/
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=23937966&player=1&quality=3&ts=1506674530&sign=b75b94ebaa0b4395816f973483a3b70d
[DEBUG] get_content: http://comment.bilibili.com/23937966.xml
site:                Bilibili
title:               王老菊教你皮影进化
stream:
    - format:        flv
      container:     flv
      size:          559.6 MiB (586783908 bytes)
    # download-with: you-get --format=flv [URL]

Downloading 王老菊教你皮影进化.flv ...
28.0% (156.5/559.6MB) ├████████████─────────────────────────────┤[2/6]  286 kB/syou-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.bilibili.com/video/av14684265/'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/htdocs2/you-get-develop/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/opt/htdocs2/you-get-develop/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/opt/htdocs2/you-get-develop/src/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/opt/htdocs2/you-get-develop/src/you_get/common.py", line 1270, in script_main
    **extra
  File "/opt/htdocs2/you-get-develop/src/you_get/common.py", line 1072, in download_main
    download(url, **kwargs)
  File "/opt/htdocs2/you-get-develop/src/you_get/common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "/opt/htdocs2/you-get-develop/src/you_get/extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "/opt/htdocs2/you-get-develop/src/you_get/extractor.py", line 228, in download
    av=stream_id in self.dash_streams)
  File "/opt/htdocs2/you-get-develop/src/you_get/common.py", line 797, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "/opt/htdocs2/you-get-develop/src/you_get/common.py", line 610, in url_save
    response = urlopen_with_retry(request.Request(url, headers=tmp_headers))
  File "/opt/htdocs2/you-get-develop/src/you_get/common.py", line 346, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by conan06** [comment]
我也遇到这个问题，卡在0.5%就不再动了…

**Comment by zhuoquanzhou** [comment]
一样的，每次中断之后再重新敲语句又能下载一点
