### ISSUE TITLE
having trouble downloading videos from icourse.cn

### ISSUE THREAD

**Issue by plsshutup** [soimort/you-get#2410]
I don't know how to solve this... I already tried run the -d command but it didn't work...

>you-get -d http://www.icourses.cn/jpk/viewCharacterDetail.action?courseId=3008&
characId=20958
[DEBUG] get_content: http://www.icourses.cn/jpk/viewCharacterDetail.action?cours
eId=3008
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.icourses.cn/jpk/viewCharacterDetail.action?c
ourseId=3008'], cookies=None, debug=True, extractor_proxy=None, force=False, for
mat=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, j
son=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', out
put_filename=None, password=None, player=None, playlist=False, socks_proxy=None,
 stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1362, in main
  File "src\you_get\common.py", line 1270, in script_main
  File "src\you_get\common.py", line 1072, in download_main
  File "src\you_get\common.py", line 1355, in any_download
  File "src\you_get\extractors\icourses.py", line 23, in icourses_download
  File "src\you_get\extractors\icourses.py", line 237, in basic_extract
  File "src\you_get\extractors\icourses.py", line 199, in get_title
AttributeError: 'NoneType' object has no attribute 'strip'
you-get returned -1
'characId' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by plsshutup** [comment]
already solved this problem...
for those having the same problem
plz check https://github.com/soimort/you-get/wiki/Window-Console-Problems

我的妈呀我为啥要学大家说英语

嘤嘤嘤 没有学过写代码的人看这些真的好费劲
