### ISSUE TITLE
Bilibili 合集下載總是錯誤

### ISSUE THREAD

**Issue by kobemtl** [soimort/you-get#2424]
在提交前，请确保您已经检查了以下内容!

- [X] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [X] 您的`you-get`为最新版.
- [X] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [X] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [X] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get -di http://www.bilibili.com/video/av10045596
[DEBUG] url_locations: http://www.bilibili.com/video/av10045596
[DEBUG] get_content: http://www.bilibili.com/video/av10045596/
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.bilibili.com/video/av10045596'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.915', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/__main__.py", line 92, in main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/common.py", line 1363, in main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/common.py", line 1271, in script_main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/common.py", line 1073, in download_main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/common.py", line 1356, in any_download
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/extractor.py", line 46, in download_by_url
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/extractors/bilibili.py", line 137, in prepare
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/extractors/bilibili.py", line 157, in entry
AttributeError: 'NoneType' object has no attribute 'group'

you-get -di -x 111.13.7.120:80 http://www.bilibili.com/video/av10045596
[DEBUG] url_locations: http://www.bilibili.com/video/av10045596
[DEBUG] get_content: http://www.bilibili.com/video/av10045596/
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.bilibili.com/video/av10045596'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy='111.13.7.120:80', info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.915', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/__main__.py", line 92, in main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/common.py", line 1363, in main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/common.py", line 1271, in script_main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/common.py", line 1073, in download_main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/common.py", line 1356, in any_download
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/extractor.py", line 46, in download_by_url
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/extractors/bilibili.py", line 137, in prepare
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/extractors/bilibili.py", line 157, in entry
AttributeError: 'NoneType' object has no attribute 'group'

```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 下載單一視頻沒問題，但當地址是合集時總是出錯，請幫幫忙，謝謝了
> [舔 :icecream:!]

**Comment by redstoneleo** [comment]
```
C:\Users\i>you-get -u -d https://www.bilibili.com/watchlater/#/av2679094/p1
[DEBUG] url_locations: https://www.bilibili.com/watchlater/#/av2679094/p1
[DEBUG] get_content: https://www.bilibili.com/watchlater/#/av2679094/p1
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/watchlater/#/av2679094/p1'], c
ookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=Fa
lse, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_cap
tion=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None
, password=None, player=None, playlist=False, socks_proxy=None, stream=None, tim
eout=600, url=True, version=False)
Traceback (most recent call last):
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\Scripts\you-get-scr
ipt.py", line 11, in <module>
    load_entry_point('you-get==0.4.915', 'console_scripts', 'you-get')()
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\common.py", line 1363, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\common.py", line 1271, in script_main
    **extra
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\common.py", line 1073, in download_main
    download(url, **kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\common.py", line 1356, in any_download
    m.download(url, **kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\extractors\bilibili.py", line 137, in prepare
    self.entry(**kwargs)
  File "c:\users\i\appdata\local\programs\python\python35-32\lib\site-packages\y
ou_get\extractors\bilibili.py", line 157, in entry
    cid = re.search(r'cid=(\d+)', self.page).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

C:\Users\i>

```

**Comment by soimort** [comment]
@kobemtl 這個視頻需要加載cookie。

@redstoneleo Fixed by 4b56e46.

**Comment by kobemtl** [comment]
@soimort 太謝謝了。用cookie就可以了。請問在何種情況下才需要加載cookie？

**Comment by cnbeining** [comment]
会员的世界
