### ISSUE TITLE
解析爱课程网址出错了？

### ISSUE THREAD

**Issue by TELIlzr** [soimort/you-get#2433]
这个是怎么了
![image](https://user-images.githubusercontent.com/32827490/31593659-8859ca5a-b262-11e7-8aff-e4d8a895dae3.png)

**Comment by TELIlzr** [comment]
![image](https://user-images.githubusercontent.com/32827490/31594320-c872abda-b266-11e7-80f0-4939db81e48f.png)

**Comment by lki2019** [comment]
失效了，爱课程本身不在支持列表··之前是有大神更新了下，现在没有开发者更新了

**Comment by lki2019** [comment]
C:\Users\Administrator>you-get http://www.icourses.cn/jpk/viewCharacterDetail.ac
tion?sectionId=71517&courseId=6955
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
'courseId' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by lki2019** [comment]
这种类型的 不行

**Comment by aiwonanjing** [comment]
显示
[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=1053433&courseId=2933
[DEBUG] get_content: http://www.icourses.cn/jpk/getResPlayInfo.action?IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&uuid=1053433&other=&v=1508420266570
[DEBUG] get_content: http://media1.icourses.cn:8080/process7/campus//ssl/host.shtml
[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=6343976
you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.icourses.cn/jpk/viewCharacterDetail.action?courseId=2933&characId=52575'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=True, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "d:\python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "d:\python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "d:\python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "d:\python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "d:\python36\lib\http\client.py", line 964, in send
    self.connect()
  File "d:\python36\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "d:\python36\lib\socket.py", line 724, in create_connection
    raise err
  File "d:\python36\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\python36\lib\site-packages\you_get\common.py", line 1363, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "d:\python36\lib\site-packages\you_get\common.py", line 1271, in script_main
    **extra
  File "d:\python36\lib\site-packages\you_get\common.py", line 1071, in download_main
    download_playlist(url, **kwargs)
  File "d:\python36\lib\site-packages\you_get\common.py", line 1360, in any_download_playlist
    m.download_playlist(url, **kwargs)
  File "d:\python36\lib\site-packages\you_get\extractors\icourses.py", line 118, in icourses_playlist_download
    icourses_download(video_url, output_dir=output_dir, **kwargs)
  File "d:\python36\lib\site-packages\you_get\extractors\icourses.py", line 29, in icourses_download
    size_url = icourses_parser.generate_url(0)
  File "d:\python36\lib\site-packages\you_get\extractors\icourses.py", line 285, in generate_url
    return self.update_url(received)
  File "d:\python36\lib\site-packages\you_get\extractors\icourses.py", line 254, in update_url
    ssl_ts, sign = self.get_sign(self.media_url)
  File "d:\python36\lib\site-packages\you_get\extractors\icourses.py", line 290, in get_sign
    ssl_callback = get_content('http://{}/ssl/ssl.shtml?r={}'.format(media_host, ran)).split(',')
  File "d:\python36\lib\site-packages\you_get\common.py", line 373, in get_content
    response = urlopen_with_retry(req)
  File "d:\python36\lib\site-packages\you_get\common.py", line 347, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "d:\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "d:\python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "d:\python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "d:\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "d:\python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "d:\python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
我想下一套课程总是在第三节课之后没多少显示这个。
