### ISSUE TITLE
Bilibili 下载失败

### ISSUE THREAD

**Issue by kang0024** [soimort/you-get#2443]
已更新至最新版本：

you-get -d https://www.bilibili.com/video/av6772741/#page=2
[DEBUG] url_locations: https://www.bilibili.com/video/av6772741/#page=2
you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/av6772741/#page=2'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:733: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kang0024\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1363, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1271, in script_main
    **extra
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1073, in download_main
    download(url, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1356, in any_download
    m.download(url, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\bilibili.py", line 115, in prepare
    self.url = url_locations([self.url])[0]
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 523, in url_locations
    response = urlopen_with_retry(request.Request(url))
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 347, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error _ssl.c:733: The handshake operation timed out>

Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by kang0024** [comment]
加载cookie之后能下载，只是速度很低。过段时间会降到1kB/s

**Comment by lki2019** [comment]
:\Users\Administrator>you-get https://www.bilibili.com/video/av6772741/index_
tml#page=2
t seems that your ffmpeg is a nightly build.
lease switch to the latest stable if merging failed.
ite:                Bilibili
itle:               【Good Show】日本人妻在远方【配音中字】(2)
tream:
   - format:        flv
     container:     flv
     size:          366.6 MiB (384417436 bytes)
   # download-with: you-get --format=flv [URL]

ownloading 【Good Show】日本人妻在远方【配音中字】(2).flv ...
0.0% (  0.0/366.6MB) ├───────────────────────────

**Comment by lki2019** [comment]
没有问题，每秒4-6M的速度

**Comment by einverne** [comment]
一样没有问题，检查一下是不是网络问题。

**Comment by YuhaoTang** [comment]
楼主的视频没遇到问题，但是我下载番剧都下不了了，加不加https都不行，比如：
you-get -di http://bangumi.bilibili.com/anime/5394/play#115603
you-get -di https://bangumi.bilibili.com/anime/5394/play#115603
https的log和楼主是一样的，http稍有不同，但也是死在socket.timeout: timed out上面，具体就不贴出来了。另外我也试了加载cookie，没有任何效果。

**Comment by Z4HD** [comment]
@YuhaoTang
你可能需要使用番剧对应的Av号（带avxxxxxx的那种）链接下载
，直接访问番剧Av号链接会被重定向至番剧链接。

**陈 睿 死 妈**

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的黑色高级手机发送_

**Comment by YuhaoTang** [comment]
直接用av号也失败了
you-get -di https://www.bilibili.com/video/av15321105/

**Comment by Z4HD** [comment]
@YuhaoTang
```
$ you-get -di https://www.bilibili.com/video/av1532110
[DEBUG] url_locations: https://www.bilibili.com/video/av15321105/
[DEBUG] get_content: https://bangumi.bilibili.com/anime/5394/play#115603
[DEBUG] get_content: http://bangumi.bilibili.com/jsonp/seasoninfo/5394.ver?callback=seasonListCallback&jsonp=jsonp&_=1509206392821
[DEBUG] get_content: http://bangumi.bilibili.com/web_api/episode/115603.json
[DEBUG] get_content: http://bangumi.bilibili.com/player/web_api/playurl?cid=24939798&module=bangumi&player=1&quality=4&ts=1509206393&sign=36ecdde2ce7a10b6e9b6198848513098
[DEBUG] get_content: http://bangumi.bilibili.com/player/web_api/playurl?cid=24939798&module=bangumi&player=1&quality=3&ts=1509206393&sign=e8dd3d22287735f2cafbcbdc96af923b
[DEBUG] get_content: http://bangumi.bilibili.com/player/web_api/playurl?cid=24939798&module=bangumi&player=1&quality=2&ts=1509206393&sign=077988a4e707d953981d98e8a7e9018c
[DEBUG] get_content: http://bangumi.bilibili.com/player/web_api/playurl?cid=24939798&module=bangumi&player=1&quality=1&ts=1509206393&sign=e1933b12e09fd36224c93e505181cae8
site: Bilibili
title: 我的英雄学院 [1 绿谷出久:原点]
streams: # Available quality and codecs
[ DEFAULT ] _________________________________
- format: flv
container: flv
size: 358.19999999999999 MiB (375549406 bytes)
# download-with: you-get --format=flv [URL]

- format: mp4
container: mp4
size: 84.200000000000003 MiB (88293906 bytes)
# download-with: you-get --format=mp4 [URL]
```

不知为何不加-d就会出错，很谜。

**Comment by cnbeining** [comment]
这是SSL握手失败了。

但是为什么呢 你开代理了？还是Python有坑？我记得2.6的SSL有坑但是3.6应该没有啊

**Comment by YuhaoTang** [comment]
VPN的问题，版权番要挂回国内，我再研究研究。
