### ISSUE TITLE
Can't download kugou playlist

### ISSUE THREAD

**Issue by DiegoWang51** [soimort/you-get#2447]
I want to download some music from http://www.kugou.com/yy/special/single/21154.html, but the following error occurred:
```
Diego-Wang:~ wlt$ you-get -o ~/Documents/YouGetDown/SecretGardenK -l http://www.kugou.com/yy/special/single/21154.html -d
[DEBUG] get_response: http://www.kugou.com/yy/special/single/21154.html
[DEBUG] get_response: http://trackercdn.kugou.com/i/?pid=6&key=cca1d06a0d9b0b5af76554ff7fb8901f&acceptMp3=1&cmd=4&hash=D4E7DCFF5453169EBE2FCDFC3FBA3E11
you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.kugou.com/yy/special/single/21154.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='/Users/wlt/Documents/YouGetDown/SecretGardenK', output_filename=None, password=None, player=None, playlist=True, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/Users/wlt/anaconda/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.939', 'console_scripts', 'you-get')()
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/__main__.py", line 92, in main
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/common.py", line 1368, in main
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/common.py", line 1276, in script_main
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/common.py", line 1076, in download_main
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/common.py", line 1365, in any_download_playlist
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/extractors/kugou.py", line 47, in kugou_download_playlist
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/extractors/kugou.py", line 36, in kugou_download_by_hash
KeyError: 'url'
```
I tried to download audios in #358, but **only the first audio** is downloaded successfully, and here's the traceback:
```
Diego-Wang:~ wlt$ you-get -o ~/Documents/YouGetDown/SecretGardenK -l http://www.kugou.com/yy/album/single/537952.html -d
[DEBUG] get_response: http://www.kugou.com/yy/album/single/537952.html
[DEBUG] get_response: http://trackercdn.kugou.com/i/?pid=6&key=d9dcd1af0bccf4b5ced1f0fe5f8beee5&acceptMp3=1&cmd=4&hash=B0CE85B55F766D8562AD86F1D7F9C9DB
[DEBUG] url_info: http://fs.w.kugou.com/201710222103/7fed22ab74f656eef0adfeb9b5f525f6/G014/M0A/01/15/Tg0DAFULeQuAD4oKAEkF3_Wg_1U418.mp3
Site:       kugou.com
Title:      μ's - KiRa-KiRa Sensation!
Type:       MP3 (audio/mpeg)
Size:       4.56 MiB (4785631 Bytes)

Downloading μ's - KiRa-KiRa Sensation!.mp3 ...
 100% (  4.6/  4.6MB) ├███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[1/1]    3 MB/s

[DEBUG] get_response: http://trackercdn.kugou.com/i/?pid=6&key=04f82cf34e360bb5f265dcda06d99c92&acceptMp3=1&cmd=4&hash=8CF193E02A4326E05240AD8DA111DAAF
you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.kugou.com/yy/album/single/537952.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='/Users/wlt/Documents/YouGetDown/SecretGardenK', output_filename=None, password=None, player=None, playlist=True, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/Users/wlt/anaconda/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.939', 'console_scripts', 'you-get')()
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/__main__.py", line 92, in main
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/common.py", line 1368, in main
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/common.py", line 1276, in script_main
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/common.py", line 1076, in download_main
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/common.py", line 1365, in any_download_playlist
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/extractors/kugou.py", line 47, in kugou_download_playlist
  File "/Users/wlt/.local/lib/python3.6/site-packages/you_get-0.4.939-py3.6.egg/you_get/extractors/kugou.py", line 36, in kugou_download_by_hash
KeyError: 'url'
```
*Any helps are appreciated ~*

**Comment by DDDDh** [comment]
I found that right click the playtools and check the source code or '审查元素‘ on webpage can found the download link

`<audio class="music" id="myAudio" src="http://fs.w.kugou.com/201711271112/00fe3407fa1fee957caea5c514adf18b/G002/M05/16/17/ooYBAFS60VyAbMfEABXrbvyaPOg288.mp3" preload="auto">
</audio>`

then you can download directly on Thunder or something else tools.
