### ISSUE TITLE
you-get download Youku video file, and can not use the --debug option. please help me.

### ISSUE THREAD

**Issue by yywf** [soimort/you-get#2448]
root@H:/home/video# you-get -v
usage: you-get [OPTION]... URL...
you-get: error: unrecognized arguments: -v
root@H:/home/video# you-get -V
you-get: version 0.4.939, a tiny downloader that scrapes the web.
root@H:/home/video# you-get http://v.youku.com/v_show/id_XMjk4ODAyMzIyOA\=\=.html\?spm\=a2h0k.8191407.0.0\&from\=s1.8-3-1.1 --debug
you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://v.youku.com/v_show/id_XMjk4ODAyMzIyOA==.html?spm=a2h0k.8191407.0.0&from=s1.8-3-1.1'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1363, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1271, in script_main
    **extra
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1073, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1356, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/youku.py", line 304, in youku_download_by_url
    Youku().download_by_url(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/youku.py", line 162, in prepare
    self.utid = fetch_cna()
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/youku.py", line 27, in fetch_cna
    req = urllib.request.urlopen(url)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
root@H:/home/video# you-get http://v.youku.com/v_show/id_XMjk4ODAyMzIyOA\=\=.html\?spm\=a2h0k.8191407.0.0\&from\=s1.8-3-1.1
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
root@H:/home/video#

**Comment by einverne** [comment]
It is OK here. Try to check your DNS settings. It seems you-get `Temporary failure in name resolution`.

Show your `nslookup www.youku.com` result here.

**Comment by yywf** [comment]
@einverne  thank you, it is my dns server error.
