### ISSUE TITLE
MacOS High Sierra: Can't download youtube videos

### ISSUE THREAD

**Issue by dev-shi** [soimort/you-get#2450]
I'm Using MacOS High Sierra, when I ran
```shell
you-get -di https://www.youtube.com/watch\?v\=3ROjxrSa5pk
```

I got

```shell
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=3ROjxrSa5pk
you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.youtube.com/watch?v=3ROjxrSa5pk'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.939', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/common.py", line 1363, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/common.py", line 1271, in script_main
    **extra
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/common.py", line 1073, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/common.py", line 1356, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/extractors/youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/common.py", line 373, in get_content
    response = urlopen_with_retry(req)
  File "/usr/local/Cellar/you-get/0.4.939/libexec/lib/python3.6/site-packages/you_get/common.py", line 347, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:777)>
```

**Comment by Hrxn** [comment]
Probably Python version..

**Comment by dev-shi** [comment]
Any way to fix this?

**Comment by cnbeining** [comment]
Maybe try using homebrew and get a brand new Python distro?

**Comment by dev-shi** [comment]
```shell
➜  ~ python3 -V
Python 3.6.3
```
It the latest version installed by homebrew
