### ISSUE TITLE
[爱奇艺]部分视频无法下载

### ISSUE THREAD

**Issue by lzy0699** [soimort/you-get#2451]
[DEBUG] get_response: http://www.iqiyi.com/v_19rrgzxk0g.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/221704700
[DEBUG] get_content: http://www.iqiyi.com/v_19rrgzxk0g.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/221704700/5f597e35d50719a1c3f8caf6dcba5b4f/?t=1508848411422&sc=ec18abe802fc86172eac010c36e8a8c8&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.iqiyi.com/v_19rrgzxk0g.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='X:\\Downloads\\', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "H:\MyExe\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python35\lib\site-packages\you_get\common.py", line 1363, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\python35\lib\site-packages\you_get\common.py", line 1271, in script_main
    **extra
  File "c:\python35\lib\site-packages\you_get\common.py", line 1073, in download_main
    download(url, **kwargs)
  File "c:\python35\lib\site-packages\you_get\common.py", line 1356, in any_download
    m.download(url, **kwargs)
  File "c:\python35\lib\site-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\python35\lib\site-packages\you_get\extractors\iqiyi.py", line 147, in prepare
    assert info['code'] == 'A00000', "can't play this video"
AssertionError: can't play this video

**Comment by luhy118** [comment]
you-get has dead,none to handle ..

**Comment by q629988171** [comment]
>you-get http://www.iqiyi.com/v_19rrdwncuc.html -d
[DEBUG] get_response: http://www.iqiyi.com/v_19rrdwncuc.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/810738600
[DEBUG] get_content: http://www.iqiyi.com/v_19rrdwncuc.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/810738600/33cb6ccd64e0b76b94546484e14bf4ef/?t=1508934477373&sc=fb196098b3222e681f8f685bccc16ebc&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               梦想改造家第4季_20171010期
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      m3u8_url:      http://cache.m.iqiyi.com/mus/216347401/1f231e5d3554816fb4f5a55124050838/afbe8fd3d73448c9//20171011/7d/34/f42d4121e63cfc37e855828eb948b0ad.m3u8?qd_originate=tmts_py&tvid=810738600&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1508934477275&qd_p=752c772a&qd_asc=831ba13682103e212ce59a7cecd79c06&qypid=810738600_04022000001000000000_14&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_s=otv&vf=0f21d380b85a5de5ffb76415957f4354&np_tag=nginx_part_tag
    # download-with: you-get --format=TD [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -i http://cache.m.iqiyi.com/mus/216347401/1f231e5d3554816fb4f5a55124050838/afbe8fd3d73448c9//20171011/7d/34/f42d4121e63cfc37e855828eb948b0ad.m3u8?qd_originate=tmts_py&tvid=810738600&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1508934477275&qd_p=752c772a&qd_asc=831ba13682103e212ce59a7cecd79c06&qypid=810738600_04022000001000000000_14&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_s=otv&vf=0f21d380b85a5de5ffb76415957f4354&np_tag=nginx_part_tag -c copy 梦想改造家第4季_20171010期.mp4
ffmpeg version N-87257-g8e17cd2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 74.100 / 55. 74.100
  libavcodec     57.105.100 / 57.105.100
  libavformat    57. 82.100 / 57. 82.100
  libavdevice    57.  8.100 / 57.  8.100
  libavfilter     6.105.100 /  6.105.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=0&end=3016272&contentlength=3016272&sd=1400&durr=6400&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02145d80] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=3016272&end=8370324&contentlength=5354052&sd=7800&durr=7960&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=8370324&end=9362588&contentlength=992264&sd=15760&durr=5840&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=9362588&end=10189976&contentlength=827388&sd=21600&durr=5800&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=10189976&end=11333016&contentlength=1143040&sd=27400&durr=8000&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=11333016&end=12486772&contentlength=1153756&sd=35400&durr=9000&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=12486772&end=13305888&contentlength=819116&sd=44400&durr=6600&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=13305888&end=14028372&contentlength=722484&sd=51000&durr=5160&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=14028372&end=15184196&contentlength=1155824&sd=56160&durr=7160&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=15184196&end=16662628&contentlength=1478432&sd=63320&durr=9400&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=16662628&end=19673260&contentlength=3010632&sd=72720&durr=8600&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=19673260&end=20720044&contentlength=1046784&sd=81320&durr=7440&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=20720044&end=21728288&contentlength=1008244&sd=88760&durr=5200&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=21728288&end=22683328&contentlength=955040&sd=93960&durr=8000&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=22683328&end=25087096&contentlength=2403768&sd=101960&durr=9880&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=25087096&end=27383892&contentlength=2296796&sd=111840&durr=8040&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=27383892&end=30053304&contentlength=2669412&sd=119880&durr=9200&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Failed to open segment of playlist 0
[hls,applehttp @ 02139e20] Opening 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=30053304&end=30842716&contentlength=789412&sd=129080&durr=4520&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi' for reading
[http @ 02156b60] HTTP error 405 Not Allowed
[hls,applehttp @ 02139e20] Error when loading first segment 'http://dx.data.video.qiyi.com/videos/v0/20171011/7d/34/f029fec88f5480b229a3a25c911e1cff.dbts?qdv=1&qypid=810738600_04022000001000000000_14&start=0&end=3016272&contentlength=3016272&sd=1400&durr=6400&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1508934477552&qd_ip=752c772a&qd_p=752c772a&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_sc=iloveiqiyi'
http://cache.m.iqiyi.com/mus/216347401/1f231e5d3554816fb4f5a55124050838/afbe8fd3d73448c9//20171011/7d/34/f42d4121e63cfc37e855828eb948b0ad.m3u8?qd_originate=tmts_py&tvid=810738600&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1508934477275&qd_p=752c772a&qd_asc=831ba13682103e212ce59a7cecd79c06&qypid=810738600_04022000001000000000_14&qd_k=fb196098b3222e681f8f685bccc16ebc&qd_s=otv&vf=0f21d380b85a5de5ffb76415957f4354&np_tag=nginx_part_tag: Immediate exit requested
Exiting normally, received signal 2.
