### ISSUE TITLE
爱奇艺下载出错

### ISSUE THREAD

**Issue by saku1119** [soimort/you-get#2463]
汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [X ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [X ] 您的`you-get`为最新版.
- [X ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ X] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [X ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get --debug -c cookies.txt --no-merge -o C:\Users\Adm
inistrator\Desktop\1 http://www.iqiyi.com/v_19rre0sy1k.html#vfrm=8-8-0-1
[DEBUG] get_response: http://www.iqiyi.com/v_19rre0sy1k.html#vfrm=8-8-0-1
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/822043700
[DEBUG] get_content: http://www.iqiyi.com/v_19rre0sy1k.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/822043700/d3caf761fa42a56efd0
57bd3f9ba6f75/?t=1509108104539&sc=6008474d405d02f5302e78b836331271&src=76f90cbd9
2f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               霹雳天命之战祸邪神 国语版第2集
stream:
    - format:        BD
      container:     m3u8
      video-profile: 1080p
      m3u8_url:      http://cache.m.iqiyi.com/mus/218023601/4c9c67572db92045d2ec
8c37ffa04736/afbe8fd3d73448c9/1312134229/20171027/03/b6/6349425b7f534a477d785a96
65b76356.m3u8?qd_originate=tmts_py&tvid=822043700&bossStatus=2&qd_vip=0&px=15ana
bLWj3Fjm1oAbvaxtSm1wfm3NUhJoSBINJIz3zqtDUiR4Su1SzUOqm1DTD2x6hVm3sb7c&qd_src=3_31
_312&prv=0&previewType=1&previewTime=6&from=&qd_time=1509108246411&qd_p=70ee10bd
&qd_asc=48c0ab6b2d74cd6f2f7eff02fa5209bc&qypid=822043700_04022000001000000000_18
&qd_k=6008474d405d02f5302e78b836331271&qd_s=otv&vf=56ebfa89cb23db196327b4cb40a13
f28&np_tag=nginx_part_tag
    # download-with: you-get --format=BD [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -i http://cache.m.iqiyi.com/mus/218023601/4c9c67572db92045d2ec8c37ffa0
4736/afbe8fd3d73448c9/1312134229/20171027/03/b6/6349425b7f534a477d785a9665b76356
.m3u8?qd_originate=tmts_py&tvid=822043700&bossStatus=2&qd_vip=0&px=15anabLWj3Fjm
1oAbvaxtSm1wfm3NUhJoSBINJIz3zqtDUiR4Su1SzUOqm1DTD2x6hVm3sb7c&qd_src=3_31_312&prv
=0&previewType=1&previewTime=6&from=&qd_time=1509108246411&qd_p=70ee10bd&qd_asc=
48c0ab6b2d74cd6f2f7eff02fa5209bc&qypid=822043700_04022000001000000000_18&qd_k=60
08474d405d02f5302e78b836331271&qd_s=otv&vf=56ebfa89cb23db196327b4cb40a13f28&np_t
ag=nginx_part_tag -c copy -bsf:a aac_adtstoasc C:\Users\Administrator\Desktop\1/
霹雳天命之战祸邪神 国语版第2集.mp4
ffmpeg version 3.3.3 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --e
nable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --
enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv
--enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-li
bfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug -
-enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enabl
e-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-li
bsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolam
e --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx
 --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable
-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
[hls,applehttp @ 034b8500] Opening 'http://dx.data.video.qiyi.com/videos/v0/2017
1027/03/b6/ac689797d5695f2e3895f51c56c4ffab.265ts?qdv=1&start=0&end=1045468&cont
entlength=1045468&sd=0&qd_uid=1312134229&qd_vip=0&qd_src=3_31_312&qd_tm=15091082
47332&qd_ip=70ee10bd&qd_p=70ee10bd&qd_k=6008474d405d02f5302e78b836331271&qd_sc=i
loveiqiyi' for reading
[http @ 0441fb20] HTTP error 405 Not Allowed
[hls,applehttp @ 034b8500] Failed to open segment of playlist 0
[hls,applehttp @ 034b8500] Opening 'http://dx.data.video.qiyi.com/videos/v0/2017
1027/03/b6/ac689797d5695f2e3895f51c56c4ffab.265ts?qdv=1&start=1045468&end=211819
6&contentlength=1072728&sd=4840&qd_uid=1312134229&qd_vip=0&qd_src=3_31_312&qd_tm
=1509108247332&qd_ip=70ee10bd&qd_p=70ee10bd&qd_k=6008474d405d02f5302e78b83633127
1&qd_sc=iloveiqiyi' for reading
[http @ 043aa060] HTTP error 405 Not Allowed
[hls,applehttp @ 034b8500] Failed to open segment of playlist 0
[hls,applehttp @ 034b8500] Opening 'http://dx.data.video.qiyi.com/videos/v0/2017
1027/03/b6/ac689797d5695f2e3895f51c56c4ffab.265ts?qdv=1&start=2118196&end=322401
2&contentlength=1105816&sd=9960&qd_uid=1312134229&qd_vip=0&qd_src=3_31_312&qd_tm
=1509108247332&qd_ip=70ee10bd&qd_p=70ee10bd&qd_k=6008474d405d02f5302e78b83633127
1&qd_sc=iloveiqiyi' for reading
[http @ 043aa060] HTTP error 405 Not Allowed
[hls,applehttp @ 034b8500] Failed to open segment of playlist 0
[hls,applehttp @ 034b8500] Opening 'http://dx.data.video.qiyi.com/videos/v0/2017
1027/03/b6/ac689797d5695f2e3895f51c56c4ffab.265ts?qdv=1&start=3224012&end=402301
2&contentlength=799000&sd=15080&qd_uid=1312134229&qd_vip=0&qd_src=3_31_312&qd_tm
=1509108247332&qd_ip=70ee10bd&qd_p=70ee10bd&qd_k=6008474d405d02f5302e78b83633127
1&qd_sc=iloveiqiyi' for reading
[http @ 043aa060] HTTP error 405 Not Allowed
[hls,applehttp @ 034b8500] Failed to open segment of playlist 0
[hls,applehttp @ 034b8500] Opening 'http://dx.data.video.qiyi.com/videos/v0/2017
1027/03/b6/ac689797d5695f2e3895f51c56c4ffab.265ts?qdv=1&start=4023012&end=527415
2&contentlength=1251140&sd=20200&qd_uid=1312134229&qd_vip=0&qd_src=3_31_312&qd_t
m=1509108247332&qd_ip=70ee10bd&qd_p=70ee10bd&qd_k=6008474d405d02f5302e78b8363312
71&qd_sc=iloveiqiyi' for reading
[http @ 043aa060] HTTP error 405 Not Allowed
[hls,applehttp @ 034b8500] Failed to open segment of playlist 0
[hls,applehttp @ 034b8500] Opening 'http://dx.data.video.qiyi.com/videos/v0/2017
1027/03/b6/ac689797d5695f2e3895f51c56c4ffab.265ts?qdv=1&start=5274152&end=672870
8&contentlength=1454556&sd=25320&qd_uid=1312134229&qd_vip=0&qd_src=3_31_312&qd_t
m=1509108247332&qd_ip=70ee10bd&qd_p=70ee10bd&qd_k=6008474d405d02f5302e78b8363312
71&qd_sc=iloveiqiyi' for reading
[http @ 043aa060] HTTP error 405 Not Allowed
[hls,applehttp @ 034b8500] Failed to open segment of playlist 0
[hls,applehttp @ 034b8500] Opening 'http://dx.data.video.qiyi.com/videos/v0/2017
1027/03/b6/ac689797d5695f2e3895f51c56c4ffab.265ts?qdv=1&start=6728708&end=786328
8&contentlength=1134580&sd=30440&qd_uid=1312134229&qd_vip=0&qd_src=3_31_312&qd_t
m=1509108247332&qd_ip=70ee10bd&qd_p=70ee10bd&qd_k=6008474d405d02f5302e78b8363312
71&qd_sc=iloveiqiyi' for reading
[http @ 043aa060] HTTP error 405 Not Allowed
[hls,applehttp @ 034b8500] Failed to open segment of playlist 0
[hls,applehttp @ 034b8500] Opening 'http://dx.data.video.qiyi.com/videos/v0/2017
1027/03/b6/ac689797d5695f2e3895f51c56c4ffab.265ts?qdv=1&start=7863288&end=927366
4&contentlength=1410376&sd=35560&qd_uid=1312134229&qd_vip=0&qd_src=3_31_312&qd_t
m=1509108247332&qd_ip=70ee10bd&qd_p=70ee10bd&qd_k=6008474d405d02f5302e78b8363312
71&qd_sc=iloveiqiyi' for reading
[http @ 043aa060] HTTP error 405 Not Allowed
[hls,applehttp @ 034b8500] Failed to open segment of playlist 0
[hls,applehttp @ 034b8500] Opening 'http://dx.data.video.qiyi.com/videos/v0/2017
1027/03/b6/ac689797d5695f2e3895f51c56c4ffab.265ts?qdv=1&start=9273664&end=107896
96&contentlength=1516032&sd=40680&qd_uid=1312134229&qd_vip=0&qd_src=3_31_312&qd_
tm=1509108247332&qd_ip=70ee10bd&qd_p=70ee10bd&qd_k=6008474d405d02f5302e78b836331
271&qd_sc=iloveiqiyi' for reading
[http @ 043aa060] HTTP error 405 Not Allowed
[hls,applehttp @ 034b8500] Failed to open segment of playlist 0
[hls,applehttp @ 034b8500] Opening 'http://dx.data.video.qiyi.com/videos/v0/2017
1027/03/b6/ac689797d5695f2e3895f51c56c4ffab.265ts?qdv=1&start=10789696&end=11838
172&contentlength=1048476&sd=45800&qd_uid=1312134229&qd_vip=0&qd_src=3_31_312&qd
_tm=1509108247332&qd_ip=70ee10bd&qd_p=70ee10bd&qd_k=6008474d405d02f5302e78b83633
1271&qd_sc=iloveiqiyi' for reading
[http @ 043aa060] HTTP error 405 Not Allowed
[hls,applehttp @ 034b8500] Error when loading first segment 'http://dx.data.vide
o.qiyi.com/videos/v0/20171027/03/b6/ac689797d5695f2e3895f51c56c4ffab.265ts?qdv=1
&start=0&end=1045468&contentlength=1045468&sd=0&qd_uid=1312134229&qd_vip=0&qd_sr
c=3_31_312&qd_tm=1509108247332&qd_ip=70ee10bd&qd_p=70ee10bd&qd_k=6008474d405d02f
5302e78b836331271&qd_sc=iloveiqiyi'
http://cache.m.iqiyi.com/mus/218023601/4c9c67572db92045d2ec8c37ffa04736/afbe8fd3
d73448c9/1312134229/20171027/03/b6/6349425b7f534a477d785a9665b76356.m3u8?qd_orig
inate=tmts_py&tvid=822043700&bossStatus=2&qd_vip=0&px=15anabLWj3Fjm1oAbvaxtSm1wf
m3NUhJoSBINJIz3zqtDUiR4Su1SzUOqm1DTD2x6hVm3sb7c&qd_src=3_31_312&prv=0&previewTyp
e=1&previewTime=6&from=&qd_time=1509108246411&qd_p=70ee10bd&qd_asc=48c0ab6b2d74c
d6f2f7eff02fa5209bc&qypid=822043700_04022000001000000000_18&qd_k=6008474d405d02f
5302e78b836331271&qd_s=otv&vf=56ebfa89cb23db196327b4cb40a13f28&np_tag=nginx_part
_tag: Immediate exit requested
Exiting normally, received signal 2.

C:\Users\Administrator>


```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [下载爱奇艺的时候出现的问题……是会员，已用cookies，刷屏特别快，暂停了截取的debug]
> [舔 :icecream:!]

**Comment by lki2019** [comment]
VIP不支持，
https://github.com/soimort/you-get/wiki/Known-Bugs

报导不会为VIP视频工作：

搜狐
＃1223
爱奇艺
＃2117
乐视网
＃1208

------------
写的清清楚楚的，

**Comment by saku1119** [comment]
我后来下下来了……只要不命令分开不合并就行- - 虽然中间也会报错，但是至少下下来了……并且可以看。我关一下吧。

**Comment by lki2019** [comment]
you-get --debug -c cookies.txt --no-merge -o C:\Users\Adm
inistrator\Desktop\1 http://www.iqiyi.com/v_19rre0sy1k.html#vfrm=8-8-0-1



最后还是用的这个命令？

我试了一下 ，也是你上面的提示 405

**Comment by saku1119** [comment]
因为我本来就是会员，所以加载cookies是有效的，并不是不支持vip的关系。

这个下载出错的原因我不是很清楚，但是去除不合并命令之后就可以下载了，所以命令是改过的。

**Comment by saku1119** [comment]
因为我本来就是会员，所以加载cookies是有效的，并不是不支持vip的关系。

这个下载出错的原因我不是很清楚，但是去除不合并命令之后就可以下载了，所以命令是改过的。

**Comment by lki2019** [comment]
you-get --debug -c cookies.txt -o C:\Users\Administrator\Desktop\1 http://www.iqiyi.com/v_19rre0sy1k.html#vfrm=8-8-0-1

**Comment by lki2019** [comment]
--no-merge 去掉这个也是405
以前开发者说过不支持271的 cookies的  也许最近支持了吧

**Comment by saku1119** [comment]
不知道了……我是可以下……

**Comment by saku1119** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get -c cookies.txt http://www.iqiyi.com/v_19rre0t5uo.
html
site:                爱奇艺 (Iqiyi)
title:               霹雳天命之战祸邪神 国语版第1集
stream:
    - format:        BD
      container:     m3u8
      video-profile: 1080p
      m3u8_url:      http://cache.m.iqiyi.com/mus/218023601/4480cc011b7fed6be1aa
ed9a6321fad8/afbe8fd3d73448c9/1312134229/20171027/1e/6d/4209234abf132ea3b4db9fad
61a140f9.m3u8?qd_originate=tmts_py&tvid=822037900&bossStatus=2&qd_vip=0&px=15ana
bLWj3Fjm1oAbvaxtSm1wfm3NUhJoSBINJIz3zqtDUiR4Su1SzUOqm1DTD2x6hVm3sb7c&qd_src=3_31
_312&prv=0&previewType=1&previewTime=6&from=&qd_time=1509261631351&qd_p=70ee10bd
&qd_asc=99a142fdb38f6fa3184d4ab11b264079&qypid=822037900_04022000001000000000_5&
qd_k=1cc7589826714f12db48edda76f023da&qd_s=otv&vf=4442ec0d054da69e0a4b23ba43dda4
64&np_tag=nginx_part_tag
    # download-with: you-get --format=BD [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -i http://cache.m.iqiyi.com/mus/218023601/4480cc011b7fed6be1aaed9a6321
fad8/afbe8fd3d73448c9/1312134229/20171027/1e/6d/4209234abf132ea3b4db9fad61a140f9
.m3u8?qd_originate=tmts_py&tvid=822037900&bossStatus=2&qd_vip=0&px=15anabLWj3Fjm
1oAbvaxtSm1wfm3NUhJoSBINJIz3zqtDUiR4Su1SzUOqm1DTD2x6hVm3sb7c&qd_src=3_31_312&prv
=0&previewType=1&previewTime=6&from=&qd_time=1509261631351&qd_p=70ee10bd&qd_asc=
99a142fdb38f6fa3184d4ab11b264079&qypid=822037900_04022000001000000000_5&qd_k=1cc
7589826714f12db48edda76f023da&qd_s=otv&vf=4442ec0d054da69e0a4b23ba43dda464&np_ta
g=nginx_part_tag -c copy -bsf:a aac_adtstoasc 霹雳天命之战祸邪神 国语版第1集.mp4

ffmpeg version 3.3.3 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --e
nable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --
enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv
--enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-li
bfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug -
-enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enabl
e-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-li
bsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolam
e --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx
 --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable
-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
[hls,applehttp @ 03258420] Opening 'http://dx.data.video.qiyi.com/videos/v0/2017
1027/1e/6d/94c1ae1f34f00c927f4ec10a2074cf6b.ts?qdv=1&start=0&end=5501474&hsize=2
8282&tag=0&v=6814203900&contentlength=3460328&qd_uid=1312134229&qd_vip=0&qd_src=
3_31_312&qd_tm=1509261632101&qd_ip=70ee10bd&qd_p=70ee10bd&qd_k=1cc7589826714f12d
b48edda76f023da&qd_sc=iloveiqiyi' for reading
Input #0, hls,applehttp, from 'http://cache.m.iqiyi.com/mus/218023601/4480cc011b
7fed6be1aaed9a6321fad8/afbe8fd3d73448c9/1312134229/20171027/1e/6d/4209234abf132e
a3b4db9fad61a140f9.m3u8?qd_originate=tmts_py&tvid=822037900&bossStatus=2&qd_vip=
0&px=15anabLWj3Fjm1oAbvaxtSm1wfm3NUhJoSBINJIz3zqtDUiR4Su1SzUOqm1DTD2x6hVm3sb7c&q
d_src=3_31_312&prv=0&previewType=1&previewTime=6&from=&qd_time=1509261631351&qd_
p=70ee10bd&qd_asc=99a142fdb38f6fa3184d4ab11b264079&qypid=822037900_0402200000100
0000000_5&qd_k=1cc7589826714f12db48edda76f023da&qd_s=otv&vf=4442ec0d054da69e0a4b
23ba43dda464&np_tag=nginx_part_tag':
  Duration: 01:16:00.00, start: 0.000000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709)
, 1920x1080, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, flt
p
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to '闇归洺澶╁懡涔嬫垬绁搁偑绁?鍥借鐗堢1闆?mp4':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p(tv, bt709)
, 1920x1080, q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, flt
p
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   22 fps=0.0 q=-1.0 size=     363kB time=00:00:00.84 bitrate=3543.8kbits/
frame=   26 fps=6.6 q=-1.0 size=     445kB time=00:00:01.00 bitrate=3644.5kbits/
frame=   29 fps=5.0 q=-1.0 size=     518kB time=00:00:01.12 bitrate=3788.1kbits/
frame=   33 fps=4.7 q=-1.0 size=     608kB time=00:00:01.28 bitrate=3890.0kbits/
frame=   36 fps=4.5 q=-1.0 size=     676kB time=00:00:01.40 bitrate=3954.4kbits/
frame=   38 fps=4.5 q=-1.0 size=     683kB time=00:00:01.48 bitrate=3781.0kbits/
frame=   42 fps=4.7 q=-1.0 size=     769kB time=00:00:01.64 bitrate=3843.4kbits/
frame=   45 fps=4.6 q=-1.0 size=     841kB time=00:00:01.76 bitrate=3912.1kbits/
frame=   47 fps=4.3 q=-1.0 size=     888kB time=00:00:01.84 bitrate=3953.4kbits/
frame=   48 fps=4.2 q=-1.0 size=     888kB time=00:00:01.88 bitrate=3869.3kbits/
frame=   50 fps=4.2 q=-1.0 size=     971kB time=00:00:01.96 bitrate=4056.9kbits/
frame=   53 fps=3.6 q=-1.0 size=    1031kB time=00:00:02.08 bitrate=4060.1kbits/
frame=   56 fps=2.8 q=-1.0 size=    1083kB time=00:00:02.20 bitrate=4033.9kbits/
frame=   62 fps=2.8 q=-1.0 size=    1140kB time=00:00:02.44 bitrate=3826.3kbits/
frame=   62 fps=2.7 q=-1.0 size=    1140kB time=00:00:02.44 bitrate=3828.1kbits/
frame=   67 fps=2.5 q=-1.0 size=    1241kB time=00:00:02.64 bitrate=3851.7kbits/
frame=   73 fps=2.7 q=-1.0 size=    1300kB time=00:00:02.88 bitrate=3697.3kbits/
frame=   73 fps=2.5 q=-1.0 size=    1303kB time=00:00:02.88 bitrate=3706.0kbits/
frame=   76 fps=2.6 q=-1.0 size=    1350kB time=00:00:03.00 bitrate=3687.3kbits/
frame=   78 fps=2.5 q=-1.0 size=    1389kB time=00:00:03.08 bitrate=3694.4kbits/
frame=   79 fps=2.4 q=-1.0 size=    1390kB time=00:00:03.12 bitrate=3648.5kbits/
frame=   81 fps=2.5 q=-1.0 size=    1410kB time=00:00:03.20 bitrate=3608.6kbits/
frame=   85 fps=2.5 q=-1.0 size=    1491kB time=00:00:03.36 bitrate=3634.4kbits/
frame=   87 fps=2.4 q=-1.0 size=    1519kB time=00:00:03.44 bitrate=3616.6kbits/
frame=   88 fps=2.3 q=-1.0 size=    1542kB time=00:00:03.48 bitrate=3629.0kbits/
frame=   91 fps=2.3 q=-1.0 size=    1585kB time=00:00:03.60 bitrate=3607.0kbits/
[mp4 @ 053bca20] Timestamps are unset in a packet for stream 0. This is deprecat
ed and will stop working in the future. Fix your code to set the timestamps prop
erly
frame=   93 fps=1.9 q=-1.0 size=    1599kB time=00:00:03.68 bitrate=3559.3kbits/
[mp4 @ 053bca20] pts has no value
frame=   96 fps=1.8 q=-1.0 size=    1789kB time=00:00:03.80 bitrate=3856.9kbits/
frame=   98 fps=1.8 q=-1.0 size=    1795kB time=00:00:03.88 bitrate=3789.7kbits/
frame=   99 fps=1.7 q=-1.0 Lsize=    1858kB time=00:00:03.92 bitrate=3883.5kbits
/s speed=0.0684x
video:1764kB audio:90kB subtitle:0kB other streams:0kB global headers:0kB muxing
 overhead: 0.265875%
Exiting normally, received signal 2.

C:\Users\Administrator>



现在是这样……不过地址没用那个……偶尔会出一点小错的样子

**Comment by lki2019** [comment]
恩这个命令是OK的

**Comment by Kara-ism** [comment]
Same problems here, environment built within Cygwin ,

> $ python3 you-get 'http://www.iqiyi.com/v_19rreo9xf8.html' --debug
[DEBUG] get_response: http://www.iqiyi.com/v_19rreo9xf8.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/848754200
[DEBUG] get_content: http://www.iqiyi.com/v_19rreo9xf8.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/848754200/049215e7f9b3d4da4560ba8d3f1a8d01/?t=1511708910914&sc=9885656faee968202ca55e17f9fddbe9&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.iqiyi.com/v_19rreo9xf8.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/Kara-ism/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/Kara-ism/you-get/src/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/home/Kara-ism/you-get/src/you_get/common.py", line 1270, in script_main
    **extra
  File "/home/Kara-ism/you-get/src/you_get/common.py", line 1072, in download_main
    download(url, **kwargs)
  File "/home/Kara-ism/you-get/src/you_get/common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "/home/Kara-ism/you-get/src/you_get/extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "/home/Kara-ism/you-get/src/you_get/extractors/iqiyi.py", line 209, in download
    download_url_ffmpeg(urls[0], self.title, 'mp4', output_dir=kwargs['output_dir'], merge=kwargs['merge'], stream=False)
  File "/home/Kara-ism/you-get/src/you_get/common.py", line 897, in download_url_ffmpeg
    assert has_ffmpeg_installed(), "FFmpeg not installed."
AssertionError: FFmpeg not installed.
