### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by AingW** [soimort/you-get#2466]
=============================================================
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=z9-83UE3DWQ
you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.youtube.com/watch?v=z9-83UE3DWQ'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player="'D:\\A_Program\\Daily\\PotPlayer\\PotPlayerMini64.exe'", playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "d:\a_program\s_sys\python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "d:\a_program\s_sys\python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\a_program\s_sys\python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "d:\a_program\s_sys\python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "d:\a_program\s_sys\python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "d:\a_program\s_sys\python36\lib\http\client.py", line 964, in send
    self.connect()
  File "d:\a_program\s_sys\python36\lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "d:\a_program\s_sys\python36\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "d:\a_program\s_sys\python36\lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "d:\a_program\s_sys\python36\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "d:\a_program\s_sys\python36\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\a_program\s_sys\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\a_program\s_sys\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\A_Program\S_sys\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\a_program\s_sys\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\a_program\s_sys\python36\lib\site-packages\you_get\common.py", line 1363, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "d:\a_program\s_sys\python36\lib\site-packages\you_get\common.py", line 1271, in script_main
    **extra
  File "d:\a_program\s_sys\python36\lib\site-packages\you_get\common.py", line 1073, in download_main
    download(url, **kwargs)
  File "d:\a_program\s_sys\python36\lib\site-packages\you_get\common.py", line 1356, in any_download
    m.download(url, **kwargs)
  File "d:\a_program\s_sys\python36\lib\site-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "d:\a_program\s_sys\python36\lib\site-packages\you_get\extractors\youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "d:\a_program\s_sys\python36\lib\site-packages\you_get\common.py", line 373, in get_content
    response = urlopen_with_retry(req)
  File "d:\a_program\s_sys\python36\lib\site-packages\you_get\common.py", line 347, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "d:\a_program\s_sys\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "d:\a_program\s_sys\python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "d:\a_program\s_sys\python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "d:\a_program\s_sys\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "d:\a_program\s_sys\python36\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "d:\a_program\s_sys\python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

================================================================

the solution in the below website，can help to be far away this problem？？？anyone can know？
https://stackoverflow.com/questions/46604114/python-requests-ssl-error-certificate-verify-failed

**Comment by ha-ni-cc** [comment]
I had this problem,too ! I think python initiate request should setting 'verify' as 'false' instead of the default value 'true'. But how can improve it ?

**Comment by ha-ni-cc** [comment]
Hey,I had sloved this problem,here is the solution:

MacOS at Python 3.6 SSL library is default not include certificate.
You should open the terminal follow this :

`cd /Applications/Python\ 3.6/
./Install\ Certificates.command`

You can see it : https://github.com/soimort/you-get/issues/1710#issuecomment-282543294

**Comment by cnbeining** [comment]
Thanks. I would put this in Wiki.

**Comment by zjhxmjl** [comment]
同样的问题，有无选项禁用证书检查或直接导入证书？
