### ISSUE TITLE
去广告观看报错

### ISSUE THREAD

**Issue by pxss** [soimort/you-get#2474]
命令：you-get -p chromium "http://v.youku.com/v_show/id_XMzExNTc5OTY2OA==.html?spm=a2hww.20027244.m_250008.5~5!2~5~5~A" --debug

C:\WINDOWS\system32>you-get -p chromium "http://v.youku.com/v_show/id_XMzExNTc5OTY2OA==.html?spm=a2hww.20027244.m_250008.5~5!2~5~5~A" --debug
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzExNTc5OTY2OA==&ccode=0401&client_ip=192.168.1.1&utid=WqmBEr2/WXECASSVAJDO4UDU&client_ts=1509604188
you-get: mp4hd2 is a preview
you-get: mp4hd3 is a preview
you-get: mp4hd3v2 is a preview
you-get: mp4hd2v2 is a preview
you-get: mp4sd is a preview
you-get: mp4hd is a preview
site:                优酷 (Youku)
title:               岳云鹏相声专场演出 悉尼站整场
stream:
    - format:        mp4hd3
      container:     mp4
      video-profile: 1080P
      size:          2369.7 MiB (2484818608 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMzExNTc5OTY2OA%3D%3D&type=hd3&ups_client_netip=36.149.64.144&ups_ts=1509604190&utid=WqmBEr2%2FWXECASSVAJDO4UDU&ccode=0401&psid=693bd94a5f0f2100d2e5d2cf78ad4ed4&duration=12911&expire=18000&ups_key=f61f526d95466890590c72fddb28ef0c
    # download-with: you-get --format=mp4hd3 [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XMzExNTc5OTY2OA==

you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://v.youku.com/v_show/id_XMzExNTc5OTY2OA==.html?spm=a2hww.20027244.m_250008.5~5!2~5~5~A'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player='chromium', playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1363, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1271, in script_main
    **extra
  File "c:\python36\lib\site-packages\you_get\common.py", line 1073, in download_main
    download(url, **kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1356, in any_download
    m.download(url, **kwargs)
  File "c:\python36\lib\site-packages\you_get\extractors\youku.py", line 304, in youku_download_by_url
    Youku().download_by_url(url, **kwargs)
  File "c:\python36\lib\site-packages\you_get\extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "c:\python36\lib\site-packages\you_get\extractor.py", line 228, in download
    av=stream_id in self.dash_streams)
  File "c:\python36\lib\site-packages\you_get\common.py", line 758, in download_urls
    launch_player(player, urls)
  File "c:\python36\lib\site-packages\you_get\common.py", line 253, in launch_player
    subprocess.call(shlex.split(player) + list(urls))
  File "c:\python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by cnbeining** [comment]
Chromium在你的系统可以命令行调用吗？
