### ISSUE TITLE
B站的直播解析挂了

### ISSUE THREAD

**Issue by mengmo** [soimort/you-get#2479]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get -di https://live.bilibili.com/10112
D:\PortableApps\Python\lib\runpy.py:125: RuntimeWarning: 'you_get.__main__' found in sys.modules after import of package 'you_get', but prior to execution of 'you_get.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[DEBUG] url_locations: https://live.bilibili.com/10112
[DEBUG] get_content: https://live.bilibili.com/neptune/10112
you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://live.bilibili.com/10112'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "D:\PortableApps\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PortableApps\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 95, in <module>
    main()
  File "D:\PortableApps\Python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1368, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1276, in script_main
    **extra
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1078, in download_main
    download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\common.py", line 1361, in any_download
    m.download(url, **kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractors\bilibili.py", line 144, in prepare
    self.live_entry(**kwargs)
  File "D:\PortableApps\Python\lib\site-packages\you_get\extractors\bilibili.py", line 191, in live_entry
    self.title = re.search(r'<title>([^<]+)', self.page).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

**Comment by zmwangx** [comment]
This should be fixed by #2511. Please test if you will.

**Comment by mengmo** [comment]
it works
```
you-get -di https://live.bilibili.com/10112
D:\PortableApps\Python\lib\runpy.py:125: RuntimeWarning: 'you_get.__main__' found in sys.modules after import of package 'you_get', but prior to execution of 'you_get.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[DEBUG] url_locations: https://live.bilibili.com/10112
[DEBUG] get_content: https://live.bilibili.com/10112
[DEBUG] get_content: https://api.live.bilibili.com/room/v1/Room/room_init?id=10112
[DEBUG] get_content: https://api.live.bilibili.com/room/v1/Room/get_info?room_id=10112
[DEBUG] get_content: http://live.bilibili.com/api/playurl?cid=10112&otype=json
site:                Bilibili
title:               　
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        live
      container:     flv
    # download-with: you-get --format=live [URL]
```

**Comment by zmwangx** [comment]
Good. Not sure why your title is empty though; it shouldn't be:

```console
$ curl -s https://api.live.bilibili.com/room/v1/Room/get_info\?room_id\=10112 | jq -r .data.title
18:00 东京万圣节2017 Live
```

Maybe you got the above when the livestream was off?

**Comment by zmwangx** [comment]
Actually, no, the title should be available even when the livestream is off.
