### ISSUE TITLE
爱课程下载出错，expected string or bytes-like object

### ISSUE THREAD

**Issue by 3ng** [soimort/you-get#2489]
```
 you-get -d  http://www.icourses.cn/viewVCourse.action?courseCode=10335V001
[DEBUG] get_content: http://www.icourses.cn/viewVCourse.action?courseCode=10335V001
[DEBUG] get_content: http://www.icourses.cn/getVideoResPlayInfo.action?IService=http%3A%2F%2Fwww.icourses.cn%2FgetVideoResPlayInfo.action&uuid=d0eec6d8&other=&v=1510318443192
you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.icourses.cn/viewVCourse.action?courseCode=10335V001'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='D:\\Video\\爱课程\\董平', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1363, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1271, in script_main
    **extra
  File "c:\python36\lib\site-packages\you_get\common.py", line 1073, in download_main
    download(url, **kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1356, in any_download
    m.download(url, **kwargs)
  File "c:\python36\lib\site-packages\you_get\extractors\icourses.py", line 23, in icourses_download
    icourses_parser.basic_extract()
  File "c:\python36\lib\site-packages\you_get\extractors\icourses.py", line 240, in basic_extract
    self.api_req(api_req_url)
  File "c:\python36\lib\site-packages\you_get\extractors\icourses.py", line 222, in api_req
    xml_str = get_content(url)
  File "c:\python36\lib\site-packages\you_get\common.py", line 385, in get_content
    charset = match1(response.getheader('Content-Type'), r'charset=([\w-]+)')
  File "c:\python36\lib\site-packages\you_get\common.py", line 219, in match1
    match = re.search(pattern, text)
  File "c:\python36\lib\re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

本来下的好好的，后面就一直报错。
Thanks in advanced。

**Comment by Pythonjake** [comment]
> you-get --debug "http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=100665&courseId=5976"
[DEBUG] get_content: http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=100665&courseId=5976
[DEBUG] get_content: http://www.icourses.cn/jpk/getResPlayInfo.action?other=&v=1510885164333&uuid=716535&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action
[DEBUG] get_content: http://media1.icourses.cn:8080/process6/campus//ssl/host.shtml
[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=1994905
[DEBUG] url_info: http://media3.icourses.cn/process6/campus/processres/flv/2013/9/27/ff808081-415caf
c1-0141-5f21a1c4-002d.flv?p=151020&lv=150606-1&h=ScNRFBBXqxsKHpvVjX_KMw&ls=play&lt=11-17%2F10%3A20%3
A16&start=0&r=1510885219
[DEBUG] HTTP Error with code404
[DEBUG] HTTP Error with code404
you-get: version 0.4.900, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=100665&cour
seId=5976'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, h
ttp_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False,no_merge=False
, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False,
socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1362, in main
  File "src\you_get\common.py", line 1270, in script_main
  File "src\you_get\common.py", line 1072, in download_main
  File "src\you_get\common.py", line 1355, in any_download
  File "src\you_get\extractors\icourses.py", line 30, in icourses_download
  File "src\you_get\common.py", line 466, in url_info
AttributeError: 'NoneType' object has no attribute 'headers'
you-get returned -1

以上是错误信息
之前可以下载，只是有一小部分课程没发下载，但是大多数还是可以
但是从2017年11月16号之后，貌似大部分（我试过好几个之前可以下载的，现在也下载不了了）都不行了。聪明的程序员哥哥，快点来解决呀，要不期末就挂科啦~

**Comment by 3ng** [comment]
蓝鹅你这个链接在我这边是可以下载的
‘’‘
D:\VedioMarking\爱课程>you-get "http://www.icourses.cn/jpk/viewCharacterDetail.a
ction?sectionId=100665&courseId=5976"
Site:       icourses.cn
Title:      数据结构与算法 第一章 第1节 1.1数据结构基本概念及研究对象
Type:       Flash video (video/x-flv)
Size:       163.91 MiB (171872979 Bytes)

Downloading 数据结构与算法 第一章 第1节 1.1数据结构基本概念及研究对象.flv ...

 0.2% (  0.2/163.9MB) ├────────────────────────────
─────────────┤[1/1]   27 kB/s
’‘’

**Comment by 3ng** [comment]
@Pythonjake 蓝鹅你这个链接在我这边是可以下载的
‘’‘
D:\VedioMarking\爱课程>you-get "http://www.icourses.cn/jpk/viewCharacterDetail.a
ction?sectionId=100665&courseId=5976"
Site: icourses.cn
Title: 数据结构与算法 第一章 第1节 1.1数据结构基本概念及研究对象
Type: Flash video (video/x-flv)
Size: 163.91 MiB (171872979 Bytes)

Downloading 数据结构与算法 第一章 第1节 1.1数据结构基本概念及研究对象.flv ...

0.2% ( 0.2/163.9MB) ├────────────────────────────
─────────────┤[1/1] 27 kB/s

**Comment by Pythonjake** [comment]
@3ng 那我这怎么总是下载不了。。。奇葩
