### ISSUE TITLE
腾讯视频无法下载，从16年到现在就没有测试成功过。谁来指点下

### ISSUE THREAD

**Issue by lll423** [soimort/you-get#2495]
Please make sure these boxes are checked before submitting your issue – thank you!

- [  ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
C:\Users\user>you-get -i https://v.qq.com/x/page/y0025peenjt.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\user>you-get -i https://v.qq.com/x/page/y0025peenjt.html --debug
[DEBUG] get_content: https://v.qq.com/x/page/y0025peenjt.html
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=y0025peenjt
you-get: version 0.4.964, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://v.qq.com/x/page/y0025peenjt.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\socket.py", line 722, in create_connection
    raise err
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1368, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1276, in script_main
    **extra
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1078, in download_main
    download(url, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1361, in any_download
    m.download(url, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\qq.py", line 152, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\qq.py", line 13, in qq_download_by_vid
    info = get_content(info_api)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 378, in get_content
    response = urlopen_with_retry(req)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 348, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>

C:\Users\user>you-get -V
you-get: version 0.4.964, a tiny downloader that scrapes the web.
```

版本显示是  0.4.964

**Comment by huzy0909** [comment]
用you-get -u 获取真实地址，再用IDM批量下载，下载后文件名都是按1、2、3排好的，再用ffmpeg合并吧

**Comment by bright-pan** [comment]
@lll423 已解决 #2943

**Comment by lll423** [comment]
@bright-pan 
 
C:\Users\user>you-get -i https://v.qq.com/x/page/y0025peenjt.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.


还是这样，已经更新了qq.py

**Comment by bright-pan** [comment]
@lll423 

```
you-get -u "https://v.qq.com/x/page/y0025peenjt.html"
Site:       QQ.com
Title:      俄罗斯 远东地区森林大火肆虐 火情仍在扩大 空气污染严重
Type:       MPEG-4 video (video/mp4)
Size:       3.94 MiB (4136395 Bytes)

Real URLs:
http://27.36.118.12/vlive.qqvideo.tc.qq.com/AQYmS04PsdEk28nwzqw9u5GPRWZqNudGRs0n9WBNK9-k/y0025peenjt.p212.1.mp4?vkey=3F126F824A4ACA1D5E56E6CD070419B6A5E24E6E3194325F25FE421BD974B9BB1523673C2429A837D6E87A6E7AC52E8F82AE41F6710C001861E52D0241F04AF565FDEF6F81FD51E93B95AB6C478570BE665602310B9B11A851543DDBCB290850
```

没有你说的这种情况，你是不是没有安装好？

**Comment by huzy0909** [comment]
就是下载速度太慢，@bright-pan 你下载速度快吗
you-get  https://v.qq.com/x/page/y0025peenjt.html
Site:       QQ.com
Title:      俄罗斯 远东地区森林大火肆虐 火情仍在扩大 空气污染严重
Type:       MPEG-4 video (video/mp4)
Size:       3.94 MiB (4136395 Bytes)

Downloading 俄罗斯 远东地区森林大火肆虐 火情仍在扩大 空气污染严重.mp4 ...
25.3% (  1.0/  3.9MB) ├███████████─────────────────────────────┤[1/1]    9 kB/s

**Comment by bright-pan** [comment]
建议获取url用别的多线程工具下试试，我这边即使拿迅雷会员加速下也是30k的速度。

**Comment by huzy0909** [comment]
我用IDM下载，8线程速度80k左右，下载小视频还能忍受，高清电视剧就太慢了

**Comment by lll423** [comment]
@bright-pan 如果没有装好 但可以解释youku这些 ，只是QQ视频不行。不知道是那里没有装好。安装是通过pop3方式安装的

**Comment by lll423** [comment]
找到原因了，原来是我的hosts文件屏蔽广告所至。可能是有v.qq.com的播放域名被我屏蔽所致

**Comment by huzy0909** [comment]
@lll423 你下载速度快不？

**Comment by luhy118** [comment]
@huzy0909 IDM是什么

**Comment by huzy0909** [comment]
＠luhy118  Internet Download  Manager 一个很好用下载工具，同时也能探测、下载视频

**Comment by luhy118** [comment]
@huzy0909 哦，没有调用接口或源码么，方便嵌入我的爬取代码中。

**Comment by huzy0909** [comment]
@luhy118  没有吧，IDM本身就是商业的收费软件，我用的是破解版

**Comment by luhy118** [comment]
@huzy0909 大神，可以帮我看下问题么，http://v3-tt.ixigua.com/062a1b63ce981fe0803e50a5bd24c288/5a155582/video/m/220433f7ac00f214d5780165f8329c03b4011526d7c0000ac4d505b5196/  这个视频，直接放在浏览器可以正常打开播放，但是我用 requests.get()，直接报403，也从浏览器把headers添加了还是报403，搞了一天了都没解决是什么问题

**Comment by lll423** [comment]
@huzy0909 我这里 广州电信  QQ视频下载速度在每秒1兆以上，youku就基本是8兆每秒下载，也就是跑到100兆的带宽左右

**Comment by jyuan15** [comment]
32线程下载速度，50M光纤
![2017-11-23_083937](https://user-images.githubusercontent.com/12642186/33155351-e4b14e6e-d02a-11e7-8108-2f02471e14dc.jpg)

**Comment by huzy0909** [comment]
@lll423 你QQ视频达到1兆以上，youku达到8兆，是用you-get 直接下载吗？

@luhy118 不好意思，我不会编程，帮不到你，不过这里高手很多，会有人出手相助的：）

**Comment by lll423** [comment]
@huzy0909   you-get直接下载，单线程
![5](https://user-images.githubusercontent.com/4048921/33158479-424b9f4c-d045-11e7-8009-af4dd25d5deb.png)

**Comment by huzy0909** [comment]
@lll423 能不能帮忙试试这个视频，我下载只有20-30k，速度实在是太慢了

you-get https://v.qq.com/x/cover/g7m84rhikqkd772/t0025z41zak.html
Site:       QQ.com
Title:      急诊科医生_31
Type:       MPEG-4 video (video/mp4)
Size:       540.61 MiB (566875620 Bytes)

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 急诊科医生_31.mp4 ...
 0.1% (  0.5/540.6MB) ├────────────────────────────────────────┤[1/8]   23 kB/s

**Comment by luhy118** [comment]
腾讯视频最近几天都是下载变得好慢慢，好像是给限制速度

**Comment by lll423** [comment]
@huzy0909  你发的这个连接简直是龟速。  23k 还死在那里不动

![1](https://user-images.githubusercontent.com/4048921/33165007-378078e6-d070-11e7-8187-53e6f4ee705a.png)

**Comment by huzy0909** [comment]
@lll423 我也是23K，还以为就我速度慢呢

**Comment by jyuan15** [comment]
https://v.qq.com/x/cover/g7m84rhikqkd772/t0025z41zak.html 用IDM下载，速度还可以

![2017-11-23_192756](https://user-images.githubusercontent.com/12642186/33170788-8ea01a46-d084-11e7-868d-90dbd47775f5.jpg)
