### ISSUE TITLE
爱奇艺视频下载出错

### ISSUE THREAD

**Issue by C-racker** [soimort/you-get#2497]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

C:\>you-get --debug http://www.iqiyi.com/v_19rrehvu3c.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rrehvu3c.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/842179700
[DEBUG] get_content: http://www.iqiyi.com/v_19rrehvu3c.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/842179700/cd4601ed5229c2c6ce3318db4c27a245/?t=1511015225893&sc=1fa8266dc8f1f20a61c6afd08fedab89&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               极限挑战第3季_20171117期
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      m3u8_url:      http://cache.m.iqiyi.com/mus/205994601/7641fbab373b70932efd769eb113e0c7/afbe8fd3d73448c9//20171117/dc/8a/57217adf80af99dd19a362a412dfa511.m3u8?qd_originate=tmts_py&tvid=842179700&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1511015225962&qd_p=df58e308&qd_asc=8b04a4c7ee1fcea31e2c58df57aaaee4&qypid=842179700_04022000001000000000_14&qd_k=1fa8266dc8f1f20a61c6afd08fedab89&qd_s=otv&vf=3b1f010e4b0fb304f7372fc9e782e6d8&np_tag=nginx_part_tag
    # download-with: you-get --format=TD [URL]

you-get: version 0.4.964, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.iqiyi.com/v_19rrehvu3c.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\users\liyang\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\liyang\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Liyang\AppData\Local\Programs\Python\Python37\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\liyang\appdata\local\programs\python\python37\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\liyang\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 1368, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\liyang\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 1276, in script_main
    **extra
  File "c:\users\liyang\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 1078, in download_main
    download(url, **kwargs)
  File "c:\users\liyang\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 1361, in any_download
    m.download(url, **kwargs)
  File "c:\users\liyang\appdata\local\programs\python\python37\lib\site-packages\you_get\extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "c:\users\liyang\appdata\local\programs\python\python37\lib\site-packages\you_get\extractors\iqiyi.py", line 209, in download
    download_url_ffmpeg(urls[0], self.title, 'mp4', output_dir=kwargs['output_dir'], merge=kwargs['merge'], stream=False)
  File "c:\users\liyang\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 903, in download_url_ffmpeg
    assert has_ffmpeg_installed(), "FFmpeg not installed."
AssertionError: FFmpeg not installed.

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 最新版本还是无法下载爱奇艺视频

**Comment by Kara-ism** [comment]
Same problems here,

> $ python3 you-get 'http://www.iqiyi.com/v_19rreo9xf8.html' --debug
[DEBUG] get_response: http://www.iqiyi.com/v_19rreo9xf8.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/848754200
[DEBUG] get_content: http://www.iqiyi.com/v_19rreo9xf8.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/848754200/049215e7f9b3d4da4560ba8d3f1a8d01/?t=1511708910914&sc=9885656faee968202ca55e17f9fddbe9&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.iqiyi.com/v_19rreo9xf8.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/Kara-ism/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/Kara-ism/you-get/src/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/home/Kara-ism/you-get/src/you_get/common.py", line 1270, in script_main
    **extra
  File "/home/Kara-ism/you-get/src/you_get/common.py", line 1072, in download_main
    download(url, **kwargs)
  File "/home/Kara-ism/you-get/src/you_get/common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "/home/Kara-ism/you-get/src/you_get/extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "/home/Kara-ism/you-get/src/you_get/extractors/iqiyi.py", line 209, in download
    download_url_ffmpeg(urls[0], self.title, 'mp4', output_dir=kwargs['output_dir'], merge=kwargs['merge'], stream=False)
  File "/home/Kara-ism/you-get/src/you_get/common.py", line 897, in download_url_ffmpeg
    assert has_ffmpeg_installed(), "FFmpeg not installed."
AssertionError: FFmpeg not installed.
