### ISSUE TITLE
PPTV下载返回405

### ISSUE THREAD

**Issue by KaminoDice** [soimort/you-get#2500]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
`$ you-get -d "http://v.pptv.com/show/54x6ibdvwibzmcGoI.html"
[DEBUG] get_content: http://v.pptv.com/show/54x6ibdvwibzmcGoI.html
[DEBUG] get_content: http://web-play.pptv.com/webplay3-0-26978791.xml?appplt=flp&appid=pptv.flashplayer.vod&appver=3.4.2.28&typ e=&version=4
site:                PPTV
title:               英超-1718赛季-联赛-第12轮-阿森纳vs热刺-全场（詹俊 张路）
stream:
    - format:        3
      container:     mp4
      video-profile: 1920x1080@2442kbps
      size:          2351.8 MiB (2466044149 bytes)
    # download-with: you-get --format=3 [URL]

Downloading 英超-1718赛季-联赛-第12轮-阿森纳vs热刺-全场（詹俊 张路）.mp4 ...
 0.0% (   0.0/2351.8MB) ├─────────────────────────────────────────────────────────────────────────────────┤[  1/112] [DEBUG] HT TP Error with code405
[DEBUG] HTTP Error with code405
[DEBUG] HTTP Error with code405
you-get: version 0.4.964, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://v.pptv.com/show/54x6ibdvwibzmcGoI.html'], cookies=None, debug=True, extractor_proxy=None, force =False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merg e=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, st ream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1368, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1276, in script_main
    **extra
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1078, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1361, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/extractor.py", line 228, in download
    av=stream_id in self.dash_streams)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 803, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 539, in url_save
    file_size = url_size(url, faker=faker, headers=tmp_headers)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 443, in url_size
    response = urlopen_with_retry(url)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 357, in urlopen_with_retry
    raise http_error
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 348, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 470, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 508, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 588, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 405: Not Allowed`
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:
@soimort-bot test this: http://v.pptv.com/show/54x6ibdvwibzmcGoI.html
> [您的内容]
> [舔 :icecream:!]

**Comment by tcsp** [comment]
碰到了同样的问题，希望可以解决下
