### ISSUE TITLE
优酷视频 mp4hd3/mp4hd2 格式无法拼接，其他格式正常。

### ISSUE THREAD

**Issue by XGHeaven** [soimort/you-get#2509]
在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
$ you-get -c cookies.sqlite "http://v.youku.com/v_show/id_XMzE0ODM1ODg1Ng\=\=.html\?spm\=a2h1n.8261147.0.0" --debug
you-get: Found cna in imported cookies. Use it
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzE0ODM1ODg1Ng&ccode=0502&client_ip=192.168.1.1&utid=c%2BCbEr2JtAkCAXAKg8KABAj1&client_ts=1511322911
site:                优酷 (Youku)
title:               功守道
stream:
    - format:        mp4hd3
      container:     mp4
      video-profile: 1080P
      size:          309.4 MiB (324457099 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMzE0ODM1ODg1Ng%3D%3D&type=hd3&ups_client_netip=700a839d&ups_ts=1511322911&utid=c%2BCbEr2JtAkCAXAKg8KABAj1&ccode=0502&psid=37af3f8434d21802962fa4d892c2fa5f&ups_userid=129270605&ups_ytid=709886597&duration=1365&expire=18000&ups_key=496715852b2da413a59b053d5281ad71
    # download-with: you-get --format=mp4hd3 [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XMzE0ODM1ODg1Ng==

Downloading 功守道.mp4 ...
 100% (309.4/309.4MB) ├████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[10/10]    2 GB/s
Merging video parts...
./功守道[00].mp4
you-get: version 0.4.964, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://v.youku.com/v_show/id_XMzE0ODM1ODg1Ng\\=\\=.html\\?spm\\=a2h1n.8261147.0.0'], cookies='cookies.sqlite', debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.964', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/common.py", line 1368, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/common.py", line 1276, in script_main
    **extra
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/common.py", line 1078, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/common.py", line 1361, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/extractors/youku.py", line 305, in youku_download_by_url
    Youku().download_by_url(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/extractor.py", line 228, in download
    av=stream_id in self.dash_streams)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/common.py", line 843, in download_urls
    concat_mp4(parts, output_filepath)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 914, in concat_mp4
    merge_mp4s(mp4s, output)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 876, in merge_mp4s
    mp4s = list(map(read_mp4, ins))
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 717, in read_mp4
    atoms = parse_atoms(stream)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 708, in parse_atoms
    atom = read_atom(stream)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/processor/join_mp4.py", line 700, in read_atom
    raise NotImplementedError('%s: %d' % (type, left))
NotImplementedError: b'\x05\x00\x00\x00': 1179407865
```

我测试过了 《功守道》 和 《战狼2》，因为我是优酷会员，所以我测试了一个需要会员，一个不需要的。
发现都是相同的问题，就是如果是 `mp4hd3` 的格式，可以下载但是无法拼接，会提示上面的那个错误。但是如果改成 `mp4hd3v2` 的格式，那么拼接正常，没有任何问题。

刚刚又测试一下，发现 `mp4hd2` 也是一样的问题，必须要用 `mp4hd2v2` 才可以。

不清楚这是优酷的问题还是其他原因。

**Comment by huzy0909** [comment]
我测试了一下，可以正常下载，也可以正常合并
 you-get http://v.youku.com/v_show/id_XMzE0ODM1ODg1Ng/=/=.html/?spm\=a2h1n.8261147.0.0
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
site:                优酷 (Youku)
title:               功守道
stream:
    - format:        mp4hd3
      container:     mp4
      video-profile: 1080P
      size:          309.4 MiB (324457099 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMzE0ODM1ODg1Ng%3D%3D&type=hd3&ups_client_netip=7b96294c&ups_ts=1511336161&utid=3BacEkONj2ECAXuWKUyLbtx%2F&ccode=0502&psid=22c7860e23d527bd7745e304eba3e028&duration=1365&expire=18000&ups_key=2a999b57d79fb1e829563ce0b67aea1a
    # download-with: you-get --format=mp4hd3 [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XMzE0ODM1ODg1Ng==

Downloading 功守道.mp4 ...
 100% (309.4/309.4MB) ├██████████████████████████████████████┤[10/10]    2 MB/s
Merging video parts... Merged into 功守道.mp4

**Comment by XGHeaven** [comment]
@huzy0909 Thanks, 我知道什么原因了，原来我没装 ffmpeg。不过很奇怪的是，就算是没装，有一些格式的 mp4 文件还是可以进行拼接的，很神奇。
