### ISSUE TITLE
优酷无法下载，提示ssl错误。

### ISSUE THREAD

**Issue by aaron111com** [soimort/you-get#2514]
系统osx，homebrew安装的you-get

alexmbp:www alexhe$ you-get http://v.youku.com/v_show/id_XMzMyMjc0ODM2.html --debug

[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzMyMjc0ODM2&ccode=0502&client_ip=192.168.1.1&utid=dmedEiL7vz0CAWVR64I1Hn/x&client_ts=1511422332
you-get: version 0.4.964, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://v.youku.com/v_show/id_XMzMyMjc0ODM2.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.964', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/common.py", line 1368, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/common.py", line 1276, in script_main
    **extra
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/common.py", line 1078, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/common.py", line 1361, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/extractors/youku.py", line 305, in youku_download_by_url
    Youku().download_by_url(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/extractors/youku.py", line 165, in prepare
    self.youku_ups()
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/extractors/youku.py", line 93, in youku_ups
    api_meta = json.loads(get_content(url, headers=headers))
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/common.py", line 378, in get_content
    response = urlopen_with_retry(req)
  File "/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/common.py", line 348, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

**Comment by huzy0909** [comment]
这是个收费的吧，只能看前10几分钟，我这边可以下载前12分钟 win7系统

 you-get http://v.youku.com/v_show/id_XMzMyMjc0ODM2.html
you-get: mp4hd is a preview
you-get: mp4hd2 is a preview
you-get: flvhd is a preview
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
site:                优酷 (Youku)
title:               异形大战铁血战士
stream:
    - format:        mp4hd2
      container:     mp4
      video-profile: 超清
      size:          936.0 MiB (981479190 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMzMyMjc0ODM2&type=hd2&ups_client_netip=7b96294c&ups_ts=1511425383&utid=ZHOdEhW82UkCAXuWKUyIWxvY&ccode=0406&psid=011cf5c7dbb70410c195e9305c2f79e5&duration=6520&expire=18000&ups_key=eb22d77798d18228567f9b4839d031a4
    # download-with: you-get --format=mp4hd2 [URL]

audio-languages:
    - lang:          英语
      download-url:  http://v.youku.com/v_show/id_XMzMyMjc0ODM2

    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XNDI4MTEwMTEy

Downloading 异形大战铁血战士.mp4 ...
11.4% (106.3/936.0MB) ├█████───────────────────────────────────┤[4/4]    2 MB/s
Merging video parts... Merged into 异形大战铁血战士.mp4

**Comment by lki2019** [comment]
VIP视频 这是···
大哥 你这命令肯定不能下载啊
