### ISSUE TITLE
视频下载后分段无法合并

### ISSUE THREAD

**Issue by icase** [soimort/you-get#2516]
新电脑，Windows10系统，通过python安装，一开始还可以使用，但是用了一会出现分段正常下载，但无法合并的问题，麻烦帮忙看一下，十分感谢。

Debug信息：

you-get: version 0.4.964, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://v.youku.com/v_show/id_XMjYzMDUzNzIxMg==.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Work\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1368, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1276, in script_main
    **extra
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1078, in download_main
    download(url, **kwargs)
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1361, in any_download
    m.download(url, **kwargs)
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\youku.py", line 305, in youku_download_by_url
    Youku().download_by_url(url, **kwargs)
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractor.py", line 228, in download
    av=stream_id in self.dash_streams)
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 843, in download_urls
    concat_mp4(parts, output_filepath)
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\processor\join_mp4.py", line 914, in concat_mp4
    merge_mp4s(mp4s, output)
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\processor\join_mp4.py", line 876, in merge_mp4s
    mp4s = list(map(read_mp4, ins))
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\processor\join_mp4.py", line 717, in read_mp4
    atoms = parse_atoms(stream)
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\processor\join_mp4.py", line 708, in parse_atoms
    atom = read_atom(stream)
  File "c:\users\Work\appdata\local\programs\python\python36-32\lib\site-packages\you_get\processor\join_mp4.py", line 700, in read_atom
    raise NotImplementedError('%s: %d' % (type, left))
NotImplementedError: b'\x05\x00\x00\x00': 1179407865

**Comment by huzy0909** [comment]
FFmpeg安装了吗

**Comment by icase** [comment]
@huzy0909装了啊，才安装的时候已经下了几个视频了，都正常。

**Comment by mengmo** [comment]
@icase `ffmpeg`的路径添加到系统环境变量的`PATH`中没？
当前项目中有可以处理部分`mp4`格式文件的代码，所以没装`ffmpeg`或者`ffmpeg`没有正确安装的情况下也是能合并的

**Comment by lisaction** [comment]
遇到同样的问题。确定ffmpeg已经添加到系统环境变量中，同时是最新版本的you-get。

**Comment by mengmo** [comment]
我这儿试了上边给的链接，没有出现问题
@lisaction 你添加的路径是这样的`...\FFmpeg\bin`还是这样的`...\FFmpeg`
无论添加什么样的路径，都应该保证`ffmpeg.exe`就在所添加的路径下
还有另外一种情况：Windows 在`环境变量`中添加路径后，只有在新打开的`命令提示符`中才能生效，原来已经开启的`命令提示符`并不能应用所做的改动

**Comment by jyuan15** [comment]
换个ffmpeg版本

**Comment by icase** [comment]
@mengmo 我直接把ffmpeg.exe放到system32文件夹里了，然后在cmd里就可以正常调用ffmpeg了啊，以前我在其他电脑上也是这么操作的。同样是windows10

**Comment by mengmo** [comment]
从 log 的内容来看，视频下载完成后并未调用 ffmpeg，而是使用了 you-get 内部的合并功能

**Comment by lisaction** [comment]
@mengmo  问题解决，十分感谢。
我是有段时间没有使用you-get，最近下载youku上的某视频出现问题，于是更新you-get成功下载之后发现merge失败，log和楼主的一样。
然后我又去下载了最新版本ffmepg同时添加到系统环境变量中。
之前还失败是因为没有重启cmd, 重启cmd之后一切正常。
希望也帮助楼主。
