### ISSUE TITLE
[Failed] Sohu

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#353]
```sh
$ you-get -i http://tv.sohu.com/20140629/n401523369.shtml\?txid\=8254069965286abe9ee523a73c256ea7
Traceback (most recent call last):
  File "/home/soimort/Projects/you-get/you-get", line 10, in <module>
    main()
  File "/home/soimort/Projects/you-get/src/you_get/extractor/__main__.py", line 94, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 937, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 803, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractor/__main__.py", line 87, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractor/sohu.py", line 18, in sohu_download
    html = get_html(url)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 182, in get_html
    content = get_response(url, faker).data
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 170, in get_response
    response = request.urlopen(url)
  File "/home/soimort/.linuxbrew/Cellar/python3/3.4.1/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/home/soimort/.linuxbrew/Cellar/python3/3.4.1/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/home/soimort/.linuxbrew/Cellar/python3/3.4.1/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/soimort/.linuxbrew/Cellar/python3/3.4.1/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/home/soimort/.linuxbrew/Cellar/python3/3.4.1/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/home/soimort/.linuxbrew/Cellar/python3/3.4.1/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pastebt** [comment]
是的，需要在get_decoded_html的时候用国内的代理，怎么改一下把--extractor-proxy传进去，看来要改一下结构，用VideoExtractor

**Comment by soimort** [comment]
Fixed by #489.
