### ISSUE TITLE
下载搜狐视频报错

### ISSUE THREAD

**Issue by ShijieLi** [soimort/you-get#456]
Video Site: Sohu.com
Title:      破产姐妹第4季第6集
Type:       MPEG-4 video (video/mp4)
Size:       158.71 MiB (166423559 Bytes)

Downloading 破产姐妹第4季第6集.mp4 ...
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1232, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1065, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1103, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 841, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 819, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 509, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 500, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 996, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 784, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 989, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/sohu.py", line 55, in sohu_download
    download_urls(urls, title, 'mp4', size, output_dir, refer = url, merge = merge)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 523, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 267, in url_save
    file_size = url_size(url, faker = faker)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 200, in url_size
    response = request.urlopen(url)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1258, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1235, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] No route to host>

**Comment by tpof314** [comment]
我这两天下载搜狐视频，也是出现错误，不过我出的错误不太一样。
大神可以看看这个链接：http://tv.sohu.com/20150117/n407865799.shtml

**Comment by pastebt** [comment]
贴你的错误出来，或者试试加了我的那个patch后，用一个proxy, 我拿到这个：

python3 you-get -y '211.155.86.25:8888' -i http://tv.sohu.com/20150117/n407865799.shtml
Video Site: Sohu.com
Title:      美少女战士Crystal第14集
Type:       MPEG-4 video (video/mp4)
Size:       365.11 MiB (382843757 Bytes)

应该是可以下了

**Comment by soimort** [comment]
Fixed by #489.
