### ISSUE TITLE
ubuntu下使用python3.2环境，出错

### ISSUE THREAD

**Issue by hanshui** [soimort/you-get#471]
Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/git/you-get/src/you_get/__main__.py", line 91, in main
    main()
  File "/git/you-get/src/you_get/common.py", line 999, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/git/you-get/src/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/git/you-get/src/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/git/you-get/src/you_get/common.py", line 992, in any_download
    m.download(url, **kwargs)
  File "/git/you-get/src/you_get/extractors/acfun.py", line 70, in acfun_download
    acfun_download_by_vid(p_vid, p_title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/git/you-get/src/you_get/extractors/acfun.py", line 38, in acfun_download_by_vid
    letvcloud_download_by_vu(sourceId, title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/git/you-get/src/you_get/extractors/letv.py", line 77, in letvcloud_download_by_vu
    urls = [base64.b64decode(sorted(type_available, key = lambda x:x['video_quality'])[-1]['video_url']).decode("utf-8")]
  File "/usr/lib/python3.2/base64.py", line 83, in b64decode
    raise TypeError("expected bytes, not %s" % s.__class__.__name__)
TypeError: expected bytes, not str

**Comment by soimort** [comment]
请提供视频地址。

**Comment by soimort** [comment]
(might be) fixed by #480
