### ISSUE TITLE
播放爱奇艺视频报错

### ISSUE THREAD

**Issue by imzf** [soimort/you-get#481]
you-get -p mpv "http://www.iqiyi.com/v_19rrnuy9co.html"
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 784, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 991, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/iqiyi.py", line 98, in iqiyi_download
    assert vlink.endswith(".f4v")
AssertionError

**Comment by soimort** [comment]
Closed via #482
