### ISSUE TITLE
新浪视频UnicodeDecodeError

### ISSUE THREAD

**Issue by Geew** [soimort/you-get#500]
URL: http://video.sina.com.cn/news/spj/topvideoes20150304/?opsubject_id=top1#137380095  

File "/usr/local/lib/python3.2/dist-packages/you_get-0.3.32-py3.2.egg/you_get/**main**.py", line 91, in main
    main()
  File "/usr/local/lib/python3.2/dist-packages/you_get-0.3.32-py3.2.egg/you_get/common.py", line 999, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.2/dist-packages/you_get-0.3.32-py3.2.egg/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.2/dist-packages/you_get-0.3.32-py3.2.egg/you_get/common.py", line 785, in download_main
    download(url, *_kwargs)
  File "/usr/local/lib/python3.2/dist-packages/you_get-0.3.32-py3.2.egg/you_get/common.py", line 992, in any_download
    m.download(url, *_kwargs)
  File "/usr/local/lib/python3.2/dist-packages/you_get-0.3.32-py3.2.egg/you_get/extractors/sina.py", line 67, in sina_download
    video_page = get_content(url)
  File "/usr/local/lib/python3.2/dist-packages/you_get-0.3.32-py3.2.egg/you_get/common.py", line 191, in get_content
    data = data.decode(charset)
UnicodeDecodeError: 'gb2312' codec can't decode bytes in position 54627-54628: illegal multibyte sequence

**Comment by Geew** [comment]
get_content 函数 decode使用: data = data.decode('GB18030')就行了, 但是下面接下来的请求会报超时错误:


Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/gowin/project/videoGet/libGit/you-get/src/you_get/__main__.py", line 91, in main
    main()
  File "/home/gowin/project/videoGet/libGit/you-get/src/you_get/common.py", line 1005, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/gowin/project/videoGet/libGit/you-get/src/you_get/common.py", line 899, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/gowin/project/videoGet/libGit/you-get/src/you_get/common.py", line 791, in download_main
    download(url, **kwargs)
  File "/home/gowin/project/videoGet/libGit/you-get/src/you_get/common.py", line 998, in any_download
    m.download(url, **kwargs)
  File "/home/gowin/project/videoGet/libGit/you-get/src/you_get/extractors/sina.py", line 79, in sina_download
    sina_download_by_vkey(vkey, title=title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/gowin/project/videoGet/libGit/you-get/src/you_get/extractors/sina.py", line 55, in sina_download_by_vkey
    type, ext, size = url_info(url)
  File "/home/gowin/project/videoGet/libGit/you-get/src/you_get/common.py", line 222, in url_info
    response = request.urlopen(request.Request(url))
  File "/usr/lib/python3.2/urllib/request.py", line 138, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.2/urllib/request.py", line 369, in open
    response = self._open(req, data)
  File "/usr/lib/python3.2/urllib/request.py", line 387, in _open
    '_open', req)
  File "/usr/lib/python3.2/urllib/request.py", line 347, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 1155, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.2/urllib/request.py", line 1138, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by soimort** [comment]
不止是编码的问题，看起来新浪视频的解析方法已经过时了。

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/you-get/blob/master/src/you_get/extractors/sina.py

**Comment by rosynirvana** [comment]
这个是因为没抓到vid所以代码跑错分支了
其实url里sharp后面的137380095就是vid
不知道```re.search(r'#(\d+)', url)```这种处理方法是不是太粗糙

**Comment by soimort** [comment]
Closed via #1982.
