### ISSUE TITLE
爱奇艺视频无法解析

### ISSUE THREAD

**Issue by tyang34** [soimort/you-get#519]
错误信息如下： 
$ you-get http://www.iqiyi.com/v_19rrnscu0w.html
Traceback (most recent call last):
  File "/usr/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.3.32', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.4/site-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1000, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 993, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/extractors/iqiyi.py", line 79, in iqiyi_download
    assert info["code"] == "A000000"
AssertionError

**Comment by tyang34** [comment]
问题并没有解决，请帮忙看一看
错误信息：
$ you-get http://www.iqiyi.com/v_19rrnscu0w.html
Traceback (most recent call last):
  File "/usr/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.3.32', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.4/site-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 994, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/extractors/iqiyi.py", line 91, in iqiyi_download
    assert info["code"] == "A000000"
AssertionError

**Comment by jackyzy823** [comment]
爱奇艺在5/14又更改了一次enc key 。目前做了自动解析swf中的enc key。在 #523 中实现，已提交PR。如果急用可 `git clone -b iqiyi-key-again https://github.com/jackyzy823/you-get/` 这个版本使用。

**Comment by tyang34** [comment]
@jackyzy823 可以用，十分感谢

**Comment by nutcrackers2** [comment]
谢谢辛苦了
