### ISSUE TITLE
[Broken] bilibili

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#521]
Not having enough time / bandwidth to look into this right now (or to review the rest of PRs). Still, the issue is there.

```
$ ./you-get -i www.bilibili.com/video/av2319861/
Traceback (most recent call last):
  File "./you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get-develop/src/you_get/__main__.py", line 91, in main
    main()
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 994, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/extractors/bilibili.py", line 130, in bilibili_download
    title = unescape_html(title)
  File "/usr/lib/python3.4/html/__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by sffxzzp** [comment]
Invalid appkey caused this issue.
