### ISSUE TITLE
acfun 解析失败

### ISSUE THREAD

**Issue by rchen9012** [soimort/you-get#530]
acfun的解析已经失败，有没有新版更新？

python3 you-get http://www.acfun.tv/v/ac1105608
Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/var/www/docs/you-get-develop/src/you_get/__main__.py", line 91, in main
    main()
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 994, in any_download
    m.download(url, **kwargs)
  File "/var/www/docs/you-get-develop/src/you_get/extractors/acfun.py", line 126, in acfun_download
    acfun_download_by_vid(p_vid, p_title, output_dir=output_dir, merge=merge, info_only=info_only ,**kwargs)
  File "/var/www/docs/you-get-develop/src/you_get/extractors/acfun.py", line 67, in acfun_download_by_vid
    info = json.loads(get_content("http://jiexi.acfun.info/index.php?vid={}".format(vid)))
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 177, in get_content
    response = request.urlopen(req)
  File "/usr/local/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by zhjawe** [comment]
这个问题确实让头皮发麻啊。

**Comment by cnbeining** [comment]
For reference only:

因为letvcloud的变化，造成acfun大量解析失败；

这造成之前的一次revert，尝试使用一个已经关闭的API进行解析，造成更大范围的失败。

看看现在能不能好了。

**Comment by zhjawe** [comment]
问题依旧啊。
