### ISSUE TITLE
ffmpeg 合并视频失败

### ISSUE THREAD

**Issue by gmg137** [soimort/you-get#541]
###这个问题其实已经好长时间了，本来以为是ffmpeg版本问题，但换了几个版本和源还是不行。
```
100.0% (196.4/196.4MB) [========================================] 7/7
ffmpeg version 2.6.3 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (SUSE Linux)
  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg --extra-cflags='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g' --optflags='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g' --enable-pic --disable-stripping --enable-shared --disable-static --enable-runtime-cpudetect --enable-gpl --disable-openssl --enable-avresample --enable-frei0r --enable-gnutls --enable-libcdio --enable-libdc1394 --enable-libfreetype --enable-libgsm --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvpx --enable-pic --enable-pthreads --enable-vaapi --enable-vdpau --disable-encoders --disable-decoders --disable-muxers --disable-demuxers --enable-encoder='flac,gif,jpegls,libopenjpeg,libtheora,libvorbis,libvpx,png' --enable-decoder='flac,gif,jpegls,ljpeg,libopenjpeg,libtheora,libvpx,png,vorbis,vp3,vp5,vp6,vp6a,vp6f,vp8,vp9,webp' --enable-muxer='flac,gif,image2,image2pipe,matroska,matroska_audio,null,webm' --enable-demuxer='flac,gif,image2,image2pipe,matroska' --enable-x11grab
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Unknown input format: 'concat'
Traceback (most recent call last):
  File "./project/git/you-get/you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/gmg/project/git/you-get/src/you_get/__main__.py", line 91, in main
    main()
  File "/home/gmg/project/git/you-get/src/you_get/common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/gmg/project/git/you-get/src/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/gmg/project/git/you-get/src/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/home/gmg/project/git/you-get/src/you_get/common.py", line 994, in any_download
    m.download(url, **kwargs)
  File "/home/gmg/project/git/you-get/src/you_get/extractor.py", line 46, in download_by_url
    self.download(**kwargs)
  File "/home/gmg/project/git/you-get/src/you_get/extractor.py", line 172, in download
    download_urls(urls, self.title, self.streams[stream_id]['container'], self.streams[stream_id]['size'], output_dir=kwargs['output_dir'], merge=kwargs['merge'])
  File "/home/gmg/project/git/you-get/src/you_get/common.py", line 535, in download_urls
    ffmpeg_concat_flv_to_mp4(parts, os.path.join(output_dir, title + '.mp4'))
  File "/home/gmg/project/git/you-get/src/you_get/processor/ffmpeg.py", line 116, in ffmpeg_concat_flv_to_mp4
    raise
RuntimeError: No active exception to reraise
```

**Comment by jackyzy823** [comment]
This reference may help: http://stackoverflow.com/a/20903614
>The error "Unknown input format: 'concat'" confirms that you don't have "concat" format enabled in your ffmpeg compilation.
>Check formats by using the command
>`ffmpeg -formats`

**Comment by gmg137** [comment]
这个链接之前已经看了，我可以确认版本是没问题的，2.6.3 版本应该是最新的了。

我是下载的优酷视频，flv 合并为 mp4时出的问题。

```ffmpeg -formats```

输出如下：

```
File formats:
 D. = Demuxing supported
 .E = Muxing supported
 --
 DE alsa            ALSA audio output
 D  asf             ASF (Advanced / Active Streaming Format)
 D  dv              DV (Digital Video)
 D  dv1394          DV1394 A/V grab
 DE fbdev           Linux framebuffer
  E ffm             FFM (FFserver live feed)
 DE flac            raw FLAC
 DE gif             GIF Animation
 DE image2          image2 sequence
 DE image2pipe      piped image2 sequence
 D  jack            JACK Audio Connection Kit
 D  lavfi           Libavfilter virtual input device
 D  libcdio          
 D  libdc1394       dc1394 v.2 A/V grab
  E matroska        Matroska
 D  matroska,webm   Matroska / WebM
 D  mov,mp4,m4a,3gp,3g2,mj2 QuickTime / MOV
 D  mpegts          MPEG-TS (MPEG-2 Transport Stream)
  E null            raw null video
 DE oss             OSS (Open Sound System) playback
 DE pulse           Pulse audio output
 D  rm              RealMedia
 D  rtsp            RTSP input
  E sdl             SDL output device
  E v4l2            Video4Linux2 output device
 D  video4linux2,v4l2 Video4Linux2 device grab
  E webm            WebM
 D  x11grab         X11 screen capture, using XCB
```

**Comment by jackyzy823** [comment]
Would you please provide your video url?

**Comment by jackyzy823** [comment]
I compile ffmpeg from http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2  in my centos by `./configure --disable-yasm && make`  and then `ffmpeg -formats`
Output:`D  concat          Virtual concatenation script` and works well for videos in youku .

it seems that your version of ffmpeg disable lots of demuxer with compile flag ,and only allow a few of them . `--disable-demuxers --enable-demuxer='flac,gif,image2,image2pipe,matroska'` in your ffmpeg output. Just guess ,not sure.

**Comment by soimort** [comment]
Legal craps.

ffmpeg shipped with OpenSUSE is simply useless, it was built without support of any patented or proprietary media formats (FLV is just one of them).

Have you tried to install ffmpeg from http://opensuse-community.org/ ?

**Comment by gmg137** [comment]
所有优酷链接都不行。
我使用的ffmpeg是packman源的，应该不存在版权造成的阉割问题。

**Comment by soimort** [comment]
@gmg137
从你的`ffmpeg -formats`输出来看，很明显是阉割版的。正常情况下至少要有`flv`支持。

```
 DE flv             FLV (Flash Video)
 D concat Virtual concatenation script
```

**Comment by gmg137** [comment]
还真是，没想到packman源的ffmpeg竟然也是阉割版，，，，，话说以前都是没问题的，也不知从哪个版本开始给去除了。
