### ISSUE TITLE
爱奇艺无法下载

### ISSUE THREAD

**Issue by nuomi1** [soimort/you-get#547]
zshrc 已设置「export LANG=en_US.UTF-8」，优酷正常。

you-get -n  http://www.iqiyi.com/v_19rrnrd84c.html                
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 994, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/extractors/iqiyi.py", line 94, in iqiyi_download
    enc_key = getEncKey(swflink)
  File "/usr/local/lib/python3.4/site-packages/you_get/extractors/iqiyi.py", line 85, in getEncKey
    return key.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by jackyzy823** [comment]
Please update to the latest version. Cause iqiyi changed its encryt method in 6/12 in #542.

**Comment by nuomi1** [comment]
OK.
