### ISSUE TITLE
爱奇艺无法下载

### ISSUE THREAD

**Issue by nuomi1** [soimort/you-get#551]
已更新最新版本。
顺便优酷解析明明是 hd3，下载的却是 3gphd。运营商 Cache 的问题？
————————————————————
you-get http://www.iqiyi.com/v_19rroga6ew.html
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/you-get/you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/usr/local/lib/python3.4/site-packages/you-get/src/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/site-packages/you-get/src/you_get/common.py", line 1018, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/site-packages/you-get/src/you_get/common.py", line 909, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/site-packages/you-get/src/you_get/common.py", line 801, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you-get/src/you_get/common.py", line 1011, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you-get/src/you_get/extractors/iqiyi.py", line 111, in iqiyi_download
    assert info["code"] == "A000000"
AssertionError
————————————————————
you-get -i http://v.youku.com/v_show/id_XMTI2NjMwMTAxNg\=\=.html
site:                优酷 (Youku)
title:               「ZEALER | Media 出品」聊聊 2K 那些事儿
streams:             # Available quality and codecs
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          333.3 MiB (349443719 bytes)
    # download-with: you-get --format=hd3 [URL]

    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          171.5 MiB (179792069 bytes)
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          78.5 MiB (82338129 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flv
      container:     flv
      video-profile: 标清
      size:          41.0 MiB (42952020 bytes)
    # download-with: you-get --format=flv [URL]

    - format:        3gphd
      container:     3gp
      video-profile: 高清（3GP）
      size:          43.0 MiB (45139662 bytes)
    # download-with: you-get --format=3gphd [URL]

**Comment by yan12125** [comment]
Commit 2e8ffbed744d62507f4398bbc011c8c82fd681f9 愛奇藝可用：
```
$ you-get "http://www.iqiyi.com/v_19rrojlavg.html"
Video Site: iQIYI.com
Title:      美国德州空中惊现奇异云团 酷似UFO
Type:       Flash video (video/x-flv)
Size:       0.93 MiB (969972 Bytes)

Downloading 美国德州空中惊现奇异云团 酷似UFO.flv ...
100.0% (  0.9/0.9  MB) [========================================] 1/1
```
是否是另外的問題？

**Comment by nuomi1** [comment]
更新 2e8ffbed74 后爱奇艺正常。
优酷也正常，但没有看到修改相关代码，应该是运营商 Cache 的问题。
