### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by civalin** [soimort/you-get#552]
# input and error messages

```bash
civa@Mimir /media/sf_D_DRIVE/mtest $ you-get https://www.youtube.com/watch?v=GBauy0o-Wzs
site:                YouTube
title:               An Interview: How Foursquare uses MongoDB
stream:
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          487.9 MiB (511553862 bytes)
    # download-with: you-get --itag=22 [URL]

Downloading An Interview: How Foursquare uses MongoDB.mp4 ...
100.0% (487.9/487.9MB) [========================================] 1/1Traceback (most recent call last):
  File "/home/civa/.local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/civa/.local/lib/python3.4/site-packages/you_get/__main__.py", line 91, in main
    main()
  File "/home/civa/.local/lib/python3.4/site-packages/you_get/common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/civa/.local/lib/python3.4/site-packages/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/civa/.local/lib/python3.4/site-packages/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/home/civa/.local/lib/python3.4/site-packages/you_get/common.py", line 994, in any_download
    m.download(url, **kwargs)
  File "/home/civa/.local/lib/python3.4/site-packages/you_get/extractor.py", line 46, in download_by_url
    self.download(**kwargs)
  File "/home/civa/.local/lib/python3.4/site-packages/you_get/extractor.py", line 172, in download
    download_urls(urls, self.title, self.streams[stream_id]['container'], self.streams[stream_id]['size'], output_dir=kwargs['output_dir'], merge=kwargs['merge'])
  File "/home/civa/.local/lib/python3.4/site-packages/you_get/common.py", line 513, in download_urls
    url_save(url, filepath, bar, refer = refer, faker = faker)
  File "/home/civa/.local/lib/python3.4/site-packages/you_get/common.py", line 343, in url_save
    os.rename(temp_filepath, filepath)
OSError: [Errno 22] Invalid argument: './An Interview: How Foursquare uses MongoDB.mp4.download' -> './An Interview: How Foursquare uses MongoDB.mp4'
```

Look like `os.rename()` didn't support colon?

# system

- ubuntu gnome 15.04
- You-Get 0.3.33, a video downloader.
- python 3.4.3
- pip 1.5.6

**Comment by civalin** [comment]
Update: I run the script under a external ntfs partition.

ext4 partition are OK.

**Comment by soimort** [comment]
I'm reopening this - colons are special characters for specifying named data streams in NTFS, they [can't be used](http://unix.stackexchange.com/questions/114461/make-linux-forbid-colons-in-file-names-on-ntfs-partitions) as part of file names when mounting ntfs-3g with option `streams_interface=windows`. As they also cause issues under Windows. This must be fixed.
