### ISSUE TITLE
Can't download video from acfun ???

### ISSUE THREAD

**Issue by xnastudio** [soimort/you-get#553]
http://www.acfun.tv/v/ac1974994

**Comment by soimort** [comment]
Please attach your command line output.

**Comment by xnastudio** [comment]
you-get 'http://www.acfun.tv/v/ac1974994'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.3.31', 'console_scripts', 'you-get')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get-0.3.31-py3.4.egg/you_get/__main__.py", line 91, in main
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get-0.3.31-py3.4.egg/you_get/common.py", line 997, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get-0.3.31-py3.4.egg/you_get/common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get-0.3.31-py3.4.egg/you_get/common.py", line 784, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get-0.3.31-py3.4.egg/you_get/common.py", line 990, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get-0.3.31-py3.4.egg/you_get/extractors/acfun.py", line 70, in acfun_download
    acfun_download_by_vid(p_vid, p_title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get-0.3.31-py3.4.egg/you_get/extractors/acfun.py", line 38, in acfun_download_by_vid
    letvcloud_download_by_vu(sourceId, title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get-0.3.31-py3.4.egg/you_get/extractors/letv.py", line 75, in letvcloud_download_by_vu
    for i in info['data']['video_info']['media']:
TypeError: list indices must be integers, not str

**Comment by soimort** [comment]
`you-get==0.3.31` is too old. You should update to the latest release.

**Comment by xnastudio** [comment]
0.3.31 too old ?
I just downloaded it from Github.

**Comment by xnastudio** [comment]
I just download from github " Download as Zip" and it still display 0.3.31 ????????????

**Comment by xnastudio** [comment]
I use python3 you-get 'http://www.acfun.tv/v/ac1974994'   instead of you-get 'http://www.acfun.tv/v/ac1974994'         and now it is ok.
