### ISSUE TITLE
music.baidu.com not working

### ISSUE THREAD

**Issue by FatKiwi** [soimort/you-get#558]
you-get http://music.baidu.com/album/31214034

Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\you_get\__main__.py", line 91, in main
    main()
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 893, in script_ma
in
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 785, in download_
main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 994, in any_downl
oad
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractors\baidu.py", line 108, in
 baidu_download
    baidu_download_album(id, output_dir, merge, info_only)
  File "C:\Python34\lib\site-packages\you_get\extractors\baidu.py", line 73, in
baidu_download_album
    song_url = baidu_get_song_url(song_data)
  File "C:\Python34\lib\site-packages\you_get\extractors\baidu.py", line 21, in
baidu_get_song_url
    return data['songLink']
TypeError: 'NoneType' object is not subscriptable

----

you-get http://music.baidu.com/song/31214038

Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\you_get\__main__.py", line 91, in main
    main()
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 893, in script_ma
in
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 785, in download_
main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 994, in any_downl
oad
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractors\baidu.py", line 112, in
 baidu_download
    baidu_download_song(id, output_dir, merge, info_only)
  File "C:\Python34\lib\site-packages\you_get\extractors\baidu.py", line 51, in
baidu_download_song
    type, ext, size = url_info(url, faker=True)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 214, in url_info
    response = request.urlopen(request.Request(url, headers = fake_headers), Non
e)
  File "C:\Python34\lib\urllib\request.py", line 266, in __init__
    self.full_url = url
  File "C:\Python34\lib\urllib\request.py", line 292, in full_url
    self._parse()
  File "C:\Python34\lib\urllib\request.py", line 321, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'None'

**Comment by soimort** [comment]
Working well for me.

```
➜  Downloads git:(master) you-get http://music.baidu.com/song/31214038
Video Site: Baidu.com
Title:      Diamonds
Type:       MP3 (audio/mpeg)
Size:       3.44 MiB (3604988 Bytes)

Downloading Diamonds - Unapologetic - Rihanna.mp3 ...
100.0% (  3.4/3.4  MB) [========================================] 1/1
```

**Comment by FatKiwi** [comment]
Perhaps it's because It's restricted. But I've tried with China proxy too with same results.

**Comment by liushuyu** [comment]
It's working... Not broken...
$ ./you-get -d "http://music.baidu.com/song/31214038"
Site:       Baidu.com
Title:      Diamonds
Type:       MP3 (audio/mpeg)
Size:       3.44 MiB (3604988 Bytes)

Downloading Diamonds - Unapologetic - Rihanna.mp3 ...
100.0% (  3.4/3.4  MB) ├██████████████████████████████████████┤[1/1]  202 kB/s

**Comment by liushuyu** [comment]
This is not a problem for me. Everything just went well for me...
```
$ ./you-get http://music.baidu.com/album/31214034
Site:       Baidu.com
Title:      Phresh Out The Runway
Type:       MP3 (audio/mpeg)
Size:       3.4 MiB (3561128 Bytes)

Downloading 01.Phresh Out The Runway.mp3 ...
100.0% (  3.4/3.4  MB) ├██████████████████████████████████████┤[1/1]  727 kB/s

Site:       Baidu.com
Title:      Phresh Out The Runway
Type:       Unknown type (None)
Size:       0.0 MiB (4044 Bytes)

Downloading 01.Phresh Out The Runway.lrc ...
100.0% (  0.0/0.0  MB) ├██████████████████████████████████████┤[1/1]   14 kB/s

Site:       Baidu.com
Title:      Diamonds
Type:       MP3 (audio/mpeg)
Size:       8.59 MiB (9010454 Bytes)

Downloading 02.Diamonds.mp3 ...
100.0% (  8.6/8.6  MB) ├██████████████████████████████████████┤[1/1]    1 MB/s

Site:       Baidu.com
Title:      Diamonds
Type:       Unknown type (None)
Size:       0.0 MiB (2664 Bytes)

Downloading 02.Diamonds.lrc ...
100.0% (  0.0/0.0  MB) ├██████████████████████████████████████┤[1/1]   10 kB/s
...............
```

**Comment by FatKiwi** [comment]
Yes, we ruled that as a restriction to China only. Nothing can be done except VPN or Proxy manually set.

**Comment by liushuyu** [comment]
I think this should be closed ...

**Comment by rosynirvana** [comment]
api changed
```diff
diff --git a/src/you_get/extractors/baidu.py b/src/you_get/extractors/baidu.py
index d5efaf0..75144e3 100644
--- a/src/you_get/extractors/baidu.py
+++ b/src/you_get/extractors/baidu.py
@@ -38,7 +38,7 @@ def baidu_get_song_title(data):

 def baidu_get_song_lyric(data):
     lrc = data['lrcLink']
-    return None if lrc is '' else "http://music.baidu.com%s" % lrc
+    return None if lrc is '' else lrc


 def baidu_download_song(sid, output_dir='.', merge=True, info_only=False):
```
