### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by bubifengyun** [soimort/you-get#563]
you-get www.iqiyi.com/v_19rrooepqk.html#curid=362454700_972ca0e1b059a2d66d362bf3feedbf10 
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 994, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/iqiyi.py", line 94, in iqiyi_download
    enc_key = getEncKey(swflink)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/iqiyi.py", line 85, in getEncKey
    return key.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'

Hi, here is error, when watch 晓松奇谈。Thank you.

**Comment by soimort** [comment]
Should be fixed by #9394e2f.
