### ISSUE TITLE
letv filed

### ISSUE THREAD

**Issue by SuperN0va** [soimort/you-get#567]
Video Site: LeTV.com
Title:      乱步奇谭01
Type:       MPEG-4 video (video/mp4)
Size:       287.6 MiB (301566100 Bytes)

Downloading 乱步奇谭01.mp4 ...
100.0% (287.6/287.6MB) [========================================] 87/87
Merging video parts...
.\乱步奇谭01[00].mp4
Traceback (most recent call last):
  File "F:\python3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\python3\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "F:\python3\lib\site-packages\you_get\__main__.py", line 91, in main
    main()
  File "F:\python3\lib\site-packages\you_get\common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "F:\python3\lib\site-packages\you_get\common.py", line 893, in script_mai
n
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "F:\python3\lib\site-packages\you_get\common.py", line 785, in download_m
ain
    download(url, **kwargs)
  File "F:\python3\lib\site-packages\you_get\common.py", line 994, in any_downlo
ad
    m.download(url, **kwargs)
  File "F:\python3\lib\site-packages\you_get\extractors\letv.py", line 145, in l
etv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, i
nfo_only=info_only,**kwargs)
  File "F:\python3\lib\site-packages\you_get\extractors\letv.py", line 98, in le
tv_download_by_vid
    download_urls(urls, title, ext, size, output_dir=output_dir, merge=merge)
  File "F:\python3\lib\site-packages\you_get\common.py", line 553, in download_u
rls
    concat_mp4(parts, os.path.join(output_dir, title + '.mp4'))
  File "F:\python3\lib\site-packages\you_get\processor\join_mp4.py", line 914, i
n concat_mp4
    merge_mp4s(mp4s, output)
  File "F:\python3\lib\site-packages\you_get\processor\join_mp4.py", line 876, i
n merge_mp4s
    mp4s = list(map(read_mp4, ins))
  File "F:\python3\lib\site-packages\you_get\processor\join_mp4.py", line 717, i
n read_mp4
    atoms = parse_atoms(stream)
  File "F:\python3\lib\site-packages\you_get\processor\join_mp4.py", line 708, i
n parse_atoms
    atom = read_atom(stream)
  File "F:\python3\lib\site-packages\you_get\processor\join_mp4.py", line 700, i
n read_atom
    raise NotImplementedError('%s: %d' % (type, left))
NotImplementedError: b'\x00\x00\xb0\r': 1195376648
I have already upgraded into the latest virsion，but still can not download

**Comment by SuperN0va** [comment]
问题应该是出现在合并的时候，能够下载到所有分片，但是合并失败- -
