### ISSUE TITLE
pan/yun.baidu.com  解析有问题

### ISSUE THREAD

**Issue by rchen9012** [soimort/you-get#571]
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.3.34', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.2/site-packages/you_get-0.3.34-py3.2.egg/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.2/site-packages/you_get-0.3.34-py3.2.egg/you_get/common.py", line 1018, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.2/site-packages/you_get-0.3.34-py3.2.egg/you_get/common.py", line 909, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.2/site-packages/you_get-0.3.34-py3.2.egg/you_get/common.py", line 801, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.2/site-packages/you_get-0.3.34-py3.2.egg/you_get/common.py", line 1011, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.2/site-packages/you_get-0.3.34-py3.2.egg/you_get/extractors/baidu.py", line 96, in baidu_download
    if len(title.split('.')) > 1:
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by liushuyu** [comment]
Could be at least partially fixed in #1461
