### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by bubifengyun** [soimort/you-get#578]
you-get http://www.iqiyi.com/v_19rrnqzz0k.html#vfrm=2-3-0-1
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.3.33', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1018, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 909, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 801, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1011, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/iqiyi.py", line 108, in iqiyi_download
    assert info["code"] == "A000000"
AssertionError

**Comment by soimort** [comment]
This was fixed in #573.

**Comment by soimort** [comment]
This was fixed in #573.
