### ISSUE TITLE
tucao.py is broken

### ISSUE THREAD

**Issue by lianxiangru** [soimort/you-get#581]
Here is the Traceback:

```zsh
 ~ % you-get -i 'http://www.tucao.cc/play/h4054179/'
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1018, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 909, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 801, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1011, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/tucao.py", line 45, in tucao_download
    tucao_single_download(format_link,title,output_dir,merge,info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/tucao.py", line 31, in tucao_single_download
    urls.append(i.firstChild.nodeValue)
AttributeError: 'NoneType' object has no attribute 'nodeValue'
```

**Comment by jackyzy823** [comment]
```
you-get http://www.tucao.cc/play/h4054179/
Video Site: tucao.cc
Title:      【七月】出包王女 To Love Ru Darkness 2nd 03 【极影】
Type:       Flash video (video/f4v)
Size:       207.25 MiB (217314586 Bytes)

Downloading 【七月】出包王女 To Love Ru Darkness 2nd 03 【极影】.flv ...
  5.1% ( 10.5/207.2MB) [===                                     ] 1/8
```
Works fine for me . Feel free to reopen this issue if there are still some problems.
