### ISSUE TITLE
FAIL TO DOWNLOAD

### ISSUE THREAD

**Issue by KSK999** [soimort/you-get#583]
請問 這是本人網路問題還是SETTING上出問題了? 
之前也沒出現過這問題
C:\Users\XXX>set PYTHONIOENCODING=utf-8
C:\Users\XXX>you-get -i http://www.iqiyi.com/v_19rrn4p51g.html
Traceback (most recent call last):
  File "C:\Python34\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.3.33', 'console_scripts', 'you-get')()
  File "C:\Python34\lib\site-packages\you_get-0.3.33-py3.4.egg\you_get\__main__.
py", line 91, in main
    main()
  File "C:\Python34\lib\site-packages\you_get-0.3.33-py3.4.egg\you_get\common.py
", line 1018, in main
    script_main('you-get', any_download, any_download_playlist)
  File "C:\Python34\lib\site-packages\you_get-0.3.33-py3.4.egg\you_get\common.py
", line 909, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "C:\Python34\lib\site-packages\you_get-0.3.33-py3.4.egg\you_get\common.py
", line 801, in download_main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get-0.3.33-py3.4.egg\you_get\common.py
", line 1011, in any_download
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get-0.3.33-py3.4.egg\you_get\extractor
s\iqiyi.py", line 106, in iqiyi_download
    assert info["code"] == "A000000"
AssertionError

**Comment by bubifengyun** [comment]
爱奇艺过一段时间就没法使用you-get，我的也是这样的。之前是可以用的，一段时间不用，再用you-get到爱奇艺就不能用了。接着有人更新后，可以用了，现在这个又不可以使用了。

you-get http://www.iqiyi.com/v_19rrh4cjcc.html#vfrm=3-6-3-1
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.3.34', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.3.34-py3.4.egg/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 1018, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 909, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 801, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 1011, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.3.34-py3.4.egg/you_get/extractors/iqiyi.py", line 108, in iqiyi_download
    assert info["code"] == "A000000"
AssertionError
you-get http://www.iqiyi.com/v_19rrh4cjcc.html#vfrm=3-6-3-1
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.3.34', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.3.34-py3.4.egg/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 1018, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 909, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 801, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 1011, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.3.34-py3.4.egg/you_get/extractors/iqiyi.py", line 108, in iqiyi_download
    assert info["code"] == "A000000"
AssertionError
我的跟你的类似。

**Comment by KSK999** [comment]
忘了CLOSE ISSUE
參考這位朋友
https://github.com/soimort/you-get/issues/585
已解決
