### ISSUE TITLE
关于风行的解析：我好像引入了个Bug

### ISSUE THREAD

**Issue by cnbeining** [soimort/you-get#607]
```you-get http://www.acfun.tv/v/ac1411054
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.3/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.3.34', 'console_scripts', 'you-get')()
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/you_get-0.3.34-py3.3.egg/you_get/__main__.py", line 91, in main
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/you_get-0.3.34-py3.3.egg/you_get/common.py", line 1026, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/you_get-0.3.34-py3.3.egg/you_get/common.py", line 915, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/you_get-0.3.34-py3.3.egg/you_get/common.py", line 807, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/you_get-0.3.34-py3.3.egg/you_get/common.py", line 1018, in any_download
    m, url = url_to_module(url)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/you_get-0.3.34-py3.3.egg/you_get/common.py", line 925, in url_to_module
    from .extractors import netease, w56, acfun, baidu, baomihua, bilibili, blip, catfun, cntv, cbs, coursera, dailymotion, dongting, douban, douyutv, ehow, facebook, freesound, funshion, google, sina, ifeng, alive, instagram, iqiyi, joy, jpopsuki, khan, ku6, kugou, kuwo, letv, lizhi, magisto, miomio, mixcloud, mtv81, nicovideo, pptv, qianmo, qq, sohu, songtaste, soundcloud, ted, theplatform, tudou, tucao, tumblr, twitter, vid48, videobam, vidto, vimeo, vine, vk, xiami, yinyuetai, youku, youtube, zhanqi
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/you_get-0.3.34-py3.3.egg/you_get/extractors/__init__.py", line 18, in <module>
    from .funshion import *
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/you_get-0.3.34-py3.3.egg/you_get/extractors/funshion.py", line 87, in <module>
    download = funshion_download
NameError: name 'funshion_download' is not defined```


看来把acfun.tv解析到fun.tv去了。（不用管我的版本问题）

然而如果之前不加fun.tv,这个解析就不能添加。

这个怎么处理？
CC
@soimort @jackyzy823

**Comment by cnbeining** [comment]
在复现前先close。

怀疑是解析冲突。

assign to myself.
