### ISSUE TITLE
[Failed] Consistent failure on Bilibili

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#616]
I tried to you-get this video like 20 times, and it succeeded at the very last run. That's not the way it's supposed to work.

```
➜  you-get-develop git:(develop) ./you-get http://www.bilibili.com/video/av2827603/
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 834, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 494, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get-develop/src/you_get/__main__.py", line 91, in main
    main()
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 1026, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 915, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 807, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 1019, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/extractors/bilibili.py", line 127, in bilibili_download
    bilibili_download_by_cid(id, title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/soimort/Projects/you-get-develop/src/you_get/extractors/bilibili.py", line 103, in bilibili_download_by_cid
    _, type_, temp = url_info(url)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 222, in url_info
    response = request.urlopen(request.Request(url))
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by liushuyu** [comment]
It seems that it was your network failed (DNS pollution?) ...

**Comment by soimort** [comment]
Tried with a proxy and it turns out fine this time. Have no idea why.

**Comment by nuomi1** [comment]
ISP: GD ZJ MOBILE
you-get version ed49c2c

I tried to download it at Mon Aug 31 08:50 CST 2015 and succeeded at the first time.

**Comment by cnbeining** [comment]
This should not be the problem with ```you-get``` or ```Biligrab```, but I do have noticed front end and API being unstable theses days according to multiple reports.

Will closely watch for a couple of days.

**Comment by soimort** [comment]
Seems to be my own DNS failure. Switching to Google Public DNS solved the problem.
