### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by kupo** [soimort/you-get#635]
you-get https://www.youtube.com/watch?v=AH61HoM5NI4
site:                YouTube
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 91, in
 main
    main()
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1018, in
 main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 909, in
script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 801, in
download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1011, in
 any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 46, i
n download_by_url
    self.download(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 164,
in download
    self.p(stream_id)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 109,
in p
    print("title:               %s" % self.title)
UnicodeEncodeError: 'ascii' codec can't encode character '\u300c' in position 33
: ordinal not in range(128)

**Comment by zhangn1985** [comment]
maybe same as #622

**Comment by soimort** [comment]
It seems you're on a Unix-like system. Please set your locale as Unicode-compatible encoding, e.g. `LANG="en_US.UTF-8"` or `LANG="zh_CN.UTF-8"`, otherwise it's not possible to display a video title with CJK character in it.
