### ISSUE TITLE
you-get支持解析移动端的视频网页吗？

### ISSUE THREAD

**Issue by WhiteTeeth** [soimort/you-get#648]
you-get支持解析ios移动端的视频网页吗？我用you-get －u $url 调用时没有输出，有什么能够解析的办法吗？

**Comment by cnbeining** [comment]
不一定。

有些解析器的URL匹配没写移动端（例如我就基本不写。。。）。

把URL报上来吧。

**Comment by WhiteTeeth** [comment]
因为iPhone系统播放器支持的视频格式比较少，播放时需要传递一个m3u8格式或者mp4格式的链接，比如http://pl.youku.com/playlist/m3u8?sid=64423714207801239b7d5&oip=1939824682&keyframe=1&ep=dCaQGEqKV8oC5STXiD8bZCWwcyMKXP0J9ByMh9ZmB9QnS+26&token=3355&ts=1442371420&ctype=12&type=mp4&vid=332396447&ev=1

我模仿you-get的代码做了优酷和土豆的视频提取，先解析vcode，然后生成链接。
但是 http://www.tudou.com/listplay/Q0MiBE2DPCs/nRwALg3YGJs.html 这个视频没有vcode值...
而且you-get 解析土豆视频和搜狐视频时失败：issues #652，issues #650

**Comment by WhiteTeeth** [comment]
对于一些网站的移动端地址和PC端有些不一样，比如乐视网，手机端是http://m.letv.com/vplay_23512816.html，PC端是 http://www.letv.com/ptv/vplay/23512816.html，
you-get 解析手机端时出错
[root@VM_78_117_centos python]# you-get -u http://m.letv.com/vplay_23512816.html
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.3.34', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 1018, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 909, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 801, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 1011, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/extractors/letv.py", line 145, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/extractors/letv.py", line 90, in letv_download_by_vid
    ext , urls = video_info(vid,**kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/extractors/letv.py", line 61, in video_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'

**Comment by jackyzy823** [comment]
For now, we suppose that you-get is running under PC platform.However patches for mobile url match  is welcomed.

**Comment by cnbeining** [comment]
胡言乱语下。

对于解析编写方面，移动端是一个入口——如果移动端和桌面的清晰度相同，那么移动端是很好的入口。

然而，这个问题有两种理解方法：

1. 支持移动端URL。

这个需要修改每个解析器，对移动端URL进行匹配。

是个浩大的工程。。。

2. 支持移动端视频的下载。

这个就麻烦的多（难倒**不一定**）。

有些解析的方法就使用了移动端入口，那么没有区别；

如果要对移动端版本的视频进行专门的解析，则需要很多功夫。

更不要提有些站没有这个区别了。

鉴于```you-get```没有很多种清晰度的支持，目前的写作基本上是直接抓最清晰的那个版本。而且也没有很好的办法透露所有的清晰度，而且视频站的定义又不一样。。。

总之都是麻烦事啦。

感觉与其直接支持，不如都考虑好后行事，或者开个新branch（谁去维护又是个天坑），或者。。。就睡用谁魔改吧。倒是可以丢进wiki，给后来人取用，再或者，弄出tap那种。。。#441

**Comment by keviler** [comment]
ios 端的视频聚合 该怎么做呀? 有没有好的建议?我们就是要用自带的播放器播放网页视频!
