### ISSUE TITLE
搜狐视频无法解析？

### ISSUE THREAD

**Issue by WhiteTeeth** [soimort/you-get#650]
比如：you-get -u http://tv.sohu.com/s2015/newslist/?vid=2582150

```
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.3.34', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 1018, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 909, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 801, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 1011, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/extractors/sohu.py", line 28, in sohu_download
    assert vid
AssertionError
```

**Comment by jackyzy823** [comment]
This link is not real url of video ,many videos in this page share this link. you can get real link by right click the flash player and choice '复制视频地址' .
