### ISSUE TITLE
土豆视频解析失败？

### ISSUE THREAD

**Issue by WhiteTeeth** [soimort/you-get#652]
```
[root@VM_78_117_centos python]# you-get -u http://www.tudou.com/listplay/Q0MiBE2DPCs/nRwALg3YGJs.html
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.3.34', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 1018, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 909, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 801, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/common.py", line 1011, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get-0.3.34-py3.4.egg/you_get/extractors/tudou.py", line 40, in tudou_download
    title = r1(r'kw\s*[:=]\s*[\'\"]([^\n]+?)\'\s*\n', html).replace("\\'", "\'")
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by jackyzy823** [comment]
can not reproduce.
```
you-get -u http://www.tudou.com/listplay/Q0MiBE2DPCs/7NlmtdGSjAQ.html             
Video Site: Tudou.com
Title:      今日头条
Type:       Flash video (video/x-flv)
Size:       18.91 MiB (19831084 Bytes)

Real URLs:
http://58.221.54.197/f4v/10/240080510.h264_98.040099010055FBB783A1FF1E4556485EAA4D08-1783-B98E-F651-000351463265.f4v?key=e5be22f2f35dc7b5099ae455fc436300112a08b9e3&qrs=3308707130&p=1865025387081086990&playtype=99&tk=149968647147956642270229544&brt=99&bc=0&xid=040099010055FBB783A1FF1E4556485EAA4D08-1783-B98E-F651-000351463265&nt=0&nw=0&bs=0&ispid=800615&rc=206&inf=12&si=un&npc=2937&pp=0&ul=0&mt=0&sid=0&pc=0&cip=159.226.8.93&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=351463265&fi=0&sz=19831084
```

**Comment by soimort** [comment]
无法重现。

```
$ /usr/bin/you-get -i http://www.tudou.com/listplay/Q0MiBE2DPCs/7NlmtdGSjAQ.html 
Video Site: Tudou.com
Title:      今日头条
Type:       Flash video (video/x-flv)
Size:       18.91 MiB (19831084 Bytes)
```
