### ISSUE TITLE
乐视不能无法下载

### ISSUE THREAD

**Issue by danran-php** [soimort/you-get#656]
你们可以吗

F:\work\app>python you-get -u http://www.letv.com/ptv/vplay/2051996
4.html
Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "F:\work\app\src\you_get\__main__.py", line 91, in main
    main()
  File "F:\work\app\src\you_get\common.py", line 1131, in main
    script_main('you-get', any_download, any_download_playlist)
  File "F:\work\app\src\you_get\common.py", line 951, in script_mai
n
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "F:\work\app\src\you_get\common.py", line 843, in download_m
ain
    download(url, **kwargs)
  File "F:\work\app\src\you_get\common.py", line 1124, in any_downl
oad
    m.download(url, **kwargs)
  File "F:\work\app\src\you_get\extractors\letv.py", line 145, in l
etv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, i
nfo_only=info_only,**kwargs)
  File "F:\work\app\src\you_get\extractors\letv.py", line 90, in le
tv_download_by_vid
    ext , urls = video_info(vid,**kwargs)
  File "F:\work\app\src\you_get\extractors\letv.py", line 61, in vi
deo_info
    support_stream_id = info["playurl"]["dispatch"].keys()
KeyError: 'playurl'

优酷下载不全，优酷这种地址比较好。you-get 把k.youku.com解析成IP了
http://k.youku.com/player/getFlvPath/sid/344264886886512c15fe0_00/st/flv/fileid/030002100F50E3753E834E055EEB3EA5AAAA11-2475-EDF9-7AA6-CFF93B306000?K=7f35e37ea6c60246261e92de&hd=1&myp=0&ts=274&ypp=0&ctype=12&ev=1&token=6681&oip=1887184030&ep=cSaQGE%2BJXsYG7SvZjT8bNC3nIiIPXP4J9h%2BFg9NiAM0hSJ28njvSspWzSopCE%2FxsB1AFZZr02qGWG0EVYfJHrm0QqjreMPrnj4Hl5d4lspkDFBo2dM3XtFSYRTjw

**Comment by jackyzy823** [comment]
In page of `http://www.letv.com/ptv/vplay/20519964.html` shows "很抱歉，您看的视频已经下线了"

**Comment by soimort** [comment]
以上。

**Comment by danran-php** [comment]
嗯嗯 不知道是不是我的网络原因 有点慢
