### ISSUE TITLE
i奇艺地址出错反馈！不知道是不是人品太差了

### ISSUE THREAD

**Issue by xujiangit** [soimort/you-get#665]
版本0.3.35
you-get http://vip.iqiyi.com/20110902/0e25977b14c36f35.html\#vfrm\=2-3-0-1
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1133, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 951, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 843, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1126, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 35, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/iqiyi.py", line 133, in prepare
    assert info["code"] == "A000000"
AssertionError

下面这种地址也出错?
 you-get http://www.iqiyi.com/v_19rrnxmh44.html         
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1133, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 951, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 843, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1126, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 35, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/iqiyi.py", line 133, in prepare
    assert info["code"] == "A000000"
AssertionError

**Comment by sceext2** [comment]
请见 #664
