### ISSUE TITLE
 用cx_freeze 如何打包you-get

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#687]
from cx_Freeze import setup, Executable

executables = [
    Executable(xxxxxx)
]

setup(name='hello',
      version='0.1',
      description='Sample cx_Freeze script',
      executables=executables
      )

要传什么值给Executable()  ？

**Comment by soimort** [comment]
`"you-get"`?

**Comment by redstoneleo** [comment]
@soimort  是的，请问用cx_freeze 如何打包you-get？

**Comment by soimort** [comment]
。。。

我已经回答过你的问题了，要传的值是`"you-get"`。

**Comment by soimort** [comment]
ps. cx_Freeze 4.x 对 Python 3.5 的支持有问题，要 apply [一个 patch](https://bitbucket.org/anthony_tuininga/cx_freeze/pull-requests/83/python-35-compatibility-for-cx_freeze-4x/diff)，或者用最新的 5.x branch。

**Comment by redstoneleo** [comment]
我的是cx_Freeze 4.x 对 Python 3.4打包，结果对打包后，对命令行输入 you-get出现

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "you-get", line 19, in <module>
  File "C:\Python34\lib\site-packages\you_get-0.3.36-py3.4.egg\you_get\__main__.py", line 90, in main
    from .common import main
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
  File "X:\Python34-x32\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\you_get-0.3.36-py3.4.egg\you_get\common.py", line 32, in <module>
    if sys.stdout.isatty():
AttributeError: 'NoneType' object has no attribute 'isatty'

**Comment by soimort** [comment]
关于如何使用 cx_freeze 打包 you-get，我在[这里](https://github.com/soimort/you-get/wiki/cx_Freeze)写了一个教程。
旧的版本出问题……我就懒得管了。

**Comment by redstoneleo** [comment]
谢谢啦！
