### ISSUE TITLE
UnicodeEncodeError: 'cp932' codec can't encode character '\u8d3a' in position 11: illegal multibyte sequence

### ISSUE THREAD

**Issue by ziuldeargon** [soimort/you-get#690]
Hi, I wanted to try out you-get in my windows machine but I am getting an error. I installed it using python 3.3.5 along with the recommended decoder "FFmpeg" but I am getting this error when I try to use any command:

```C:\Users\ZiulDeArgon>you-get -u http://www.bilibili.com/video/av2488534/
Video Site: bilibili.com
Title:      Traceback (most recent call last):
  File "C:\Users\ZiulDeArgon\AppData\Local\Programs\Python\Python35-32\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.3.36', 'console_scripts', 'you-get')()
  File "C:\Users\ZiulDeArgon\AppData\Local\Programs\Python\Python35-32\lib\site-packages\you_get-0.3.36-py3.5.egg\you_get\__main__.py", line 91, in main
    main()
  File "C:\Users\ZiulDeArgon\AppData\Local\Programs\Python\Python35-32\lib\site-packages\you_get-0.3.36-py3.5.egg\you_get\common.py", line 1152, in main
    script_main('you-get', any_download, any_download_playlist)
  File "C:\Users\ZiulDeArgon\AppData\Local\Programs\Python\Python35-32\lib\site-packages\you_get-0.3.36-py3.5.egg\you_get\common.py", line 966, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "C:\Users\ZiulDeArgon\AppData\Local\Programs\Python\Python35-32\lib\site-packages\you_get-0.3.36-py3.5.egg\you_get\common.py", line 851, in download_main
    download(url, **kwargs)
  File "C:\Users\ZiulDeArgon\AppData\Local\Programs\Python\Python35-32\lib\site-packages\you_get-0.3.36-py3.5.egg\you_get\common.py", line 1145, in any_download
    m.download(url, **kwargs)
  File "C:\Users\ZiulDeArgon\AppData\Local\Programs\Python\Python35-32\lib\site-packages\you_get-0.3.36-py3.5.egg\you_get\extractors\bilibili.py", line 127, in bilibili_download
    bilibili_download_by_cid(id, title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "C:\Users\ZiulDeArgon\AppData\Local\Programs\Python\Python35-32\lib\site-packages\you_get-0.3.36-py3.5.egg\you_get\extractors\bilibili.py", line 106, in bilibili_download_by_cid
    print_info(site_info, title, type_, size)
  File "C:\Users\ZiulDeArgon\AppData\Local\Programs\Python\Python35-32\lib\site-packages\you_get-0.3.36-py3.5.egg\you_get\common.py", line 786, in print_info
    print("Title:     ", unescape_html(tr(title)))
UnicodeEncodeError: 'cp932' codec can't encode character '\u8d3a' in position 11: illegal multibyte sequence```

**Comment by soimort** [comment]
The video title may contain one (or more) characters not supported by your Windows code page (CP932).
You might want to try one of the following solutions:

1. `chcp 65001`
2. `set PYTHONIOENCODING=utf-8`
3. Switch to powershell.

**Comment by ziuldeargon** [comment]
Wow, it works!
I can finally get my freaky stuff! wooooot!

In case someone else reads this issue the steps I used to activate the code page 65001 were:

1.- Start Run (Win+R)
2.- Type cmd /K chcp 65001

http://stackoverflow.com/questions/14109024/how-to-make-unicode-charset-in-cmd-exe-by-default
