### ISSUE TITLE
Unable to download from iqiyi

### ISSUE THREAD

**Issue by pmt4wn** [soimort/you-get#715]
$ you-get http://www.iqiyi.com/v_19rrn64apc.html

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/__main__.py", line 91, in main
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/common.py", line 1152, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/common.py", line 966, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/common.py", line 851, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/common.py", line 1145, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/extractor.py", line 36, in download_by_url
    self.prepare(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/extractors/iqiyi.py", line 121, in prepare
    html = get_html(self.url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/common.py", line 168, in get_html
    content = get_response(url, faker).data
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/you_get/common.py", line 158, in get_response
    data = response.read()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 512, in read
    s = self._safe_read(self.length)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 664, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(125989 bytes read, 49126 more expected)

$ you-get --version

You-Get 0.3.36, a video downloader.

$ python --version

Python 2.7.10

**Comment by soimort** [comment]
iQiyi has very poor access and hard to reach for some networks (especially overseas). Try with a proxy.

```
$ ~/Projects/you-get-develop/you-get -i http://www.iqiyi.com/v_19rrn64apc.html
site:                爱奇艺 (Iqiyi)
title:               单身男女2
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        suprt-high
      container:     f4v
      video-profile: 超高清
      size:          1278.1 MiB (1340202458 bytes)
    # download-with: you-get --format=suprt-high [URL]

    - format:        high
      container:     f4v
      video-profile: 高清
      size:          491.3 MiB (515135261 bytes)
    # download-with: you-get --format=high [URL]

    - format:        standard
      container:     f4v
      video-profile: 标清
      size:          329.3 MiB (345320526 bytes)
    # download-with: you-get --format=standard [URL]

    - format:        topspeed
      container:     f4v
      video-profile: 最差
      size:          138.0 MiB (144697173 bytes)
    # download-with: you-get --format=topspeed [URL]
```
