### ISSUE TITLE
[56] Failed

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#720]
```
$ you-get -i http://www.56.com/u90/v_MTM3MTQ3ODE1.html
Traceback (most recent call last):
  File "/home/soimort/Projects/you-get-develop/you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get-develop/src/you_get/__main__.py", line 91, in main
    main()
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 1143, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 1101, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 964, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 1136, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/extractors/w56.py", line 29, in w56_download
    w56_download_by_id(id, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/soimort/Projects/you-get-develop/src/you_get/extractors/w56.py", line 17, in w56_download_by_id
    assert len(files) == 1
AssertionError
```

It seems the support for 56 is broken for most of its videos.

**Comment by zhangn1985** [comment]
56 应该用embed.py实现，它已经和sohu合并了。

**Comment by V-Zemlyakov** [comment]
$ you-get http://www.youtube.com/watch?v=z3Lfa7dQXh4
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1152, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 966, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 851, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1145, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 36, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/youtube.py", line 141, in prepare
    ytplayer_config = json.loads(re.search('ytplayer.config\s*=\s*([^\n]+});ytplayer', video_page).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by soimort** [comment]
@V-Zemlyakov it's a private video. You need to pass the browser cookies via `-c` option, if you have access to that video.

**Comment by V-Zemlyakov** [comment]
I understand.
If possible dont show python errors? 
And maybe show "private video" message.

**Comment by soimort** [comment]
It's like that the problem solved itself.
