### ISSUE TITLE
iqiyi解析又不行了

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#728]
```C:\Python34\Scripts\you-get.exe -u http://www.iqiyi.com/v_19rrn5nh4k.html```
Traceback (most recent call last):
  File "C:\Python34\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.3.36', 'console_scripts', 'you-get')()
  File "C:\Python34\lib\site-packages\you_get-0.3.36-py3.4.egg\you_get\__main__.
py", line 91, in main
    main()
  File "C:\Python34\lib\site-packages\you_get-0.3.36-py3.4.egg\you_get\common.py
", line 1198, in main
    script_main('you-get', any_download, any_download_playlist)
  File "C:\Python34\lib\site-packages\you_get-0.3.36-py3.4.egg\you_get\common.py
", line 1004, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "C:\Python34\lib\site-packages\you_get-0.3.36-py3.4.egg\you_get\common.py
", line 867, in download_main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get-0.3.36-py3.4.egg\you_get\common.py
", line 1191, in any_download
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get-0.3.36-py3.4.egg\you_get\extractor
.py", line 39, in download_by_url
    self.prepare(**kwargs)
  File "C:\Python34\lib\site-packages\you_get-0.3.36-py3.4.egg\you_get\extractor
s\iqiyi.py", line 129, in prepare
    assert info["code"] == "A000000"
AssertionError

**Comment by KSK999** [comment]
你不是最UPDATE
不過還是不行
C:\Python34\Scripts\you-get>you-get -i http://www.iqiyi.com/v_19rrkkyf10.html
Traceback (most recent call last):
  File "C:\Python34\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.4.0', 'console_scripts', 'you-get')()
  File "C:\Python34\lib\site-packages\you_get-0.4.0-py3.4.egg\you_get\__main__.p
y", line 91, in main
    from .common import main
  File "C:\Python34\lib\site-packages\you_get-0.4.0-py3.4.egg\you_get\common.py"
, line 95, in <module>
    from .util import log, term
  File "C:\Python34\lib\site-packages\you_get-0.4.0-py3.4.egg\you_get\util\term.
py", line 3, in <module>
    import fcntl, termios, struct
ImportError: No module named 'fcntl'

**Comment by benhong** [comment]
是是看這個KEY吧
2c76de15dcb44bd28ff0927d50d31620
若可以用請回報一下

**Comment by benhong** [comment]
不知道是否有好心人可以幫忙 在 iqiyi 增加判斷
當  info["code"]  != "A000000" 
直接提示 要更新key

因為我不太熟悉 Python 語法 和 github 的操作

**Comment by redstoneleo** [comment]
@benhong  太正点了，用了你的key之后解析成功，非常感谢！！！
能分享一下你获取key的方法吗？谢谢啦！

**Comment by benhong** [comment]
#692 這邊有教學

**Comment by soimort** [comment]
@benhong :+1:
