### ISSUE TITLE
希望更新下搜狐视频的解析

### ISSUE THREAD

**Issue by goxofy** [soimort/you-get#731]

**Comment by CzBiX** [comment]
当前版本无法正常处理这种格式的视频，http://video.sina.com.cn/view/249898406.html。
我尝试简单修改代码，强制使用 vid 下载就解决了。
不过我怕影响到其他类型的解析，也没有足够的视频地址样本来测试。就不提交 PR 了。

**Comment by goxofy** [comment]
@CzBiX 这个是新浪视频吗？我说的是搜狐视频，我看最新版的readme里那个表格，tv.sohu.com 是支持的，但是我这边解析有问题

**Comment by CzBiX** [comment]
@goxofy 是我弄错了。
我这边测试搜狐视频是正常的，你应该附上不正常的测试链接。

**Comment by zhangn1985** [comment]
其实你不用改代码和提PR，新浪视频的地址都是：
        ``url = 'http://v.iask.com/v_play_ipad.php?vid={}'.format(self.vid)``

**Comment by goxofy** [comment]
@CzBiX 比如这个URL    http://tv.sohu.com/20151024/n424073087.shtml

最后提示的错误是 urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by soimort** [comment]
经测试可以正常下载。如果仍有问题，请附上测试链接和**完整的output**。

```
λ  you-get-develop [develop] you-get http://tv.sohu.com/20151024/n424073087.shtml
Site:       Sohu.com
Title:      《我知道第二季》20151024 王刚柳岩达成同盟 郭敬明队内惨烈对决
Type:       MPEG-4 video (video/mp4)
Size:       300.53 MiB (315130227 Bytes)

Downloading 《我知道第二季》20151024 王刚柳岩达成同盟 郭敬明队内惨烈对决.mp4 ...
  0.1% (  0.2/300.5MB) ├────────────────────────────────────────┤[1/15]    4 kB/s
```

**Comment by goxofy** [comment]
@soimort 感谢回复。这是我这边的--debug的完整output

```
# tink at HOMEBOT in ~/script/py3env/you-get on git:develop o [11:26:55]
$ ./you-get http://tv.sohu.com/20151024/n424073087.shtml --debug
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.


# tink at HOMEBOT in ~/script/py3env/you-get on git:develop o [11:27:03]
$ ./you-get --debug http://tv.sohu.com/20151024/n424073087.shtml
you-get: version 0.4.111, a tiny downloader that scrapes the web.
you-get: ['http://tv.sohu.com/20151024/n424073087.shtml']
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1232, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1065, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1103, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 841, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 819, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 509, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 500, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./you-get", line 17, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/tink/script/py3env/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/tink/script/py3env/you-get/src/you_get/common.py", line 1213, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/tink/script/py3env/you-get/src/you_get/common.py", line 1134, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/home/tink/script/py3env/you-get/src/you_get/common.py", line 987, in download_main
    download(url, **kwargs)
  File "/home/tink/script/py3env/you-get/src/you_get/common.py", line 1206, in any_download
    m.download(url, **kwargs)
  File "/home/tink/script/py3env/you-get/src/you_get/extractors/sohu.py", line 26, in sohu_download
    html = get_html(url)
  File "/home/tink/script/py3env/you-get/src/you_get/common.py", line 254, in get_html
    content = get_response(url, faker).data
  File "/home/tink/script/py3env/you-get/src/you_get/common.py", line 242, in get_response
    response = request.urlopen(url)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1258, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1235, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

```

**Comment by goxofy** [comment]
看输出好像是无法打开url，但是我用curl 访问这个url是可以正常得到页面的，所以我就不清楚问题出到哪了
