### ISSUE TITLE
作者能否添加一个Follow Redirection选项？

### ISSUE THREAD

**Issue by gonejack** [soimort/you-get#736]
这种网址它下不动啊
```
python3 you-get  http://ift.tt/1MPzpjC
```
ifttt的短网址都是跳转，挺尴尬的，现在下载之前要用 curl 去获取到 effective url

**Comment by zhangn1985** [comment]
```
        import http.client
        conn = http.client.HTTPConnection(video_host)
        conn.request("HEAD", video_url)
        res = conn.getresponse()
        location = res.getheader('location')
```
是不是？

**Comment by soimort** [comment]
本来就支持跳转。如有问题，请贴**完整的命令行输出**。

```
$ you-get http://ift.tt/1MPzpjC 
Site:       Tumblr.com
Title:      feedmerightmeow: “ I’m not bringing your food in the bed. This is not mothers day and you are not a mother. ”
Type:       Unknown type (None)
Size:       1.34 MiB (1400923 Bytes)

Site:       Tumblr.com
Title:      tumblr_nsemjzCCFV1tvby72o1_1280
Type:       JPEG Image (image/jpeg)
Size:       0.68 MiB (709568 Bytes)

Downloading tumblr_nsemjzCCFV1tvby72o1_1280.jpg ...
100.0% (  0.7/0.7  MB) ├████████████████████████████████████████┤[1/1]    5 MB/s

Site:       Tumblr.com
Title:      tumblr_nsemjzCCFV1tvby72o2_1280
Type:       JPEG Image (image/jpeg)
Size:       0.66 MiB (691355 Bytes)

Downloading tumblr_nsemjzCCFV1tvby72o2_1280.jpg ...
100.0% (  0.7/0.7  MB) ├████████████████████████████████████████┤[1/1]   11 MB/s
```

**Comment by nuomi1** [comment]
@gonejack https://ifttt.com/ 正常，http://ift.tt/ 已被认证……

**Comment by gonejack** [comment]
这里用proxy可以下载到html
```
i@debian:~/pytools/you-get$ curl -LO "http://ift.tt/1MPzpjC" --proxy socks5://192.168.56.1:1080
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   176  100   176    0     0    163      0  0:00:01  0:00:01 --:--:--   163
100 59045    0 59045    0     0   9644      0 --:--:--  0:00:06 --:--:-- 27943
```

这里出错
```
i@debian:~/pytools/you-get$ python3 you-get --debug -x socks5://192.168.56.1:1080 http://ift.tt/1MPzpjC
you-get: version 0.4.111, a tiny downloader that scrapes the web.
you-get: ['http://ift.tt/1MPzpjC']
Traceback (most recent call last):
  File "you-get", line 17, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/youi/pytools/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 1212, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 1133, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 986, in download_main
    download(url, **kwargs)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 1204, in any_download
    m, url = url_to_module(url)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 1196, in url_to_module
    res = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''
```

**Comment by gonejack** [comment]
使用http代理：
```
i@debian:~/pytools/you-get$ curl -LvI "http://ift.tt/1MPzpjC" --proxy http://192.168.56.1:7777
* Hostname was NOT found in DNS cache
*   Trying 192.168.56.1...
* Connected to 192.168.56.1 (192.168.56.1) port 7777 (#0)
> HEAD http://ift.tt/1MPzpjC HTTP/1.1
> User-Agent: curl/7.38.0
> Host: ift.tt
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
* Server nginx is not blacklisted
< Server: nginx
Server: nginx
< Date: Sun, 25 Oct 2015 14:32:42 GMT
Date: Sun, 25 Oct 2015 14:32:42 GMT
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8
< Content-Length: 176
Content-Length: 176
< Cache-Control: private, max-age=90
Cache-Control: private, max-age=90
< Location: http://cat-erva.tumblr.com/post/129901618111/feedmerightmeow-im-not-bringing-your-food-in
Location: http://cat-erva.tumblr.com/post/129901618111/feedmerightmeow-im-not-bringing-your-food-in
< Connection: keep-alive
Connection: keep-alive
< Keep-Alive: timeout=15
Keep-Alive: timeout=15

< 
* Connection #0 to host 192.168.56.1 left intact
* Issue another request to this URL: 'http://cat-erva.tumblr.com/post/129901618111/feedmerightmeow-im-not-bringing-your-food-in'
* Hostname was found in DNS cache
*   Trying 192.168.56.1...
* Connected to 192.168.56.1 (192.168.56.1) port 7777 (#1)
> HEAD http://cat-erva.tumblr.com/post/129901618111/feedmerightmeow-im-not-bringing-your-food-in HTTP/1.1
> User-Agent: curl/7.38.0
> Host: cat-erva.tumblr.com
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
* Server nginx is not blacklisted
< Server: nginx
Server: nginx
< Date: Sun, 25 Oct 2015 14:32:44 GMT
Date: Sun, 25 Oct 2015 14:32:44 GMT
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8
< Vary: Accept-Encoding
Vary: Accept-Encoding
< Set-Cookie: tmgioct=562ce80be801a60280693620; expires=Wed, 22-Oct-2025 14:32:43 GMT; Max-Age=315360000; path=/; httponly
Set-Cookie: tmgioct=562ce80be801a60280693620; expires=Wed, 22-Oct-2025 14:32:43 GMT; Max-Age=315360000; path=/; httponly
< P3P: CP="Tumblr's privacy policy is available here: https://www.tumblr.com/policy/en/privacy"
P3P: CP="Tumblr's privacy policy is available here: https://www.tumblr.com/policy/en/privacy"
< X-Tumblr-User: cat-erva
X-Tumblr-User: cat-erva
< X-Tumblr-Pixel-0: https://px.srvcs.tumblr.com/impixu?T=1445783563&J=eyJ0eXBlIjoidXJsIiwidXJsIjoiaHR0cDpcL1wvY2F0LWVydmEudHVtYmxyLmNvbVwvcG9zdFwvMTI5OTAxNjE4MTExXC9mZWVkbWVyaWdodG1lb3ctaW0tbm90LWJyaW5naW5nLXlvdXItZm9vZC1pbiIsInJlcXR5cGUiOjAsInJvdXRlIjoiXC9wb3N0XC86aWRcLzpzdW1tYXJ5In0=&U=PGHKFNABNJ&K=bb2d7bc8b9b01fdc3f43e89514b5ef68732bcc12cfa619637f380b1386ba2c79--https://px.srvcs.tumblr.com/impixu?T=1445783563&J=eyJ0eXBlIjoicG9zdCIsInVybCI6Imh0dHA6XC9cL2NhdC1lcnZhLnR1bWJsci5jb21cL3Bvc3RcLzEyOTkwMTYxODEx
X-Tumblr-Pixel-0: https://px.srvcs.tumblr.com/impixu?T=1445783563&J=eyJ0eXBlIjoidXJsIiwidXJsIjoiaHR0cDpcL1wvY2F0LWVydmEudHVtYmxyLmNvbVwvcG9zdFwvMTI5OTAxNjE4MTExXC9mZWVkbWVyaWdodG1lb3ctaW0tbm90LWJyaW5naW5nLXlvdXItZm9vZC1pbiIsInJlcXR5cGUiOjAsInJvdXRlIjoiXC9wb3N0XC86aWRcLzpzdW1tYXJ5In0=&U=PGHKFNABNJ&K=bb2d7bc8b9b01fdc3f43e89514b5ef68732bcc12cfa619637f380b1386ba2c79--https://px.srvcs.tumblr.com/impixu?T=1445783563&J=eyJ0eXBlIjoicG9zdCIsInVybCI6Imh0dHA6XC9cL2NhdC1lcnZhLnR1bWJsci5jb21cL3Bvc3RcLzEyOTkwMTYxODEx
< X-Tumblr-Pixel-1: MVwvZmVlZG1lcmlnaHRtZW93LWltLW5vdC1icmluZ2luZy15b3VyLWZvb2QtaW4iLCJyZXF0eXBlIjowLCJyb3V0ZSI6IlwvcG9zdFwvOmlkXC86c3VtbWFyeSIsInBvc3RzIjpbeyJyb290X2Jsb2dpZCI6IjE3NTYyMTQ1NCIsInJvb3RfcG9zdGlkIjoiMTI1NTkxODc3NTA1IiwicG9zdGlkIjoiMTI5OTAxNjE4MTExIiwiYmxvZ2lkIjoiMTc0MzUxNjYzIiwic291cmNlIjozM31dfQ==&U=OADAAKJEJA&K=ba1991e5994ced33a72fe3a5e7382e2d355a9771b666705e6c445ea08ab304e2
X-Tumblr-Pixel-1: MVwvZmVlZG1lcmlnaHRtZW93LWltLW5vdC1icmluZ2luZy15b3VyLWZvb2QtaW4iLCJyZXF0eXBlIjowLCJyb3V0ZSI6IlwvcG9zdFwvOmlkXC86c3VtbWFyeSIsInBvc3RzIjpbeyJyb290X2Jsb2dpZCI6IjE3NTYyMTQ1NCIsInJvb3RfcG9zdGlkIjoiMTI1NTkxODc3NTA1IiwicG9zdGlkIjoiMTI5OTAxNjE4MTExIiwiYmxvZ2lkIjoiMTc0MzUxNjYzIiwic291cmNlIjozM31dfQ==&U=OADAAKJEJA&K=ba1991e5994ced33a72fe3a5e7382e2d355a9771b666705e6c445ea08ab304e2
< X-Tumblr-Pixel: 2
X-Tumblr-Pixel: 2
< Link: <http://tmblr.co/ZDmrCo1u_lME->; rel=shorturl
Link: <http://tmblr.co/ZDmrCo1u_lME->; rel=shorturl
< Link: <http://38.media.tumblr.com/avatar_41a23b152687_128.png>; rel=icon
Link: <http://38.media.tumblr.com/avatar_41a23b152687_128.png>; rel=icon
< X-UA-Compatible: IE=Edge,chrome=1
X-UA-Compatible: IE=Edge,chrome=1
< Content-Length: 0
Content-Length: 0
< Connection: keep-alive
Connection: keep-alive
< Keep-Alive: timeout=15
Keep-Alive: timeout=15

< 
* Connection #1 to host 192.168.56.1 left intact

```

```
i@debian:~/pytools/you-get$ python3 you-get --debug -x 192.168.56.1:7777 http://ift.tt/1MPzpjC
you-get: version 0.4.111, a tiny downloader that scrapes the web.
you-get: ['http://ift.tt/1MPzpjC']
Traceback (most recent call last):
  File "you-get", line 17, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/youi/pytools/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 1212, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 1133, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 986, in download_main
    download(url, **kwargs)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 1204, in any_download
    m, url = url_to_module(url)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 1196, in url_to_module
    res = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

```

**Comment by gonejack** [comment]
```
i@debian:~/pytools/you-get$ python3 you-get --debug --http-proxy 192.168.56.1:7777 http://cat-erva.tumblr.com/post/129901618111/feedmerightmeow-im-not-bringing-your-food-in
Site:       Tumblr.com
Title:      feedmerightmeow: “ I’m not bringing your food in the bed. This is not mothers day and you are not a mother. ”
Type:       Unknown type (None)
Size:       1.34 MiB (1400923 Bytes)

Site:       Tumblr.com
Title:      tumblr_nsemjzCCFV1tvby72o1_1280
Type:       JPEG Image (image/jpeg)
Size:       0.68 MiB (709568 Bytes)

Skipping ./tumblr_nsemjzCCFV1tvby72o1_1280.jpg: file already exists

Site:       Tumblr.com
Title:      tumblr_nsemjzCCFV1tvby72o2_1280
Type:       JPEG Image (image/jpeg)
Size:       0.66 MiB (691355 Bytes)

Skipping ./tumblr_nsemjzCCFV1tvby72o2_1280.jpg: file already exists

```

```
i@debian:~/pytools/you-get$ python3 you-get --debug --http-proxy 192.168.56.1:7777 http://ift.tt/1MPzpjCyou-get: version 0.4.111, a tiny downloader that scrapes the web.
you-get: ['http://ift.tt/1MPzpjC']
Traceback (most recent call last):
  File "you-get", line 17, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/youi/pytools/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 1212, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 1133, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 986, in download_main
    download(url, **kwargs)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 1204, in any_download
    m, url = url_to_module(url)
  File "/home/youi/pytools/you-get/src/you_get/common.py", line 1196, in url_to_module
    res = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

```

**Comment by soimort** [comment]
目前并不支持 SOCKS5 代理。

既然`you-get --http-proxy 192.168.56.1:7777`可以正常访问 Tumblr 的话，我觉得这种 `BadStatusLine` 应该是 Python urllib 的实现问题。
建议直接走 proxychains，连`--http-proxy`都可以省了。全局 SOCKS 应该是没有问题的。
