### ISSUE TITLE
letvcloud 已经有失效的风险

### ISSUE THREAD

**Issue by zhangn1985** [soimort/you-get#738]
```
 you-get --debug http://www.acfun.tv/v/ac2288433
you-get: version 0.4.121, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.tv/v/ac2288433']
Traceback (most recent call last):
  File "/home/xxx/source/you-get/you-get", line 17, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/xxxx/source/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/xxx/source/you-get/src/you_get/common.py", line 1212, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/xxx/source/you-get/src/you_get/common.py", line 1133, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/home/xxx/source/you-get/src/you_get/common.py", line 986, in download_main
    download(url, **kwargs)
  File "/home/xxx/source/you-get/src/you_get/common.py", line 1205, in any_download
    m.download(url, **kwargs)
  File "/home/xxx/source/you-get/src/you_get/extractors/acfun.py", line 126, in acfun_download
    acfun_download_by_vid(p_vid, p_title, output_dir=output_dir, merge=merge, info_only=info_only ,**kwargs)
  File "/home/xxx/source/you-get/src/you_get/extractors/acfun.py", line 38, in acfun_download_by_vid
    letvcloud_download_by_vu(sourceId, '2d8c027396', title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/xxx/source/you-get/src/you_get/extractors/letv.py", line 112, in letvcloud_download_by_vu
    for video_type in info['data']['video_info']['media']:
TypeError: list indices must be integers, not str
```
主要是因为API返回为`{"code":10071,"data":[],"message":"\u94FE\u63A5\u5DF2\u5931\u6548,\u8BF7\u66F4\u6539\u540E\u91CD\u8BD5","timestamp":1445837970,"total":0}`

但重试又可能会成功，所以已有失效的风险。

**Comment by cnbeining** [comment]
好奇怪啊喵。

留观，请各位报告所有的类似事故。

**Comment by A-Circle-Zhang** [comment]
ran 这个参数会检查时效性，取mp4不加就行了，取 flv 需保证本地时间是正确的，要不，取乐视的服务器时间也行：
http://api.letv.com/time

**Comment by soimort** [comment]
Can't reproduce.
