### ISSUE TITLE
acfun 现在似乎有原创视频

### ISSUE THREAD

**Issue by zhangn1985** [soimort/you-get#745]
```
 you-get --debug http://www.acfun.tv/v/ac2302288
you-get: version 0.4.139, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.tv/v/ac2302288']
Traceback (most recent call last):
  File "/home/zhangn1985/source/you-get/you-get", line 17, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/zhangn1985/source/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/common.py", line 1213, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/common.py", line 1134, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/home/zhangn1985/source/you-get/src/you_get/common.py", line 987, in download_main
    download(url, **kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/common.py", line 1206, in any_download
    m.download(url, **kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/extractors/acfun.py", line 126, in acfun_download
    acfun_download_by_vid(p_vid, p_title, output_dir=output_dir, merge=merge, info_only=info_only ,**kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/extractors/acfun.py", line 40, in acfun_download_by_vid
    raise NotImplementedError(sourceType)
NotImplementedError: zhuzhan
```

**Comment by cnbeining** [comment]
可以确认。

据消息：

用了Dnion的CDN。

其他信息未知。

过往视频将转移到新CDN。

**Comment by cnbeining** [comment]
```
General
Complete name                            : 1764019_720p.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 19.3 MiB
Duration                                 : 3mn 47s
Overall bit rate                         : 713 Kbps
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00
Writing application                      : Lavf56.15.102

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 3mn 47s
Bit rate                                 : 658 Kbps
Nominal bit rate                         : 700 Kbps
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.029
Stream size                              : 17.8 MiB (92%)
Writing library                          : x264 core 142 r62 24e4fed
Encoding settings                        : cabac=1 / ref=2 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=6 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=36 / lookahead_threads=5 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=30 / rc=abr / mbtree=1 / bitrate=700 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 3mn 47s
Duration_LastFrame                       : -10ms
Bit rate mode                            : Constant
Bit rate                                 : 48.0 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 KHz
Compression mode                         : Lossy
Stream size                              : 1.30 MiB (7%)
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00

```


我已经炸毛了。

我们换逻辑吧：

如果source是10位字母+数字 则强行按照```vu```解析。起码乐视云的东西人还能看。

这700K的屎没法吃。
