### ISSUE TITLE
Cannot merge mp4 fragments (NotImplementedError())

### ISSUE THREAD

**Issue by abhoriel** [soimort/you-get#747]
Jonathans-Air:pokemon_zw jonathan$ you-get --debug http://www.letv.com/ptv/vplay/567670.html
Current Video Supports:
	--format 1300 <URL>
	--format 720p <URL>
	--format 350 <URL>
	--format 1000 <URL>
Site:       LeTV.com
Title:      宠物小精灵003
Type:       MPEG-4 video (video/mp4)
Size:       320.43 MiB (336000368 Bytes)

Downloading 宠物小精灵003.mp4 ...
100.0% (320.4/320.4MB) ├██████████████████████████████████████┤[81/81]    2 MB/s
Merging video parts...
./宠物小精灵003[00].mp4
you-get: version 0.4.125, a tiny downloader that scrapes the web.
you-get: ['http://www.letv.com/ptv/vplay/567670.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1213, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1134, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 987, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1206, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/letv.py", line 145, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/letv.py", line 98, in letv_download_by_vid
    download_urls(urls, title, ext, size, output_dir=output_dir, merge=merge)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 722, in download_urls
    concat_mp4(parts, output_filepath)
  File "/usr/local/lib/python3.5/site-packages/you_get/processor/join_mp4.py", line 914, in concat_mp4
    merge_mp4s(mp4s, output)
  File "/usr/local/lib/python3.5/site-packages/you_get/processor/join_mp4.py", line 876, in merge_mp4s
    mp4s = list(map(read_mp4, ins))
  File "/usr/local/lib/python3.5/site-packages/you_get/processor/join_mp4.py", line 717, in read_mp4
    atoms = parse_atoms(stream)
  File "/usr/local/lib/python3.5/site-packages/you_get/processor/join_mp4.py", line 708, in parse_atoms
    atom = read_atom(stream)
  File "/usr/local/lib/python3.5/site-packages/you_get/processor/join_mp4.py", line 700, in read_atom
    raise NotImplementedError('%s: %d' % (type, left))
NotImplementedError: b'\x00\x00\xb0\r': 1195376648

**Comment by abhoriel** [comment]
Running python3.5 as installwed by Homebrew on OSX El Capitan

**Comment by soimort** [comment]
Install **FFmpeg**.

**Comment by nuomi1** [comment]
@soimort flvgo extracted only one url for letv, but you-get not.
eg: http://flvgo.com/download?url=http%3A%2F%2Fwww.letv.com%2Fptv%2Fvplay%2F567670.html

**Comment by zhangn1985** [comment]
和flvgo的主要区别：flvgo: platid=3&splatid=301 you-get platid=1&splatid=101

**Comment by soimort** [comment]
Closing.

@nuomi1 @zhangn1985 Let's keep the discussion in #606.
