### ISSUE TITLE
QQ video error 

### ISSUE THREAD

**Issue by epikish** [soimort/you-get#761]
I'm not really sure how to use you-get. I just downloaded the 7zip file and extracted it on my desktop. I was able to download youtube videos, but I can't seem to download qq or youku videos. Am I doing something wrong?

    you-get -d http://v.qq.com/cover/j/j0fp5yhsgkh6c29.html?vid=n001877b10t
    Site: QQ.com
    you-get: version 0.4.156, a tiny downloader that scrapes the web.
    you-get: ['http://v.qq.com/cover/j/j0fp5yhsgkh6c29.html?vid=n001877b10t']
    Traceback (most recent call last):
    File "", line 17, in
    File "C:\msys64\home\win7\you-get\src\you_get__main__.py", line 92, in main
    File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1216, in main
    File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1137, in script
    _main
    File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 990, in downloa
    d_main
    File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1209, in any_do
    wnload
    File "C:\msys64\home\win7\you-get\src\you_get\extractors\qq.py", line 23, in q
    q_download
    File "C:\msys64\home\win7\you-get\src\you_get\extractors\qq.py", line 14, in q
    q_download_by_vid
    File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 925, in print_i
    nfo
    File "e:\programs\python\python35\lib\encodings\cp850.py", line 19, in encode
    UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: cha
    racter maps to
    you-get returned -1
    Title:

**Comment by soimort** [comment]
Windows encoding is hell.

I see that you're using code page 850 (Western Europe). In order to download videos with Asian CJK characters in titles, you need to change your code page to **936** (Chinese) or **932** (Japanese), etc. You may also give **`chcp 65001`** (which is the code page for UTF-8) a try, but it's badly implemented on Windows and sometimes crashes my python process.

**Comment by epikish** [comment]
I see thanks. I changed my code page to 936. Somehow I can only download LQ vidoes in qq.
