### ISSUE TITLE
Unable to download this LetvCloud video

### ISSUE THREAD

**Issue by tistatt** [soimort/you-get#770]
http://yuntv.letv.com/bcloud.html?uu=78e2e89114&vu=e1c6d52343
就是这个url，解析不了。
首先，我用-i参数获取视频信息，取不到。
其次，我直接选择下载，下载失败。

PS.这是一个没有版权保护的免费视频。哪位大神能够帮忙看一下。

**Comment by tistatt** [comment]
原来issue 里面可以发中文的啊。我重表达一遍吧，还是汉字自然。
http://yuntv.letv.com/bcloud.html?uu=e5fceee7d8&vu=ca6a608270
就是这个url，解析不了。
首先，我用-i参数获取视频信息，取不到。
其次，我直接选择下载，下载失败。

PS.这是一个没有版权保护的免费视频。哪位大神能够帮忙看一下。

**Comment by zhangn1985** [comment]
大概是这个视频有不同的signkey

**Comment by cnbeining** [comment]
咦这不是我家翻译的视频么

我说为啥这个vu我认得

这种事您直接跟我们说一下我就帮您找原版了嘛

闹半天是一家啊（

**Comment by zhangn1985** [comment]
```
you-get --debug 'http://yuntv.letv.com/bcloud.html?uu=78e2e89114&vu=e1c6d52343'
you-get: version 0.4.200, a tiny downloader that scrapes the web.
you-get: ['http://yuntv.letv.com/bcloud.html?uu=78e2e89114&vu=e1c6d52343']
Traceback (most recent call last):
  File "/home/zhangn1985/source/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/zhangn1985/source/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/common.py", line 1216, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/common.py", line 1137, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/home/zhangn1985/source/you-get/src/you_get/common.py", line 990, in download_main
    download(url, **kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/common.py", line 1209, in any_download
    m.download(url, **kwargs)
  File "/home/zhangn1985/source/you-get/src/you_get/extractors/letv.py", line 130, in letv_download
    letvcloud_download(url, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/zhangn1985/source/you-get/src/you_get/extractors/letv.py", line 126, in letvcloud_download
    letvcloud_download_by_vu(vu, uu, title=title, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/zhangn1985/source/you-get/src/you_get/extractors/letv.py", line 112, in letvcloud_download_by_vu
    for video_type in info['data']['video_info']['media']:
TypeError: list indices must be integers, not str
```
