### ISSUE TITLE
Youku error?

### ISSUE THREAD

**Issue by epikish** [soimort/you-get#778]
>you-get -d http://v.youku.com/v_show/id_XMTM5ODY1MzgwOA==.html?from=y1.7-1.2
you-get: version 0.4.167, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTM5ODY1MzgwOA==.html?from=y1.7-1.2']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "C:\msys64\home\win7\you-get\src\you_get\__main__.py", line 92, in main
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1216, in main
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1137, in script_main
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 990, in download_main
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1209, in any_download
  File "C:\msys64\home\win7\you-get\src\you_get\extractor.py", line 39, in download_by_url
  File "C:\msys64\home\win7\you-get\src\you_get\extractors\youku.py", line 110, in prepare
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 256, in get_html
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 244, in get_response
  File "e:\programs\python\python35\lib\urllib\request.py", line 162, in urlopen
  File "e:\programs\python\python35\lib\urllib\request.py", line 465, in open
  File "e:\programs\python\python35\lib\urllib\request.py", line 483, in _open
  File "e:\programs\python\python35\lib\urllib\request.py", line 443, in _call_chain
  File "e:\programs\python\python35\lib\urllib\request.py", line 1268, in http_open
  File "e:\programs\python\python35\lib\urllib\request.py", line 1243, in do_open
  File "e:\programs\python\python35\lib\http\client.py", line 1174, in getresponse
  File "e:\programs\python\python35\lib\http\client.py", line 282, in begin
  File "e:\programs\python\python35\lib\http\client.py", line 243, in _read_status
  File "e:\programs\python\python35\lib\socket.py", line 571, in readinto
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
you-get returned -1

**Comment by soimort** [comment]
Network issue.

Feel free to come up with more details if you could reproduce it on a different network.
