### ISSUE TITLE
you-get can not be execuded

### ISSUE THREAD

**Issue by jenchxin** [soimort/you-get#791]
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by jenchxin** [comment]
[root@VM_168_175_centos youGet]# you-get --version
you-get: version 0.4.176, a tiny downloader that scrapes the web.

**Comment by jenchxin** [comment]
[root@VM_168_175_centos youGet]# you-get -du http://www.iqiyi.com/kszt/bpbxd3.html
you-get: version 0.4.176, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/kszt/bpbxd3.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.176', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.176-py3.5.egg/you_get/__main__.py", line 92, in main
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.176-py3.5.egg/you_get/common.py", line 1216, in main
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.176-py3.5.egg/you_get/common.py", line 1137, in script_main
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.176-py3.5.egg/you_get/common.py", line 990, in download_main
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.176-py3.5.egg/you_get/common.py", line 1209, in any_download
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.176-py3.5.egg/you_get/extractor.py", line 50, in download_by_url
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.176-py3.5.egg/you_get/extractor.py", line 186, in download
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.176-py3.5.egg/you_get/extractor.py", line 120, in p
UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-23: ordinal not in range(128)

**Comment by soimort** [comment]
1. **Check your `locale`**. `UTF-8` is the recommended default encoding, otherwise you can't handle video titles with non-ASCII (like, Chinese) characters. In your case, you need something like `LANG=en_US.UTF-8`.
2. (Although it has nothing to do with `you-get`) I suggest not using `root` account to run any untrusted user program or perform daily tasks. You can easily shoot yourself in the foot that way.
