### ISSUE TITLE
MioMio is not supported anymore?

### ISSUE THREAD

**Issue by loki8217** [soimort/you-get#795]
I have succeed in downloading from mio mio about a month ago, but after I  re-installed ubuntu and you-get, i cannot download. i listed log below, would you please help to look into this case?thank you!

zero@computer:~/Videos$ you-get -d "http://www.miomio.tv/watch/cc251907/"
Site:       MioMio.tv
Title:      ロンドンハーツ　動けるおデブ女王決定戦!! - 15 12 08
Type:       Unknown type (None)
Size:       0.0 MiB (0 Bytes)

Downloading ロンドンハーツ　動けるおデブ女王決定戦!! - 15 12 08.None ...
you-get: version 0.4.176, a tiny downloader that scrapes the web.
you-get: ['http://www.miomio.tv/watch/cc251907/']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1216, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1137, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 990, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1209, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/miomio.py", line 36, in miomio_download
    download_urls([url], title, ext, total_size=None, output_dir=output_dir, merge=merge)        
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 674, in download_urls
    url_save(url, output_filepath, bar, refer = refer, faker = faker)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 462, in url_save
    assert received == os.path.getsize(temp_filepath), '%s == %s == %s' % (received, os.path.getsize(temp_filepath), temp_filepath)
  File "/usr/lib/python3.4/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: './ロンドンハーツ\u3000動けるおデブ女王決定戦!! - 15 12 08.None.download'

**Comment by cnbeining** [comment]
Cannot fix within the current system of ```you-get``` as Dec.12.2015.

A playaround would be:

```
you-get -u "http://www.miomio.tv/watch/cc251907/"
Site:       MioMio.tv
Title:      ロンドンハーツ　動けるおデブ女王決定戦!! - 15 12 08
Type:       Unknown type (None)
Size:       0.0 MiB (0 Bytes)

Real URLs:
http://mtv.aplmm.com/2015/12/151208/0074_OGNlNGE1ZjEw.flv
```

Then

```
curl -o "video.flv" -H 'Referer: http://www.miomio.tv/'  'http://mtv.aplmm.com/2015/12/151208/0074_OGNlNGE1ZjEw.flv' --compressed 
```

.

See #805 .

**Comment by soimort** [comment]
If that's the case, I'm happy to merge #785, before I start to work on a complete rewrite of `you-get` presumably in the faraway future.

**Comment by cnbeining** [comment]
Another careful review of my PR, especially regarding ```common.py``` would be appreciated.
