### ISSUE TITLE
[YouTube] Unable to download restricted videos (no "url_encoded_fmt_stream_map")

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#8]
```sh
➜  Downloads  you-get -i http://www.youtube.com/watch\?v\=rbVBpbZVHTQ
Traceback (most recent call last):
  File "/usr/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.2.7', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.2/site-packages/you_get/main.py", line 55, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/lib/python3.2/site-packages/you_get/common.py", line 643, in script_main
    download_main(download, download_playlist, args, playlist, output_dir, merge, info_only)
  File "/usr/lib/python3.2/site-packages/you_get/common.py", line 563, in download_main
    download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/usr/lib/python3.2/site-packages/you_get/main.py", line 48, in any_download
    m.download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/usr/lib/python3.2/site-packages/you_get/downloader/youtube.py", line 30, in youtube_download
    youtube_download_by_id(id, None, output_dir, merge = merge, info_only = info_only)
  File "/usr/lib/python3.2/site-packages/you_get/downloader/youtube.py", line 16, in youtube_download_by_id
    url = unicodize(url)
  File "/usr/lib/python3.2/site-packages/you_get/common.py", line 48, in unicodize
    return re.sub(r'\\u([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])', lambda x: chr(int(x.group(0)[2:], 16)), text)
  File "/usr/lib/python3.2/re.py", line 167, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

**Comment by soimort** [comment]
This is no longer an issue.
