### ISSUE TITLE
KeyError: 'HOME' OSError: Could not find .netrc: $HOME is not set

### ISSUE THREAD

**Issue by ziuldeargon** [soimort/you-get#803]
I am getting this error when I try to download something from nicovideo.jp
```
Traceback (most recent call last):
  File "c:\users\ziuldeargon\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ziuldeargon\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ZiulDeArgon\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\ziuldeargon\appdata\local\programs\python\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\ziuldeargon\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1216, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\ziuldeargon\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1137, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "c:\users\ziuldeargon\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 990, in download_main
    download(url, **kwargs)
  File "c:\users\ziuldeargon\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1209, in any_download
    m.download(url, **kwargs)
  File "c:\users\ziuldeargon\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\nicovideo.py", line 22, in nicovideo_download
    info = netrc.netrc().authenticators('nicovideo')
  File "c:\users\ziuldeargon\appdata\local\programs\python\python35-32\lib\netrc.py", line 29, in __init__
    raise OSError("Could not find .netrc: $HOME is not set")
OSError: Could not find .netrc: $HOME is not set
```

**Comment by soimort** [comment]
Please, include the exact command line and full output when reporting an issue next time.

**Comment by ziuldeargon** [comment]
Sorry, this is the command I used:

`C:\Users\ZiulDeArgon>you-get http://www.nicovideo.jp/watch/sm27760741`

![screenshot](https://cloud.githubusercontent.com/assets/7907421/11759786/ffe4fb5c-a040-11e5-919b-6fd82cc2d875.png)

**Comment by soimort** [comment]
@ziuldeargon It should be already fixed in the latest `develop` branch - let me know if it doesn't work.

**Comment by ziuldeargon** [comment]
Updated to version version 0.4.192, still there:

![screenshot](https://cloud.githubusercontent.com/assets/7907421/11760695/f113e5cc-a061-11e5-9722-0594d3ac7b0c.png)

**Comment by soimort** [comment]
Try the **`develop` branch**, not version 0.4.192 -- it's several commits behind and the fix hasn't been released yet.

**Comment by ziuldeargon** [comment]
All right, it is working now, thanks!
