### ISSUE TITLE
[优酷] 提示：该视频被设为仅粉丝观看

### ISSUE THREAD

**Issue by jiemoon** [soimort/you-get#814]
如题，这个大家有碰到过？

比如： http://v.youku.com/v_show/id_XMTQxMjI1NzEyMA==.html 这个视频

```
$ you-get -i --debug 'http://v.youku.com/v_show/id_XMTQxMjI1NzEyMA==.html'
you-get: version 0.4.192, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTQxMjI1NzEyMA==.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1217, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1138, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 991, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1210, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractor.py", line 39, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/youku.py", line 176, in prepare
    audio_lang = data1['stream'][0]['audio_lang']
KeyError: 'stream'
```

**Comment by soimort** [comment]
这种设置权限的视频是没有办法直接解析的，需要用`--cookies`传浏览器cookies。

![screenshot from 2015-12-22 12-11-48](https://cloud.githubusercontent.com/assets/342945/11954054/87f8a202-a8a5-11e5-913c-5583f9b0c4a9.png)
