### ISSUE TITLE
error when getting video from youtube

### ISSUE THREAD

**Issue by nguyentienlong** [soimort/you-get#819]
you-get https://www.youtube.com/watch?v=KzV_UCQFY6w

got this error
```
Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1018, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 909, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 801, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1011, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/extractor.py", line 44, in download_by_url
    self.extract(**kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/extractors/youtube.py", line 202, in extract
    sig = self.__class__.decipher(js, s)
  File "/usr/lib/python3.4/site-packages/you_get/extractors/youtube.py", line 53, in decipher
    f1def = re.sub(r'([$\w]+\.)([$\w]+\(\w+,\d+\))', r'\2', f1def)
  File "/usr/lib64/python3.4/re.py", line 175, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

```

**Comment by soimort** [comment]
Closed via 12465a6.
