### ISSUE TITLE
pptv assistance

### ISSUE THREAD

**Issue by johny1** [soimort/you-get#832]
Hello, I'm new to this and I'm having issues with downloading from pptv. I'm using the .exe. I'm not sure if I'm doing something wrong but youtube vids work for me.

$ you-get http://v.pptv.com/show/N2Vt6quYUpDlW8Amlg.html

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

$ you-get --debug http://v.pptv.com/show/N2Vt6quYUpDlW8Amlg.html
you-get: version 0.4.217, a tiny downloader that scrapes the web.
you-get: ['http://v.pptv.com/show/N2Vt6quYUpDlW8Amlg.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "C:\msys64\home\win7\you-get\src\you_get\__main__.py", line 92, in main
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1229, in main
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1150, in script
_main
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1003, in downlo
ad_main
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1222, in any_do
wnload
  File "C:\msys64\home\win7\you-get\src\you_get\extractors\pptv.py", line 150, i
n pptv_download
  File "C:\msys64\home\win7\you-get\src\you_get\extractors\pptv.py", line 123, i
n pptv_download_by_id
TypeError: 'NoneType' object is not subscriptable
you-get returned -1

**Comment by cnbeining** [comment]
#447 ?
