### ISSUE TITLE
json.dumps(...ensure_ascii=False) has an `UnicodeEncodeError` issue.

### ISSUE THREAD

**Issue by haoliangxxx** [soimort/you-get#835]
detail of debug output:

```
you-get: version 0.4.217, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTQyNjUwNDUxNg==_ev_1.html']
Traceback (most recent call last):
  File "/opt/you-get-upstream/you-get", line 11, in 
    you_get.main(repo_path=_filepath)
  File "/opt/you-get-upstream/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/opt/you-get-upstream/src/you_get/common.py", line 1229, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/opt/you-get-upstream/src/you_get/common.py", line 1145, in script_main
    download_main(download, download_playlist, args, playlist, stream_id=stream_id, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/opt/you-get-upstream/src/you_get/common.py", line 1003, in download_main
    download(url, **kwargs)
  File "/opt/you-get-upstream/src/you_get/common.py", line 1222, in any_download
    m.download(url, **kwargs)
  File "/opt/you-get-upstream/src/you_get/extractor.py", line 50, in download_by_url
    self.download(**kwargs)
  File "/opt/you-get-upstream/src/you_get/extractor.py", line 160, in download
    json_output.output(self)
  File "/opt/you-get-upstream/src/you_get/json_output.py", line 15, in output
    print(json.dumps(out, indent=4, sort_keys=True, ensure_ascii=False))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-16: ordinal not in range(128)
```

It works for me only by `ensure_asscii=True`

as I don not use python, I can not commit a PR.

**Comment by soimort** [comment]
Unable to confirm, closing (before #838 gets fixed)
