### ISSUE TITLE
miomio.tv UnicodeEncodeError

### ISSUE THREAD

**Issue by nnpcYvIVl** [soimort/you-get#844]
C:\Download\you-get-0.4.217-win32-full\you-get>you-get --debug http://www.miomio.tv/watch/cc254010/
you-get: version 0.4.217, a tiny downloader that scrapes the web.
you-get: ['http://www.miomio.tv/watch/cc254010/']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "C:\msys64\home\win7\you-get\src\you_get\__main__.py", line 92, in main
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1229, in main
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1150, in script_main
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1003, in download_main
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 1222, in any_download
  File "C:\msys64\home\win7\you-get\src\you_get\extractors\miomio.py", line 34,in miomio_download
  File "C:\msys64\home\win7\you-get\src\you_get\common.py", line 938, in print_info
  File "e:\programs\python\python35\lib\encodings\cp1252.py", line 19, in encode

UnicodeEncodeError: 'charmap' codec can't encode characters in position 3-14: character maps to <undefined>
you-get returned -1

**Comment by soimort** [comment]
Windows CP-1252 doesn't handle CJK characters. Use CP-932 or UTF-8 instead.

**Comment by nnpcYvIVl** [comment]
I tried to use 65001 but the application crashed:

C:\Download\you-get-0.4.217-win32-full\you-get>chcp 65001
Active code page: 65001

C:\Download\you-get-0.4.217-win32-full\you-get>you-get http://www.miomio.tv/watch/cc254010/
Fatal Python error: Py_Initialize: can't initialize sys standard streams
LookupError: unknown encoding: cp65001

Current thread 0x00000f3c (most recent call first):

**Comment by soimort** [comment]
It is a [known bug](https://github.com/soimort/you-get/issues/812#issuecomment-164696201) caused by [pyinstaller/pyinstaller#1705](https://github.com/pyinstaller/pyinstaller/issues/1705).

This bug should only affect the Windows package built by PyInstaller, we can't fix it until the issue gets fixed in PyInstaller. **If you're on Windows and need the 65001 code page, don't use the `.7z`/`.exe` release for now**. Use the pip version or install from git instead.

Or you could try to switch to the corresponding code page, I guess either 932 or 936 should work in this case.
