### ISSUE TITLE
[youku] HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by univert** [soimort/you-get#845]
python you-get --debug "http://v.youku.com/v_show/id_XMTQyODI3MjI4MA==.html?f=26343628&ev=1"
```
you-get: version 0.4.217, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTQyODI3MjI4MA==.html?f=26343628&ev=1']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "src\you_get\common.py", line 1230, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "src\you_get\common.py", line 1151, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=jso
n_output)
  File "src\you_get\common.py", line 1004, in download_main
    download(url, **kwargs)
  File "src\you_get\common.py", line 1223, in any_download
    m.download(url, **kwargs)
  File "src\you_get\extractor.py", line 48, in download_by_url
    self.extract(**kwargs)
  File "src\you_get\extractors\youku.py", line 256, in extract
    ksegs += [i['server'] for i in json.loads(get_content(u))]
  File "src\you_get\common.py", line 295, in get_content
    response = request.urlopen(req)
  File "c:\global\python3.4\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "c:\global\python3.4\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "c:\global\python3.4\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\global\python3.4\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "c:\global\python3.4\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "c:\global\python3.4\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by soimort** [comment]
Neither #839 or #841 will work now.

**Comment by besta9188** [comment]
same as top

you-get --debug http://www.tudou.com/albumplay/WXDaOez0dhE/Aj-6Mpt5EC4.html

Traceback (most recent call last):
  File "c:\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python\python35\lib\site-packages\you_get\common.py", line 1229, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python\python35\lib\site-packages\you_get\common.py", line 1150, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "c:\python\python35\lib\site-packages\you_get\common.py", line 1003, in download_main
    download(url, **kwargs)
  File "c:\python\python35\lib\site-packages\you_get\common.py", line 1222, in any_download
    m.download(url, **kwargs)
  File "c:\python\python35\lib\site-packages\you_get\extractors\tudou.py", line 47, in tudou_download
    return youku_download_by_vid(vcode, title=title, output_dir=output_dir, merge=merge, info_only=info_only, **kwargs)
  File "c:\python\python35\lib\site-packages\you_get\extractor.py", line 66, in download_by_vid
    self.extract(**kwargs)
  File "c:\python\python35\lib\site-packages\you_get\extractors\youku.py", line 256, in extract
    ksegs += [i['server'] for i in json.loads(get_content(u))]
  File "c:\python\python35\lib\site-packages\you_get\common.py", line 294, in get_content
    response = request.urlopen(req)
  File "c:\python\python35\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python\python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "c:\python\python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python\python35\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "c:\python\python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "c:\python\python35\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by zhangn1985** [comment]
```
curl 'http://k.youku.com/player/getFlvPath/sid/245148247989010a651fb_00/st/flv/fileid/0300020900568158F47C7A2F6AABA814ACEF5E-8B66-56FD-F8A1-AEC6C137161A?K=c6ac7725fa878c4e241274e0&hd=0&myp=0&ts=386&ymovie=1&ypp=2&ctype=10&ev=1&token=3706&oip=1988431828&ep=IDN9OqIKmV75%2F4wT8eMafrBKQUubd68RGyO4Ct7O4jAz1F2QjWDFMmiTDFwPtMhrl0XiHfEnlzE6LHQ95c7cTBmnwvtIkCyUCkOKDBknFatVK4WpzEzpcAAoTzQGyhTVGYqCOMDEZhc%3D&yxon=1&special=true'
```
不带cookies请求，是能得到最终url的。
所以是里面参数错了。
我们目前的算法是用ctype=10的ep+token，带上ctype=12的segs算的。
可以试试都用ctype=10。。。

**Comment by zhangn1985** [comment]
试了一下也不行，莫非是ctype=12的算法变了，导致403？得认真看一下。

**Comment by linhua55** [comment]
@zhangn1985 
看来ct=12的需要名为r的cookie，ct=10的不需要。

**Comment by zhangn1985** [comment]
@linhua55 破解fascc才是正途呀。

**Comment by A-Circle-Zhang** [comment]
@zhangn1985 我这边已经弄出 ct = 10 的算法了。但我不希望这样的东西进入开源平台，这会导致它被大量盗用，很快失效。对比 ct = 10 、11、12、20、30 的算法之后，我认为你们研究的方向应该锁定在 ct = 20 和 30，也就是优酷的手机客户端和 TV 客户端，相对来说要简单，也普遍一些。

**Comment by Ouroboros** [comment]
```
func (self *YoukuDownloader) decryptSidAndToken(encryptString String) (sid, token String) {
    fmt.Println(encryptString)

    data := base64.DecodeString(encryptString.String())

    cipher, _ := des.NewCipher([]byte("00149ad5"))
    for i := 0; i < len(data); i += cipher.BlockSize() {
        cipher.Decrypt(data[i:], data[i:])
    }

    decrypted := String(data).Split("\x00", 1)[0].Split("_", 1)

    sid = decrypted[0]
    token = decrypted[1]
    return
}

func (self *YoukuDownloader) encryptEp(info YoukuVideoInfo, fileId String) String {
    bctime := 0
    ep := fmt.Sprintf("%v_%v_%v_%v", info.security.sid, fileId, info.security.token, bctime)
    sum := md5.Sum([]byte(ep + "_kservice"))

    ep = ep + "_" + fmt.Sprintf("%x", sum[:])[:4]

    data := []byte(ep)

    cipher, _ := des.NewCipher([]byte("21dd8110"))

    for len(data) % cipher.BlockSize() != 0 {
        data = append(data, 0)
    }

    for i := 0; i < len(data); i += cipher.BlockSize() {
        cipher.Encrypt(data[i:], data[i:])
    }

    return base64.EncodeToString(data)
}
```

我来回报社会了
花了1000大洋买了个AVS 2016, 发现跟免费的那个效果差不多, 稍微好一点点
