### ISSUE TITLE
music.163.com / netease - some songs work and some don't

### ISSUE THREAD

**Issue by rynstone** [soimort/you-get#858]
I keep getting timeouts for certain songs while other work just fine.
For example 
you-get --debug http://music.163.com/song?id=796424 
will dl without any issue, but
you-get --debug http://music.163.com/song?id=22704514
will always give me a timeout

**Comment by pini-gh** [comment]
It's worse now. It can't get anything from netease anymore. This has something to do with area restrictions, for sure.

I've had some success using a chinese proxy **plus** replacing "m5." with "m2." in URLs. "m5." URLs return 404.

**Comment by soimort** [comment]
True. Since I can't stream any of its tracks on its website, I don't know which exact server is handling the workload now.

It comes as no surprise to me that they will eventually shut down overseas access, due to unresolved copyright issues.

**Comment by rynstone** [comment]
I tried with https://github.com/JixunMoe/proxy-163
It seems to work, but the m2 links give a 404 now?

`[*] Proxy started at port 4003
[*] Proxy url http://music.163.com/api/song/detail/?id=22704514&ids=[22704514]&csrf_token=
[*] p* domain does not work, try proxy..
[*] Proxy via 218.106.96.202
[*] Proxy url http://m2.music.126.net/LRNFhoongTtaLRiOVecCNA==/1239149604503915.mp3
[*] p* domain does not work, try proxy..
[*] Proxy via 218.106.96.200
[*] Proxy url http://m2.music.126.net/LRNFhoongTtaLRiOVecCNA==/1239149604503915.mp3
[*] Proxy via 120.198.231.23`



`you-get --debug --http-proxy 185.109.144.149:4003 http://music.163.com/song?id=22704514
Site:       163.com
Title:      8. Godot ~ The Fragrance Of Dark Coffee
Type:       MP3 (audio/mpeg)
Size:       4.09 MiB (4284674 Bytes)

Downloading 8. Godot ~ The Fragrance Of Dark Coffee.mp3 ...
you-get: version 0.4.272, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/song?id=22704514']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.272', 'console_scripts', 'you-get')()
  File "/root/.local/lib/python3.3/site-packages/you_get-0.4.272-py3.3.egg/you_get/__main__.py", line 92, in main
  File "/root/.local/lib/python3.3/site-packages/you_get-0.4.272-py3.3.egg/you_get/common.py", line 1238, in main
  File "/root/.local/lib/python3.3/site-packages/you_get-0.4.272-py3.3.egg/you_get/common.py", line 1159, in script_main
  File "/root/.local/lib/python3.3/site-packages/you_get-0.4.272-py3.3.egg/you_get/common.py", line 1007, in download_main
  File "/root/.local/lib/python3.3/site-packages/you_get-0.4.272-py3.3.egg/you_get/common.py", line 1231, in any_download
  File "/root/.local/lib/python3.3/site-packages/you_get-0.4.272-py3.3.egg/you_get/extractors/netease.py", line 120, in netease_download
  File "/root/.local/lib/python3.3/site-packages/you_get-0.4.272-py3.3.egg/you_get/extractors/netease.py", line 66, in netease_cloud_music_download
  File "/root/.local/lib/python3.3/site-packages/you_get-0.4.272-py3.3.egg/you_get/extractors/netease.py", line 107, in netease_song_download
  File "/root/.local/lib/python3.3/site-packages/you_get-0.4.272-py3.3.egg/you_get/extractors/netease.py", line 113, in netease_download_common
  File "/root/.local/lib/python3.3/site-packages/you_get-0.4.272-py3.3.egg/you_get/common.py", line 691, in download_urls
  File "/root/.local/lib/python3.3/site-packages/you_get-0.4.272-py3.3.egg/you_get/common.py", line 404, in url_save
  File "/root/.local/lib/python3.3/site-packages/you_get-0.4.272-py3.3.egg/you_get/common.py", line 323, in url_size
  File "/usr/lib64/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.3/urllib/request.py", line 475, in open
    response = meth(req, response)
  File "/usr/lib64/python3.3/urllib/request.py", line 587, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.3/urllib/request.py", line 513, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 595, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
`

**Comment by rynstone** [comment]
nvm its working now!
