### ISSUE TITLE
非vip资源偶尔成功，偶尔失败，失败的时候程序挂死

### ISSUE THREAD

**Issue by wadeliuyi** [soimort/you-get#872]
root@ubuntu:/home/liuyi/vbox_get# ./you-get --json --debug http://v.youku.com/v_show/id_XNTM0NDQ2NzMy.html?from=y1.6-97.3.1.cc173812962411de83b1
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XNTM0NDQ2NzMy.html?from=y1.6-97.3.1.cc173812962411de83b1']
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 834, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 494, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "./src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "./src/you_get/common.py", line 1237, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "./src/you_get/common.py", line 1158, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "./src/you_get/common.py", line 1006, in download_main
    download(url, **kwargs)
  File "./src/you_get/common.py", line 1230, in any_download
    m.download(url, **kwargs)
  File "./src/you_get/extractor.py", line 48, in download_by_url
    self.extract(**kwargs)
  File "./src/you_get/extractors/youku.py", line 270, in extract
    ksegs += [i['server'] for i in json.loads(get_content(u))]
  File "./src/you_get/common.py", line 297, in get_content
    response = request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
root@ubuntu:/home/liuyi/vbox_get#

**Comment by soimort** [comment]
无法复现，请检查你的DNS和网络设置。

```
$ you-get -di http://v.youku.com/v_show/id_XNTM0NDQ2NzMy.html\?from\=y1.6-97.3.1.cc173812962411de83b1 
site:                优酷 (Youku)
title:               小龙人 02
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          53.9 MiB (56482304 bytes)
    # download-with: you-get --format=flvhd [URL]
```
