### ISSUE TITLE
视频无法解析

### ISSUE THREAD

**Issue by hitechbeijing** [soimort/you-get#873]
试了youku和youtube都是失败，以下是debug日志，请帮忙看看是什么问题

site:                YouTube
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=0HUAoaujnTw']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1237, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1158, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1006, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1230, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 50, in download_by_url
    self.download(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 172, in download
    self.p([])
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 121, in p
    print("title:               %s" % self.title)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-27: ordinal not in range(128)

**Comment by hitechbeijing** [comment]
应该是系统编码的问题，sys.getdefaultencoding()系统编码的确是UTF-8。终端都没法输入汉字。折腾半天，后来重装系统解决问题。
