### ISSUE TITLE
you-get does not work with Vimeo URLs containing no ID

### ISSUE THREAD

**Issue by codejunky** [soimort/you-get#879]
Hi! 

I get the following error when calling you-get:

[jan@virtual you-get-upstream]$ python3 you-get --debug  http://vimeo.com/fone/mitu-monteiro-pro-model-2015
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://vimeo.com/fone/mitu-monteiro-pro-model-2015']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "src/you_get/common.py", line 1237, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "src/you_get/common.py", line 1158, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "src/you_get/common.py", line 1006, in download_main
    download(url, **kwargs)
  File "src/you_get/common.py", line 1230, in any_download
    m.download(url, **kwargs)
  File "src/you_get/extractors/vimeo.py", line 62, in vimeo_download
    assert id
AssertionError

It seems that you-get does not handle the following URL correctly:
http://vimeo.com/fone/mitu-monteiro-pro-model-2015

Kind regards,
Jan

**Comment by soimort** [comment]
The video link redirects to https://vimeo.com/117250286, which has an actual ID. The fix is easy, though.
