### ISSUE TITLE
腾讯视频下载失败

### ISSUE THREAD

**Issue by yangaowei** [soimort/you-get#882]
python3 you-get --debug http://v.qq.com/page/e001958azai.html
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/page/e001958azai.html']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "src/you_get/common.py", line 1237, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "src/you_get/common.py", line 1158, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "src/you_get/common.py", line 1006, in download_main
    download(url, **kwargs)
  File "src/you_get/common.py", line 1230, in any_download
    m.download(url, **kwargs)
  File "src/you_get/extractors/qq.py", line 23, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "src/you_get/extractors/qq.py", line 11, in qq_download_by_vid
    url = output_json['vd']['vi'][0]['url']
KeyError: 'vd'

**Comment by yangaowei** [comment]
坐等大神回复

**Comment by yangaowei** [comment]
临时解决方案，对于这种视频，可以下载m站上的视频
