### ISSUE TITLE
没有办法下载vine上的视频

### ISSUE THREAD

**Issue by xiukunhuang** [soimort/you-get#886]
C:\Users\Robin.Huang>you-get --debug https://vine.co/v/iMTBZpe9Unp
Site:       Vine.co
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['https://vine.co/v/iMTBZpe9Unp']
Traceback (most recent call last):
  File "c:\users\robin.huang\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\robin.huang\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Robin.Huang\AppData\Local\Programs\Python\Python35-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\robin.huang\appdata\local\programs\python\python35-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\robin.huang\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1237, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\robin.huang\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1158, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\robin.huang\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1006, in download_main
    download(url, **kwargs)
  File "c:\users\robin.huang\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1230, in any_download
    m.download(url, **kwargs)
  File "c:\users\robin.huang\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\vine.py", line 18, in vine_download
    print_info(site_info, title, mime, size)
  File "c:\users\robin.huang\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 941, in print_info
    print("Title:     ", unescape_html(tr(title)))
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f331' in position 21: illegal multibyte sequence
Title:

**Comment by nuomi1** [comment]
`UnicodeEncodeError` 的问题，文件名含有 emoji 表情。

```
you-get https://vine.co/v/iMTBZpe9Unp
Site:       Vine.co
Title:      Watch LXGRKN's Vine "🌱"
Type:       MPEG-4 video (video/mp4)
Size:       0.8 MiB (843784 Bytes)

Downloading Watch LXGRKN's Vine "🌱".mp4 ...
100.0% (  0.8/0.8  MB) ├██████████████████████████████████████┤[1/1]   91 kB/s
```

**Comment by soimort** [comment]
同上。
