### ISSUE TITLE
[Sohu] Blocked access from outside mainland China

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#9]
```sh
➜  you-get git:(master) ✗ ./you-get -i http://tv.sohu.com/20110923/n320325529.shtml
Traceback (most recent call last):
  File "./you-get", line 6, in <module>
    main()
  File "/home/soimort/Source/you-get/you_get/main.py", line 55, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/soimort/Source/you-get/you_get/common.py", line 643, in script_main
    download_main(download, download_playlist, args, playlist, output_dir, merge, info_only)
  File "/home/soimort/Source/you-get/you_get/common.py", line 563, in download_main
    download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/soimort/Source/you-get/you_get/main.py", line 48, in any_download
    m.download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/soimort/Source/you-get/you_get/downloader/sohu.py", line 21, in sohu_download
    title = data['tvName']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by soimort** [comment]
No longer care. Any volunteers?
