### ISSUE TITLE
下载搜狐视频时报错

### ISSUE THREAD

**Issue by khalidhsu** [soimort/you-get#900]
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://tv.sohu.com/20130302/n367600509.shtml?txid=9075b2a7de230eeef8505336cfdc34ae']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1237, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1158, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1006, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1230, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/sohu.py", line 35, in sohu_download
    hqvid = info['data'][qtyp]
TypeError: 'NoneType' object is not subscriptable

linode主机
Distributor ID: Debian
Description:    Debian GNU/Linux 7.6 (wheezy)
Release:        7.6
Codename:       wheezy

python3.5.1 x64

在本地电脑可以正常下载的。linode主机会报错，未搞清楚原因

**Comment by soimort** [comment]
地区限制。
