### ISSUE TITLE
本机解析不了，服务器上可以？

### ISSUE THREAD

**Issue by zouhua** [soimort/you-get#902]
[root@vagrant-centos65 you-get]# ./you-get -d 'http://v.youku.com/v_show/id_XMTQ1MjU4NDQ2MA==.html'
you-get: version 0.4.125, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTQ1MjU4NDQ2MA==.html']
Traceback (most recent call last):
  File "./you-get", line 17, in <module>
    you_get.main(repo_path=_filepath)
  File "/vagrant/python/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/vagrant/python/you-get/src/you_get/common.py", line 1213, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/vagrant/python/you-get/src/you_get/common.py", line 1134, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/vagrant/python/you-get/src/you_get/common.py", line 987, in download_main
    download(url, **kwargs)
  File "/vagrant/python/you-get/src/you_get/common.py", line 1205, in any_download
    m, url = url_to_module(url)
  File "/vagrant/python/you-get/src/you_get/common.py", line 1192, in url_to_module
    return import_module('.'.join(['you_get', 'extractors', SITES[k]])), url
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/vagrant/python/you-get/src/you_get/extractors/__init__.py", line 3, in <module>
    from .acfun import *
  File "/vagrant/python/you-get/src/you_get/extractors/acfun.py", line 11, in <module>
    from .youku import youku_download_by_vid
ImportError: cannot import name 'youku_download_by_vid'

**Comment by soimort** [comment]
0.4.125是很老的版本了。请按照说明重新安装you-get。
