### ISSUE TITLE
cctv部分链接地址不支持啊

### ISSUE THREAD

**Issue by xujiangit** [soimort/you-get#909]
http://jiankang.cntv.cn/jiankangzhilu/classpage/video/20110930/100261.shtml

you-get --debug http://jiankang.cntv.cn/jiankangzhilu/classpage/video/20110930/100261.shtml
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://jiankang.cntv.cn/jiankangzhilu/classpage/video/20110930/100261.shtml']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/**main**.py", line 92, in main
    main(*_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1237, in main
    script_main('you-get', any_download, any_download_playlist, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1158, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1006, in download_main
    download(url, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1230, in any_download
    m.download(url, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/cntv.py", line 39, in cntv_download
    raise NotImplementedError(url)
NotImplementedError: http://jiankang.cntv.cn/jiankangzhilu/classpage/video/20110930/100261.shtml

**Comment by zhangn1985** [comment]
需要用playlist来实现。但是，这个html解析有点不好做。
