### ISSUE TITLE
Redirecting StdOut: UnicodeEncodeError

### ISSUE THREAD

**Issue by VertigoRay** [soimort/you-get#913]
I have a URL that works ...

```powershell
PS > & you-get-0.4.245-win32.exe --debug 'http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&'
Site:       Dailymotion.com
Title:      Telemundo 02-02-2016
Type:       MPEG-4 video (video/mp4)
Size:       128.85 MiB (135106815 Bytes)

Downloading Telemundo 02-02-2016.mp4 ...
  2.3% (  3.0/128.8MB) ├█─────────────────────────────────────┤[1/1]  123 kB/s
```

Except when trying to redirect StdOut ...

```powershell
PS > & you-get-0.4.245-win32.exe --debug 'http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&' | Out-File $log -Append
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1237, in main
  File "src\you_get\common.py", line 1158, in script_main
  File "src\you_get\common.py", line 1006, in download_main
  File "src\you_get\common.py", line 1230, in any_download
  File "src\you_get\extractors\dailymotion.py", line 28, in dailymotion_download
  File "src\you_get\common.py", line 690, in download_urls
  File "src\you_get\common.py", line 431, in url_save
  File "src\you_get\common.py", line 585, in update_received
  File "src\you_get\common.py", line 571, in update
  File "e:\programs\python\python35\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-63: character maps to <undefined>
you-get returned -1
```

Same thing happens using `Start-Process` ...

*Here's the script ([full code](https://github.com/VertigoRay/Download-EcuaVisa/blob/master/Download-EcuaVisa.ps1)):*
```powershell
# snipped some code, but it's irrelevant
foreach ($i in 0..($number_of_episodes_to_keep-1)) {
    $episode_url = $noticieros_episode -f $episode_numbers[$i]
    Write-Output "Episode URL (initial): ${episode_url}" | Out-File $log -Append
    try {
        $html = (Invoke-WebRequest $episode_url -UseBasicParsing).Content
    } catch {
        Write-Output "[$($_.Exception.GetType().FullName)] $($_.Exception.Message)" | Out-File $log -Append
    }

    $url = [regex]::matches($html, '<iframe(?:[^>]*)src="([^"]+)"', 'IgnoreCase') | %{ $_.Groups[1].Value }
    Write-Output "Episode URL  (actual): ${url}" | Out-File $log -Append
    $proc = Start-Process -FilePath $you_get -ArgumentList @('--debug', $url) -WorkingDirectory $plex_tv_ecuavisa -Wait -PassThru -WindowStyle Hidden -RedirectStandardOutput $stdout -RedirectStandardError $stderr

    Get-Content $stdout -ErrorAction Ignore | %{ Write-Output "You_Get StdOut: $($_.Trim())" | Out-File $log -Append }
    Write-Output "You_Get Process ($($proc.ID)) Completed [$($proc.ExitCode)] at $($proc.ExitTime): `n$(($proc | Out-String).Trim())" | Out-File $log -Append
    Get-Content $stderr -ErrorAction Ignore | %{ Write-Output "You_Get StdErr: $($_.Trim())" | Out-File $log -Append }
    $stdout, $stderr | Remove-Item -Force -ErrorAction Ignore
}
```

*Here's what gets put in the log:*
```log
Episode URL (initial): http://www.ecuavisa.com/ajax-noticiero/nojs/127315/ampliado
Episode URL  (actual): http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&
You_Get StdOut: Site:       Dailymotion.com
You_Get StdOut: Title:      Telemundo 02-02-2016
You_Get StdOut: Type:       MPEG-4 video (video/mp4)
You_Get StdOut: Size:       128.85 MiB (135106815 Bytes)
You_Get StdOut: 
You_Get StdOut: Downloading Telemundo 02-02-2016.mp4 ...
You_Get Process (16868) Completed [-1] at 02/03/2016 13:11:49: 
Handles  NPM(K)    PM(K)      WS(K) VM(M)   CPU(s)     Id  SI ProcessName                                              
-------  ------    -----      ----- -----   ------     --  -- -----------                                              
              0        0          0     0     0.05  16868
You_Get StdErr: you-get: version 0.4.245, a tiny downloader that scrapes the web.
You_Get StdErr: you-get: ['http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&']
You_Get StdErr: Traceback (most recent call last):
You_Get StdErr: File "<string>", line 11, in <module>
You_Get StdErr: File "src\you_get\__main__.py", line 92, in main
You_Get StdErr: File "src\you_get\common.py", line 1237, in main
You_Get StdErr: File "src\you_get\common.py", line 1158, in script_main
You_Get StdErr: File "src\you_get\common.py", line 1006, in download_main
You_Get StdErr: File "src\you_get\common.py", line 1230, in any_download
You_Get StdErr: File "src\you_get\extractors\dailymotion.py", line 28, in dailymotion_download
You_Get StdErr: File "src\you_get\common.py", line 690, in download_urls
You_Get StdErr: File "src\you_get\common.py", line 431, in url_save
You_Get StdErr: File "src\you_get\common.py", line 585, in update_received
You_Get StdErr: File "src\you_get\common.py", line 571, in update
You_Get StdErr: File "e:\programs\python\python35\lib\encodings\cp1252.py", line 19, in encode
You_Get StdErr: UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-63: character maps to <undefined>
You_Get StdErr: you-get returned -1
```

**Comment by soimort** [comment]
Hi,

1. Debugging PowerShell code is something beyond my scope. Please try to narrate the problem on the side of `you-get`.

2. I'm not sure why would you redirect the progress bar (which is intended for terminal display only) to StdOut, but I'd imagine that it IS problematic on Windows, due to incompatible code page or other encoding related issues. A quick google search leads me to https://gist.github.com/xoner/4671514, so, as a general suggestion: you should always use UTF-8 as the default coding, even if scripting on Windows.

**Comment by VertigoRay** [comment]
The problem is narrated on the side of `you-get`. There's plenty of python errors in there referring to `src\you_get\common.py`.

I don't care about logging the progress bar, just the text output so I can dump it to a log file. So I can check status of this reoccurring job later, of course. **Maybe this should be a feature request?**  Here are some idea options that shouldn't be too hard to implement:

- Add a `--log` parameter.
  - If you do that, I'm sure you'll use [logging](https://docs.python.org/3.5/library/logging.html), so maybe you can also add a `--logformat` parameter.
  - Logging should be append mode without keep a the file handle open.
- Add a `--hide-progress` parameter. This should be self explanatory.
- Add a `--quiet` parameter. Hides all output to the command-line.

**Comment by soimort** [comment]
@VertigoRay So, have you tried to default to UTF-8 encoding yet?

---

`--quiet` seems to be a fair idea to me, though I'm not sure if most users actually need the logging feature. It's much easier to open a new terminal session, run the command and wait for it to finish; `you-get` was not designed to be a daemon, so showing the progress bar foreground should suffice in most cases.

**Comment by VertigoRay** [comment]
Trying UTF-8 (added ` -Encoding utf8` to `Out-File`):

```powershell
PS > & you-get-0.4.245-win32.exe --debug 'http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&' | Out-File 'C:\Temp\you-get-0.4.245-win32.log' -Append -Encoding utf8
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1237, in main
  File "src\you_get\common.py", line 1158, in script_main
  File "src\you_get\common.py", line 1006, in download_main
  File "src\you_get\common.py", line 1230, in any_download
  File "src\you_get\extractors\dailymotion.py", line 28, in dailymotion_download
  File "src\you_get\common.py", line 690, in download_urls
  File "src\you_get\common.py", line 431, in url_save
  File "src\you_get\common.py", line 585, in update_received
  File "src\you_get\common.py", line 571, in update
  File "e:\programs\python\python35\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-63: character maps to <undefined>
you-get returned -1
```

I'm not trying to use it as a daemon either. I was just trying to call it with some intelligence in a *Scheduled Task*. I'll explain what I was *hacking* on here, I was trying to shove it into a *Scheduled Task* for some automagic. However, running the *Scheduled Task* as *hidden* produced no results. I haven't looked into it, but I'm thinking it's related to this unicode err. The ability to hide some of the output might resolve this. :unamused:

Thanks for all the great work on `you-get`. I [re-wrote my script in Python](/VertigoRay/Download-EcuaVisa/blob/master/download-ecuavista.py) and put it on my [Synology](https://www.synology.com/en-global/products/DS1511+) to auto-download the latest episodes and put them where [Plex](http://plex.tv) will find them, keeping only the latest episodes since it's just the news.

Cheers!! :beers:

**Comment by soimort** [comment]
```console
File "e:\programs\python\python35\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-63: character maps to <undefined>
you-get returned -1
```

This line indicated that it's still on the same code page `cp1252` rather than UTF-8 (which is `65001`).

**Comment by VertigoRay** [comment]
Okay, this time, I'll change the console encoding ...

```powershell
PS > [Console]::OutputEncoding


IsSingleByte      : True
BodyName          : IBM437
EncodingName      : OEM United States
HeaderName        : IBM437
WebName           : IBM437
WindowsCodePage   : 1252
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : False
IsMailNewsSave    : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 437



PS > $OutputEncoding = New-Object -typename System.Text.UTF8Encoding
PS > [Console]::OutputEncoding = New-Object -typename System.Text.UTF8Encoding
PS > [Console]::OutputEncoding


BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : False
CodePage          : 65001


PS > # Try `Out-File` without `-Encoding` parameter ...
PS > & you-get-0.4.245-win32.exe --debug 'http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&' | Out-File 'C:\Temp\you-get-0.4.245-win32.log' -Append
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1237, in main
  File "src\you_get\common.py", line 1158, in script_main
  File "src\you_get\common.py", line 1006, in download_main
  File "src\you_get\common.py", line 1230, in any_download
  File "src\you_get\extractors\dailymotion.py", line 28, in dailymotion_download
  File "src\you_get\common.py", line 690, in download_urls
  File "src\you_get\common.py", line 431, in url_save
  File "src\you_get\common.py", line 585, in update_received
  File "src\you_get\common.py", line 571, in update
  File "e:\programs\python\python35\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-63: character maps to <undefined>
you-get returned -1
PS > # Try `Out-File` with `-Encoding utf8` parameter ...
PS > & you-get-0.4.245-win32.exe --debug 'http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&' | Out-File 'C:\Temp\you-get-0.4.245-win32.log' -Append -Encoding utf8
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1237, in main
  File "src\you_get\common.py", line 1158, in script_main
  File "src\you_get\common.py", line 1006, in download_main
  File "src\you_get\common.py", line 1230, in any_download
  File "src\you_get\extractors\dailymotion.py", line 28, in dailymotion_download
  File "src\you_get\common.py", line 690, in download_urls
  File "src\you_get\common.py", line 431, in url_save
  File "src\you_get\common.py", line 585, in update_received
  File "src\you_get\common.py", line 571, in update
  File "e:\programs\python\python35\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-63: character maps to <undefined>
you-get returned -1
```

**Comment by VertigoRay** [comment]
Maybe since it's a Unicode error, I should change to Unicode?

```powershell
PS > $OutputEncoding = New-Object -typename System.Text.UnicodeEncoding
PS > [Console]::OutputEncoding = New-Object -typename System.Text.UnicodeEncoding
PS > [Console]::OutputEncoding


BodyName          : utf-16
EncodingName      : Unicode
HeaderName        : utf-16
WebName           : utf-16
WindowsCodePage   : 1200
IsBrowserDisplay  : False
IsBrowserSave     : True
IsMailNewsDisplay : False
IsMailNewsSave    : False
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : False
CodePage          : 1200



PS > # Try `Out-File` without `-Encoding` parameter ...
PS > & you-get-0.4.245-win32.exe --debug 'http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&' | Out-File 'C:\Temp\you-get-0.4.245-win32.log' -Append
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1237, in main
  File "src\you_get\common.py", line 1158, in script_main
  File "src\you_get\common.py", line 1006, in download_main
  File "src\you_get\common.py", line 1230, in any_download
  File "src\you_get\extractors\dailymotion.py", line 28, in dailymotion_download
  File "src\you_get\common.py", line 690, in download_urls
  File "src\you_get\common.py", line 431, in url_save
  File "src\you_get\common.py", line 585, in update_received
  File "src\you_get\common.py", line 571, in update
  File "e:\programs\python\python35\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-63: character maps to <undefined>
you-get returned -1
PS > # Try `Out-File` with `-Encoding unicode` parameter ...
PS > & you-get-0.4.245-win32.exe --debug 'http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&' | Out-File 'C:\Temp\you-get-0.4.245-win32.log' -Append -Encoding unicode
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1237, in main
  File "src\you_get\common.py", line 1158, in script_main
  File "src\you_get\common.py", line 1006, in download_main
  File "src\you_get\common.py", line 1230, in any_download
  File "src\you_get\extractors\dailymotion.py", line 28, in dailymotion_download
  File "src\you_get\common.py", line 690, in download_urls
  File "src\you_get\common.py", line 431, in url_save
  File "src\you_get\common.py", line 585, in update_received
  File "src\you_get\common.py", line 571, in update
  File "e:\programs\python\python35\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-63: character maps to <undefined>
you-get returned -1
```

**Comment by VertigoRay** [comment]
I think the fix for this is two fold:

1. Make a `--quiet` and/or `--hide-progress` parameter.
1. Use `try` to catch this exception and throw an intelligent error pointing the user to try using the `--quiet` and/or `--hide-progress` parameter.

**Comment by soimort** [comment]
I just tried on a Windows 7 machine with code page `1252` today, couldn't reproduce your issue

![cp](https://cloud.githubusercontent.com/assets/342945/12852351/6b9c170c-cc26-11e5-9f8f-21a06e26c347.png)

The log output looks weird because of wrong encoding, but it should just work and not throw an exception.

![1](https://cloud.githubusercontent.com/assets/342945/12852631/da8dc114-cc27-11e5-94d6-dce02f5f5892.png)

As I said, if you look at the last 2 lines in the trackback, **your python environment is insisting on using the `cp1252` rather than UTF-8**, and I have no idea why it is the case. You should try something like `$env:PYTHONIOENCODING = "UTF-8"` (not familiar with PowerShell though, but make sure to put that env variable correct)

**Comment by VertigoRay** [comment]
Interesting ... not sure what else you've got going on in your profile. What are your `$OutputEncoding` and `[Console]::OutputEncoding`? 

Just because it works on one computer doesn't make this a non-issue. I still think you should [add the parameters we discussed](https://github.com/soimort/you-get/issues/913#issuecomment-180112268) to ensure consistent functionality.

---------------------------------------------------

My clean Win7 Test VM experiences that same issue:
![image](https://cloud.githubusercontent.com/assets/792482/12855236/47fd5a00-cc0c-11e5-8b41-6a2538798af1.png)

Does not work as you demonstrated for me in Windows 10 Pro x64 either:

```powershell
PS C:\temp> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.10586.0 Microsoft Windows NT 10.0.10586.0

PS C:\temp> chcp 1252
Active code page: 1252
PS C:\temp> .\you-get-0.4.272-win32.exe --debug 'http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&' | Out-File 'C:\Temp\you-get-0.4.245-win32.log' -Append
you-get: version 0.4.272, a tiny downloader that scrapes the web.
you-get: ['http://www.dailymotion.com/embed/video/x3q7lrw?syndication=173592?info=0&logo=0&related=0&']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1238, in main
  File "src\you_get\common.py", line 1159, in script_main
  File "src\you_get\common.py", line 1007, in download_main
  File "src\you_get\common.py", line 1231, in any_download
  File "src\you_get\extractors\dailymotion.py", line 28, in dailymotion_download
  File "src\you_get\common.py", line 691, in download_urls
  File "src\you_get\common.py", line 475, in url_save
  File "src\you_get\common.py", line 586, in update_received
  File "src\you_get\common.py", line 572, in update
  File "e:\programs\python\python35\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-63: character maps to <undefined>
you-get returned -1
```

**Comment by soimort** [comment]
I just noticed that you kept using the prebuilt `you-get.exe` all along. I understand that the prebuilt binary could have caused unexpected issues on your system settings, but I was not able to devote much time to test it on different Windows envs. This `exe` is generated by PyInstaller via an automatized script every time a new release is made; there's no reliable way to tell that it's not malicious (_maybe it is_!)
Note that this `exe` is just for non-developers' convenience; since you are a programmer and trying to integrate it as part of scripting, I strongly recommend you not to use the binary, but the source code.

Please **try to install `you-get` via the "canonical" approach** (e.g. pip, git, direct calling `python you-get`), then ping me back again.

---

To all other volunteers on Windows: if you are able to host nightly builds for Windows binaries as a 3rd party, or if you have a clean environment for testing those binaries, please let me know. I would appreciate any help on that!

**Comment by soimort** [comment]
Oh, and on the `--hide-progress` option you suggested: it would be nice to have that, but if your code page has some issues even with the progress bar, it **will** have the same issue on **any video titles with non-Latin characters**. I would say it's in no way a solution to the encoding issue you have. `chcp 65001` is. See if you can download this video with `you-get`:

- https://www.youtube.com/watch?v=xL86MWw7YQY
