### ISSUE TITLE
网易视频有些会出错

### ISSUE THREAD

**Issue by magicknight** [soimort/you-get#917]
比如这个

you-get --debug http://v.163.com/zixun/V8GAM7JAP/VBE9LPR8T.html
you-get: version 0.4.272, a tiny downloader that scrapes the web.
you-get: ['http://v.163.com/zixun/V8GAM7JAP/VBE9LPR8T.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1238, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1159, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1007, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1231, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/netease.py", line 136, in netease_download
    _, _, hd_size = url_info(hd_url)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 346, in url_info
    response = request.urlopen(request.Request(url))
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 470, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 502, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 685, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 470, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 508, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 588, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by soimort** [comment]
Thanks for the bug report, this should be fixed now.
