### ISSUE TITLE
新浪部分视频出错

### ISSUE THREAD

**Issue by magicknight** [soimort/you-get#922]
you-get: version 0.4.272, a tiny downloader that scrapes the web.
you-get: ['http://video.sina.com.cn/p/news/live/gtx/v/2016-02-15/111665184811.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.272', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.4.272-py3.4.egg/you_get/__main__.py", line 92, in main
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.4.272-py3.4.egg/you_get/common.py", line 1238, in main
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.4.272-py3.4.egg/you_get/common.py", line 1159, in script_main
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.4.272-py3.4.egg/you_get/common.py", line 1007, in download_main
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.4.272-py3.4.egg/you_get/common.py", line 1231, in any_download
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.4.272-py3.4.egg/you_get/extractors/sina.py", line 77, in sina_download
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.4.272-py3.4.egg/you_get/extractors/sina.py", line 33, in sina_download_by_vid
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.4.272-py3.4.egg/you_get/extractors/sina.py", line 47, in sina_download_by_xml
  File "/usr/local/lib/python3.4/dist-packages/you_get-0.4.272-py3.4.egg/you_get/common.py", line 655, in download_urls
AssertionError

**Comment by nuomi1** [comment]
```
you-get http://video.sina.com.cn/p/news/live/gtx/v/2016-02-15/111665184811.html
Site:       Sina.com
Title:      奥巴马情人节公开秀恩爱 为爱妻念肉麻情诗
Type:       Flash video (video/x-flv)
Size:       16.22 MiB (17002796 Bytes)

Downloading 奥巴马情人节公开秀恩爱 为爱妻念肉麻情诗.flv ...
100.0% ( 16.2/16.2 MB) ├██████████████████████████████████████┤[1/1]    1 MB/s
```

没有问题。
