### ISSUE TITLE
优酷失效了

### ISSUE THREAD

**Issue by amitbha** [soimort/you-get#937]
在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get --debug 'http://v.youku.com/v_show/id_XMTQ4MzU1ODU0OA==.html'
you-get: version 0.4.125, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTQ4MzU1ODU0OA==.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1213, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1134, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 987, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1206, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractor.py", line 39, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/youku.py", line 110, in prepare
    meta = json.loads(get_html('http://v.youku.com/player/getPlayList/VideoIDS/%s/Pf/4/ctype/12/ev/1' % self.vid))
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 254, in get_html
    content = get_response(url, faker).data
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 242, in get_response
    response = request.urlopen(url)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1243, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by cnbeining** [comment]
您没有检查

 - [ ] 您的问题没有在https://github.com/soimort/you-get/issues 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.

例如。。。#928 ？

**Comment by amitbha** [comment]
扫了下，没认出来
还是对中文比较敏感。。

**Comment by soimort** [comment]
(1) 首先，这个视频不是VIP视频，和 #928 无关。

```
$ you-get -di http://v.youku.com/v_show/id_XMTQ4MzU1ODU0OA\=\=.html 
site:                优酷 (Youku)
title:               容祖儿动情吟唱《月半小夜曲》 天后妙音如泣似诉 160226
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          11.7 MiB (12279524 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          8.9 MiB (9338361 bytes)
    # download-with: you-get --format=flvhd [URL]
```

(2) 其次，
- [ ] **您的you-get为最新版.**

```
you-get: version 0.4.125, a tiny downloader that scrapes the web.
```

为什么看都不看就打勾呢？

**Comment by amitbha** [comment]
我是按照首页指示新安装的，没想到不是最新版啊，忘了看 release 记录
$ pip3 install you-get

**Comment by soimort** [comment]
请运行
```
$ you-get -V
```

如果不是`version 0.4.306`，说明最新版没有正确地安装到路径中（或者是pypi镜像太旧了）
