### ISSUE TITLE
windows系统下的you-get无法解析下载视频

### ISSUE THREAD

**Issue by gayhubnewcomer** [soimort/you-get#939]
使用的是最新的release里面的exe，以及pip包安装的方法，在windows系统下均出现错误，无法下载视频，无论是youku、acfun等国内网站的视频还是在挂代理时候下载youtube视频都不行
debug信息：
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1250, in main
  File "src\you_get\common.py", line 1171, in script_main
  File "src\you_get\common.py", line 1019, in download_main
  File "src\you_get\common.py", line 1243, in any_download
  File "src\you_get\extractor.py", line 50, in download_by_url
  File "src\you_get\extractor.py", line 186, in download
  File "src\you_get\extractor.py", line 120, in p
  File "e:\programs\python\python35\lib\encodings\cp437.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 21-22: character maps to <undefined>
you-get returned -1

**Comment by cnbeining** [comment]
您试过https://github.com/soimort/you-get/wiki/FAQ 了？

**Comment by gayhubnewcomer** [comment]
好的，多谢，设为65001以后解决了

**Comment by cnbeining** [comment]
OK，我关issue了。

Issue头落下个link 得补上。

**Comment by jackey99** [comment]
@gayhubnewcomer 请问下怎么设置的，我看不太明白，我的问题跟你的一样
