### ISSUE TITLE
windowns 64 ,why?

### ISSUE THREAD

**Issue by youppgd** [soimort/you-get#940]
you-get: version 0.4.293, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/a_19rrhc496p.html']
Traceback (most recent call last):
  File "C:\Python34\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.4.293', 'console_scripts', 'you-get')()
  File "C:\Python34\lib\site-packages\you_get-0.4.293-py3.4.egg\you_get\__main__.py", line 92, in main
  File "C:\Python34\lib\site-packages\you_get-0.4.293-py3.4.egg\you_get\common.py", line 1250, in main
  File "C:\Python34\lib\site-packages\you_get-0.4.293-py3.4.egg\you_get\common.py", line 1171, in script_main
  File "C:\Python34\lib\site-packages\you_get-0.4.293-py3.4.egg\you_get\common.py", line 1019, in download_main
  File "C:\Python34\lib\site-packages\you_get-0.4.293-py3.4.egg\you_get\common.py", line 1243, in any_download
  File "C:\Python34\lib\site-packages\you_get-0.4.293-py3.4.egg\you_get\extractor.py", line 39, in download_by_url
  File "C:\Python34\lib\site-packages\you_get-0.4.293-py3.4.egg\you_get\extractors\iqiyi.py", line 131, in prepare
  File "C:\Python34\lib\site-packages\you_get-0.4.293-py3.4.egg\you_get\extractors\iqiyi.py", line 106, in getVMS
  File "C:\Python34\lib\site-packages\you_get-0.4.293-py3.4.egg\you_get\extractors\iqiyi.py", line 50, in mix
TypeError: Can't convert 'NoneType' object to str implicitly

**Comment by nuomi1** [comment]
you-get doesn't support iqiyi playlist.
