### ISSUE TITLE
Win10, 64bit, can't download youtube vedios

### ISSUE THREAD

**Issue by ZYT2014** [soimort/you-get#944]
you-get: version 0.4.306, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=KPX7GXSc1q8']
Traceback (most recent call last):
  File "e:\python\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Python\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "e:\python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "e:\python\lib\site-packages\you_get\common.py", line 1250, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "e:\python\lib\site-packages\you_get\common.py", line 1171, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "e:\python\lib\site-packages\you_get\common.py", line 1019, in download_main
    download(url, **kwargs)
  File "e:\python\lib\site-packages\you_get\common.py", line 1243, in any_download
    m.download(url, **kwargs)
  File "e:\python\lib\site-packages\you_get\extractor.py", line 39, in download_by_url
    self.prepare(**kwargs)
  File "e:\python\lib\site-packages\you_get\extractors\youtube.py", line 150, in prepare
    self.title = parse.unquote_plus(video_info['title'][0])
KeyError: 'title'

**Comment by ZYT2014** [comment]
And for youku
you-get: version 0.4.306, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XNzIwODk2NTky.html?from=s1.8-1-1.2']
Traceback (most recent call last):
  File "e:\python\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Python\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "e:\python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "e:\python\lib\site-packages\you_get\common.py", line 1250, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "e:\python\lib\site-packages\you_get\common.py", line 1171, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "e:\python\lib\site-packages\you_get\common.py", line 1019, in download_main
    download(url, **kwargs)
  File "e:\python\lib\site-packages\you_get\common.py", line 1243, in any_download
    m.download(url, **kwargs)
  File "e:\python\lib\site-packages\you_get\extractor.py", line 50, in download_by_url
    self.download(**kwargs)
  File "e:\python\lib\site-packages\you_get\extractor.py", line 186, in download
    self.p(stream_id)
  File "e:\python\lib\site-packages\you_get\extractor.py", line 120, in p
    print("site:                %s" % self.__class__.name)
  File "e:\python\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 21-22: character maps to <undefined>

**Comment by soimort** [comment]
For the first video: This is a YouTube Red video which is behind a paywall. If you have paid for access to it, please try with your browser cookies via `--cookies`.
(I'm not sure if all you want is the preview version; in that case we might find a workaround.)

For the second video, please refer to
https://github.com/soimort/you-get/wiki/FAQ

**Comment by ZYT2014** [comment]
Thanks for replying! Is there any way to get the preview video?
