### ISSUE TITLE
无法下载爱奇艺视频

### ISSUE THREAD

**Issue by RockWithBoA** [soimort/you-get#952]
日志如下

```
D:\Python34\you-get>python you-get -i --debug http://www.iqiyi.com/v_19rrkviljg.
html
site:                爱奇艺 (Iqiyi)
you-get: version 0.4.306, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrkviljg.html']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "src\you_get\common.py", line 1253, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "src\you_get\common.py", line 1174, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "src\you_get\common.py", line 1022, in download_main
    download(url, **kwargs)
  File "src\you_get\common.py", line 1246, in any_download
    m.download(url, **kwargs)
  File "src\you_get\extractor.py", line 50, in download_by_url
    self.download(**kwargs)
  File "src\you_get\extractor.py", line 172, in download
    self.p([])
  File "src\you_get\extractor.py", line 121, in p
    print("title:               %s" % self.title)
UnicodeEncodeError: 'gbk' codec can't encode character '\u200b' in position 37:
illegal multibyte sequence
```

**Comment by soimort** [comment]
https://github.com/soimort/you-get/wiki/FAQ
