### ISSUE TITLE
debug issue

### ISSUE THREAD

**Issue by KingSora** [soimort/you-get#958]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ x ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ x ] Your `you-get` is up-to-date.
- [ x ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ x ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get: version 0.4.293, a tiny downloader that scrapes the web.
you-get: ['http://www.xiami.com/song/1770838366?spm=a1z1s.3061781.226669510.9.vP
w2V1']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1250, in main
  File "src\you_get\common.py", line 1171, in script_main
  File "src\you_get\common.py", line 1019, in download_main
  File "src\you_get\common.py", line 1243, in any_download
  File "src\you_get\extractors\xiami.py", line 157, in xiami_download
  File "src\you_get\extractors\xiami.py", line 65, in xiami_download_song
  File "src\you_get\common.py", line 700, in download_urls
  File "e:\programs\python\python35\lib\encodings\cp850.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 26-31: c
haracter maps to <undefined>
you-get returned -1
```

**Comment by cnbeining** [comment]
https://github.com/soimort/you-get/wiki/FAQ
