### ISSUE TITLE
Youtube - any underscore or hyphen will not download

### ISSUE THREAD

**Issue by sente2357** [soimort/you-get#959]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ x] Your `you-get` is up-to-date.
- [x ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[C:\Python34\Scripts>you-get --debug -o C:/_Downloads/video https://www.youtube.c
om/watch?v=5_TtRsvgefc
site:                YouTube
you-get: version 0.4.293, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=5_TtRsvgefc']
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1250, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1171, in script_m
ain
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1019, in download
_main
    download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\common.py", line 1243, in any_down
load
    m.download(url, **kwargs)
  File "c:\python34\lib\site-packages\you_get\extractor.py", line 50, in downloa
d_by_url
    self.download(**kwargs)
  File "c:\python34\lib\site-packages\you_get\extractor.py", line 186, in downlo
ad
    self.p(stream_id)
  File "c:\python34\lib\site-packages\you_get\extractor.py", line 121, in p
    print("title:               %s" % self.title)
  File "c:\python34\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 21-27: c
haracter maps to <undefined>
]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by soimort** [comment]
1. Your `you-get` is NOT up-to-date.
2. Also, did you tried `chcp 65001`, as suggested by https://github.com/soimort/you-get/wiki/FAQ?
