### ISSUE TITLE
problem in letv

### ISSUE THREAD

**Issue by cybmp3** [soimort/you-get#964]
you-get --debug  'http://www.le.com/ptv/vplay/24814542.html'
Current Video Supports:
	--format 1000 <URL>
	--format 1300 <URL>
	--format 350 <URL>
	--format 720p <URL>
Site:       Le.com
Title:      伪娘Kiwebaby直播穿衣变装 转身后亮了！
Type:       MPEG-4 video (video/mp4)
Size:       13.95 MiB (14631664 Bytes)

Downloading 伪娘Kiwebaby直播穿衣变装 转身后亮了！.mp4 ...
 3.3% (  0.5/ 14.0MB) ├█████───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤[1/7]   26 7.7% (  1.1/ 14.0MB) ├███████████─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤[2/717.1% (  2.4/ 14.0MB) ├██████████████████████████────────────────────────────────────────────────────────────────────────────────────────────────────────────────────34.2% (  4.8/ 14.0MB) ├████████████████████████████████████████████████████────────────────────────────────────────────────────────────────57.8% (  8.1/ 14.0MB) ├████████████████████████████████████████████████████████████████████████████████████82.3% ( 11.5/ 14.0MB) ├████████████████████████████████████████████████████████████████████████████████████ 100% ( 14.0/ 14.0MB) ├████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[7/7]  126 MB/s
Merging video parts...
./伪娘Kiwebaby直播穿衣变装 转身后亮了！[00].mp4
you-get: version 0.4.324, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/24814542.html']
Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1257, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1178, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1026, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1250, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/extractors/le.py", line 137, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/extractors/le.py", line 98, in letv_download_by_vid
    download_urls(urls, title, ext, size, output_dir=output_dir, merge=merge)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 761, in download_urls
    concat_mp4(parts, output_filepath)
  File "/usr/lib/python3.4/site-packages/you_get/processor/join_mp4.py", line 914, in concat_mp4
    merge_mp4s(mp4s, output)
  File "/usr/lib/python3.4/site-packages/you_get/processor/join_mp4.py", line 876, in merge_mp4s
    mp4s = list(map(read_mp4, ins))
  File "/usr/lib/python3.4/site-packages/you_get/processor/join_mp4.py", line 717, in read_mp4
    atoms = parse_atoms(stream)
  File "/usr/lib/python3.4/site-packages/you_get/processor/join_mp4.py", line 708, in parse_atoms
    atom = read_atom(stream)
  File "/usr/lib/python3.4/site-packages/you_get/processor/join_mp4.py", line 700, in read_atom
    raise NotImplementedError('%s: %d' % (type, left))
NotImplementedError: b'\x00\x00\xb0\r': 1195376648

**Comment by soimort** [comment]
Please install FFmpeg, or use the `you-get-win32-full.7z` from downloads.

**Comment by cybmp3** [comment]
Thx
U are so good.
Thank you for your being so quickly reply!

**Comment by cybmp3** [comment]
you-get: ['http://www.letv.com/ptv/vplay/24803008.html', '--json']
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1223, in url_to_module
    assert video_host and video_url
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib64/python3.4/http/client.py", line 1223, in connect
    super().connect()
  File "/usr/lib64/python3.4/http/client.py", line 834, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python3.4/socket.py", line 512, in create_connection
    raise err
  File "/usr/lib64/python3.4/socket.py", line 503, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1257, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1178, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1026, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1249, in any_download
    m, url = url_to_module(url)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1225, in url_to_module
    url = google_search(url)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1206, in google_search
    page = get_content(url, headers=fake_headers)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 304, in get_content
    response = request.urlopen(req)
  File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib64/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

**Comment by cybmp3** [comment]
Maybe have a  problem in json.......
