### ISSUE TITLE
problem about json

### ISSUE THREAD

**Issue by cybmp3** [soimort/you-get#967]
if i execute you-get -u http://www.letv.com/ptv/vplay/24803008.html
It's ok.
But wen I execute you-get -u http://www.letv.com/ptv/vplay/24803008.html --json
you-get: ['http://www.letv.com/ptv/vplay/24803008.html', '--json']
Traceback (most recent call last):
File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1223, in url_to_module
assert video_host and video_url
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib64/python3.4/urllib/request.py", line 1182, in do_open
h.request(req.get_method(), req.selector, req.data, headers)
File "/usr/lib64/python3.4/http/client.py", line 1088, in request
self._send_request(method, url, body, headers)
File "/usr/lib64/python3.4/http/client.py", line 1126, in _send_request
self.endheaders(body)
File "/usr/lib64/python3.4/http/client.py", line 1084, in endheaders
self._send_output(message_body)
File "/usr/lib64/python3.4/http/client.py", line 922, in _send_output
self.send(msg)
File "/usr/lib64/python3.4/http/client.py", line 857, in send
self.connect()
File "/usr/lib64/python3.4/http/client.py", line 1223, in connect
super().connect()
File "/usr/lib64/python3.4/http/client.py", line 834, in connect
self.timeout, self.source_address)
File "/usr/lib64/python3.4/socket.py", line 512, in create_connection
raise err
File "/usr/lib64/python3.4/socket.py", line 503, in create_connection
sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/you-get", line 11, in
sys.exit(main())
File "/usr/lib/python3.4/site-packages/you_get/main.py", line 92, in main
main(*kwargs)
File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1257, in main
script_main('you-get', any_download, any_download_playlist, *kwargs)
File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1178, in script_main
download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1026, in download_main
download(url, *kwargs)
File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1249, in any_download
m, url = url_to_module(url)
File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1225, in url_to_module
url = google_search(url)
File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1206, in google_search
page = get_content(url, headers=fake_headers)
File "/usr/lib/python3.4/site-packages/you_get/common.py", line 304, in get_content
response = request.urlopen(req)
File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib64/python3.4/urllib/request.py", line 463, in open
response = self._open(req, data)
File "/usr/lib64/python3.4/urllib/request.py", line 481, in _open
'_open', req)
File "/usr/lib64/python3.4/urllib/request.py", line 441, in _call_chain
result = func(args)
File "/usr/lib64/python3.4/urllib/request.py", line 1225, in https_open
context=self._context, check_hostname=self._check_hostname)
File "/usr/lib64/python3.4/urllib/request.py", line 1184, in do_open
raise URLError(err)
urllib.error.URLError:

**Comment by cnbeining** [comment]
Thanks for your report.

Are you sure that your Internet connection is reliable and stable?

**Comment by cybmp3** [comment]
I‘m not sure.Because my ip address is belongs to a idc.Mayebe letv has recongize it.

**Comment by cybmp3** [comment]
# you-get -u --debug http://www.le.com/ptv/vplay/24814330.html --json
Current Video Supports:
	--format 720p <URL>
	--format 350 <URL>
	--format 1300 <URL>
	--format 1000 <URL>
Site:       Le.com
Title:      Type:       MPEG-4 video (video/mp4)
Size:       14.52 MiB (15221044 Bytes)

Real URLs:
http://183.131.245.38:80/208/41/107/letv-uts/14/ver_00_22-1030576783-avc-1424694-aac-96000-76840-14706111-3a18c2733cb4e3381c0383c0db978230-1457318320086_mp4/ver_00_22_0_0_1_79712_0_0.ts?mltag=1&platid=1&splatid=101&playid=0&geo=CN-11-140-1&tag=letv&ch=&p1=&p2=&p3=&tss=ios&b=1529&bf=20&nlh=3072&path=&sign=letv&proxy=3079193366,3078830692,1778917275&uuid=&ntm=1457520600&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&its=0&nkey2=dfa43e1224764c74b7af531ff67951e8&uid=1944574256.rp&qos=3&enckit=&m3v=1&token=&vid=&liveid=&station=&app_name=&app_ver=&fcheck=0&pantm=&panuid=&pantoken=&cips=115.231.217.48
http://183.131.245.38:80/208/41/107/letv-uts/14/ver_00_22-1030576783-avc-1424694-aac-96000-76840-14706111-3a18c2733cb4e3381c0383c0db978230-1457318320086_mp4/ver_00_22_1_1_1_231428_79712_0.ts?mltag=1&platid=1&splatid=101&playid=0&geo=CN-11-140-1&tag=letv&ch=&p1=&p2=&p3=&tss=ios&b=1529&bf=20&nlh=3072&path=&sign=letv&proxy=3079193366,3078830692,1778917275&uuid=&ntm=1457520600&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&its=0&nkey2=dfa43e1224764c74b7af531ff67951e8&uid=1944574256.rp&qos=3&enckit=&m3v=1&token=&vid=&liveid=&station=&app_name=&app_ver=&fcheck=0&pantm=&panuid=&pantoken=&cips=115.231.217.48
http://183.131.245.38:80/208/41/107/letv-uts/14/ver_00_22-1030576783-avc-1424694-aac-96000-76840-14706111-3a18c2733cb4e3381c0383c0db978230-1457318320086_mp4/ver_00_22_2_2_1_200972_311140_0.ts?mltag=1&platid=1&splatid=101&playid=0&geo=CN-11-140-1&tag=letv&ch=&p1=&p2=&p3=&tss=ios&b=1529&bf=20&nlh=3072&path=&sign=letv&proxy=3079193366,3078830692,1778917275&uuid=&ntm=1457520600&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&its=0&nkey2=dfa43e1224764c74b7af531ff67951e8&uid=1944574256.rp&qos=3&enckit=&m3v=1&token=&vid=&liveid=&station=&app_name=&app_ver=&fcheck=0&pantm=&panuid=&pantoken=&cips=115.231.217.48
http://183.131.245.38:80/208/41/107/letv-uts/14/ver_00_22-1030576783-avc-1424694-aac-96000-76840-14706111-3a18c2733cb4e3381c0383c0db978230-1457318320086_mp4/ver_00_22_3_3_1_715152_512112_0.ts?mltag=1&platid=1&splatid=101&playid=0&geo=CN-11-140-1&tag=letv&ch=&p1=&p2=&p3=&tss=ios&b=1529&bf=20&nlh=3072&path=&sign=letv&proxy=3079193366,3078830692,1778917275&uuid=&ntm=1457520600&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&its=0&nkey2=dfa43e1224764c74b7af531ff67951e8&uid=1944574256.rp&qos=3&enckit=&m3v=1&token=&vid=&liveid=&station=&app_name=&app_ver=&fcheck=0&pantm=&panuid=&pantoken=&cips=115.231.217.48
http://183.131.245.38:80/208/41/107/letv-uts/14/ver_00_22-1030576783-avc-1424694-aac-96000-76840-14706111-3a18c2733cb4e3381c0383c0db978230-1457318320086_mp4/ver_00_22_4_4_2_3105572_1227264_0.ts?mltag=1&platid=1&splatid=101&playid=0&geo=CN-11-140-1&tag=letv&ch=&p1=&p2=&p3=&tss=ios&b=1529&bf=20&nlh=3072&path=&sign=letv&proxy=3079193366,3078830692,1778917275&uuid=&ntm=1457520600&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&its=0&nkey2=dfa43e1224764c74b7af531ff67951e8&uid=1944574256.rp&qos=3&enckit=&m3v=1&token=&vid=&liveid=&station=&app_name=&app_ver=&fcheck=0&pantm=&panuid=&pantoken=&cips=115.231.217.48
http://183.131.245.38:80/208/41/107/letv-uts/14/ver_00_22-1030576783-avc-1424694-aac-96000-76840-14706111-3a18c2733cb4e3381c0383c0db978230-1457318320086_mp4/ver_00_22_5_6_2_2615456_4332836_0.ts?mltag=1&platid=1&splatid=101&playid=0&geo=CN-11-140-1&tag=letv&ch=&p1=&p2=&p3=&tss=ios&b=1529&bf=20&nlh=3072&path=&sign=letv&proxy=3079193366,3078830692,1778917275&uuid=&ntm=1457520600&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&its=0&nkey2=dfa43e1224764c74b7af531ff67951e8&uid=1944574256.rp&qos=3&enckit=&m3v=1&token=&vid=&liveid=&station=&app_name=&app_ver=&fcheck=0&pantm=&panuid=&pantoken=&cips=115.231.217.48
http://183.131.245.38:80/208/41/107/letv-uts/14/ver_00_22-1030576783-avc-1424694-aac-96000-76840-14706111-3a18c2733cb4e3381c0383c0db978230-1457318320086_mp4/ver_00_22_6_8_2_3069664_6948292_0.ts?mltag=1&platid=1&splatid=101&playid=0&geo=CN-11-140-1&tag=letv&ch=&p1=&p2=&p3=&tss=ios&b=1529&bf=20&nlh=3072&path=&sign=letv&proxy=3079193366,3078830692,1778917275&uuid=&ntm=1457520600&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&its=0&nkey2=dfa43e1224764c74b7af531ff67951e8&uid=1944574256.rp&qos=3&enckit=&m3v=1&token=&vid=&liveid=&station=&app_name=&app_ver=&fcheck=0&pantm=&panuid=&pantoken=&cips=115.231.217.48
http://183.131.245.38:80/208/41/107/letv-uts/14/ver_00_22-1030576783-avc-1424694-aac-96000-76840-14706111-3a18c2733cb4e3381c0383c0db978230-1457318320086_mp4/ver_00_22_7_10_3_3875620_10017956_0.ts?mltag=1&platid=1&splatid=101&playid=0&geo=CN-11-140-1&tag=letv&ch=&p1=&p2=&p3=&tss=ios&b=1529&bf=20&nlh=3072&path=&sign=letv&proxy=3079193366,3078830692,1778917275&uuid=&ntm=1457520600&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&its=0&nkey2=dfa43e1224764c74b7af531ff67951e8&uid=1944574256.rp&qos=3&enckit=&m3v=1&token=&vid=&liveid=&station=&app_name=&app_ver=&fcheck=0&pantm=&panuid=&pantoken=&cips=115.231.217.48
http://183.131.245.38:80/208/41/107/letv-uts/14/ver_00_22-1030576783-avc-1424694-aac-96000-76840-14706111-3a18c2733cb4e3381c0383c0db978230-1457318320086_mp4/ver_00_22_8_13_1_1327468_13893576_0.ts?mltag=1&platid=1&splatid=101&playid=0&geo=CN-11-140-1&tag=letv&ch=&p1=&p2=&p3=&tss=ios&b=1529&bf=20&nlh=3072&path=&sign=letv&proxy=3079193366,3078830692,1778917275&uuid=&ntm=1457520600&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&its=0&nkey2=dfa43e1224764c74b7af531ff67951e8&uid=1944574256.rp&qos=3&enckit=&m3v=1&token=&vid=&liveid=&station=&app_name=&app_ver=&fcheck=0&pantm=&panuid=&pantoken=&cips=115.231.217.48
you-get: version 0.4.324, a tiny downloader that scrapes the web.
you-get: ['http://www.le.com/ptv/vplay/24814330.html', '--json']
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1223, in url_to_module
    assert video_host and video_url
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib64/python3.4/http/client.py", line 1223, in connect
    super().connect()
  File "/usr/lib64/python3.4/http/client.py", line 834, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python3.4/socket.py", line 512, in create_connection
    raise err
  File "/usr/lib64/python3.4/socket.py", line 503, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1257, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1178, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1026, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1249, in any_download
    m, url = url_to_module(url)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1225, in url_to_module
    url = google_search(url)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1206, in google_search
    page = get_content(url, headers=fake_headers)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 304, in get_content
    response = request.urlopen(req)
  File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib64/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

**Comment by soimort** [comment]
From https://docs.python.org/3/library/getopt.html:

> Unlike GNU getopt(), after a non-option argument, all further arguments are considered also non-options. This is similar to the way non-GNU Unix systems work.

That means you have to put `--json` **before** the URL, in this way:

```
    $ you-get --json -u http://www.le.com/ptv/vplay/24814330.html
```

**Comment by cybmp3** [comment]
THX U

**Comment by cybmp3** [comment]
thank you
