### ISSUE TITLE
优酷某些链接下载过程中出现403错误

### ISSUE THREAD

**Issue by yangaowei** [soimort/you-get#971]
python3 you-get --debug http://v.youku.com/v_show/id_XMjY3NjA1MjQw.html

you-get: version 0.4.324, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjY3NjA1MjQw.html']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "src/you_get/common.py", line 1257, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "src/you_get/common.py", line 1178, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "src/you_get/common.py", line 1026, in download_main
    download(url, **kwargs)
  File "src/you_get/common.py", line 1250, in any_download
    m.download(url, **kwargs)
  File "src/you_get/extractor.py", line 50, in download_by_url
    self.download(**kwargs)
  File "src/you_get/extractor.py", line 205, in download
    av=stream_id in self.dash_streams)
  File "src/you_get/common.py", line 721, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers)
  File "src/you_get/common.py", line 412, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "src/you_get/common.py", line 330, in url_size
    response = request.urlopen(url)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by soimort** [comment]
视频下载到第二分片时可复现。

```console
$ yg -d http://v.youku.com/v_show/id_XMjY3NjA1MjQw.html  
site:                优酷 (Youku)
title:               新乡获嘉国泰酒店唯美婚礼MV
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          60.4 MiB (63312115 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 新乡获嘉国泰酒店唯美婚礼MV.flv ...
83.6% ( 50.5/ 60.4MB) ├███████████████████████████████████████████████████████████████████████████████████████████████████████████─────────────────────┤[1/2]    3 MB/syou-get: version 0.4.326, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjY3NjA1MjQw.html']
Traceback (most recent call last):
  File "/home/soimort/Projects/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1257, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1178, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1026, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1250, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractor.py", line 50, in download_by_url
    self.download(**kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractor.py", line 205, in download
    av=stream_id in self.dash_streams)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 721, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 412, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 330, in url_size
    response = request.urlopen(url)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by linhua55** [comment]
➜  my-you-get git:(develop) ./you-get --debug http://v.youku.com/v_show/id_XMjY3NjA1MjQw.html
site:                优酷 (Youku)
title:               新乡获嘉国泰酒店唯美婚礼MV
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          60.4 MiB (63312115 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 新乡获嘉国泰酒店唯美婚礼MV.flv ...
 100% ( 60.4/ 60.4MB) ├████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[2/2]    2 MB/s
Merging video parts... Done.

不能复现   at  2016.3.10 23:54

**Comment by soimort** [comment]
现已无法复现。如有问题请再报告。

```console
$ yg -d http://v.youku.com/v_show/id_XMjY3NjA1MjQw.html
site:                优酷 (Youku)
title:               新乡获嘉国泰酒店唯美婚礼MV
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          60.4 MiB (63312115 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 新乡获嘉国泰酒店唯美婚礼MV.flv ...
 100% ( 60.4/ 60.4MB) ├████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[2/2]  330 MB/s
Merging video parts... Done.
```
