### ISSUE TITLE
逼站任意视频403

### ISSUE THREAD

**Issue by chinuno-usami** [soimort/you-get#973]
```
you-get: [Failed] DNS not resolved. Please change your DNS server settings.
you-get: version 0.4.324, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av4062471/']
Traceback (most recent call last):
  File "src\you_get\extractors\bilibili.py", line 104, in bilibili_download_by_c
id
  File "src\you_get\common.py", line 353, in url_info
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 471, in open
  File "urllib\request.py", line 581, in http_response
  File "urllib\request.py", line 509, in error
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 589, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1257, in main
  File "src\you_get\common.py", line 1178, in script_main
  File "src\you_get\common.py", line 1026, in download_main
  File "src\you_get\common.py", line 1250, in any_download
  File "src\you_get\extractors\bilibili.py", line 150, in bilibili_download
  File "src\you_get\extractors\bilibili.py", line 107, in bilibili_download_by_c
id
  File "src\you_get\util\log.py", line 98, in wtf
NameError: name 'exit' is not defined
you-get returned -1
```
试了音乐区，番剧和游戏区
带不带cookie都一样，win7和ubuntu都是这样的问题

**Comment by soimort** [comment]
@cnbeining 是否API key的问题？

**Comment by nuomi1** [comment]
@soimort 试了几个，不是提示 DNS 出错，就是 0MiB。

**Comment by soimort** [comment]
> @soimort 试了几个，不是提示 DNS 出错，就是 0MiB。

我觉得应该是 @cnbeining 的key被封了。

待求证。

**Comment by soimort** [comment]
不等了，先换个能用的。

**Comment by cnbeining** [comment]
我觉得逼站要封第三方了。
