### ISSUE TITLE
最新的0.4.330版，爱奇艺解析有问题

### ISSUE THREAD

**Issue by mengmo** [soimort/you-get#985]
Python 我用的是官方的 python-3.5.1-embed-amd64.zip，you-get 下的这儿的https://github.com/soimort/you-get/archive/v0.4.330.zip ，之前一直用 releases 里打包好的exe

you-get --debug http://www.iqiyi.com/v_19rrkvzj08.html
you-get: [error] outdated iQIYI key
you-get: is your you-get up-to-date?
you-get: version 0.4.324, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrkvzj08.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "src\you_get\common.py", line 1257, in main
    m, url = url_to_module(url)
  File "src\you_get\common.py", line 1178, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "src\you_get\common.py", line 1026, in download_main
    download(url, **kwargs)
  File "src\you_get\common.py", line 1250, in any_download
    location = res.getheader('location')
  File "src\you_get\extractor.py", line 39, in download_by_url
    self.prepare(**kwargs)
  File "src\you_get\extractors\iqiyi.py", line 146, in prepare
    log.wtf("is your you-get up-to-date?")
  File "src\you_get\util\log.py", line 98, in wtf
    exit(exit_code)
NameError: name 'exit' is not defined
you-get returned -1

**Comment by cnbeining** [comment]
不能复现。你git clone下？

```
 python3 you-get --debug http://www.iqiyi.com/v_19rrkvzj08.html
site:                爱奇艺 (Iqiyi)
title:               龙珠超 第34集
stream:
    - format:        suprt-high
      container:     f4v
      video-profile: 超高清
      size:          111.8 MiB (117248174 bytes)
    # download-with: you-get --format=suprt-high [URL]

Downloading 龙珠超 第34集.f4v ...
```

**Comment by mengmo** [comment]
爱奇艺的这个问题跟 B站那边的问题一样
(⊙o⊙)…
