### ISSUE TITLE
[Failed] 网易云音乐

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#994]
> Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] <del>You can actually watch the video in your browser or mobile application, but not download them with `you-get`.</del> _(Not applicable)_
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

> Run the command with the `--debug` option, and paste the full output inside the fences:

```console
$ you-get -di 'http://music.163.com/song?id=188204'
you-get: version 0.4.347, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/song?id=188204']
Traceback (most recent call last):
  File "/home/soimort/Projects/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1266, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1179, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1027, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1259, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractors/netease.py", line 120, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractors/netease.py", line 66, in netease_cloud_music_download
    netease_song_download(j["songs"][0], output_dir=output_dir, info_only=info_only)
  File "/home/soimort/Projects/you-get/src/you_get/extractors/netease.py", line 97, in netease_song_download
    songNet = 'p' + song['mp3Url'].split('/')[2][1:]
AttributeError: 'NoneType' object has no attribute 'split'
```

> If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

It seems their API doesn't return `mp3Url` for some audio links. Anyone got the same issue?

**Comment by xyuanmu** [comment]
这个问题我这边没有遇到，可以正常解析：
```
请输入命令/地址: -di http://music.163.com/song?id=188204

Site:       163.com
Title:      16. 沉默是金
Type:       MP3 (audio/mpeg)
Size:       9.43 MiB (9882886 Bytes)
```

**Comment by soimort** [comment]
@soimort-bot test this for me: http://music.163.com/song?id=188204

**Comment by soimort** [comment]
看起来是地区限制的问题。

**Comment by emiruyunka** [comment]
I encounter the same problem. It is very annoying.

```
>you-get -di http://music.163.com/song?id=188204
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=188204&ids=[188204]&csrf_token=
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/song?id=188204']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1328, in main
  File "src\you_get\common.py", line 1241, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1321, in any_download
  File "src\you_get\extractors\netease.py", line 129, in netease_download
  File "src\you_get\extractors\netease.py", line 66, in netease_cloud_music_download
  File "src\you_get\extractors\netease.py", line 106, in netease_song_download
AttributeError: 'NoneType' object has no attribute 'split'
you-get returned -1
```

The problem "AttributeError: 'NoneType' object has no attribute 'split'" seems to be limited to region-restricted songs (songs that are only available in China and Russia).

Using a Chinese proxy does **not always** solve the problem for me.

In this case, a proxy solves the problem:

```
>you-get --http-proxy 223.68.1.38:8000 http://music.163.com/song?id=188204
Site:       163.com
Title:      16. 沉默是金
Type:       MP3 (audio/mpeg)
Size:       9.43 MiB (9882886 Bytes)

Downloading 16. 沉默是金.mp3 ...
 100% (  9.4/  9.4MB) ├█████████████████████████████████████████┤[1/1]  235 kB/s

Saving 16. 沉默是金.lrc ...Done.
```

But for this song, a proxy does not solve the problem:

The song is region-restricted, so I get "AttributeError":

```
>you-get -di http://music.163.com/song?id=188204
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=188204&ids=[188204]&csrf_token=
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/song?id=188204']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1328, in main
  File "src\you_get\common.py", line 1241, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1321, in any_download
  File "src\you_get\extractors\netease.py", line 129, in netease_download
  File "src\you_get\extractors\netease.py", line 66, in netease_cloud_music_download
  File "src\you_get\extractors\netease.py", line 106, in netease_song_download
AttributeError: 'NoneType' object has no attribute 'split'
you-get returned -1
```

With a chinese proxy, the download still fails. Now I get Error 404:

```
>you-get -di --http-proxy 223.68.1.38:8000 http://music.163.com/song?id=27580979
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=27580979&ids=[27580979]&csrf_token=
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/song?id=27580979']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1328, in main
  File "src\you_get\common.py", line 1241, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1321, in any_download
  File "src\you_get\extractors\netease.py", line 129, in netease_download
  File "src\you_get\extractors\netease.py", line 66, in netease_cloud_music_download
  File "src\you_get\extractors\netease.py", line 116, in netease_song_download
  File "src\you_get\extractors\netease.py", line 119, in netease_download_common
  File "src\you_get\common.py", line 370, in url_info
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 471, in open
  File "urllib\request.py", line 581, in http_response
  File "urllib\request.py", line 509, in error
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 589, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
you-get returned -1
```




And one more thing:

This album is region-restricted: http://music.163.com/#/album?id=500838

Therefore, I cannot download any songs from it. I always get "AttributeError"

First song of album ... download fails: (AttributeError)

```
>you-get --debug http://music.163.com/song?id=5044435
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=5044435&ids=[5044435]&csrf_token=
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/song?id=5044435']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1328, in main
  File "src\you_get\common.py", line 1241, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1321, in any_download
  File "src\you_get\extractors\netease.py", line 129, in netease_download
  File "src\you_get\extractors\netease.py", line 66, in netease_cloud_music_download
  File "src\you_get\extractors\netease.py", line 106, in netease_song_download
AttributeError: 'NoneType' object has no attribute 'split'
you-get returned -1
```

Second song of album ... download fails: (AttributeError)

```
>you-get --debug http://music.163.com/song?id=5044436
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=5044436&ids=[5044436]&csrf_token=
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/song?id=5044436']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1328, in main
  File "src\you_get\common.py", line 1241, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1321, in any_download
  File "src\you_get\extractors\netease.py", line 129, in netease_download
  File "src\you_get\extractors\netease.py", line 66, in netease_cloud_music_download
  File "src\you_get\extractors\netease.py", line 106, in netease_song_download
AttributeError: 'NoneType' object has no attribute 'split'
you-get returned -1
```

Third song of album ... download fails: (AttributeError)

```
>you-get --debug http://music.163.com/song?id=5044437
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=5044437&ids=[5044437]&csrf_token=
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/song?id=5044437']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1328, in main
  File "src\you_get\common.py", line 1241, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1321, in any_download
  File "src\you_get\extractors\netease.py", line 129, in netease_download
  File "src\you_get\extractors\netease.py", line 66, in netease_cloud_music_download
  File "src\you_get\extractors\netease.py", line 106, in netease_song_download
AttributeError: 'NoneType' object has no attribute 'split'
you-get returned -1
```

However, I can download **the whole album** without errors:

```
>you-get -i http://music.163.com/#/album?id=500838
Site:       163.com
Title:      1. Opening Title
Type:       MP3 (audio/mpeg)
Size:       8.07 MiB (8459127 Bytes)

Site:       163.com
Title:      2. No Place Like London
Type:       MP3 (audio/mpeg)
Size:       12.69 MiB (13311647 Bytes)

Site:       163.com
Title:      3. The Worst Pies in London
Type:       MP3 (audio/mpeg)
Size:       5.5 MiB (5766446 Bytes)

Site:       163.com
Title:      4. Poor Thing
Type:       MP3 (audio/mpeg)
Size:       7.25 MiB (7598125 Bytes)

Site:       163.com
Title:      5. My Friends
Type:       MP3 (audio/mpeg)
Size:       8.74 MiB (9161292 Bytes)

Site:       163.com
Title:      6. Green Finch & Linnett Bird
Type:       MP3 (audio/mpeg)
Size:       5.23 MiB (5481193 Bytes)

Site:       163.com
Title:      7. Alms Alms
Type:       MP3 (audio/mpeg)
Size:       2.94 MiB (3082074 Bytes)

Site:       163.com
Title:      8. Johanna
Type:       MP3 (audio/mpeg)
Size:       4.51 MiB (4727784 Bytes)

Site:       163.com
Title:      9. Pirelli s Miracle Elixir
Type:       MP3 (audio/mpeg)
Size:       4.62 MiB (4842757 Bytes)

Site:       163.com
Title:      10. The Contest
Type:       MP3 (audio/mpeg)
Size:       8.33 MiB (8739155 Bytes)

Site:       163.com
Title:      11. Wait
Type:       MP3 (audio/mpeg)
Size:       6.09 MiB (6384986 Bytes)

Site:       163.com
Title:      12. Ladies and Their Sensitivities
Type:       MP3 (audio/mpeg)
Size:       3.2 MiB (3355879 Bytes)

Site:       163.com
Title:      13. Pretty Women
Type:       MP3 (audio/mpeg)
Size:       10.24 MiB (10734912 Bytes)

Site:       163.com
Title:      14. Epiphany
Type:       MP3 (audio/mpeg)
Size:       7.54 MiB (7907410 Bytes)

Site:       163.com
Title:      15. A Little Priest
Type:       MP3 (audio/mpeg)
Size:       12.05 MiB (12633498 Bytes)

Site:       163.com
Title:      16. Johanna
Type:       MP3 (audio/mpeg)
Size:       4.51 MiB (4727784 Bytes)

Site:       163.com
Title:      17. God, That s Good!
Type:       MP3 (audio/mpeg)
Size:       6.4 MiB (6708930 Bytes)

Site:       163.com
Title:      18. By The Sea
Type:       MP3 (audio/mpeg)
Size:       5.28 MiB (5540721 Bytes)

Site:       163.com
Title:      19. Not While I m Around
Type:       MP3 (audio/mpeg)
Size:       9.64 MiB (10104855 Bytes)

Site:       163.com
Title:      20. Final Scene
Type:       MP3 (audio/mpeg)
Size:       23.75 MiB (24907906 Bytes)
```

I hope this information is helpful.

**Comment by HongxuChen** [comment]
I encountered an issue about netease music. 

``` bash
~/tools > you-get --version                                                                                                                                                          < 3:06 PM
you-get: version 0.4.536, a tiny downloader that scrapes the web.
~/tools > you-get -di 'http://music.163.com/#/song?id=36297568'                                                                                                                      < 3:09 PM
[DEBUG] get_content: http://music.163.com/api/song/detail/?id=36297568&ids=[36297568]&csrf_token=
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/song?id=36297568']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/netease.py", line 130, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/netease.py", line 67, in netease_cloud_music_download
    netease_song_download(j["songs"][0], output_dir=output_dir, info_only=info_only)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/netease.py", line 107, in netease_song_download
    songNet = 'p' + song['mp3Url'].split('/')[2][1:]
AttributeError: 'NoneType' object has no attribute 'split'
```

The problem also exists for downloading the playlist (you-get -di 'http://music.163.com/#/playlist?id=426832974') that contains this song.

**Comment by emiruyunka** [comment]
The song (http://music.163.com/#/song?id=36297568) it region restricted. See the screenshot below: the play button is greyed out when accessing it from outside China or Russia.

![untitled](https://cloud.githubusercontent.com/assets/19289477/18044208/f22c2dfa-6dcc-11e6-91a5-960fb2794c80.png)

For downloading region-restricted songs, you always get "AttributeError".

Try using a Chinese proxy (you-get --http-proxy XXX.XX.XX.X:XXXX http://music.163.com/#/song?id=36297568). Sometimes that solves the problem.

**Comment by HongxuChen** [comment]
@emiruyunka that may be part of the reason, but perhaps not exactly true since there are some grey songs that I can still download w/o proxy (http://music.163.com/#/song?id=5233649 for example; yes, w/ proxy I can download it).

Particularly I think you-get should handle some common errors (e.g., collect failed urls AND continue) rather than exits unexpectedly.
